FEX-Emu/FEX

- Source/Tests/IRLoader.cpp
Fixes a warning that slipped through
> Tests/IRLoader: Silence missing override warning

- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Debug/X86Tables.h
- unittests/ASM/H0F3A/pclmulqdq.asm
- unittests/ASM/VEX/vpclmulqdq.asm
Closes #1713 
`PCLMULQDQ` on x86 is very closely matched by one of AArch64's own carryless multiplication instructions (`PMULL`/`PMULL2`), albeit with just a tad less flexibility, but nothing that makes it unworkable.
This allows us to handle the x86 CLMUL instruction extension and enable the corresponding CPUID bit.
> OpcodeDispatcher: Handle CLMUL opcode extension

- External/FEXCore/Source/Interface/IR/IREmitter.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
- External/FEXCore/include/FEXCore/IR/IR.h
This is the start of the plan to move all such helpers to common functions, so that when semantics change we don't have to change all the optimisation passes manually.
> IR: add IsFragmentExit, IsBlockExit

- .github/workflows/ccpp.yml
- CMakeLists.txt
- Scripts/guest_test_runner.py
- unittests/CMakeLists.txt
- unittests/FEXLinuxTests/CMakeLists.txt
- unittests/FEXLinuxTests/Disabled_Tests
- unittests/FEXLinuxTests/Expected_Output
- unittests/FEXLinuxTests/Known_Failures
- unittests/FEXLinuxTests/tests/CMakeLists.txt
- unittests/FEXLinuxTests/tests/signal/pthread_cancel.cpp
- unittests/FEXLinuxTests/tests/signal/sigtest_no_defer.cpp
- unittests/FEXLinuxTests/tests/signal/sigtest_samask.cpp
- unittests/FEXLinuxTests/tests/signal/sigtest_sigmask.cpp
- unittests/FEXLinuxTests/tests/signal/synchronous-signal-block.cpp
- unittests/FEXLinuxTests/tests/signal/timer-sigev-thread.cpp
- unittests/FEXLinuxTests/tests/smc/smc-1-dynamic.cpp
- unittests/FEXLinuxTests/tests/smc/smc-1.inl
- unittests/FEXLinuxTests/tests/smc/smc-2.cpp
- unittests/FEXLinuxTests/tests/smc/smc-common.h
- unittests/FEXLinuxTests/tests/smc/smc-mt-1.cpp
- unittests/FEXLinuxTests/tests/smc/smc-mt-2.cpp
- unittests/FEXLinuxTests/tests/smc/smc-shared-1.cpp
- unittests/FEXLinuxTests/tests/smc/smc-shared-2.cpp
- unittests/POSIX/CMakeLists.txt
- unittests/gcc-target-tests-32/CMakeLists.txt
- unittests/gcc-target-tests-64/CMakeLists.txt
- unittests/gvisor-tests/CMakeLists.txt
FEXLinuxTests, derived from https://github.com/FEX-Emu/fex-assorted-tests-bins. I've only added a couple of signal tests, this is mostly to discuss on how we integrate with the rest of the build.
Unlike previous discussions, after experimenting a bit, I decided to include these as source and not binaries. They require `g++`/`g++-multilib` (x86-hosts) or `g++-x86-64-linux-gnu`/`g++-multilib-x86-64-linux-gnu` (non-x86 hosts) to build.
They are hidden behind a new cmake config, `BUILD_FEX_LINUX_TESTS`.
They are included via `ExternalProject_Add`, similar to `GuestThunks`. The same configuration vars are used for cross compiler selection.
Test themselves can define their compilation flags (optional, defaults to "-g O2") and a list of arguments to execute with. This is inspired from …
> unittests: Add FEXLinuxTests with a few tests

- Scripts/InstallFEX.py
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/FEXRootFSFetcher/XXFileHash.cpp
- docs/ReleaseProcess.md
The final tail of the file reading was incorrect, so our hashing was
"correct" but it was using stale data from the previous block size read.
Noticed this while wiring up the CI rootfs fetching since the hashing is
a lot simpler there.
Now instead of reading a tail, just attempt to read the full block size
and use the resulting data size instead. Confirmed it matches expected
results now.
In the process we are going to need to update hyperlinks and hashes
anyway, change the hash to XXH3 so it is faster to run.
> FEXRootFSFetcher: Update and fix xxhash file hashing

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Frontend.cpp
- External/FEXCore/Source/Interface/Core/Frontend.h
- External/FEXCore/Source/Interface/Core/LookupCache.cpp
- External/FEXCore/Source/Interface/Core/LookupCache.h
- unittests/FEXLinuxTests/tests/smc/smc-mt-2.cpp
During compilation, another thread might change the code while it is being compiled.
This modifies `frontend` & `compile` to add watches to pages before they are read for code from the frontend.
This guarantees that we never tear during compilation with parts of the block being stale.
`smc-mt-2` is also updated to do 100 iterations, as this is a race test and might pass some times
- Add iterations to `smc-mt-2`
- Split code page tracking from `LookupCache::AddBlockMapping` to `LookupCache::AddBlockExecutableRange`
- Remove code page tracking from `Context::AddBlockMapping`
- Add `std::function<void(uint64_t BlockEntry, uint64_t Start, uint64_t Length)> AddContainedCodePage` to `Frontend::DecodeInstructionsAtEntry`, call it once for every page encountered in this block, before any reads …
> SMC: Track code pages before frontend decode

- Source/Tests/LinuxSyscalls/LinuxAllocator.cpp
32-bit allocations were scanning for available pages by shifting by the
length of allocation. This is incorrect since large allocations would
then only scan through the region in very large chunks. Especially if
MAP_32BIT was present. Instead scan by page size to ensure better fit.
This fixes X-Plane 11.
Also ensure we don't try to munmap a range unless the result is
MAP_FAILED, noticed we were trying to munmap ~0ULL
> Linux: Fixes 32-bit allocator range scanning

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/include/FEXCore/Core/Context.h
- External/FEXCore/include/FEXCore/HLE/SyscallHandler.h
- Source/Tests/IRLoader.cpp
- Source/Tests/LinuxSyscalls/Syscalls.h
- Source/Tests/LinuxSyscalls/SyscallsSMCTracking.cpp
Adds an overload of `InvalidateGuestCodeRange` with `std::function<void(uint64_t start, uint64_t Length)> CallAfter` that guarantees no code is compiled between invalidation in and callback invocation. 
As shared code invalidation only needs to be interlocked around each mirror invalidation, and not around the entire invalidation, this is enough for `SyscallHandler::HandleSegfault` to work.
This is also needed for invalidations in #1760, that is where it was inspired from :)
> Invalidations: Move invalidation locks to Context

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
Keeps the include type consistent so that we don't have some files including external headers with both `<>` and `""`
> JITs: Qualify external includes consistently

- External/FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
Prevents an assertion from firing in vixl when they're enabled (destination needs to be a scalar)
> Arm64/EncryptionOps: Fix register specifiers in PCLMUL movs

- External/FEXCore/Source/CMakeLists.txt
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
- unittests/32Bit_ASM/CMakeLists.txt
- unittests/ASM/CMakeLists.txt
The endless generation is caused because the directory timestamps are newer than some of the generated files, and the directories are a build time dependency, creating a circular dependency that always forces regeneration.
I'm not a cmake expert, so not sure if there are any drawbacks with this solution.
> CMAKE: Create directories during configuration, fixes endless generation of unittests

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
`Context::CreateThread` would add a thread to the `Threads` vector before it has been fully constructed / initialized.
> Context: Fix CreateThread partial initialization issue

- External/FEXCore/Source/Interface/IR/AOTIR.cpp
This thing is allocated with malloc so it needs to be free'd with free.
This was poisoning asan runs.
> AOTIR: Fix RAData free

- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/GdbServer.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- External/FEXCore/Source/Interface/IR/Passes/DeadStoreElimination.cpp
- External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- External/FEXCore/Source/Interface/IR/Passes/StaticRegisterAllocationPass.cpp
- External/FEXCore/include/FEXCore/Core/CoreState.h
- Source/Tests/HarnessHelpers.h
- Source/Tests/TestHarnessRunner/HostRunner.cpp
- Source/Tools/Debugger/IMGui_I.cpp
Gets rid of some magic numbers and reduces the number of things that need to manually change (e.g. when supporting AVX and needing to increase the xmm size).
> CoreState: Add register size constants

- Source/Tests/LinuxSyscalls/FileManagement.cpp
`std::string::find` returns `std::string::npos` on fail, not `std::string::size` or `std::string::end`
> ThunksDB: Fix String.find error check

- Source/Common/Config.cpp
Wine will set the application name later in the boot process but we
can't defer application profile loading that late.
Once an application is loaded with wine or wine64, then check the next
argument for the application name instead.
This will allow us to have wine application application profiles.
eg: FEXInterpreter `which wine` $HOME/.wine/drive_c/GOG\ Games/Oblivion/Oblivion.exe
This will give us the application name of `Oblivion.exe`
Same with: FEXInterpreter `which wine` C:\\GOG\ Games\\Oblivion\\Oblivion.exe
> Common: Support application profiles for games launched through wine

- Source/Common/FDUtils.h
- Source/Tests/ELFCodeLoader2.h
- Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/Syscalls.h
- Source/Tests/LinuxSyscalls/SyscallsSMCTracking.cpp
std::filesystem::canonical is very heavyweight and walks the full path
to ensure that each folder in the path is not a symlink.
eg:
```
readlink("/proc", 0x7ffd5646e210, 1023)                                         = -1 EINVAL (Invalid argument)
readlink("/proc/self", "880556", 1023)                                          = 6
readlink("/proc/880556", 0x7ffd5646e210, 1023)                                  = -1 EINVAL (Invalid argument)
readlink("/proc/880556/fd", 0x7ffd5646e210, 1023)                               = -1 EINVAL (Invalid argument)
readlink("/proc/880556/fd/5", "/home/ryanh/.fex-emu/RootFS/Ubuntu_22_04/usr/lib/x86_64-linux-gnu/ld-linux-x86-6"..., 1023) = 86
readlink("/home", 0x7ffd5646e210, 1023)                                         = -1 EINVAL (Invalid argument) …
```
> Linux: Make `get_fdpath` more optimal

- Source/Tests/LinuxSyscalls/x32/Ioctl/drm.h
- Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp
DRM ioctls are taking advantage of the fact that any ioctl structure
that is passed in to the kernel smaller than the expected value will
zero out the remaining members of the structure.
Some more ioctls coming down the pipe will also abuse this, so we might
as well as get started with the v3d ioctl that requires it.
Due to how this works, the kernel knows how big an ioctl structure
should be and if the userspace passes in a smaller struct, it will
memset the remaining size to zero.
> Ioctl: Safely access v3d csd ioctl structure

- unittests/ThunkLibs/generator.cpp
Code generated by the thunkgen tests is always compiled with libclang, so this define is just empty (corresponding to the `__clang__` path in Guest.h.
> unittests/ThunkLibs: Fix test failures due to missing FEX_PACKFN_LINKAGE define

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.h
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/Arm64Relocations.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/JITCore.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/include/FEXCore/Core/CPUBackend.h
- External/FEXCore/include/FEXCore/Core/CoreState.h
- External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
This makes it the responsibility of the dispatcher to generate GDB checks and interpreter trampolines, unifies the dispatcher between interpreter and jits.
Reworked a lot of minor inconveniences along the way as well as did some small cleanups.
#1783
> Backends: Unified dispatch, interface rework, cleanups

- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
Can't use the dispatcher one if > 1 threads want to use it. Quick workaround using a thread_local.
> Dispatchers: Use thread local emitters for backend callbacks

- Source/Tests/LinuxSyscalls/Syscalls.cpp
- Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tests/LinuxSyscalls/Syscalls/Thread.h
- Source/Tests/LinuxSyscalls/x32/Thread.cpp
- Source/Tests/LinuxSyscalls/x64/Thread.cpp
We weren't adjusting the guest stack size when using clone3.
If the clone comes from CLONE3 then we need to offset the RSP by the
provided stack size.
This also translates to fork/vfork through clone, so make sure to adjust
stack in that case as well.
Fixes Ender Lilies crashing with Ubuntu 22.04 rootfs
> Linux: Fixes for clone3 stack size

- Source/Common/FDUtils.h
Our `get_fdpath` was broken and would include junk data after the filename, as `readlinkat` does not null terminate,it returns length instead.
> FDUtils: Fix get_fdpath

- CMakeLists.txt
- External/FEXCore/Source/CMakeLists.txt
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Context/Context.cpp
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
- External/FEXCore/Source/Interface/GDBJIT/GDBJIT.cpp
- External/FEXCore/Source/Interface/GDBJIT/GDBJIT.h
- External/FEXCore/Source/Interface/IR/AOTIR.cpp
- External/FEXCore/Source/Interface/IR/AOTIR.h
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Debug/GDBReaderInterface.h
- External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
- External/FEXCore/include/FEXCore/HLE/SourcecodeResolver.h
- External/FEXCore/include/FEXCore/HLE/SyscallHandler.h
- Source/Linux/Utils/ELFParser.h
- Source/Tests/LinuxSyscalls/Syscalls.cpp
- Source/Tests/LinuxSyscalls/Syscalls.h
- Source/Tests/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/CMakeLists.txt
- Source/Tools/FEXGDBReader/CMakeLists.txt
- Source/Tools/FEXGDBReader/FEXGDBReader.cpp
The question no one asked: If gdb stub is too much in fex, what about fex stub in gdb?
This is a very-quick-hack-and-slash prototype to get some feedback. With a small set of features, gdb could become /much/ more welcoming to us. I'll ponder on what that means and think about talking with upstream.
Even as is, the results are very encouraging. Looks like long-term, we'd have to generate faux elfs or work with upstream for an improved interface.
Uses the gdb jit interface to register guest asm and guest source. Uses `x86-....-objdump -SC` to generate mixed asm / source 'source' files. Places them in `~/.fex-emu/fexsrc/fileid.fexsrc`.
Can be slow during objdump, parsing or with many symbols.
See https://github.com/FEX-Emu/fex-assorted-tests-bins/tree/main/src/gdb-jit#gdb-jit-interface-test …
> gdb: jit integration

- Source/Common/FEXServerClient.cpp
- Source/Common/FEXServerClient.h
- Source/Tools/FEXServer/ArgumentLoader.cpp
- Source/Tools/FEXServer/ArgumentLoader.h
- Source/Tools/FEXServer/Main.cpp
- Source/Tools/FEXServer/ProcessPipe.cpp
It can be useful to know in tooling when the current active FEXServer
has exited.
Two things can happen when this command is run.
No FEXServer is active, returns immediately.
A FEXServer is active, we query for a pidfd from the active server, then
we wait until it exits.
Both instances of this is valid to use.
> FEXServer: Adds -w option for waiting on current FEXServer

- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
Workaround for vixl needing a valid pointer on init, even if not used.
Fixes #1810
> Dispatcher/Arm64: Fix vixl assert

- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/include/FEXCore/Config/Config.h
- Source/Common/FEXServerClient.cpp
pressure-vessel overrides our rootfs when it does a pivot_root.
Since we are still communicating to the FEXServer we were pulling the
configured rootfs.
Instead check if we are in pressure vessel and avoid doing that.
This fixes FEX running under pressure-vessel.
(There may be some implications to this down the road with code caching
but let's worry about that later)
> FEXServerClient: When running under pressure-vessel don't use FEXServer rootfs

- unittests/POSIX/Disabled_Tests
- unittests/POSIX/Known_Failures
Interpreter is flakey here, likely due to some race, but is periodically
fails and makes CI red.
> unittests: Disable known flake in posix tests

- Scripts/ClassifyCPU.py
- unittests/32Bit_ASM/CMakeLists.txt
- unittests/ASM/CMakeLists.txt
Instead of relying on runner features, classify based on CPU features.
This fixes an annoying issue where if running unit tests locally without
it set then you get an unexpected failure.
Fixes #1807
> unittests: Classify CPU based on CPU features

- Scripts/CheckBinfmtNotInstall.sh
- Source/Tests/CMakeLists.txt
Check for qemu and box binfmt_misc file conflicts before the
`binfmt_misc` install command.
This ensures if you're building from source that you won't inadvertently
install conflicting binfmt_misc files, breaking program execution.
> CMake: Check for binfmt_misc conflicts before install

- Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp
Oops. Used the incorrect ioctl for this one. Copy and paste fail.
> Ioctl32: Fix DRM_IOCTL_WAIT_VBLANK

- Source/Tools/FEXServer/ProcessPipe.cpp
- Source/Tools/FEXServer/SquashFS.cpp
Attach the CLOEXEC flag on each of the FDs/Sockets we open.
> FEXServer: Stop leaking FDs to subprocesses

- Data/ThunksDB.json
- External/FEXCore/include/FEXCore/Common/Paths.h
- Source/Tests/LinuxSyscalls/FileManagement.cpp
Since we have switched over to thunking the vulkan loader, behaviour has
changed here and we need to thunk this library.
While a bit unsafe to thunk arbitrary libraries, we know this one is
safe to thunk.
Fixes thunking Vulkan on steam games which have been broken since
switching over to vulkan loader thunking.
In the future this may become unnecessary but it is required for now.
> Thunks: Adds libvulkan steam pinned library thunking support

- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
Dota Underlords hit this when querying Vulkan two different symbols (vkGetPhysicalDeviceFeatures2/vkGetPhysicalDeviceFeatures2KHR) that resolve to the same function. Ignoring the error in that specific case is safe, since the linked guest functions have the same implementation.
Ideally, we'll make the target guest wrappers unique by-signature to avoid this conflict. Then we can treat the error as fatal again.
> Thunks: Soften error condition to be non-fatal

- ThunkLibs/libvulkan/Guest.cpp
The Vulkan driver may support functions that are not listed in FEX's `libvulkan_interface.cpp` definitions. FEX will be unable to call those functions, however it's useful to allow the application to pass anyway since often these functions are just eagerly queried and then never used.
For Release builds, we return `nullptr` in case the application has a fallback code path. For Debug builds, a function is injected that fatally errors when called.
> Vulkan: Handle queries for unknown functions more gracefully

- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
When some SRA code was being shuffled around, this config variable was
never being set. This caused the guest signal handlers to never expect
SRA to be enabled.
Moves the Dispatcher config object to the actual dispatcher rather than
having it in the arch specific dispatcher class. Then have the signal
delegator check the config directly instead of having this secondary
config value.
Fixes vc_redist_x64 and vc_redist_x86. Probably also fixes a bunch of
other random Proton/Wine things that rely on signal long jump.
> Dispatcher: Fix SRA enabled check in signal delegator handlers

- External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/F80Ops.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/FlagOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/MoveOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
Converts the opaque args array usage over to the given IR argument names where applicable. Brings the interpreter in sync with the ARM JIT
I made these changes a while ago and I guess I forgot to actually make a PR for them (whoops!)
> Interpreter: Move argument names over to IR names

- Data/AppConfig/VC_redist.x64.exe.json
- Data/AppConfig/VC_redist.x86.exe.json
- Data/AppConfig/vcredist_x64.exe.json
- Data/AppConfig/vcredist_x86.exe.json
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
If an application is doing long jumps on exceptions then we need to
ensure that RIP is synchronized at least to block entry for some amount
of safety.
Due to our block linking which doesn't ensure that RIP is synchronized
on block entry, our exception handling wouldn't see a RIP change, thus
not going down the path that we jump to Dispatcher loop top on RIP
change.
Burn a couple of instructions on block entry to ensure that RIP
synchronized but only on config.
**Fixes Proton Experimental hangs when it is installing the VC runtimes.**
> FEXCore: Support synchronizing RIP on block entry through config

- External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/FlagOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MoveOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Now all of the existing CPU cores are consistent with each other
This also resolves a benign case where the wrong struct type was used in VRev64 (though no issues arose because layouts are the exact same).
> x86_64: Migrate args over to named IR arguments

- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/GdbServer.cpp
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
- External/FEXCore/Source/Interface/Core/HostFeatures.h
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- External/FEXCore/include/FEXCore/Core/CoreState.h
- External/FEXCore/include/FEXCore/Core/UContext.h
- unittests/IR/Correctness/FPRStoreTruncate.ir
Provides a minimal as possible set of changes to modify various bits of FEX to make it ready to start the implementation of AVX.
This essentially just expands the core state xmm registers and ensures that nothing breaks due to that.
Subsequent PRs will make use of the extended state/implement IR handling for it
> AVX initial groundwork

- unittests/CMakeLists.txt
- unittests/FEXLinuxTests/CMakeLists.txt
- unittests/FEXLinuxTests/tests-32/CMakeLists.txt
- unittests/FEXLinuxTests/tests-32/signal/into.cpp
This is a very basic test to check for overflow exception.
`into` instruction only exists on 32-bit, so it needs to not be built as
a 64-bit executable.
Fixes #1808
> unittests: Adds 32-bit into test 

- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/include/FEXCore/Config/Config.h
- Source/Common/Config.cpp
- Source/Tests/FEXBash.cpp
- Source/Tools/FEXGetConfig/Main.cpp
By default this file ends up in `/usr/share/fex-emu/Config.json`.
Some documentation here: https://wiki.fex-emu.org/index.php/Development:Configuration
> Config: Support a global configuration file

- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/Source/Interface/IR/IRDumper.cpp
- External/FEXCore/Source/Interface/IR/IRParser.cpp
- External/FEXCore/include/FEXCore/Core/CoreState.h
- External/FEXCore/include/FEXCore/IR/IR.h
- Source/Tests/IRLoader.cpp
- Source/Tests/TestHarnessRunner.cpp
- unittests/FEXLinuxTests/tests/signal/invalid_hlt.cpp
- unittests/FEXLinuxTests/tests/signal/invalid_int.cpp
- unittests/FEXLinuxTests/tests/signal/invalid_int1.cpp
- unittests/FEXLinuxTests/tests/signal/invalid_int3.cpp
- unittests/FEXLinuxTests/tests/signal/invalid_ud2.cpp
- unittests/IR/Basic/MemoryData.ir
- unittests/IR/Basic/Sbfe.ir
- unittests/IR/Basic/SetGPR.ir
- unittests/IR/Correctness/AddTruncate.ir
- unittests/IR/Correctness/FPRStoreTruncate.ir
- unittests/IR/Correctness/LeftShiftTruncate.ir
- unittests/IR/Correctness/SubTruncate.ir
x86 has six instructions that will fault on us that we mostly handled. A
few of these weren't being handled correctly.
One problem is that RIP needs to synchronize differently depending on
which fault instruction it is. Some instructions fault at the
instruction RIP, some at the instruction afterwards.
Additionally some of the metadata generated around the signal delegation
wasn't correct.
With behaviour of all of these instructions changed, it will now be
easier to switch over to non-faulting guest synchronous signals off of
these instructions. This doesn't go far enough to change that behaviour
yet.
I noticed this when looking at Elden Ring's weird faulting behaviour
with ud2 and `int 0x2d`. This made me investigate since I had a
suspicion that we weren't handling both cases correctly. …
> FEXCore: Fix-up edge case behaviour on faulting instructions 

- External/FEXCore/Scripts/json_ir_generator.py
- External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
Since the IR argument can be accessed directly by name, this is no longer needed as a shorthand.
Also results in a decently smaller generated file
> json_ir_generator: Remove Args() functions from IR structs

- Source/Tests/LinuxSyscalls/Syscalls.cpp
- Source/Tests/LinuxSyscalls/Syscalls.h
- Source/Tests/LinuxSyscalls/x32/Syscalls.cpp
- Source/Tests/LinuxSyscalls/x32/Syscalls.h
- Source/Tests/LinuxSyscalls/x64/Syscalls.cpp
- Source/Tests/LinuxSyscalls/x64/Syscalls.h
We were registering syscall handlers to the temporary working vectors for
both x86 and x86_64 regardless of which bitness we launched with.
We then only installed the syscall handlers depending on bitness.
This was burning a decent amount of time and some memory on
initialization. Instead just don't register syscall handlers on the
other bitness.
Also stop wasting memory, clear the syscall registration vector after
we've registered everything.
Saves about 28KB of memory per process.
> Linux: Only install syscall handlers for the arch we launched with

- External/FEXCore/Source/Utils/Telemetry.cpp
- External/FEXCore/include/FEXCore/Utils/Telemetry.h
- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Tests/FEXLoader.cpp
While we were getting the application name for the application layer, we
were failing to store the filename for telemetry.
Save the filename we get for application layers and store it for the
telemetry file.
Otherwise these were just alway ending up as wine or wine-preloader.
> Telemetry: Support executable names through wineserver

- Source/Tools/FEXRootFSFetcher/Main.cpp
Missed this since I tested the erofs path which only supports -a
> FEXRootFSFetcher: Actually wire up -a -x

- Source/Tools/CommonGUI/IMGui.h
- Source/Tools/FEXConfig/Main.cpp
Removes the "Load Default Options" menu option. This option was
confusing for new users and isn't necessary anymore.
Fixes the "Load Default" option so it actually populates the full
configuration layer in the face of partial configuration.
This is a /very/ common use case for new users that ran through
FEXRootFSFetcher, where the only configuration set is the RootFS.
The configuration would be visually confusing since the visual
representation for missing options wouldn't reflect their default
configuration state. "TSO Enabled" is an example where it would appear
disabled in the GUI, but it is default enabled.
Also fixes the issue that the default configuration window would just be
a 320x240 floating window in the center of the screen. This is due to
the window being a floating sub …
> FEXConfig: Some quality of life improvements

- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/FileManagement.h
- unittests/FEXLinuxTests/tests/fd/test_close_range.cpp
It's common for Linux applications that use close_range to pass in ~0 as
the last FD. This was causing FEX to spin from [2, ~0U] in this loop.
This would take /forever/ to run.
Change over to an ordered map and use the map's range searching and
ranged erase to more quickly remove these elements.
Fixes a hang that occurs with first time Steam setup in
steam-linux-runtime heavy application `steam-runtime-identify-library-abi`.
Thanks to @koss on Discord for discovering and reporting this issue.
> Linux: Fixes hang in close_range 

- External/FEXCore/Source/Common/JitSymbols.cpp
- External/FEXCore/Source/Common/JitSymbols.h
- External/FEXCore/Source/Interface/Core/Core.cpp
In most cases we aren't using JIT symbols but still creating the perf
map file.
Early check if we should generate the file or not, this way we stop
polluting the /tmp folder.
> JitSymbols: Only initialize perf map file if using

- Source/Tests/LinuxSyscalls/Syscalls.h
- Source/Tests/LinuxSyscalls/x32/Syscalls.h
- Source/Tests/LinuxSyscalls/x64/Syscalls.h
No interface changes, just throwing out unused code and shortening implementations.
> Cleanup syscalls headers

- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
These are always used inside the function via assignments.
> Arm64/JIT: Remove unnecessary [[maybe_unused]] attributes

- Source/Tools/FEXRootFSFetcher/Main.cpp
If the user doesn't have any of the tools necessary for handling FEX's
images then the tool would spuriously fail with `Couldn't parse rootfs definition URL.`
With zero indication as to why we removed images from the parsed json.
If the user has at least one of these tools installed then they won't
get this error message.
> FEXRootFSFetcher: Adds runtime checks for image mounting tools

- Source/Tests/FEXBash.cpp
Currently FEXBash only outputs `FEXBash>` which gives weird docker
vibes. This can confuse users since they no longer see what folder they
are in.
Change this so it still has the user and path exposed like a typical PS1
eg: `FEXBash-ryanh@ryanh-TR2:/mnt/Work/Work/work/FEXNew/Build>`
> FEXBash: Changes PS1 to hopefully help users

- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
A missed portion when readding the stp/ldp optimization. This corrects the spilling of SRA FPRs in guest signals
> Arm64Dispatcher: Amend memcpy in SpillSRA 

- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/libGL/libGL_Guest.cpp
- ThunkLibs/libX11/libX11_NativeGuest.cpp
Steam's gameoverlayrenderer.so relies on libX11 symbols to be available without actually loading that library directly. This works on an unthunked system since libGL.so depends on libGLX.so, which in turn pulls in libX11.so at load-time. This PR adds a fake libX11 dependency to the libGL-guest thunks to reproduce this behavior.
The linker is eager to throw out unused libraries from libGL's dependency list, so `libX11_NativeGuest.cpp` exports an arbitrary symbol (`XSetErrorHandler`) which libGL picks up in a dummy variable. That way, the linker considers libX11 to be actually "used" by libGL.
Instead of generating a fake `libX11.so`, just link against libraries from the RootFS. The linker fails to handle these, since transitive dependencies for `libX11.so` use absolute paths that don't …
> Thunks: Make GL guest thunks implicitly load libX11.so

- CMakeLists.txt
- Source/Tests/CMakeLists.txt
- Source/Tools/FEXGetConfig/CMakeLists.txt
- Source/Tools/FEXRootFSFetcher/CMakeLists.txt
- Source/Tools/FEXServer/CMakeLists.txt
Due to glibc issues around static applications doing dlopen this is a
fundamentally broken option and no longer supported by FEX.
Remove the option entirely as to not be confusing.
We kept this around initially for chroot support, but with our RootFS
mounting AArch64 folders inside the chroot this isn't necessary anymore.
> cmake: Remove the static-pie compilation option

- .gitmodules
- CMakeLists.txt
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
This will help compiling on older distros which are shipping older
Vulkan-Headers.
We need to catch newer Vulkan features earlier than what distros ship
since it is highly common that users will update their drivers through
means that make their drivers be newer.
For example to build on Ubuntu 20.04 we will support symbols much newer
than what that verison of the distro supports.
We could wrap all uses of newer features behind `#ifdef` checks, or
include the newest version of the loader that FEX itself supports.
The submodule is much cleaner and resolves the issue of drivers
supporting newer vulkan versions than libvulkan-dev.
Again super common with Nvidia blob users, kisak-ppa users, or people
updating mesa directly to be on the bleeding edge.
> Thunks: Use external Vulkan-Headers 

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/IR/IREmitter.cpp
- Source/Tests/IRLoader.cpp
Keeps the codebase up to date with the latest major version (we were previously on 8.1.1)
Changelog can be seen [here](https://github.com/fmtlib/fmt/releases/tag/9.0.0)
> Externals: Update fmt to 9.0.0

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Core/CoreState.h
Hopefully this resolves #1876.
More careful dance around block linking/unlinking and invalidations, trying to cover all possible situations.
> Synchronized Block Linking

- ThunkLibs/libGL/libGL_Guest.cpp
We can just have it return itself.
Unknown why some games do this, but it happens and is expected to work.
Needs #1895 merged first. First commit is from that.
> Thunks: Make glXGetProcAddress self-query work 

- CMakeLists.txt
Instead of just ThunksDB.
Unused currently but necessary to keep things running smooth.
> CMake: Support multiple json files in the root of Data/

- Source/Tests/CMakeLists.txt
This is currently unused and can just cause compilation issues.
Disable it until we start hooking up aggressive fuzzing tests.
> Disable UnitTestGenerator

- Data/AppConfig/CMakeLists.txt
Turns out cmake will cut the filename at the first period, not the last.
Fixes an issue if we have application names with multiple periods in it.
> AppConfig: Fix bug with filename

- .github/workflows/ccpp.yml
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
- ThunkLibs/libX11/libX11_Guest.cpp
- ThunkLibs/libX11/libX11_interface.cpp
- ThunkLibs/libXext/libXext_interface.cpp
- ThunkLibs/libasound/libasound_interface.cpp
To ensure that our thunks don't become horribly broken with our changes. Build them in CI.
Requires some tinkering because the 20.04 requirement, but otherwise works.
> CI: Build Thunks

- Source/Tests/LinuxSyscalls/Syscalls.cpp
- Source/Tests/LinuxSyscalls/Syscalls.h
- Source/Tests/LinuxSyscalls/x32/FD.cpp
- Source/Tests/LinuxSyscalls/x64/FD.cpp
- Source/Tests/LinuxSyscalls/x64/Types.h
Arm64 doesn't have the classic getdents syscall, only getdents64.
Old glibc versions (like 2.17) don't support getdents64
This fixes 64-bit `ls` with a centos 7 rootfs. Likely also fixes some other very
old applications.
Packing differences between 32-bit and 64-bit getdents means we need to
template this between the two types, otherwise it's quite similar.
No known applications rely on the 32-bit getdents but worked with test
applications.
> Linux: Emulate classic getdents syscall for x64 and x32

- External/FEXCore/Source/Interface/Config/Config.json.in
- Source/Common/FEXServerClient.cpp
This is necessary for the fexserver to function correctly when chrooting
in to our rootfs and doing things.
Requires independent rootfs script modifications which will come with
the next rootfs update.
Problem comes down to a chroot supporting multiple users, where our
typical use case is only one user. Bind the server file to a single
server for the entire chroot session regardless of users, solving this
problem inside the chroot.
Fixes apt-get inside of chroot, which runs as user _apt.
> FEXServer: Support socket path override

- External/FEXCore/CMakeLists.txt
While the default value of `git config core.abbrev` is `7` (used to truncate the commit hash in several git commands) and most people don't configure anything else, I happen to prefer when commits hashes stay valid for a while, so I changed that value to `20`.
Because of this, FEX fails to build in [`External/FEXCore/Source/Interface/Core/CPUID.cpp:961`](https://github.com/FEX-Emu/FEX/blob/a2f4f494a9cdfcfffdba52b35da7a1f9378e635c/External/FEXCore/Source/Interface/Core/CPUID.cpp#L961)
Let's be explicit in the git command about what minimum length of commit hash we expect.
---
Note that this is not a proper fix, but should work for enough years that we don't yet need to bother truncating these two variables at 31 chars, but technically any two random commits hashes could have 31 chars in …
> cmake: fix incorrect assumption about the value of git's core.abbrev

- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
This only fixes the compile error. Thunks aren't expected to be used
without jemalloc enabled.
> Thunks: Fix compile without jemalloc

- Source/Tests/CMakeLists.txt
> Termux: Add android-shmem library

- Source/Common/FDUtils.h
- Source/Tests/ELFCodeLoader2.h
- Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/SyscallsSMCTracking.cpp
Encountered this while running wine things.
Non-fatal so don't explode
> FDUtils: Don't make unknown get_fdpath fatal

- ThunkLibs/libX11/libX11_interface.cpp
Some of these were required to get thunking to work with Proton and
DXVK.
> Thunks/X11: Adds missing XLibint functions

- External/FEXCore/Source/Utils/Allocator.cpp
- External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
- External/FEXCore/include/FEXCore/Utils/Allocator.h
- Source/Tests/FEXLoader.cpp
This parses `/proc/self/maps` with a very tiny FSM, and allocates all unmapped regions.
This makes `/bin/true` run in < 10-15 msecs from 38-43 with #1842
- #1914
> Allocator: Simplify StealMemory, make it less chatty with kernel space

- ThunkLibs/libX11/libX11_Host.cpp
Found an issue with wine + DXVK + thunks where these were passing in
more than 7 arguments and crashing.
Create some assembly to support any size of variadic stack packing.
Only implemented for AArch64 for now.
> Thunks/X11: Support Variadic stack packing

- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/Source/Interface/Config/Config.json.in
- Source/Tests/FEXLoader.cpp
- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/FileManagement.h
Previously in order to enable thunks, we needed an independent
description file of which thunks to be enabled. This is nice for quickly
testing out new games by setting `FEX_THUNKCONFIG` environment variable.
For users that just want to enable thunks this is an unwieldy
indirection that doesn't make much sense at a glance.
Previously this meant you needed two files as an example:
```
ryanh@ubuntu-linux-20-04-desktop:~/.fex-emu$ cat thunks.json
{
"ThunksDB": {
"GL": 1,
"Vulkan": 1
}
}
ryanh@ubuntu-linux-20-04-desktop:~/.fex-emu$ cat AppConfig/EnderLiliesSteam-Linux-Shipping.json
{
"Config": {
"ThunkConfig":"~\/.fex-emu\/thunks.json"
}
}
```
Instead of this unwieldy redirection just support `ThunksDB` json
directly in the AppConfig.
```
ryanh@ubuntu-linux-20-04-desktop:~/.fex-emu$ cat …
```
> Thunks: Support direct thunk config in configuration files 

- Source/Tests/CMakeLists.txt
If we're not building tests then just don't build the IRLoader since it
won't get used.
> IRLoader/TestHarnessLoader: Don't build if not building tests

- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
Initial opening commit to begin bringing forward some ops to support SVE. Particularly the super trivial operations that allow us to get things up and running.
More to follow after this PR, since all of the necessary helper functions and other minor things will be in place.
> VectorOps: Extend VectorZero

- unittests/ThunkLibs/generator.cpp
tmpnam is considered insecure since it's vulnerable to TOCTOU issues (as generating the filename and creating the directory are done separately). This is not an issue for these tests, but replacing tmpnam is not any more complicated than silencing the warning.
> unittests/ThunkLibs: Fix warning about "dangerous" use of tmpnam

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends VectorImm to be capable of using SVE to handle 256-bit length vectors.
> VectorOps: Extend VectorImm

- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
Just a log that was missed during the previous fmt deprecation cleanup.
> x86_64/JIT: Resolve lingering fmt deprecation warning

- External/FEXCore/include/FEXCore/Core/UContext.h
- Source/Tests/TestHarnessRunner/HostRunner.cpp
Now we properly copy out the upper lanes instead of ignoring them.
> HostRunner: Handle upper YMM lanes in sigsegv handler

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends VectorImm to be capable of using SVE to handle 256-bit length vectors.
> VectorOps: Extend VMov

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Fairly trivial extending that allows SVE to be used to handle 256-bit vectors
> VectorOps: Extend VAnd/VBic/VOr/VXor

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
Extends how the SSAData block is allocated so that 256-bit operations can be implemented safely.
One other point to bring up is the preferred path forward to supporting those operations in the interpreter. We use `__uint128_t` fairly extensively, but there is no `__uint256_t` equivalent to translate over to.  Currently I was thinking of using an existing solution like [this project](https://github.com/calccrypto/uint256_t) that provides a uint256_t type, but wanted to hear other ideas if anyone had them.
> InterpreterOps: Extend SSAData size to accomodate 256-bit operations

- Source/Tools/FEXRootFSFetcher/Main.cpp
This can happen when the link goes down or internet blip.
> FEXRootFSFetcher: Fix crash if curl fails to download rootfs definition file

- .github/workflows/ccpp.yml
build folder doesn't exist on a freshly started runner.
Executing the rootfs fetch script doesn't care what the working
directory is. Doesn't need to be in `build/` which doesn't exist on a
fresh runner and will fail chdir.
> Github: Fix fresh runner rootfs checkout

- External/FEXCore/Source/Interface/Context/Context.cpp
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.h
- External/FEXCore/include/FEXCore/Core/Context.h
- External/FEXCore/include/FEXCore/IR/IR.h
- Source/Tests/CMakeLists.txt
- Source/Tests/ELFCodeLoader2.h
- Source/Tests/FEXLoader.cpp
- Source/Tests/VDSO_Emulation.cpp
- Source/Tests/VDSO_Emulation.h
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/libVDSO/libVDSO_Guest.cpp
- ThunkLibs/libVDSO/libVDSO_Guest.lds
- ThunkLibs/libVDSO/libVDSO_interface.cpp
- unittests/FEXLinuxTests/tests/vdso/vdso_test.cpp
VDSO is heavily abused by Proton games to the point it is showing up as
CPU time.
Implement a guest-facing only thunk library using the hardcoded VDSO
interface in Thunks.
If available this will always be loaded on application load and set the
auxv value to support it.
This requires a bit of special treatment as our first user of linker
scripts since the format of the ELF must be careful crafted to not break
applications trying to parse it.
This library exposes a handful of symbols:
- clock_gettime
- clock_getres
- gettimeofday
- time
- getcpu
- All previous with `__vdso_` prefix
- LINUX_2.6
All of these symbols get routed directly to the host architecture VDSO
interface if they exist.
AArch64 doesn't have getcpu or time VDSO.
In a microbench, VDSO improved bench times substantially …
> Thunks: Adds VDSO thunk library 

- CMakeLists.txt
- External/FEXCore/CMakeLists.txt
This has been seen in some build environments, forgot to commit this a while ago.
> CMake: Extend AArch64 check to include arm64

- Source/Tests/FEXLoader.cpp
- Source/Tools/FEXConfig/Main.cpp
Also in FEXLoader make sure to use `EraseSet` for these runtime options.
Fixes a bug where the config was being set to nothing, breaking the ThunksDB configuration option.
Makes it so the following json works again.
```
~/.fex-emu/AppConfig$ cat vulkaninfo.json
{
"ThunksDB": {
"GL": 1,
"Vulkan": 1
}
}
```
> FEXConfig: Ensure APP_CONFIG_NAME isn't stored in json

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Fairly trivial extending that allows SVE to be used to handle 256-bit vectors for VAdd/VSub IR opcodes
> VectorOps: Extend VAdd/VSub

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends these IR ops to be able to handle 256-bit vectors
> VectorOps: Extend VSQAdd/VSQSub/VUQAdd/VUQSub

- ThunkLibs/Generator/gen.cpp
- ThunkLibs/Generator/interface.h
*NOTE: This change is best viewed with whitespace changes ignored and with a git client that supports highlighting moved lines [see gitconfig's diff.colormoved]*
`ASTVisitor` is great for iterating over AST nodes by type, but most of our analysis is based on symbol names. For this task, a lookup in `DeclContexts` after parsing is complete is better suited. (We only use the `ASTVisitor` for discovering relevant namespaces now.)
Notably, instead of separately "visiting" the `fex_gen_config` template declaration and each of its specializations, this new approach allows us to process them all at once. That makes the processing logic more localized and eliminates the need to refetch namespace information.
> Move thunk generator logic from ASTVisitor to ASTFrontendAction

- ThunkLibs/Generator/CMakeLists.txt
- ThunkLibs/Generator/gen.cpp
Makes a few things easier to read, particularly when formatting hex numbers or arrays. The only drawback is that emitting `{`/`}` requires escaping, since those characters are used by the fmt syntax.
Good example:
```diff
-file << "{(uint8_t*)\"";
-for (auto c : sha256) {
-  file << "\\x" << std::hex << std::setw(2) << std::setfill('0') << +c << std::dec;
-}
-file << "\", (void(*)(void *))&fexfn_unpack_" << libname << "_" << function_name << "}, // " << libname << ":" << function_name << "\n";
+fmt::print(file, "  {{(uint8_t*)\"\\x{:02x}\", (void(*)(void *))&fexfn_unpack_{}_{}}}, // {}:{}\n",
+           fmt::join(sha256, "\\x"), libname, function_name, libname, function_name);
```
I only applied fmt formatting to the lines that clearly benefit from it. For lines that just concatenate …
> Thunks/gen: Use fmt for writing formatted output

- CMakeLists.txt
- External/FEXCore/Source/CMakeLists.txt
- FEXHeaderUtils/CMakeLists.txt
- FEXHeaderUtils/FEXHeaderUtils/Syscalls.h
- Source/Common/CMakeLists.txt
Noticed recently that `FEXServer -w` was broken and couldn't understand why. Turns out that FHU syscall handling was /always/ falling down the `#else` path in the handlers since cmake `add_definitions` follows folder scoping rules.
This means it was always returning -1, which was causing FEXServer's pidfd_open usage to always receive -1, which meant the sendmsg with FD was always failing, which meant the `FEXServer -w` would forever wait for a message that was never sent.
Converting the utility over to a target not only fixes definition scoping problems, but also makes the other paths actually work.
This found some compiling bugs and instead lets us define SYS_pidfd_open if it doesn't exist. Letting the kernel return the ENOSYS if it doesn't exist on that platform.
Main thing, fixes …
> FHU: Convert to a interface target

- unittests/FEXLinuxTests/tests-32/CMakeLists.txt
- unittests/FEXLinuxTests/tests/CMakeLists.txt
- unittests/FEXLinuxTests/tests/signal/pthread_cancel.cpp
- unittests/FEXLinuxTests/tests/signal/timer-sigev-thread.cpp
- unittests/FEXLinuxTests/tests/smc/smc-1-dynamic.cpp
- unittests/FEXLinuxTests/tests/smc/smc-mt-1.cpp
- unittests/FEXLinuxTests/tests/smc/smc-mt-2.cpp
- unittests/FEXLinuxTests/tests/smc/smc-shared-1.cpp
- unittests/FEXLinuxTests/tests/smc/smc-shared-2.cpp
Previously, a RegEx was ran over the test source to extract compile flags, which means there was a circular C++ Source <-> CMake dependency. Compile flags are just specified explicitly in CMakeLists.txt now. Combined with #1981 (which removes the `args` annotation), this eliminates the circular dependency.
The intent of these annotations was presumably to make it easier to adjust compile flags on a per-test basis, but doing this in the build system is actually much cleaner.
> FEXLinuxTests: Use the build system instead of setting up compile flags via source-code annotations

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
Provides equal support with the JITs (which do handle 256-bit operations for these IR ops)
> Interpreter: Handle 256-bit VAnd/VBic/VOr/VXor

- CMakeFiles/cmake_uninstall.cmake.in
- CMakeLists.txt
- Source/Tests/CMakeLists.txt
- ThunkLibs/GuestLibs/CMakeLists.txt
Following guidance from cmake's FAQ:
https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake
Due to some of the special handling that we do with installs, we need to do additional uninstall handling that the install manifest doesn't cover.
Specifically we need to add additional uninstall targets for:
- FEXInterpreter
- binfmt_misc
- guest_thunks (Doing its own uninstall target, so passthrough)
While it isn't generally advised to install and uninstall through source systems, this is something that users want to do all the time. This has been asked for a couple of times now.
Fixes #1592
> cmake: Adds uninstall target

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends the VUMinV IR opcode to handle 256-bit operations
> VectorOps: Handle 256-bit VUMinV

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends VURAvg to be able to handle 256-bit vector lengths
> VectorOps: Handle 256-bit VURAvg

- unittests/gvisor-tests/Disabled_Tests
- unittests/gvisor-tests/Known_Failures
This has a badly coded test that can hang forever. Our timeout kills it at 5 minutes, which causes it to not even fall down the flake path.
Just disable it outright because of the bad test.
> unittests: Disable gvisor pselect test

- Scripts/StructPackVerifier.py
Older clang fails to pull in these include paths when cross compiling. Add them manually.
> CI: Fixes struct verifier on Ubuntu 20.04

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
Gets rid of a few repeated definitions and allows the emitter itself to make use of these defines without causing a circular dependency on the JIT.
> Arm64: Centralize location for register defines

- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
- External/FEXCore/include/FEXCore/Core/CPUBackend.h
This will be necessary to handle spilling 256-bit vectors. Also centralizes the constant into one spot so that future modifications to slot sizes (if any), will only need to change the constant value.
> JITs: Expand max spill slot size to 32 bytes

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
SVE DUP instruction does sign extension on the incoming immediate, while ASIMD MOVI does zero extension.
If the immediate doesn't fit then move in to a GPR first and then DUP from GPR.
> Arm64: Fixes SVE VectorImm

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/IR/IR.json
These IR ops are redundant and mostly unused.
VDupElement does exactly what these operations were already doing and more closely matches what the hardware wants.
> IR: Removes SplatVector{2,4}

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
Adds in support for dealing with 256-bit vectors when AVX support is enabled.
> JITs: Handle spilling/filling 256-bit vectors

- unittests/FEXLinuxTests/Flake_Tests
Missed the 32-bit version of this test
> FEXLinuxTests: Adds missing pthread_cancel flake status

- ThunkLibs/libX11/libX11_interface.cpp
- ThunkLibs/libXext/libXext_interface.cpp
_XData32 and _XRead32 don't exist as real functions in 32-bit versions of these libraries, these end up just being defines that redirect to the non-suffixed versions of the functions.
Noticed this while tinkering around and is easy enough to solve today.
> ThunkLibs: X11/Xext: Removes two functions that don't exist on 32-bit

- ThunkLibs/libvulkan/Guest.cpp
Value passed in to this print will be 32-bit or 64-bit depending on arch.
Noticed this while tinkering around and is easy enough to solve today.
> Thunks/libvulkan: Fixes print for 32-bit

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- ThunkLibs/include/common/Guest.h
Use the fastcall ABI for 32-bit x86 to make our lives easier. Fastcall ABI puts the first two 32-bit arguments in ECX and EDX respectively.
Compilers are nice today and allow us to do cross-abi function calls like this.
> Thunks: Implement the Thunk IR op for 32-bit mode

- CMakeLists.txt
- External/FEXCore/Source/Interface/Config/Config.json.in
- Source/Tests/ELFCodeLoader2.h
- Source/Tests/FEXLoader.cpp
- Source/Tests/VDSO_Emulation.cpp
- Source/Tests/VDSO_Emulation.h
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/include/common/Guest.h
- ThunkLibs/libVDSO/Types.h
- ThunkLibs/libVDSO/libVDSO_Guest.cpp
- ThunkLibs/libVDSO/libVDSO_Guest_32.lds
- ThunkLibs/libVDSO/libVDSO_interface.cpp
- unittests/FEXLinuxTests/tests/vdso/vdso_test.cpp
As promised, here is the other half of the hand-written host-side implementation of VDSO.
VDSO for 32-bit and 64-bit are the only thunks that need this handwritten path.
This has ~~#2008~~, ~~#2009~~, and ~~#2010~~ merged in to which needs to be merged before this PR is merged.
Fixes #690
Some special things here
1) Now defaulting to hidden visibility
2) 32-bit thunks compiled with features to make PLT overhead more bearable
3) Only fexthunks_exports_<library> and other required symbols should be publicly exposed.
4) 32-bit VDSO needs clock_gettime64 and vsyscall on top of the other symbols
5) 32-bit thunks use fastcall ABI to reduce overhead
The PLT and hidden things are required to reduce overhead of thunks on 32-bit:
Without:
With hidden plus PLT compile flags:
As we can see, it …
> 32-bit VDSO support

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Since PR #2003, we now set up some predicate registers within FillStaticRegs. We can now make use of those instead of manually setting up predicate registers inside the IR opcodes.
> Arm64/VectorOps: Make use of static predicate registers

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
This instruction was purely a move that did format reinterpretation. This was necessary with LLVM when we had implicit IR op sizes.
Now that all vector ops are explicitly sized, this is not only redundant, but also completely unnecessary sicne we don't support LLVM anymore.
Remove the op, which technically is a very minor optimization for the two instructions that still used it.
> IR: Removes unnecessary VBitcast IR op

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- External/FEXCore/Source/Interface/IR/IR.json
This is a duplicate of VDupElement since AArch64 doesn't support an element extract plus zero of the rest of the register.
Removes and replaces its uses with VDupElement.
> IR: Removes VExtractElement

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/MoveOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MoveOps.cpp
- External/FEXCore/Source/Interface/IR/IR.json
This is unused and shouldn't ever be used.
> IR: Removes Mov IR op

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
Also put an assert in place to catch any over-sized values.
> Interpreter: Handle 256-bit VMov

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
Makes the previously implemented ops a little more self-documenting, and, if we ever actually need to change this, there's a nice constant that can be looked up instead of magic 32 values.
> Interpreter: Use constant for AVX register size where applicable

- ThunkLibs/libVDSO/libVDSO_Guest.cpp
The `mov ebp, ecx` was breaking vsyscall and was expected to be used with the `syscall` instruction rather than `int 0x80`. Remove that to fix it.
Also remove the pushes and pops around the syscall instruction, these are unnecessary in an emulated environment, we won't clobber the registers.
Fixes Steam execution with VDSO.
> VDSO: Fix vsyscall

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends VNot to handle 256-bit vectors.
> IR: Handle 256-bit VNot

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends VCMPGT, VCMPGTZ, and VCMPLTZ to be able to handle 256-bit vectors.
Finishes up the regular vector integer comparisons
> IR: Handle 256-bit VCMPGT/VCMPGTZ/VCMPLTZ

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Extends VFCMPORD and VFCMPUNO to handle 256-bit vectors.
Finishes up all the floating point comparisons
> IR: Handle 256-bit VFCMPORD/VFCMPUNO

- Source/Tests/ELFCodeLoader2.h
Specifically fixes /sbin/ldconfig.
Fixes 8df7c2d84f03ef092ae2474ade1d80369b8f542f
Fixes Steam launching
I failed to test ELF files that are dynamic with no interpreter here, so EntryPoint ended up being set to zero, which results in an instant crash.
Ensure these values are set correctly after the primary ELF and interpreter are loaded so starting RIP is correct.
> ELFCodeLoader: Fixes dynamic non-interpreter ELFs

- Source/Tests/ELFCodeLoader2.h
Instead of mapping to find a range, unmapping, and then submapping inside of it.
Map once, then mmap with MAP_FIXED to overwrite the mapping. This fixes an issue where if you enabled ASAN then it would stick additional mappings inbetween where we want to map. Thus breaking asan.
> ELFCodeloader: Map once and then use MAP_FIXED to overwrite

- External/FEXCore/Source/Utils/Allocator.cpp
- Source/Tests/ELFCodeLoader2.h
The kernel maps the primary ELF with a hint to some place *near* the
middle of the virtual address space. While the interpreter stays at the
top of the address space.
This also adds ASLR to the ELF loading, with a define for debugging and
testing purposes.
Requires both https://github.com/FEX-Emu/FEX/pull/2013 and ~~https://github.com/FEX-Emu/FEX/pull/2014~~ merged first.
> ELFCodeLoader: Map primary ELF more like the kernel 

- ThunkLibs/GuestLibs/CMakeLists.txt
Ensures the thunk is rebuilt if the linker scripts have changed.
Fixes #2054
> Thunks: Adds dependency on linker script

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
These are only implemented in the interpreter currently, which makes these easy to extend
> Interpreter: Handle 256-bit VSShr/VUShl/VUShr

- unittests/ASM/H0F38/66_04.asm
This should be using xmm2 rather than mm2.
> unittests: Amend mm register usage in H0F38/66_04.asm test

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/IR/IR.json
Extends VSXTL and VSXTL2 to handle 256-bit vectors.
> IR: Handle 256-bit VSXTL/VSXTL2

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/IR/IR.json
Extends VUXTL and VUXTL2 to handle 256-bit vectors
> IR: Handle 256-bit VUXTL/VUXTL2

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
Otherwise we will end up allocating code buffers in the lower 32-bits, consuming precious virtual address space.
> Ensure Arm64Emitter uses FEX allocator

- Source/Tests/ELFCodeLoader2.h
- Source/Tests/FEXLoader.cpp
Implements AT_PLATFORM: Ends up being `i686` or `x86_64` depending on ELF arch
Implements AT_HWCAP and AT_HWCAP2
AT_HWCAP is just CPUID function 01h EDX result
AT_HWCAP2 only has two defined bits in it, which we don't support either.
Implements AT_RANDOM
Previously we were just sticking hardcoded values in to this. Now we pass along the host's AT_RANDOM, or we generate our own if that doesn't exist
Fixes #788
> ELFCodeLoader: Implement four more auxv values

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
Accidentally didn't implement this for FPREM1 but it /was/ implemented for FPREM. Fixes an infinite loop in cossin implementations.
Test code from the application returns an incorrect result, but it isn't due to FPREM1.
```
$ `which wine` ./hello.exe
Sin 1.22460635382238E-16
Cos -1
$ FEXInterpreter `which wine` ./hello.exe
Sin 1.22460635382238E-16
Cos 0.54030230586814
```
Fixes #2021
> OpcodeDispatcher: Fixes FPREM1 C2 flag calculation

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- unittests/ASM/Primary/ROL_Flags.asm
- unittests/ASM/Primary/ROR_Flags.asm
- unittests/ASM/Primary/SHL.asm
- unittests/ASM/Primary/SHR.asm
These were being calculated incorrectly in the case of rotating with
values larger than 8-bit or 16-bit
> OpcodeDispatcher: Fixes flag calculation on ROR and ROL by immediate

- unittests/ASM/Disabled_Tests_Simulator
Brings in a fix for the narrowing and widening operations erroneously clearing the upper portion of the vector register when using lower narrowing instruction variants in the case where the source register and destination register are the same. I've also made a PR upstream to fix this as well (https://github.com/Linaro/vixl/pull/49)
Since this fixes the issue, we can also re-enable the tests that make use of narrowing and widening on the simulator.
This will also let me extend the narrowing and widening IR ops reliably, since I'll now have test cases
> External: Update vixl submodule

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Turns out I completely missed the existence of SUNPKLO/SUNPKHI and UUNPKLO/UUNPKHI which do exactly what we need.
> Arm64/VectorOps: Simplify SVE VSXTL/VSXTL2/VUXTL/VUXTL2 implementations

- Source/Tests/LinuxSyscalls/FileManagement.cpp
Need to dereference the boolean to ensure we only load the thunksDB files once.
> ThunksDB: Fixes Thunks loaded boolean pointer check

- ThunkLibs/libEGL/libEGL_interface.cpp
- ThunkLibs/libGL/libGL_interface.cpp
- ThunkLibs/libxcb-dri2/libxcb-dri2_interface.cpp
- ThunkLibs/libxcb-dri3/libxcb-dri3_interface.cpp
- ThunkLibs/libxcb-glx/libxcb-glx_interface.cpp
- ThunkLibs/libxcb-present/libxcb-present_interface.cpp
- ThunkLibs/libxcb-randr/libxcb-randr_interface.cpp
- ThunkLibs/libxcb-shm/libxcb-shm_interface.cpp
- ThunkLibs/libxcb-xfixes/libxcb-xfixes_interface.cpp
- ThunkLibs/libxcb/libxcb_interface.cpp
Some libraries were missing these version defines, which was causing dlopen to fail.
This was causing thunks to break in pressure-vessel.
> Thunks: Fixes missing thunk librarie so versions

- External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp
Previously this would silently ignore unhandled masks.
> IR: Check for invalid conversion masks in Float_FromGPR_S

- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
Removes a heap allocation for inline syscalls.
> Arm64/BranchOps: Remove unused std::vector

- ThunkLibs/GuestLibs/CMakeLists.txt
Clang thunks already have these default enabled, but let's also enable this on the GCC side.
sse2 will enable most things we care about, which matches ASIMD quite closely.
fpmath=sse removes some x87 usage for 32-bit thunks specifically.
Should effectively be a non-functional-change
> Thunks/Guest: Enable SSE2 on thunks and set fpmath to sse

- CMakeLists.txt
- External/FEXCore/Source/CMakeLists.txt
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Frontend.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/IR/PassManager.cpp
- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- External/FEXCore/Source/Interface/IR/Passes/DeadCodeElimination.cpp
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- External/FEXCore/Source/Interface/IR/Passes/DeadStoreElimination.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/LongDivideRemovalPass.cpp
- External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/RAValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
- External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- External/FEXCore/Source/Interface/IR/Passes/StaticRegisterAllocationPass.cpp
- External/FEXCore/Source/Interface/IR/Passes/SyscallOptimization.cpp
- External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
- External/FEXCore/Source/Utils/Profiler.cpp
- External/FEXCore/include/FEXCore/Utils/Profiler.h
- Source/Tests/FEXLoader.cpp
This creates a generic interface that FEXCore can use for timeline profiling. This allows us to create a generic interface which the backend details are hidden so we can support multiple timeline profile APIs.
The only API supported right now is ftrace/gpuvis. Which is extremely lightweight of an interface with minimal overhead.
We must be careful here since in most cases will will have dozens of FEX instances running at any given time. So a timeline profiler like Microprofiler can have major issues since that only ever expects a single process at a time.
Not enabled by default but just needs the `ENABLE_FEXCORE_PROFILER` cmake option set to enable.
Gives us pretty pictures like this:
> FEXCore: Adds support for a timeline profiler interface

- Scripts/testharness_runner.py
- unittests/32Bit_ASM/CMakeLists.txt
- unittests/ASM/CMakeLists.txt
- unittests/ASM/Known_Failures_int
- unittests/ASM/Known_Failures_jit
- unittests/ASM/X87/D9_F5_2.asm
- unittests/ASM/X87/D9_F5_3.asm
- unittests/IR/CMakeLists.txt
unit tests that show the difference of output between FPREM and FPREM1.
Setup as known failures on everything except for host since we don't
implement fprem correctly.
An incorrect fix to FPREM is as follows:
```diff
--- a/External/FEXCore/Source/Common/SoftFloat.h
+++ b/External/FEXCore/Source/Common/SoftFloat.h
@@ -158,6 +158,10 @@ struct X80SoftFloat {
return Result;
#else
+    BIGFLOAT lhs_ = lhs;
+    BIGFLOAT rhs_ = rhs;
+    BIGFLOAT Result = fmodl(lhs_, rhs_);
+    return Result;
return extF80_rem(lhs, rhs);
#endif
}
```
But we shouldn't implement this fix. We should instead implement a new `extF80_mod`
function that handles the rounding differences between FPREM and FPREM1.
Fixes https://github.com/FEX-Emu/FEX/issues/2097.
Doesn't attempt to resolve - …
> unittests/asm: Adds more extensive FPREM/FPREM1 tests 

- External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
- External/FEXCore/Source/Utils/Allocator/FlexBitSet.h
- Some minor cleanups in the VMARegion struct type.
- Switches over to using the FlexBitSet range scanning, based off this
implementation.
- Move memory region allocation to its own function instead of
constructor
- This will be used by a new constructor later for 48-bit host-side
allocations
- Minor optimization to keep track of Munmap.
- We were burning a bunch of time on backward scanning for free
regions even though we never did a munmap to free anything.
- Now only do backward scanning if a munmap occured.
- Saves a bunch of CPU time
This is preparation work towards having FEX having its own independent allocator for host side allocations when running on a device with 48-bit VA. Necessary to work around some wine bugs where they overwrite our memory.
> Utils/64BitAllocator: Minor cleanups and optimization for munmap 

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- unittests/ASM/Primary/ROL_OF.asm
- unittests/ASM/Primary/ROR_OF.asm
Turns out this was calculating OF incorrectly, breaking Denuvo early in its execution.
Changes the ROL imm OF calculation code as well to be more consistent and not keep src1 alive longer than it needs to be.
Also adds two new unit tests to ensure this stays correct.
Denuvo Anti-tamper still crashes, but it gets farther at least.
> OpcodeDispatcher: Fixes ROR imm OF calculation

- ThunkLibs/GuestLibs/CMakeLists.txt
This was generating GOT prologues even on naked functions which was breaking VDSO on 32-bit.
Fixes almost every 32-bit application when running with debug options.
> 32bit: Fixes Debug build of VDSO

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
We don't detect the range of the long F80, so we need to set that the source was in range to fix sin/cos/tan calculations.
If we don't set this flag to zero then glibc will do some additional operations that causes the value to be incorrect.
Fixes the output of the test application in #2021, probably fixes some camera orientation problems in games as well.
> X87: Claim incoming float was in the range for trancendental ops

- Source/Tools/FEXServer/ProcessPipe.cpp
Chrome seems to like sending us invalid packets of data sometimes. With an invalid packet type just skip parsing the data entirely.
Fixes an infinite loop in Vampire Survivors.
> FEXServer: Be robust against invalid packets.

- External/FEXCore/Source/Utils/Allocator.cpp
If we take all of the stack space then the auto expanding stack doesn't work and we get stuck with a small stack that breaks thunks.
> Allocator: Expand stack space when stealing virtual address space

- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- External/FEXCore/include/FEXCore/Core/CoreState.h
- Source/Tests/HarnessHelpers.h
- Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tests/LinuxSyscalls/x32/Thread.cpp
- Source/Tests/LinuxSyscalls/x64/Thread.cpp
- unittests/IR/Correctness/FPRStoreTruncate.ir
Segment registers are indexed significantly more than they are changed.
Pay the cost of indexing during the set and store rather than the per
register index.
Should be a fairly significant performance improvement for 32-bit
applications. At least on hardware that doesn't have a data dependent
prefetcher.
Breaks Steam atm and isn't clean.
> Segment register index optimization

- External/FEXCore/Source/Interface/Core/Interpreter/MiscOps.cpp
This has been unused since ff1d51c7bda3a4151ffb13fc0f2caec5d8c5e3a5
Silences a compiler warning.
> Interpreter/MiscOps: Remove unused StopThread() function

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Gets rid of some leftover bits from when we didn't have statically allocated predicate registers.
> Arm64/MemoryOps: Remove lingering unnecessary ptrue instances

- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
Extends LoadMem, LoadMemTSO, and ParanoidLoadMemTSO to handle 256-bit vectors
> IR: Handle 256-bit LoadMem/LoadMemTSO/ParanoidLoadMemTSO

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
There's nothing preventing the `OpSize == 1` case from being merged into the switch, so we can do that to make things a little more consistent.
> Arm64/MemoryOps: Merge if statement into switch in ParanoidLoadMemTSO

- External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
We can just use the destination register in this case.
> Arm64/ConversionOps: Eliminate use of temporary in Vector_FToF

- ThunkLibs/GuestLibs/CMakeLists.txt
The IDE integration path didn't set up the BITNESS variable.
This change also unmarks that variable as a CMake option since it's not a boolean value. (CMake doesn't support non-boolean options.)
> Thunks: Fix guest targets not being detected by IDEs

- Scripts/InstallFEX.py
Also removes Hirsute and Impish since Ubuntu's PPA system doesn't support these anymore.
Fixes #2140 
Ubuntu 22.10 rootfs is already uploaded to the server.
> InstallFEX.py: Adds support for Kinetic

- Source/Tests/ELFCodeLoader2.h
- Source/Tests/VDSO_Emulation.cpp
- Source/Tests/VDSO_Emulation.h
AT_SYSINFO points to the vsyscall location that the kernel provides. This AUXV value isn't used on x86-64.
If we have VDSO installed then we can use the one provided from there, otherwise we need to provide a code page.
It seems like some behaviour changed with glibc provided in Ubuntu 22.10 that it now requires AT_SYSINFO.
Fixes wine 7.0 execution inside the Ubuntu 22.10 rootfs.
> ELFCodeLoader: Ensure we set AT_SYSINFO for 32-bit

- Source/Tests/ELFCodeLoader2.h
When we are installed as a binfmt_misc handler the Linux kernel will assign us AT_SECURE for setuid binaries.
Ensure we are passing this through for any application that will end up needing it.
> ELFCodeLoader: Pass through AT_SECURE

- Source/Tests/ELFCodeLoader2.h
We were failing to null terminate the platform which is causing strcmp to fail.
> ELFCodeLoader: Fixes AT_PLATFORM null terminator

- Source/Tools/FEXConfig/Main.cpp
This was driving me nuts that this wasn't sorted by name.
> FEXConfig: Sort named rootfs vector

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/IR/IR.json
We use these two IR ops for PSRLQ and PSLLQ respectively, Which is actually implemented in a quite inefficient way.
Instead switch the ops over to using VExtr which maps directly to one instruction and can emulate both.
> IR: Removes the only uses of VSLI and VSRI

- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Ensures we have more convenient upper-lane clearing behavior with AVX 128-bit operations
> x86_64/VectorOps: Separate 128-bit/256-bit paths

- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/include/FEXCore/Config/Config.h
- Source/Common/Config.cpp
- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tools/FEXGetConfig/Main.cpp
This will be useful for keying specific executables to steamids. This is sadly required because a bunch of games end up naming themselves "game.exe" so we can't safely enable thunks for all things shipping a generic name.
> Config: Add support for steamid based configurations.

- External/FEXCore/Source/Interface/Core/Core.cpp
This hasn't ever caused problems and instead just adds a message that appears in logs for nearly every application invocation.
Remove it because it isn't necessary to track.
> Core: Removes log about migrating to shared memory mode

- External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
This is a nice helper that was otherwise missing.
> IntrusiveIRList: Add a utility helper for getting an OrderedNodeWrapper

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
- External/FEXCore/include/FEXCore/Core/CoreState.h
This isn't really a performance issue, more just something that is gross looking at while looking at unit tests.
Break /usually/ isn't abused heavily by games (Except Denuvo) so not really a perf concern regardless.
> Arm64: Optimize Break IR op codegen

- Source/Common/FEXServerClient.cpp
- Source/Common/FEXServerClient.h
- Source/Tools/FEXServer/ProcessPipe.cpp
- Source/Tools/FEXServer/SquashFS.cpp
Two changes here.
- Make the mount path follow server temp folder requirements.
- Will be mounted in `/tmp/` or `$XDG_RUNTIME_DIR/` now
- Switch the FEXServer socket to an "abstract" AF_UNIX socket.
- If the socket is in `/tmp/` then systemd will put the service in a private `/tmp` folder that only exists for the service.
- If the socket is in `$XDG_RUNTIME_DIR` then pressure-vessel can't chroot anymore since they make their own runtime directory.
- If it is in `$HOME/.fex-emu/` then it breaks usage where the filesystem is a mount that doesn't support AF_UNIX like sshfs.
The only reasonable thing to do is to switch over to `abstract` sockets which will work in all cases.
Tested with pressure-vessel and systemd and now it works in all situations.
> FEXServer: More Systemd fixes

- Source/Tests/LinuxSyscalls/x32/Syscalls.cpp
- Source/Tests/LinuxSyscalls/x64/Syscalls.cpp
Shaves a couple milliseconds off initialization time.
Noticed this while poking around.
> Syscalls: Minor optimization with initialization of syscall definition vector

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/X86Tables/SecondaryGroupTables.cpp
- unittests/32Bit_ASM/Disabled_Tests_host
- unittests/32Bit_ASM/Secondary/07_XX_00.asm
- unittests/ASM/Disabled_Tests_host
- unittests/ASM/Secondary/07_XX_00.asm
Ran in to this when running Team Sonic Racing.
This game uses Denuvo Anti-Tamper which some versions rely on SGDT.
The Linux kernel catches and emulates this instruction.
It will always return a limit of 0 and a base of `0xFFFFFFFFFFFE0000ULL`
which is guaranteed to be in kernel space.
This gets the game slightly farther but still not running entirely.
> OpcodeDispatcher: Implement SGDT 

- External/FEXCore/Source/Interface/Config/Config.json.in
This causes users pain currently since the JIT isn't doing any caching and our RA being a hack mess means it is quite slow.
Disable by default to improve JIT time performance.
When testing I'm usually running with multiblock disabled myself because of the performance hit.
> Config: Disable multiblock by default

- External/FEXCore/Source/Interface/Core/LookupCache.h
- External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
Improves the shutdown time a small amount and performance of these maps.
> Core: Replace a couple maps with tsl robin_map

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
- unittests/ASM/VEX/vmovq.asm
- unittests/ASM/VEX/vmovq_vmovd_reg.asm
Fairly trivial, we can reuse the existing implementation for MOVQ.
> OpcodeDispatcher: Handle VMOVQ

- unittests/ASM/VEX/vpclmulqdq.asm
Now that we have some AVX instructions in place, we can make the test use them and also enforce correctness behavior in the upper lane.
> unittests: Expand VPCLMULQDQ unit test

- External/FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
The less number of FPR<->GPR movement instructions the better. This removes one instance of `ins` and replaces the other with a 64-bit `dup` instead.
The LoadConstant still turns in to a single `movz` instruction with the shift.
> Arm64: Minor optimization in AESKEYGENASSIST

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterFallbacks.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/FlagOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Just noticed this when tinkering around the JIT.
These arguments can safely be const.
> Arm64: Const on unmodified argument

- Source/Tests/FEXLoader.cpp
`std::filesystem::exists` is particularly gnarly in how it checks to see if the file exists.
It allocates memory, it creates lists, it splits things, then eventually checking the status
Remove all this overhead to help out minorly for applications that execve a lot.
Before:
After:
> FEXLoader: Make `IsInterpreterInstalled` check less horrible.

- Source/Tests/ELFCodeLoader2.h
- Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/FileManagement.h
`GetEmulatedPath` and `OpenAt` are called a /lot/ in applications. std::filesystem::path handling here is quite heavy and costly for what we are trying to achieve.
Remove this usage and instead use lstat, access, and readlink directly which is a heck of a lot faster.
In particular this helps out pressure-vessel, shaving off launch times by 1-2 seconds.
Going from ~22 seconds down to ~20 seconds.
> Linux: Improve performance of hot paths in path searching

- Source/Common/FEXServerClient.cpp
- Source/Common/FEXServerClient.h
On first FEXInterpreter execution, it is expected that `ConnectToServer` will fail with `ECONNREFUSED` because FEXServer won't be running.
Skip printing this first messaage to stderr if configured. If it is some other error message then ensure it is still printed.
> FEXServerClient: Disable confusing connection log

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
We can just use VBic here to simplify everything.
> OpcodeDispatcher: Simplify VANDN

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Currently `VDupElement` allows duplicating 128-bit elements in 256-bit vectors with SVE, so we can extend `VInsElement` to have similarly consistent behavior.
(this will also be nice to have when implementing VINSERTI128/VINSERTF128
> IR: Handle 128-bit VInsElement with SVE

- External/FEXCore/Source/Interface/Config/Config.cpp
Accidentally was checking for SteamID layer types twice, rather than global.
Fixes steamwebhelper config not getting loaded from global config.
> Config: Fixes global application configs

- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Frontend.cpp
- External/FEXCore/Source/Interface/Core/Frontend.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- unittests/32Bit_ASM/FEX_bugs/GOT_calculation.asm
32-bit GOT calculation needs to do a call+pop to do get the EIP on 32-bit. LEA doesn't work because it there is no EIP relative ops like on x86-64.
This causes a terrible block split on every GOT calculation without the optimization in place.
Now the block can continue through this weird GOT calculation.
This will be worthwhile for our 32-bit thunks where for some reason the GOT calculation can't be removed. The GOT is calculated even though it isn't used.
> OpCodeDispatcher: Optimize a case of GOT calculation

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Reduces the amount of code size generated by the specializations.
Only targets ones that are heavily templated like the generic op helper functions.
> OpcodeDispatcher: Move template impl to regular function where applicable

- External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
Previously these were doing 128-bit accesses, when they only need to do 64-bit ones
> X86Tables: Restrict CVTDQ2PD and CVTTSD2SI to 64-bit memory accesses

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
Ensures the 128-bit case will be handled when extending for 256-bit (which the simulator currently doesn't support).
Technically this should be here anyways like with other AVX ops to begin with. But I was silly and implemented the 128-bit support for this when we had none of the other AVX facilities set up.
> Crypto: Explicitly clear upper lane with VPCLMULQDQ

- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
We currently only use 2236 bytes, no need for two pages. Once #2250 is merged we will use 1716 bytes
> Arm64: Reduce dispatcher to 1 page

- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
This was likely an issue with signals racing to the spill handler, which we have fixed bugs with over the past few months.
This means we don't need to spill all SRA GPR registers anymore, at most we need to spill three registers that intersect with syscall arguments.
> Arm64: Inline Syscall spill optimization

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
- unittests/ASM/VEX/vpextrw.asm
Whoops. Missed one when implementing the VPEXTR family
> OpcodeDispatcher: Handle remaining PEXTRW opcode

- External/FEXCore/Source/Interface/Core/LookupCache.cpp
- External/FEXCore/Source/Interface/Core/LookupCache.h
Use one large allocation for all levels of the cache so they are virtually contiguous.
This allows us to clear the cache entirely by using a single madvise instead of three. Which ends up being quite a bit nicer.
> LookupCache: Optimize cache clearing and allocation

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
The extract operation essentially does this for us.
> OpcodeDispatcher: Remove unnecessary usage of VMov in VPSLLDQOp

- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
GetDst and GetSrc renamed to GetVReg. Makes it less confusing that these are for vector registers and having two implementations makes no sense now.
Renamed GetSrcPair to GetRegPair to match naming of all these register helpers.
> Arm64: Rename GetSrcPair, GetDst, and GetSrc

- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Makes this a little nicer for 128-bit and soon-to-be 256-bit vectors.
> OpcodeDispatcher: Zip elements instead of for loop insertion in PHSUB 

- Data/ThunksDB.json
- Source/Tests/LinuxSyscalls/FileManagement.cpp
Found by turning overly defensive code into a hard error.
Wasn't sure whether `ERROR_AND_DIE` was the right thing to use here. Do we have a better mechanism for critical failures?
> ThunksDB: Fix misspelt guest library names

- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/FileManagement.h
A number of various cleanups eliminating the bits that confused me while trying to understand this code the first time.
* Reduces floating state carried around in lambdas (and the overall number of lambdas used)
* Replaces thunk DB template handling (such as `%ARCH_PREFIX%`): Instead of iteratively replacing each "prefix" one after the other, all of them are replaced in one go now
* Decouples processing steps that were previously intertwined (such as DB template filling and the actual insertion into the `Overlays` list)
As a side effect, this avoids a few heap allocations from `std::string` and `std::function`.
> ThunkDB: Clean up database loading

- External/FEXCore/include/FEXCore/Debug/X86Tables.h
We were leaving some ugly holes in a couple of these structs. Reorder them so they are packed more efficiently.
> X86Tables: Optimize struct layouts

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Found an application today (hashtree tests) that causes us to spill a large amount of values on to the stack.
We were encoding larger offsets than what unsigned offset load and store can handle.
If the offset is too large for the loadstore, use a temporary to put the offset in to first.
> Arm64: Fixes large offset spill slots

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
FADDF64 & co. had incorrect logic for loading integer arguments.
Copies the correct logic over from FILDF64.
> F64: Fix integer immediates for add,mul,div,sub

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- unittests/ASM/X87/FPREM1_Flags.asm
- unittests/ASM/X87/FPREM_Flags.asm
- unittests/ASM/X87_F64/FPREM1_Flags_F64.asm
- unittests/ASM/X87_F64/FPREM_Flags_F64.asm
Copy+paste error meant C2 flag was not getting cleared for FPREM/1 in F64 mode.
Also adds tests to verify C2 flag clear on both F80 and F64
> Fix FPREM flags calculation in F64

- External/FEXCore/Source/Common/JitSymbols.cpp
- External/FEXCore/Source/Common/JitSymbols.h
When a process is in the process of forking and getting ready for execve, it is common practice to do a `close_range` or close loop to close all file descriptors before the execve.
This is a security/sanitization feature to ensure that FDs aren't leaked to the child process. While it is more reliable to have these FDs opened with O_CLOEXEC, people get it wrong all the time so this feature has been put in place. Both python and glibc wrappers for launching applications do this.
The problem with this for FEX is that we were using a FILE handle for emitting JIT symbols to the perf file. When the underlying FD is ripped out from under the FILE handle, it throws an assert that we can't recover from.
Switching to a raw FD and checking to ensure the FD is still open on writes means that we can …
> JitSymbols: Fixes a crash that can occur

- Scripts/InstallFEX.py
This was never updated for 22.10, Updated list.
Thanks to a Discord user for noticing this.
> Scripts: Update InstallFEX.py rootfs links

- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/CPUID.h
- External/FEXCore/Source/Utils/FileLoading.cpp
- External/FEXCore/Source/Utils/FileLoading.h
Map lookup was quite expensive, switched over to three small vectors
that are constexpr instead.
Some file querying and parsing was fairly slow as well. Optimized to
make that CPU time to go away.
This improves initialization time of CPUIDEmu by 33%
> CPUID: Optimize initialization

- Source/Tests/CMakeLists.txt
- Source/Tests/FEXLoader.cpp
This is causing some heartburn with the hardlink.
- Removes some termux cmake list hacking.
- Removes the need to do post-install packaging fixups when hardlinks get dropped.
- Removes a custom uninstall target that was necessary before.
Might want to hide whitespace when reviewing this, it looks like a lot of changes but it is fairly minimal.
> FEXLoader: Build FEXInterpreter and FEXLoader independently

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Was using the wrong sized registers in spill which was breaking Steam. Oops.
> Arm64: Fix SpillRegister C&P error

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
CVAU does Clean to `Point Of Unification` CIVAC does Clean+Invalidate to `Point of Coherency`
`Point of Unification` means to L2/L3, so unification of core visibility.
`Point of Coherency` means SLC/RAM, All cores, DNA engines, etc must be coherent.
> Arm64: Fixes incorrect operation for CacheLineClear

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/unittests/Emitter/ASIMD_Tests.cpp
Adds three classes:
- Advanced SIMD three same (FP16)
- Advanced SIMD two-register miscellaneous (FP16)
- Advanced SIMD three-register extension
A handful of the three-register extension unit tests are disabled because the vixl disassembler doesn't support them.
Only six more classes of ASIMD operations remaining once this is merged.
> ArmEmitter: Adds three more classes of ASIMD instructions

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
- External/FEXCore/unittests/Emitter/ASIMD_Tests.cpp
Also adds four missing shift by imm instructions.
Only missing four ASIMD instruction classes now.
- 3Reg SM3 crypto
- 3Reg SHA512/SHA3/SM3
- 4Reg SHA3/SM3
- 2Reg SHA512/SM4
Also some misc instructions
> ArmEmitter: Adds two more classes of ASIMD instructions

- External/FEXCore/Source/Common/JitSymbols.cpp
We shouldn't use O_EXCL, since we need to overwrite previous entry PIDs if they happen to exist. The kernel ensures that PIDs don't overlap, but in some kernel configurations PIDs are aggressively reused, resulting in O_EXCL quickly hitting an issue when writing stale files.
Additionally O_DIRECT, this doesn't allow us to write to files, so all write functions were failing.
Additionally use O_APPEND, we are only ever appending, so let the kernel know.
Additionally use O_TRUNC, in the case that a stale perf file exists, this will immediately truncate the file to zero.
> JitSymbols: Fixes file opening and writing

- FEXHeaderUtils/FEXHeaderUtils/Syscalls.h
Seen issue while compiling on alpine linux (musl).
> fix ifdef to use HAS_SYSCALL_TGKILL for tgkill as it was intented

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Buffer.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
- External/FEXCore/unittests/Emitter/TestDisassembler.h
The current separated adr and adrp handlers are difficult to use if you
don't know if the resulting address is going to be within 1MB or 4GB.
Adds a `LongAddressGen` helper that will generate the various pieces of
code that will need to be emitted.
Backward labels:
- Can generate three different code segments depending on distance to
label
- adr if label is within 1MB
- adrp if label is 4K page aligned and within 4GB
- adrp+add if label is within 4GB
Forward labels:
- Can generate three different code segments depending on distance to
label
- nop+adr if label is within 1MB
- nop+adrp if label is 4K page aligned and within 4GB
- adrp+add if label is within 4GB
There is still the limitation that this can't generate addresses to
labels that are >4GB away. Which is fine.
> ARMEmitter: Support helper for long address generation 

- FEXHeaderUtils/FEXHeaderUtils/SymlinkChecks.h
- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Linux/Utils/ELFContainer.cpp
- Source/Linux/Utils/ELFContainer.h
- Source/Tests/ELFCodeLoader2.h
- Source/Tests/FEXLoader.cpp
- Source/Tests/LinuxSyscalls/Syscalls.cpp
- Source/Tests/LinuxSyscalls/Syscalls.h
- Source/Tests/LinuxSyscalls/x32/Thread.cpp
- Source/Tests/LinuxSyscalls/x64/Thread.cpp
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/FEXServer/Main.cpp
Fixes https://github.com/FEX-Emu/FEX/issues/2136
This is a fairly tricky edge case to support with FEX.
If execveat is used with AT_EMPTY_PATH then the application can pass an
FD to execve instead of a filename. This includes FDs that have been
deleted from the disk so the child process can't open it by filename
anymore.
To work around this limitation, we need to pass the FD to the new FEX
process and open it directly, similar to how binfmt_misc works with FDs.
The FD will get passed through environment variables, which the new
process will check for and then remove the variable from the
environment.
Lots of prickly edge cases to support here.
Without binfmt_misc:
- Passes the FD to FEXLoader directly.
- Requires duplicating the FD if it has O_CLOEXEC on the FD.
With binfmt_misc:
- …
> FEXLoader: Adds support for execveat with AT_EMPTY_PATH 

- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- unittests/ASM/X87/DA_02.asm
- unittests/ASM/X87/DE_02.asm
- unittests/ASM/X87_F64/DA_02_F64.asm
- unittests/ASM/X87_F64/DE_02_F64.asm
This was not correctly converting both 32-bit and 16-bit integers over
to 64-bit double.
> X87_F64: Fixes FICOM

- External/FEXCore/Source/Interface/Core/Core.cpp
We only need a 32-bit virtual memory size when running a 32-bit application.
Just lowers some virtual memory space that we need to allocate.
> Core: Adjust virtual memory size for 32-bit

- Source/Tests/LinuxSyscalls/Syscalls.cpp
Somewhere during the refactoring/review process, failed to strip the shebang prefix off of the arguments.
Causing shebang files to always fail as if the file never existed.
Fixes steam execution.
> Linux: Fixes shebang file execution

- Source/Tests/LinuxSyscalls/Syscalls.cpp
`string::find()` returns `npos` (-1) if the given character was not found, so it can't be used to construct a string like this. Luckily, the use of std::span allows this code to be written such that it's both correct and simpler than before.
> Syscalls: Fix out-of-bounds read when handling single-line shebang files

- External/FEXCore/Scripts/json_ir_generator.py
- External/FEXCore/Source/Interface/IR/IRDumper.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- External/FEXCore/include/FEXCore/IR/IREmitter.h
Split off from #2243 to remove each member individually.
IR ops are hardcoded by operation to have a destination or not. No need to have each operation have a boolean for determining if the operation has a destination or not.
The number of places things need to know if the operation has destination or not is better served by using a lookup instead.
> IR: Remove HasDest member

- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
Stripped from #2344 at request to ensure 64-bit code hasn't changed in a meaningful way. So that PR can focus on 32-bit.
> Dispatcher: Extract 64-bit signal frame save and restore

- External/FEXCore/Scripts/json_ir_generator.py
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/IR/IREmitter.cpp
- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
- External/FEXCore/include/FEXCore/IR/IREmitter.h
Split off from #2243 to remove each member individually.
Shaves 8-bits off of each IR op.
No need to cart around this data when it is constant for each operation. Especially since most optimization passes don't need the data anyway.
Needed to add a new `GetRAArgs` to get the number of SSA arguments that get RA versus `GetArgs` which returns all SSA arguments the IR operation owns. This is what was causing #2243 to fail CI since it needs to know the difference in some places.
> IR: Removes NumArgs member from IR ops

- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/X86Tables/SecondaryGroupTables.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Core/HostFeatures.h
- Scripts/json_config_parse.py
- Source/Tests/HarnessHelpers.h
- Source/Tests/TestHarnessRunner.cpp
- Source/Tests/TestHarnessRunner/HostRunner.cpp
- unittests/ASM/Secondary/CLFLUSHOPT.asm
- unittests/ASM/Secondary/CLWB.asm
These fairly trivially map to AArch64 operations.
CLWB just maps to `dc cvac`
CLFLUSHOPT just maps to `dc civac` without the final `dsb`.
Also captures if something tries using XSAVEOPT without checking.
> OpDispatcher: Adds support for CLWB and CLFLUSHOPT

- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/X86HelperGen.cpp
- External/FEXCore/Source/Interface/Core/X86HelperGen.h
- External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Core/CoreState.h
- External/FEXCore/include/FEXCore/Core/UContext.h
- External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
- unittests/FEXLinuxTests/tests/signal/invalid_util.h
- unittests/FEXLinuxTests/tests/signal/sigtest_siginfo.32.cpp
Follow-up to https://github.com/FEX-Emu/FEX/pull/2327.
~~First four commits are from #2327 and those should be merged first.~~
Split off from https://github.com/FEX-Emu/FEX/pull/2176 and improved.
32-bit signals are a bit more complex than 64-bit due to behaviour
changing depending on if `rt_sigaction` and `sigaction` syscall is used
and if `SA_SIGINFO` is passed in to the flags.
With `SA_SIGINFO` used, both turn in to an `RT` frame, which is encoded
differently than without `SA_SIGINFO`.
Additionally 32-bit signals support both regular Linux stack ABI and
`regparm(3)` ABI.
Without `SA_SIGINFO` then `siginfo_t` is removed from the signal handler
arguments, but most of the rest still remains.
Also two of the arguments to the signal handler are forced to be nullptr
with `regparm(3)`.
> FEXCore: Fixup 32-bit signal handling 

- ThunkLibs/Generator/gen.cpp
- ThunkLibs/include/common/Host.h
- unittests/ThunkLibs/generator.cpp
1) The host library needs to be loaded in the global namespace.
2) We need to use `RTLD_DEFAULT` instead of querying the object
directly.
We need to load the host library in the global namespace so the symbols
end up in the global symbol table. This follows how all these symbols
/usually/ get loaded. Either by linking directly to the library or how
loaders will end up loading these.
We need to use RTLD_DEFAULT to follow symbol overriding rules that tend
to occur. For example, MangoHUD will LD_PRELOAD a library that provides
GLX and EGL symbols. Which FEX's thunk libraries need to pick up this
override.
If we are querying the host library directly then we fail to pickup
these overrides, thus breaking MangoHUD and other overlays.
> Thunks: Fixes host symbol overrides

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Adds HISTCNT/HISTSEG FCADD/FCMLA and MATCH/NMATCH
Knocks out a few TODOs
> ARMEmitter: Add a few missing instructions

- Source/Tools/FEXServer/ProcessPipe.cpp
Fixes this file compiling on musl at least.
POLLREMOVE usage here is technically incorrect as it shouldn't be OR'd with other flags.
But it is also additionally wrong here because the Linux kernel doesn't even support this flag anymore, so it doesn't change behaviour.
> FEXServer: Remove POLLREMOVE usage

- Source/Tools/FEXRootFSFetcher/Main.cpp
Fixes #2356
In the case of the `-y` option being used, it will auto say "yes", but when presented with the distro list this doesn't work. This happens when used on a distro that doesn't have an exact match to what we provide.
Exposes a new option that when presented the distro list, auto select the first option. Solving this issue when automating.
> FEXRootFSFetcher: Support option to auto select first distro

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Finishes off MUL/DIV (predicated) and the remaining integer reduction operations.
> ARMEmitter: Handle SVE predicated mul/div and finish off integer reduction category

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Knocks out two more small classes of instructions
> ARMEmitter: Handle MLA/MLS (vector) and MAD/MSB

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Knocks out the relevant stack management functions. The other variants are SME only
> ARMEmitter: Handle ADDVL/ADDPL and RDVL

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
We can leverage the existing `SVE2IntegerMultiplyVectors` to make these trivial to implement
> ARMEmitter: Handle SVE SQDMULH/SQRDMULH (vector)

- External/FEXCore/Source/Interface/Config/Config.json.in
- Source/Tests/ELFCodeLoader2.h
When used in conjuction with #2345 this is a useful way to enable libSegFault in applications using application profiles.
Very useful for applications and games that use launcher scripts that set LD_PRELOAD to nothing prior to launch.
A user was wanting this.
> ELFCodeLoader: Adds an option to inject libSegFault

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
SelectCC shift wasn't necessary since we just need to ensure the final result is zero when or'd together.
Also operations calculating SF can just use a BFE instead of a shifts with a constant. BFE by immediate is more efficiently encoded in our IR.
> Dispatcher: Minor flags optimization

- Scripts/GenerateSyscallNumbers.py
- Source/Tests/LinuxSyscalls/Arm64/SyscallsEnum.h
- Source/Tests/LinuxSyscalls/x32/FD.cpp
- Source/Tests/LinuxSyscalls/x32/SyscallsEnum.h
- Source/Tests/LinuxSyscalls/x64/SyscallsEnum.h
Similar to our other syscall conflicts, musl/Alpine Linux has a global define that is conflicting with our name here
> Syscalls: Renamed fstatat64 to fstatat_64

- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/Arm64Relocations.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
- External/FEXCore/include/FEXCore/Core/CPUBackend.h
Currently unused (The full data gets thrown away after CompileCode is called), but allows us to separate code and data in what `CompileCode` returns.
This will allow us put a header on JIT blocks which will fix a long outstanding bug where RIP isn't always synchronized on block entry, but since it only needs to synchronize on signal we can rebuild in the handler. This future task will remove the `86dec_SynchronizeRIPOnAllBlocks` config option, but the data will also end up being used for more things in the future.
> Core: Support Data in JIT buffer header

- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- External/FEXCore/include/FEXCore/Core/CPUBackend.h
- External/FEXCore/include/FEXCore/Core/CoreState.h
~~Relies on #2377 to be merged first.~~
This will be used to store various bits of data about the code going
forward.
Currently unused but that will change as we move forward.
> JIT: Adds a JIT data header and tail. 

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
Deduplicates quite a bit of code and centralizes the op handling in one place, as opposed to each individual instruction implementation
> ARMEmitter: Centralize instruction handling for a few categories

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
With this in place, a _VMov isn't necessary for variable blends anymore, since the vector upper lanes are guaranteed to be zeroed out in the 128-bit case.
> VectorOps: Only use VBSL 256-bit path if SVE is present

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
We can use movprfx here to allow compressing the move and bsl operation together on cpus that can handle it.
Noticed after #2386 was merged
> Arm64/VectorOps: Use movprfx with VBSL

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Now all the wide shift categories are handled
> ARMEmitter: Handle predicated wide shifts

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Clears out the scalar CPY broadcasting ops
> ARMEmitter: Handle CPY (scalar) and CPY (SIMD&FP, scalar)

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
A few were logging out the wrong instruction name on a precondition failure.
> ARMEmitter/ASIMDOps: Amend a few error logs

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
A little more straightforward than using VectorImm for the same purpose.
> OpcodeDispatcher: Use VectorZero over VectorImm in InsertPSOpImpl

- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
Fixes #2410
We were pulling the guest RSP before spilling static registers back to the state.
Move this to after we spill SRA state to fix this bug.
Thanks to @ifquant for diving in, identifying, and finding the exact bug.
> Dispatcher: Fixes guest stack register usage

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Take a leaf from the Vector ops and have the jump entry choose the IR op.
Also generate one atomic op and modify the IR type in the locked memory type just like the non locked memory path.
This class of instructions in the number one instruction type percentage wise, so making this more optimal will be a win.
It's a fairly minor optimization so it should be a small impact.
> OpcodeDispatcher: Optimize ALUOp handler

- Scripts/aarch64_fit_native.py
Cortex-X1C and A78C are relatively minor changes to their non-C counterparts. Support classifying them in case clang understands them.
Fixes a minor perf regression noticed on the Lenovo X13s while testing.
> Scripts: Update fit_native script for X1C/A78C

- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
When executing a non-inlined syscall, we spill all static registers. We weren't storing in to the thread context that we have done this. If a signal occured between FEX returning from the syscall (after the blr) and before the `FillStaticRegs` then the signal handler would get the incorrect register state.
This typically manifested as Steam getting a SIGCHLD, trying to recover the guest stack pointer, and it that pointer would be zero or some other corrupt value. Thus crashing inside of the signal handler.
Surprising that we hadn't hit this way more before this point, must have needed hardware that tickled the race condition *just* right.
> Arm64: Fixes a race condition on syscall spilling SRA

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Handles the INDEX instruction.
Also moves some instruction helpers that were public into the private section of the class
> ARMEmitter: Handle SVE index generation category

- Data/AppConfig/VC_redist.x64.exe.json
- Data/AppConfig/VC_redist.x86.exe.json
- Data/AppConfig/vcredist_x64.exe.json
- Data/AppConfig/vcredist_x86.exe.json
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/include/FEXCore/Core/CPUBackend.h
This allows us to not update RIP on block entry, but still allow
reconstructing the RIP up until that point.
While still not full RIP reconstruction, this lets us update the signal
context's RIP just like the `x86dec_SynchronizeRIPOnAllBlocks` without
eating the cost of writing to RIP on block entry.
This was tested on a few Proton games that were using the VC setup files to ensure it still worked as expected.
> Dispatcher: Support reconstructing RIP from block entry

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Adds the remaining instructions for the group and also centralizes them under a single helper implementation, getting rid of a bit more code in the process.
Also adds a check to ensure the registers in the constructive variant of SPLICE are consecutive, and fixes a similar check in the constructive variant of EXT
> ARMEmitter: Finish off SVE Permute Vector - Predicated group

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
IIRC: 
0x10/0x11 in the two byte op table corresponds to MOVUPS
0x28/0x29 in the two byte op table corresponds to MOVAPS
so we were treating both MOVAPS encodings as MOVUPS, unless I'm reading the table wrong.
> OpcodeDispatcher: Handle alignment for MOVAPS a little better

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
We can piggy-back on top of the existing SVEIntegerCompareVector helper to make these trivial to implement.
> ARMEmitter: Handle SVE integer compare with wide elements category

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
Just keeps the use of builtins contained to one place.
> Arm64Emitter: Use bit utils wrapper over __builtin_ffs

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
XMM instances can't use high indices anymore, since we've gotten rid of the only flag that allows this scenario to occur.
> OpcodeDispatcher: Remove now unused _VDupElement path in LoadSource_WithOpSize

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
Fixes a few incorrect instruction names in the logs.
> Emitter/ALUOps: Fix typos in log messages

- External/FEXCore/Source/Interface/Core/ArchHelpers/MContext.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
When we were taking a signal that had a misaligned stack, we would store the host stack at a weird offset.
After that point when we were trying to sigreturn we wouldn't know the alignment of the stack coming back and we would try loading the host stack from the wrong offset. Easy fix is to just align the host stack location.
Fixes Ender Lilies, which was consistently crashing from a SIGCHLD due to having a misaligned stack.
Side-change: Move the cookie check to the start of the restore. Doesn't make sense to check the cookie after restoring state since it could be quite wrong.
> Dispatcher: Fixes crash with misalign stack returning from signal

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/LoadstoreOps.inl
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Expands the `LoadStoreUnsigned` helper to handle everything, including the immediate shifts in a single function. This lets us specify the opcode template in one spot and all its behavior in one spot.
This also gets rid of a bunch of magic values related to the encoding limits of the instructions and makes them named constants, which we can make use of outside the emitter itself to get rid of even more magic constants in the AArch64 JIT backend
> ARMEmitter: Centralize handling for unsigned offset load-stores

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ScalarOps.inl
Same behavior, but collapses some if statements.
> ARMEmitter: Simplify advanced SIMD copy

- Source/Tools/FEXServer/Main.cpp
It looks like `SYSTEMD_EXEC_PID` can leak through to the executable environment in regular situations. Instead let's key off of `INVOCATATION_ID` which doesn't leak through.
Fixes an edge case behaviour where FEXServer wouldn't daemonize in some systemd environments.
> FEXServer: Change systemd service environment variable key

- Data/AppConfig/client.json
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/CPUID.h
This is known to cause issues in some cases. We hit the first game that checks for this bit and early exits if it is found.
Lets the MMORPG Tibia run in non-VM situations.
Looks like they have more checks for VMs other than hypervisor bit, so running under Parallels still won't work. Running on bare Linux is fine.
> CPUID: Adds an config option to hide hypervisor bit

- Source/Common/FDUtils.h
- Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/FileManagement.h
Fixes #2443
I found out with some profiling that this we were spending a decent amount of time with the `openat` syscall in heavily utilized situations. While not super common in active gameplay situations, it matters significantly in loading screens that this is fairly optimal.
The bulk of the time is spent in the emulated files handler to ensure that whatever path we are given, we can capture file paths that we need to emulate. The largest contributor being the std::filesystem::canonical function call.
A couple of optimizations in place here.
1) Do a quick hashmap check right at the start to see if we exactly fit
2) Change from `std::fs::canonical` to `realpath`
3) Switch `GetEmulatedFDPath` to not use optional so it stops building
on the stack
I'm still not super happy with the …
> EmulatedFiles: Optimize openat handler

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
A large amount of size handling in this category is just decrementing the size by 1, so we can tidy up a bunch of conditionals by just doing that instead.
> ARMEmitter: Simplify size handling Advanced SIMD 3 different group

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/LoadstoreOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/ASIMD_Tests.cpp
- External/FEXCore/unittests/Emitter/Loadstore_Tests.cpp
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
A few vector instructions that take register lists often require vector registers within the list to be sequential in the form of an increasing list (modulo the register file size).
For example:
```
v1, v2, v3, v4
```
and
```
v31, v0, v1, v2
```
both fit these requirements.
However, in quite a few instructions that permit it, we don't handle the latter one that wraps around at all. This fixes this by introducing a helper to do all the work for us when it comes to these cases.
Also expands the tests to ensure these cases are handled.
> ARMEmitter: Handle sequential registers in lists nicer

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Registers.h
All other parameter taking constructors for the other register types are explicit, so this just makes behavior more consistent.
> ARMEmitter: Make VRegister constructor explicit

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Registers.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/unittests/Emitter/ASIMD_Tests.cpp
- External/FEXCore/unittests/Emitter/Scalar_Tests.cpp
These can create conversion ambiguity compiler errors and in the worst case, cause the wrong thing to happen. So we can get rid of all the implicit conversion operators, except for the the one to `VRegister`, since it's supposed to be the catch-all type.
For the other cases, we already have explicit conversion functions that can be used instead to specify behavior.
This also catches a few cases where the wrong conversion functions were being called, but happened to work, since they'd implicitly be converted to the right type.
> ARMEmitter: Remove most implicit conversion operators for vector register types

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Registers.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
Adds defaulted comparison operators to the interface, which allows comparisons to be done without directly accessing the index. With these in place, the implicit conversion to uint32_t operators can be removed.
> ARMEmitter: Remove predicate uint32_t conversion operators

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Registers.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
- External/FEXCore/unittests/Emitter/Loadstore_Tests.cpp
Ensures that we're always explicit about the size of a register when using APIs that enforce it.
The only implicit conversions we keep are conversions that convert down to Register, but not anything that converts up the hierarchy or across it.
> ARMEmitter: Remove implicit conversions from Register/XRegister/WRegister

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
Matches the assembly use of it more closely.
> ARMEmitter: Make second sxtw parameter a WRegister

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Registers.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Like with the vector registers, we can remove all implicit conversion operators except the ones that convert down to the base PRegister class.
With this, all of the registers are now adequately constrained, so we shouldn't have any wonky implicit conversions happening anymore.
> ARMEmitter: Remove predicate implicit conversion operators

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Some cases are trivially able to be moved into the implementation function, which deduplicates quite a bit.
Also noticed that some of the floating-point compare instructions were missing (FACGE/FACGT), so those were added in another commit as well.
> ARMEmitter: Tidy up some assertion handling

- Source/Tools/FEXRootFSFetcher/Main.cpp
Switches to the new CDN which is significantly faster and has other benefits.
In order to make sure we don't break old clients, switch to the new link for a few months while leaving the old one operational.
The links file in the old CDN still points to the new rootfs links so they get the performance improvement on old clients still.
> FEXRootFSFetcher: Update link to rootfs links file

- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/FileManagement.h
Need to ensure that dirfd is AT_FDCWD and also need to check flags correctly.
Flags were incorrectly checking mode for O_WRONLY and also we should check for O_APPEND. Split it out to a helper function just so it is easier to see what is going on.
Fixes the issue of proton not finding `/lib64/ld-linux-x86-64.so.2`
> FileManagement: Fixes Proton

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/IR/IR.json
x86's REP STOS instruction is a memset (with element size!) with the
ability to choose a direction of execution.
Additionally it has a feature where if it faults part-way through the
copy, an application can catch the fault and continue afterwards to know
how many bytes got copied.
RCX is the counter which decrements for each element, and RDI is the
memory pointer. On fault these will reflect the last location that was
attempted to be written. FEX doesn't support this behaviour which makes
our lives easier.
Without supporting that feature, this turns in to a directional memset
by element size. Let's remove all the multiple blocks and just emit a
single IR operation to improve performance of the JIT.
Our generated code here was terrible, the IR was terrible, multiblock is
always slow with …
> OpcodeDispatcher: Optimize REP STOS to MemSet operation

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
Turns out these can be nicely simplified to being directly in the template declaration.
Neat little tip pointed out by @neobrain in https://github.com/FEX-Emu/FEX/pull/2444
> ARMEmitter: Simplify uses of IsXOrWRegister

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
The templated variants were never used. Also we can make the remaining non-templated helpers constexpr and simplify them a little as well.
> ARMEmitter: Remove unused helper functions

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
Now that our register types are strongly typed and don't implicitly convert across one another, we can get rid of the templating on some member functions, turning them into normal member functions.
> ARMEmitter/ASIMDOps: Remove unnecessary template constraints

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/IR/IR.json
Just like the `REP STOS` instruction, this removes a fairly nasty bit of
code generation from our dispatcher. This instruction behaves like a
memcpy/memmove when not dealing with the faulting behaviour around the
instruction.
With a microbench things improves this instruction's throughput by 3.5%
to 26.5% depending on operating size.
There is a TODO for implementing this instruction with ARM's future MOPS
instructions which will accelerate this implementation further.
> OpDispatcher: Implements REP MOVS as Memcpy IR op 

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
This shouldn't be exposed in the public section. While we're at it, we can move the precondition checks into the helper itself
> ARMEmitter: Move SVEBitwiseShiftbyVector into private section 

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
While the register size parameter of VExtractToGPR is currently unused, it's correct to differentiate between 128-bit and 256-bit registers here, since this is used for both the SSE and AVX implementation.
No change in behavior, just making the operation less confusing.
> OpcodeDispatcher: Pass full register size through VExtractToGPR

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
These are leftover operations that aren't necessary for these operations anymore
> Arm64/VectorOps: Remove unnecessary EOR in VAddP/VFAddP SVE path

- unittests/ASM/VEX/vpsadbw_256.asm
Meant to change this over when writing the test, but forgot.
> unittests: Change alignment directive in 256-bit VPSADBW test to 32

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Deduplicates some code and centralizes all the assertions. Also finishes off FTMAD, since we can leverage the same helper for it.
> ARMEmitter: Move op and assertions into SVEFloatArithmeticPredicated helper

- External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
Necessary to be glibc allocator clean.
> IntrusiveIRList: Ensure this is using the FEX allocator

- External/FEXCore/Source/CMakeLists.txt
- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Utils/CPUInfo.cpp
- External/FEXCore/include/FEXCore/Utils/CPUInfo.h
- FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
Allocates memory behind our backs. Needed to make CI glibc allocator clean.
> CPUInfo: Switch away from using get_nprocs_conf

- CMakeLists.txt
- External/FEXCore/Source/CMakeLists.txt
- Source/Tests/CMakeLists.txt
- Source/Tools/CMakeLists.txt
Right now cmake doesn't even get past the configuration stage when mingw is used.
If mingw is detected, setup cmake so it can at least configure itself. Will be necessary for cleaning up the rest of the codebase.
> CMake: Get past configuration when mingw is used

- Source/Tests/LinuxSyscalls/FileManagement.cpp
- Source/Tests/LinuxSyscalls/FileManagement.h
- Source/Tests/LinuxSyscalls/Syscalls.cpp
This was completely unused so this just reduces some syscall signal mutex locking around FD operations.
> FM: Remove unused FD to Name mapping

- External/FEXCore/Source/Interface/Core/CPUID.cpp
Even without this being an optimal implementation, enabling this option reduces the amount of time spent in memmove in Hollow Knight.
Before:
```
10.07%  [JIT] tid 284422  [.] /usr/lib/x86_64-linux-gnu/libc.so.6+0x17d780 (0x7fbcef8d6dfd)
```
After:
```
0.53%  [JIT] tid 288916  [.] /usr/lib/x86_64-linux-gnu/libc.so.6+0x17d780 (0x7f0cbe0dc608)
```
> CPUID: Enable FAST REP MOVS

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.h
- External/FEXCore/include/FEXCore/IR/RegisterAllocationData.h
- Source/Tests/IRLoader.cpp
Causes Portal to go from 85FPS to 120FPS on Lenovo X13s.
When running in 32-bit mode we were wasting 8 GPRs and 8 FPRs by still allocating the top 8 registers of each even though 32-bit can't use them.
Reallocate them to be register allocated registers when running 32-bit applications which reduces spills and lowers the cost of spilling/filling SRA registers.
Quite a significant speed boost for a little bit of work.
> Arm64: Reclaim SRA registers on 32-bit

- External/FEXCore/include/FEXCore/fextl/allocator.h
- External/FEXCore/include/FEXCore/fextl/deque.h
- External/FEXCore/include/FEXCore/fextl/forward_list.h
- External/FEXCore/include/FEXCore/fextl/list.h
- External/FEXCore/include/FEXCore/fextl/map.h
- External/FEXCore/include/FEXCore/fextl/set.h
- External/FEXCore/include/FEXCore/fextl/string.h
- External/FEXCore/include/FEXCore/fextl/unordered_map.h
- External/FEXCore/include/FEXCore/fextl/unordered_set.h
- External/FEXCore/include/FEXCore/fextl/vector.h
Completely unused right now, this will very quickly spread throughout the entire codebase.
Currently only containers with FEX's global allocator usage. Any STL class that is allocation free and has been vetted to fit within the guidelines of not allocating memory will get an alias inside of `fextl`.
This means that any std:: namespace usage going forward will need to be scrutinized heavily. As aliasing it will mean it is vetted, otherwise it needs to be checked with FEX CI (once in place) to ensure it doesn't allocate memory behind our back.
Aliases everything we allow from std:: reduces mental burden from needing to check if it is okay to use or not. Additionally it will allow us to quickly pivot to the EASTL if we find as some point during this transition that this will in-fact not …
> FEXCore: Adds fexctl container alias objects

- External/FEXCore/Source/CMakeLists.txt
This dependency was on FEXCore only. Add it to the same dependency definitions that CONFIG_INC is in so that FEXCore_Base picks it up.
Might solve a compile error from FEX Common missing the dependency being generated.
Edit:
Confirms to resolve the compile error.
> FEXCore: IR_INC dependency on FEXCore_Base

- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
When building with the simulator enabled, these aren't used and cause some unused funtion/variable warnings.
We can silence these with [[maybe_unused]], since these are used in non-simulator builds.
> HostFeatures: Mark DCZID related utilities as [[maybe_unused]]

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Makes it consistent with all of the other variable shift IR ops.
Now this won't explode if we ever implement VPSRAVQ from AVX-512
> Arm64/VectorOps: Handle 64-bit elements in VSShr

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
These conditionals were accidentally inverted and were treating 32-bit elements as 64-bit ones, when this is unintended.
Also add missing tests to ensure this doesn't slip through in the future.
> ARMEmitter: Fix treating 32-bit elements as 64-bit with ld1w

- External/FEXCore/Source/Interface/Core/Core.cpp
The previous log in the frontend is super useful when an instruction decoding wasn't supported.
Now that most of AVX is covered, a game will crash on SIGILL (and usually catch it) and close without any indication.
Now if the instruction is decoded but it is invalid for the configuration, still output a message as a good indicator that the game is using instructions that the host doesn't support.
Will let us still pick up on games crashing due to lack of SVE very easily.
> Core: Add a new log message for unsupported instruction

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
- unittests/32Bit_ASM/Primary/Primary_D6.asm
This is an undocumented but supported instruction. It behaves just like an `sbb al, al` but doesn't set flags and is one byte shorter.
The end result is that al is set to 0xFF or 0 depending on if CF is set or not.
> OpcodeDispatcher: Implement support for 32-bit SALC instruction

- Source/Tools/FEXConfig/Main.cpp
When the textual field is changed, that order changes and there would be
a partial resort where the labels would misalign compared to the text
entries.
Fixes that.
> FEXConfig: Fixes misalignment when advanced option is changed. 

- Data/ThunksDB.json
- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
- ThunkLibs/Generator/gen.cpp
- ThunkLibs/Generator/main.cpp
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
- ThunkLibs/libwayland-client/Guest.cpp
- ThunkLibs/libwayland-client/Host.cpp
- ThunkLibs/libwayland-client/libwayland-client_interface.cpp
This PR implements basic support for Wayland thunking on 64-bit guests. Two applications have been tested: [hello-wayland](https://github.com/emersion/hello-wayland) and vkcube.
Wayland is relatively simple to thunk since most of its API is exposed through an internal so-called *wire protocol*, whereby function signatures are encoded as ASCII strings and arguments are serialized to a stack array.
One obstacle for FEX is support for callbacks that also use this wire protocol. Our main job here is to decode the function signatures so that our host trampolines are aware of the arguments they're receiving. This is done by a handy little `ArgType` template which maps an ASCII character into a C type according to the wire protocol. Applying this to the entire signature string allows for …
> Add support for thunking Wayland

- unittests/gcc-target-tests-32/Disabled_Tests
- unittests/gcc-target-tests-32/Known_Failures
- unittests/gcc-target-tests-64/Disabled_Tests
- unittests/gcc-target-tests-64/Known_Failures
This has a race condition with SIGPROF which the Tegra Orin hits consistently. Probably due to a faster timer or something?
> unittests/gcc: Disable mcount_pic test

- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
Found this copy&paste issue while doing the Hangover integration.
Though only checked that compilation doesn't introduce new Warnings.
> Dispatcher: Fixes restoring of AVX state

- External/FEXCore/Source/Utils/Allocator.cpp
- External/FEXCore/include/FEXCore/Utils/Allocator.h
- Source/Tests/FEXLoader.cpp
- Source/Tests/TestHarnessRunner.cpp
This is done by consuming a single page at the end of the current sbrk memory region. Then consuming any remaining bytes that could have potentially ended up in it.
This ensures that glibc won't be able to return 64-bit pointers to 32-bit thunks once the remaining work is in place.
This can be merged independently of the other pull requests.
> Allocator: Disable glibc sbrk allocations

- External/FEXCore/Source/Common/StringConv.h
`std::stoul` and `std::stroull` take a std::string which was converting the string_view to a std::string first. Causing glibc fault testing to catch this since not much uses this.
These will be added to the documentation.
> StringConv: Convert to conversion functions that don't use std::string

- External/FEXCore/include/FEXCore/fextl/fmt.h
fwrite allocates some backing memory for buffering outputs which FEX can't track.
Switch to using `fileno` to get the fd from the FILE and write directly. This will need to be changed for llvm-mingw support but that will come after this.
This will be added to the documentation that we can't use fwrite.
> fextl::fmt: Remove fwrite usage

- External/FEXCore/Source/Utils/Allocator.cpp
- External/FEXCore/Source/Utils/AllocatorOverride.cpp
- External/FEXCore/include/FEXCore/Utils/AllocatorHooks.h
Every time we are calling a function in `FEXCore::Allocator::` this is a
pointer indirection. Which means on x86 it is always a `call [rdi]` and
on AArch64 it is a `ldr x17, [x0]; blr x17;`.
Instead of doing this, use inline functions in the header that call the
correct allocation function directly. This function gets inlined and is
no longer an indirect call.
When compiling with jemalloc, we forward declare the jemalloc function
definitions so we don't have to pull in the entire jemalloc interface in
to the public header definitions.
> Allocator: Remove pointer indirection overhead

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
Fixes #2199
Very few uses actually, we were pretty good at this already.
> OpcodeDispatcher: Move usages of `And(Not(` to Andn

- .github/workflows/ccpp.yml
- .github/workflows/vixl_simulator.yml
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
The dispatcher was saving AVX state even though FEX doesn't support it currently. This is due to it checking for the config option rather than the HostFeatures option.
The `EnableAVX` config option is supposed to be used to inform FEXCore if we want AVX disabled or not when the host supports the feature. In this case it is universally enabled because we haven't encountered any games that have issues with AVX state being saved with signals. (We know they exist, we just don't have configurations for them).
The HostFeatures option `SupportsAVX` is the option that is supposed to be getting used for determining if the runtime AVX feature is enabled. This also had an issue though that this was **also** always enabled if running on an x86 host with AVX, or an ARM host with SVE2-256bit. It was …
> FEXCore: Stop leaking AVX configuration state

- External/FEXCore/Source/Common/StringUtils.h
Use a string_view instead of a fextl::string so this stops allocating memory (stack in the cases I have seen).
Fixes #2562
> StringUtils: Stop allocating TrimTokens

- Scripts/StructPackVerifier.py
- Source/Tools/FEXLoader/LinuxSyscalls/x32/Ioctl/drm.h
Nothing here that changes anything really. Just need to handle `__user` define and a new Aligned Attribute for clang.
i915 still has some changes that we might not be picking up, but that is a known issue and considering i915 doesn't compile on non-x86 platforms I'm inclined to not care.
No uapi changes otherwise.
> Update drm headers to v6.2

- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
FEX might not ever make it to its cleanup routines when exit is used. So make sure to disable the fault checking if exit is used.
Opened #2594 to track this investigation.
> Threads: Disable glibc allocator fault testing with `exit`

- .github/workflows/glibc_fault.yml
This is based on our regular CI runner file with a couple of things stripped out.
- gvisor tests removed because they cause our CI machines pain with tmp/shm mounts
- Thunks disabled since glibc fault testing is incompatible with it
- ARMEmitter tests removed since we don't want to test vixl.
~~First two commits are from #2591 so that needs to be merged first.~~
~~Next commit is from #2592 and needs to be merged first.~~
~~Next commit is from #2593 and needs to be merged first.~~
~~Next commit is from #2595 and needs to be merged first.~~
~~Next commit is from #2596 and needs to be merged first.~~
Fixes #2500
> CI: Adds glibc faulting testing

- unittests/gvisor-tests/Disabled_Tests
- unittests/gvisor-tests/Known_Failures
Somewhere between kernel 5.15 and 6.0 this syscall's behaviour has changed.
The unit test expects -ESPIPE result but new kernels will return 0 (noop_llseek in the source).
The new solidrun board is our first CI machine to be running kernel 6.1 so this needs to be merged before that CI machine can be enabled.
> gvisor: Disable timerfd test

- Source/Tools/CMakeLists.txt
FEXLoader won't ever work in this configuration. This was a mistake to enable.
> FEXLoader: Don't build with mingw

- External/FEXCore/Source/Interface/Core/Interpreter/F80Ops.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/F80Ops.h
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterFallbacks.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Core/CoreState.h
- unittests/ASM/H0F3A/pcmpestri_equal_any.asm
- unittests/ASM/H0F3A/pcmpestri_equal_each.asm
- unittests/ASM/H0F3A/pcmpestri_equal_ordered.asm
- unittests/ASM/H0F3A/pcmpestri_ranges.asm
- unittests/ASM/VEX/vpcmpestri_equal_any.asm
- unittests/ASM/VEX/vpcmpestri_equal_each.asm
- unittests/ASM/VEX/vpcmpestri_equal_ordered.asm
- unittests/ASM/VEX/vpcmpestri_ranges.asm
Handles the rather behavior-abundant PCMPESTRI instruction variants.
We only implement this instruction in this PR, since the fallback itself on top of the tests are quite large. This allows the base implementation to get reviews, making it much nicer to review following instructions that will add handling for implicit lengths and mask handling
> OpcodeDispatcher: Handle PCMPESTRI/VPCMPESTRI

- External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
These are all AVX1, not sure how I missed this.
Sorry @lioncash, four more instructions.
Uncharted legacy of thieves uses `VCVTSD2SS` specifically.
Sackboy also uses `VCVTSD2SS`
The Last of Us also uses `VCVTSD2SS`
Death Stranding also uses `VCVTSD2SS`
Returnal uses `VCVTSS2SD`
> VEXTables: Adds a missing class of AVX instructions

- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
This will use the correct `__cpuid` define, either in cpuid.h or self-defined depending on environment.
Otherwise we would need to define our own cpuid helpers to match the difference between mingw and linux.
> FEXCore: Switch to xbyak for CPUID fetch helpers.

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/CPUBackend.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/LookupCache.cpp
- External/FEXCore/Source/Interface/Core/X86HelperGen.cpp
- External/FEXCore/Source/Utils/Allocator.cpp
- External/FEXCore/include/FEXCore/Utils/AllocatorHooks.h
- External/FEXCore/include/FEXCore/Utils/ThreadPoolAllocator.h
Most cases of direct mmap are just there for virtual memory allocation reasons. We don't usually care about mapping files or other extended behaviour.
Also disables the signal safe compiling with Mingw in the x86Dispatcher as a bonus.
> AllocatorHooks: Adds some mingw allocator helpers

- External/FEXCore/Source/Interface/Config/Config.cpp
- FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
- FEXHeaderUtils/FEXHeaderUtils/Syscalls.h
These use std::filesystem and should be moved over to WIN32 specific code.
Added comments to explain that these are currently placeholders and since we don't do mingw+glibc fault testing these won't get picked up anyway.
> FHU/FS: Create WIN32 helpers for some functions.

- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/UContext.h
There are a handful of siginfo layout types. To determine which layout to use we need to check a combination of si_code and signal number because each one in isolation doesn't explain the layout type.
Once the layout is calculated then calculate the siginfo using that layout type. Adds a couple of different layout types to our guest siginfo_t to handle the previously missing types.
> SignalDelegator: Calculate siginfo layout

- Source/Tools/FEXLoader/LinuxSyscalls/ArchHelpers/MContext.h
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
Fixes #2560
This was a forgotten member of the context that needs to be saved and restored when jumping around the signal state.
When FEX was receiving signals back to back, there was a chance that the signals would ride the edge of having set `InSyscallInfo` in the JIT, which meant the SRA state would get saved once, then another signal would occur with the previous SRA data, saving SRA again. Then when unwinding the frames it would corrupt the SRA registers. This would result in trying to load SRA state that was no longer valid, looking like a crash in the JIT that was hard to see what happens.
Should also make Mono games a little less crash happy.
Cleans up CPUState memcpy as well, since it was a little weird looking.
> SignalDelegator: Make sure to save and restore `InSyscallInfo`

- External/FEXCore/Source/Interface/Core/Interpreter/Fallbacks/InterpreterFallbacks.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/Fallbacks/VectorFallbacks.h
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Core/CoreState.h
- unittests/ASM/H0F3A/pcmpistri_equal_any.asm
- unittests/ASM/H0F3A/pcmpistri_equal_each.asm
- unittests/ASM/H0F3A/pcmpistri_equal_ordered.asm
- unittests/ASM/H0F3A/pcmpistri_ranges.asm
- unittests/ASM/VEX/vpcmpistri_equal_any.asm
- unittests/ASM/VEX/vpcmpistri_equal_each.asm
- unittests/ASM/VEX/vpcmpistri_equal_ordered.asm
- unittests/ASM/VEX/vpcmpistri_ranges.asm
Handles the implicit variant of the string-compare-returning-index instructions. Now all that remains is the masked variants.
> OpcodeDispatcher: Handle PCMPISTRI/VPCMPISTRI

- Source/Tools/FEXLoader/LinuxSyscalls/x32/IoctlEmulation.cpp
These strings don't actually null-terminate and previous checks were working just because it would usually be null terminated due to initialization.
Since this isn't guaranteed, I noticed a failure to determine drm device due to some trailing garbage in the string.
> Ioctl: Ensure DRM name check uses strncmp

- Source/Tools/FEXLoader/LinuxSyscalls/x32/IoctlEmulation.cpp
In the case that an unknown drm device shows up, send it down the default handler. This handler is just a passthrough and assumes that the kernel doesn't have any compat handlers for that device.
This is nicer than crashing or returning EPERM, since then downstream drm drivers like Xe, Asahi, and PVR and still try to run.
We of course still want to run their struct definitions through CI once they go upstream.
> Ioctl: Add default handler for drm

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
All variants of the PCMPXSTRX instructions will take their arguments in the same manner, so we don't need to specify them for each handler.
We can also rename the function to PCMPXSTRXOpImpl, since this will be extended to handle the masking variants of the string instructions.
> OpcodeDispatcher: Simplify PCMPXSTRIOpImpl

- External/FEXCore/include/FEXCore/fextl/memory.h
This ensures we don't hit a programming error since we don't support the array version of this.
> fextl/memory: Don't allow arrays in fextl::make_unique

- External/FEXCore/Source/Utils/LogManager.cpp
- External/FEXCore/include/FEXCore/Utils/LogManager.h
This non-fmt handler is now entirely unused and can be removed.
> LogManager: Remove unused handler

- External/FEXCore/Source/Interface/Core/LookupCache.h
All code paths to this are already guaranteed to own the lock.
The rest of the codepaths haven't been vetted to actually need recursive_mutex yet, but seems likely that it will be able to get converted to a regular mutex with some more work.
> LookupCache: Removes unnecessary recursive lock_guard

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
Platform register stores the TEB region on win32 and needs to be preserved if we're going to overwrite it.
Ensure we do so.
> ARM64Emitter: Ensure platform register is saved on win32

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
Related to #2659 but not necessary directly.
Currently x30(LR) is unused in our RA. In all locations that call out to code, we are already preserving LR and bringing it back after the fact. This was just a missed opportunity since we aren't doing any call-ret stack manipulations that would facilitate LR needing to stick around.
Since x18 is a reserved platform register on win32, we can replace its usage with r19, and then replace r19 usage with x30 and everything just works happily. Now x18 is the unused register instead of x30 and we can come back in the future to gain one more register for RA on Linux platforms.
Also tidies up the RA arrays to be in pairs for easier readability.
> Arm64Emitter: Replace x18 usage with x30

- External/FEXCore/include/FEXCore/Utils/AllocatorHooks.h
This will be used with the TestHarnessRunner in the future to map specific memory regions.
This is only used as a hint rather than exact placement with failure on inability to map. This also hits the fun quirk of 64k allocation granularity which developers need to be careful about.
> Allocator: Adds VirtualAlloc with memory Base hint function

- External/FEXCore/CMakeLists.txt
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.h
This disables some unwinding overhead when FEXCore is already guaranteed to not throw.
> FEXCore: Compile without exceptions

- External/FEXCore/Source/Interface/Core/CPUID.cpp
We don't have a sane way to query cpu index under wine. We could technically still use the syscall since we know that we are still executing under Linux, but that seems a bit terrible.
Disable for now until something can be worked out. Not like it is used heavily anyway.
> CPUID: Disable RDTSCP under wine

- ThunkLibs/libxcb/libxcb_Guest.cpp
- ThunkLibs/libxcb/libxcb_interface.cpp
Forgot to initialize CBDone to false before the helper thread is started.
This fixes an issue where an XCB context is created, then stopped, then another is created but immediately exits because CBDone was still true from the previous run.
Also adds the handler for `xcb_connect_to_fd` so we don't miss that usage.
> Thunks: Fixes xcb helper thread creation

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/ObjectCache/CodeObjectSerializationConfig.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/FEXLoader.cpp
From https://github.com/AsahiLinux/linux/commits/bits/220-tso
This fails gracefully in the case the upstream kernel doesn't support this feature, so can go in early.
This feature allows FEX to use hardware's TSO emulation capability to reduce emulation overhead from our atomic/lrcpc implementation. In the case that the TSO emulation feature is enabled in FEX, we will check if the hardware supports this feature and then enable it.
If the hardware feature is supported it will then use regular memory accesses with the expectation that these are x86-TSO in strength.
The only hardware that anyone cares about that supports this is Apple's M class SoCs. Theoretically NVIDIA Denver/Carmel supports sequentially consistent, which isn't quite the same thing. I haven't cared to check if multithreaded …
> FEXCore: Adds support for hardware x86-TSO prctl

- External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Disabling SRA has been broken a quite a while. Disabling this was instrumental in figuring out the VC redistributable crash.
Ensure it works by reintroducing non-SRA load/store register handlers, and by supporting runtime selectable dispatch pointers for the JIT.
Side-bonus, moves the {LOAD,STORE}MEMTSO ops over to this dispatch as well to make it consistent and probably slightly quicker.
> ARM64: Fixes SRA disabled codepath

- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
No need to use adr for getting the PC relative literal, we can use LDR (literal) to load the PC relative address directly.
Reduces trampline instructions from 3 to 2, also reduces trampoline size from 24-bytes to 16-bytes.
> Thunks: Optimize ARM64 trampoline

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
- unittests/CMakeLists.txt
- unittests/Utilities/CMakeLists.txt
- unittests/Utilities/DeleteOldSHMRegions.cpp
Some of the unit tests we run will leak shm regions. Presumably this is because they never called `shmctl(IPC_RMID)` so the ID is leaked forever.
This can be seen by querying `/proc/sysvipc/shm` to see a list of old shm regions that eventually hit the maximum capacity of 4096 shm ids.
Once CI is done running, run a utility application that all it does is check for SHM IDs that have zero attachments (thus unused), it was created by the UID of the runner, and it is older than ten minutes. At which point it will erase it.
This will fix spurious failures in our CI caused by running out of SHM IDs, previously I had a cron job setup to restart the CI runners every hour or so which caused its own spurious failure problems.
FINALLY this bug was triaged which has been annoying us for...years?
> unittests: Adds step to remove stale SHM regions.

- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
- External/FEXCore/include/FEXCore/IR/IR.h
Wine syscalls need to end the code block at the point of the syscall. This is because syscalls may update RIP which means the JIT loop needs to immediately restart.
Additionally since they can update CPU state, make wine syscalls not return a result and instead refill the register state from the CPU state. This will mean the syscall handler will need to update their result register (RAX?) before returning.
Depends on #2666 for this code to be active but can be merged independently.
> FEXCore: Support Wine syscalls

- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
I forgot that x11 was part of the custom ABI of thunks. #2672 had broken thunks on ARM64. I thought I had tested a game with them enabled but apparently I tested the wrong game.
Not a full revert since we can still ldr with a literal, but we also still need to adr x11 and nop pad. At least removes the data dependency on x11 from the ldr.
> Thunks: Mostly reverts #2672

- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
Investigation in #2589 shows we can push it to this point. 6.3 adds a new prctl that FEX can't enable yet.
> FEXLoader: Allow simulated kernel version up to 6.2

- External/FEXCore/Source/Interface/Context/Context.cpp
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/CPUID.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Core/CPUID.h
- External/FEXCore/include/FEXCore/Core/Context.h
- External/FEXCore/include/FEXCore/Core/CoreState.h
- unittests/ASM/SecondaryModRM/Reg_2_0.asm
This returns the `XFEATURE_ENABLED_MASK` register which reports what features are enabled on the CPU.
This behaves similarly to CPUID where it uses an index register in ecx.
This is a prerequisite to enabling XSAVE/XRSTOR and AVX since applications will expect this to exist.
xsetbv is a privileged instruction and doesn't need to be implemented.
> FEXCore: Implements support for xgetbv

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
- .github/workflows/vixl_simulator.yml
Removes some annotation warnings that have been showing up on the actions results page.
v2 is deprecated so going to v3 is necessary. Apparently this upgrades from Node.js 12 to 16.
> github: Updates some actions to v3

- External/FEXCore/Source/Utils/Telemetry.cpp
- External/FEXCore/include/FEXCore/Utils/Telemetry.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXLoader/IRLoader.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.h
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
When a signal handler is not installed and is a terminal failure, make sure to save telemetry before faulting.
We know when an application is going down in this case so we can make sure to have the telemetry data saved.
Adds a telemetry signal mask data point as well to know which signal took it down.
> Telemetry: Save on signal terminate

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- External/FEXCore/Source/Interface/IR/AOTIR.cpp
- External/FEXCore/Source/Interface/IR/AOTIR.h
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
- External/FEXCore/Source/Utils/Allocator/HostAllocator.h
- External/FEXCore/include/FEXCore/Core/Context.h
- External/FEXCore/include/FEXCore/Core/CoreState.h
- External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
- External/FEXCore/include/FEXCore/HLE/SyscallHandler.h
- External/FEXCore/include/FEXCore/Utils/DeferredSignalMutex.h
- FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
- Source/Tools/FEXLoader/ELFCodeLoader.h
- Source/Tools/FEXLoader/IRLoader.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Memory.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/x32/Memory.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/x32/Semaphore.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/x32/Syscalls.h
- Source/Tools/FEXLoader/LinuxSyscalls/x64/Memory.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/x64/Syscalls.h
- Source/Tools/FEXLoader/VDSO_Emulation.cpp
- docs/DeferredSignals.md
~~First three commits are cherry-picks from: #2490, #2491, #2492~~
This is partial support, we still use sigprocmask based signal deferring in some cases. This replaces the most egregious abuse of it though.
This is a fairly scary change but I've done a bunch of testing to try and make sure nothing has broken. The whole point of this change is to reduce the use sigprocmask system calls by deferring the signal if the signal is received inside of an "uninterruptible" code section. Read the markdown file for more information as to how that exactly occurs.
Very specifically this changes two things:
1) Entry in to "uninterruptible" code section
Before:
```cpp
LoadConstant(ARMEmitter::Size::i64Bit, ARMEmitter::Reg::r0, ~0ULL);
stp<ARMEmitter::IndexType::PRE>(ARMEmitter::XReg::x0, …
```
> Implement support for deferred asynchronous signals

- External/FEXCore/Source/Interface/Core/CPUID.cpp
These two extensions rely on AVX being supported to be used. Primarily because they are VEX encoded.
GTA5 is using these flags to determine if it should enable its AVX support.
> CPUID: Only enable BMI1 and BMI2 if AVX is supported

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
This caught my eye as I was skimming, remove one IR op per FCMOV instruction.
This was just duplicating the generated GPR mask across the FPR.
> X87: Super minor FCMOV optimization

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
Noticed this was slightly unoptimal. Resulting in a 18% code reduction in the case of of a simple four instruction test ASM case.
> OpcodeDispatcher: Optimize EFLAG unpacking

- External/FEXCore/Source/Interface/IR/IRDumper.cpp
This can spuriously end up as a hex number which makes it hard to reason why DCE wasn't deleting IR operations. Ensure it is always a decimal.
> IRDumper: Fixes ssa number in arguments.

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- External/FEXCore/Source/Interface/IR/IR.json
`eor <reg>, <reg>, #-1` can't be encoded as an instruction. Instead use
mvn which does the same thing.
Removes a single instruction from each OF calculation for ADC and ADD.
Also no reason to use a switch statement for the source size, just use
_Bfe and calculate the offset based on operation size.
SBB caught in the crossfire to ensure it also isn't using a switch
statement.
> OpcodeDispatcher: Optimize ADC/ADD OF flag calculation

- Source/Tools/FEXConfig/Main.cpp
This is just confusing end users these days and no longer matters as a debug option.
Remove from the GUI initially, maybe afterwards we will even remove setting this at all and always auto-detect.
> FEXConfig: Removes Emulated CPU cores option

- External/FEXCore/Scripts/json_ir_generator.py
We spent a bit of effort removing 8-bits from this header to get it down to three bytes. This ended up in PRs #2319 and #2320
There was no explicit need to go down to three bytes, the other two arguments we were removing were just better served to be lookups instead of adding IR overhead for each operation.
This now introduced alignment issues that was brought up in #2472. Apparently the Android NDK's clang will pad nested structs like this, maybe to match alignment? Regardless we should just make it be 32-bit.
This fixes Android execution of FEXCore.
This fixes #2472
Pros:
- Initialization now turns in to a single str because it's 32-bit
- We have 8-bits more space that we can abuse in the IR op now
- If we need more than 64-bit and 128-bit are easy bumps in the future
Cons:
- Each IR …
> IR: Pad IROp_Header to be 32-bit in width

- External/FEXCore/Source/Interface/Core/CPUID.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/Fallbacks/VectorFallbacks.h
- unittests/ASM/H0F3A/pcmpistri_ranges.asm
So, uh, this was a little silly to track down. Having the upper limit as unsigned was a mistake, since this would cause negative valid lengths to convert into an unsigned value (woo sign conversions, gotta love 'em!) within the first two flag comparison cases. A -1 valid length can occur if one of the strings starts with a null character in a vector's first element. (It will be zero and we then subtract it to make the length zero-based).
Fixes this edge-case up and expands a test to check for this in the future
> VectorFallbacks: Fix PCMPSTR fallback ZF/SF flag setting 

- Source/Tools/FEXLoader/LinuxSyscalls/x32/Thread.cpp
Not sure how this ever managed to work before this point actually. We were returning a 64-bit pointer when we were supposed to be returning a 32-bit pointer.
Seemingly this was overwriting the len stack variable so then Steam's chromehtml.so library was checking the results thoroughly and detecting that the robust list wasn't setup before this point.
SOMEHOW this worked if FEX was built locally, but broke from the PPA builders? Not sure how that happened, but theoretically on the next PPA release this is now fixed and Steam can run from those builds.
Also when setting the robust list, make sure to return EINVAL if the size doesn't match what's expected there.
> x32/Thread: Fixes robust futex fetching

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
When FEX was updated to reclaim 64-bit registers in #2494, I had mistakenly messed up pair register class conflicts.
The problem is that FEX has r30 stuck in the middle of the RA which causes the paired registers to need to offset their index half way.
This meant that the conflict index being incorrect was always broken on 32-bit applications ever since that PR.
Keep the intersection indexes in their own array so to can be correctly indexed at runtime.
Thanks to @asahilina finding out that Osmos started crashing a few months ago and I finally just got around to bisecting what the problem was.
This now fixes Osmos from crashing, although the motes are still invisible on the 32-bit application. Not sure what other havok this has been causing.
> Arm64: Fixes register pair conflict.

- unittests/ASM/CMakeLists.txt
Allows us to have a place to put helper includes and files that contain macro utilities. This will be nice for making macro files that cut down on verbosity across tests (e.g. Making tests for XSAVE would be way less copy-pastey this way, especially for setting up initial state).
> unittests: Add include search path for asm tests

- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/IR/IR.json
We can handle this in the dispatcher itself, so that we don't need to pass along the register size as a member of the opcode. This gets rid of some unnecessary duplication of functionality in the backends and makes it so potential backends don't need to deal with this.
We can also remove the HasSideEffects JSON boolean from the IR description as well, since we don't actually perform any side-effects, since we only operate directly on the data given to the IR op and that's it.
> IR: Move VPCMPESTRX REX handling to OpcodeDispatcher 

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Previously, the bits that we support in the MXCSR weren't being saved, which means that some opcode patterns may fail to restore the rounding mode properly.
e.g. FXSAVE, followed by FNINIT, followed by FXRSTOR wouldn't restore the rounding mode properly
This fixes that.
> OpcodeDispatcher: Ensure MXCSR is saved/restored with FXSAVE/FXRSTOR

- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
- External/FEXCore/include/FEXCore/Core/CPUBackend.h
FEX's current implementation of RIP reconstruction is limited to the
entrypoint that a single block has. This will cause the RIP to be
incorrect past the first instruction in that block.
While this is fine for a decent number of games, especially since fault
handling isn't super common. This doesn't work for all situations.
When testing Ultimate Chicken Horse, we found out that changing the
block size to 1 worked around an early crash in the game's startup.
This game is likely relying on Mono/Unity's AOT compilation step, which
does some more robust faulting that the runtime JIT. Needing the RIP to
be correct since they do some sort of checking for what the code came
from.
This fixes Ultimate Chicken Horse specifically, but will likely fix
other games that are built the same way.
Fixes …
> JIT: Implement support for per-instruction RIP reconstruction

- External/FEXCore/include/FEXCore/IR/IR.h
Keeps ourselves up to date with the latest major release.
Changelog [here](https://github.com/fmtlib/fmt/releases/tag/10.0.0)
> Externals: Update fmt to 10.0.0

- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
istringstream is a very slow way to parse this, let's make it a bit quicker.
Some implementation numbers:
1. Original implementation - 1833556 calculations per second
2. std::strtoul implementation - 4666818 calculations per second
- 2.54x the istringstream implementation
3. str::from_chars implementation - 5120718 calculations per second
- 1.09x the std::strtoul implementation
- 2.79x the istringstream implementation
> Linux: Optimize CalculateHostKernelVersion

- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
This message is complaining each time VFORK was using with clone, but we are handling VFORK here now.
This is just causing debug messages for no reason. Remove the message and remove the flag removal option.
> Linux: Remove warning that isn't necessary anymore

- External/FEXCore/Source/Interface/Context/Context.cpp
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/include/FEXCore/Core/Context.h
This has been around since the initial commit. Bad idea that wasn't ever thought through. Something about remapping guest virtual and host virtual memory which will never be a thing.
> Context: Removes dead `AddVirtualMemoryMapping` function

- Scripts/Threaded_Lockstep_Runner.py
- Scripts/testharness_runner.py
Fixes #2724
If catchsegv doesn't exist then just remove it from the execution environment.
While nice to have, this shouldn't be mandatory especially with Debian no longer shipping it.
> Scripts: Disable using catchsegv if it doesn't exist

- Source/Common/FEXServerClient.cpp
To make sure we don't have dangling FDs when an application calls execve, enable this flag.
> FEXServerClient: Ensure server socket is created with SOCK_CLOEXEC

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
- External/FEXCore/unittests/Emitter/System_Tests.cpp
Not used currently but will be used in the future.
Needed to rebase vixl on upstream in the process so unittests understand cssc correctly. Which also removed a decent amount of patches from our downstream fork.
> Emitter: Adds support for CSSC 

- CMakeLists.txt
- External/FEXCore/Source/Common/JitSymbols.cpp
- External/FEXCore/include/FEXCore/Utils/AllocatorHooks.h
- Source/Tools/CMakeLists.txt
Fixes a few issues I encountered when trying to build for android (non-termux, via NDK).  A successful build does currently require either using a beta NDK or pulling in a local libc++ through CMake though due to FEX's reliance on std::pmr.
> Some small fixes for android building

- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
This can can issues when running on devices with kernel older than 5.8.
> Linux: Stop using faccessat2 for faccessat emulation

- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/FS.cpp
Fixes a spurious `No such file or directory` error when `ls` is trying to query a path's xattributes that come from the emulated rootfs.
These syscalls don't support the *at variants, so it can't use the optimized `GetEmulatedFDPath` implementation. It must also return an error on a found file path, which makes their implementation be slightly different than the other user of of `GetEmulatedPath`. In the case of error, it must only return an error from the emulated path if it is /not/ ENOENT.
Before:
```
$ FEXInterpreter /usr/bin/ls -alth /usr/bin/wine-stable
/usr/bin/ls: /usr/bin/wine-stable: No such file or directory
-rwxr-xr-x 1 ryanh ryanh 1.1K Sep 24  2022 /usr/bin/wine-stable
```
After:
```
$ FEXInterpreter /usr/bin/ls -alth /usr/bin/wine-stable
-rwxr-xr-x 1 ryanh ryanh 1.1K Sep 24 …
```
> Linux: Handle xattr syscalls with emulated paths.

- FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
In libstdc++ version 13, they moved the implementation of `polymorphic_allocator` to `bits/memory_resource.h`. In doing so they forgot to move the template's default argument to that header. This causes the problem that `bits/memory_resource.h` is included first without the template's default argument defined. This breaking the automatic type deducation of `std::byte`.
Still broken in
[upstream](https://github.com/gcc-mirror/gcc/blob/be240fc6acc9714e66afbfbe6dc193844bfcba05/libstdc%2B%2B-v3/include/std/memory_resource#L79-L83) and is unlikely to be fixed and backported. Since this is the only place we use this type, just fix it here.
Shoutout to Rob Clark for noticing this bug and getting hit by it since they are using a distro new enough to ship libstdc++13.
> FHU: Workaround libstdc++ version 13+ bug

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Utils/Allocator.cpp
- External/FEXCore/Source/Utils/Allocator.h
- External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
- External/FEXCore/Source/Utils/Allocator/HostAllocator.h
- External/FEXCore/include/FEXCore/Core/Context.h
- External/FEXCore/include/FEXCore/Utils/DeferredSignalMutex.h
- FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SyscallsSMCTracking.cpp
When a fork occurs FEX needs to be incredibly careful as any thread
(that isn't forking) that holds a lock will vanish when the fork occurs.
At this point if the newly forked process tries to use these mutexes
then the process hangs indefinitely.
The three major mutexes that need to be held during a fork:
- Code Invalidation mutex
- This is the highest priority and causes us to hang frequently.
- This is highly likely to occur when one thread is loading shared
libraries and another thread is forking.
- Happens frequently with Wine and steam.
- VMA tracking mutex
- This one happens when one thread is allocating memory while a fork
occurs.
- This closely relates to the code invalidation mutex, just happens at
the syscall layer instead of the FEXCore layer.
- Happens as frequently as the …
> Linux: Fixes hangs due to mutexes locked while fork happens.

- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
Only return the particular flags that are being requested in the moment
since compacting them all when requested is fairly slow.
x87 fcmov in particular was requesting all the flags when it only needs
a couple.
This reduces a `fcmovb` instruction count blowup from 103x to 38x. Still
more room to go but this one stood out as being particularly bad.
Old:
```asm
0x0000000265a002bc  10ffffe0    adr x0, #-0x4 (addr 0x265a002b8)
0x0000000265a002c0  f9005f80    str x0, [x28, #184]
0x0000000265a002c4  d2800014    mov x20, #0x0
0x0000000265a002c8  d2800035    mov x21, #0x1
0x0000000265a002cc  d2800056    mov x22, #0x2
0x0000000265a002d0  394b0397    ldrb w23, [x28, #704]
0x0000000265a002d4  d3407ef7    ubfx x23, x23, #0, #32
0x0000000265a002d8  aa1702d6    orr x22, x22, x23
0x0000000265a002dc …
```
> OpcodeDispatcher: Optimize GetPackedRFLAG

- unittests/Utilities/DeleteOldSHMRegions.cpp
Newer libstdc++ moved an internal header include and now this failed to compile.
> unittests: Adds missing header

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/ASM/FEX_bugs/pcmpestri_garbage_rcx.asm
When this instruction returns the index in to the ecx register, this is defined as a 32-bit result. This means it actually gets zero-extended to the full 64-bit GPR size on 64-bit processes.
Previously FEX was doing a 32-bit insert which leaves garbage data in the upper 32-bits of the RCX register.
Adds a unit test to ensure the result is zero extended. Fixes running Java games under FEX now that SSE4.2 is exposed.
> OpcodeDispatcher: Fixes bug with pcmpestri

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/IR/IREmitter.h
- unittests/IR/Correctness/LeftShiftTruncate.ir
Inspired from #2561, these shifts don't need to be masked if we know their operating size up front.
Causes a handful of these to become more optimal.
> OpcodeDispatcher: Optimize some shifts size masking

- CMakeLists.txt
Fixes #2751
Luckily fmt provides an option to disable this.
> CMake: Stop installing fmt

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Easy fixed. Found through inspection.
Before:
```
eor v0.16b, v0.16b, v0.16b
mov v0.s[0], v16.s[0]
mov v4.16b, v0.16b
str s4, [x11]
```
After:
```
str s16, [x11]
```
> OpcodeDispatcher: Optimize MOVSS to memory destination

- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
These address calculations were failing to understand that they can be optimized. When TSO emulation is disabled these were fine, but with TSO we were eating one more instruction.
Before:
```
add x20, x12, #0x4 (4)
dmb ish
ldr s16, [x20]
dmb ish
```
After:
```
dmb ish
ldr s16, [x12, #4]
dmb ish
```
Also left a note that once LRCPC3 is supported in hardware that we can do a similar optimization there.
Found through inspection.
> IR: Optimize vector TSO loadstore address calculation

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Easily fixed. Found through inspection.
Before:
```
eor v0.16b, v0.16b, v0.16b
mov v0.s[0], v17.s[0]
mov v4.16b, v0.16b
mov v16.s[0], v4.s[0]
```
After:
```
mov v16.s[0], v17.s[0]
```
> OpcodeDispatcher: Optimize MOVSS to register

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
Noticed during introspection that we were generating zero constants redundantly. Bunch of single cycle hits or zero-register renames.
Every time a `SetRFLAG` helper was called, it was /always/ doing a BFE on everything passed in to extract the lowest bit. In nearly all cases the data getting passed in is already only the lowest bit.
Instead, stop the helper from doing this BFE, and ensure the OpcodeDispatcher does BFE in the couple of cases it still needs to do.
As I was skimming through all these to ensure BFE isn't necessary, I did notice that some of the BCD instructions are wrong or questionable. So I left a comment on those so we can come back to it.
> OpcodeDispatcher: Remove spurious bfe with flag storing

- FEXHeaderUtils/FEXHeaderUtils/Syscalls.h
Both parameters to getcpu are nullable and FEX relies upon this for CPUID, this fixes an access violation when running Portal under PE FEX.
> FHU: Fix WIN32 getcpu implementation

- Source/Tools/FEXRootFSFetcher/XXFileHash.cpp
Multiply it by 100 to actually show as a percentage, only show two digits past the decimal, and update every second to be more responsive.
> FEXRootFSFetcher: Make verification percent easier to read

- External/FEXCore/Source/Interface/Core/Core.cpp
Not sure why this still existed.
> FEXCore: Removes unused TLS variable

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Allows emitting SVE gather loads, which will be useful for implementing AVX2's gather instructions.
This also adds the scalar + vector variants for the first-faulting load variants as well, since the encoding is trivially derived off of the normal gather loads (we just set bit 13 in the opcode to signify first-faulting variants).
> Arm64/Emitter: Handle LD1{*}/LDFF1{*} scalar + vector load variants

- External/FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
- External/FEXCore/Source/Interface/IR/IRDumper.cpp
- External/FEXCore/Source/Interface/IR/IRParser.cpp
- External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/RAValidation.cpp
- External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
- External/FEXCore/docs/IR.md
- External/FEXCore/docs/OpDispatcher.md
- External/FEXCore/include/FEXCore/IR/IREmitter.h
- unittests/IR/Basic/MemoryData.ir
- unittests/IR/Basic/Sbfe.ir
- unittests/IR/Basic/SetGPR.ir
- unittests/IR/Correctness/AddTruncate.ir
- unittests/IR/Correctness/FPRStoreTruncate.ir
- unittests/IR/Correctness/LeftShiftTruncate.ir
- unittests/IR/Correctness/SubTruncate.ir
This is less noisy with no loss of clarity, and follows the notation used by both LLVM IR and NIR. (So, it should be familiar.)
Change done with:
sed -i -e 's/%ssa/%/g' $(git grep -l '%ssa')
> IR: Print SSA values as %123 instead of %ssa123

- External/FEXCore/docs/OptimizationPasses.md
- docs/DeferredSignals.md
- docs/ReleaseProcess.md
Fixing some minor spelling errors which should not affect functionality but improve the overall quality of documentation.
> fix spelling errors

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- unittests/ASM/FEX_bugs/Test_JP.asm
We store garbage in the upper bits. That's ok, but it means we need to
mask on read for correct behaviour.
> OpcodeDispatcher: Fix and optimize PF calculation

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
This only needs to be loaded when a partial insert needs to be performed, so we can narrow it's scope instead of always loading it in the AVX case.
> OpcodeDispatcher: Narrow use of LoadXMMRegister in StoreResult_WithOpSize

- Data/ThunksDB.json
- FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.h
Removes the @PREFIX_ARCH@ replacement  string in the thunks path.
The library prefix paths now get generated upfront and everything gets replaced to handle the differences between multiarch distros.
Fixes Thunks on Arch and Fedora.
> Thunks: Fixes thunks in non-multiarch

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
We can just hoist the header out of the union, since it's present in all cases. We can also make type querying a little less verbose
> Arm64/Emitter: Simplify SVEMemOperand data union 

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
While we're in the area implementing the Scalar + Vector variants, we may as well cross off the Vector + Immediate variants and complete all of the load variants for the regular LD1{*} loads
> Arm64: Emitter: Handle LD1{*}/LDFF1{*} Vector + Immediate encodings

- CMakeFiles/version_to_variables.cmake
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
- ThunkLibs/libxcb/libxcb_interface.cpp
Our regex would only ever capture a single digit, so versions that had more than one digit per section would lose additional digits.
Fixes and moves the helper to a cmake file to be shared between GuestLibs and HostLibs.
Uses the fix in xcb because Fedora ships an older version that doesn't have some of FEX's newer symbols.
> CMake: Fix pkg version extraction for xcb

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/include/FEXCore/Core/HostFeatures.h
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
Removes one instruction from FILD, or two instructions if the CPU
supports the CSSC extension.
Going from 47 instructions to 46/45.
> OpcodeDispatcher: Minor optimization to FILD

- External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
- External/FEXCore/include/FEXCore/Core/SignalDelegator.h
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.h
There was one holdout variable that was in a TLS object in FEXCore. Move it to the frontend with the rest of the TLS variables.
Allows us to remove "Frontend" TLS management to be the only TLS management.
> SignalDelegator: Moves last TLS variable to the frontend

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
This instruction doesn't match ARM semantics very well since it returns the position of the minimum element.
But at the very least the insert in to the final instruction can be a bit more optimal, Converts an 5 inst eor+mov+mov+mov+mov in to 2 inst mov+mov.
This works because `VUMinV` already zero extends the vector so the position only needs to be inserted at the end.
> OpcodeDispatcher: Minor optimization to phminposuw

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Since we implemented the gather variants, we may as well add the scatters as well for symmetry
> Arm64/Emitter: Handle ST1{*} scatter store variants

- ThunkLibs/libxcb/libxcb_interface.cpp
Somehow this 14 turned in to a 4.
> Thunks/xcb: Fixes typo in version check.

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
We handle the unsized load variants, so we should do the same with the stores.
Noticed this after wrapping up adding the gather/scatter variants
> Arm64/Emitter: Handle unsized contiguous STR variants

- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Removes two member variables that were only assigned to, but never actually used, and moves all members into the private class section. Almost all of the members were only used internally anyway, and for the few accesses outside of the class, we can just add querying accessors for those.
Has the nice effect of putting most of the members in one place.
> OpcodeDispatcher: Remove unused member variables and reorganize

- External/FEXCore/Source/Interface/Core/Frontend.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
Ensures that we handle the AVX2 VSIB byte in a decent way.
As is, we can't compute the [index * scale] variant portion of the entire address operand, since the scale needs to act on every element of the vector after sign extension.
What we can do though, is compute the base address and add the displacement to it ahead of time though.
> OpcodeDispatcher: Handle VSIB byte

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- External/FEXCore/include/FEXCore/Core/X86Enums.h
If we are loading exactly the flags we need from the RFLAGS (ensuring we don't load the reserved flag in bit 1) then we don't need to do a mask on the result.
Additionally there is some bad code-motion around selects that was causing SBFE operations to occur on constants. Ensure that we const-prop any SBFE operations to clean this up.
This PR along with #2783 causes FMOV blow-up to go from 41 instruction to 31 instructions.
> OpcodeDispatcher: Another FCMov minor optimization

- External/FEXCore/Scripts/config_generator.py
- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/include/FEXCore/Config/Config.h
- Source/Tools/FEXConfig/Main.cpp
Allows us to consume an array of strings and convert it to an mask of enum values. This is a quality of life change that allows us to specify a mask of options.
The first configuration option added to support this is to control the vixl disassembler. Now by default the vixl disassembler doesn't disassemble any blocks and needs to be enabled individually.
eg:
```
FEXLoader --disassemble=blocks <args>
FEXLoader --disassemble=dispatcher <args>
FEXLoader --disassemble=blocks,dispatcher <args>
```
Has the additional convenience option of just passing in numbers as well.
```
FEXLoader --disassemble=2 <args>
FEXLoader --disassemble=1 <args>
FEXLoader --disassemble=3 <args>
```
Also of course all of this works through environment variables.
```
FEX_DISASSEMBLE=blocks FEXInterpreter <args> …
```
> FEXCore/Config: Adds support for enum mask configuration array

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
For the unary and unpredicated bitwise ops, we can move the opcode into the implementation function as well as asserts to deduplicate some code.
> Arm64/Emitter: Deduplicate some opcode values

- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
Prevents the code invalidation mutex from being locked as shared recursively, since it is locked before entering ThreadExitFunctionLink and would end up being locked again by ThreadAddBlockLink.
This fixes a deadlock on Windows.
> Jit: Add block links directly through the lookup cache on thread exit

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Now that we have the helper for encoding immediate shifts, we can trivially implement the remaining missing instruction in the bitwise logical unpredicated group.
> Arm64/Emitter: Handle SVE XAR

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Pretty straightforward to handle
> Arm64/Emitter: Handle SVE FP arithmetic with immediate (predicated) group

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/include/FEXCore/Utils/MathUtils.h
- External/FEXCore/unittests/APITests/CMakeLists.txt
- External/FEXCore/unittests/APITests/ILog2.cpp
- External/FEXCore/unittests/CMakeLists.txt
All of these IR operations were being fairly inefficient in their address calculation. All of these are known using power of 2 stride indexing. So all of these can be converted from three instructions to one.
These are always used for x87 stack accesses so each one gets an improvement.
Before:
```asm
0x0000ffff6a800248  d2800200    mov x0, #0x10
0x0000ffff6a80024c  9b007e80    mul x0, x20, x0
0x0000ffff6a800250  8b000380    add x0, x28, x0
0x0000ffff6a800254  fd417805    ldr d5, [x0, #752]
```
After:
```asm
0x0000ffff91e80240  8b141380    add x0, x28, x20, lsl #4
0x0000ffff91e80244  fd417805    ldr d5, [x0, #752]
```
> Arm64: Optimize {Load,Store}ContextIndexed address generation

- ThunkLibs/include/common/Host.h
Fixes #2754
These panicking fallbacks are at times not ending up in as plt calls for some reason that I haven't been able to reproduce locally.
So far the only way I can reproduce is building with Canonical's PPA build system, since rebuilding locally didn't resolve the issue.
This will change the failure mode from these panicking asserts happening at call time, to dlopen failing during relocation when loading the thunk. Which LD_DEBUG=all can be used for debugging relocation failure in that case.
> Thunks: Remove weak symbol definitions

- Data/ThunksDB.json
I was hitting an issue where thunking in Wine+Vulkan applications was breaking unless both OpenGL and Vulkan was enabled.
Turns out this was because Vulkan enabled only XCB, which didn't enable X11. So when XCB is thunked but X11 isn't, this causes weird issues where X11 calls in to XCB functions and gets in desync'ed state. Causing hangs to appear in xcb_take_socket.
Now we can enabled just `Vulkan` as a thunk and it'll work fine.
```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/aarch64/syscall.S:38
#1  0x00007fffe21d3d5c in xcb_take_socket_cb(void*) () from target:/usr/lib/fex-emu/HostThunks//libxcb-host.so
#2  0x00007fffe248b734 in ?? () from target:/lib/aarch64-linux-gnu/libxcb.so.1
#3  0x00007fffe2492e28 in xcb_send_request_with_fds64 () from …
```
> ThunksDB: Adds X11 dependency to XCB

- ThunkLibs/libX11/X11Common.h
- ThunkLibs/libX11/libX11_Guest.cpp
- ThunkLibs/libX11/libX11_Host.cpp
- ThunkLibs/libX11/libX11_interface.cpp
Two bugs here that caused thunking X11 thunking in Wine/Proton to not work.
The easier of the two. The various variadic functions that we thunk actually take key:value pairs where the first is a string pointer, and the value can be various things.
We need to handle these as true key:value pairs rather than finding the first nullptr and dropping the remainder.
Additionally, there are 12 keys that specify a callback that FEX needs to catch and convert to host callable. Wine is the first application that I have seen that actually uses this. If these callbacks aren't wired up then it it can miss events.
The harder of the two problems is the `libX11_Variadic_u64` function was subtly incorrect. Nothing had previously truly exercised this and my test program didn't notice anything wrong while …
> Thunks/X11: Fixes variadic packing and callbacks.

- External/FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
For #2804 so it can compare if GPRs match more easily.
Only adding to GPR and Literal types, since its ambiguous what this would mean for the memory accessing types. Going to leave those other ones alone for now.
> X86Tables: Adds spaceship operator to couple op types

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- External/FEXCore/Source/Interface/IR/Passes/LongDivideRemovalPass.cpp
Warming up to more serious work, but this unit test
```
xor eax, eax
hlt
```
gets a 40% cycle count reduction according to llvm-mca.
---
before assembly:
```
2995: 0x0000000265a0001c  321003e0		orr w0, wzr, #0x10000
2995: 0x0000000265a00020  10ffffc0		adr x0, #-0x8 (addr 0x265a00018)
2995: 0x0000000265a00024  f9005f80		str x0, [x28, #184]
2995: 0x0000000265a00028  2a0403f4		mov w20, w4
2995: 0x0000000265a0002c  2a0403f5		mov w21, w4
2995: 0x0000000265a00030  4a1402b4		eor w20, w21, w20
2995: 0x0000000265a00034  b3407e84		bfxil x4, x20, #0, #32
2995: 0x0000000265a00038  52800015		mov w21, #0x0
2995: 0x0000000265a0003c  390b1395		strb w21, [x28, #708]
2995: 0x0000000265a00040  d35f7e96		ubfx x22, x20, #31, #1
2995: 0x0000000265a00044  390b1f96		strb w22, [x28, #711]
2995: 0x0000000265a00048 …
```
> Optimize `xor %eax, %eax`

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
Lets us hoist out the asserts and also collapse all the branching into one series of operations.
> Arm64/Emitter: Collapse encoding cases for indexed dup 

- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
Need to save and restore LR before branching out to the helpers. Confirmed that the rest of the JIT handles this correctly.
> Arm64: Fixes LR corruption in 128-bit divides

- Scripts/StructPackVerifier.py
python-clang is getting pretty bad with missing cursor kinds these days. This was hit from clang-15, will be required for new CI runners
> StructPackVerifier: Fixes missing cursorkind again

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
- External/FEXCore/include/FEXCore/Utils/ArchHelpers/Arm64.h
Inspired from: https://github.com/dotnet/runtime/issues/8072
Currently FEX is /very/ heavy handed with our backpatching where we wrap every backpatched loadstore with `dmb ish`.
This can be relaxed slightly according to the linked issue.
For TSO load instructions the instruction sequence changes to:
ldr <args>;
dmb ld; <-- Slightly less strict dmb
For TSO store instructions the instruction sequence changes to:
dmb ish; <-- Still the all encompassing dmb
str <args>;
For backpatching loadstores this does the same thing where only one side needs the nop and it uses the same instruction sequence when backpatched.
The minor change is that on load backpatching, we are no longer backing up a single instruction, instead just re-executing the instruction we patched directly.
Took a long time to …
> Arm64: Switch to using half barriers

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Moves some more asserts to be centralized in one place as opposed to being in every individual instruction declaration. It also turns out that we were missing a signed immediate version of cmpne, which is now added.
> Arm64/Emitter: Reorganize some base opcode and assert locations

- External/FEXCore/Source/Interface/Core/Frontend.cpp
insert() will only ever perform an insertion if the relevant element doesn't exist within the set, so we were doing an unnecessary lookup in two spots.
We don't use emplace() here because it will need to construct the key for the element inside the allocated node (since the key may be non-copyable/non-movable), causing an allocation even if an insert doesn't actually occur.
Conversely, insert() will not need to allocate and construct a node ahead of time if an element already exists in the set.
> Frontend: Remove redundant lookups in BranchTargetInMultiblockRange()

- External/FEXCore/Source/Interface/Core/Frontend.cpp
This is assigned to but never used.
> Frontend: Remove unused ModRMDecoded instance

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/IR/AOTIR.cpp
- External/FEXCore/Source/Interface/IR/AOTIR.h
- External/FEXCore/include/FEXCore/Core/Context.h
Makes these a little nicer. Since some of these are part of the interface, this also makes them easier to refactor, since just the declaration would need to change, rather than every implementing class.
> Context: Pull out some long std::function declarations into aliases

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Just moves some base opcodes and asserts into one place. Follow up to #2824
> Arm64/Emitter: Deduplicate some more SVE implementations

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Moves more base opcodes and assertions into internal implementation functions to put them all in one place. We also make some of the assert messages much more informative if they're hit.
This was mainly intended to add missing checks that enforce only using predicates p0 through p7 for instruction groups that require it... but it snowballed into this.
> Arm64/Emitter: Deduplicate some more SVE implementations pt. 2

- External/FEXCore/Scripts/json_ir_generator.py
- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/Source/Interface/Core/Frontend.cpp
- External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
Inspired by #2832 by going through the source and removing uses of `assert`.
assert doesn't work for us in debug builds because some games will capture SIGABRT and continue running. So we need to use FEX's built in assert handlers which call `FEX_TRAP_EXECUTION` which will take down the FEX process as expected.
There wasn't too much usage of this in the source, so this is relatively straightforward.
> FEXCore: Remove erroneous asserts in the project

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
Inspired by #2832, since it was using adds directly. cmn is an alias of adds with the destination register being zr.
> ARMEmitter: Implement cmn alias

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
Now all SVE emitter ops restrict predicate register usage within p0-p7 when necessary
> Arm64/Emitter: Add remaining missing SVE predicate range assertions

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Crosses off the lingering TODOs for this group
> ARMEmitter: Finish off remaining SVE Integer Wide Immediate - Unpredicated categories

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
Adds the Nintendo GameCube aliases for sbc/sbcs.
Crosses two more off #2836
> ARMEmitter: Add ngc/ngcs aliases

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- External/FEXCore/unittests/Emitter/ALU_Tests.cpp
Also corrects a cneg test using CC_AL. The ARM ARM says this shouldn't be using both AL and NV
Crosses three more aliases off #2836
> ARMEmitter: Add cinc/cinv/csetm aliases

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- unittests/ASM/FEX_bugs/SHRD_OF.asm
We were calculating this like the regular SHR instruction which isn't correct.
With this resolved, Denuvo games get slightly farther.
> OpcodeDispatcher: Fixes SHRD by immediate OF flag calculation

- ThunkLibs/GuestLibs/CMakeLists.txt
This will help non-multiarch aware distros
> Thunks: Set bitness flags for 64-bit guests

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/IR/IR.json
Optimizes this instruction from 18 down to 10 instructions.
Fixes #443
Before:
```asm
0x00007fffe2080908  10ffffe0            adr x0, #-0x4 (addr 0x7fffe2080904)
0x00007fffe208090c  f9005f80            str x0, [x28, #184]
0x00007fffe2080910  3dc03cc4            ldr q4, [x6, #240]
0x00007fffe2080914  2f08a705            uxtl v5.8h, v24.8b
0x00007fffe2080918  6f08a706            uxtl2 v6.8h, v24.16b
0x00007fffe208091c  2f08a487            uxtl v7.8h, v4.8b
0x00007fffe2080920  6f08a484            uxtl2 v4.8h, v4.16b
0x00007fffe2080924  6e6784a5            sub v5.8h, v5.8h, v7.8h
0x00007fffe2080928  6e6484c4            sub v4.8h, v6.8h, v4.8h
0x00007fffe208092c  4e60b8a5            abs v5.8h, v5.8h
0x00007fffe2080930  4e60b884            abs v4.8h, v4.8h
0x00007fffe2080934  4e71b8a5 …
```
> OpcodeDispatcher: Optimize PSAD* to use vuabdl{2,} 

- External/FEXCore/Source/CMakeLists.txt
When cmake's `install` function is invoked with a relative path, then it is interpreted as being relative to the `CMAKE_INSTALL_PREFIX` variable.
This variable follows both `DESTDIR` and `CMAKE_INSTALL_PREFIX` so it is best to use relative addresses in the install path.
Thanks for the report Mike!
Fixes #2849
> FEXCore: Ensure that the man page follows DESTDIR

- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- External/FEXCore/include/FEXCore/Core/CPUBackend.h
- External/FEXCore/include/FEXCore/Core/X86Enums.h
This is the first piece of the NZCV flags puzzle. Instead of having 4 distinct bytes for the four SF/ZF/CF/OF flags, we have a single packed 32-bit word, with SF in bit 31, ZF in bit 30, CF in bit 29, and OF in bit 28. This layout matches the structure of arm64's native NZCV register (semantics diverge with the inverted carry flag, though). That means we can calculate the packed flags with the help of arm64 flag setting registers. In other cases we can calculate this packed format in software, but still end up ahead (compared to 4 `strb`s) with clever use of bitwise operations. In particular, arm's shift-then-OR instructions are invaluable for this.
This is showing instruction count improvements on some synthetic unit tests I'm looking at. I haven't benchmarked it. The really fruitful …
> Pack NZCV flags

- External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- External/FEXCore/include/FEXCore/IR/IREmitter.h
Optimizes the instruction blow-up from 36x to 34x.
The issue with this instruction is that AArch64 doesn't do something
like x86 where it sets a flag if the CAS was successful. This means we
need to do additional comparisons after the fact to see if it was
actually successful.
Previously this was implemented as eor+eor+orr+cmp+cset, Now it is
cmp+ccmp+cset, Saving two instructions.
Simple optimization but easy to do. This instruction is still mostly
killed by the overhead of moving registers all over.
Before:
```asm
0x0000ffffe25002ec  10ffffe0            adr x0, #-0x4 (addr 0xffffe25002e8)
0x0000ffffe25002f0  f9005f80            str x0, [x28, #184]
0x0000ffffe25002f4  aa0403f4            mov x20, x4
0x0000ffffe25002f8  aa0603f5            mov x21, x6
0x0000ffffe25002fc  aa0703f6 …
```
> OpcodeDispatcher: Optimize CMPXCHG{8B,16B} final comparison

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
In the non-immediate cases, we can amortize some work between the two flags to come out 1 instruction ahead.
In the immediate case, costs us an extra 2 instructions compared to before we packed NZCV flags, but this mitigates a bigger instr count regression that this PR would otherwise have. Coming out ahead will require FlagM and smarter RA, but is doable.
> OpcodeDispatcher: Optimize rotates

- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
This is more obvious. llvm-mca says TST is half the cycle count of CMN for whatever it's defaulting to. dougallj's reference shows both as the same performance.
> JIT: Use TST instead of CMN

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/32Bit_ASM/Primary/Primary_61_2.asm
Caught this when debugging Stalker, OpenAL does this amazing little hack https://github.com/OpenXRay/xray-15/blob/1390dfb08ed20997d7e8c95147ea8e8cb71f5e86/cs/3rd%20party/OpenAL/OpenAL-Windows/Router/alc.cpp#L1862 that was broken by the FEX behaviour
> Fix 16-bit popa insertion behaviour

- External/FEXCore/Source/Interface/Core/X86Tables/SecondaryModRMTables.cpp
- unittests/32Bit_ASM/SecondaryModRM/Reg_7_4_2.asm
This needs to default to 64-bit addresses, this was previously defaulting to 32-bit which was meaning the destination address was getting truncated. In a 32-bit process the address is still 32-bit.
I'm actually surprised this hasn't caused spurious SIGSEGV before this point.
Adds a 32-bit test to ensure that side is tested as well.
> X86Tables: Fixes CLZero destination address

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/LoadstoreOps.inl
- External/FEXCore/unittests/Emitter/Loadstore_Tests.cpp
Finishes off the missing aliases in #2836
> ARMEmitter: Add missing atomic aliases

- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
This was a debug LoadConstant that would load the entry in to a temprary register to make it easier to see what RIP a block was in.
This was implemented when FEX stopped storing the RIP in the CPU state for every block. This is now no longer necessary since FEX stores the in the tail data of the block.
This was affecting instructioncountci when in a debug build.
> Arm64: Remove erroneous LoadConstant

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/ASM/FEX_bugs/VectorShift_zero.asm
- unittests/ASM/FEX_bugs/VectorShift_zero_256.asm
- unittests/ASM/FEX_bugs/VectorShift_zero_avx_128.asm
All vector shifts by zero were broken on the AArch64 JIT since shift operations by constant encoding of "zero" turns in to a different instruction.
Fixes this by making OpcodeDispatcher not emit zero shifts and also making the JIT treat them as nops or moves in that case.
Fixes a bug uncovered by my instruction auditing.
> FEXCore: Fixes vector shifts by zero

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
`eor <reg>, <reg>, <reg>` is not the optimal way to zero a vector register on ARM CPUs. Instead we should move by constant or zero register to take advantage of zero-latency moves.
> ARM64: Optimize vector zeroing

- External/FEXCore/Scripts/config_generator.py
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- External/FEXCore/include/FEXCore/Config/Config.h
- External/FEXCore/include/FEXCore/Core/HostFeatures.h
- External/FEXCore/include/FEXCore/Utils/EnumOperators.h
This is a /very/ simple optimization purely because of a choice that ARM
made with SVE in latest Cortex.
Cortex-A715:
- sxtl/sxtl2/uxtl/uxtl2 can execute 1 instruction per cycle.
- sunpklo/sunpkhi/uunpklo/uunpkhi can execute 2 instructions per cycle.
Cortex-X3:
- sxtl/sxtl2/uxtl/uxtl2 can execute 2 instruction per cycle.
- sunpklo/sunpkhi/uunpklo/uunpkhi can execute 4 instructions per cycle.
This is fairly quirky since this optimization only works on SVE systems
with 128-bit Vector length. Which since it is all of the current
consumer platforms, it will work.
Requires #2864 to be merged first.
> Arm64: Implement first SVE-128bit optimization 

- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
I use this locally when looking for optimization opportunities in the JIT.
The instruction count CI in the future will use this as well. Just get it upstreamed right away.
> Arm64: Adds stats to the disassembly

- External/FEXCore/Source/CMakeLists.txt
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Context/Context.h
- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/Source/Interface/IR/IRParser.cpp
- External/FEXCore/Source/Interface/IR/PassManager.cpp
- External/FEXCore/Source/Interface/IR/PassManager.h
- External/FEXCore/Source/Interface/IR/Passes.h
- External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRDumperPass.cpp
This is incredibly useful and I find myself hacking this feature in
every time I am optimizing IR. Adds a new configuration option which
allows dumping IR at various times.
Before any optimization passes has happened
After all optimizations passes have happened
Before and After each IRPass to see what is breaking something.
> IR: Adds Option to run the IRDumper with more configurations

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Crosses off the only remaining "normal" FP group that hasn't been implemented. All that remains for FP groups are BFloat and SME-related categories which we don't need to worry about (yet)
> ARMEmitter: Handle SVE FP multiply-add long groups

- External/FEXCore/Source/Interface/Core/Core.cpp
- External/FEXCore/Source/Interface/Core/Frontend.cpp
- External/FEXCore/Source/Interface/Core/Frontend.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- External/FEXCore/Source/Interface/IR/IRDumper.cpp
- External/FEXCore/Source/Interface/IR/IRParser.cpp
- External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
- unittests/IR/Basic/MemoryData.ir
- unittests/IR/Basic/Sbfe.ir
- unittests/IR/Basic/SetGPR.ir
- unittests/IR/Correctness/AddTruncate.ir
- unittests/IR/Correctness/FPRStoreTruncate.ir
- unittests/IR/Correctness/LeftShiftTruncate.ir
- unittests/IR/Correctness/SubTruncate.ir
Requires the IR headerop to house the number of host instructions this code is translating for the stats.
Fixes compiling with disassembly enabled, will be used with the instruction count CI.
> FEXCore: Fixes Arm64 stats disassembly

- CMakeLists.txt
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
With these, only three warnings relating to our use of `offsetof` in the dispatchers and one warning in ImGui remain.
@lioncash Could you double-check that the variables in SVEOps.inl are intentionally unused in Release builds?
> Various warning fixes

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
Adds the only missing implementation category for the first-faulting loads, making the interface more consistent
> ARMEmitter: Handle contiguous first fault load (scalar plus scalar) group

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
I forgot to remove this after implementing the normal gather instruction handling.
> ARMEmitter: Remove resolved TODO comment

- .github/workflows/vixl_simulator.yml
- External/FEXCore/Scripts/config_generator.py
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/include/FEXCore/Config/Config.h
- External/FEXCore/include/FEXCore/Core/CoreState.h
- Source/Common/Config.cpp
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
We don't currently have a device in CI that can run SVE with 128-bit
width registers. Until we have a device with this, make sure the vixl
simulator is also running the ASM tests in this width.
> Github: Adds a CI runner for 128-bit SVE testing 

- .github/workflows/vixl_simulator.yml
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/include/FEXCore/Utils/File.h
- Scripts/InstructionCountParser.py
- Scripts/UpdateInstructionCountJson.py
- Source/Tools/CMakeLists.txt
- Source/Tools/CodeSizeValidation/CMakeLists.txt
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/CMakeLists.txt
- unittests/InstructionCountCI/CMakeLists.txt
- unittests/InstructionCountCI/SecondaryGroup.json
Implements CI for tracking instruction counts for generate blocks of
code when transforming from x86 to ARM64 assembly.
This will end up encompassing every instruction in our instruction
tables similarly to how our assembly tests try to test everything in our
instruction tables.
Incidentally, the data for this CI is generated using our assembly
tests. By enabling disassembly and instruction stats when executing a
suite of instructions, this gives the stats that can be added to a json
file.
The current implementation only implements the SecondGroup table of
instructions because it is a relatively small table and has known
inefficiencies in the instruction implementations. As this gets merged I
will be adding more tables of instructions to additional json files for
testing.
These JSON files …
> FEX: Adds instruction count CI

- External/FEXCore/Source/Interface/Core/Frontend.cpp
- External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
- unittests/ASM/FEX_bugs/adcx_size.asm
When a 32-bit adcx instruction was encountered, it was getting treated as a 16-bit adcx instruction instead. This is because of the 0x66 prefix required to handle this instruction.
Adds a unit test to ensure it doesn't break again.
Instruction count CI caught this while looking at the assembly output.
> FEXCore: Fixes bug with 32-bit adcx

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ScalarOps.inl
Since we have our own now, we can lessen our dependence on vixl by shifting over to our own equivalents
> ARMEmitter: Migrate off vixl float utils

- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/DDD.json
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/SecondaryModRM.json
3DNow! table, H0F3A table, and SecondaryModRM table.
H0F3A table skips the SSE4.2 string instructions because they're
nightmares for now.
> InstructionCountCI: Adds three more instruction tables 

- External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/VEX_map3.json
Pretty much no instructions are optimal here. 64-bit RORX is the
outlier.
> InstCountCI: Adds VEX map3 tables

- External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
I think this was the intended logic?
> ConstProp: Fix set-but-not-used mask variable

- External/FEXCore/Source/Interface/Config/Config.cpp
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/IR/PassManager.cpp
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
Main change here is fixing a logic bug in the IRDumper, using the wrong config option for dumping around each optimization pass versus before and after all passes.
And then automatically enabling one of the dump options if DumpIR has been set.
> Config: Minor changes

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
We already handle the scalar plus immediate variants, so this adds the only other missing variant for them
> ARMEmitter: Handle load/store multiple structures (scalar plus scalar) groups

- Scripts/InstructionCountParser.py
Pretty sure this is why CI is unhappy. If a test in a different file has the same name then it is highly likely to conflict when nasm is generating files and will overwrite and erase, causing CI to break.
Include the incoming json filename as part of the asm keys so it can't conflict here.
> InstCountCI: Ensure output nasm name doesn't conflict

- External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map1.json
We can perform the SQRT first and then broadcast 1.0 into the destination since all the intermediary work is done, meaning we don't have to worry about Dst and Vector aliasing one another
> Arm64/VectorOps: Remove redundant move in VFRSqrt SVE path

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map2.json
We no longer need to do any manual zero-extending here, since this will occur automatically on hardware with SVE when AdvSIMD is used
> OpcodeDispatcher: Eliminate unnecessary moves in AVXVectorUnaryOpImpl

- unittests/CMakeLists.txt
Need to have the vixl disassembler enabled for instcountci.
Also need to make sure the host platform is using the ARM64 JIT.
> InstCountCI: Disables tests with unsupported configurations

- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/SecondaryGroup.json
Some instructions in the SecondaryGroup need RNG support for testing.
> InstCountCI: Adds RNG support

- .github/workflows/instcountci.yml
- External/FEXCore/Source/Interface/Config/Config.json.in
- External/FEXCore/Source/Interface/Core/HostFeatures.cpp
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/CMakeLists.txt
simulator generates some instruction count differences that we don't care about. Just run this on ARM platforms only instead.
> GIthub: Only enable InstCountCI on an ARM platform

- External/FEXCore/Source/Interface/IR/PassManager.cpp
Didn't notice this in the previous PR, When DUMPIR=stderr without and selection of where to place it in PASSMANAGERDUMPIR it was supposed to put the dumper at the end of the passes.
We need to make sure that it it placed at the end of the passes rather than current `it`.
> FEXCore/IR: Fixes bug in IRDumper without specification

- External/FEXCore/include/FEXCore/Config/Config.h
- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.h
Instead of allocating a temporary copy of the string, return a view of
it instead. Should improve the performance of system calls that take
file paths. Since it was allocating a string for every single syscall
that uses them in this case.
> Filemanagement: Optimize GetSelf using a string_view 

- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Forgot to remove this when getting rid of the unnecessary explicit zero-extending behavior (whoops!)
> OpcodeDispatcher: Remove unused variable in AVXVectorUnaryOpImpl

- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- unittests/InstructionCountCI/SecondaryGroup.json
When the cacheline size matches the expected x86 cacheline size then we
can remove the spurious move + add.
> Arm64: Optimize CacheLine{Clear,Clean}

- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- External/FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/VEX_map2.json
Allows the implementations of the vbroadcast instructions to perform the load and broadcast in one operation as opposed to doing the load and then broadcast separately.
Notably, the broadcasting loads can also be used on systems that have SVE 128-bit support as well, not only 256-bit. On non-SVE systems, the AdvSIMD equivalent LD1R is used instead.
> IR: Add VBroadcastFromMem opcode 

- External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
In the case of running on a 128-bit SVE system this predicate wasn't setup. Since we never had any predicate usage before this wasn't an issue. Now that #2914 is using the 128-bit predicate we need to make sure that we are generating it.
> Arm64Emitter: Ensure that 128-bit predicate is generated with SVE

- External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- External/FEXCore/unittests/Emitter/SVE_Tests.cpp
These can be used to allow the 128-bit loads to go down the broadcasting path in VBROADCASTOp in the opcode dispatcher
> ARMEmitter: Handle SVE load and broadcast quadword groups

- External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map2.json
Now all vbroadcast implementations go down the more optimal path.
For non-SVE 128-bit cases where we only have 128-bit wide registers, we behave like ld1rqb and just act as a normal 128-bit load for interface convenience.
> IR: Allow 128-bit broadcasts in VBroadcastFromMem

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
We can make use of TRN1 here to collapse a bunch of these moves.
> OpcodeDispatcher: Improve VMOVDDUP output

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
PSLLIImpl already checks for and handles a shift value of zero.
> OpcodeDispatcher: Remove unnecessary conditionals in {V}PSLLIOp

- FEXCore/include/FEXCore/Utils/LogManager.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXLoader/IRLoader.cpp
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
- Source/Tools/FEXServer/Main.cpp
Avoids the same logic being duplicated 5 times and should make it easier to add or change log levels in the future.
> LogMan: Commonise log level to string conversion

- FEXCore/Source/Utils/FileLoading.cpp
- FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
- Source/Common/Config.cpp
This relies on wine's behaviour of passing through linux paths and env vars, so that the config in the user's linux home directory can be accessed when running FEXCore under wine.
> Support for Config.json loading on WIN32

- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- FEXCore/include/FEXCore/Utils/AllocatorHooks.h
This takes a similar approach to deferred signal handling and allows any given thread to be interrupted while running JIT code by protecting the appropriate page as RO. Then, when the thread then enters a new block, it will try to access that page and segfault. This can then be caught by the frontend where it can recover/edit the context as required.
> FEXCore: Allow for interrupting the JIT on block entry

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
In cases where we have a vector source and destination, we can load the vector by its full size. This lets us skip some unnecessary zero-extending behavior, since we're doing an insert rather than operating on the 64-bit value.
> OpcodeDispatcher: Remove some extraneous MOVs from VMOVSD/VMOVSS

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/VEX_map1.json
We can specify the full vector length when dealing with a source vector to avoid zero-extending the vector unnecessarily. When dealing with a memory operand, however, we only want to load the exact source size.
> OpcodeDispatcher: Remove redundant moves from {V}CVTSD2SI/{V}CVTSS2SI

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/VEX_map1.json
Removes a few unnecessary moves in the vector source operand case by not zero-extending the scalar value, since it's only going to be inserted into another vector after the operation is complete.
> OpcodeDispatcher: Remove unnecessary moves in {AVX}VectorScalarALUOp 

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/VEX_map1.json
Since all we're going to be doing is an insert as the final operation, in the cases where our source is a vector, we can specify the size of the vector rather than the size of the element to avoid doing unnecessary zero-extending.
> OpcodeDispatcher: Remove extraneous moves in {V}CVTSD2SS/{V}CVTSS2SD

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/VEX_map1.json
When dealing with source vectors, we can use the vector length rather than using a smaller size and zero extending the register, especially since the resulting value is just inserted into another vector.
> OpcodeDispatcher: Remove unnecessary moves in {AVX}VectorUnaryOp

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/VEX_map1.json
We dealing with scalar vector sources, we don't need to zero-extend the vector, and we can just use it as is.
> OpcodeDispatcher: Eliminate unnecessary moves in {AVX}VFCMPOp

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/VEX_map3.json
When dealing with scalar source registers, we can opt to not zero-extend the vector and just perform the scalar operation and then insert the result.
> OpcodeDispatcher: Eliminate redundant moves in {AVX}VectorRound

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
FEX doesn't use the platform register on wine platforms so there is no reason to save  and restore it.
On Linux we can still use it at some point but for now it isn't part of our RA.
> Arm64Emitter: Stop saving and restoring platform register

- FEXCore/include/FEXCore/Core/SignalDelegator.h
Not used by FEX today but will be used by the WINE integration.
> SignalDelegator: Allow getting the internal configuration

- FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
- unittests/InstructionCountCI/H0F38.json
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map3.json
This is a little more optimal than XORing the vector by itself.
> Arm64/EncryptionOps: Use MOVI reg, #0 to zero vectors

- FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- unittests/InstructionCountCI/H0F38.json
We can simplify these inserts down to only two inserts.
> OpcodeDispatcher: Improve SHA1MSG1 output

- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
- unittests/InstructionCountCI/Primary_32Bit.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_32Bit.json
This paves the way to optimizing pushes in to both push operations and
push pair operations to more optimally match Arm64 push support.
While this does the first step for supporting the base push, we'll leave
optimizing push pairs to future work.
> OpcodeDispatcher: Implement support for push IR operation

- .github/workflows/instcountci.yml
- FEXCore/Source/Interface/Core/CPUBackend.cpp
- FEXCore/Source/Interface/Core/Interpreter/AtomicOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/AtomicOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Utils/Telemetry.cpp
- FEXCore/include/FEXCore/Core/CoreState.h
- FEXCore/include/FEXCore/Utils/Telemetry.h
Due to Intel dropping support for legacy segment registers[1] there is a concern that this will break legacy 32-bit software that is doing some magic segment register handling.
Adds some simple telemetry for 32-bit applications that when they encounter an instruction that sets the segment register or uses a segment register that the JIT will do a /relatively/ quick four instruction check to see if it is not a null segment.
It's not enough to just check if the segment index is 0 or not, 32-bit Linux software starts with non-zero segment register indexes but the LDT for each segment index is a null-descriptor.
Once the segment address is loaded, the IR operation will do a quick check against zero and if it /isn't/ zero then set the telemetry value.
A very minor optimization that segment …
> FEXCore: Adds telemetry around legacy segment register setting

- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
Oops, this has been broken for a while now.
> FEXInterpeter: Fixes compilation when telemetry is disabled

- FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
Lets us extract the size into one location for easy size changes in the future if necessary.
> Interpreter: Use alias for temporary vector data

- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
Now, if we ever increase our vector sizes, the allocated data elements will follow suit without needing to remember to handle this as well.
> Interpreter: Tie SSA data elements to supported vector width

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/SecondaryGroup.json
In the SSE and lower cases, we don't need to do anything, since the value is already in the destination.
While super unlikely, we can simply do nothing faster regardless
> OpcodeDispatcher: Handle zero immediate shifts better

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
Our store will already zero-extend if the vector is 128-bit.
> OpcodeDispatcher: Remove redundant move in AVXVectorScalarALUOpImpl

- FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
- unittests/InstructionCountCI/Secondary_OpSize.json
Just use the full register size and store the lower bits.
> X86Tables: Optimize MOVLPD stores 

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map2.json
We already do a zero-extend if necessary in StoreResult.
This also lets us unify both the SSE and AVX handling code.
> OpcodeDispatcher: Remove unnecessary move from VPHMINPOSUW

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map2.json
We already zero-extend on a store if necessary.
> OpcodeDispatcher: Remove unnecessary moves from AVXVariableShiftImpl

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
These zero-extensions will already happen automatically if necessary.
> OpcodeDispatcher: Remove unnecessary moves from AVX conversion operations

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map_group.json
These zero-extensions will occur automatically when applicable.
> OpcodeDispatcher: Remove redundant moves from AVX immediate shifts

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
Zero-extension will occur automatically when necessary upon storing.
> OpcodeDispatcher: Remove unnecessary moves from AVX register shifts

- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize.json
This now uses the new load element IR operation and makes these
instructions optimal.
LRPCPC3 will introduce instructions in the future for TSO emulation to
help these operations, but that doesn't exist today.
> OpcodeDispatcher: Optimize MOVLP{S,D} loads 

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map3.json
We already zero-extend on stores when necessary.
> OpcodeDispatcher: Remove unnecessary moves from AVX inserts

- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize.json
Loads can turn in to element Loads.
Stores can turn in to element stores.
These four instruction variants are now optimal.
~~Requires #2963 to be merged first.~~
> OpcodeDispatcher: Optimize MOVHP{S,D}

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map3.json
Zero-extension will happen if necessary upon storing.
> OpcodeDispatcher: Remove redundant moves in AVX blend special cases

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/DDD.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/VEX_map1.json
We can be more optimal on the selects. This makes 3DNow! and SSE packed
min/max operations optimal.
> Arm64: Optimize VFMin/VFMax

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
Zero-extension will already occur if necessary upon storing.
> OpcodeDispatcher: Remove unnecessary moves in AVXVFCMPOp

- FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/VEX_map3.json
This can be used for the scalar conversions instead of always using the vector variants. Also corrects an oversight on the AdvSIMD side of things where rounding nearest would be using `frinti` (host rounding mode) instead of `frintn`.
While we're in the area, we can also remove unnecessary moves on the AVX side of things, where we were doing a manual zero-extension when we didn't need to.
> Arm64/ConversionOps: Add scalar support to Vector_FToI 

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map2.json
Zero-extension will occur automatically if necessary.
> OpcodeDispatcher: Remove redundant moves from VPACKUSOP/VPACKSSOp

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map2.json
Zero-extension will occur automatically if necessary upon storing.
> OpcodeDispatcher: Remove redundant moves from remaining AVX ops

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map1.json
If Dst and Vector1 alias one another, then we can perform the operation without needing to move any data around.
> Arm64/VectorOps: Remove redundant moves from SVE VURAvg if possible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map1.json
Given the operation is:
```
Dst = Vector1 / Vector2
```
If Dst and Vector1 alias one another, then we can just perform the division as is without any moving of data around.
> Arm64/VectorOps: Remove moves from SVE VFDiv if possible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map1.json
We can perform these operations in place if the destination and first source alias one another.
> Arm64/VectorOps: Remove redundant moves from SVE VFMin/VFMax when possible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map2.json
When the destination and first source alias, we can perform the operation in place without needing to move any data around.
> Arm64/VectorOps: Remove redundant moves from SVE V{S,U}Min/V{S,U}Max when possible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
If the destination and true vector alias one another, then we can perform the operation in place instead of moving data around.
> Arm64/VectorOps: Remove redundant moves from SVE BSL when possible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map3.json
- unittests/InstructionCountCI/VEX_map_group.json
When our destination aliases the vector to be shifted, we don't need to emit a movprfx
> Arm64/VectorOps: Remove redundant moves from SVE variable/immediate/vector shifts when possible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map2.json
We don't need to perform a move if some vectors alias the destination
> Arm64/VectorOps: Remove redundant moves from VSQXTN2/VSQXTUN2/VSQSHL/VSRSHR

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map_group.json
We don't need to do any moves here is the destination aliases the lower bits.
> Arm64/VectorOps: Remove redundant moves in SVE VExtr when possible

- FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
Makes them equal feature-wise to the vector variants
> Arm64/ConversionOps: Add missing half-precision conversions to scalar functions

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map3.json
Zero-extension will occur automatically upon storing if necessary.
> OpcodeDispatcher: Remove redundant moves from PCLMULQDQ and AES operations

- FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/Secondary_OpSize_SVE128.json
- unittests/InstructionCountCI/Secondary_OpSize_SVE256.json
- unittests/InstructionCountCI/VEX_map1.json
SSE implementations are now optimal.
SVE-128bit operation makes it more optimal.
Interestingly when SVE-256bit is supported, the 128-bit operation gets worse.
> OpcodeDispatcher: Optimize PMULH{U,}W using new IR operations

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/Secondary_OpSize_FCMA.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/Secondary_REPNE_FCMA.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map1_FCMA.json
This extension was added with seemingly Cortex-A710 and turns this
instruction in to two instructions which is quite good.
~~Needs https://github.com/FEX-Emu/FEX/pull/2994 merged first.~~
Huge thanks to @dougallj for the optimization idea!
> OpcodeDispatcher: Optimize addsubp{s,d} using fcadd 

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/VEX_map1.json
SSE version is now optimal and AVX version gets rid of a redundant move.
> OpcodeDispatcher: Optimize cvtps2pd 

- FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/VEX_map1.json
1) In the case that we are converted a GPR, don't zero extend it first.
2) In the case that the scalar comes from memory, load it first in an
FPR and converted it in-place.
These are now optimal in the case of AFP is unsupported.
> OpcodeDispatcher: Generate more optimal code for scalar GPR converts

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/VEX_map1.json
Removes a redundant move between registers and makes it optimal.
Also removes a couple redundant moves on the avx version.
> OpcodeDispatcher: Optimizes movq

- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
This previously used `Round_Nearest` which had a bug on Arm64 that it actually was always using `Round_Host` aka frinti. Ever since 393cea2e8ba47a15a3ce31d07a6088a2ff91653c[1] this has been fixed so that `Round_Nearest` actually uses frintn for neaest.
This instruction actually wants to use the host rounding mode. Once issue with this is that x87 and SSE have different rounding mode flags and currently we conflate the two in our JIT. This will need to be fixed in the future.
In the meantime this restores behaviour that it actually uses the host rounding mode, which fixes black screen and broken vertices in Grim Fandango Remastered.
[1] e89321dc602e35cbb1382b35ac2b35e7e417ef92 for scalar.
> X8764: Ensure frndint uses host rounding mode

- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
When the application calls exit_group we no longer need to care about cleanup because the entire process group is leaving.
Just immediately call exit group and get out. Might revisit this in the future.
Fixes #2752
> Linux: Call exit_group when application tries

- unittests/InstructionCountCI/VEX_map3.json
Just to ensure we capture the nop nature of passing in the rotate amount of the operating size.
> InstCountCI: Test rorx at max mask size

- FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRParser.cpp
- FEXCore/include/FEXCore/IR/IR.h
- FEXCore/include/FEXCore/IR/IREmitter.h
- unittests/IR/Basic/Sbfe.ir
- unittests/IR/Correctness/AddTruncate.ir
- unittests/IR/Correctness/LeftShiftTruncate.ir
- unittests/IR/Correctness/SubTruncate.ir
The number of times the implicit size calculation in GPR operations has bit us is immeasurable and was a mistake from the start of the project. The vector based operations never had this problem since they were explicitly sized for a long time now.
This converts the base IR operations to be explicitly sized, but adds implicit sized helpers for the moment while we work on removing implicit usage from the OpcodeDispatcher.
Should be NFC at this moment but it is a big enough change that I want it in before the "real" work starts.
> IR: Convert all Move+Atomic+ALU ops from implicit to explicit size

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- unittests/32Bit_ASM/FEX_bugs/adc.asm
Noticed that we hadn't ever enabled this, which was a concern when our
GPR operations weren't as strict about leaving garbage in the upper bits
when operating as a 32-bit operation.
Now that our ALU operations are more strict about enforcing upper bit
zeroing we can enable this.
This causes Half-Life: Source FPS to get to > 200FPS finally. Causes
significant performance improvements for 32-bit games because we're no
longer redundantly moving registers before and after every operation.
Causing a bunch of 3-4 instruction sequences to convert to 1.
> IR/Passes/RA: Enable SRA for 32-bit GPRs

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/include/FEXCore/IR/IREmitter.h
This one was already explicit sized. Just convert it over to OpSize.
> IR: Removes bfi from variable size

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- FEXCore/include/FEXCore/IR/IREmitter.h
Saw a few locations in here that we operate things at 64-bit unconditionally around pointer calculation. Will be coming back for those when running in 32-bit mode.
This is the last of the implicit sized ALU operations! After this I'll be going through the IR more individually to try and remove any stragglers.
Then should be able to start cleaning up and actually optimizing GPR operations.
> IR: Removes implicit sized add

- FEXCore/Source/Interface/IR/IRDumper.cpp
> IR: Adds IR::OpSize to IRDumper

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/H0F38.json
This instruction has xmm0 be one of the implicit sources. We were
loading xmm0 twice. https://github.com/FEX-Emu/FEX/pull/2700 would also fix this but that breaks other
things for some reason.
This was already optimal when one of the two explicit sources wasn't xmm0. So made sure to add those to InstCountCI.
> OpcodeDispatcher: Optimize BLENDV when xmm0 is one of the sources 

- FEXCore/Source/Interface/Core/CPUBackend.cpp
- FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
- FEXCore/include/FEXCore/Core/CoreState.h
- FEXCore/include/FEXCore/IR/IR.h
- unittests/InstructionCountCI/H0F38.json
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map3.json
- unittests/InstructionCountCI/VEX_map_group.json
A bunch of the AES operations take a zero register upfront and we
currently materialize it for each instruction.
Considering that most AES operations are used back to back, we can
eliminate these materializations by caching it between instructions.
Additionally removes a move in the optimal case when destination matches
the state register, which is exactly what the SSE operation ends up
doing.
AESKeyGenAssist has an edge case that if the destination RA overlaps the
zero register then we still need to eat a move, hopefully doesn't happen
too frequently in practice. This is also the lesser used instruction so
it isn't a big deal. RA constraints could solve that still.
Looking between the disassembly trees for back to back operations:
Original:
```asm
aesenc  xmm2, xmm1
aesenc  xmm3, xmm1 …
```
> Arm64: Optimize AES operations by caching a zero register 

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
InstCountCI doesn't cover branch instructions so needs manual inspection.
Branch instruction assembly:
```asm
; Header
adr x0, #-0x4 (addr 0xffffe228005c)
str x0, [x28, #184]
; Calculate return address
mov w20, #0xa
movk w20, #0x1, lsl #16
; Calculate target RIP (Only +1 in this instance)
add x21, x20, #0x1 (1)
; Push ret
str x20, [x8, #-8]!
; Load L1 code cache base
ldr x0, [x28, #1864]
; Calculate offset
and x3, x21, #0xfffff
add x0, x0, x3, lsl #4
; Load 128-bit values from base + offset
ldp x1, x0, [x0]
; Compare if L1 target RIP is current RIP
cmp x0, x21
; b.ne to dispatcher
b.ne #+0x8 (addr 0xffffe2280094)
; Jump to block target
br x1
; Dispatcher path. Load dispatcher PTR
ldr x0, [x28, #1776]
; Store current RIP to CPU state so dispatcher can pick it up
str x21, [x28]
; Branch to …
```
> OpcodeDispatcher: Optimize calls with push

- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
Picked up on more games exiting with exit_group that I want to ensure their telemetry data gets saved. Implement support for this.
> Syscalls: Fix telemetry with exit_group

- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
/home/alyssa/FEX/Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp:1546:7: error: use of undeclared identifier 'CrashMask'
CrashMask |= (1ULL << Signal);
> SignalDelegator: Fix build with telemetry disabled

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/GdbServer.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.h
Currently FEX's internal EFLAGS representation is a perfect 1:1 mapping between bit offset and byte offset. This is going to change with #3038. There should be no reason that the frontend needs to understand how to reconstruct the compacted flags from the internal representation.
Adds context helpers and moves all the logic to FEXCore. The locations that previously needed to handle this have been converted over to use this.
> Context: Adds helper to reconstruct and consume packed EFLAGS

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- unittests/FEXLinuxTests/tests/signal/signal_flags.cpp
Currently in main today, FEX fails to compact OF/CF/ZF/SF and PF.
This is due to recent optimizations with flag calculations on each of
these. Now that we have a centralized location where we compact and set
our internal representation of flags we can do this in one location.
Sorry @alyssarosenzweig, I sniped this before you had a chance to do it
> OpcodeDispatcher: Fixes NZCV and PF flag compacting 

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
This class is very expensive to initialize so if you happen to have the disassembler configuration enabled you were eating a very bad initialization cost for no reason.
Only initialize the data member if any disassembler runtime option is enabled, this completely removes the overhead.
> Arm64: Only allocate vixl::Decoder if enabled

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
- unittests/InstructionCountCI/Primary_32Bit.json
- unittests/InstructionCountCI/Secondary.json
Save 1 instruction for all add/sub/cmp-like instructions by deferring part of the AF calculation. on top of #3035
> Defer AF extract

- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
Fixes a critical regression from #3057.
> FileManagement: Fix inverted boolean check for procfs/interpreter support

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/PrimaryGroup.json
Removes todo from explicit size PR. Saves one instruction.
> OpcodeDispatcher: Update 32/64-bit RCR for operating size

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/PrimaryGroup.json
Removes todo from explicit size PR. Saves one instruction.
> OpcodeDispatcher: Update 32/64-bit RCL for operating size 

- FEXCore/Source/Interface/IR/IR.json
CRC32 is always a 32-bit sized operation even with a 64-bit source value.
This doesn't change any InstCountCI results.
> IR: Changes crc32 operation to always return a 32-bit result.

- Source/Tools/FEXLoader/ELFCodeLoader.h
We have supported this since #163 but we haven't been exposing the feature in hwcap2.
We have exposed it in CPUID this entire time, just not in hwcap2.
> ELFCodeLoader: Expose FSGSBase in getauxval HWCAP2

- FEXCore/Source/Interface/Core/CPUID.cpp
Missed with #2490.
This changes behaviour of glibc's memmove slightly, seems to recover a bit of performance on Half-Life 2's title screen.
> CPUID: Enabled Enhanced REP MOVSB/STOSB

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/DDD.json
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/VEX_map1.json
Move instruction to itself here is a nop.
Need to be careful about AVX operations which use a different handler
since those might actually zero the upper bits on 128-bit move
Unlikely that this ever gets hit by a real compiler.
> OpcodeDispatcher: Optimize NOP vector move

- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/FEXServer/SquashFS.cpp
waitpid can return early if interrupted due to EINTR. Loop on this case and try again.
> Tools: Fixes usage of waitpid in the face of EINTR

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/Secondary.json
Removes a redundant move, making it optimal now.
> OpcodeDispatcher: Optimize 32-bit bswap 

- FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/ASM/Secondary/shufps_optimization.asm
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/VEX_map1.json
Hits a whole bunch of common cases, most of which then emit optimal code
generation.
Two cases that use VInsElement hit the RA quirk where the SRA
destination is dead but RA doesn't see it, so it ends up doing a couple
moves. If RA gets fixed then those two moves will go away.
There are definitely still cases that we could emit more optimal code.
Additionally we could implement a TBL2 IR operation to do a LUT approach
for ones we don't cover.
Problem with implementing a TBL2 ir operation is that we have no way to
ensure registers are sequential so we would need to always do moves
```asm
ldr v2, <LUT Table>
mov v0, v16
mov v1, v18
tbl v16.16b, { v0.16b, v1.16b }, v2.16b
```
Which to be fair isn't terrible, and if we're lucky that the guest uses
sequential registers we can naturally get the …
> OpcodeDispatcher: Optimize a bunch of shufps variants 

- unittests/InstructionCountCI/Secondary_OpSize.json
I managed to miss a whole section of instructions from the secondary opsize tables. This resulted in four instructions missing from the database.
Adds cmppd, pinsrw, pextrw, and shufpd which are all non-optimal instruction implementations.
> InstCountCI: Adds missing instructions from Secondary OpSize tables

- Source/Tools/CodeSizeValidation/Main.cpp
If CI faults out due to a bug then we would have no log as to which instruction caused the issue.
I find myself adding this each time an assert fires to see what instruction it was working on. Just add it directly.
> InstCountCI: Add log before compiling instruction

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map3.json
Cleans up the code which had special cased some 32-bit optimization
which is unnecessary now that both 8-bit and 16-bit are also optimized.
When FEX does a VExtractToGPR, the result is zero extended to the full
GPR register size. This means we don't need to do a zero extend when
storing to a guest GPR.
Makes pextr{b,w} optimal now.
~~Needs https://github.com/FEX-Emu/FEX/pull/3088 merged first.~~
> OpcodeDispatcher: Optimize pextr{b,w} 

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map3.json
Inserting from a GPR and memory can both be optimized. These are now
optimal
~~Needs https://github.com/FEX-Emu/FEX/pull/3088 merged first.~~
> OpcodeDispatcher: Optimize pins{b,w,d,q}

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/H0F3A.json
Optimal blendps is worst case 2 instructions.
FEX's RA doesn't quite get there since it can't see through multiple
instructions with SRA destinations. That'll be fixed in the future.
Optimal blendpd is always one instruction, one is a no-op.
We always hit this.
> OpcodeDispatcher: Optimize blendp{s,d}

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
Most of these finish in a couple of seconds. Reordering the tests makes PRs that fail CI provide quicker feedback.
PRs that change e.g. code gen will need to wait a couple of seconds longer for feedback, but that's reasonable since running the ASM tests to begin with already took a while before.
> CI: Run tests with <30s runtime first

- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- unittests/InstructionCountCI/Primary_32Bit.json
- unittests/InstructionCountCI/Secondary_32Bit.json
{Load,Store}RegisterSRA always loads or stores GPRSize. 8-bit and 16-bit
are vestigial and all OpcodeDispatcher usage will load the full GPR size
(32-bit or 64-bit) and then extract or insert as necessary.
This cleans up a few bits of codegen in InstCountCI.
> FEXCore: Minor optimization to StoreRegisterSRA 

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/include/FEXCore/IR/IREmitter.h
Changes the helper which all the source uses to still calculate the size
implicitly. This is going to take a while to convert all implicit uses
over to the explicit operation.
Get us started by at least having the IR operation itself be explicit.
This is taking the same idea as #3073 but doing it more slowly so we don't break anything.
> IR: Changes Select operation to not have implicit sizes 

- FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/H0F38.json
16-bit MOVBE is a bit of a special case where it loads 16-bits in to the
bottom of the GPR without clearing the upper bits of the register.
Which means 32-bits or 64-bits depending on operating mode.
Arm64 doesn't support a 16-bit bswap so it needs to operate at 32-bits
instead. We then can insert the resulting bits of the 32-bit rev with a
bfxil in to the lower bits of the resulting destination register.
This allows 16-bit movbe to be optimal now.
> OpcodeDispatcher: Optimize 16-bit MOVBE 

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/H0F38.json
The only version of this instruction that was generating optimal code
was the one with 64-bit destination and source.
Optimizes the rest of the operating sizes so that they are all optimal
at one instruction translations
> OpcodeDispatcher: Optimize CRC32 

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize_SVE128.json
- unittests/InstructionCountCI/Secondary_SVE128.json
Wide shifts under SVE use 64-bit source elements. If a smaller element
overlaps the 64-bit shift element then it uses that shift
eg:
- Src1[15:0] >> Shift[63:0]
- Src1[31:16] >> Shift[63:0]
- Src1[47:32] >> Shift[63:0]
- Src1[63:48] >> Shift[63:0]
- After this point it will switch to the next 64-bit shift element
- Src1[79:64] >> Shift[127:64]
- Src1[95:80] >> Shift[127:64]
- Src1[111:96] >> Shift[127:64]
- Src1[127:112] >> Shift[127:64]
As seen, we can skip the duplication of the scalar element if the OpSize
is 64-bit, this makes MMX emulation slightly more optimal here.
This also means that a few instructions that weren't claimed to be
optimal actually are since they need the duplication operation (which
vixl always labels as a mov).
> Arm64: Optimize wide shifts slightly for 64-bit OpSize

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUID.cpp
Hades and the vcruntime hits this very hard in memmove.
`86.56%  [JIT] tid 458574        [.] JIT_0x18000c375_0x7fffc94790c8`
```asm
0x00007fffc94790f8:  ldaprb  w3, [x2]
0x00007fffc94790fc:  stlrb   w3, [x1]
0x00007fffc9479100:  add     x1, x1, #0x1
0x00007fffc9479104:  add     x2, x2, #0x1
0x00007fffc9479108:  sub     x0, x0, #0x1
0x00007fffc947910c:  cbnz    x0, 0x7fffc94790f8
```
This performance is terrible because Cortex's LRCPC performance is bottom-tier. Work around the performance issue by forcing things to do larger moves with vector moves instead.
> FEXCore: Disable Enhanced REP MOVSB if Atomic TSO is enabled

- FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/include/FEXCore/Core/CPUBackend.h
This wasn't implemented initially for the interpreter and x86 JIT.
This meant we are maintaining two codepaths. Implement these operations in the interpreter and x86 JIT so we no longer need to do that.
The emitted code in the x86 JIT is hot garbage, but it's only necessary for correctness testing, not performance testing there.
> FEXCore: Implements support for shifted bitwise ops

- FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
While we're in the same relevant area, we can also covert LastAccessType into an enum class
> DeadContextStoreElimination: Silence unused function warning 

- unittests/InstructionCountCI/VEX_map3.json
Allows viewing the codegen for cases where conditional zeroing is performed.
Also fixes up the vperm2f variants shorthanding one of the registers to make everything a little more explicit.
> InstCountCI/VEX_map3: Add missing zeroing vperm2f128/vperm2i128 test cases

- FEXCore/Source/Interface/Core/HostFeatures.cpp
This was clobbering the BMI2 boolean unintentionally.
> HostFeatures: Fix x86 CLWB support check

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/ASM/VEX/rorx.asm
- unittests/InstructionCountCI/H0F38.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/SecondaryGroup.json
- unittests/InstructionCountCI/SecondaryModRM.json
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map3.json
- unittests/InstructionCountCI/VEX_map_group.json
There are a few cases where we were emitting code when we didn't really need to, or could emit less.
> OpcodeDispatcher: Handle RORX corner cases better

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/VEX_map2.json
We can remove some unnecessary moves for the 32-bit cases and collapse the operations down to a single instruction.
> OpcodeDispatcher: Improve output of SHLX/SHRX/SARX

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Seems like this was a type from 8d11073, since we'd be moving into a temporary and then never use it.
We currently don't have usages of this shift IR op yet, so better to catch this ahead of time than not at all
> Arm64/VectorOps: Fix SVE aliasing-path  move in VSShr

- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Registers.h
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Ensures that if our temp vectors change in the future that this is caught at compile-time rather than runtime if not accounted for.
> Arm64/VectorOps: Assert VTMP1 and VTMP2 are sequential in VTBL2

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
In the event the destination and lower source are the same, then we don't need to perform any moves. Makes this consistent with the other IR ops that don't move on aliasing destination and source registers
> Arm64/VectorOps: Elide moves in ASIMD VUShrNI2 if possible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/H0F3A.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map3.json
If none of the vectors alias the destination, then we can eliminate an extra move and usage of a temporary.
> Arm64/VectorOps: Improve handling of 128-bit vector VInsElement

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
If the destination and lower data alias, we can avoid needing to move into a temporary.
> Arm64/VectorOps: Elide moves where applicable in 128-bit VSQXTUN2

- CI/FEXLinuxTestsThunks.json
- Data/ThunksDB.json
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
- ThunkLibs/libfex_thunk_test/Guest.cpp
- ThunkLibs/libfex_thunk_test/Host.cpp
- ThunkLibs/libfex_thunk_test/api.h
- ThunkLibs/libfex_thunk_test/lib.cpp
- ThunkLibs/libfex_thunk_test/libfex_thunk_test_interface.cpp
- unittests/FEXLinuxTests/CMakeLists.txt
- unittests/FEXLinuxTests/tests/CMakeLists.txt
- unittests/FEXLinuxTests/tests/thunks/thunk_testlib.cpp
- unittests/POSIX/CMakeLists.txt
- unittests/gcc-target-tests-32/CMakeLists.txt
- unittests/gcc-target-tests-64/CMakeLists.txt
- unittests/gvisor-tests/CMakeLists.txt
This adds a new FEXLinuxTest written against a custom `libfex_thunk_test` library. `libfex_thunk_test` allows us to define interfaces specifically to trigger thunk generator edge cases that couldn't easily be tested for in actual libraries.
The new test opens a third category of thunk-related tests:
* unittests/ThunkLibs: Unit tests that check the syntax tree of `thunkgen` code output and (in the future) results of data layout analysis (no runtime behavior is checked)
* unittests/ThunkFunctionalTests: Integration tests that runs simple applications (e.g. glxinfo) to verify basic functionality of real-world libraries works
* FEXLinuxTests/thunk_testlib: Mixed unit/integration tests that benefit from us controlling the interfaces in `libfex_thunk_test`. Individual properties of the thunk …
> unittests: Add test thunk library

- FEXCore/Source/Common/JitSymbols.cpp
- FEXCore/Source/Common/JitSymbols.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
- FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
- FEXCore/Source/Interface/IR/AOTIR.cpp
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
While this interface is usually pretty fast because it is a write and forget operation, this has issues when there are multiple threads hitting the perf map file at the same time. In particular this interface becomes a bottleneck due to a locking mutex on writes in the kernel.
The situations when this bottleneck occurs is when a bunch of threads get spawned and they are all jitting code as quickly as possible. In particular Geekbench's clang benchmark hits this hard where each CPU thread spends ~40% CPU time on all eight CPU threads because they are stalled waiting for this mutex to unlock.
To work around this issue, buffer the writes a small amount. Either up to a page-ish of data or 100ms of time. This completely eliminates threads waiting on the kernel mutex.
- Around a page of buffer …
> FEXCore/JitSymbols: Buffer writes to reduce overhead

- ThunkLibs/libwayland-client/Guest.cpp
- ThunkLibs/libwayland-client/Host.cpp
- ThunkLibs/libwayland-client/libwayland-client_interface.cpp
This allows zink-on-Wayland to function in FEX. To verify it properly works, support for APIs used by Super Meat Boy itself was added as well, such that this game runs under Wayland now.
For testing, I verified SMB runs both with and without zink enabled:
```
SDL_VIDEODRIVER=wayland EGL_PLATFORM=wayland ./SuperMeatBoy
SDL_VIDEODRIVER=wayland EGL_PLATFORM=wayland MESA_LOADER_DRIVER_OVERRIDE=zink ./SuperMeatBoy
```
I only tested on llvmpipe (`LIBGL_ALWAYS_SOFTWARE=1`), since virgl seemingly lacks the GL extensions required by SDL's wayland video driver.
> Thunks/wayland: Add support for APIs required by zink and Super Meat Boy

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- unittests/InstructionCountCI/Secondary.json
Renames the explicit sized one to `SelectCC`
Cleans up a bit of duplicated code.
> OpcodeDispatcher: Removes non-explicit SelectCC function 

- FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/x86_64/AtomicOps.cpp
- FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/SecondaryGroup.json
This is an atomicFetchCLR, removes two mvn instructions that are back to
back negating the source.
We didn't have this instruction combination in InstCountCI so will be a
bit hard to see.
> OpcodeDispatcher: Optimize lock btr 

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/CMakeLists.txt
- Source/Windows/CMakeLists.txt
- Source/Windows/Defs/ntdll.def
- Source/Windows/Defs/wow64.def
- Source/Windows/WOW64/BTInterface.h
- Source/Windows/WOW64/CMakeLists.txt
- Source/Windows/WOW64/IntervalList.h
- Source/Windows/WOW64/Module.cpp
- Source/Windows/WOW64/libwow64fex.def
- Source/Windows/include/wine/debug.h
- Source/Windows/include/wine/unixlib.h
- Source/Windows/include/winternl.h
- Implements the WOW64 BT API using FEXCore, allowing the unix-side of wine to run as ARM code, with FEX only being called into to run the PE-side x86 application or wine code. WOW64 itself handles most of the dirty work that FEXLoader/LinuxSyscalls end up doing so the implementation here is comparatively small.
- At the moment the boundary between ARM and x86 code is at the syscall/unixcall level, so the resulting performance is likely only a slight improvement over FEXLoader + (hypothetical) 32 bit thunks. However this paves the way for significant improvements in the future, extending the WOW frontend to support ARM64EC/CHPE-style interop with a custom ABI, so that DXVK and wine DLLs can run as native code. Most of this code can also be reused for 64-bit support.
- Currently depends on …
> Add WOW64 JIT frontend

- FEXCore/Source/Interface/Config/Config.cpp
This would have caused core to try and initialize a custom core on Arm64, which causes a std::function assert because it doesn't support that.
Users would likely get hit by this immediately since we deleted the interpreter and shifted all the core numbers.
> Config: Fixes core sanitization

- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
The range was slightly incorrect which mostly wouldn't have caused issues.
The lowest byte would have just generated slightly less optimal code. The upper byte could have generated broken code, which our CI couldn't catch since TSO instructions only get enabled when multiple threads are in-flight.
Easy enough to fix.
> ConstProp: Fixes unscaled signed 9-bit range

- FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
Ever since we reordered registers in `X86Enums.h` this has silently been broken. This wasn't hit because RCLSE has been broken ever since SRA was added, so inlinesyscalls just weren't ever happening.
Quick fix while I think of a way to more strictly correlate these registers so it doesn't happen again.
> Arm64: Fixes inline syscalls

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- unittests/InstructionCountCI/x87.json
The bug that was causing crashes with this was due to inline syscalls.
Now that this is fixed we can re-enable store->load operations.
This allows constant propagation to work significantly better, which
means inline syscalls start working again. This can significantly
improve syscall performance in some cases.
This is most likely to improve performance in dxsetup and vc_redist but
hard to get a real profile.
Additionally this will let us inline cpuid results in the future which
is pretty nice.
~~Needs #3142 merged first~~
> RCLSE: Optimize redundant store->load operations

- Source/Common/FEXServerClient.cpp
This option was disabled a few months ago when we switched the server
socket from a filesystem unix socket to an abstract socket.
This partially broke our chroot scripts which relied on this option
existing.
Readds support for an explicitly named abstract socket named from
config.
This is a workaround for dealing with chroots that change users.
They end up changing a user while doing operations and then can't
connect to the FEXServer anymore because environment variables have been
wiped away.
> FEXServerClient: Adds back ServerSocketPath config option 

- .github/workflows/instcountci.yml
- Source/Tools/CodeSizeValidation/Main.cpp
Now that InstCountCI has proven itself a workable solution, change the CI solution so that CI fails if there is any difference.
- If instruction count has changed then it can fail directly  in the run step
- CI then runs the `instcountci_update_tests` target which updates the git repo with the new data
- If there is any changes in the git repo then fail CI. This means there was a difference.
- diff file is uploaded as an artifact to quickly see why something changed and the dev can quickly create a patch with it.
This fixes the issue that semi-conflicting instruction changes could previously merge and produce unexpected results and we don't detect it. Plus improves workflow for people that don't directly work with InstCountCI every day.
> InstCountCI: Fail CI if there was any difference.

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
- .github/workflows/hostrunner.yml
- .github/workflows/instcountci.yml
- .github/workflows/mingw_build.yml
- .github/workflows/vixl_simulator.yml
These overlapping names make it impossible to ensure all checks are required to pass before merge.
Unique names will fix this.
> Github: Changes jobs to have unique names

- FEXCore/Source/CMakeLists.txt
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/PassManager.cpp
- FEXCore/Source/Interface/IR/PassManager.h
- FEXCore/Source/Interface/IR/Passes.h
- FEXCore/Source/Interface/IR/Passes/InlineCallOptimization.cpp
- FEXCore/Source/Interface/IR/Passes/SyscallOptimization.cpp
If we const-prop the required functions and leafs then we can directly
encode the CPUID information rather than jumping out of the JIT.
In testing almost all CPUID executions const-prop which function is
getting called. Worst case that I found was only 85% const-prop rate.
This isn't quite 100% optimal since we need to call the RCLSE and
Constprop passes after we optimize these, which would remove some
redundant moves.
Sadly there seems to be a bug in the constprop pass that starts crashing
applications if that is done.
Easily enough tested by running Half-Life 2 and it immediately hitting
SIGILL.
Even without this optimization, this is stil a significant savings since
we aren't jumping out of the JIT anymore for these optimized CPUIDs.
> PassManager: Optimize out CPUID and XGetBV calls

- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/x87_f64.json
Adds support for the tests to set environment variables just like the asm tests.
This gets used to turn on the reduced precision mode.
Then adds all the x87 tests to be ran in this reduced precision mode.
> InstCountCI: Support f64 reduced precision mode tests

- ThunkLibs/HostLibs/CMakeLists.txt
The interface files themselves don't use FEXLoader. Only the final library does.
Speeds up build times of some of the thunk targets, allowing for quicker development iteration cycles (e.g. while rebasing branches).
> Thunks: Avoid recompiling thunk interfaces on FEXLoader changes

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
Eliminate a pile of moves/uxt.
> OpcodeDispatcher: Don't mask logic op inputs

- ThunkLibs/HostLibs/CMakeLists.txt
Linking will fail on clang if `--no-undefined` is used while address sanitizer is enabled. See https://github.com/google/sanitizers/issues/380 for details.
As a workaround, we can just disable the flag for ASan builds.
> Thunks: Fix AddressSanitizer build

- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- unittests/InstructionCountCI/x87_f64.json
Reduces the blowup for FLDCW and FCHS a bit.
> X87F64: Use Bfe for rounding mode, FCHS use float instruction

- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/x87_f64.json
- `_VFAbs` added to IR, implemented with fabs arm instruction.
- X87F64 FABS implementation updated to use it.
Reduces fabs instruction count by two :tada:
> X87F64: Implement FABS with vector instruction

- Data/AppConfig/steam.json.in
This was only required on x86 devices trying to escape the emulation. Since x86 is now remove, this is entirely unnecessary.
When Steam launches applications with `/bin/sh`, this will remain under the emulation and not escape these days.
> AppConfig: Removes Steam config

- .github/workflows/instcountci.yml
- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/CMakeLists.txt
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXLoader/IRLoader.cpp
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
- unittests/CMakeLists.txt
- unittests/InstructionCountCI/Secondary_OpSize_SVE128.json
- unittests/InstructionCountCI/x87.json
This is a quality of life improvement for people that want to tinker
with the InstCountCI but they may not necessarily have an Arm64 device
available immediately for poking.
As long as the vixl disassembler is enabled then the InstCountCI tests
can run and get bit-accurate encodings just like on an Arm64 device.
This also ensures that behaviour is consistent with or without the vixl
simulator enabled which is very important when running on x86 hosts.
> InstCountCI: Enable running on x86 hosts 

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- unittests/InstructionCountCI/Secondary_OpSize_SVE256.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map1_FCMA.json
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map3.json
- unittests/InstructionCountCI/VEX_map_group.json
Some very minor optimizations that I saw we were missing
- Minor optimization in vzeroall to take advantage of `movi` directly to the destination register instead of using a temporary.
- Allow RA to pre-alias and pre-colour AVX registers, which removes a TON of redundant moves in AVX operations.
- 218 instructions went from non-optimal to optimal
> Minor AVX optimizations

- Source/Tools/FEXLoader/LinuxSyscalls/x32/Time.cpp
This syscall requires a valid pointer otherwise it returns EFAULT. When going through the glibc helper it can crash before reaching the raw syscall even.
> Linux: Fixes warning in 32-bit clock_settime

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- Source/Tools/CodeSizeValidation/Main.cpp
Enables in InstCountCI so Pi users can run InstCountCI can run the tests without breaking on crypto operations.
When crypto is enabled or disabled just wholesale change AES, CRC32, and PMULL 128-bit in one step. We don't really care about partial support here.
> FEXCore: Support crypto extensions in HostFeatures override

- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
Also disable AFP under the vixl simulator by default since it doesn't support it.
> InstCountCI: Support overriding AFP features

- Scripts/InstructionCountParser.py
- unittests/InstructionCountCI/CMakeLists.txt
This will be used to move AFP tests to a sub-directory
> InstCountCI: Fixes recursive tests with same filename

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/DDD.json
- unittests/InstructionCountCI/RPRES/DDD.json
- unittests/InstructionCountCI/RPRES/Secondary.json
- unittests/InstructionCountCI/RPRES/Secondary_REP.json
- unittests/InstructionCountCI/RPRES/VEX_map1.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/VEX_map1.json
This allows us to use reciprocal instructions which matches precision of
what x86 expects rather than converting everything to float divides.
Currently no hardware supports this, and even the upcoming X4/A720/A520
won't support it, but it was trivial to implement so wire it up.
> FEXCore: Implements support for RPRES 

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- FEXCore/include/FEXCore/Core/X86Enums.h
- Scripts/json_config_parse.py
- Source/Tools/FEXLoader/HarnessHelpers.h
Six of the EFLAGS can't be used directly in a bitmask because they are
either contained in a different flags location or has multiple bits
stored in it.
SF, ZF, CF, OF are stored in ARM's NZCV format in offset 24.
PF calculation is deferred but stored in the regular offset.
AF is also deferred in relation to the PF but stored in the regular
offset.
These /need/ to be reconstructed using the `ReconstructCompactedEFLAGS`
function when wanting to read the EFLAGS.
When setting these flags they /need/ to be set using
`SetFlagsFromCompactedEFLAGS`.
If either of these functions are not used when managing EFLAGs then the
internal representation will get mangled and the state will be
corrupted.
Having a little `_RAW` on these to signify that these aren't just
regular single bit representations …
> FEXCore: Renames raw FLAGS location names to signify they can't be used directly

- unittests/InstructionCountCI/Atomics.json
This adds all the missing atomic tests in to their own tests files. This includes all of them except a few choice ones that are in their original files.
- BTC, BTR, BTS  are in their Secondary/SecondaryGroup files
- CMPXCHG, CMPXCHG8B, CMPXCHG16B are in their Secondary/SecondaryGroup files
- These always imply lock semantics even without the prefix.
> InstCountCI: Adds missing atomic tests

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ScalarOps.inl
- FEXCore/unittests/Emitter/SVE_Tests.cpp
- FEXCore/unittests/Emitter/Scalar_Tests.cpp
Removes the need for an annoying switch statement with scalar operations for the most part.
> ArmEmitter: Adds sized Scalar 1 source and 2 source helpers

- unittests/InstructionCountCI/FEXOpt/MultiInst.json
- unittests/InstructionCountCI/FEXOpt/MultiInst_AFP.json
Some simple tests to showcase instructions that we can optimize.
- Back to back pushes could be optimized
- Back to back scalar vector operations can be optimized
- Show with AFP that back to back scalar is already optimal
- Also ensures we don't break this stage.
> InstCountCI: Adds some multi instruction tests

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/VEX_map3.json
By allowing junk in the upper bits, we can avoid an unnecessary move, since we'll be ignoring them in the following ROR instruction anyway.
> OpcodeDispatcher: Remove redundant moves from rorx

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
Allows for easier expansion without needing to expand the function definitons.
Also makes a few usages significantly less verbose and makes specifying options a little more declarative, rather than having to memorize what each argument is specifying.
> OpcodeDispatcher: Put extra LoadSource options in a struct

- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/AFP/VEX_map1.json
- unittests/InstructionCountCI/RPRES/VEX_map1.json
- unittests/InstructionCountCI/RPRES/VEX_map1_AFP.json
- unittests/InstructionCountCI/Secondary_OpSize_SVE256.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map1_FCMA.json
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map3.json
- unittests/InstructionCountCI/VEX_map_group.json
Removes the truncating move that we perform inside the StoreResult function and instead delegates the responsibility to the instruction implementations themselves.
This removes a lot of redundant moves that occur on 128-bit variants of AVX instructions.
Also fixes a weird case where we were handling 128-bit SVE in VBroadcastFromMem when we already have AdvSIMD instructions that will perfom the zero-extension behavior for us.
> OpcodeDispatcher: Remove unnecessary 128-bit truncating moves from StoreResult

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/ASM/VEX/vpavgb_aliasing.asm
- unittests/ASM/VEX/vpavgw_aliasing.asm
- unittests/InstructionCountCI/VEX_map1.json
We can perform less moves by checking for scenarios where aliasing occurs. Since addition is commutative (usually, general-case anyway), order of inputs doesn't strictly matter here.
> VectorOps: Handle SVE VURAvg a little better

- ThunkLibs/libvulkan/libvulkan_interface.cpp
These interfered heavily with pending changes in #3135 (within multiple patches). Let's reapply the reordering once the dust has settled instead.
> Thunks/vulkan: Revert reordering changes from 180d16af7a

- Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp
When a syscall from the *at series is provided an FD but the path is absolute then dirfd should be ignored. We weren't correctly doing this. Now if the path is absolute, but set the argument to the special AT_FDCWD..
Fixes #3204
> Linux: Fixes issue with *at syscalls with absolute paths not working

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/VEX_map1_FCMA.json
If the source registers don't alias the destination, then we can safely move the lower bits over to it without using a temporary.
> VectorOps: Handle SVE VExtr a little better

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/RPRES/Secondary_REP.json
- unittests/InstructionCountCI/RPRES/Secondary_REP_AFP.json
- unittests/InstructionCountCI/RPRES/VEX_map1.json
- unittests/InstructionCountCI/RPRES/VEX_map1_AFP.json
Noticed this during code investigation, these two operations were
swapped.
Would have caused issues if anything supported RPRES today.
> JITArm64: Fixes bug in rpres scalar operations 

- Source/Tools/FEXLoader/HarnessHelpers.h
This lets most of the ASM tests run on 16K Linux hosts which is good because I have a Mac and I'm bad at computer.
> FEXLoader: Query runtime page size

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- FEXCore/include/FEXCore/IR/IR.h
- unittests/InstructionCountCI/FEXOpt/MultiInst.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
Previously this moved two constant, did a compare and a csel. Four
instructions in total. It also corrupts NZCV which we want to use for
other things.
This new codegen emits one constant and one subtract instruction, two
instructions total and doesn't touch NZCV.
More optimal!
> OpcodeDispatcher: Optimize DF pointer offset calculation

- unittests/InstructionCountCI/SecondaryGroup.json
- unittests/InstructionCountCI/Secondary_OpSize.json
We only had the move to memory destination version, ensure we test to GPR as well.
> InstCountCI: Adds two missing variants of movd/movq

- unittests/32Bit_ASM/FEX_bugs/rep_lods_bug.asm
This PR has a bug around flags calculation and REP LODS{B,W,D,Q}. This currently passes on main but fails on #3162.
Bug only occurs in 32-bit instead of 64-bit with the same test. Should help diagnose the bugs in #3162.
> unittests: Adds test for bug from #3162

- Source/Tools/FEXLoader/HarnessHelpers.h
Just allocate a single page that we query at runtime.
> TestHarnessRunner: Don't hardcode stack allocation to 4096 bytes

- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
- ThunkLibs/include/common/Guest.h
Function pointers (either host-side or guest-side) weren't supported on 32-bit previously. However, it turns out only these minor fixes are needed to get them working:
* `uintptr_t` is replaced with `uint64_t` in the guest-side thunking headers, since 64-bit pointers are expected by the host-side thunking runtime (`LinkAddressToFunction`/...)
* Tweak the inline assembly on `CallHostFunction` to read the target function address (similarly to the 64-bit path, the code is chosen more or less by trial-and-error such that the compiler doesn't overwrite the `mm0` register before we read it)
* `THUNK_ABI` is used in more places, and `[[gnu::fastcall]]` is replaced by `__attribute__((fastcall))` since clang doesn't understand the former
* JIT logic around function pointer invocation is updated …
> Thunks: Fix function pointer support on 32-bit

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/Atomics.json
- unittests/InstructionCountCI/FlagM/Atomics.json
- unittests/InstructionCountCI/FlagM/Primary.json
- unittests/InstructionCountCI/FlagM/PrimaryGroup.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
Secondary ALU operations were missed and when the operation is 4-bytes
in size we can also allow garbage upper bits since the JIT will emit a
32-bit operation for this instruction which is safe.
Optimizes some bad codegen around 32-bit ALU operations.
> OpcodeDispatcher: Allow garbage in upper bits for more ALU ops 

- ThunkLibs/Generator/analysis.cpp
- ThunkLibs/libX11/libX11_interface.cpp
- ThunkLibs/libXext/libXext_interface.cpp
Also cleaned up the surrounding code a bit, particularly since it redundantly checked a complex subcondition twice.
This should fix thunks building on Ubuntu 20.04, where EGL was failing due to `XDisplay` being an incomplete type (even though it's only ever used in an `assume_compatible_data_layout` context).
> Thunks: Skip data layout analysis for types that are always assumed compatible

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/DDD.json
Instead of using VInsElement in pi2fw and pf2iw, just use uzp1 to ensure
we don't unintentionally add to RA pressure.
Additionally we can generate the constant needed for pmulhrw directly
using the movi instruction. Converts two instructions in to one.
Under FEX's current constraints this makes all 3DNow! instructions
optimal.
> OpcodeDispatcher: Optimize a few 3DNow! operations 

- FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/DeadCodeElimination.cpp
When the result of an atomic fetch operation is unused then we can
safely convert it to a non-fetching version of the operation.
This happens hundreds of times per process as far as I can tell. No idea
if this actually helps any hardware, but theoretically it can allow CPUs
to not stall waiting for writeback of the atomic operation.
Couldn't detect any performance improvements in the various little
things I was poking at least. Very trivial to support so add it.
Unaligned variants are already handled in our unaligned fault handler
since the only difference is the acquire semantic is dropped and the
destination register is the zero register.
> IR: Optimize unused result atomic fetch mop to just atomic mop

- FEXCore/Scripts/json_ir_generator.py
Currently we don't get why an IR emit failed in the assert message. Put the code in to the message so it is easier to see. This also resolved the issue that when in RelWithDebInfo the assert line would typically be the end of the IR emission function, so you couldn't see which assert actually triggered. Now since the message is printed this is easier
Before:
```
[ASSERT]
```
After:
```
[ASSERT] Size == FEXCore::IR::OpSize::i32Bit || Size == FEXCore::IR::OpSize::i64Bit
```
This is a lot easier and better data than what #3227 proposed.
> IR: Print assert code for IR EmitValidation

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- unittests/InstructionCountCI/FlagM/PrimaryGroup.json
- unittests/InstructionCountCI/FlagM/SecondaryGroup.json
- unittests/InstructionCountCI/FlagM/x87.json
- unittests/InstructionCountCI/FlagM/x87_f64.json
- unittests/InstructionCountCI/PrimaryGroup.json
- unittests/InstructionCountCI/SecondaryGroup.json
- unittests/InstructionCountCI/x87.json
- unittests/InstructionCountCI/x87_f64.json
When the destination doesn't alias the source, we can remove a final mov
from both of these operations.
Does some minor code improvement.
> Arm64: Minor optimization to bfxil and bfi 

- unittests/InstructionCountCI/H0F3A.json
This is optimal without AFP. We already test these with AFP in a different file.
> InstCountCI: Update rounds{s,d} classification

- FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
Everytime I want to quickly output a value for testing I tend to use Print which didn't work under the simulator.
Give this a quick fix to wire up the jump to the vixl sim.
> JIT: Implements Print support for vixl sim

- FEXCore/include/FEXCore/Config/Config.h
Messed up when originally implementing this, substr's second argument is requested substring length, not the ending position.
Noticed this while trying to parse multiple FEX_HOSTFEATURES options.
> Config: Fixes string enum parser with multiple arguments
