- FEXCore/Source/Interface/Core/GdbServer.cpp
gdb gets angry if we return text with `<No Name>` in an xml text field. Instead only return a name if we have one and gdb will take care of the rest.
Additionally change the formatting of the return packet, it doesn't need the xml version header.
> GdbServer: Fixes returning thread names

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/include/FEXCore/Core/CPUBackend.h
gdbserver is currently entirely broken so this doesn't change behaviour. The gdb pause check that we originally had an excessive amount of overhead.
Instead use the pending interrupt fault check that was wired up for wine.
This makes the check very lightweight and makes it more reasonable to implement a way to have gdbserver support attaching to a process.
> FEXCore: Removes gdb pause check handler

- FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
This was supposed to be included in #3241 but I accidentally pushed an outdated patch to that branch.
> Thunks: Print error if guest-provided callbacks are called asynchronously

- FEXCore/Source/Utils/FileLoading.cpp
- FEXCore/unittests/APITests/FileLoading.cpp
When attempting to read files that aren't backed by a filesystem then
our current read file helpers fail since they query the file size
upfront.
Change the helper so that it doesn't query the size and just reads the file if it
can be opened. This lets us read `/proc/self/maps` using helpers.
> FEXCore/FileLoading: Updates helper to load file that is backed by memory

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
While tracking issues in #3162, I had encountered a random crash that I started hunting. It was very quickly apparent that this crash was unrelated to that PR. I just happened to be running a unittest that was creating and tearing down a bunch of threads that exacerbated the problem.
See as follows with the strace output:
```
[pid 269497] munmap(0x7fffde1ff000, 16777216) = 0
[pid 269497] munmap(0x7fffde1ff000, 16777216 <unfinished ...>
[pid 268982] mmap(NULL, 16777216, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fffde1ff000
[pid 269497] <... munmap resumed>)      = 0
```
One thread is freeing some memory with munmap, another one then does a mmap and gets the same address back. Nothing too crazy at initial glance, but taking a closelier look, we can see that …
> JITArm64: Fixes double munmap issue that was causing crashes

- unittests/FEXLinuxTests/tests/signal/eflags_signal.cpp
When attempting to debug #3162 I had noticed spurious behaviour around what I assumed to be eflags getting corrupt around inlined syscalls. This turned out to be a red herring but to ensure we are still testing this, create a fully fleshed out unit test.
This test ensures a couple of things.
1) A flag that is set or unset before a syscall doesn't have its data
corrupt
2) An inline syscall doesn't corrupt the eflags, checking the eflag
result after returning from the syscall.
3) A signal occuring while in an inline syscall returns the correct
eflags information in the signal handler information
This test gets accomplished by setting or unsetting a particular flag and then calling the futex syscall in a way that is guaranteed to be inlined and also wait forever. Then the parent thread will …
> FEXLinuxTests: Adds a unittest for eflags and signals around a inlined syscall

- unittests/ASM/FEX_bugs/nzcv_implicit_clobber.asm
It looks like currently FEX has a bug around implicit flag clobbering with this pull request where an IR operation that implicitly clobbers flags isn't correctly saving the NZCV flags before doing the operation.
Adds a unit test that specifically captures this issue. RAX will be 1 or 0 depending on if the flags are clobbered incorrectly or not.
> unittests/ASM: Adds unittest for implicit flag clobber for #3254

- unittests/ASM/FEX_bugs/nzcv_spill_enderlilies.asm
SHA instructions are very large right now and cause register spilling due to their codegen. Ender Lilies has a really large block in a function called `sha1_block_data_order` that was causing FEX to spill NZCV flags incorrectly. The assumption which held true before NZCV optimizations were a thing was that all flags were either 1-bit in an 8-bit container, or just 8-bit (x87 TOP flag).
NZCV host flags broke this assumption by making its flags 32-bit which ended up breaking when encounting spilling situations.
> unittests/ASM: Adds unittest found from Ender Lilies that crashed with NZCV

- Source/Tools/FEXLoader/LinuxSyscalls/GdbServer.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/GdbServer.h
Resolving the issue that we can only ever have one gdbserver process running consuming port 8086 (even if the port number is cute).
Doesn't give us anything yet but in the future will allow us to have whole process trees running gdbservers that we can attach to.
> GdbServer: Switch over to a unix domain socket

- ThunkLibs/libX11/libX11_Guest.cpp
These are setup to be nullptr by default. Instead of providing no-op lock instructions just have them be nullptr.
It's already part of the API that they need to be nullptr checked before calling and this matches behaviour of the real libX11 library. Removes some spam that is unnecessary.
> Thunks/libX11: Change lock functions to nullptr by default

- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ASIMDOps.inl
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/IR/IR.json
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/Crypto/H0F38.json
- unittests/InstructionCountCI/Crypto/H0F3A.json
- unittests/InstructionCountCI/H0F38.json
- unittests/InstructionCountCI/H0F3A.json
- sha1nexte
- Takes advantage of sha1h if supported
- Does the operation in a vector otherwise
- sha1msg2
- Instead of dumping everything to GPRs, we can do this with vectors
- Mostly matches ARM's sha1su1 instruction, but it is /just/
different enough to be annoying.
- sha256msg1
- Directly matches sha256u0
- Leaves the previous implementation alone
> OpcodeDispatcher: Optimize three sha instructions

- Source/Common/FEXServerClient.cpp
- Source/Common/FEXServerClient.h
- Source/Tools/FEXLoader/LinuxSyscalls/GdbServer.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/GdbServer.h
Nothing too crazy in here, trying to avoid some of the bigger changes.
A couple of stand-out things
- Adds some lldb specific query commands.
- Set the thread name of gdbserver. Easier to pick out if a thread hung.
- Try binding twice, unlinking the unix domain socket path in between
- Poll the listen socket instead of waiting in accept. Removing a hang that could occur.
> More GdbServer improvements

- FEXCore/CMakeLists.txt
While clang side code to support preserve_all on Windows is in place (and thus there are no errors for using it), there are still some parts missing on the [https://github.com/llvm/llvm-project/blob/2402b14046b9628b584c07789830d7ed481f7d74/llvm/lib/Target/AArch64/AArch64RegisterInfo.cpp#L88](LLVM side). I'll submit a patch to fix this upstream, but this works for now.
Thanks to @AndreRH for reporting this, glad I was finally able to reproduce it :)
> FEXCore: Work around broken preserve_all support in Windows clang

- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/include/FEXCore/Core/Context.h
Split off from #3282 to reduce burden.
We read the member directly now. Removes one usage of ParentThread in FEXCore.
> FEXCore: Removes GetExitReason

- Source/Tools/FEXLoader/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
O_TMPFILE has a few minor problems that I have been thinking about for a while. I just recently got reminded about this and remembered that most problems get resolved by using memfd_create.
- O_TMPFILE is only supported on some filesystems.
- Supported filesystem must be the one mounted to the pathname being opened.
- Only a minor inconvenience as tmpfs and all related filesystems support this.
- An inode is actually created on whatever filesystem is backing the folder.
- `/tmp/` must exist as a directory
- If this folder happened to not be mounted then these temporary files wouldn't have been created.
- memfd_create doesn't have a folder that needs to exist.
- We were leaving the files open as read/write
- While we were rewinding the file offset, an misbehaving application could have …
> EmulatedFiles: Stop relying on O_TMPFILE

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/CPUBackend.h
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/AOT/AOTGenerator.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Windows/WOW64/Module.cpp
First commit from #3282.
The frontend needs to be in control of how threads are created. This is inherent to the fact that OS threads are OS specific. We currently have this weird split that when initializing the FEXCore context, we create a parent thread at all times.
This does some initial cleanup that gets the core initialization nearly decoupled.
> FEXCore: Start changing how thread creation works

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/CoreState.h
- Source/Tools/FEXLoader/LinuxSyscalls/GdbServer.cpp
These are only used by gdbserver for filling out its XML data structures so just remove them from FEXCore.
Also fixes the ordering on RegNames to match the definition of the enum class definition in CoreState. This has been out of correct order since we reordered registers months ago.
> FEXCore: Moves debug strings to gdbserver

- Source/Tools/FEXRootFSFetcher/Main.cpp
As I was poking around erofs-utils documentation, I found out that fsck.erofs actually provides an option for extracting erofs images without using fuse.
This finally puts the erofs handling on feature parity with squashfs.
> FEXRootFSFetcher: Supports extracting erofs images

- FEXCore/include/FEXCore/Core/CoreState.h
Removes new warning from clang:
```
FEXCore/include/FEXCore/Core/CoreState.h:119:35: warning: not packing field 'DeferredSignalRefCount' as it is non-POD for the purposes of layout [-Wpacked-non-pod]
119 |     NonAtomicRefCounter<uint64_t> DeferredSignalRefCount;
|                                   ^
```
We already ensure sane data layout that this is unnecessary anyway.
> FEXCore: Removes FEX_PACKED from CPUState

- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/IRLoader.cpp
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
Split off from #3282 to reduce burden.
We can read the data member directly now since it isn't opaque. In fact we already do in the signal handlers. Removes these redundant helpers.
Removes one usage of ParentThread in FEXCore.
> FEXCore: Removes Get/SetCPUState

- FEXCore/Source/Interface/IR/IRDumper.cpp
When COND_AL was added it wasn't added to this helper. Since there is a gap between the last condition, just early check the value.
Fixes reading beyond the end of the array
> IRDumper: Fixes missing conditional name

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
Forgot to pass a few arguments through. Doesn't change behaviour since we were always passing in TMP1 and FPRs = true but this is correct.
> FEXCore: Fixes passing arguments to ABI helpers

- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXLoader/IRLoader.cpp
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
- Source/Windows/WOW64/Module.cpp
This isn't necessary anymore, just initialize everything on context creation immediately. All use cases just called this immediately afterwards.
> FEXCore: Removes InitializeContext API

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/FEXLoader.cpp
Split from #3284 without changing ownership semantics while I reduce the debugging surface here.
Removes one usage of ParentThread from FEXCore. Which can be done since it is no longer an opaque structure, we can read the StatusCode directly.
No functional change.
> FEXCore: Removes GetProgramStatus

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/IR.json
- unittests/ASM/FEX_bugs/ShiftConstantBug.asm
In some situations TestNZ is generated with a constant that is using a
constant that can't fit inside of the tst instruction.
This was found in libGLX with virgl, crashing invalid instruction
generation and crashing steamwebhelper
> JIT: Fixes crash in TestNZ

- ThunkLibs/libvulkan/Host.cpp
Previously, these were only accessible through `vkGetDeviceProcAddr`. Technically `vkGetInstanceProcAddr` is not supposed to return device-related functions, but doing so anyway doesn't cause any immediate problems and is easier to maintain while we're still in the process of bringing up the full API for 32-bit guests.
Also changed the code to use `std::string_view_literals` instead of `strcmp`, which makes the if-else-cascade much easier to read.
> Thunks: Allow querying customized functions through vkGetInstanceProcAddr

- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/x64/Syscalls.cpp
- Source/Tools/FEXLoader/TestHarnessRunner.cpp
These appear to have slipped through the migration to fmt syntax.
> FEXLoader: Fix incorrect format strings

- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
This flag breaks FEX heavily for now.
glibc 2.38 started using this flag as an optimization for posix_spawn. It will fall back to a "non-optimized" implementation if the clone syscall returns EINVAL. For now do this while we investigate a more proper implementation.
Should be backported to 2312.1.
> FEXLoader: Temporarily disable CLONE_CLEAR_SIGHAND

- Scripts/InstallFEX.py
A dictionary lookup was only ever returning the .ero result since we were adding multiple values to the same key. Adds them as a list now and walks them.
Additionally if we forget to add a new version again, have a fallback to try checking using our file format layout.
Fixes an issue where a user running 23.10 was faulting the python script.
> Scripts: More changes to InstallFEX script

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/SignalDelegator.h
- Source/Tools/CommonTools/DummyHandlers.h
- Source/Tools/FEXLoader/LinuxSyscalls/SignalDelegator.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
The XID signal handler is OS specific and needs to be delegated to being handled in the frontend. This only happens when we create a thread with pthread rather than clone/fork/vfork.
The first created pthread will reset the XID signal handler in glibc, which we need to check the first time this occurs. A little bit disjoint while the actual thread creation still happens in the backend but will come together once the thread creation gets moved to the frontend.
The only game I am aware of that requires this to work is SOMA since its one of its middleware libraries tries asking for root privileges.
Retested the game to make sure it still works as expected.
> FEXCore: Moves XID check to the frontend

- Source/Tools/FEXLoader/LinuxSyscalls/GdbServer.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/GdbServer.h
GdbServer object was getting deleted before the socket thread was shutdown which was causing a crash on detach.
Now on destructor it will wait for the thread to thread to exit.
> GdbServer: Fixes crash on gdb detach

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp
~~Needs #3294 merged first.~~
Fairly lightweight since it is almost 1:1 transplanting the code from
FEXCore in to the SyscallHandler's thread creation code.
Minor changes:
- ExecutionThreadHandler gets freed before executing the thread
- Saves 16-bytes of memory per thread
- Start all threads paused by default
- Since I moved the code to the frontend, I noticed we needed to do
some post thread-creation setup.
- Without the pause we were racing code execution with TLS setup and
a few other things.
> FEXCore: Moves OS thread creation to the frontend 

- FEXCore/Source/Interface/Core/X86Tables.cpp
- FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/DDDTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/EVEXTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
- FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
- FEXCore/Source/Interface/Core/X86Tables/PrimaryGroupTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/SecondaryGroupTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/SecondaryModRMTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
- FEXCore/Source/Interface/Core/X86Tables/X87Tables.cpp
- FEXCore/Source/Interface/Core/X86Tables/XOPTables.cpp
Reduces the ELF's VM size from 9.8MB down to 9.37MB and should reduce initialization time a smidge.
Slammed this out while waiting for other PRs to get reviewed.
> X86Tables: Converts tables to be mostly consteval

- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.cpp
- Source/Tools/FEXLoader/LinuxSyscalls/Syscalls.h
clone needs to allocate memory before the fork locks are held, otherwise they will hang forever waiting on a locked mutex.
This wasn't previously seen since nothing was using fork with clone3.
> Linux: Adjust when clone allocates stack memory

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/IR/PassManager.h
git blame shows that 718b3e6b4cc577cda8710b8c1f7ac5b59563814c added this handler.
It doesn't explain why this was desired but it was never wired up to anything. Just remove it.
> PassManager: Removes unused exit handler

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
- FEXCore/Source/Interface/Core/Core.cpp
No need to wait for initialization on for this anymore. Ever since Init was refactored to do basically no work, this hasn't been necessary.
CPUID does need to still be initialized after HostFeatures though, so need to ensure correct member ordering there.
> CPUID: Removes Init and just uses constructor

- FEXCore/Source/Interface/Core/InternalThreadState.h
- FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
This was a temporary header to help with when this header was migrated to our public API headers.
It's temporary nature is no longer necessary, just get rid of it.
> FEXCore: Removes old InternalThreadState header

- Source/Tools/FEXLoader/VDSO_Emulation.cpp
When originally written I was testing symbol loading on an x86 host assuming that the vdso symbol names were the same between x86 and aarch64.
Turns out this is not true and aarch64 uses `__kernel_` prefix instead of x86's `__vdso_`.
AArch64 VDSO only provides us with four symbols right now
- __kernel_rt_sigreturn
- __kernel_gettimeofday
- __kernel_clock_gettime
- __kernel_clock_getres
This means that currently AArch64 is missing getcpu and time. time is unlikely to ever be implemented so the vdso scanning for that is unlikely to ever get a pointer and will need to go down the glibc path.
getcpu is likely to get an implementation at some point. There's even an old patch series that implemented it[1]. Currently the patch has been dropped on the floor for whatever reason but hopefully they …
> VDSO: Fixes symbol fetching for a few symbols

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/JIT/JITCore.h
> FEXCore: Removes stale references to x86 JIT

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
While we were calling this function, its asserting nature hasn't been used for a long time.
This used to trigger more frequently when CompileBlock would fail to compile code, either due to not being able to decode an instruction or hitting an instruction that FEX doesn't understand.
When these cases are hit today we still generate code blocks which generate SIGILL. This means that this code was actually never hit.
Completely remove this function and have the JIT's dispatcher call the CompileBlock function directly. Signature is slightly different since we need to set x3 to be 0.
> Dispatcher: Removes unused asserting CompileBlock function

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/FlagM/HotBlocks_32Bit.json
- unittests/InstructionCountCI/Primary.json
When the address calculation for SIB has both index and base then we can
optimize this to an add with a shifted register. This will convert a
three instruction sequence in to one instruction in most cases.
> OpcodeDispatcher: Optimize SIB addr calculation 

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/ASM/FEX_bugs/IMUL_garbagedata_negative.asm
- unittests/InstructionCountCI/FlagM/Primary.json
- unittests/InstructionCountCI/FlagM/Secondary.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/Secondary.json
On overflow with 32-bit we weren't setting the flags correctly.
While this does happen to fix the immediate issue in #3316, it crashes quickly after the fact still.
> OpcodeDispatcher: Fixes flags generation in imul

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
Instead of just poking raw uint64_t data values, describe it with a struct.
This will be a read-only in the future.
> FEXCore: Describe exit function linking object with a structure

- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
~~Needs #3323 merged first.~~
This was older code that was written before the PMF helper was available.
Switch it over.
> Dispatcher: Convert GetCompileBlockPtr to using PMF helper

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/AOT/AOTGenerator.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/IRLoader/IRLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/WOW64/Module.cpp
Similar to #3284 but works around some of the bugs that one introduced.
This is the minimal amount of changes to move the ownership from FEXCore to the frontend. Since the frontends don't yet have a full thread state tracking, there is an opaque pointer that needs to be managed.
In the followup commits this will be changed to have the syscall handler to be the thread object manager.
> FEXCore: Changes ParentThread ownership from the CTX to the frontend, take 2

- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- FEXCore/include/FEXCore/Core/Context.h
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- FEXCore/include/FEXCore/HLE/SyscallHandler.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/AOT/AOTGenerator.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/IRLoader/IRLoader.cpp
- Source/Tools/LinuxEmulation/CMakeLists.txt
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/WOW64/Module.cpp
Lots going on here.
This moves OS thread object lifetime management and internal thread
state lifetime management to the frontend. This causes a bunch of thread
handling to move from the FEXCore Context to the frontend.
Looking at `FEXCore/include/FEXCore/Core/Context.h` really shows how
much of the API has moved to the frontend that FEXCore no longer needs
to manage. Primarily this makes FEXCore itself no longer need to care
about most of the management of the emulation state.
A large amount of the behaviour moved wholesale from Core.cpp to
LinuxEmulation's ThreadManager.cpp. Which this manages the lifetimes of
both the OS threads and the FEXCore thread state objects.
One feature lost was the instruction stepping, but this was already
buggy and is going to be rewritten/fixed when …
> FEXLoader: Moves thread management to the frontend 

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
Fixes a couple of crashes in bubblewrap that seem to have cropped up. Potentially SLR updated the version of bubblewrap they ship?
I have unit tests coming for this but it is uncovering some more bugs in
FEX's thread handling. Some of which are getting fixed with the current
PRs that are moving the thread handling to the frontend.
But since proton is broken now, this needs to get in.
> Fixes Proton again

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
- FEXCore/Source/Interface/Config/Config.json.in
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
We only used this so that our Xavier CI system which were running old kernels could run unit tests. We have now removed the Xaviers from CI and this is no longer necessary.
Stop pretending that we support kernels older than 5.0 and allowing this fallback.
The 32-bit allocator is still used for the MAP_32BIT mmap flag, so the load bearing code can't be fully removed. Just remove the config and the frontend things using it.
> FEX: Removes legacy kernel 32-bit allocator

- ThunkLibs/Generator/analysis.cpp
- ThunkLibs/Generator/analysis.h
- ThunkLibs/Generator/data_layout.cpp
- ThunkLibs/Generator/data_layout.h
- ThunkLibs/Generator/gen.cpp
- ThunkLibs/include/common/GeneratorInterface.h
- ThunkLibs/include/common/Host.h
- ThunkLibs/libvulkan/Host.cpp
- ThunkLibs/libvulkan/libvulkan_interface.cpp
- ThunkLibs/libwayland-client/Host.cpp
- unittests/FEXLinuxTests/tests/thunks/thunk_testlib.cpp
- unittests/ThunkLibs/common.h
- unittests/ThunkLibs/generator.cpp
This PR makes the thunk generator emit helper structures to allow repacking `struct`s that have different data layout on the guest than on the host. The new `guest_layout` and `host_layout` wrappers are emitted for each type used in APIs of forwarded libraries. These structures have the same members as the original structure but they are defined in an architecture-agnostic way. This allows the host to read guest structures without having to worry about member offsets, type size differences, or other sorts of differences in the data layout.
There is no *automatic* struct repacking yet, but the wrappers allow for *manual* repacking by converting a `guest_layout` is converted to a `host_layout`, or vice-versa.
See #3156 for the data layout analysis framework that gathers the required …
> Library Forwarding: Emit layout helpers to allow repacking struct data

- FEXCore/Scripts/config_generator.py
- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
- Source/Common/Config.cpp
OpenSSL ships a fairly nasty [bug](https://github.com/openssl/openssl/issues/23144) that crashes games when they are calculating SHA on systems without AVX. This is hit by the game [Claybook](https://wiki.fex-emu.com/index.php/Claybook) which statically links in OpenSSL.
Adds a config option to allow adjusting CPUID options with only SHA being supported by now. This lets users create a config option for the game to disable SHA.
```
$ cat Steam_661920_Claybook-Win64-Shipping.exe.json
{
"Config": {
"CPUID": "disablesha"
}
}
```
> Support disabling SHA in CPUID

- FEXCore/Scripts/config_generator.py
- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- Source/Common/Config.cpp
~~Need https://github.com/FEX-Emu/FEX/pull/3348 merged first.~~
As I was casually thinking, this code made me realize that it was quite
branch heavy and could likely be optimized to logic.
The previous code generated some fairly nasty branch heavy code. This
can be optimized to be branchless and take roughly five instructions
per flag. Using a bitfield for each feature would turn each calculation
in to 3-4 instructions but that seems overkill.
Very minor thing.
Before:
After:
> FEXCore: Optimize HostFeatures and CPUID feature calculation

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
While locking a shared_lock and doing an empty table lookup is fairly fast, just remove them from the hot path entirely if no custom IR handlers are installed.
This is only used for our IRLoader, which is losing its importance significantly and should probably be removed anyway.
> FEXCore: Removes context wide and map lookup

- .gitmodules
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner/HostRunner.cpp
The last few patches we need have been upstreamed so we shouldn't need our downstream fork anymore.
> Externals: Update xbyak to v7.02 and switch away from fork

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Utils/MemberFunctionToPointer.h
We can safely call virtual functions through the JIT with a little bit
of work.
FEX's JIT has quite a few steps before it gets to a syscall handler.
Before this commit:
JIT->static HandleSyscall->SyscallHandler::HandleSyscall->SyscallHandler
After this commit:
JIT->SyscallHandler::HandleSyscall->SyscallHandler
A bit hard to notice this when this interface can spin at 67-million
calls per second though.
> Arm64: Removes a vtable indirection in syscalls 

- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
- FEXCore/Source/Utils/ArchHelpers/Arm64_stubs.cpp
- FEXCore/include/FEXCore/Utils/ArchHelpers/Arm64.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Windows/WOW64/Module.cpp
Currently no functional change but public API breaks should come early.
The thread state object will be used for looking up thread specific codebuffers in the future when we support MDWE with code mirrors.
> FEXCore: Pass thread object to HandleUnalignedAccess

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/LookupCache.h
The delinker step of the JIT was using std::function with capture lambdas that required memory allocation when unnecessary. Because the compiler can't see through our std::function usage it could never decompose these by itself.
By passing the Thread's frame and record to the function as arguments then we can have the signature be a raw function pointer.
This fixes an area of concern from:
https://github.com/FEX-Emu/FEX/blob/main/docs/ProgrammingConcerns.md#stdfunction-and-lambdas
> FEXCore: Decompose some std::function usage to regular pointers

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/BranchOps.inl
- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/Emitter.h
- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/LoadstoreOps.inl
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/LookupCache.h
~~Needs #3361 merged first.~~
Previously forward labels needed to be pessimistic about multiple instructions binding to a label. This results in forward labels having a vector that always allocates memory. Instead if we know the data is only going to be used by a single instruction then we don't need to allocate any memory. This is the common case in FEX.
In particular the delinker step for the JIT blocks was always allocating memory due to the forward label. Now it no longer allocates any memory since it uses a single use forward label.
> ArmEmitter: Support single use forward labels

- ThunkLibs/Generator/gen.cpp
- ThunkLibs/include/common/Host.h
- ThunkLibs/libfex_thunk_test/Host.cpp
- ThunkLibs/libfex_thunk_test/api.h
- ThunkLibs/libfex_thunk_test/lib.cpp
- ThunkLibs/libfex_thunk_test/libfex_thunk_test_interface.cpp
- ThunkLibs/libvulkan/libvulkan_interface.cpp
- unittests/FEXLinuxTests/tests/thunks/thunk_testlib.cpp
- unittests/ThunkLibs/generator.cpp
Struct data passed across architecture boundaries requires repacking of the contained data if the data layout differs between the guest and host architectures. Similarly, integers and pointers need to be zero-extended when their guest size differs from the host. This PR extends the thunk generator to automatically use the guest_layout/host_layout wrappers added in #3318 to convert data where needed.
Simplified examples of generated code:
```cpp
struct fexfn_packed_args_glBindBufferRange {
guest_layout<GLenum> a_0;
guest_layout<GLuint> a_1;
guest_layout<GLuint> a_2;
guest_layout<GLintptr> a_3;
guest_layout<GLsizeiptr> a_4;
};
static void fexfn_unpack_glBindBufferRange(fexfn_packed_args_glBindBufferRange* args) {
host_layout<GLenum> a_0 { args->a_0 };
host_layout<GLuint> a_1 { args->a_1 }; …
```
> Library Forwarding: Implement automatic argument repacking

- Source/Tools/CMakeLists.txt
- Source/Tools/pidof/CMakeLists.txt
- Source/Tools/pidof/pidof.cpp
This behaves exactly like pidof but only searches for FEX applications. This fixes a long standing annoyance of mine that pidof doesn't work for FEX. This behaves exactly like pidof but knows how to decode the command line options to pull out the program data.
If the Linux kernel ever accepts the patches for binfmt_misc to change how the interpreter is handled then this will become redundant, but until that happens here is a utility that I want.
> Tools: Adds new FEXpidof tool

- ThunkLibs/Generator/analysis.cpp
- ThunkLibs/Generator/analysis.h
- ThunkLibs/Generator/data_layout.cpp
- ThunkLibs/Generator/gen.cpp
- ThunkLibs/include/common/GeneratorInterface.h
- ThunkLibs/include/common/Host.h
- ThunkLibs/libfex_thunk_test/Host.cpp
- ThunkLibs/libfex_thunk_test/api.h
- ThunkLibs/libfex_thunk_test/lib.cpp
- ThunkLibs/libfex_thunk_test/libfex_thunk_test_interface.cpp
- unittests/FEXLinuxTests/tests/thunks/thunk_testlib.cpp
- unittests/ThunkLibs/abi.cpp
- unittests/ThunkLibs/common.h
- unittests/ThunkLibs/generator.cpp
The machinery for *automatic struct repacking* (#3371) is limited to "simple" data, i.e. structs of which all members are either integers or other structs that themselves are simple. The real world is more messy than that, because structs frequently contain pointers. This PR adds a *custom repacking* mechanism for specific members to be repacked manually while leaving the rest to be handled by the same autogenerated boilerplate code as before. This allows a wider range of structs to be repacked automatically with minimal additional manual work.
For a struct member `MyStruct::MyMember` annotated as `fexgen::custom_repack`, two functions must be implemented in the FEX's host-side glue code (Host.cpp):
```cpp
void fex_custom_repack_entry(host_layout<MyStruct>& into, const …
```
> Library Forwarding: Implement assisted struct repacking

- Dockerfile
I added the `pkg-config` that is missing in the Dockerfile, and make the git clone the repository direct from the image, so the user don't need to clone it manually and after that pulls inside the Dockerfile!
If the git change is too much, tell me that I remove it and keep only the dependecies update, because without it, it's not compiling at all.
> Improvements to the Dockerfile

- ThunkLibs/Generator/main.cpp
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/libfex_thunk_test/api.h
- ThunkLibs/libfex_thunk_test/lib.cpp
- ThunkLibs/libfex_thunk_test/libfex_thunk_test_interface.cpp
- unittests/FEXLinuxTests/tests/thunks/thunk_testlib.cpp
~~Needs https://github.com/FEX-Emu/FEX/pull/3373 merged first.~~
This just adds one more test to test the interaction between automatic struct repacking (added in #3371) and the previously added `assume_compatible_data_layout` annotation (#3177). This serves mainly as a consistency check to ensure other tests don't just pass "by accident".
While developing this, I also found that we aren't setting up `GUEST_THUNK_LIBRARY` properly, which the test library needs to enable guest-specific behavior however. A fix for this is included in the PR now as well.
> Library Forwarding: Test interaction of struct repacking and assume_compatible_data_layout

- ThunkLibs/include/common/Host.h
Minor fix to #3373, which dereferenced `data` for custom repacking before performing the `nullptr` check. This wasn't hit in practice even in my WIP branch, but could've caused crashes when using custom repacking with arguments that can be null.
> Library Forwarding: Flip order of nullptr check and custom repacking

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- unittests/FEXLinuxTests/tests/signal/Syscall_state.32.cpp
- unittests/FEXLinuxTests/tests/signal/Syscall_state.64.cpp
Noticed this while writing #3342.
Fixes #3343
The syscall instruction is defined in the documentation that it will set RCX to the next instruction's RIP and R11 to be RFLAGS. We entirely skipped this which I noticed while writing unit tests.
Adds unittests to test both 32-bit and 64-bit behaviour because our helper shares code with both.
I don't know if anything actually relied on this behaviour but we should definitely support it.
> OpcodeDispatcher: Fixes syscall rcx/r11 generation

- Source/Tools/LinuxEmulation/CMakeLists.txt
- Source/Tools/LinuxEmulation/LinuxSyscalls/FaultSafeMemcpy.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/FD.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Types.h
- unittests/FEXLinuxTests/Known_Failures
- unittests/FEXLinuxTests/tests/syscalls/syscalls_efault.cpp
We are required in our syscall emulation to handle cases where pointers
are invalid. This means we need to pessimistically assume a memcpy will
fault when reading application memory.
This implements a signal handler based approach to catching the SIGSEGV
on memcpy and returning an EFAULT if it faults.
> Linux: Implements a fault safe memcpy routine

- Source/Tools/FEXConfig/Main.cpp
Previously, FEXConfig would unconditionally place its `FEXConfig_imgui.ini` in the current working directory, since `GetConfigDirectory` would always return "".
> FEXConfig: Initialize paths before trying to read configuration files

- FEXCore/CMakeLists.txt
Forces disabling use of __attribute__((preserve_all)). Until CI uses clang17, where this attribute was added, instcountci fails when FEX is compiled with clang>=17.
> Add cmake option DISABLE_CLANG_PRESERVE_ALL

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- unittests/ASM/FEX_bugs/BLSI_flags.asm
- unittests/ASM/FEX_bugs/BLSMSK_flags.asm
- unittests/ASM/FEX_bugs/BLSR_flags.asm
- unittests/InstructionCountCI/FlagM/Secondary_REP.json
- unittests/InstructionCountCI/FlagM/VEX_map2.json
- unittests/InstructionCountCI/FlagM/VEX_map_group.json
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map_group.json
Optimize blsi/blsr/blsmsk/bextr/lzcnt/tzcnt/popcnt, mostly around flags. Also fix some bugs in blsi/blsr flag calcs found along the way, with unit tests added to repro the issues.
> Optimize bit manipulation instructions

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- unittests/InstructionCountCI/Primary.json
Optimize `cwde` and `cbw`.
Change OpcodeDispatcher CDQOp to load directly from GPR, and recognize instruction width.
Also change Constant Propagation to synthesize 32bits constant when necessary.
Update instcountci files.
> Optimize CDQOp

- FEXCore/Scripts/config_generator.py
When 4d109c9ce02bbc392e59c74d34b885de8fa8efde fixed parsing strenum types in the json, it also added `ArgumentHandler` types to the json parsing. This was incorrect as those types are already stored in the json in their decoded numerical format.
Without this change, all config options with `ArgumentHandler` will decode as "0" which is incorrect. The main killer here is that SMCChecks gets disabled (visible in both FEXConfig and when applications are running) which was causing spurious failures.
> Config: Fixes JSON parsing of "ArgumentHandler" types

- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
- FEXCore/include/FEXCore/Core/Context.h
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- FEXCore/include/FEXCore/HLE/SyscallHandler.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/AOT/AOTGenerator.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/CMakeLists.txt
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/WOW64/Module.cpp
This was caught up in the previous bisecting as a potential reason why Proton was failing to execute.
But it was actually because of the strenum json parsing and runtime long mode switch PRs which were merged right next to it.
Retested this and proton games are still working fine.
This is necessary as a first step to fix an additional hang that occurs where a forking process can hang when another thread is in the process of allocating memory. This fork+alloc hang is a pre-existing condition that needs to be fixed in a follow-up PR.
> Revert "Revert "FEXLoader: Moves thread management to the frontend""

- FEXCore/Source/Utils/SpinWaitLock.h
With a contended unique lock, we forgot to reset the `Expected` value to zero. This was causing a contended mutex to incorrectly succeed.
Noticed this when converting some pthread mutexes over to spinloops to remove strace noise.
The reference wfe_mutex library I wrote didn't have this problem since the implementation is slightly different.
> SpinLockWait: Fixes unexpected lock success

- FEXCore/Source/Utils/SpinWaitLock.h
Tmp was no longer being used, forgot to remove it.
> SpinWaitLock: Removes unused variable in spin-loop fallback

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/InterpreterFallbacks.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Source/Tools/CodeSizeValidation/Main.cpp
This is used for instcountci to ensure instruction counts don't change when a compiler supports this feature or not. Always runtime disable when running in instcountci.
CMake option from #3394 can still be useful so leaving that in place.
> HostFeatures: Supports runtime disabling of preserve_all

- FEXCore/CMakeLists.txt
Reverts FEX-Emu/FEX#3394. A runtime-check for this was added in #3401.
> Revert "Add cmake option DISABLE_CLANG_PRESERVE_ALL"

- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
If the thread object is added to the tracking vector immediately then there ends up being a race condition before the thread manages to fill out the thread-specific data that only occurs at the start of the new thread.
This manifests in a crash when a thread is allocating memory while another thread is getting constructed. Easy fix is to defer the tracking until the thread has setup its state.
> Linux: Decouple thread object creation and tracking

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
When code invalidation is happening we currently have the issue that a thread can acquire the code invalidation mutex in the middle of invalidation. This is due to us acquiring and releasing the mutex between each thread's code invalidation.
We need to hold the mutex for the entire duration for all thread's code invalidation.
This fixes a rare hang on proton startup and resolves a consistent hang on Proton application shutdown.
This now puts us on par with FEX-2312.1 with hanging.
This does not fix a relatively rare hang on fork (which also existed with FEX-2312.1).
This also does not fix the issue that the intersection of our mutexes between frontend and backend are very convoluted. In part of the work that is going to fix the rare fork mutex hang will change more of this.
> Fixes one mutex hang

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
The creation mutex could have been held if the parent thread was in the
middle of creating a thread when forking. This would result in a
deadlock once the fork child attempted to create another thread.
Forcefully dropping the lock in the fork child works around this
deadlock. This comes at the expense of potentially leaving resources
guarded by the thread creation mutex in an invalid state. Crashes caused
by this are easier to reason about than a delayed deadlock, though.
> ThreadManager: StealAndDropActiveLocks in the child forked process

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- unittests/InstructionCountCI/Atomics.json
- unittests/InstructionCountCI/FlagM/Atomics.json
- unittests/InstructionCountCI/FlagM/Primary.json
- unittests/InstructionCountCI/FlagM/PrimaryGroup.json
- unittests/InstructionCountCI/FlagM/Secondary.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
- unittests/InstructionCountCI/Primary_32Bit.json
- unittests/InstructionCountCI/Secondary.json
If we shift first, NZCV matches up exactly :+1:
> Optimize 8/16-bit adds/subs

- Source/Tools/LinuxEmulation/VDSO_Emulation.cpp
- ThunkLibs/Generator/gen.cpp
- ThunkLibs/include/common/Host.h
- ThunkLibs/include/common/PackedArguments.h
ARM64, x86 (64-bit), and x86 (32-bit) each have different alignment requirements, so this change ensures that consistent data layout is used for packing and unpacking.
Ready for review, but let's merge it after the February release.
> Library Forwarding: Disable struct padding for packed arguments

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
This fixes a fairly large memory leak.
> Linux: Make sure to destroy thread object when thread shuts down

- FEXCore/include/FEXCore/Debug/InternalThreadState.h
FEXCore is guaranteed to not touch this pointer and can be used by frontends to store thread-specific data.
> FEXCore: Add a frontend pointer to InternalThreadState

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- unittests/InstructionCountCI/FlagM/SecondaryModRM.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/SecondaryModRM.json
Games engines are expecting >1Ghz cycle counters. Scale them to work around the issue.
Resolves the excessive busy waiting in Unreal Engine 5 games.
> Implement small TSC scaling

- ThunkLibs/Generator/analysis.cpp
- ThunkLibs/Generator/gen.cpp
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
- ThunkLibs/include/common/Host.h
- ThunkLibs/libwayland-client/Guest.cpp
- ThunkLibs/libwayland-client/Host.cpp
- ThunkLibs/libwayland-client/libwayland-client_interface.cpp
- unittests/ThunkLibs/generator.cpp
Finally, the first real 32-bit library we can forward to the 64-bit host, moving us up to Phase 3 of the [Library Forwarding Roadmap](https://gist.github.com/neobrain/3812c111a2da57bfd8376dd21d61a886):
|                          | X11 (64-bit) | Wayland (64-bit) | Wayland (32-bit) | X11 (32-bit) |
| ------------------------ | ------------ | ---------------- | ---------------- |------------- |
| no thunks            | ☑️ 2022      | ☑️ 2022         | ☑️ 2022          | ☑️ 2022      |
| only Wayland thunks  | N/A          | ☑️ Phase 1      | ✅Phase 3          | N/A           |
| Vulkan               | ☑️ 2022      | ☑️ Phase 1      | Phase 4          | Phase 7       |
| zink on Vulkan       | ☑️ Phase 2   | ☑️ Phase 2      | Phase 4          | Phase 7       |
| OpenGL               | ☑️ …
> Library Forwarding: Add support for 32-bit Wayland

- CMakeLists.txt
Note that this explicitly differs from the Windows define _M_ARM64EC, in the same way that Windows defines _M_ARM64 but FEX defines  _M_ARM_64. Matching the windows define ends up confusing CMake which expects MSVC to be used in such cases
> CMake: Define _M_ARM_64EC when building for ARM64EC

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/SignalDelegator.h
ARM64EC has a shared SRA mapping between ARM64 and X64 code, so there needs to be a public way to enter the dispatcher without refilling SRA from the in-memory context structure to avoid a needless roundtrip.
> FEXCore: Expose AbsoluteLoopTopAddress to the frontend

- unittests/InstructionCountCI/FlagM/HotBlocks.json
> InstCountCI: add The Witcher 3 block

- unittests/InstructionCountCI/FlagM/HotBlocks.json
Looks like #3436 had an interaction that was unexpected.
Not sure why the scripts aren't showing this diff, should be looked at separately.
> Fix instcountci

- FEXCore/Source/Interface/Core/Core.cpp
This isn't actually using TLS allocations. Instead it is an allocation tied to the InternalThreadState object.
> Moves JITSymbol allocation

- unittests/InstructionCountCI/FEXOpt/AddressingLimitations.json
- unittests/InstructionCountCI/FEXOpt/AddressingLimitations_32Bit.json
Spurred on by #3421
This does a bunch of GPR and vector loads to showcase addressing limitations between ARM and x86.
Tests:
- 8/16/32/64-bit GPR loads
- Both 32-bit and 64-bit addressing modes
- 32/64/128-bit Vector loads
- Both 32-bit and 64-bit addressing modes
- Duplicate the tests for 32-bit addressing mode with a 32-bit process
- Since it should change behaviour.
Untested:
- 8/16-bit vector loadstores since those don't exist on x86
- 16-bit x87 integer load exists but that doesn't go through a vector load in FEX.
> InstcountCI: Adds addressing limitations to instcountci

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/SignalDelegator.h
- Source/Tools/CommonTools/DummyHandlers.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
FEXCore doesn't need track the TLS state of the SignalDelegator, this is a frontend concept.
Removes the tracking from the backend and keeps it in the frontend.
> Moves SignalDelegator TLS tracking to the frontend

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
This fixes a regression from 9dd715573, which accidentally changed the filename and set up incorrect file opening flags.
For personal reference, it seems that Ubuntu's `gdb` package enables assertions that break with FEX's GDBJITReader, however it's working fine when building gdb from source with the default configuration.
> Syscalls: Fix SourcecodeMap generation for GDB JIT integration

- unittests/InstructionCountCI/FlagM/HotBlocks.json
This was interesting because it caught that we are failing loadstores with reg+reg address generation on vectors.
Additionally the address generation is duplicated twice, but once reg+reg gets added that won't be an issue.
> InstcountCI: Adds a vector addition loop from bytemark

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/ASM/FEX_bugs/xor_flags.asm
Fixes 140976d322dc5e26c129d1e6448f25f6b2378341
Adds a unit test to ensure it keeps working.
Before fix:
After fix:
> Fixes zero register flag generation

- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
> RedundantFlagCalculationElimination: fix missing NEG case

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/SyscallsEnum.h
Previously: Would keep one clone thread's stack active for teardown delaying.
With aggressive cloning and teardown, this was unsafe. Only reap the stack when told it is safe to do so.
> Linux: More safe stack cleanup for clone

- FEXCore/Source/Utils/Allocator.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
Spurred on by https://github.com/FEX-Emu/FEX/pull/3421. To ensure that applications don't take advantage of
small address wrap around, allocate the second 4GB of virtual memory.
Some context. Linux always reserves the first 16KB of virtual address
space (unless you tinker with some settings which nobody should do).
Example of 32-bit code:
lea eax, [0xffff_0000]
mov ebx, [eax + 0x1_0000]
The address calculated by the mov will wrap around to 0x0 which will
result in SIGSEGV. If FEX messes up zero extensions then it would try to
access 0x1_0000_0000 instead.
This could result in a 32-bit application potentially accessing some FEX
memory instead of crashing.
Add this safety net which will still SIGSEGV and we will be able to see
the crash.
> FEXLoader: Allocate the second 4GB of virtual memory when executing 32-bit

- unittests/32Bit_ASM/FEX_bugs/SignExtendBug.asm
When the source arguments for LoadMem/StoreMem have bit 31 set then they are incorrectly sign extending in some instances.
Detected this when testing #3421 but I don't have a proper fix for it.
> Adds a unittest for a bug from #3421

- unittests/32Bit_ASM/CMakeLists.txt
- unittests/ASM/CMakeLists.txt
> Track unittest dependencies through to the custom target

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/ASM/FEX_bugs/32bit_syscall.asm
- unittests/ASM/Known_Failures_jit
Fixes #591
Adds a simple unittest
> Capture a 64-bit process trying to jump to 32-bit syscall handler

- .gitmodules
- CMakeLists.txt
- FEXCore/Source/CMakeLists.txt
- Source/Tools/FEXRootFSFetcher/CMakeLists.txt
Update xxhash to v0.8.2
Switches to using upstream cmake files. Which means we don't need to use our own fork now.
There has been some good ARM ASIMD/SVE optimizations since our last update. I have also seen some additional changes merged, so when they do a version bump we should probably update again.
> Update xxhash to v0.8.2

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/32Bit_ASM/FEX_bugs/SignExtendBug.asm
- unittests/InstructionCountCI/FlagM/HotBlocks.json
This accidentally removed optimizations elsewhere that was only checking
for Add.
Adds a unit test that gets unveiled with this that #3421 ends up breaking.
> OpcodeDispatcher: Don't use AddShift with no shift

- FEXCore/Source/Utils/Allocator.cpp
Fixes an issue where TestHarnessRunner was managing to reserve the space below stack again, resulting in stack growth breaking. Would typically only show up when using the vixl simulator under gdb for some reason.
This is likely the last bandage on this code before it gets completely rewritten to be more readable.
> Fix reserving range check

- FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp
- unittests/InstructionCountCI/Atomics.json
- unittests/InstructionCountCI/Primary.json
ldswpal doesn't overwrite the source register and only reads the bits
required for the sized operation.
Not sure exactly why we were doing a copy here.
Removing it means improving Skyrim's hottest code block, as seen in https://github.com/FEX-Emu/FEX/issues/3472
> Arm64: Stop moving source in atomic swap

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/Atomics.json
- unittests/InstructionCountCI/FlagM/Atomics.json
> Optimize lock dec

- unittests/32Bit_ASM/FEX_bugs/SignExtendBug.asm
This time found in MGRR. It flips the problem space on its head.
Sorry @pmatos that I keep finding bugs and poking holes in your implementation.
> ASM: Another sign extend bug in #3421

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
- unittests/InstructionCountCI/FlagM/Atomics.json
- unittests/InstructionCountCI/FlagM/FlagOpts.json
- unittests/InstructionCountCI/FlagM/PrimaryGroup.json
This isn't as useful as you'd like, since the definition of SETF seems to be broken (due to a fundamental misunderstanding at Arm about how OF works?). But it's still a win in this one case.
> Use SETF8/16 for 8/16-bit INC/DEC

- Data/AppConfig/steamwebhelper.json
Fixes #3479
As of the Steam update on Feb 29 2024, this is no longer necessary and actually causes steamwebhelper to abort.
Steam has started using SLR to launch steamwebhelper, which already passes in --no-sandbox. Adding this argument twice seemingly breaks the application since it starts complaining that it doesn't understand the argument and closes with a SIGABRT.
With this removed Steam starts working again.
> Removes steamwebhelper config

- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/IoctlEmulation.cpp
The NVIF ioctl isn't publicly described in the nouveau headers and it is required for anything to work with Nouveau.
Pass the ioctl command through without modification and hope that this ioctl is architecture agnostic.
Gets NVK working with FEX on 32-bit.
> IoctlEmulation: Add missing nouveau ioctl

- ThunkLibs/include/common/Host.h
The converted `host_layout` object may be referenced by a pointer, so taking a copy would produce stale pointers. This is a regression from 28ae84cf60d7d7d25bee8f348791c8d8ad61098f.
Fixes a crash during startup of Wayland applications in Debug mode. (Release/RelWithDebInfo builds likely optimized the copy away.)
> Library Forwarding: Fix accidental data copying when converting from host to guest layout

- FEXCore/Source/Interface/Context/Context.h
Arguments and conditional doesn't get optimized out in release builds for the inline function call versus the define.
Was showing up an annoying amount of time when testing.
> Disable assert in release

- unittests/ASM/FEX_bugs/repeat_stringops_crash.asm
This unit test recreates the error condition that #3478 causes. With a string operation that is a backwards copy then the optimization will read past the end of the page and result in a crash.
Seemingly only happens with backwards string operations, but test forward and backward in this test.
> unittests/ASM: Implements a unit test for #3478

- FEXCore/Source/Utils/Allocator.cpp
- FEXCore/include/FEXCore/Utils/Allocator.h
- unittests/APITests/Allocator.cpp
- unittests/APITests/CMakeLists.txt
**Marked as draft seeking general feedback and a nod-off for a minor functional change.**
This throws the completely overblown handwritten state-machine that emulated regex parsing before. Instead, `/proc/self/maps` is parsed line-by-line, which flattens control flow and enables use of `std::from_chars`.
To minimize risk for regressions, interfaces have been changed to allow unit-testing this functionality. Special care was taken around the StackLocation case (see e.g. #3474) by uglifying `StealMemoryRegions`'s interface temporarily. This ensures each individual patch is correct, but the final patch drops this test coverage in the interest of keeping the interface clean.
A minor functional change was encountered during this testing: If the range end falls into the stack mapping, the new …
> Allocator: Cleanup StealMemoryRegions implementation

- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/X86Tables/SecondaryGroupTables.cpp
- unittests/ASM/Disabled_Tests_Simulator
- unittests/ASM/Secondary/09_F3_07.asm
- unittests/InstructionCountCI/SecondaryGroup.json
Missed this instruction when implementing rdtscp. Returns the same ID result in to register just like rdtscp, but without the cycle counter results. Doesn't touch any flags just like rdtscp.
> OpcodeDispatcher: Implement rdpid

- FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/LoadstoreOps.inl
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- unittests/InstructionCountCI/FEXOpt/AddressingLimitations.json
- unittests/InstructionCountCI/FlagM/SecondaryGroup.json
- unittests/InstructionCountCI/SecondaryGroup.json
x86 has a few prefetch instructions.
- prefetch - One of two classic 3DNow! instructions
- Prefetch in to L1 data cache
- prefetchw - One of two classic 3DNow! instructions
- Implies prefetch in to L1 data cache
- Prefetch cacheline with intent to write and exclusive ownership
- prefetchnta
- Prefetch non-temporal data in respect to /all/ cache levels
- Assumes inclusive caches?
- prefetch{t0,t1,t2}
- Prefetch data with respect to each cache level
- T0 = L1 and higher
- T1 = L2 and higher
- T2 = L3 and higher
**Some silly duplicates**
- prefetchwt1
- Duplicate of prefetchw but explicitly L1 data cache
- prefetch_exclusive
- Duplicate of prefetch
God Of War 2018 uses prefetchw as a hint for exclusive ownership of the
cacheline in some very aggressive spin-loops. Let's implement the …
> OpcodeDispatcher: Implement support for the various prefetch instructions

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Don't clobber NZCV.
Before/after assembly from the Primary_E1 unit test:
```
< 4340: [INFO] cset w20, ne
< 4340: [INFO] mrs x21, nzcv
< 4340: [INFO] cmp x5, #0x0 (0)
< 4340: [INFO] cset x22, ne
< 4340: [INFO] and x20, x22, x20
< 4340: [INFO] msr nzcv, x21
< 4340: [INFO] cbnz x20, #+0x8 (addr 0xffff896f8084) < 4340: [INFO] b #+0x1c (addr 0xffff896f809c)
< 4340: [INFO] ldr x0, pc+8 (addr 0xffff896f808c)
---
> 4340: [INFO] csel x20, x5, xzr, ne
> 4340: [INFO] cbnz x20, #+0x8 (addr 0xfffed7308070)
> 4340: [INFO] b #+0x1c (addr 0xfffed7308088)
> 4340: [INFO] ldr x0, pc+8 (addr 0xfffed7308078)
```
> OpcodeDispatcher: optimize LOOP/N/E

- FEXCore/Source/Utils/Telemetry.cpp
Since we do an immediate overwrite of the file we are copying, we can instead do a rename. Failure on rename is fine, will either mean the telemetry file didn't exist initially, or some other permission error so the telemetry will get lost regardless.
Basic renaming is also faster which is a nice benefit:
- renameat syscall: 0.000179 seconds
Old exist check + copy (sequence of syscalls):
- faccessat: 0.000027 s
- faccessat: 0.000011 s (directory cached in kernel now?)
- openat: 0.000016 s
- openat: 0.000104 s
- newfstatat: 0.000007 s
- fchmod: 0.000010 s
- sendfile: 0.000049 s
- close: 0.000065 s
- close: 0.000005 s
Total: 0.000294 s
> Telemetry: Rename old file instead of copying

- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
I find myself adding this every time I find a game that panic spills. Let's just print it out.
> RA: Adds RIP when a block panic spills

- Source/Tools/CommonTools/Linux/Utils/ELFParser.h
Clang-18 complains about this, use a vector instead.
> ELFParser: Stop using a VLA

- ThunkLibs/libvulkan/Host.cpp
The Vulkan specification states that "global commands" like vkCreateInstance may only be queried with a NULL instance. Some implementations return null pointers otherwise.
Fixes #3519.
> Library Forwarding/vulkan: Fix query of vkCreateInstance function pointer

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/include/FEXCore/Config/Config.h
- Source/Tools/FEXConfig/Main.cpp
This wasn't actually wired up to anything ever since some refactoring occured two years ago.
> FEXCore: Removes vestigial mman SMC checking

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- Source/Tools/FEXConfig/Main.cpp
Lets use control vector loadstores and memcpy/memset TSO visibility. This just gives us a bit more configuration rather than TSO off or on.
> FEXCore: Adds more TSO control levers

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/FlagM/HotBlocks_32Bit.json
- unittests/InstructionCountCI/FlagM/SecondaryGroup.json
- unittests/InstructionCountCI/SecondaryGroup.json
In the old case:
* if we take the branch, 1 instruction
* if we don't take the branch, 3 instruction
* branch predictor fun
* 3 instructions of icache pressure
In the new case:
* unconditionally 2 instructions
* no branch predictor dependence
* 2 instructions of icache pressure
This should not be non-neglibly worse, and it simplifies things for RA.
> OpcodeDispatcher: eliminate branch in cmpxchg pair

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/LookupCache.h
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
This hasn't been used and is blocking refactoring more code.
> FEXCore: Remove DebugStore map

- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
Just like #3508, clang-18 complains about VLA usage.
This vector is relatively small, only around 18 elements but is semi-dynamic depending on arch and if FEXCore is targeting Linux or Win32.
> RA: Removes VLA usage

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/HLE/SyscallHandler.h
- Source/Tools/CommonTools/CodeLoader.h
- Source/Tools/CommonTools/HarnessHelpers.h
- Source/Tools/FEXLoader/ELFCodeLoader.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
FEXCore no longer has a need for this since a bunch of related code was already moved to the frontend. Move the CodeLoader now.
> FEXCore: Moves CodeLoader to frontend

- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
Unused, and new RA won't use it either. Torch it.
> RA: drop dead block interference code

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/FlagM/SecondaryGroup.json
- unittests/InstructionCountCI/FlagM/Secondary_REP.json
- unittests/InstructionCountCI/SecondaryGroup.json
- unittests/InstructionCountCI/Secondary_REP.json
lot of complexity for only a single interesting case. we can massively simplify.
> OpcodeDispatcher: drop ZeroMultipleFlags

- FEXCore/Source/Interface/Core/DebugData.h
This isn't included or used anywhere, so it can be removed.
> DebugData: Remove header

- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Tony noticed this last week. I encountered it this week. Add support for spilling and filling GPR pairs.
> JIT: Adds support for spilling/Filling GPRPair

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/LookupCache.h
Rather than checking the actual EC bitmap in the dispatcher (~6 instrs), this indirection through the code cache allows just 1 instr for the hot path of calling repeated EC code/x64 code.
> LookupCache: Track ARM64EC page state in the code cache

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
There's quite a few places where the segment offset appending is open-coded throughout the opcode dispatcher, but we can pull these out into a few helpers to make the sites a little more compact and declarative.
> OpcodeDispatcher: Add helper for making segment offset addresses

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/IR/IR.json
We have LoadNamedVectorConstant that now performs this behavior while also being more flexible.
> IR: Remove VectorZero

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
GPR Direct/Indirect already had this and SIB version also already supported on the load side. Fixes this missed behaviour.
> OpcodeDispatcher: Fixes disabling TSO access on RSP SIB stores

- FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
These were broken to varying degrees across the board on win32, just switch to their std::filesystem as windows doesn't have the same allocator issues that require their reimplementation.
NOTE: using std::filesystem within syscall callbacks (i.e. invalidation related code) would still cause issues, however I don't see that ever happening on the FEX side?
> FHU: Switch over win32 file operations to std::filesystem

- CMakeLists.txt
- FEXCore/include/FEXCore/Utils/AllocatorHooks.h
Since FEX shares msvcrt with the guest on ARM64EC, FEX code can called into with the crt heap lock locked e.g by a system call callback inside of malloc. To avoid deadlocking in such scenarios jemalloc is used instead of msvcrt malloc.
> Enable jemalloc for ARM64EC

- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/InterpreterFallbacks.cpp
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
clang-format-16 had some issues with const placement, so we are manually changing these.
> Move const to the left in preparation for reformatting

- FEXCore/include/FEXCore/Utils/SignalScopeGuards.h
- Source/Tools/CommonTools/Linux/Utils/ELFContainer.h
- unittests/ThunkLibs/generator.cpp
- unittests/Utilities/DeleteOldSHMRegions.cpp
Followup to 2b4ec88daebd35fefb5bf5c73d7fc2b4155771ed. Some files needed a couple of calls to clang-format 16.0.6 to reach a fixed point.
> Reformat until fixed-point

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
- .github/workflows/hostrunner.yml
- .github/workflows/instcountci.yml
- .github/workflows/mingw_build.yml
- .github/workflows/vixl_simulator.yml
This setting was removed a while ago.
> CI: Drop use of obsolete ENABLE_X86_HOST_DEBUG setting

- .clang-format
- .clang-format-ignore
- Scripts/clang-format.py
- Scripts/reformat.sh
Adds paths to ignore to clang-format, .clang-format file. Also a wrapper script to clang-format to read .clang-format-ignore.
To format the whole tree at the root of the repository run: `find . -iname '*.h' -o -iname '*.cpp' -exec python3 Scripts/clang-format.py -i \{\} \;`
> Clang Format file and script

- Data/AppConfig/steamwebhelper.json
This app bypasses the glX functions exported by libGL and instead sends GLX requests directly via xcb. FEX won't support forwarding this usage pattern in the foreseeable future.
> AppConfig: Disable libGL forwarding for steamwebhelper

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- unittests/32Bit_ASM/Secondary/07_XX_04.asm
- unittests/ASM/Secondary/07_XX_04.asm
Found out that Far Cry uses this instruction and it is viable to use in CPL-3. This only returns constant data but its behaviour is a little quirky.
This instruction has a weird behaviour that the 32-bit operation does an insert in to the 64-bit destination, which might be an Intel versus AMD behaviour. I don't have an Intel machine available to test if that theory is true although. This assumption would match similar behaviour where segment registers are inserted instead of zext.
Gets the game farther but then it crashes in a `___ascii_strnicmp` function where the arguments end up being `___ascii_strnicmp(nullptr, "Color", 5);`.
> OpcodeDispatcher: Implement support for SMSW

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
messed up my RA.
fixes ShiftPF.asm with jit_1 with a pathological register allocation
> JIT: fix ShiftFlags shuffles

- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
Instead of only enabling enhanced rep movs if software TSO is disabled, Enable it if software tso is disabled OR memcpysettso is disabled. This is because now we hit the fast path when memcpysettso is disabled alone but global TSO is disabled.
Retested Hades and performance was fine in this configuration.
> CPUID: Enable enhanced rep movs in more situations

- Source/Windows/Common/InvalidationTracker.cpp
- Source/Windows/Common/InvalidationTracker.h
- Source/Windows/Defs/ntdll.def
- Source/Windows/WOW64/Module.cpp
- An invalidation event on one thread will now invalidate the cache across all threads.
- The entire section is now invalidated on section unmap events, rather than just the region of the section that contained the unmap address - this fixes msacm32 setup in wine.
> WOW64 backend code invalidation fixes

- FEXCore/Source/Utils/Allocator.cpp
This header was missing.
Either libstdc++14 or clang-18 changed includes and we were only getting this indirectly before.
> Allocator: Fixes compiling on Fedora 40

- ThunkLibs/GuestLibs/CMakeLists.txt
The library's soname is changed to libX11.so.6 and the CMake target is
renamed to libPlaceholderX11. This fixes two issues:
* Steam and mangohud can't find libX11 during startup if the library doesn't include a version suffix.
* Calling the CMake target libX11 overrode the true host X11 library used by unrelated targets (such as FEXConfig), which could cause link errors
> Library Forwarding: Fix issues with libGL's fake X11 dependency

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
We were previously genrating nonsense code if the destination != source:
faddp v2.4s, v4.4s, v4.4s
faddp s2, v4.2s
The result of the first faddp is ignored, so the second merely calculates the sum of the first 2 sources (not all 4 as needed).
The correct fix is to feed the first add into the second, regardless of the final destination:
faddp v2.4s, v4.4s, v4.4s
faddp s2, v2.2s
Hit in an ASM test with new RA.
> JIT: fix neon vec4 faddv

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
- FEXCore/Source/Utils/ArchHelpers/Arm64_stubs.cpp
- FEXCore/include/FEXCore/Utils/ArchHelpers/Arm64.h
- Source/Tools/FEXConfig/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Windows/WOW64/Module.cpp
A feature of FEX's JIT is that when an unaligned atomic load/store operation occurs, the instructions will be backpatched in to a barrier plus a non-atomic memory instruction. This is the half-barrier technique that still ensures correct visibility of loadstores in an unaligned context.
The problem with this approach is that the dmb instructions are HEAVY, because they effectively stop the world until all memory operations in flight are visible. But it is a necessary evil since unaligned atomics aren't a thing on ARM processors. FEAT_LSE only gives you unaligned atomics inside of a 16-byte granularity, which doesn't match x86 behaviour of cacheline size (effectively always 64B).
This adds a new TSO option to disable the half-barrier on unaligned atomic and instead only convert it to a …
> Arm64: Adds another TSO hack to disable half-barrier TSO

- Scripts/clang-format.py
> clang-format: allow overriding clang-format

- FEXCore/Source/Interface/Core/CPUID.cpp
This was inverted and always enabling the RDTSCP cpuid bit for wine. Thus always disabling it elsewhere.
> CPUID: Fix inverted RDTSCP check

- FEXCore/Source/Interface/Core/CPUID.cpp
- docs/CPUID.md
Moves it to the hypervisor leafs.
Before:
```bash
$ FEXBash 'cat /proc/cpuinfo | grep "model name"'
model name      : FEX-2404-101-gf9effcb           Cortex-A78C
model name      : FEX-2404-101-gf9effcb           Cortex-A78C
model name      : FEX-2404-101-gf9effcb           Cortex-A78C
model name      : FEX-2404-101-gf9effcb           Cortex-A78C
model name      : FEX-2404-101-gf9effcb           Cortex-X1C
model name      : FEX-2404-101-gf9effcb           Cortex-X1C
model name      : FEX-2404-101-gf9effcb           Cortex-X1C
model name      : FEX-2404-101-gf9effcb           Cortex-X1C
```
After:
```bash
$ FEXBash 'cat /proc/cpuinfo | grep "model name"'
model name      : Cortex-A78C
model name      : Cortex-A78C
model name      : Cortex-A78C
model name      : Cortex-A78C
model name      : …
```
> CPUID: Removes FEX version string from CPU model name

- Source/Tools/FEXLoader/FEXLoader.cpp
From `man 2 open`:
> The mode argument must be supplied if O_CREAT or O_TMPFILE is
> specified in flags; if it is not supplied, some arbitrary bytes
> from the stack will be applied as the file mode.
(Fix broken build on Fedora Rawhide: https://download.copr.fedorainfracloud.org/results/teohhanhui/fex-emu/fedora-rawhide-aarch64/07399392-fex-emu/builder-live.log.gz)
> Pass compulsory `mode` argument to `open` when `O_CREAT` is used

- Readme.md
This is no longer the case as x86-64 hosts is purely a development vehicle and it is not expected for users to try this.
> Readme: Remove misleading text about x86 hosts being supported

- CMakeLists.txt
This setting was removed in Catch2 3.0 and has no effect anymore.
> CMake: Remove obsolete Catch2 setting

- Source/Tools/FEXServer/ProcessPipe.cpp
- Source/Tools/FEXServer/SquashFS.cpp
- Source/Tools/FEXServer/SquashFS.h
Was causing unnecessary memory allocation churn when a FEXInterpreter was asking for the rootfs folder path.
> FEXServer: Removes temporary variable allocation

- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
A bit of refactoring necessary before we can move the remaining Linux specific code to the frontend.
Most of this taken from #3535 but attempting to be NFC as much as possible.
> FEXLoader: Changes frontend thread management to wrap FEXCore thread objects

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- FEXCore/include/FEXCore/Core/CoreState.h
- FEXCore/include/FEXCore/Utils/AllocatorHooks.h
- FEXCore/include/FEXCore/Utils/EnumOperators.h
- FEXCore/include/FEXCore/Utils/SignalScopeGuards.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- docs/DeferredSignals.md
- unittests/InstructionCountCI/FlagM/SecondaryModRM.json
- unittests/InstructionCountCI/SecondaryGroup.json
- unittests/InstructionCountCI/SecondaryModRM.json
Arm64ec introduced the InterruptFaultPage which is lower overhead since instead of ldr+str it just turns in to a single str. We were already allocating the space, FEXCore and the frontend signal delegator just needed to be updated to understand the new location.
We can additionally use this in the future if we want to make deferred async signals INSIDE the JIT only cost a single str as well.
Side-benefit: Shaving 1 page off each thread's state object allocation size. From 3 pages down to 2. Not much but eh, isn't the point of this PR.
> FEXCore: Get rid of DeferredSignalFaultAddress and use the InterruptFaultPage

- .github/workflows/pr-code-format.yml
Sometimes github or the CI runner times out trying to checkout the source and stays timing out forever.
Give it a three minute timeout otherwise the CI runner will stall forever.
This seems to occur if you push a change to a branch and then force push a new commit before the original code format step has run. It forever walks backwards trying to find a commit and it can't ever find one.
> Github: Support a timeout on checkout

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Part of my project to clean up FEXCore in prep. for IR go-fast
> JIT/VectorOps: deduplicate common implementations

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/IR/AOTIR.cpp
- FEXCore/Source/Interface/IR/AOTIR.h
- FEXCore/Source/Interface/IR/IREmitter.h
- FEXCore/Source/Interface/IR/IntrusiveIRList.h
- FEXCore/Source/Interface/IR/RegisterAllocationData.h
FEX normally stores IR/RA data on the heap, but it can also read them as an overlay from a memory-mapped file if IR caching is used. This requires a careful dance around ownership issues, which is an easy source for memory leaks or double-frees that are difficult to audit for.
This PR identifies two core issues and fixes them:
1. Raw pointers are passed across multiple layers and modules without indication of memory ownership
2. The `IRListView` type can either act as a proper, non-owning view, or it can act as an owning container. In practice it's often impossible to tell if code referencing an `IRListView` owns the underlying memory or not.
The solution to (2) is to split `IRListView` into two types: One for the purely non-owning view, and one for memory storage (which in turn can be …
> AOTIR: Refactor interfaces to clarify ownership flow

- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
no instcountci changes. The RCLSE patch may cause behaviour change but only due to RCLSE bugs not yet hit in instcountci. We should fix those.
> ConstProp, RCLSE: simplifications

- unittests/ASM/Disabled_Tests
- unittests/ASM/FEX_bugs/XeSS_quadratic.asm
Useful smoke test for the asymptoptic behaviour of our constant pooling code. Not useful for correctness testing, so skip in CI.
> unittests: add XeSS test

- unittests/InstructionCountCI/FlagM/HotBlocks.json
this was basically practice for using perf with FEX, but a few things do stand out in the assembly as suboptimal.
> InstructionCountCI: add bytemark hot block

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- unittests/InstructionCountCI/FlagM/Secondary.json
from looking idly at bytemark asm
> Optimize large sign-extended constants

- FEXCore/Source/Interface/Config/Config.json.in
After two months of testing I finally have enough confidence that these default options getting changed is safe enough that most games won't notice the difference. But the performance differences can be wild.
Might want to come back and reenable this on platforms that support hardware TSO and LRCPC3 (for the vector feature), but we can care once those platforms come up to speed.
> Config: Change default TSO options

- Source/Common/FEXServerClient.h
- Source/Tools/FEXServer/Logger.cpp
- Source/Tools/FEXServer/Main.cpp
This was a bit confusing to read and I had always expected to change this at some point.
Previous:
```
[INFO][1579518391560577][1601857.1601857] clone: Unsupported flags w/o CLONE_THREAD (Shared Resources), 4100
```
Now:
```
[INFO][1590468.992593376][1629501.1629501] clone: Unsupported flags w/o CLONE_THREAD (Shared Resources), 4100
```
> FEXLogging: Changes representation of timestamp

- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Tools/FEXLoader/ELFCodeLoader.h
- Source/Tools/FEXLoader/FEXLoader.cpp
In preparation for seccomp execve inheritance where we need to extract another FD from a different environment variable.
- Small function to extract the FD and also unset the environment variable in the same place.
- Keeping the fetch and unset together instead of spreading to another location in the source.
- Extract the FD upfront instead of passing the string_view around, since we are unsetting the environment variable at the same place.
Future seccomp inheritance will get the FD just after the FEXFD
- `int FEXSeccompFD {GetFEXFDFromEnv("FEX_SECCOMPFD")};`
> FEXLoader: Cleanup FD extraction from environment variables

- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- unittests/ASM/FEX_bugs/SIBScaleTranspose.asm
- unittests/ASM/FEX_bugs/VectorLoadCrash.asm
- unittests/InstructionCountCI/FEXOpt/AddressingLimitations.json
Alongside #3666 This will fix Darwinia's Linux executable.
Two bugs here.
ConstProp with AddShift was transposing Base and Offset registers, which means we were scaling the Base and not scaling Offset.
Additionally we were accidentally allowing GPR loadstore limits on Vector loadstores which is invalid.
Both of these combined were causing fault behaviour in Darwinia after #3666 was fixed.
> ConstProp fixes for Darwinia

- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.h
- unittests/FEXLinuxTests/tests/fs/self_symlink.cpp
When asked to not follow the symlink, FEX needs to return data about the symlink itself rather than following to the target executable. In that case we need to return symlink information otherwise games that sanity check can break.
This is what happened with Darwinia in #3662.
We return the FEXInterpreter symlink information in this case since it doesn't return any information that is relevent to leaking emulator state. Once the application asks to follow through to the symlink target is when we will replace.
Also adds a unit test to ensure we don't break it.
> FileManagement: Fix fstatat/statx with self and NOFOLLOW

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- unittests/InstructionCountCI/Atomics.json
- unittests/InstructionCountCI/FlagM/PrimaryGroup.json
- unittests/InstructionCountCI/H0F38.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
- unittests/InstructionCountCI/Primary_32Bit.json
- unittests/InstructionCountCI/VEX_map1.json
Many FEX IR ops want their dests assigned to the same register as a particular source. Denote this in the IR.
Then, add a very simple heuristic in the RA to take advantage of this in typical cases. The "proper" RA handling will hopefully come soon(tm) in a follow up PR, that will guarantee coalescing in all cases to let us delete a chunk of JIT code. But this is a step towards that anyhow.
> Track tied sources in the IR

- FEXCore/docs/MemoryModelEmulation.md
I keep needing to look these up to remember the limitations. Add a doc file so I can more easily point to the information.
> FEXCore/docs: Adds programmer documentation about memory model emulation

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/Source/Interface/IR/IREmitter.cpp
- FEXCore/Source/Interface/IR/IREmitter.h
- FEXCore/Source/Interface/IR/IntrusiveIRList.h
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- FEXCore/Source/Interface/IR/Passes/LongDivideRemovalPass.cpp
- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
This is a step towards the new IR, where we don't have pointerful data structures and instead have flat handles only. Naming inspired by `ibc_ref`, it represents a reference to a source or destination (which are not explicitly stored).
> Find-and-replace OrderedNode* with Ref

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
In preparation for seccomp execve inheritance.
We are going to need to add a new environment variable earlier in the execve sequence to handle inheritance in the case of binfmt_misc.
No functional change in regards to envp handling.
Minor change around execveat with FD without binfmt_misc. In the case that execveat returned an error and we did a `dup` of the FD then we would have an FD leak. Make sure to close the duplicated FD in that instance.
> LinuxSyscalls: Cleanup envp copying in execve

- unittests/ASM/VEX/bextr.asm
dougallj mentioned that adding these tests might expose a bug in bextr. Since bextr implementation was changed apparently it now works correctly, that's good.
> unittests/bextr: add SrcSize tests

- ThunkLibs/Generator/analysis.cpp
- ThunkLibs/Generator/gen.cpp
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
- ThunkLibs/include/common/Host.h
- ThunkLibs/include/common/X11Manager.h
- ThunkLibs/libGL/libGL_Guest.cpp
- ThunkLibs/libGL/libGL_Host.cpp
- ThunkLibs/libGL/libGL_interface.cpp
This PR adds support for forwarding the overwhelming majority of the OpenGL API to the host driver for 32-bit applications. Previously, this was exclusively possible for 64-bit titles.
This work is enabled by #3584, thanks to which forwarding OpenGL calls to the host does not require forwarding libX11 calls anymore. We can now tick off the last critical box in the [Library Forwarding Roadmap](https://gist.github.com/neobrain/3812c111a2da57bfd8376dd21d61a886):
|                          | X11 (64-bit) | Wayland (64-bit) | Wayland (32-bit) | X11 (32-bit) |
| ------------------------ | ------------ | ---------------- | ---------------- |------------- |
| no forwarding            | ☑️ 2022      | ☑️ 2022         | ☑️ 2022          | ☑️ 2022      |
| only Wayland forwarding  | N/A          | …
>  Library Forwarding: Add support for 32-bit OpenGL

- Scripts/InstallFEX.py
After running the script my Ubuntu 24.04 lists https://ppa.launchpadcontent.net/fex-emu/fex/ubuntu in the output of `apt-cache policy` (which means GetPPAStatus would always fail).
Now, maybe older Ubuntus use http://ppa.launchpad.net/fex-emu/fex/ubuntu? If not then I guess the fix is just this commit, otherwise some sort of `or` with strings would be in order.
> Scripts/InstallFEX: update PPA URL

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- unittests/InstructionCountCI/Atomics.json
- unittests/InstructionCountCI/FlagM/Atomics.json
- unittests/InstructionCountCI/FlagM/Primary.json
- unittests/InstructionCountCI/FlagM/PrimaryGroup.json
- unittests/InstructionCountCI/FlagM/VEX_map2.json
- unittests/InstructionCountCI/Primary.json
- unittests/InstructionCountCI/PrimaryGroup.json
- unittests/InstructionCountCI/VEX_map2.json
This reverts commit bb8336fcad9cf5619215e5a9f765ca48c7d48970.
Fixes #3686
Tried creating some unit tests to figure out why this is broken, but it is likely an interaction between multiple instructions.
Revert for now to fix the compatibility issue, which will be a minor performance hit.
> Revert "OpcodeDispatcher: optimize logical flags"

- FEXCore/unittests/Emitter/ASIMD_Tests.cpp
Updates vixl to track the latest upstream changes that fix erroneous non-zeroing behavior for 256-bit vectors
> Externals: Update vixl submodule

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/ASM/FEX_bugs/NegativeCallAddressSizeOverride.asm
FEX had a bug with this instruction where it was incorrectly using both the address size override and operand size override to truncate the immediate offset. This isn't how the instruction should behave as it should actually ignore the address size override.
This now puts it correctly inline with how the jump instruction works and adds a unit test to ensure it doesn't break again.
This fixes a crash from the Arch rootfs from the glibc dynamic linker being compiling in a way where a call instruction was getting aligned using this prefix (Since the compiler knew it does nothing).
As a side-note, FEX doesn't handle 16-bit displacement at all in both the jump and call instructions. This is because the operand size qualifier controls both the immediate size and the RIP size. This is because …
> FEXCore: Fixes Call with 32-bit displacement and address size override

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
I fixed this when we landed the new RA
> Arm64Emitter: drop out of date comment

- FEXCore/Scripts/json_ir_generator.py
this makes the print more noisy for no benefit, don't do it.
before:
%9(GPRFixed16) i32 = Add OpSize:Tmp:Size, %6(GPRFixed0) i64, %17(Invalid)
%10(GPR0) i64 = Bfi OpSize:Tmp:Size, #0x10, #0x0, %6(GPRFixed0) i64, %9(GPRFixed16) i32
(%11 i64) StoreRegister %6(GPRFixed0) i64, #0x11, GPR, u8:Tmp:Size
(%12 i64) StoreRegister %9(GPRFixed16) i32, #0x10, GPR, u8:Tmp:Size
(%13 i64) StoreRegister %10(GPR0) i64, #0x0, GPR, u8:Tmp:Size
after:
%9(GPRFixed16) i32 = Add %6(GPRFixed0) i64, %17(Invalid)
%10(GPR0) i64 = Bfi #0x10, #0x0, %6(GPRFixed0) i64, %9(GPRFixed16) i32
(%11 i64) StoreRegister %6(GPRFixed0) i64, #0x11, GPR
(%12 i64) StoreRegister %9(GPRFixed16) i32, #0x10, GPR
(%13 i64) StoreRegister %10(GPR0) i64, #0x0, GPR
> json_ir_generator: don't print unrecoverable temps

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/PassManager.cpp
- FEXCore/Source/Interface/IR/Passes.h
- FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
In quite a few locations we are mixing the case that SVE256 == AVX or that AVX means the guest register size is 256-bit.
While this is true today, this is entanglement is going to change very quickly and cause confusion in follow-up PRs.
Now we have SVE128, SVE256, and SVE2 HostFeatures to disambiguate the different features which mean different things.
This PR keeps the alias that `SupportsAVX` = `SupportsSVE256 && SupportsSVE2` but that alias is going to very quickly change its definition.
> FEXCore: Disentangle the SVE256 feature from AVX

- Source/Tools/FEXGetConfig/Main.cpp
Allows a nice way to get information about how TSO emulation is occuring on the individual's hardware. In particular, the more subtle details around the implementation rather than just a hard on or off toggle.
Base ARMv8.0 implementation:
Cortex-A78AE:
Apple Silicon on Asahi Linux:
> FEXGetConfig: Support the ability to get TSO emulation facts

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
Pulled from the seccomp WIP PR where it pulls this object more frequently. Since it is an opaque frontend pointer it needs to be cast and we already have a few locations that use it.
No functional change.
> LinuxEmulation: Add a helper for getting the ThreadStateObject from CPU frame

- Source/Common/CMakeLists.txt
- Source/Common/Config.cpp
- Source/Common/JSONPool.cpp
- Source/Common/JSONPool.h
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
Fixes #3691
We weren't checking if the file was empty before using its `at` function member. This was causing an early crash if the config file existed but was empty.
Consolidates the three locations that copy and pasted the json allocator tools and adds an empty check for all of them.
Also adds two missing checks to the ThunksDB handler that could have resulted in the same crash if ThunksDB was an empty file.
> FEX: Consolidate JSON allocators and fix 3691

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Extract some helpers to deduplicate the code to decode address modes, so when AVX128 adds its own load/store helpers we won't end up with 4 (!) copies of this logic.
[I'm now porting the AVX128 helpers to use this, don't worry about that]
> OpcodeDispatcher: Refactor address modes

- unittests/InstructionCountCI/FEXOpt/AddressingLimitations.json
- unittests/InstructionCountCI/FEXOpt/AddressingLimitations_32Bit.json
add a bit of coverage for this funny addressing corner. We do handle this optimally but I had to write this to check ;)
> InstCountCI: add segment register cases

- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.cpp
Fixes #3675
This was the first time I've ever actually dived in to this code and this function melted my brain a bit while reading it. It was trying to be too smart in tracking VMA splits, but if it split right at the end of a VMA range it would then add a new range at the end where one already existed. This then caused us to have overlapping VMA ranges and it would completely break our SMC tracking since all tracking in the map must not overlap.
Instead of being too smart, just break it down in to 4 merge strategies, three of which are one shot. This is significantly easier to reason about and each strategy is mostly self-contained. The fourth strategy in the list is the most complex since it requires multiple steps since it needs to walk multiple VMAs.
To help test this I added some …
> SMCTracking: Fix incorrect mprotect tracking

- unittests/ASM/VEX/vtestps.asm
Makes it easier to see what is failing on the 128-bit side versus 256-bit side.
> unittests: Split up vtestps unittest to accumulate flags in independent registers.

- FEXCore/Source/Interface/Core/CPUID.cpp
These aren't reserved and I was confused that they were missing.
> CPUID: Update labeling on some reserved bits

- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
First use case of the binary operation helper. Some are related, some are not.
Removing the `SupportsSaturatingRoundingShifts` option because it's always true now.
> AVX128: Some pun pickles, moves and conversions

- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Arm64: Implement support for emulated masked vector loadstores
In order to support `vmaskmov{ps,pd}` without SVE128 this is required.
It's pretty gnarly but they aren't often used so that's fine from a
compatibility perspective.
Example SVE128 implementation:
```json
"vmaskmovps ymm0, ymm1, [rax]": {
"ExpectedInstructionCount": 9,
"Comment": [
"Map 2 0b01 0x2c 256-bit"
],
"ExpectedArm64ASM": [
"ldr q2, [x28, #32]",
"mrs x20, nzcv",
"cmplt p0.s, p6/z, z17.s, #0",
"ld1w {z16.s}, p0/z, [x4]",
"add x21, x4, #0x10 (16)",
"cmplt p0.s, p6/z, z2.s, #0",
"ld1w {z2.s}, p0/z, [x21]",
"str q2, [x28, #16]",
"msr nzcv, x20"
]
},
```
Example ASIMD implementation
```json
"vmaskmovps ymm0, ymm1, [rax]": {
"ExpectedInstructionCount": 35,
"Comment": [
"Map 2 0b01 0x2c 256-bit"
],
"ExpectedArm64ASM": [
"ldr …
```
> Arm64: Implement support for emulated masked vector loadstores

- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
Previously we could always tell the size of the operation depending on how this effects the operating size of the instruction. Converting 64-bit down to 32-bit as an example.
AVX gather instructions are the first instruction class that can't infer this information. The element load size is determined by the W flag but the operating size of 128-bit or 256-bit is determined by other means.
Expose this flag so we can determine this difference. The FMA instructions are going to need this flag as well.
> Frontend: Expose AVX W flag

- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
Any time we get the value of Literal, we want to assert that it's actually a
literal. We've been open coding this pattern sporadically throughout the
opcodedispatcher. Let's add an ergonomic helper to fetch the value of literal,
asserting that the value is indeed literal.
This is very noticeable in the AVX changes.
> X86Tables: add Literal() helper

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/WOW64/Module.cpp
Due to the distinct view of AVX registers changing depending on if the host supports SVE256 or not, introduce some helpers to reconverge the view in the ways that Linux and Wow64 wants.
The TestHarnessRunner has a bit of a kludge but rewriting it to not read the InternalThreadState object directly will take longer than currently desired. So fetch the register state, then reconverge the AVX register state. Once the InternalThreadState object changes its view to cut out those excess 256bytes then this will get refactored at that point.
> FEXCore: Implement AVX reconstruction helpers

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
A smattering of scalar operations and vector shifts.
> AVX128: More various instructions

- .github/workflows/ccpp.yml
- .github/workflows/glibc_fault.yml
- .github/workflows/hostrunner.yml
- .github/workflows/instcountci.yml
- .github/workflows/mingw_build.yml
- .github/workflows/vixl_simulator.yml
- CMakeLists.txt
This is a footgun for users to allow this configuration through without anything stopping them.
Had a user try this configuration today and not understand that it isn't supported.
> Adds back cmake error on x86-64 hosts

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Based on top of #3746
Adds AES instructions, SSE4.2 string ops, silly minposuw, and rounds.
> AVX128: More instructions Part 3

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
Oops, this was just completely wrong.
> AVX128: Fixes SSE4.2 string compare instructions

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- unittests/ASM/VEX/vpclmulqdq_256.asm
use the helper. I assumed the lack of zero extension here was intentional.
alternative to #3759
> AVX128: fix VPCLMULQDQl

- FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/VEX_map3.json
We can avoid a LOT of pointless work with some dedicated IR ops for specifically
overriding the round mode.
Small behaviour change here: we no longer reset FTZ. I think this is a bug fix?
But if it's not it's not hard to fix.
> Optimize vcvtps2ph

- FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/ASM/Disabled_Tests_Simulator
- unittests/ASM/VEX/vcvtps2ph_rd_mxcsr.asm
- unittests/ASM/VEX/vcvtps2ph_rtne_mxcsr.asm
- unittests/ASM/VEX/vcvtps2ph_ru_mxcsr.asm
- unittests/ASM/VEX/vcvtps2ph_trunc_mxcsr.asm
Adds a couple unit tests to ensure MXCSR is adhered to as well
> AVX128: F16C support

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
During refactoring this was missed and rerunning unittests locally caught it. 256-bit operations get their shift only from the lower half of the vector register.
> AVX128: Fixes wide shifts

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/ASM/FEX_bugs/mov_address_size_override.asm
When the source or destination is a register, the address size override doesn't apply. We were accidentally applying it on all sources regardless of type which was causing us to zero extend on operations that aren't affected by address size override.
This fixes the OpenSSL cert error in every application, but most importantly Steam.
> FEXCore: Fixes address size override on GPR sources and destinations

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- unittests/InstructionCountCI/AVX128/VEX_map2.json
- unittests/InstructionCountCI/AVX128/VEX_map2_SVE128.json
This accidentally snuck in. Scalar FMA is quite a bit more flexible on ASIMD, so this removes a bunch of redundant moves and a negation on one.
> AVX128: Fixes scalar FMA accidentally using vector wide

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/AVX128/VEX_map2.json
Generate the same mask register once and use it for both low and high 128-bits
> AVX128: Minor optimization to 256-bit vpshufb

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- unittests/ASM/VEX/vmovlhps.asm
- unittests/InstructionCountCI/AVX128/VEX_map1.json
- unittests/InstructionCountCI/VEX_map1.json
We didn't have a unit test for this and we weren't implementing it at all.
We treated it as vmovhps/vmovhpd accidentally. Once again caught by the libaom Intrinsics unit tests.
> AVX128: Fixes vmovlhps

- CodeEmitter/CodeEmitter/LoadstoreOps.inl
- unittests/ASM/FEX_bugs/smallvectorload_regreg.asm
We had failed to enable these implementations for the `ExtendedMemOperand` helpers. We had already implemented the non-helper forms, which are already tested in CI. These helpers just weren't updated?
Noticed this when running libaom's SSE4.1 tests, where it managed to execute a pmovzxbq instruction with reg+reg memory source and was breaking the test results.
There are /very/ few vector register operations that access only 8-bit or 16-bit in vectors so this flew under the radar for quite a while.
Fixes their unit tests.
Also adds a unittest using sse4.1 pmovzxbq to ensure we support the reg+reg case, and also a few other instructions to test 8-bit and 16-bit vector loads and stores.
> CodeEmitter: Fixes vector {ldr,str}{b,h} with reg-reg source

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/AVX128/VEX_map1.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/VEX_map1.json
The canonical way to generate a zero register vector in x86 is to xor
itself. Capture this can convert it to canonical zero register instead.
Can get zero-cycle renamed on latest CPUs.
> OpcodeDispatcher: Optimize x86 canonical vector zero register 

- CodeEmitter/CodeEmitter/SVEOps.inl
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/unittests/Emitter/SVE_Tests.cpp
- unittests/InstructionCountCI/AVX128/VEX_map1.json
- unittests/InstructionCountCI/AVX128/VEX_map1_SVE128.json
- unittests/InstructionCountCI/VEX_map1.json
x86 doesn't have a lot of non-temporal vector stores but we do have a
few of them.
- MMX: MOVNTQ
- SSE2: MOVNTDQ, MOVNTPS, MOVNTPD
- AVX: VMOVNTDQ (128-bit & 256-bit), VMOVNTPD
Additionally SSE4a adds 32-bit and 64-bit scalar vector non-temporal
stores, which we keep as regular stores. Since ARM doesn't have matching
semantics for those. MMX non-temporal store is also untouched since no matching semantics.
Additionally SSE4.1 adds non-temporal vector LOADS which this doesn't
touch.
- SSE4.1: MOVNTDQA
- AVX: VMOVNTDQA (128-bit)
- AVX2: VMOVNTDQA (256-bit)
Fixes https://github.com/FEX-Emu/FEX/issues/3364
> OpcodeDispatcher: Implement support for non-temporal vector stores 

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/AVX128/VEX_map3_SVE128.json
This is a very minor performance change. On Cortex CPUs that support
SVE, they do movprfx+<instruction> fusion to remove two cycles and a
dependency from the backend.
This is a minor win to convert from ASIMD mov+bsl to SVE movprfx+bsl
because of this, saving two cycles and a dependency on Cortex A710 and
A715. This is slightly less of a win on Cortex-A720/A725 because it supports
zero-cycle vector register renames, but it is still a win on Cortex-X925
because that is an older core design that doesn't support zero-cycle
vector register renames.
Very silly little thing.
> Arm64: Minor VBSL optimization with SVE128 

- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- unittests/ASM/FEX_bugs/LongSignedDivide.asm
The two halves are provided as two uint64_t values that shouldn't be
sign extended between them. Treat them as uint64_t until combined in to
a single int128_t. Fixes long signed divide.
> Arm64: Fixes long signed divide 

- FEXCore/Source/Common/SoftFloat.h
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/F80Fallbacks.h
- unittests/ASM/FEX_bugs/x87_integer_indefinite.asm
Regardless of positive or negative value, if the converted integer
doesn't fit in to the converted int16_t then it returns INT16_MIN.
> Softfloat: Fixes Integer indefinite return for 16-bit signed values 

- .github/workflows/mingw_build.yml
- CMakeLists.txt
- Source/Windows/CMakeLists.txt
Dep on #3773, the toolchain artifact from https://github.com/bylaws/llvm-mingw/releases/download/20240628/llvm-mingw-20240627-ucrt-ubuntu-20.04-aarch64.tar.xz  will also need to be installed on the runner
> FEXCore ARM64EC CI support

- FEXCore/Source/Interface/Core/CPUID.cpp
These should be making their way to the market sooner rather than later so make sure we have the descriptor text for them.
> CPUID: Adds a few missing CPU names for new CPU cores

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- unittests/InstructionCountCI/AVX128/VEX_map2_SVE128.json
- unittests/InstructionCountCI/VEX_map2.json
The codepath from https://github.com/FEX-Emu/FEX/pull/3826 was only targeting 256-bit sized operations.
This missed the vpgatherdq/vgatherdpd 128-bit operations. By extending
the codepath to understand 128-bit operations, we now hit these
instruction variants.
With this PR, we now have SVE128 codepaths that handle ALL variants of
x86 gather instructions! There are zero ASIMD fallbacks used in this
case!
Of course depending on the instruction, the performance still leaves a
lot to be desired, and there is no way to emulate x86 TSO behaviour
without an ASIMD fallback, which we will likely need to add as a
fallback at some point.
Based on https://github.com/FEX-Emu/FEX/pull/3836 until that is merged.
> AVX128: Extends 32-bit indexes path for 128-bit operations 

- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- unittests/InstructionCountCI/AVX128/VEX_map2.json
- unittests/InstructionCountCI/AVX128/VEX_map2_SVE128.json
- unittests/InstructionCountCI/VEX_map2.json
If the destination isn't any of the incoming sources then we can avoid
one of the moves at the end. This half works around the problem proposed
in https://github.com/FEX-Emu/FEX/issues/3794, but doesn't solve the entire problem.
To solve the other half of the moving problem means we need to solve the
SRA allocation problem for this temporary register with addsub/subadd, so it gets allocated
for both the FMA operation and the XOR operation.
> Arm64: Remove one move if possible in FMA operations 

- FEXCore/include/FEXCore/fextl/memory.h
`fextl::default_delete<...>{}(nullptr)` must be a no-op, reflecting behavior of std::default_delete.
Previously, `std::destroy_at` would invoke the destructor on null objects.
> fextl: Properly handle nullptr arguments in fextl::default_delete

- FEXCore/Source/Interface/IR/AOTIR.h
Originally brought up in #3618.
> AOTIR: Change std::unique_ptr to fextl::unique_ptr

- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Common/JSONPool.cpp
- Source/Common/JSONPool.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Ioctl/drm.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Semaphore.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Socket.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Types.h
Fixes all warnings I found in my local build configuration, excluding those from External/.
Two few patches are worth highlighting (others are trivial):
* de258ced20f9351b55281fd87accc5cbe91e0938: Adds an **internal** `unique_ptr` replacement, side-stepping the issues mentioned in a prior attempt in #3618 . By dropping movability, this becames a mere auto-deleting wrapper for non-transferable memory, which makes it much easier to reliably implement while allowing the rest of the code to continue using `std::unique_ptr`.
* 68936a0dce59e34fccb5819bc29e8776978676e2: Structs embedding `compat_ptr` can't use custom constructors without triggering warnings. Luckily we only need the constructors when *initializing data* or when *calling functions*, which can both be served by a utility class …
> Fix all the warnings

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Scripts/InstructionCountParser.py
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/AVX128/VEX_map2_flagm.json
- unittests/InstructionCountCI/FlagM/VEX_map2.json
- unittests/InstructionCountCI/VEX_map2.json
- unittests/InstructionCountCI/VEX_map2_svebitperm.json
PEXT: 12 (With a loop!) -> 4 instructions
PDEP: 14 (With a loop!) -> 4 instructions
Cortex's bext/bdep instructions are pretty quick, 4 or 6 cycles depending on if it is Cortex-A versus Cortex-X. Bit of a shame that Cortex-X has a cycle penalty here, but it'll be significantly faster than the looping variant regardless.
Fixes #3851
> Arm64: Implement support for SVE bitperm

- CodeEmitter/CodeEmitter/SVEOps.inl
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/unittests/Emitter/SVE_Tests.cpp
- unittests/InstructionCountCI/AVX128/VEX_map2_SVE128.json
- unittests/InstructionCountCI/VEX_map2.json
Implements support for both SSE4.1 128-bit NT load and AVX 128/256-bit NT loads
Only feature missing is doing a 256-bit load with AVX128 using LDNP for discontiguous registers, but we don't have a sane way to return results in two different vector registers today.
Fixes #3790
> Implement support for SSE4.1/AVX NT loads

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Clang was inlining a few of the functions it was calling. So force it never to inline since this is suppose to be a little shim trampoline only.
> OpcodeDispatcher: Force noinline for the function call in the Bind helper

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
- FEXCore/Source/Interface/HLE/Thunks/Thunks.h
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/LinuxEmulation/VDSO_Emulation.cpp
- Source/Tools/LinuxEmulation/VDSO_Emulation.h
This causes a global initializer that registers an atexit handler.
Be smarter, use an std::array and pass its data around using a span instead.
Removes the global initializer and removes the atexit installation
> VDSO: Stop using a vector for a static

- FEXCore/Source/Utils/LogManager.cpp
- FEXCore/include/FEXCore/Utils/LogManager.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
We never use more than one logging method at a time so this was overengineered for what it is doing.
Instead only allow one handler for messages and throw messages each which just is a pointer.
Removes a global initializer and an atexit handler being installed
> LogManager: Removes fextl::vector usage

- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/IoctlEmulation.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/IoctlEmulation.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Syscalls.cpp
Removes a global static initializer for the vector and its atexit handler.
This handler array can be consteval similar to the x86 tables so it can be generated entirely at compile time.
> Ioctl32: Removes static fextl::vector in ioctlemulation

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/ASM/FEX_bugs/vmov_size_test.asm
- unittests/InstructionCountCI/AVX128/VEX_map1.json
This was doing a 128-bit load from memory and then a 64-bit zero extend
which looked like a spurious move but it was trying to match the
behaviour of vmovq where it needed the zero extend.
Also adds a unit test to ensure that we aren't loading too much data by
loading right up against a page boundary.
Fixes https://github.com/FEX-Emu/FEX/issues/3787
> AVX128: Fixes vmovq loading too much data

- FEXCore/Source/Utils/Telemetry.cpp
- FEXCore/include/FEXCore/Utils/Telemetry.h
Removes global initializer for telemetry values since their address is visible and PIC relative code loading handles the address fetching for us.
> Telemetry: Change how visibility of telemetry values work

- CMakeLists.txt
- Source/Windows/ARM64EC/BTInterface.h
- Source/Windows/ARM64EC/CMakeLists.txt
- Source/Windows/ARM64EC/Module.S
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/ARM64EC/libarm64ecfex.def
- Source/Windows/CMakeLists.txt
- Source/Windows/WOW64/CMakeLists.txt
- Source/Windows/include/winnt.h
- Source/Windows/include/winternl.h
This implements an ARM64EC JIT module compatible with [this](https://github.com/bylaws/wine/tree/arm64ec) fork of wine, allowing for much reduced overhead when compared to running x64 wine under FEXLoader as native ARM64 windows system libraries (dxvk, msvcrt) etc can be used. Currently the dependency on kernel32/the system CRT prevents compatibility with windows or upstream wine, and some API function signatures differ, but I am currently looking into this.
A brief summary of ARM64EC can be found [here](https://learn.microsoft.com/en-us/windows/arm/arm64ec):
>Code built as Arm64EC is interoperable with x64 code running under emulation within the same process. The > Arm64EC code in the process runs with native performance, while any x64 code runs using emulation that comes built-in with …
> ARM64EC frontend

- .github/workflows/vixl_simulator.yml
We were only running SVE256 and SVE128 with AVX disabled.
Enable asm tests with SVE256, SVE128, and ASIMD, all running with AVX enabled to hit all the tests.
> github: Vixl simulator enable more asm tests

- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
Macros that don't end in a semicolon inherently break automatic code formatting. `clang-format` ended up putting several of these on the same line.
Luckily this one doesn't need to be a macro anyway.
> EmulatedFiles: Fix bad formatting

- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
We support leaf functions now, so add the few that were calling for it. We will be gaining support for the xsave ones relatively soon, so its good to have them supported.
Also deletes a couple of cdt/cqm things that aren't exposed and we won't be supporting.
> EmulatedFiles: Adds a few leaf CPUID flags

- Source/Common/ArgumentLoader.cpp
- Source/Common/ArgumentLoader.h
- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Tools/FEXBash/FEXBash.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/FEXServer/Main.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
Removes a global initializer and atexit registration
Ownership of this data has always been the frontend and the config system, we just used these static vectors as a side-channel.
> ArgumentLoader: Removes static fextl::vector usage

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/include/FEXCore/Core/CoreState.h
- Scripts/json_config_parse.py
- Source/Tools/CommonTools/HarnessHelpers.h
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- unittests/ASM/DAZTest.asm
- unittests/ASM/VEX/vldmxcsr.asm
- unittests/InstructionCountCI/FlagM/SecondaryGroup.json
- unittests/InstructionCountCI/SecondaryGroup.json
- unittests/InstructionCountCI/VEX_map_group.json
When AFP is supported then we can actually support DAZ. This might also
fix the audio corruption in Animal Well but I can't test it until Steam
is running on Oryon. Requires a bit of plumbing for MXCSR which we were
hacking around before but now we actually want to store the value.
Fixes https://github.com/FEX-Emu/FEX/issues/3856
> Arm64: Implements support for DAZ using AFP.FIZ 

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/IR/IR.json
stop prefixing the arguments when we generate allocate ops (in particular), this is more convenient and simpler. in exchange we need to prefix Op to avoid a collision on fcmpscalarinsert which has an argument named Op, but that's a local change at least.
came up when experimenting with new IR, but I think this is probably a win by itself.
> json_ir_generator: stop prefixing arguments

- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/AVX128/VEX_map2.json
- unittests/InstructionCountCI/AVX128/VEX_map2_AFP.json
- unittests/InstructionCountCI/AVX128/VEX_map2_SVE128.json
Now that I have AFP supporting hardware I felt better implementing this
since I can run unit tests.
Fixes https://github.com/FEX-Emu/FEX/issues/3793
> AVX128: Implement support for scalar FMA with AFP

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/JITCore.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
We were only ever hardcoding true for TBL2 and Flags now. Get rid of it.
> FEXCore: Removes CPUBackendFeatures

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
Instead of passing the TID back to the exit handler, just pass the whole thread object. This will allow some cleanups with the frontend thread tracking soon
NFC
> FEXCore: Refactor ExitHandler slightly

- FEXCore/include/FEXCore/Utils/Threads.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.h
Also removes the atexit handler installation
This now gets tracked by an object owned by FEXLoader (and shared with the pthreads interface)
> Threads: Setup the stack tracker to not need global initialization

- FEXCore/Scripts/config_generator.py
In the environment section this was causing the next environment variable line to be merged with the strenum options
Also makes it so strenum options doesn't have a spurious comma at the end of the list.
Before:
After:
> man: Fixes newline issue with strenum

- Source/Tools/LinuxEmulation/LinuxSyscalls/Arm64/SyscallsEnum.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Passthrough.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/SyscallsEnum.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/SyscallsEnum.h
Only mseal was added and can be a simple passthrough for us. Which is
nice.
> Syscalls: Updates for v6.10 

- unittests/ASM/X87/Rounding.asm
Fixes this warning from nasm:
```
/home/pmatos/dev/FEX/build/unittests/ASM/X87/Rounding.asm_TMP.asm:316: warning: attempt to initialize memory in a nobits section: ignored [-w+other]
```
Fixed it pre-merge in Rounding_F64.asm, RoundingNeg.asm and RoundingPos.asm but somehow forgot it here.
> Fix nasm warning in Rounding.asm

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/include/FEXCore/HLE/SyscallHandler.h
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
Also drop the legacy hangover ABI as it has no users.
> FEXCore: Add a generic spill/fill-all syscall ABI and use for Windows

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- unittests/ASM/FEX_bugs/SegmentAddressOverride.asm
The address-size flag only applies to the offset from the segment base, rather than the segment address itself.
> Don't apply the address-size flag to segment addresses

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/LookupCache.h
The prior approach using the L2 cache was flawed as it assumed L2 page entries had a 1-1 correspondence with actual pages. While the L2 cache could be extended to handle aliases with EC, this could lead to thrashing etc. The cost of a lookup in the actual EC code bitmap is cheap enough to perform every time considering the infrequency of calls to ARM64EC code when compare to X86 L2 hits.
> Directly use the EC code bitmap for determining page arch

- Source/Windows/ARM64EC/BTInterface.h
- Source/Windows/ARM64EC/Module.S
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/ARM64EC/libarm64ecfex.def
- Source/Windows/Common/CMakeLists.txt
- Source/Windows/Common/CPUFeatures.cpp
- Source/Windows/Common/Logging.cpp
- Source/Windows/Common/Logging.h
- Source/Windows/WOW64/Module.cpp
Ontop of #3913 
This updates the exposed ARM64EC API to match that of Windows and upstream wine, though it is currently usable on neither due to FEX's reliance on msvcrt.
> ARM64EC: Support the JIT API as is used by Windows

- CodeEmitter/CodeEmitter/Emitter.h
- CodeEmitter/CodeEmitter/VixlUtils.inl
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/HostFeatures.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- IsImmLogical already existed in our CodeEmitter. We just forgot to allow nullptr arguments and to use it.
- Adds an equivalent IsImmAddSub helper and uses it
This gets us closer to removing vixl's global initializers from FEXCore.
> CodeEmitter: Removes vestigial vixl usage

- Source/Windows/ARM64EC/Module.cpp
Better matches the windows behaviour here to avoid losing flags after a thread suspends  and resumes.
> ARM64EC: Improvements to exception flag handling

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
While ARM64EC code cannot use x28, it can be cleared by the kernel when performing syscalls etc so restore it from the TEB to be safe.
> Arm64Emitter: Reload STATE before SRA fill on ARM64EC

- Scripts/aarch64_fit_native.py
Different approach from #3579
Instead of completely dropping the deprecated path, support the new path and the old path using python try-except import exceptions.
This allows us to continue using old packages in CI, while supporting the future API once pkg_resources gets deprecated and removed. Best of both worlds.
> Scripts: Workaround deprecated parse_version

- FEXCore/Source/Utils/SpinWaitLock.h
This would cause the atomic load after the wfe to be dropped, effectively returning stale data.
> SpinWaitLock: Fixes missing newline in asm

- CMakeLists.txt
- FEXCore/CMakeLists.txt
- FEXCore/Source/CMakeLists.txt
- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/include/FEXCore/Core/Context.h
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Source/Common/CMakeLists.txt
- Source/Common/HostFeatures.cpp
- Source/Common/HostFeatures.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/TestHarnessRunner/CMakeLists.txt
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
This moves the CPU feature querying to the frontend. The primary purpose here is for the wow64 frontend to not require linux-isms for querying these features. This is required since non-Linux environments don't have the "CPUID" feature for reading EL1 MSRs in EL0.
Wiring up the remaining wow64 registry querying is left for a future exercise.
This also technically removes an xbyak requirement from FEXCore for when building the x86 Test harness runner, but that doesn't really matter for regular use cases.
> FEX: Moves HostFeatures querying to the frontend

- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Source/Common/HostFeatures.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
These are only missing if using the hostrunner and the CI machine doesn't support that particular feature. FEX otherwise always supports these feature flags so they don't need to exist as options.
Just check the feature bit directly in the HostRunner frontend for these bits.
> HostFeatures: Removes feature flags always supported by FEX

- Source/Windows/Common/InvalidationTracker.cpp
When given a NULL base address, Windows invalidation callbacks will ignore the given size and invalidate all code.
> InvalidationTracker: Better match Windows code invalidation behaviour

- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
The class constructor for ContextImpl::CPUID requires HostFeatures to be available at construction time. Pass the host features struct directly through during construction time instead, which cleans up the interface slightly and fixes that issue.
> FEXCore: Pass HostFeatures in to CreateNewContext directly

- unittests/ASM/full_vpblendw_imm.asm
This typo was causing undefined data to be used in the unittest, showed up in debug builds.
> unittests: Fixes vpblend unittest

- Source/Windows/ARM64EC/Module.S
- Source/Windows/ARM64EC/Module.cpp
Some programs will hook the NTDLL exports that FEX depends on, the regular ARM64EC call checker will detect such patches and invoke the JIT to run them, which leads to infinite recursion if those same exports are used during code compilation. Fix this by resolving all patchable FFSs to their native ARM implementations for all indirect calls performed by FEX, skipping any x86 patches.
> ARM64EC: Install a custom call checker to bypass NTDLL function patches

- FEXCore/include/FEXCore/Config/Config.h
Removes a simple runtime nullcheck in Config::Layer::Set. Since we never pass a nullptr to this.
> Config: Little assume non-null check

- Source/Common/HostFeatures.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/SyscallsEnum.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Syscalls.h
- We can have the SyscallFunctionDefinitions be the correct size out of the gate. Both tables are always 512 entries in size.
- In the RegisterSyscall_{32,64} handlers, just get the reference using operator[]. We always know we will be under the size of the array, add a an assert to check. Removes a bit of vector range checking overhead.
- Namespace 32-bit syscalls like 64-bit syscalls and include in the regular header like 64-bit. This was just an oversight
- Use std::fill for the syscall gap for the invalid syscall, just a minor cleanup.
No functional change.
> LinuxSyscalls: Some minor cleanups

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/ASM/FEX_bugs/repeat_on_incdec.asm
Somewhere there was an assumption made that INC and DEC supported the repeat prefix. This isn't actually the case, while the prefix can be encoded, it is a nop and should only expect to be used for padding.
Adds a unittest to ensure that behaviour is as expected.
> OpcodeDispatcher: Remove old bad assumption in INC/DEC

- FEXCore/Source/CMakeLists.txt
Some distributions (e.g. Fedora) use `lib64` instead of `lib` for libraries, this ensures we always install in the correct location instead of hardcoding `lib`.
> Install libraries in the correct location

- FEXCore/Source/CMakeLists.txt
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- Source/Common/CMakeLists.txt
- Source/Common/HostFeatures.cpp
- Source/Common/HostFeatures.h
- Source/Windows/Common/CMakeLists.txt
- Source/Windows/Common/CPUFeatures.cpp
This was mostly there, just needed to remove some extraneous headers and only insert vixl in to the library list if the options were enabled.
> FEXCore: Disable vixl linking if vixl disasm or simulator is disabled

- Source/Windows/ARM64EC/CMakeLists.txt
- Source/Windows/WOW64/CMakeLists.txt
Windows is jumping on the bandwagon too! this allows FEX to install itself directly into the system wine install:
` -DCMAKE_INSTALL_LIBDIR=$(LIBDIRA64)/wine/aarch64-windows`
> Windows: Install libraries to CMAKE_INSTALL_LIBDIR

- FEXCore/include/FEXCore/fextl/fmt.h
- Source/Windows/Common/CRT/IO.cpp
- ThunkLibs/Generator/gen.cpp
Required adding a new header to FEXCore/fextl/fmt.h
> External: Update fmt from 10.1.1 to 11.0.2

- Source/Tools/FEXLoader/CMakeLists.txt
not used. we'll probably rip the whole thing out at some point but for now, no reason to pollute user systems with this.
> FEXLoader: don't install FEXUpdateAOTIRCache

- FEXCore/Source/CMakeLists.txt
This hasn't ever mattered. Our API isn't even stable enough to really install the shared library.
> FEXCore: Stop installing static library

- FEXCore/Source/Interface/Config/Config.json.in
- ThunkLibs/HostLibs/CMakeLists.txt
Thunk host libraries were still hardcoded to lib/, use the same mechanism as #3964 for installing to the correct location.
> Library Forwarding: Follow up from #3964

- Source/Common/CMakeLists.txt
- Source/Common/HostFeatures.cpp
- Source/Common/HostFeatures.h
- Source/Windows/Common/CMakeLists.txt
- Source/Windows/Common/CPUFeatures.cpp
If we query the CPU flags ourselves then vixl is no longer a
compile-time or runtime dependency unless the vixl disassembler or
simulator is built.
A bit spicy from all the feature bits we need to load up.
> HostFeatures: Removes vixl usage 

- Source/Windows/Common/Priv.h
- Source/Windows/Common/WinAPI/IO.cpp
Used when the .fex-emu config dir doesn't exist. Also fixes up CreateFile to not leak memory.
> Windows: Implement CreateDirectoryW CRT function

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
Fixes a bug that is getting introduced in to #3955 when it rearranged register allocation.
> Arm64: Allow directly correlating an ARM register back to an x86 register

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
- FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
PR #3980 is adding a feature to merge loadstores in to paired loadstores, but it was using the incorrect atomic check to determine if it can safely merge them or not. It was using the GPR atomic check instead of the vector atomic check. While this would improve performance on Apple Silicon with its hardware TSO implementation, it would have had zero impact on Cortex and Oryon.
Instead split out the three config options to live as a boolean check in the ContextImpl similar to how we disable "AtomicTSOEmulation". Removing the various configs in the JIT and CPUID so that it queries from the same context. This makes it clearer that if you are wanting the current active configuration for memcpy, vector, or general atomic TSO emulation, you should query one of those three getters.
This also …
> FEXCore: Splits up atomic enablement checks

- FEXCore/Source/Utils/SpinWaitLock.h
With recent bug fixes, WFE now can sleep for roughly as long as the programmed architecture timer of 100 microseconds. Still nowhere near as close as what x86 CPUs can get with waitx and waitpkg, because those don't get spuriously woken up by an architecture timer.
100 microseconds is a significantly improvement over 52ns although.
> SpinWaitLock: Update comment about WFE spurious wakeups

- Scripts/UpdateInstructionCountJson.py
- unittests/InstructionCountCI/FEXOpt/AddressingLimitations.json
- unittests/InstructionCountCI/FEXOpt/AddressingLimitations_32Bit.json
- unittests/InstructionCountCI/FEXOpt/MultiInst.json
- unittests/InstructionCountCI/FEXOpt/MultiInst_AFP.json
- unittests/InstructionCountCI/FEXOpt/libnss.json
- unittests/InstructionCountCI/FlagM/FlagOpts.json
- unittests/InstructionCountCI/FlagM/HotBlocks.json
- unittests/InstructionCountCI/FlagM/HotBlocks_32Bit.json
- unittests/InstructionCountCI/FlagM/HotBlocks_AFP.json
- unittests/InstructionCountCI/FlagM/x87-HalfLife.json
- unittests/InstructionCountCI/FlagM/x87-Oblivion.json
- unittests/InstructionCountCI/FlagM/x87-Psychonauts.json
- unittests/InstructionCountCI/FlagM/x87.json
- unittests/InstructionCountCI/FlagM/x87_f64.json
- unittests/InstructionCountCI/x87.json
- unittests/InstructionCountCI/x87_f64.json
useful for checking blow up ratios. I keep calculating this by hand so let's
just add it to the json
> InstCountCI: include x86 instruction count 

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
- unittests/InstructionCountCI/FlagM/HotBlocks.json
When flags are not needed, we can translate to an equivalent arm64 idiom.
When flags *are* needed, we can still rearrange a bit to save a move, though that's less interesting.
Since we don't know whether we need flags in the dispatcher, we add a specialized pair of IR ops so we can optimize things appropriately.
> Optimize `adc x, 0`

- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
- unittests/ASM/FEX_bugs/UnalignedLoadStoreSIGBUS.asm
When https://github.com/FEX-Emu/FEX/pull/3899 refactored some of this code, it had split an if-else chain
in to two independent if-else chains. Turns out there was a minor
dependency between them. Add back the few checks necessary to ensure
that FEAT_LRCPC falls through before hitting the FEAT_LSE checks.
This is necessary because their instructions share an encoding so the
masks between the two instruction classes overlap slightly.
> Arm64: Fixes SIGBUS handler for FEAT_LRCPC

- Source/Windows/ARM64EC/Module.cpp
There is a common arch bit that is included in each individual mask, explicitly test for equality against the whole mask to avoid just testing for this.
> ARM64EC: Fix ContextFlag member tests

- Source/Windows/Common/CRT/IO.cpp
- Source/Windows/Common/WinAPI/IO.cpp
The current FEX implementation was mostly tested with wine so a few things that don't actually apply to windows snuck in.
> Windows: Fix some file operations on actual Windows

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- unittests/FEXLinuxTests/tests/signal/sigtest_defer.cpp
Fairly trivial because we already supported deferring these signals. We
had just failed the final step of blocking the signal if we can't block
the signal (like with SIGSEGV, SIGBUS, etc).
Once the guest unblocks the signal mask with sigprocmask, the signal
will fire again.
Apparently older glibc relied on this behaviour for signal raising which
this fixes.
> SignalDelegator: Make sure to defer a signal if the guest signal mask desires

- Source/Windows/ARM64EC/Module.S
New wine tests suggest x0 holding the pointer to the correct context is just a coincidence so avoid relying on it.
> ARM64EC: Always use the CPU area context for BeginSimulation

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Required by newer insider preview versions, I noticed many crashes with this exception number and QueryPeformanceCounter in the backtrace, testing with XTA found it to not be passed through and instead write the host CNTVCT (unscaled) into RAX. No other registers seem to be affected.
> OpcodeDispatcher: Allow x86 code to read CNTVCT on ARM64EC

- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Source/Common/HostFeatures.cpp
- Source/Common/HostFeatures.h
- Source/Windows/Common/CPUFeatures.cpp
The MIDR querying is inherently OS specific and needs a bit of special casing. Instead let the frontend inform FEXCore how many CPU cores there are and their MIDRs instead.
This lets us keep the Linux specific code in the frontend.
> HostFeatures: Moves MIDR querying to the frontend

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
To ensure that it actually dies after logging.
> SignalDelegator: Changes AFmt to ERROR_AND_DIE_FMT

- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Signals.cpp
In rt_sigqueueinfo and rt_tgsigqueueinfo we were failiny to pass along the provided siginfo_t information to the syscall.
Fix that
> x32/Signals: Fixes bug in the sigqueue syscalls

- FEXCore/Source/Interface/IR/Passes/DeadStoreElimination.cpp
lets us kill some AF calculations with multiblock.
> DeadStoreElimination: handle PF/AF invalidate

- FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
Our JIT will happily consume incorrectly formed 256-bit vector operations in a lot of cases when the host CPU doesn't support 256-bit SVE. This is what caused the bug in #4006. For every vector operation that can consume a 256-bit size, add an assert that always checks if 256-bit SVE is supported in those cases.
This will ensure that #4006 doesn't happen again.
~~Needs #4006 and #4008 merged first and then this rebased before this can pass CI.~~
> Arm64: Ensure 256-bit operations always assert without 256-bit SVE

- Source/Tools/FEXGDBReader/CMakeLists.txt
Similarly to #3964 install this in the correct location instead of hardcoding.
> Install GDBSymbol integration in the correct location

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/Frontend.h
A source of overhead with multiblock is hitting instructions through a conditional branch that can never be executed. Usually AVX512 instructions in glibc. This causes us to emit partial blocks for a ton of targets that will never get executed.
Instead, when we have multiblock enabled, if a block hits an instruction encoding we don't support, then remove all the decoded instructions from the block and early terminate it if it isn't the entry block. This resolves the issue of emitting a bunch of IR and code for blocks never executed.
If the block of code has an invalid instruction in the entry block for decoding then it'll still emit code up to the invalid instruction and raise a SIGILL. This has the potential for generating some additional blocks of code if a game is abusing SIGILL, but …
> Frontend: short-circuit code generation on invalid instructions with multiblock

- CMakeToolchains/AArch64.cmake
This is useful for some people.
This doesn't allow building thunks due to the cmake limitation about tools binaries also getting cross compiled, we need to switch to meson if we want that, since they recently started fixing this https://github.com/mesonbuild/meson/pull/12022
But that's an okay limitation for now.
> CMake: Adds an AArch64 cross-compile toolchain file

- FEXCore/Source/Interface/Core/CPUID.cpp
The Ultra-class SoCs are two Max-class SoCs connected via Apple's fabric, and thus use the same core revisions as the Max-class SoCs for both big and LITTLE cores.
> CPUID: add missing Apple core part numbers

- FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
This variable can't be constexpr initialized since it requires linker fix-ups, which changes it in to a global static initializer instead.
While this benign as it doesn't allocate any memory, just move it next to its single use. Removes the static initializer that was there for no reason.
> Thunks: Removes global static initializer

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/X86HelperGen.cpp
- FEXCore/Source/Interface/Core/X86HelperGen.h
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/VDSO_Emulation.cpp
- Source/Tools/LinuxEmulation/VDSO_Emulation.h
These are a Linux construct and should live here. Removes a weird passthrough API from FEXCore and keeps it in the frontend instead. This isn't even typically allocated in a real setup, as it's only a fallback for if VDSO isn't loaded.
The CallbackReturn function stays in FEXCore because it would have caused an API in the other direction instead.
> FEX: Moves sigreturn symbols to frontend

- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Time.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Timer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Thread.cpp
Getting closer to full coverage, only a handful of missing syscalls now.
> More EFAULT handlers

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
- FEXCore/Source/Utils/SpinWaitLock.h
- Source/Tools/FEXConfig/Main.cpp
- Source/Tools/FEXGetConfig/Main.cpp
For atomics that cross the 16-byte or 64-byte granularity, we need to
lock a mutex to ensure strict emulation of split-locks.
I took another look at these when I found out that Zen3 actually
implements split-locks. Not sure which architecture actually added
support for from them, but I wanted to ensure we have the ability to
handle this.
One thing that we can't handle in user-space is cross-process
split-locks through shared memory. This requires a kernel SIGBUS handler
to ensure a crashing/SIGKILL'd process doesn't lock all FEX processes in
the system.
This fixes a little split-lock abusing test that I have locally. It's a
bit flakey so it isn't viable to run in CI. Considering it is explicitly
testing a race problem.
> Arm64: Implement support for strict in-process split-locks

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Signals.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/FS.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Signals.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Thread.cpp
Two primary things here:
- Remove the static `GlobalDelegator`
- Move the thread_local SignalDelegator::ThreadState information directly in to ThreadStateObject
Having the ThreadStateObject and the SignalDelegator information disjoint was confusing but was required when we didn't have any object in the frontend that could have its own independent data. Since we fixed this with the `ThreadStateObject` type we can now move this over.
The `GlobalDelegator` object is now instead stored in `ThreadStateObject` instead.
Instead of using a thread_local variable, we now just consume 8-bytes of the signal alt-stack since the kernel gives us that information about where it lives. This then converts all the thread_local usage to use either the passed in CPU state if it exists, or fetching it from the …
> SignalDelegator: Refactor how thread local data is stored

- FEXCore/Scripts/config_generator.py
- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Tools/FEXConfig/Main.cpp
- Source/Tools/FEXGetConfig/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXQonfig/Main.cpp
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/FEXServer/Main.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
A couple things to note here.
This expects multiple environment variables to be set
- `FEX_PORTABLE=1`
- `FEX_THUNKHOSTLIBS=<Local install path for thunks>`
- `FEX_THUNKHOSTLIBS32=<Local install path for thunks>`
- `FEX_THUNKGUESTLIBS=<Local install path for thunks>`
- `FEX_THUNKGUESTLIBS32=<Local install path for thunks>`
Some optional environment variables that can be set
- FEX_APP_CONFIG_LOCATION
- With FEX_PORTABLE set,  this will default to a path at `<FEXInterpreter>/fex-emu/`
- This overrides the default $HOME behaviour
- This path is used by the `$HOME/.fex-emu/Config.json` and `$HOME/.fex-emu/AppConfig/<Files>.json`
- FEX_APP_DATA_LOCATION
- With FEX_PORTABLE set,  this will default to a path at `<FEXInterpreter>/fex-emu/`
- This overrides the default $HOME behaviour
- This path …
> FEXInterpreter: Support portable installs

- Source/Tools/FEXQonfig/main.qml
This was missed in the initial FEXQConfig implementation since it was implemented at the same time.
> FEXQConfig: Add strict split-lock option

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Interface/Core/CPUID.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/FlagM/SecondaryModRM.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/SecondaryModRM.json
When I implemented TSC scaling originally, I chose a scale factor of 128 because it basically covered the range of devices we cared about without going too high. I also only tested devices that had a TSC scale factor from 19.2Mhz to 34Mhz. Turns out there is hardware that also has a 48Mhz cycle counter, which cause them to effectively have a 6.1Ghz cycle counter, which is kind of absurd.
Instead of a fixed scale, just calculate the amount of scaling we need to get >= the minimum threshold of 1Ghz. This will change the shift from 7 to 5 or 6 for the faster cycle counter devices.
Of course if someone wants to know the scale factor they can still use cpuid function 15h to know it.
Fixes #4026
> FEXCore: Dynamically scale TSC

- Source/Tools/FEXQonfig/Main.cpp
- Source/Tools/FEXQonfig/main.qml
* FEXConfig was displaying an error when saving to a new file even though the operation succeeded.
* `~/.fex-emu/Config.json` (as returned by `FEXCore::Config::GetConfigFileLocation()`) is automatically set as the config filename on first load now
* Various minor UI quirks have been fixed
> FEXQonfig: Fix minor saving/loading quirks

- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
despite conventional wisdom, the robin map is slower than emitting extra nodes.
without multiblock, shaves around 2% off node. with multiblock, a bit less than 1% but still a win.
> ConstProp: stop pooling inline constants

- FEXCore/Source/Common/JitSymbols.cpp
- FEXCore/Source/Common/JitSymbols.h
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
This definition doesn't need to be exposed in the public API.
> FEXCore: Move `JITSymbolBuffer` to internal header

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/include/FEXCore/Core/Context.h
This definition doesn't need to be exposed in the public API.
Stopped needing to be public once we removed our IR CI thing.
> FEXCore: Move `CustomIRResult` to internal header

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/FD.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/FD.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/FD.cpp
The pointer is allowed to be null or garbage if the number of nfds passed in is zero.
Unify the x86 and x86-64 implementations to ensure consistency.
Fixes Warhammer 40k: Relics of War
> LinuxSyscalls: With poll syscall, ensure fds is writable only if nfds is not zero

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
This works fine on real Windows and is relied on by wine as SystemCall is set to 1 in KUSER_SHARED_DATA, which causes the ntdll thunks to use it over `syscall`
> OpcodeDispatcher: Do not forbid INT 2E syscalls on 64-bit Windows

- FEXCore/Source/Interface/IR/AOTIR.h
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
This definition doesn't need to be exposed in the public API.
> AOTIR: Move debugdata structure to internal header

- Source/Windows/ARM64EC/Module.S
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/include/winternl.h
The previous approach assumed that ntdll wouldn't have been patched before FEX was loaded, but that isn't necessarily the case thanks to CEF. This takes the same approach used by xtajit which wine recently gained support for wine. The overhead to this isn't ideal but most syscalls aren't directly done through x86 code anyway and in the future FEX could forward unpatched thunks to their ARM variants at JIT time.
Tested with steam on windows (sandbox disabled), not entirely sure I like how KiUserExceptionDispatcher is called but this way seems the simplest
> ARM64EC: Switch to exception-based native syscall dispatch

- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
I see no reason not to. Simpler code and it's slightly faster on Firestorm.
> JIT: always use 64-bit moves for SRA

- FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
This variable is only used in a log message now, so move it there.
> Arm64: Fix warning

- CodeEmitter/CodeEmitter/ASIMDOps.inl
- FEXCore/Scripts/config_generator.py
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/F80Fallbacks.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Utils/Allocator.cpp
- Source/Tools/FEXLoader/ELFCodeLoader.h
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/FEXRootFSFetcher/XXFileHash.cpp
- Source/Tools/FEXServer/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Seccomp/BPFEmitter.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Seccomp/BPFEmitter.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Ioctl/drm.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Semaphore.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Time.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Types.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/FD.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Types.h
- Source/Tools/pidof/pidof.cpp
- unittests/ASM/FEX_bugs/PSRLDQBuf.asm
- unittests/InstructionCountCI/AVX128/VEX_map_group.json
Mostly NFC, but it actually did find a few bugs, which is kind of unexpected.
Functional changes:
- (f51832ca6bae65c1ae692a0c0db81541106aa706) Fixes a bug in VPSRLDQ where larger than 16-byte shifts weren't zeroing the upper 16-bytes of a YMM register.
- (c559445b62a8f738fb096ed15da1c1ee5405e79c, 2d91c5441e4ef99d691fe8f1d022f241da777ef0, 9141322666eb7381b93ab3bf4605a288ad61900c, c4a0fb66092a2df82114bff9a001473777aabf99) IoctlEmulation: Fixes for a few structs that were copying the wrong direction for Host->Guest and missing a few member copies (Unlikely to affect anything as it was legacy interfaces)
- (98a91d242d77b555e78ce31263dbfa8b58295641) Fix resource leak on XXHash error
- (f6a8e595df2f82eb1dc454228beb2a1f632d4545) Add a TODO for futimesat because the syscall doesn't exist on ARM64 …
> Bunch of little things reported by coverity

- CMakeLists.txt
Like how FEXCore disabled vixl linking, make sure we aren't accidentally compiling and including it when vixl stuff is disabled. Noticed this in the build logs.
> CMake: Disable vixl compiling if not enabled

- Source/Tools/FEXRootFSFetcher/XXFileHash.cpp
Since `HadError` is a lambda that handles FD closing this was a double FD close. Just move the xxhash state freeing in there as well and remove the FD and hash freeing. Fixes the double free.
> FEXRootFSFetcher/XXHash: Fix double fd close

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
- FEXCore/Source/Interface/Core/ObjectCache/JobHandling.cpp
- FEXCore/Source/Interface/Core/ObjectCache/NamedRegionObjectHandler.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
This is one of the most expensive headers in FEX, averaging 1.2 seconds of compile time per include.
We include this header 31 times around the project. Remove the five instances where it is unused to help this issue. Next step would be to make the header lighter if possible.
> FEXCore: Remove Context header include when unneeded

- FEXCore/Source/Interface/Core/LookupCache.cpp
- FEXCore/include/FEXCore/HLE/SyscallHandler.h
- FEXCore/include/FEXCore/Utils/AllocatorHooks.h
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/Common/OvercommitTracker.h
- Source/Windows/WOW64/Module.cpp
The lookup cache requires >100mb of address space per thread, which broke anything particularly complicated on native windows due to the lack of overcommit. Fix this faulting in pages in the exception handler
> Support for emulated overcommit on Windows 

- Source/Windows/ARM64EC/Module.S
- Source/Windows/ARM64EC/Module.cpp
CEF on Windows patches these before FEX is even loaded, so this needs to be setup as early as possible using some direct syscalls which skip any such patches.
> ARM64EC: Patch the call checker before calling any syscall exports

- Source/Tools/FEXServer/PipeScanner.cpp
This was causing problems in a typical use case of piping stdout/stderr to another application. So if FEXInterpreter was started, with stdout piped to another application, and FEXServer wasn't running so a new instance needed to be started. FEXServer would write a null to every pipe then close it. This includes the stdout that is being piped to the new application!
This writing was legacy behaviour before FEX was properly listening to POLLHUP and is no longer necessary. Just remove the writing completely to fix this issue.
Easiest test case was just `./Bin/FEXInterpreter /usr/bin/ls / | xxd | head -n 3`
Returned:
```
$ ./Bin/FEXInterpreter `which ls` / | xxd | head -n 3
00000000: 0000 0000 6269 6e0a 6269 6e2e 7573 722d  ....bin.bin.usr-
00000010: 6973 2d6d 6572 6765 640a 626f 6f74 0a64 …
```
> FEXServer/PipeScanner: Stop writing null to incoming pipes

- Source/Tools/FEXRootFSFetcher/Main.cpp
If packaged improperly or if someone has just did a source install then they may not have zenity. Fallback to TTY path if zenity isn't installed.
> FEXRootFSFetcher: Fallback to TTY if zenity isn't installed

- unittests/32Bit_ASM/CMakeLists.txt
- unittests/ASM/CMakeLists.txt
- unittests/FEXLinuxTests/CMakeLists.txt
- unittests/POSIX/CMakeLists.txt
- unittests/ThunkFunctionalTests/CMakeLists.txt
- unittests/gcc-target-tests-32/CMakeLists.txt
- unittests/gcc-target-tests-64/CMakeLists.txt
- unittests/gvisor-tests/CMakeLists.txt
Turns out our unittests have been passing an incorrect argument for years.
cherry-picked from #4070
> unittests: Fixes incorrect argument

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/BaseTables.h
- FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
Only doing the single table for review purposes. Once reviewed I will hammer out the remaining tables.
Similar to #3320, most of the OpcodeDispatcher tables can be consteval and made to be a compile time constant. This just requires shuffling the code slightly. The idea is to get almost all of the table setup out of the `InstallOpcodeHandlers` function and instead only install the handlers that change based on 32-bit or 64-bit, just like the x86 tables we also did.
> FEXCore: Convert Base tables over to constexpr

- FEXCore/Source/Interface/Core/CPUID.cpp
Previously reported as some old CPU without AVX and SSE4 and other things.
Start advertising as something more modern that actually shipped with AVX2 and other features. Should help some modern libraries that do bad family and model checks rather that CPUID features checks.
Also removes the silly `(ES)` tag from CPU-Z.
Also moves generation in to a constexpr function that can actually range check these 4-bit and 8-bit values.
> CPUID: Update to something a little more modern

- Source/Common/Config.cpp
EnvLoader::Load was generating strings on the stack and then copying them to the FEXCore::Config state. FEXCore::Config::Set supports string_views directly which will emplace in to the map directly.
This improves this functions stack usage from ~4464 bytes to ~288 bytes.
I believe this was missed when we were converting from std::string to fextl::string.
> Config: Fixes stack usage in EnvLoader

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
We were creating a copy of the FEXCore::Core::CPUState object when we didn't need to. We can pass the host thread's CPUState frame through to the creation handlers since it's read-only (so modify it to be const).
We then just move the RAX and RSP setting to /after/ the CreateThread handling instead of before.
This reduces stack usage from ~1392 bytes to ~80 bytes.
> Linux: Optimize CreateNewThread and HandleNewClone stack usage

- FEXCore/Source/Interface/Config/Config.cpp
- FEXCore/include/FEXCore/Config/Config.h
- Source/Common/Config.cpp
- Source/Tools/FEXConfig/Main.cpp
- Source/Tools/FEXConfig/Main.h
Global rootfs doesn't support a named rootfs (only local supports that).
So when it is a global rootfs option just give the full path to the
config path.
Just needs some special handling to ensure the full path is retained for
global paths.
A reimplementation of https://github.com/FEX-Emu/FEX/pull/4067 that doesn't hardcode paths and routes the
global data path through FEXCore.
> FEXConfig: Add the ability to watch and configure global rootfs

- CMakeLists.txt
- Source/Tools/FEXLoader/CMakeLists.txt
With the new systemd support, we had forgotten to wrap this check in an arm64 check. I had done an install and broke my x86 machine.
Add the check back so we stop breaking x86 machines...again. Took me only about three hours to find the issue this time.
> Stop installing binfmt_misc on x86

- FEXCore/Source/Common/SoftFloat.h
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/F80Fallbacks.h
- unittests/ASM/X87/FScale-Zero.asm
- unittests/ASM/X87_F64/FScale-Zero_F64.asm
Added tests will fail without the current patch.
> Fix FScale'ing zero that should return zero

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/SignalDelegator.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator/GuestFramesManagement.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
Since the frontend has changed to informing the backend if AVX is supported, there is no reason to feed that configuration back in to SignalDelegator from the backend.
Instead inform the SignalDelegator directly in the frontend instead of this now weird round-about path.
> SignalDelegator: Let the frontend inform AVX support

- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/VDSO_Emulation.cpp
- Source/Tools/LinuxEmulation/VDSO_Emulation.h
- ThunkLibs/libVDSO/libVDSO_Guest.cpp
- ThunkLibs/libVDSO/libVDSO_Guest.lds
- ThunkLibs/libVDSO/libVDSO_interface.cpp
This is an interesting vdso implementation because it only exists in
x86-64 with kernel v6.11. For Arm64 the implementation is likely to land
in a couple kernel versions from now.
Some differences with vdso_getrandom versus the regular getrandom
syscall
- Has two additional arguments, opaque_state and opaque_len
- Expects the userspace to mmap/munmap this opaque state structure
- Lets userspace query information about this structure upfront
- If the opaque data structure isn't provided then it falls back to
regular SYS_getrandom
With the "glibc" implementation, we can tell the interface to allocate a
single page that gets unused (otherwise glibc ends up not using the
interface), and fallback to the regular SYS_getrandom.
In the case of the vdso interface, currently the arguments just get …
> VDSO: Implements v6.11 vdso getrandom

- Source/Windows/ARM64EC/CMakeLists.txt
- Source/Windows/Common/CMakeLists.txt
- Source/Windows/Common/CRT/IO.cpp
- Source/Windows/Common/CRT/String.cpp
- Source/Windows/Common/LoadConfig.S
MSVCRT is deprecated and the reasons FEX used it no longer apply, so support UCRT and UCRT only.
Draft as not tested particularly well and this needs new CI binaries 
cc: @AndreRH
> Windows: Switch supported MinGW CRT to UCRT

- ThunkLibs/libvulkan/libvulkan_interface.cpp
Between this version and our previous version v1.3.278 this adds a few
extensions.
- VK_EXT_device_generated_commands
- VK_EXT_depth_clamp_control
- VK_AMD_anti_lag
- VK_KHR_pipeline_binary
These extensions are almost immediately getting picked up by mesa and
the D3D layers, so we want to support them as soon as possible.
Once again updated as described in https://github.com/FEX-Emu/FEX/pull/2076. This is starting to take more
time as more features and extensions get added to Vulkan. We probably
want to update the `DefinitionExtract.py` script at some point to
contain all the tertiary data in some json so everything gets generated
automatically. Not doing that today but something to think about.
Fixes https://github.com/FEX-Emu/FEX/issues/4083
> Thunks/Vulkan: Updates thunks to v1.3.296

- unittests/32Bit_ASM/CMakeLists.txt
- unittests/ASM/CMakeLists.txt
> We had a bug in our arguments getting passed to unittests for years (https://github.com/FEX-Emu/FEX/pull/4071) and it was undiscovered. Due to a quirk with cpp-optparse where any unsupported arguments were gathered and passed to the guest application. This didn't necessarily break anything in our unittests, just made them run silently, and for all the harness things the additional argument was ignored anyway.
cherry-picked from #4070 with the review comments resolved.
Only the ASM and 32-bit ASM tests were missing this.
Breaking it out in to an independent PR since it can be freestanding.
> unittests: Be more strict with -- separator

- Source/Windows/ARM64EC/Module.cpp
Takes advantage of the consistent alphabetical syscall ordering that wine follows. This finally allows the CEF sandbox to work with arm64ec FEX under wine.
> ARM64EC: Dynamically determine syscall numbers under wine.

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/ASM/FEX_bugs/tls_vector_element.asm
These had completely forgotten to load segment prefixes on the element
loadstore operations. This had caused a crash on the Linux version of
"Halls of Torment" (steamid 2218750).
This game has TLS vector data which it was loading with a movhps and hit
this path.
> OpcodeDispatcher: Fixes segment prefixing on vector element loadstores 

- Source/Tools/LinuxEmulation/LinuxSyscalls/Arm64/SyscallsEnum.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/NotImplemented.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/SyscallsEnum.h
Only thing added was uretprobe on x86-64. We can't support this so just return ENOSYS.
> LinuxEmulation: Update syscalls for v6.11

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
Investigated the uapi differences and nothing terrifying leapt out that we haven't already implemented.
> LinuxSyscalls: Update max reported kernel version to 6.11

- Source/Tools/FEXLoader/FEXLoader.cpp
The size of the input_event struct differs between 32 bits applications and 64 bits applications. To deal with this, the kernel implements a compat variant for the input syscalls, but it's only enabled for 32 bit processes.
In libkrunfw we're introducing a prctl that enables a 64 bit process to request the kernel to enable the compat variant for the input syscalls. This commit makes use of that interface for enabling/disabling the compat input variant as required.
The visible effect is that input devices such as gamepads work properly on emulated 32 bit applications.
> FEXCore: adds support for compat input prctl

- Source/Tools/TestHarnessRunner/TestHarnessRunner/HostRunner.cpp
When writing `FEX_bugs/tls_vector_element.asm` I had to switch to using
GS segment instead of FS segment because the unittests didn't correctly
restore FS after running. This is because GS is unused on Linux
applications, but FS would become broken and break glibc cleanup on
shutdown.
Now that xbyak has been updated to v7.09, it now supports
{rd,wr}{fs,gs}base which allows us to save and restore the segments
correctly. This lets us drop in TLS tests in to unittests more easily
now.
Ensured this works by modifying the test temporarily to use fs instead
of gs again, seeing it crash before HostRunner changes, and work after
HostRunner changes.
Fixes https://github.com/FEX-Emu/FEX/issues/4104
> TestHarnessRunner: Fixes FS/GS usage in tests

- unittests/ASM/FEX_bugs/fnsave_fnrstor_size.asm
The instruction definition only allows these instructions to load/store 94 or 108 bytes, not affecting any bytes afterwards. This is a bit awkward because 80-bit x87 registers are stored at the end.
FEX has an optimization today where it uses overlapping loads and stores for the first seven x87 registers, and a split loadstore for the final register. This ensures that we get the correct data while reducing the number of loadstores.
We didn't have a unittest in place to ensure we only ever write the correct amount of data, so changes like in #4107 which look correct from an initial glance, would have resulted in broken behaviour.
This unittest ensures both that the instructions don't try to access beyond the end of the page, and also ensures that they don't overwrite subsequent data. …
> unittests/ASM: Ensures FNSAVE and FRSTOR only store as much data as required

- FEXCore/Source/Interface/Core/Core.cpp
- Source/Tools/LinuxEmulation/VDSO_Emulation.cpp
Just requires a thread pointer check to be fixed in FEXCore. This doesn't need unique pages to exist for the file mapping and can be shared since it's readonly mapped.
> VDSOEmulation: Support loading VDSO thunk as shared

- unittests/FEXLinuxTests/Known_Failures_Host
Already properly skipped in the right place.
File added accidentally.
> Remove file since FXAM_Simple is not a Linux test

- FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
- unittests/InstructionCountCI/Primary.json
According to
https://github.com/rust-lang/rust/commit/c064b6560b7ce0adeb9bbf5d7dcf12b1acb0c807
turns out that the arm yield instruction is effectively a nop on all
reasonably new CPUs.
Instead switch over to wfe because it matches x86 `PAUSE` semantics more
closely.
> FEXCore: Change yield implementation to use wfe 

- FEXHeaderUtils/FEXHeaderUtils/StringArgumentParser.h
- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- unittests/APITests/ArgumentParser.cpp
- unittests/APITests/CMakeLists.txt
This was brought up by #3831 but I finally got the courage to look at the hard problem.
Although I'm only tackling half of the problem with this PR, which is that FEXLoader needs to strip the rootfs path from the executed path if it begins with the rootfs, plus some changes to the surrounding code.
The primary concern here is that when an application has been executed under FEX, specifically through binfmt_misc, then FEX needs to prepend the full rootfs path otherwise Linux can't find the program. Additionally execveat with an FD will resolve a full path to the rootfs.
So past FEX's initial setup, we need to strip off the rootfs path to provide an "absolute" path that is visible to the guest application later. Which is kind of funny since we have a `RootFSRedirect` function which did the …
> FEXLoader: Fixes newer wine versions and Fedora

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Info.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Passthrough.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- unittests/FEXLinuxTests/tests/CMakeLists.txt
- unittests/FEXLinuxTests/tests/syscalls/personality.cpp
Comes from #1119 
Previously we were just passing the personality to the host kernel, which worked for most cases but not all.
- Adds per-thread tracking of personality
- Handles PER_LINUX32 which AArch64-only hardware would have returned error on
- Supports the uname changes that PER_LINUX32 and UNAME26 changes
Flags still not supported after this PR:
- ADDR_COMPAT_LAYOUT
- READ_IMPLIES_EXEC
- ADDR_LIMIT_3GB
Adds a unit test to ensure personality is set and returned as expected.
> LinuxEmulation: Personality handling

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- unittests/InstructionCountCI/AVX128/VEX_map1.json
MMX, SSE, and AVX were all using different implementations. Unify the three of them.
This is a nop for the MMX and SSE implementation, but this does some minor optimization for the AVX implementation since the SSE path was slightly more optimal.
Fixes #4123
> OpcodeDispatcher: Unify PSHUF{L,H}W implementations

- Readme.md
- Scripts/InstallFEX.py
This adds that release since it is built in the PPA:
https://launchpad.net/~fex-emu/+archive/ubuntu/fex?field.series_filter=oracular
It may be recommended to remove non-LTS releases or at least ones that are no longer supported by Ubuntu perhaps.
> add Ubuntu 24.10 and remove unsupported releases

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
No functional change.
This is a continued stride towards using OpSize enums instead of constant numbers to reduce confusion and misunderstandings.
It gets very confusing at times when an argument to an IR operation is a size versus an index, or scale or another constant. We had already cleaned up a decent amount of this early this year, late last year but this hits all the OpcodeDispatcher files in the folder. Once this is merged we can start enforcing OpSize passing to IR operations without implicit conversions. Likely will require a bit more mopping up on the edges, but should make it easier.
Just a little cleanup while I'm distracted.
> Fix IR operation usage to use OpSize when possible

- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Passthrough.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/FD.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/FD.cpp
Chromium/CEF has code that iterates through all open FDs and bails if any are directories (apparently a sandboxing sanity check). To avoid this check, we need to hide the RootFS FD. This requires hooking all the getdents variants to skip that entry.
To keep the runtime cost low, we keep track of the inode of /proc/self/fd/<rootfs fd> (note: not the RootFS inode, the inode of the magic symlink in /proc), and first do a quick check on that. If it matches, then we stat the dirfd we are reading and check against the procfs device, to complete the inode equality check.
As an extra benefit, this also fixes code that tries to iterate and close all/extra FDs and ends up closing the RootFS fd.
> FileManagement: Hide the FEX RootFS fd from /proc/self/fd

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Trivial but quite a few places pass in a raw integer
NFC
> OpcodeDispatcher: Convert {Load,Store}GPRRegister to OpSize

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
NFC
Plus the tertiary bits that require changing to support it.
> OpcodeDispatcher: Convert flags helpers over to OpSize

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp
NFC
Probably more of these around, just tracking the few I found.
> OpcodeDispatcher: Various missed OpSize implicit cast fixes

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/Core/JIT/AtomicOps.cpp
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
- FEXCore/Source/Interface/IR/IREmitter.h
NFC
Finally converts the IR operations themselves to store the OpSize for the IR operation size and element sizes.
This also finally, FINALLY, converts that remaining `_Constant` helper to stop using a size field that is specified in bits rather than bytes like all the other IR op handlers. That thing was so confusing and now it's gone.
> IR: Converts base IR operations to store OpSize sizes

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/InterpreterFallbacks.cpp
- FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/ConversionOps.cpp
- FEXCore/Source/Interface/Core/JIT/EncryptionOps.cpp
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
- FEXCore/Source/Interface/IR/IREmitter.h
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
- FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp
NFC
Do the final mopping up to convert the OpSize enum to an enum class!
> IR: Convert OpSize over to enum class

- Source/Common/Config.cpp
This allows FEX to be used in situations where `HOME` is set to something invalid, e.g. inside Nix builds.
> Check if a candidate home directory exists before using it

- Source/Tools/FEXLoader/ELFCodeLoader.h
This ensures that __libc_stack_end is aligned, the same way it is on native.
> FEXLoader: Align stack base

- FEXCore/Scripts/json_ir_generator.py
This was causing unused variable warning due
to the variable only being used in an assertion.
> Avoid warning on assertionless builds

- unittests/32Bit_ASM/Disabled_Tests_Simulator
- unittests/ASM/Disabled_Tests_Simulator
It seems a form of `mrs` is unsupported as well as the hint `wfe` used for `pause`.
Remove skipping Rounding(Neg|Pos).asm as they are passing.
> Add some more tests as unsupported by vixl

- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.h
Apparently Chromium/CEF can chroot or otherwise sandbox the filesystem away before forking and checking for directory FDs, making /proc inaccessible, which means we can't stat it for our inode check, breaking the hiding.
So, double down on things and do what Chromium does: open an fd to /proc ahead of time, so that continues to work. Then we use it to update the inode of our RootFS fd instead, and finally, also do the /proc fd itself to hide that one too.
We also don't need to check the st_dev of /proc more than once, since that's not expected to change anyway.
Fixes cefsimple.
> FileManagement: Hide the FEX RootFS fd from /proc/self/fd take 2

- Source/Common/FEXServerClient.cpp
- Source/Common/FEXServerClient.h
- Source/Tools/FEXServer/Main.cpp
- Source/Tools/FEXServer/ProcessPipe.cpp
- Source/Tools/FEXServer/ProcessPipe.h
- docs/ProgrammingConcerns.md
Abstract sockets have one limitation: they are bound to a network namespace. Chromium/CEF sandboxes using a new netns, which breaks connecting to the FEXServer.
To work around this, use and try *both* abstract and named sockets. As long as either the filesystem or the network is unsandboxed, things will work. If both are sandboxed, there isn't much we can do... but at that point we shouldn't be reinitializing the FEXServer connection anyway since the FS should be available on FEXInterpreter startup.
> FEXServer: Listen on both abstract & named sockets

- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/Common/Exception.h
- Source/Windows/WOW64/Module.cpp
- Source/Windows/include/winternl.h
This is required for wow64.dll to setup the cross-process queue that is used to pass through e.g. memory unmap events.
> WOW64: Set the software CPU area flag

- Source/Tools/FEXLoader/FEXLoader.cpp
This ensures we don't underflow at --RootFSLength.
> Check that LDPath is not empty

- CMakeLists.txt
Previously, running ctest with BUILD_TESTS=OFF would discover and execute leftover tests from a previous build. This change ensures CTestTestfile.cmake gets regenerated so that ctest will see an empty test list in that case.
NOTE: `include(CTest)` automatically calls `enable_testing` if `BUILD_TESTING=ON`, so that line has been removed. To ensure `BUILD_TESTS=OFF` produces an empty test list, the CTest module is included unconditionally.
> CMake: Generate test list even when testing is disabled

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
- FEXCore/Source/Utils/Allocator/HostAllocator.h
- FEXCore/include/FEXCore/Core/Context.h
- FEXCore/include/FEXCore/Utils/Allocator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
Alloc::OSAllocator uses a TLS variable of the thread object so it can use a forkable mutex plus a deferring signal section. This was setup when the FEXCore "ExecutionThread" function is called, which is a bit awkward and is an artifact from when the thread creation was mixed between the frontend and the backend.
Instead let the frontend inform the backend when to install the TLS variable.
This is one step required to make GdbServer work correctly again since the thread initialization and pausing is awkward today.
> FEXCore: Moves TLS initialization for Alloc::OSAllocator

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
This was working around an edge case in the GdbServer where a thread was getting created while the process was shutting down. This edge case is getting removed so get rid of it.
> FEXCore: Removes EarlyExit running event

- FEXCore/include/FEXCore/Core/SignalDelegator.h
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Tools/CommonTools/DummyHandlers.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
This is purely a Linux frontend construct now, move it.
> FEXCore: Moves SignalThread/SignalEvent to Frontend

- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
Deferred signal frames are a frontend construct. Move it there.
> FEXCore: Moves DeferredSignalFrames to the frontend

- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
This is a Linux construct, move it to the frontend.
This is going to need some changes in the future since exit_group and exit syscalls are supposed to behave differently than how FEX implements it. For now just move it to the frontend.
> FEXCore: Moves StatusCode to the frontend

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
The CTX pointer in the InternalThreadState object will not and must not change, since it is associated with that CTX object.
Contify it to codify it.
> FEXCore: Constify CTX ptr in InternalThreadState

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- Source/Tools/LinuxEmulation/CMakeLists.txt
- Source/Tools/LinuxEmulation/GdbServer/Info.cpp
- Source/Tools/LinuxEmulation/GdbServer/Info.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.h
Unlike in #3592, this does some initial work towards making my life easier for improving the gdbserver.
Some very minor behaviour changes but pretty much just moving some code around and documenting the command packets so I can quickly search around in vim.
> GdbServer: Minor work

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
Only in one location does the frontend actually care about this, the
backend doesn't care at all.
> FEXCore: Moves ThreadWaiting to the frontend 

- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
Once again this is another frontend construct, so move it to ThreadStateObject
> FEXCore: Moves InternalThreadState ExecutionThread to the frontend

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
These are all frontend constructs with mostly deprecated constraints.
WaitingToStart isn't used anymore, Running is effectively always true
(and behaviour has changed that if a thread is alive, it's running).
The only one that remains is `ThreadSleeping` which is only handled in
the frontend, and there was some conflation between ThreadSleeping and
Running which was hard to gauge. So delete `Running` and
`WaitingToStart`, but move `ThreadSleeping` to the frontend.
> FEXCore: Removes remaining RunningEvents from InternalThreadState 

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- unittests/ASM/X87/LoadAtBoundary.asm
- unittests/ASM/X87/StoreAtBoundary.asm
- unittests/InstructionCountCI/FlagM/x87.json
- unittests/InstructionCountCI/x87.json
These tests ensure that FEX's x87 80-bit loadstores don't read/write past the end of the page.
Noticed we were missing testing this edge case a few days ago.
> unittests/ASM: Fixes x87 80-bit loads on the edge of page boundaries.

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
> FEXCore: Removes CoreShuttingDown from ContextImpl

- FEXCore/Source/Interface/Context/Context.h
`CopyMemoryMapping` was removed a long time ago, the definition happened to remain. Remove the definition.
> FEXCore: Removes stale function definition

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
Only a few remaining uses left, easy enough to convert. This finally switches the final few uses over.
NFC
> FEXCore: Removes GetGPRSize and convert all uses to GetGPROpSize

- FEXCore/Source/Interface/Context/Context.cpp
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
Now that all the threading behaviour has been correctly separated/moved to the frontend, these functions serve no purpose.
- Instead of using RunUntilExit, all threads can use `ExecuteThread` directly, since there's nothing special about the primary thread now.
- This also removes the public function definition of `ExecutionThread` since that was only used for threading logic.
- Instead of using an exit handler, just do the same cleanup after `ExecuteThread` has returned.
- Just make gdbserver is cleaned up early if it exists since it may want to send some things to the connected gdb instance before threads are exited.
> FEXCore: Removes ExitHandler and RunUntilExit

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Thread.cpp
clone3 was added in Linux 5.3 but our minimum spec is 5.0. Additionally the Raspberry Pi 5 kernel seems to complain about clone3 for some reason?
Just use clone instead of clone3
> LinuxEmulation: Don't use clone3 for fork

- docs/ReleaseProcess.md
On December 6th 2024, the fex-emu packages got a deletion request:
> MarsSeed [1] filed a deletion request for fex-emu [2]:
>
> ARM-only package.
> This should be submitted to ArchLinuxARM.org [a], not to AUR - see
> quote from ArchWiki [b]:
>
>     "Packages that do not support the x86_64 architecture
>     are not allowed in the AUR."
>
> [a]:
> https://archlinuxarm.org/forum/viewforum.php?f=4
> [b]:
> https://wiki.archlinux.org/title/AUR_submission_guidelines#Rules_of_submission
>
> [1] https://aur.archlinux.org/account/MarsSeed/
> [2] https://aur.archlinux.org/pkgbase/fex-emu/
This is due to a rule clarification that occured in Arch's forum on November 25th: https://lists.archlinux.org/archives/list/aur-general@lists.archlinux.org/thread/IRZ2LWYX3ECPJQZJXMLAP6JIKL6HLHPZ/#GMYC74CRSFH7GG …
> docs: Remove Arch from the release process.

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- unittests/FEXLinuxTests/tests/syscalls/syscall_exit.cpp
if an application is using `exit` then it is usually a faulting condition rather than cleanly exiting. When cleanly exiting applications will typically use `exit_group` instead.
`exit` is useful to quickly cause a single thread to exit in a multi-threaded environment as well, where `exit_group` will take down the entire process group.
FEX had implemented this in a way that would do a double Stop signal, cascading to a crash. When tied in to a crash handler, this could get caught in a weird way.
This /should/ fix #4198, but I can't confirm locally. It looks like in that issue that the steam install is slightly buggered (as evident by missing srt-logger and steam-runtime-identify-library-abi).
This is a bug regardless so fix it and create a unittest. If it doesn't fix the user's bug, then …
> LinuxSyscalls: Fixes exit syscall

- FEXCore/Source/Interface/Core/Core.cpp
Seems the unused mutex locking is able to cause some hangs according to #4198 Hard to tell why, but might as well as get rid of that potential pitfall.
> FEXCore: Don't `WaitForEmptyJobQueue` if CodeObjectCacheService isn't used

- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
This is the command used when the `k` argument is passed to gdb. There is nothing to do once this is received other than "kill" as quickly as possible. The absolute way to ensure this is using SIGKILL.
No way to do a `r` command after `k` yet, but might be possible.
> GdbServer: Implement support for `$vKill`

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
This only reads the GPRs passed in, doesn't modify it.
> Context: Constify GPRs passed to ReconstructCompactedEFLAGS

- FEXCore/Source/Interface/IR/Passes.h
> IR/Passes: Adds missing comment that clang-format keeps complaining about locally

- Source/Tools/LinuxEmulation/GdbServer/Info.cpp
- Source/Tools/LinuxEmulation/GdbServer/Info.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
Requires restructuring a couple of things, but nothing too crazy here.
First commit is from #4203
> GdbServer: Support 32-bit context definitions

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/include/FEXCore/Core/Context.h
- Source/Windows/ARM64EC/Module.S
- Source/Windows/ARM64EC/Module.cpp
When an SMC trap happens: reconstruct the context before the SMC write then compile the write as a single instruction block to reduce it to regular SMC. SMC where the writing instruction is the instruction being patched will hit the signal handler at most twice: the 1st will trigger the write to be compiled as a single instuction block, the 2nd will detect inline SMC of a single instruction block and then just take the usual invalidate+reprotect+continue step, avoiding a potential infinite loop of recompilation.
Ontop of TF support
> Support inline self modifying code

- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
Just a typo accidentally prefixing 0x on the hex when it shouldn't.
> GdbServer: Fixes encoding of hex

- FEXCore/Source/Utils/FileLoading.cpp
It is not an error that pread returns /less/ than what was requested. In fact it's very common for the Linux kernel to return less than the data requested from procfs.
procfs keeps coming back to bite this function, previously it was fstat returning size of 0 which it hit. Now it only feeds data as much as it wants per loop. In particular /proc/self/maps would only read ~3k bytes on my system, but not be complete.
To fully fix the issue, always make sure to keep reading until there is either an error OR zero is reached!
> Utils/FileLoading: Fix LoadFileImpl

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
This is going to get used by gdbserver soon for ensuring memory accesses are fault safe, because it tries to read outside of correct memory bounds at times.
> Linux/FaultSafeUserMemAccess: Break out fault safe handler

- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
These couple of functions have some footguns that I'm encountering while rewriting gdbserver. Ensure that assertion builds capture the problems
> ThreadManager: Add some sanity asserts

- FEXCore/include/FEXCore/fextl/fmt.h
See: https://github.com/fmtlib/fmt/issues/4247, this is required for newer clang
> External: Update bundled libfmt

- unittests/InstructionCountCI/FlagM/HotBlocks.json
Factorio hammers its drawSprite() function and ends up cpu bound under FEX. Unfortunately, its hot blocks seem to be translated pretty optimally :-/
> InstructionCountCI: add some hot blocks from Factorio

- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
The immediate offset masking was at the completely wrong offset when I wrote these handlers. No idea how I managed to mess those up so badly.
Should fix at least some of the issues with #4216
> ArchHelpers/Arm64: Fixes LDAPUR and STLUR backpatching

- unittests/InstructionCountCI/FEXOpt/MultiInst_TSO.json
- unittests/InstructionCountCI/FEXOpt/MultiInst_TSO_32bit.json
We weren't testing 64-bit variants, and we also weren't testing 8-bit and 16-bit loadstores. Add some more to ensure we are hitting these.
> InstCountCI: Adds more LRCPC2 tests that are missed

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/FlagM/PrimaryGroup.json
- unittests/InstructionCountCI/PrimaryGroup.json
No need to extract the subregisters out before operating on them since
the long division and long remainder IR operations correctly zero/sign
extend the incoming sources as necessary. Saves a couple of
instructions.
> OpcodeDispatcher: Minor division improvement 

- CMakeLists.txt
- ThunkLibs/Generator/main.cpp
- ThunkLibs/GuestLibs/CMakeLists.txt
- ThunkLibs/HostLibs/CMakeLists.txt
This is the last commit from #3597, rebased. It's sufficient to build FEX with thunks on Fedora aarch64, given a suitable x86_64/i686 sysroot with the required includes and glibc/libstdc++ and friends (and some gnarly toochain override files because the cross-compilers Fedora ships on aarch64 aren't actually configured identically to the native compilers on x86/x86_64).
> Library Forwarding: Allow reading standard library headers from a development x86 rootfs

- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
This is a new RootFS approach where the entire filesystem hierarchy is bind-mounted under the RootFS directory, with the RootFS itself overlaid. This, in principle, lets FEX avoid all the RootFS merge logic and lets the kernel do it, which should be both faster and more correct. In particular, symlinks between user directories and the RootFS work, and listing a directory correctly returns the merged entries from the RootFS and the host FS, instead of only the RootFS ones.
This PR includes fixes to make a merged-RootFS configuration work (as well as some misc adjacent issues), but does not add an explicit configuration option to disable the filesystem overlay logic in this scenario. That may come later, but it should only be an optimization at that point and may or may not be worth it.
The …
> Support a merged RootFS (and a bunch of related fixes)

- unittests/gvisor-tests/Disabled_Tests
This tests some bugged or changed behaviour. So we need to disable these since our CI crosses kernel versions that hit both behaviour paths.
> unittests/gvisor: Disable memfd tests

- unittests/ASM/FEX_bugs/3DNow_ModRMSIBDecode.asm
This codepath was unttested in our CI.
> unittests: Adds a 3DNow! ModRM SIB encoding test

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/H0F3ATables.h
- FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
- unittests/ASM/FEX_bugs/H0F3AREXBug.asm
Most of this table ignores REX.W, but two encodings change behaviour
based on REX.W. These two encodings are PEXTRD/PEXTRQ and PINSRD/PINSRQ.
For every other instruction encoding, they will ignore REX.W, but FEX
was requiring that they didn't have REX.W encoding. I had special cased
this in the past by adding PALIGNR, but that didn't handle any of the
other instructions.
We can't just handle REX.W in the OpcodeDispatcher and remove the two
special cased instructions because these vector operations also interact
with instruction prefix 0x66 which changes the operating size to 16bit
with regular instructions.
So instead just generate all listings of instructions with REX.W being
zero and one and install handlers in all cases.
> OpcodeDispatcher: Fixes FEX's H0F3A table handling of REX.W 

- unittests/ASM/OpSize/66_D6.asm
This test was generating the wrong form of instruction. There's no way to choose this form with nasm deliberately, so manually encode it.
Fixes #4150
> unittests/ASM: Fix incorrect instruction form test

- Source/Tools/FEXLoader/FEXLoader.cpp
Some early FEXServer startup log failures weren't getting printed correctly. They were going through the LogManager but before FEXServer setup, or even stderr/stdout logman setup. So they were just getting written to -1 and failing.
Fixes #4155
> FEXLoader: Enable early logs output to stderr

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/IR/IR.json
The IR stores elementsize, where the json was wanting number of elements. While the IR Emitter function declaration always wanted element size. This was causing us to do a little dance from ElementSize -> Number of elements -> ElementSize. Just pass the ElementSize directly instead of this bogus little dance.
> IR: Change convention from number of elements to elementsize

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
> LinuxSyscalls: Ensure CSIGNAL is merged back in to flags for clone2

- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
The thread termination callback can be called for other threads in the
process, not just the current one, in which case we cannot call DeinitCRT.
Deinitializing the CRT of another thread would be awkward so just skip that
and accept the small leak for now.
> Windows: Only deinit the thread CRT when destroying the current thread

- External/tiny-json/CMakeLists.txt
- ThunkLibs/Generator/CMakeLists.txt
Noticed this as I was scrolling through some cmake. Usually this doesn't matter as we declare `BUILD_SHARED_LIBS` as False/Off, but this can technically be overridden even when we don't want to.
Updates the two definitions of `add_library` that was missing the static qualifier to ensure they generate the code we want.
> cmake: Adds some missing STATIC qualifiers

- Source/Windows/Common/CRT/IO.cpp
Noticed that the FEXCore config file was open forever.
> Windows/CRT: Fixes FD leak

- FEXCore/Source/Interface/IR/IRDumper.cpp
Without this the log is full of `<Unknown OpSize Type>` when looking at x87 IR.
> Print arg type f80Bit

- FEXCore/Source/Interface/Core/Frontend.cpp
Currently FinalInstruction causes only to the currently decoding block to be terminated, but that is not enough as both MaxInst and DefaultDecodedBufferSize are global limits that apply across all blocks within a multiblock.
> Frontend: Stop all decoding once MaxInst/DecodeBufferSize is reached

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
Multiblock can generate such not-taken ExitFunction calls when enabled
> JIT: Avoid OOB EC bitmap checks in ExitFunction

- FEXCore/Source/Interface/Core/Frontend.cpp
'add [rax], al' is almost never seen in actual code so the assumption can be made that we are most likely trying to explore garbage code and that this will never be hit. If it is then code will be generated at that point (where Entrypoint == true).
> Frontend: End multiblocks early after hitting 2 consecutive null bytes

- FEXCore/Source/Utils/Profiler.cpp
- FEXCore/include/FEXCore/Utils/Profiler.h
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/Common/CRT/IO.cpp
- Source/Windows/WOW64/Module.cpp
This will get gpuviz working under Wine.
> Profiler: Setup for usage on Windows

- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
With multiblock enabled, host code generated from guest code with a lower address may be placed after host code generated from guest code with a higher address in a multiblock. As each guest RIP reconstruction entry is always relative to the one before it the offset needs to be signed to allow this.
> CPUBackend: Make guest RIP reconstruction offsets signed

- FEXCore/Source/Interface/Core/Frontend.cpp
This avoids both the generation of multiblocks that cover massive spans of guest code, which causes issues for both SMC and context reconstruction and attempting to decode branch targets in unmapped memory regions.
Once support for querying mappings from the FEX frontend is in place this limit could be increased if necessary, but this seems fine for now.
> Frontend: Disallow cross-page branches in multiblock

- Source/Tools/LinuxEmulation/LinuxSyscalls/Arm64/SyscallsEnum.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/FS.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/SyscallsEnum.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/SyscallsEnum.h
Just four new *at variants of the xattr syscalls.
This will also let us use the *at variants for the non-at versions but I didn't implement that optimization because this is brand new.
> LinuxSyscalls: Update for new v6.13 syscalls

- Source/Common/HostFeatures.cpp
- ThunkLibs/Generator/analysis.cpp
These don't show up in the default build configuration and hence were missed before.
> Fix warnings about unused objects

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
This PR fixes two critical issues in Paranoid TSO mode: Many applications that work with FEX's default settings would fail to run since TSO emulation wasn't enabled for most instructions. Further complications arose due to indirect memory addressing not being implemented.
A negative (but expected) side effect of fixing these issues is that Paranoid TSO mode will now make emulation unusably slow (>90% performance impact). I'm not sure there are strong enough reasons to keep around the current PTSO approach, so I wrote a patch that implements backpatching-free TSO without requiring excessive signalling. It's not included here since it's a bit more tricky to maintain at the moment, but this current PR will get things back to a functional state at least.
As a small but related side change, I …
> Fix crashes in Paranoid TSO mode

- unittests/ASM/PrimaryGroup/3_F7_05_2.asm
Needs cwd/cdq/cqo to sign extend into RDX/EAX/AX for imul to do what is described, for example in
```
; Negative * Negative
mov ax, -128
imul word [r8 + 8 * 0 + 0]
ofcfmerge
```
dx:ax is not negative, unless if we do `cwd`
> Fix slight inaccuracy in test 3_F7_05_2

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
At the moment this seems to be NFC since all calls to this function end up passing `true` but it seems that it's a bug waiting to happen if someone ever calls the function with `false`.
> Pass through FPRs argument

- .clang-format-ignore
- .git-blame-ignore-revs
- CodeEmitter/CodeEmitter/ALUOps.inl
- CodeEmitter/CodeEmitter/ASIMDOps.inl
- CodeEmitter/CodeEmitter/BranchOps.inl
- CodeEmitter/CodeEmitter/Emitter.h
- CodeEmitter/CodeEmitter/LoadstoreOps.inl
- CodeEmitter/CodeEmitter/SVEOps.inl
- CodeEmitter/CodeEmitter/ScalarOps.inl
- CodeEmitter/CodeEmitter/SystemOps.inl
- CodeEmitter/CodeEmitter/VixlUtils.inl
- Scripts/reformat.sh
External tooling couldn't process these files before since there was no context, but with a little preprocessor hack this can be supported. I'm not too happy about needing this, but we only need it for these 8 files.
As a nice bonus, other tooling (IDEs in particular) can process these files as well now, allowing "go to definition", error highlighting, and other features to work out of the box.
Best reviewed per patch, since the second patch reformats 18.000 lines of code that hadn't been auto-formatted before.
> CodeEmitter: Auto-format .inl headers

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
Removing unused declarations.
Cleaning up unused headers and empty lines.
Avoiding static analysis warnings on `const auto` defaulting to int.
> NFC: Code cleanup

- Scripts/changelog_generator.py
Looking e.g. over the [2405 release notes](https://github.com/FEX-Emu/FEX/releases/tag/FEX-2405), I noticed categories and descriptions are placed on separate lines:
> - Allocator
>  - Fixes compiling on Fedora 40 (https://github.com/FEX-Emu/FEX/commit/7b88b0f2711b1ee9f2f47f7547b6ee3d2a184d90)
> - AllocatorHooks
>  - Mark JIT code memory as EC code on ARM64EC (https://github.com/FEX-Emu/FEX/commit/bb24e1419c5ef07ee9d93b2d77fa08c8253902cf)
> - AppConfig
>  - Disable libGL forwarding for steamwebhelper (https://github.com/FEX-Emu/FEX/commit/02ebb6e32074ca26d60727b998d39fe04a2a2465)
Instead, the descriptions were meant to be placed in sublists (since there might be multiple per category):
> - Allocator
>   - Fixes compiling on Fedora 40 …
> Scripts: Fix indentation of changelog items

- CodeEmitter/CodeEmitter/ALUOps.inl
- CodeEmitter/CodeEmitter/BranchOps.inl
- CodeEmitter/CodeEmitter/Emitter.h
- CodeEmitter/CodeEmitter/LoadstoreOps.inl
- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
- FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/AtomicOps.cpp
- FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
The biggest change here is the merger of ForwardLabel and SingleUseForwardLabel by adding a small-vector optimization for the former. In this new version, clang [can elide](https://godbolt.org/z/1Ycse1z5e) unnecessary `std::vector` code in principle, but there is still a 0.13% Release binary size overhead since that doesn't always happen in practice.
At runtime we still avoid any unnecessary heap-allocation, so maybe the simpler code is worth it (fewer templates + not having two classes that kinda do the same thing). If not I can take the patch out from the series too. (Arguably it would be handy to have a more generic SmallVector utility that we can use elsewhere too, though.)
The other patches should be uncontroversial.
Binary size changes:
* Release: 4,209,232 -> 4,214,896 bytes
* …
> CodeEmitter: Various cleanups

- ThunkLibs/libwayland-client/Guest.cpp
`clang-format` tried a bit too hard to help here.
Before:
```cpp
LOAD_LIB_INIT(libwayland - client, OnInit)
```
After:
```cpp
LOAD_LIB_INIT(libwayland-client, OnInit)
```
This caused FEX to search for a file named `libwayland - client-host.so` instead of `libwayland-client-host.so`, hence failing to map the library to its host equivalent.
> Library Forwarding/wayland: Fix regression caused by erroneous format

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/FS.cpp
> LinuxEmulation: Ensure syscall wrapper declaration has CpuStateFrame as the first argument

- FEXCore/Source/Utils/Profiler.cpp
String parsing was adding a newline but then we failed to use it. I don't think it caused any issues considering how infrequent instant profiler objects are used.
> Profiler/GPUViz: Fixes typo in instant TraceObject

- unittests/InstructionCountCI/Primary.json
Nasm between the versions of 2.16.03 and 2.15.05 starting changing the operand order of the instruction on us. Hard code both operand encodings to ensure coverage.
Fixes #4296
> InstCountCI: Hardcode xchg instructions

- FEXCore/Source/Utils/Profiler.cpp
These parsing strings are tiny, less than 64 bytes all the time. Just stack allocate the buffer. Makes it safer to use during extenuating circumstances as well, like SIGBUS and SIGSEGV.
> Profiler/GPUViz: Stop allocating memory

- FEXCore/Source/Utils/Allocator.cpp
- FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
- FEXCore/Source/Utils/Allocator/FlexBitSet.h
- FEXCore/Source/Utils/Allocator/HostAllocator.h
- FEXCore/include/FEXCore/Utils/Allocator.h
- FEXCore/unittests/APITests/FlexBitSet.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
When running on a system with a 48-bit VA, if FEX does any allocations between us reserving the upper 128TB and the application running, then /technically/ we are intersecting with the application's memory region in the lower 47-bits.
This didn't typically result in any problems due to how ASLR works, but if we did any large allocations (like #4291 wants with 128MB VMA region) then these typically get pushed higher in the VA space.
Again not usually a problem, but if you happen to be running an application that is using MAP_FIXED with hardcoded addresses then this can stomp over FEX-Emu memory causing problems.
This is what happens with Wine, it reserves the upper-32MB of its 47-bit VA space, which is /highly/ likely to stomp on FEX memory. In-fact it likely occurs all the time, we just …
> FEX: Allocate a VMA allocator when running on a 48-bit VA

- Source/Tools/FEXLoader/ELFCodeLoader.h
For some reason steamwebhelper is setting a zero length environment variable. This was causing an assert to be raised early as the web helper was starting up.
Just stop trying to memcpy the zero length string, gets steamwebhelper working in the steam beta client again
> FEXLoader/ELFCodeLoader: Be robust against zero length environment variables

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
- FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IREmitter.cpp
- FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp
- unittests/ASM/X87/MemcopyWithCPUID.asm
- unittests/InstructionCountCI/X87ldst-SVE.json
Alternative implementation to #4274 
Fixes #4264
> Predicate cache alternative implementation

- FEXCore/Source/Interface/Config/Config.json.in
- Source/Tools/FEXLoader/FEXLoader.cpp
Sleeps only if current process matches this name. Leave empty to sleep StartupSleep seconds on all processes.
> Add option StartupSleepProcName

- FEXCore/Source/Utils/Allocator.cpp
`fmt` requires pointers to be wrapped in `fmt::ptr`, otherwise it will fail at runtime.
> Allocator: Fix format string

- CMakeLists.txt
Our unittests don't compile with Catch2 2.x, so make sure to fall back to the submodule if the system library is not a 3.x version.
> CMake: Check for compatible Catch2 versions

- Source/Tools/FEXServer/Main.cpp
Certain configuration changes are missed unless FEXServer restarts, so the 10s timeout could make iterative development a bit annoying.
It's quite rare that no FEX process would run for more than 1 second but less than 10 seconds, so this seems like a more reasonable default.
> FEXServer: Lower close timeout

- FEXCore/Source/Interface/IR/IR.h
- FEXCore/Source/Interface/IR/IRDumper.cpp
Nothing here is modified, so this interface can be used with const references, too.
> IRDumper: Allow const RA data

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
When the alt-stack gets overflown then it is hard to see what went wrong since the TLS variable is no longer accessible.
Protect the first page that contains the TLS variable.
Fixes #4320
> SignalDelegator: Protect first page of the altstack

- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/NetStream.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/NetStream.h
A major limitation of iostream is that you can't have reads or writes
with a safe interrupt. Instead rewrite the interface with Linux ppoll so
that these can be safely interrupted with a signal and return early.
> GdbServer: Implement new netstream that can be interrupted

- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Utils/variable_length_integer.h
- FEXCore/unittests/APITests/vl_integer.cpp
When #2722 implemented this initially and #4271 switched over to signed int16_t there was assumptions made that int16_t was a reasonable trade-off in encoding size versus needing to deal with 8-bit values being too small in some cases.
In the common case we are almost always encoding 8-bit values because instructions are typically linear (and less than 15-bytes in size), but 16-bit was chosen because optimizing JIT and multiple instructions that don't cause exceptions can add up to larger than 8-bit.
Instead of hardcoding 16-bit values, implement a variable length integer class where ~96.8% of values are 8-bit encoded, and the remaining 3.19% are encoded using 16-bit. Due to some constraints that #4271 put in place, we can basically guarantee currently that branch targets are within …
> FEXCore/JIT: Encode the JITRIPReconstructionEntries using variable length integer

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/IR/AOTIR.cpp
- FEXCore/Source/Interface/IR/IntrusiveIRList.h
This wastes a significant amount of compilation time (30%!!) when the copies IR is promptly thrown away after compilation anyway.
Breaks AOTIR - this is already broken and removal is planned so shouldn't be an issue.
Stats (mean over 3*8 runs of nodejs):
With: 2419065553ns
Without:  3307522698ns
> FEXCore: Don't copy IR after compilation

- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/Frontend.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
With the prior approach, backwards jumps into existing blocks would explore the overlapping part rather than splitting the block, generating needless code and wasting time decoding. Similarly, the current block wouldn't be split when it is extended to overlap with a pending jump target.
Solve this by tracking blocks in a sorted vector and splitting existing blocks on jumps when appropriate, in order to avoid any possibility of overlapping blocks, which would break the lookup, misaligned and zero instruction blocks are disallowed.
When exploring, keep track of the next block/jmp target following the current to know when to split or end the block (note the special case of A rejoining a block B but misaligned, A is dropped at such point but added to VisitedBlocks so future jumps there don't …
> Frontend: Split blocks at jump target boundaries

- FEXCore/Scripts/config_generator.py
- Source/Common/Config.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/Common/PortabilityInfo.h
- Source/Windows/WOW64/Module.cpp
Completely didn't listen to FEX_PORTABLE. Necessary otherwise it can read configs from some random locations when portable is enabled.
> WINE: Fixes FEX_PORTABLE usage

- FEXCore/Source/Interface/Config/Config.cpp
- Source/Tools/CommonTools/PortabilityInfo.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXServer/CMakeLists.txt
- Source/Tools/FEXServer/Main.cpp
This was causing FEXServer to look in to global installed paths and local paths for things when FEXServer was started.
Ensure it listens to FEX_PORTABLE so this doesn't occur. This also requires us to scan both data directories and config directories to find them.
> FEXServer: Fixes FEX_PORTABLE usage

- FEXCore/Source/Utils/variable_length_integer.h
- FEXCore/unittests/APITests/vl_integer.cpp
For some reason when I was writing the tests I got the byte order
incorrect. The type header needs to be in the first byte, not the second
byte.
> FEXCore/vl64: Fixes int16 encoding

- FEXCore/Source/Interface/Config/Config.json.in
Dep #4325 #4326 
Before these:
MB on: 3790969649ns
MB off: 3169002331ns
After:
MB on: 2594371996ns
MB off: 2386604655ns
Seems reasonable to take the 10% hit here
> Config: Enable multiblock by default

- Source/Common/FEXServerClient.cpp
- Source/Common/FEXServerClient.h
- Source/Tools/CommonTools/PortabilityInfo.h
- Source/Tools/FEXLoader/FEXLoader.cpp
argv[0] is whatever the user passed in and may not directly be FEXLoader/FEXInterpreter's path. Make sure get the full path.
> FEXServerClient: Fix searching for FEXServer

- Source/Common/FEXServerClient.cpp
- Source/Tools/FEXServer/ArgumentLoader.cpp
- Source/Tools/FEXServer/Main.cpp
- Source/Tools/FEXServer/PipeScanner.cpp
- Source/Tools/FEXServer/PipeScanner.h
The problem here is that the pipe we used for telling FEXInterpreter that the FEXServer is ready to accept connections was inherited by erofsfuse or squashfuse. So the closing of the pipe from the FEXServer side would leave a reference open in squashfuse or erofsfuse.
Fix this by setting FD_CLOEXEC on the pipe, but also pass the pipe FD through an argument instead of scanning for all pipes.
Then once we execve the squashfuse/erofsfuse application, the FD isn't inherited.
Fixes #4329
> FEXServer: Fixes background startup

- FEXCore/Source/CMakeLists.txt
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/InterpreterFallbacks.cpp
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/StringCompareFallbacks.cpp
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/VectorFallbacks.h
With ASIMD this can be decently faster. With my microbenchmark this makes pcmpistri ~6% faster.
With #4324 this can be made even faster since the incoming data can stay in vector registers; Removing some overhead of umov.
> FEXCore: Optimize VPCMPISTRX implicit length calculation

- FEXCore/Source/Common/SoftFloat.h
- FEXCore/Source/Common/VectorRegType.h
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/InterpreterFallbacks.cpp
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/StringCompareFallbacks.cpp
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/VectorFallbacks.h
- FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- unittests/InstructionCountCI/FlagM/HotBlocks.json
- unittests/InstructionCountCI/SSE42_Strings.json
This reduces our codegen size and removes a few umov instructions. Performance falls within noise but this small change will allow us to do more vector optimizations in C code in the future.
> FEXCore: Keep PCMPISTRI arguments in vectors longer

- .gitmodules
- CMakeLists.txt
- FEXCore/Source/CMakeLists.txt
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Utils/Profiler.cpp
- FEXCore/include/FEXCore/Utils/Profiler.h
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
The existing GPUVis backend isn't suitable for live-profiling and carries heavy overhead per traced event (a memory allocation and a system call). This makes gathering accurate data for quantitative analysis impossible.
This PR adds a new backend for FEX's profiler interface based on Tracy, a nanosecond resolution profiler with support for live tracing and a rich feature set. Notably, statistics and histograms are generated from profiled zones out-of-the-box.
To use this backend, one of the environment variables `FEX_PROFILE_TARGET_NAME`
or `FEX_PROFILE_TARGET_PATH` must be defined to select the application under
profile by name or by path suffix.
Here's an example screenshot of the profiler view while running God of War (a very JIT-time heavy title). I'll post more screenshots as …
> Profiler: Add Tracy backend

- CodeEmitter/CodeEmitter/SVEOps.inl
We had duplicated code paths in the ternary selection for 64-bit source size, and on 32-bit source size 16-bit is an invalid target so the second ternary was dead.
> CodeEmitter: Minor fixes to SVE fcvtz{u,s}

- Source/Common/Profiler.cpp
Was accidentally zeroing size of ThreadStatsHeader instead of ThreadStats. So 64 bytes instead of 48, which would have overrunned a slot.
> Profiler: Fixes zeroing of allocated slots.

- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
This would become an issue when multiple threads are contending with the SIGBUS handler on the same code.
We were failing to mask the VR, OPC, Rm, and Option bits, resulting in a comparison below always resulting in a false result if another thread managed to backpatch.
This was just unlikely to be seen on LRCPC2 supporting hardware and since we fixed `LDSTUNSCALED_MASK` before, this wasn't really getting seen.
> ArchHelpers/Arm64: Fix loadstore mask

- FEXCore/Scripts/config_generator.py
- Source/Common/Config.cpp
- Source/Common/Config.h
It is desired that FEX_APP_CONFIG and FEX_APP_CONFIG_LOCATION support
relative paths when portable is used. Support this.
> Config: Correctly handle relative paths with portable 

- FEXCore/Source/Interface/IR/AOTIR.cpp
- FEXCore/Source/Interface/IR/Passes/IRDumperPass.cpp
- FEXCore/Source/Utils/Telemetry.cpp
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
Just switch the uses over to `const auto&`
> Fixes some instances of auto usage with unintentional copy

- FEXCore/Source/Utils/Profiler.cpp
This seems to have slipped in while I had rebased #4300 on latest main.
> Profiler: Drop accidentally included debugging code

- Data/ThunksDB.json
- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Tools/FEXConfig/Main.cpp
- Source/Tools/FEXConfig/Main.h
- Source/Tools/FEXConfig/main.qml
- Source/Windows/Common/CRT/String.cpp
This will save the list of enabled libraries to the main configuration file. Reading it from there was already supported.
Using a dedicated Thunks.json is considered deprecated and should not be used anymore outside of FEX testing.
Example Config.json:
```json
{
"Config":{...},
"ThunksDB": {
"fex_thunk_test":0,
"asound":0,
"drm":0,
"Vulkan":1,
"WaylandClient":0,
"GL":0
}
}
```
> Library Forwarding: Add GUI for enabling use of individual host libraries

- FEXCore/Source/Interface/Core/CPUBackend.h
Reduces the size by 8 bytes from 48 to 40.
> CPUBackend: Move bool to end of JITCodeTail

- FEXCore/Source/Interface/Core/JIT/EncryptionOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/Crypto/H0F38.json
Only saves a handful of instructions, but still an improvement.
```diff
"sha1msg2 xmm0, xmm1": {
-      "ExpectedInstructionCount": 11,
+      "ExpectedInstructionCount": 7,
```
> OpcodeDispatcher: Implement support for SHA1MSG2 using SHA instructions 

- FEXCore/Source/Interface/Core/JIT/VectorOps.cpp
- unittests/ASM/FEX_bugs/MinMaxNaN.asm
- unittests/InstructionCountCI/AFP/VEX_map1.json
If AFP.AH is supported then fmin/fmax behaves like the x86 min/max
instruction so we don't need to jump through any additional hoops.
Support this use case to save a few instructions when AFP is supported.
> JIT: Optimize packed float min/max if AFP is supported 

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
- unittests/InstructionCountCI/Crypto/H0F38.json
- unittests/InstructionCountCI/Crypto/H0F3A.json
We already have this mask generated, and because sha instructions
typically don't exist in a vacuum it is actually beneficial to cache the
mask and use a single tbl instruction per shuffle.
OpenSSL has 12 sha1 instructions in their hot loop as an example, so
this would be a fairly good reduction in that loop. Sadly we don't have
it in instcountci, instead having their sha256 hotloop instead (Which
currently doesn't have sha256rnds2 optimized).
Even in a vacuum this is technically 1 instruction savings for each
instruction which is nice.
> OpcodeDispatcher: Reuse PSHUFD shuffle mask for sha data shuffling 

- FEXCore/Source/Interface/Core/JIT/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/DDDTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/ASM/3DNow/86.asm
- unittests/ASM/3DNow/87.asm
- unittests/ASM/3DNow/96.asm
- unittests/ASM/3DNow/97.asm
- unittests/ASM/Disabled_Tests
- unittests/ASM/H0F3A/66_22_2.asm
- unittests/ASM/Includes/checkprecision.mac
- unittests/ASM/REP/F3_52.asm
- unittests/ASM/REP/F3_52_2.asm
- unittests/ASM/REP/F3_53.asm
- unittests/ASM/TwoByte/0F_52.asm
- unittests/ASM/TwoByte/0F_53.asm
- unittests/ASM/VEX/vrcpps.asm
- unittests/ASM/VEX/vrcpss.asm
- unittests/ASM/VEX/vrsqrtps.asm
- unittests/ASM/VEX/vrsqrtss.asm
- unittests/InstructionCountCI/DDD.json
- unittests/InstructionCountCI/RPRES/DDD.json
Reciprocal estimations did not have enough accuracy. Tests were enabled to check for accurate values of reciprocals.
> Improve reciprocal estimate and tests

- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/SecondaryGroupTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/SecondaryTables.h
- FEXCore/Source/Interface/Core/X86Tables/SecondaryGroupTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
These are used by recent Denuvo. LSL behaviour doesn't match Windows or Linux exactly but I don't see this mattering, and the Windows behaviour is to encode the cpu index in the segment size anyway so exposing e.g. a way for the frontend to set sizes wouldn't cut it.
Unsure what to do about tests for these since they're not deterministic across different OSs.
> Implement SIDT/LSL

- CodeEmitter/CodeEmitter/LoadstoreOps.inl
- FEXCore/unittests/Emitter/Loadstore_Tests.cpp
We weren't checking if the post-index variants of these instructions were using the correct post-offset. These support /only/ the correctly sized post-index. The no-offset version is an entirely different set of functions.
> CodeEmitter: Adds missing assert checks

- Source/Common/Profiler.h
If ProfileStats aren't enabled then `Initialize` early returns, but some of these values weren't being zero initialized which could result in crashes.
Ensure all the values in StatAlloc are zero initialized so this doesn't occur.
> Profiler: Fixes potential crash due to uninitialized variables

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
NFC. These wouldn't even occur in practice.
> Various: Removes warnings about uninitialized variables

- Source/Common/ArgumentLoader.cpp
- Source/Common/ArgumentLoader.h
The argument loader was loading configuration from the arguments twice.
The use of the argument loader needs to preload the arguments before being handed off to the config system. This way we can pull remaining arguments that get passed to the guest application.
Due to this, `Load` was getting called twice, once in the constructor and once in the Config system. This was causing the backend to allocate twice as much memory since the second load appends the arguments to a fextl::list internally.
Not really any functional change but it was causing some heartburn with some changes I was working on.
> ArgumentLoader: Fixes double load

- FEXCore/Source/Interface/Config/Config.cpp
- FEXCore/include/FEXCore/Config/Config.h
- Source/Tools/FEXLoader/ELFCodeLoader.h
With the previous fixes in place, we can now stop burning a fextl::list in every single config option. This list is only required for strarray options so reserve it for those entirely.
We also don't need to save the config option enum for each, so these actually go from ~32 bytes per object down to their base type for most everything.
> Config: Stop using config values with list when unnecessary

- FEXCore/Source/CMakeLists.txt
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/F80Fallbacks.h
This is embarassing. We were throwing away performance by failing to use the softfloat library's inline helpers.
Turns out we needed to define `INLINE` to something in order for them to work.
Feels bad.
> Softfloat: Define INLINE

- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
This comment isn't relevant anymore as unused half of ymm loads will get DCE'd
> AVX128: Remove old comment from VEXTRACT{F,I}128

- Scripts/StructPackVerifier.py
Fixes some errors with newer compilers.
> StructVerifier: Use isystem for system header includes

- Scripts/DefinitionExtract.py
This makes diff-ing the output with existing Vulkan definitions easier.
> Scripts/DefinitionExtract: Make output consistent with clang-format

- ThunkLibs/libvulkan/libvulkan_interface.cpp
This was missed in #4402 since `thunkgen` doesn't error out when annotating parameters of an undeclared entry point.
> LibraryForwarding/vulkan: Add missing vkCmdPushDescriptorSetWithTemplate declaration

- FEXCore/Source/Interface/Core/JIT/ConversionOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/IR/IR.json
- unittests/InstructionCountCI/FlagM/x87-Oblivion.json
- unittests/InstructionCountCI/FlagM/x87.json
- unittests/InstructionCountCI/FlagM/x87_f64.json
- unittests/InstructionCountCI/x87.json
- unittests/InstructionCountCI/x87_f64.json
We weren't optimally moving two GPRs in to a vector register because we had no way to describe this operation easily.
Shaves an instruction off of each FILD and FRSTOR instruction. Should fall within noise but makes the asm a bit easier to read.
> X87: Minor optimization in how GPRs are moved in to vector registers

- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
- unittests/InstructionCountCI/AVX128/VEX_map1.json
- unittests/InstructionCountCI/AVX128/VEX_map1_FCMA.json
- unittests/InstructionCountCI/AVX128/VEX_map2.json
- unittests/InstructionCountCI/AVX128/VEX_map2_AFP.json
- unittests/InstructionCountCI/AVX128/VEX_map2_SVE128.json
- unittests/InstructionCountCI/AVX128/VEX_map2_flagm.json
- unittests/InstructionCountCI/AVX128/VEX_map3.json
- unittests/InstructionCountCI/AVX128/VEX_map3_SVE128.json
- unittests/InstructionCountCI/AVX128/VEX_map_group.json
Turn this into stp to save a move in a /ton/ of AVX-128 code. It's pretty
annoying to optimize this at the dispatcher level because of the SRA cache, so
doing it in the ConstProp is a nice compromise solution.
> ConstProp: optimize StoreContext(128-bit zero)

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.cpp
Previously, new VMA entries were always prepended to the list of the associated MappedResource. This usually made FirstVMA erroneously point to the *highest* VMA instead of the lowest.
> SMCTracking: Fix order of VMAs tracked per MappedResource

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/CPUID.cpp
Instead use the HostFeatures option that exists which is controlled by the {enable,disable}crypto option.
> FEXCore: Remove CPUID option for SHA

- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
Support using an app profile for putting a process to sleep at the start. Useful for getting a debugger attached early.
> WINE: Support sleeping a process

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/FlagM/Secondary.json
- unittests/InstructionCountCI/Secondary.json
hit by upcoming opt pass, but we don't want to depend on that pass for that.
> OpcodeDispatcher: drop useless mask in trivial cmpxchg

- FEXCore/Scripts/config_generator.py
- FEXCore/Source/Common/StringConv.h
- FEXCore/Source/Interface/Config/Config.cpp
- FEXCore/include/FEXCore/Config/Config.h
- Source/Common/Config.cpp
- Source/Common/FEXServerClient.cpp
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXConfig/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
Instead of keeping the vlaue as a string array in the MetaLayer, convert the value to its final type once.
Improves performance in some hotpaths that were doing config based string conversion in a relatively high frequency.
> Convert config options once

- FEXCore/Source/Interface/Core/Addressing.cpp
Bitwise AND here is a little odd and was likely intended to be a logical AND.
> Addressing: Amend binary AND into logical AND in SelectAddressMode()

- Source/Tools/FEXRootFSFetcher/Main.cpp
Just a few instances where static analysis reports unnecessary copies.
> FEXRootFSFetcher: Move strings in GetDistroInfo()

- FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
- FEXCore/Source/Interface/Core/JIT/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
- FEXCore/Source/Interface/IR/IREmitter.h
- FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
NFC, none of these would be hit but good to guard against potential programming errors.
> Static analysis warning fixes

- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
This is already guaranteed to be true, since it's checked in the outer if, so this can just be a regular else statement
> OpcodeDispatcher: Remove unnecessary 128-bit check in VPGATHER()

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
If Src isn't a constant, then no value is actually assigned to SrcConst, so this can result in uninitialized arithmetic being performed
> OpcodeDispatcher: Fix potential for uninitialized value use in RCRSmallerOp()

- FEXCore/Source/Interface/Core/Addressing.cpp
ilog2 already has an assert for this.
> Addressing: Remove unnecessary assert in LoadEffectiveAddress()

- CodeEmitter/CodeEmitter/Buffer.h
Lets us tidy up the repeated generation code a little bit (and also allow for generic data writing, should it ever be needed)
> CodeEmitter: Generify data writing

- unittests/InstructionCountCI/FEXOpt/MultiInst.json
to see the impact of Billy's stuff in a real world context since we don't have hot blocks for it yet. random blocks I pulled from Control_DX11.exe which I had handy, with rip relative addressing replaced.
> InstructionCountCI: add blocks using F->I conversion

- CodeEmitter/CodeEmitter/SVEOps.inl
- FEXCore/unittests/Emitter/SVE_Tests.cpp
We couldn't add these before because vixl had a policy of not implementing cryptography ops (which is now not the case), so we can go ahead and drop those into place so we never have to worry about them
> CodeEmitter/SVEOps: Add SVE2 crypto operations

- CodeEmitter/CodeEmitter/Registers.h
- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
- FEXCore/Source/Interface/IR/IR.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Types.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Types.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Types.h
This type trait is deprecated in C++26 (see the relevant [proposal](https://isocpp.org/files/papers/P3247R2.html) that spurred this), so we can just use one of the more specific related traits instead.
Gets rid of needing to care about this later down the line.
> General: Replace deprecated std::is_trivial/std::is_trivial_v trait usages

- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
These three options are mutually exclusive with each other and could potentially result in invalid encodings of the table on accident.
Change over to a 2-bit bitfield to encode if the operand that consumes the VEX option is none, destination, 1st src, or 2nd src.
This ensures the table can't ever be incorrectly encoded.
> FEXCore/Frontend: Changes how VEX operand encoding flags are encoded

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Time.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/FD.cpp
- unittests/FEXLinuxTests/tests/syscalls/futimesat.cpp
Since this syscall doesn't exist, we need to convert it to the
equivalent utimensat like the kernel does internally.
This is fairly trivial but there are some safety nets in place.
> LinuxSyscalls: Emulate futimesat syscalls

- FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp
Just to silence some warnings that think these aren't zero initialized before using.
> x87StackOptimizationPass: Initialize a couple of arrays

- CMakeLists.txt
- Scripts/aarch64_fit_native.py
Hasn't been updated in a while, missing a bunch of CPUs. Noticed since my Orion-O6 was getting compiled for a Cortex-A57.
Additionally remove the comment about llvm not being able to detect newer Kryo CPUs since that has been fixed since Clang 12 from MR https://reviews.llvm.org/D94954 and our minimum spec is Clang 13.
> Scripts: Update CPU classification

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Core/JIT/ConversionOps.cpp
- FEXCore/Source/Interface/Core/JIT/VectorOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Scripts/InstructionCountParser.py
- Source/Common/HostFeatures.cpp
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/AVX128/VEX_map1.json
- unittests/InstructionCountCI/DDD.json
- unittests/InstructionCountCI/FEXOpt/MultiInst.json
- unittests/InstructionCountCI/Secondary.json
- unittests/InstructionCountCI/Secondary_OpSize.json
- unittests/InstructionCountCI/Secondary_REP.json
- unittests/InstructionCountCI/Secondary_REPNE.json
- unittests/InstructionCountCI/Secondary_REPNE_SVE128.json
- unittests/InstructionCountCI/Secondary_REP_FRINTTS.json
- unittests/InstructionCountCI/VEX_map1.json
- unittests/InstructionCountCI/VEX_map1_FRINTTS.json
https://github.com/FEX-Emu/FEX/pull/4237 fixed our float->int conversions to match x86 semantics. That fixed a bunch of games, but unfortunately significantly regressed performance. Fortunately, when frintts is supported, we can optimize the sequence using the appropriate arm instruction. This should recover most of the perf lost by #4237.
> Optimize float->integer conversions with Feat_FRINTTS

- Source/Tools/FEXLoader/FEXLoader.cpp
Avoids the non-fatal error: "[ERROR] Close closing FEX FD 2" that happens when the guest program executes a syscall to close fd 2, and it's not in fex tracked set.
> Initialize OutputFS to -1

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/SecondaryTables.h
- FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
- Thunk opcodes are unused on windows and cause more garbage code to be explored in denuvo games
- Noticed suspend checks were being incorrectly emitted for arm64ec
> Windows: Small fixups

- FEXCore/Source/Interface/Core/JIT/EncryptionOps.cpp
- FEXCore/Source/Interface/IR/IR.json
I keep carrying this patch around. Not yet wired up to the instruction implementation yet, but I don't want to forget about it.
> IR: Implement support for sha256h{2,}

- FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp
- unittests/ASM/FEX_bugs/x87DecrementStackBug.asm
- unittests/ASM/FEX_bugs/x87IncrementStackBug.asm
On the slow path these were pushing and popping in the wrong direction.
Switch them around to ensure the unittests work.
> x87OptimizationPass: Fixes {Inc,Dec}StackPop

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
In the Push/Pop CalleeSavedRegisters these vectors were getting created on the heap, allocating memory and then just iterating them.
Just use a std::array which makes it stop allocating memory and saves the number of instructions.
Before:
After:
> FEXCore/Emitter: Stop creating a vector on the heap

- FEXCore/Source/CMakeLists.txt
- FEXCore/Source/Interface/Config/Config.cpp
- FEXCore/Source/Interface/Core/CPUID.cpp
- FEXCore/Source/Utils/CPUInfo.cpp
- Source/Common/CMakeLists.txt
- Source/Common/CPUInfo.cpp
- Source/Common/CPUInfo.h
- Source/Common/HostFeatures.cpp
- Source/Tools/FEXLoader/AOT/AOTGenerator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
- Source/Windows/Common/CPUFeatures.cpp
- docs/ProgrammingConcerns.md
Nothing crazy, just recalculate the maximum string length rather than
use PATH_MAX.
> FEXCore: Reduce stack usage in CalculateNumberOfCPUs

- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/FD.cpp
`llseek` returns only ever 0 or errno in the return register. This is in contrast to `lseek` which returns the result (or errno) in the return register.
We were accidentally returning the result on non-error conditions which could freak out some software. Thanks to
[OFFTKP](https://github.com/OFFTKP) for pointing out this issue
> LinuxSyscalls: Fixes 32-bit llseek result

- unittests/gcc-target-tests-32/Disabled_Tests
- unittests/gcc-target-tests-32/Known_Failures
No point in duplicating test info between Disabled and Known Failures.
Leaving tests known to fail in Known_Failures. Flakes / Unreliable tests go into Disabled_Tests.
> Cleanup info test files for 32bits

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/HLE/SyscallHandler.h
- FEXCore/include/FEXCore/Utils/AllocatorHooks.h
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
Cross process notifications need to be handled before compilation to avoid permissions changes from e.g. game launchers injecting code being missed.
> Windows: Misc cleanups and fixes

- CodeEmitter/CodeEmitter/ASIMDOps.inl
- FEXCore/unittests/Emitter/ASIMD_Tests.cpp
Like with the SVE side of things, we can just drop these into place, now that vixl supports them
> Emitter: Add missing ASIMD crypto operations

- FEXCore/unittests/Emitter/ASIMD_Tests.cpp
These issues seem to be resolved now.
> ASIMD_Tests: Re-enable tests disabled due to dissassembly bugs

- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
- FEXCore/Source/Utils/ArchHelpers/Arm64_stubs.cpp
These aren't directly used outside of the translation unit.
> Arm64: Mark several functions as internally linked

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
In regular x86 programs, when a signal occurs, the signal will not be handled within the signal handler. However, under FEX's defer signal mechanism, the signal is not immediately masked when it is deferred. When returning to the location that receives the signal and continues processing, the signal might be received again, causing inconsistency between the emulation and the actual program.
Here is an unit test for this patch from ltp:
https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/timer_settime/timer_settime03.c
> LinuxSyscalls: Update signal mask at deferring time

- CodeEmitter/CodeEmitter/ScalarOps.inl
- FEXCore/unittests/Emitter/Scalar_Tests.cpp
Crosses off two related scalar categories, now the scalar side of things only has 3 TODO's left
> CodeEmitter/ScalarOps: Add two more instruction categories

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.h
Fixes an issue where a thread that exits with the `exit` syscall never actually frees its pivot stack. This is common practice and it was missed when I was fixing the previous stack pivot leak.
This was uncovered when looking at the game
[RUINER](https://store.steampowered.com/agecheck/app/464060/?curator_clanid=4777282) for timing bugs. Turns out the Linux build of the game creates and destroys a VLC object every tick of the engine. Creating this VLC object creates six threads behind the scenes. At what I assume the default tick of the engine is of 120Hz(?) this would mean it is attempting to create and destroy 720 threads per second, quickly leading to memory exhaustion under FEX.
While this hits the biggest memory leak we have around thread creation, this game is still hitting thread …
> LinuxSyscalls: Fixes a major stack memory leak

- CodeEmitter/CodeEmitter/Emitter.h
- FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/MiscOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/include/FEXCore/Core/HostFeatures.h
- Source/Common/HostFeatures.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
Does a few minor things:
- Wires up ECV self-synchronizing timers if supported (Latest ARM devices but not Apple Silicon VMs)
- Use the Self-synchronizing cycle counter to match rdtscp behaviour
- Add an ISB fence to CPUID because some applications use CPUID as a serialization instruction (Because it is) around timing.
- Adds a bogomips calculation to Linux because some applications badly use that for timing, matching Linux behaviour.
Noticed these while trying to track down some timing issues in a game. Didn't solve that game's problem sadly.
> A couple of barrier and timing fixes.

- CodeEmitter/CodeEmitter/ASIMDOps.inl
- FEXCore/unittests/Emitter/ASIMD_Tests.cpp
These are trivial enough to just drop right in.
> CodeEmitter/ASIMDOps: Support RADDHN{2}/RSUBHN{2}

- CodeEmitter/CodeEmitter/LoadstoreOps.inl
- FEXCore/unittests/Emitter/Loadstore_Tests.cpp
Adds all of the memory facilities in FEAT_MOPS to the emitter.
> CodeEmitter/LoadStoreOps: Add Memory Copy and Memory Set category

- Source/Tools/FEXConfig/main.qml
Not sure why I didn't use `anchors.fill: parent` here before, but my testing today found that it's working just fine on Qt 5 / 6.6 / 6.9.
Fixes #4507.
> FEXConfig: Fix layout issues on Qt 6.9

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.h
With the previous stack leak fix, RUINER reduced its memory leaking down to around 50MB/s. The remaining memory leaks come from the pthread stack that we are required to allocate (128KB per thread) and some internal DTV tracking structures.
The problems come in the fact that glibc/pthread only tears down its internal state for these if the pthread function actually returns! We can **technically** switch the initial stack over to a "user" stack but that introduces more problems around internal dtv tracking that we already fixed months ago, so we can't actually do that in practice.
This leaves us no choice, we effectively are mandated to return from the pthread function in order to free the memory from glibc. The only way we can safely do this is with a long jump and deferring some data …
> LinuxEmulation: Fixes remaining memory leak on pthread teardown

- CodeEmitter/CodeEmitter/LoadstoreOps.inl
- FEXCore/unittests/Emitter/Loadstore_Tests.cpp
Eh, what the heck. Gets rid of the last TODO marker in the base load-stores.
> CodeEmitter/LoadstoreOps: Add Load/store register (PAC) group

- FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
Ends exploration earlier when exploring invalid code.
> X86Tables: Set FLAGS_BLOCK_END for more faulting ops

- CodeEmitter/CodeEmitter/ASIMDOps.inl
- CodeEmitter/CodeEmitter/Emitter.h
- CodeEmitter/CodeEmitter/LoadstoreOps.inl
Similar to the X and W contraints, we can have one for the Q and D registers, which makes quite a few require clauses unnecessary or much shorter
> CodeEmitter/ASIMDOps: Constrain Q and D register requirements with concept

- FEXCore/unittests/Emitter/ASIMD_Tests.cpp
vixl now supports these. We can also get rid of the invalid data sizes, since only halfword and 128-bit variants are defined.
> ASIMD_Tests: Enable PMULL/PMULL2 tests

- Scripts/update_instcountci.sh
Previously, the script would silently commit any other local changes as well.
`git add -u :/unittests/InstructionCountCI/*.json` will reliably only add the JSON files (recursively), independently of the current working directory (`:` is a shorthand for the repository root).
> Scripts/InstCountCI: Restrict git-add to relevant JSON files only

- CodeEmitter/CodeEmitter/SystemOps.inl
- FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
- FEXCore/include/FEXCore/Core/HostFeatures.h
- FEXCore/unittests/Emitter/System_Tests.cpp
- Source/Tools/CodeSizeValidation/Main.cpp
- unittests/InstructionCountCI/FlagM/x87-Crysis2Max-fmodel.json
- unittests/InstructionCountCI/FlagM/x87-HalfLife.json
- unittests/InstructionCountCI/FlagM/x87-Oblivion.json
- unittests/InstructionCountCI/FlagM/x87-Psychonauts.json
Due to how jit block tail padding is working, there's no real good way
to determine the true "implementation size" of an instruction without
the backend being aware of wanting to investigate it.
Trying to inject another instruction, or another IR operation actually
subtly changes codegen in a way that gives invalid results. The only
real way to get around this is to inject a known token in to the
instruction stream as we `ExitFunction`.
So inject a `udf #0x420f`, and change the scanning behaviour to find the
first one and cut everything else off afterwards.
This already scoops out some code in some game blocks that were
accidentally landing ExitFunction code in the json.
This also has been tested to work with https://github.com/FEX-Emu/FEX/pull/4528 with its InstCountCI
specific changes …
> InstcountCI: Changes how code size is calculated 

- Dockerfile
Add multi-stage Dockerfile for FEX emulator build
- Stage 1 (Builder): Sets up build environment with Ubuntu 22.04
- Installs development tools and dependencies
- Builds FEX using clang-13 with optimized settings
- Configures cmake with LTO enabled and tests disabled
- Stage 2 (Runner): Creates minimal runtime image
- Includes only necessary runtime libraries
- Copies built binaries from builder stage
> updated Dockerfile to reflect latest FEX-Emu releases

- FEXCore/Source/CMakeLists.txt
The kernelbase import library is not available in upstream mingw-w64. Instead, similar to MSVC, we can use mincore, which allows importing the relevant functions via apisets.
> Link to mincore instead of kernelbase on ARM64EC

- FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
LSE2 platforms give us free (?) atomic 128-bit stores. We can use these to make the block (de-/)linking code apply their patches atomically, which allows blocks to be shared across threads without adding further thread-safety issues.
Credits for this idea go to @Sonicadvance1 .
I think all potential tearing issues are considered, but I'm not fully confident my atomicity/cache behavior assumptions are correct. I've done my best :innocent: 
For context, the unpatched code generally looks like this:
```
0x00000000: ldr x1, +8
0x00000004: blr x1
0x00000008: <address of ExitFunctionLinker>
0x0000000c: <address of ExitFunctionLinker>
0x00000010: <GuestRIP>
0x00000014: <GuestRIP>
```
On LSE2 platforms (as specified at build-time via `-mcpu`), DirectBlockDelinker will compile roughly to the …
> JIT: Make code patching during (un-/)linking thread-safe

- FEXCore/Source/Interface/Core/CPUBackend.cpp
- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/include/FEXCore/Core/SignalDelegator.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.h
protects last page of codebuffer. This should cause a SIGSEGV if we try to access it. Until now it was possible to go over and access out of bounds.
In addition, there a couple of clang-tidy fixes which should be NFC.
> mprotect last page of CodeBuffer

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Utils/variable_length_integer.h
- FEXCore/unittests/APITests/vl_integer.cpp
As said in the implementation of this struct commit message. This new
pair struct optimizes specific cases of small forward only increments
that can fit in to 8-bit space, and small forward or backward jump cases
that fit in to 16-bit space.
Some stats of this change:
- Steam: 5.88MB down to 4.34MB. 73.8% the space consumed
- Steamwebhelper: 15.8MB down to 13.24MB. 83.8% space consumed
- Sonic Mania: 3.6MB down to 2.58MB. 71.6% space consumed
As for absolute stats when compared to all code buffer size:
- Steam: 86MB of code buffer to 5.88MB -> 4.34MB of RIP reconstruction.
- 6.8% -> 5% code buffer space used for RIP reconstruction
- Steamwebhelper: 285MB of code buffer to 17MB -> 14.26MB of RIP reconstruction.
- 5.9% -> 4.9% code buffer space used for RIP reconstruction
- Sonic Mania: …
> FEXCore/JIT: Switch over to new vl64pair for RIP reconstruction 

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
I noticed this cascade of mprotects when poking at Crypt of the Necrodancer, since it consistently is invalidating code. I saw us calling mprotect on the same page 32 times in a tight loop and thought surely this isn't FEX doing this.
Turns out we were calling the callback after invalidating each thread. It should instead be done once at the end of invalidating the thread's caches while still holding the locks.
Fixes this weird cascade of mprotects that equal the number of FEX threads.
> Linux/SMCTracking: Stop calling mprotect on a memory region times the number of threads

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Passthrough.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/FD.cpp
The 32-bit and 64-bit fadvise64 is not the same, the 32-bit version has a high+low offset and a 32-bit len
https://github.com/torvalds/linux/blob/master/arch/x86/kernel/sys_ia32.c#L112
> Fix 32-bit fadvise64

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
Previously, 16 additional bytes were emitted if the buffer was already aligned.
In practice this fix reduces CodeBuffer size by about 0.2%.
> Arm64Emitter: Fix overalignment in Align16B

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
ParentTID is purely a Linux construct and has been moved entirely to the frontend at this point. Remove this argument which is now unused.
NFC
> NFC: FEXCore: Removes unused argument on CreateThread

- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
We don't want this to be compiled out if the definition doesn't exist. Actually define it in that case.
> LinuxEmulation: Fix bad compile time definition check

- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp
With fortifications enabled, glibc long jump has some additional checks in place that break because we do a stack pivot. The only way around this is to do our own long jumps. Luckily this is trivial.
Fixes #4558
> LinuxEmulation: Implement custom longjump that is fortification safe

- Source/Windows/Common/WinAPI/IO.cpp
Libcxx uses GetSystemTimePreciseAsFileTime if _WIN32_WINNT specifies a version new enough to have it.
> Windows: Fix building with llvm-libcxx

- Source/Common/Async.h
- Source/Tools/FEXServer/ProcessPipe.cpp
Previously, we applied a generic timeout to the reactor, which caused FEXServer to exit if clients where still connected but inactive.
Thanks for reporting to @WhatAmISupposedToPutHere.
> FEXServer: Don't time out while clients are still connected

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.h
NFC, just moving this to its own header. It's already a huge PITA to read. I just want to try and preserve some sanity while attempting to fix #4557
> LinuxEmulation: Minor cleanup by separating VMA definitions

- FEXCore/include/FEXCore/Utils/ThreadPoolAllocator.h
Default-constructed iterators can't be copied.
Interestingly, that's the only issue FEX had with `_GLIBCXX_DEBUG`.
> ThreadPoolAllocator: Fix assertion in _GLIBCXX_DEBUG builds

- FEXCore/Source/Interface/Core/Frontend.h
- FEXCore/Source/Interface/IR/IntrusiveIRList.h
- FEXCore/include/FEXCore/Utils/ThreadPoolAllocator.h
This will be used in #4479 to manage temporary buffers for parallel compilation.
> ThreadPoolAllocator: Add support for updating the size of managed data

- Source/Windows/ARM64EC/CMakeLists.txt
- Source/Windows/CMakeLists.txt
- Source/Windows/WOW64/CMakeLists.txt
Avoid hardcoding the file name. Upstream Clang currently expects the aarch64 variant of compiler-rt. Changing this to use arm64ec in the file name could be problematic in the future, if the MinGW toolchain gains support for ARM64X. Querying Clang for the correct file name is the most forward-compatible approach.
> Use -print-libgcc-file-name to get the compiler-rt file name

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
In the near future we'll want to create instructions without knowing what instructions wrote the sources... the dest size inference gets in the way of that. Luckily, it's not load bearing. This PR drops it as a preliminary cleanup.
> IR: drop DestSize inference

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
mov x19, sp
st4 {v8.d-v11.d}[0], [x19], #32
st4 {v12.d-v15.d}[0], [x19], #32
ld4 {v12.d-v15.d}[0], [sp], #32  =>   ld4 {v8.d-v11.d}[0], [sp], #32
ld4 {v8.d-v11.d}[0], [sp], #32   =>   ld4 {v12.d-v15.d}[0], [sp], #32
> Fix callee saved floating-point arguments order issue

- FEXCore/Source/Interface/Core/CPUID.h
This is currently only used on win32 builds because Linux doesn't understand TPIDRRO.
> FEXCore/CPUID: Remove warning

- Source/Common/Async.h
FEXServer's logger performs such self-moves for the log pipe posix_descriptor of short-lived clients. This resulted in a double-close previously, which could interfere with file operations on other threads (typically crashing FEXServer in effect).
> Async: Don't destruct on self-moves

- Source/Tools/FEXLoader/ELFCodeLoader.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Memory.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Semaphore.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Memory.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Syscalls.h
- Source/Tools/LinuxEmulation/VDSO_Emulation.cpp
This has been a bug that we have technically lived with ever since SMC
tracking was introduced. The problem boils down to the fact that memory
management syscalls from multiple threads can race our SMC tracking.
This was only uncovered due to recent changes in the Steam client where
downloading games has more aggressively started reallocating memory.
This causes Steam to oversubscribe the CPU by a small margin, causing
threads to context switch more heavily during memory management.
The strace that finally managed to capture this:
```
41574 munmap(0xba84e000, 724992 <unfinished ...>
<...>
41227 mmap(NULL, 540672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -3, 0 <unfinished ...>
<...>
41574 <... munmap resumed>)             = 0
<...>
41227 <... mmap resumed>)               = …
```
> Linux/SMCTracking: Fixes nasty race condition causing invalid memory tracking

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- FEXCore/Source/Interface/Core/CPUBackend.cpp
- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/Core/LookupCache.cpp
- FEXCore/Source/Interface/Core/LookupCache.h
- FEXCore/include/FEXCore/Core/Context.h
- FEXCore/include/FEXCore/fextl/memory.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
To ease state management, FEX currently dedicates a separate CodeBuffer to each thread for storing the output of JIT binary recompilation. Effectively, this means lots of code must be compiled multiple times, particularly during startup and loadscreens of an application. This PR fixes this by sharing CodeBuffers between threads wherever possible, drastically reducing JIT time and mitigating microstutters (see below for benchmarks).
The broader goal here is that CodeBuffer memory should never be discarded unless strictly necessary, establishing the invariant "every guest block is compiled exactly once". This will also prepare us for effective on-disk code caching (which will further reduce startup times).
> ... partially what now?
This is an [idea from functional …
> Reduce JIT time by 25% by sharing code buffers between threads

- ThunkLibs/GuestLibs/CMakeLists.txt
This is required for clang to find architecture-specific libstdc++ headers as distributed by NixOS.
Verified to also work with Ubuntu. Fedora (using `x86_64-redhat-linux`) should be unaffected too since their packaging scripts where already working around this.
> LibraryForwarding: Change target env to gnu

- ThunkLibs/HostLibs/CMakeLists.txt
This fixes issues in the nix build, where CMAKE_INSTALL_LIBDIR is an absolute path instead of the typical "lib(64)".
> LibraryForwarding: Use CMAKE_INSTALL_FULL_LIBDIR instead of constructing the library install paths manually

- FEXCore/Source/Interface/Config/Config.json.in
Same as #4603. This ensures nix builds will use the correct defaults for ThunkLibs paths.
> Config: Use CMAKE_INSTALL_FULL_LIBDIR when templating default values

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Memory.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Semaphore.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Memory.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Syscalls.h
We can deal with the differences between these much more easily with a dedicated Is64Bit parameter instead of using runtime polymorphism.
Additionally, moving `Get32BitAllocator` to the parent class as a virtual member function makes the 32-bit implementation closer to the 64-bit one.
~~(Marking as draft until we decide whether to merge #4581 first or later.)~~
> LinuxSyscalls: Reduce code duplication between 32-bit and 64-bit paths

- FEXCore/include/FEXCore/Utils/LogManager.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
- Source/Tools/FEXServer/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/Common/Logging.cpp
* Changed "ERROR" strings to single-letters to reduce noise and to ensure message alignment
* Added mild use of colors
* Time stamps:
* Fixed zero-padding for time stamps (previously `0.1234` would be printed when the actual time was `0.000001234`)
* Using milliseconds instead of nanoseconds now, which should be more than sufficient and reduces clutter
* Using time stamps relative to the first log message now
* Process ID and thread ID are separated using `|` instead of `.` to facilitate copy-paste
* Fixed `^C` being printed before the final message when exiting FEXServer running in the foreground
Before:
After:
> Improve log message formatting

- CMakeLists.txt
- Source/Tools/FEXBash/CMakeLists.txt
- Source/Tools/FEXBash/FEXBash.cpp
- Source/Tools/FEXGetConfig/Main.cpp
- include/Config.h.in
Having a dedicated build step just for the install prefix is unnecessarily involved. This information can easily be retrieved otherwise, which also has the upside of not triggering a source rebuild when changing the install prefix.
Furthermore, this cuts down the number of files FEX uses that start with "Config" from 10 to 8 and the number of top-level folders from 16 to 15. Baby steps.
Some functional changes to FEXBash are documented via PR comments.
> Remove code generation build step for install prefix

- Data/nix/FEXLinuxTests/shell.nix
- Data/nix/LibraryForwarding/shell.nix
- Data/nix/WineOnArm/shell.nix
- Data/nix/cmake_configure_woa32.sh
- Data/nix/cmake_configure_woa64.sh
- Data/nix/cmake_enable_flt.sh
- Data/nix/cmake_enable_libfwd.sh
FEX has various subprojects that require cross-compilation with different compilers:
* FEXLinuxTests, requiring 32-bit gcc and 64-bit gcc targeting x86
* Library forwarding, requiring clang targeting x86 (both 32-bit and 64-bit) with a full C++ standard library
* Wine-on-Arm, requiring custom mingw-w64 toolchains
Having to set up a custom toolchain for Wine-on-Arm is merely a minor annoyance. However for the first two points we found that most Linux distributions besides Debian/Ubuntu simply lack the required cross-compilers to reliably enable these features. The situation has improved over time (see #3597 and #4230), however fundamentally the process is still very involved.
**Nix provides a general purpose solution that runs on any distribution.** This PR hence sets up a few convenience …
> Build: Add nix-based helpers to facilitate cross-compilation

- Data/CMake/toolchain_mingw.cmake
Avoids the need for the toolchain to override the system AR.
Should now build with https://github.com/mstorsjo/llvm-mingw/ though there are some windows fixes not in the latest LLVM release (I think SVE etc) - will push a release with that to my repo
> CMake: Set CMAKE_AR for MinGW toolchains

- Data/CMake/toolchain_mingw.cmake
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/CPUBackend.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/Frontend.h
- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/Core/LookupCache.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/PrimaryGroupTables.cpp
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IREmitter.h
- FEXCore/include/FEXCore/HLE/SyscallHandler.h
- FEXCore/include/FEXCore/Utils/IntervalList.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/CommonTools/DummyHandlers.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/Common/InvalidationTracker.cpp
- Source/Windows/Common/InvalidationTracker.h
- Source/Windows/WOW64/Module.cpp
This allows a single JIT call to translate the entire bodies of most functions not using indirect jumps, previously multiblocks would end at calls which often led to regions being translated multiple times as in e.g.:
```
if (a)
do_b()
a = false; // <-- this would be translated twice prior to this if ran with both a=false then a=true
...
```
This paves the way for call-ret optimisations and decreases MB-enabled nodejs startup JIT time by ~8%.
Executable permission tracking is necessary to avoid following a non-taken return location into unmapped memory - this occurs in many unity games.
> Support multiple entrypoints into a multiblock and executable permission tracking

- Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
bus_lock_detect might be interesting to expose if applications ever change behaviour depending on the underlying fault behaviour.
> EmulatedFiles/cpuinfo: Add a few missing flags

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
This actually seems to be the only instance where FEX triggers signed integer over/underflows in normal operation. Changing `-fwrapv` to `-ftrapv` yields a functional FEX build with this patch.
> Arm64Emitter: Fix signed overflow

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Utils/AllocatorOverride.cpp
- FEXCore/include/FEXCore/Utils/LogManager.h
Ensures that `ERROR_AND_DIE_FMT` gets printed with the ASSERT level. Also changed one error message that I hit to be critical, since there's no reliable way to proceed after hitting it.
> Miscellaneous log changes

- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
- Source/Windows/include/winternl.h
Relies on a [https://github.com/bylaws/wine/commit/d41dcbe25dcc707ffd3a110993e480053c5c8a1a](wine-side) patch to expose the prctl to the PE-side
> Windows: Support enabling hardware TSO on Asahi Linux

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/BaseTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/DDDTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/H0F38Tables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/H0F3ATables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/PrimaryGroupTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/SecondaryGroupTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/SecondaryModRMTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/SecondaryTables.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/VEXTables.h
> FEXCore/OpcodeDispatcher: Removes tuple usage for Dispatch tables

- FEXCore/Source/Interface/Core/JIT/JIT.cpp
Go to a whole page of additional padding, #4670 adds some more size to a block and overran the padding causing a unittest to fail.
> JIT: Add more padding

- FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
- Source/Tools/FEXLoader/FEXLoader.cpp
Necessary for #4670 since GCS shouldn't be enabled in the simulator.
Further check in FEXLoader if GCS is enabled since it won't work.
> Disable GCS in simulator and userspace

- Scripts/reformat.sh
The flag and the optional directory helps target the reformatting changes. In any case, this should be backwards compatible. Running it without flags should do what it did before.
> Add --changed flag to reformat.sh script

- FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- unittests/InstructionCountCI/FlagM/Secondary_REP.json
- unittests/InstructionCountCI/FlagM/Secondary_REP_CSSC.json
- unittests/InstructionCountCI/Secondary_REP.json
Now that the PF flag isn't using popcount, this is a win across the board if the hardware supports it.
Been a while since I last looked at this, added a new instcountci file to show the improvement.
> FEXCore: Reintroduce support for CSSC

- unittests/InstructionCountCI/Primary.json
These were actually encoded incorrectly, and I noticed they changed in PR #4670 for some reason. So I dove in to the nasm source to figure out what it takes to encode these sanely rather than with raw bytes, turns out it's fairly trivial, just annoying to track in their parser through iwdq->mem_offset->MEM_OFFS->qword.
Should remove the change in #4670 once it rebases.
> InstcountCI: Fix bad encoded moffset instructions

- CodeEmitter/CodeEmitter/SVEOps.inl
Initially introduced in #4687 as a utility for ASIMD ops, this can be used elsewhere as well to reduce the verbosity of some other assertions.
> SVEOps: Make use of IsStandardFloatSize() more

- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/Frontend.h
- FEXCore/Source/Interface/Core/LookupCache.h
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- Source/Windows/Common/InvalidationTracker.cpp
Prevents invalidations being missed under the following circumstances: Thread A JITs block A into the global codebuffer, adding the guest to host mapping to its CodePages, thread A is then killed. Thread B then performs SMC on block A. An exception will be triggered but as CodePages was stored per-thread, and thread A is now killed when all threads are iterated over by the frontend to perform invalidations it will be missed.
> LookupCache: Move CodePages to GuestToHostMap

- Source/Windows/Common/InvalidationTracker.cpp
This needs to return the base of the non-RWX interval, with a size that when added to the base is the start of the RWX interval.
> InvalidationTracker: Fix queries in the non-intersecting RWX case

- FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
- FEXCore/Source/Utils/ArchHelpers/Arm64_stubs.cpp
- FEXCore/include/FEXCore/Utils/ArchHelpers/Arm64.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
It's being treated like optional, where a value means it has been handled, and no value means it hasn't been handled. Stop using pair in this case.
> ArchHelpers: Remove pair usage in unaligned handler

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/F80Fallbacks.h
- FEXCore/include/FEXCore/Debug/InternalThreadState.h
- FEXCore/include/FEXCore/Utils/Profiler.h
- FEXCore/include/FEXCore/Utils/SHMStats.h
- Source/Common/CMakeLists.txt
- Source/Common/SHMStats.cpp
- Source/Common/SHMStats.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/Common/CMakeLists.txt
- Source/Windows/Common/SHMStats.cpp
- Source/Windows/Common/SHMStats.h
- Source/Windows/WOW64/Module.cpp
This option is free and only enabled if the config option is set. Enable it always at build time so that users can pick it up without enabling the full gpuviz/tracy paths.
> Profiler: Decouple profile stats from the profiler option

- Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
Works the same as ARM64EC/WOW64, recovering the context for SMC insts in non-single-instruction and recompiling them as ones.
Closes #4706
Needs testing in peggle/crysis/denuvo games. Theoretically should work though
> Implement inline SMC handling for linux FEX

- FEXCore/Source/Interface/Core/Frontend.cpp
REX prefix isn't even encoded in to the instruction tables if a 32-bit process is running. Just remove this.
> Frontend: Remove arbitrary check

- CodeEmitter/CodeEmitter/ASIMDOps.inl
In a few categories, we often repeated the base opcode template and then passed it into the implementation function, when we could just situate it in the implementation to begin with. Lets us get rid of a bunch of noise.
Also managed to find a case where we weren't constraining an instruction adequately (uaddlv)
> ASIMDOps: Move base opcode into implementation function for some categories

- FEXCore/Source/Interface/Core/CPUID.cpp
Additional reserved bits have set uses now.
Additionally set the cpuid bit for bus-lock-detect, because FEX definitely detects bus-locks.
> CPUID: Update documentation comments

- CodeEmitter/CodeEmitter/ASIMDOps.inl
We had quite a few instructions that we weren't constraining with this, now the instruction itself will show up in the failure output more immediately instead of failing on the internal implementation function if anything is incorrectly passed through.
> ASIMDOps: Constrain more instructions with IsQOrDRegister

- CodeEmitter/CodeEmitter/ASIMDOps.inl
- CodeEmitter/CodeEmitter/ScalarOps.inl
- FEXCore/unittests/Emitter/ASIMD_Tests.cpp
Now we have all of the base opcodes in ASIMDOps deduplicated.
> ASIMDOps: Move remaining base opcodes into implementing function

- FEXCore/Source/Interface/Core/JIT/AtomicOps.cpp
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
- FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
This is expensive and only needed for spilling, so only do it for spilling. This
complicates the RA a bit but speeds us up on average since most blocks
don't spill. Total results of this change (including the prep commits that
slowed things down temporarily):
Difference at 95.0% confidence
-1.71952% +/- 0.455996%
(This requires us to introduce the notion of kill-bits to replace next-use info for the non-spilling code path)
> RegisterAllocationPass: defer next-use analysis

- FEXCore/Source/Interface/Core/Frontend.cpp
During multiblock code discovery this fires a lot and it isn't interesting. Just remove the log, it'll SIGILL correctly if it actually hits.
> Frontend: Remove log about VEX map_select

- Source/Tools/TestHarnessRunner/TestHarnessRunner/HostRunner.cpp
We were failing to save the entire 64-bit register, cutting off the top 32-bits which contain SS and CS. This ...happened to not cause issues but is a bug that I encountered with far jump handling.
> HostRunner: Fixes bug with saving CSFSGS

- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
When these are set the allocation permissions aren't actually updated. Fixes steam under wine
Closes #4493
> Windows: Ignore MEM_RESET(_UNDO) allocation protection notifications

- unittests/ASM/3DNow/0E.asm
We are onyl wanting to test the FTW, which is 16-bit but we were reading a whole 32-bits. The upper 16-bits was ending up in the reserved section, which is undefined as to what it contains. In FEX it'll contain 0 but on a Zen 4 CPU it contains 0xFFFF.
Only read the bits we care about.
> unittests/3DNow: Fix femms test

- Source/Common/HostFeatures.cpp
This ensures we don't forget about it if bug diagnosis leads nowhere.
> HostFeatures: Fix insufficient documentation to reproduce 3DNow! bug

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/PrimaryGroupTables.h
- FEXCore/Source/Interface/Core/X86Tables/PrimaryGroupTables.cpp
- unittests/ASM/PrimaryGroup/5_FF_05.asm
- unittests/InstructionCountCI/PrimaryGroup.json
If anything actually attempts to use this to change CS then it'll very
quickly hit some other asserts, but it gets one more change off my list.
> OpcodeDispatcher: Implement support for far jump

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator/GuestFramesManagement.cpp
Effectively NFC today while we don't allow installing LDT entries, but is required to have signal handlers execute in the correct bitness if 32-bit code segments are enabled.
Nothing too crazy, just that four segments are stuffed in to the `REG_CSGSFS` data value, and then CS/SS gets restored on restore. FS and GS are ignored in this instance because edge case behaviour where those don't get reset on signal entry, so if they get changed then it is on the userspace application to fix it.
Gets another change out of my stashes.
> LinuxSyscalls: Save and restore segment registers on signal

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/CoreState.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Thread.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
This will allow the frontend to manage LDT and GDT so that Linux will be
able to install 32-bit code segments.
A slight behaviour change on wow64 and arm64ec where threads are now sharing their gdt entries, but because we don't yet support having the guest modify those it should be a non-issue? I need to some testing with arm64ec/wow64 still to ensure this doesn't break things, but this is the probably the scariest change in this series.
> FEXCore: Move LDT/GDT management to the frontend

- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Stubs.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Stubs.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Thread.cpp
This nearly gets FEX's TestHarnessRunner to be self-hosting inside of
FEX. The only thing blocking it currently is that our SBRK emulation
reserves the whole region, when it should be "soft-reserved" and mmap
with MAP_FIXED_NOREPLACE can override it. Plus an assert in
OpcodeDispatcher preventing any 32-bit code from running from a 64-bit
process.
In the most simple terms, gdt and ldt are setup to be unique per thread,
and modify_ldt then modifies that thread's ldt entry. On thread
creation, these values get inherited as a copy.
This allows installation of 32-bit code entries, which with the previous
PRs merged allows the code to attempt jumping to that 32-bit code entry.
It then will immediately explode with an assert in our OpcodeDispatcher.
We can't allow 32-bit code jumping yet until …
> LinuxSyscalls: Support modify_ldt on x64 

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/include/FEXCore/Utils/IntervalList.h
- Source/Common/CMakeLists.txt
- Source/Common/VolatileMetadata.cpp
- Source/Common/VolatileMetadata.h
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/Common/VolatileMetadata.h
- Source/Windows/WOW64/Module.cpp
- unittests/APITests/CMakeLists.txt
- unittests/APITests/ExtendedVolatileMetadata.cpp
Only wired up for wow64 and arm64ec. Gives more granular control over
TSO enabling and disabling. Matches arm64ec volatile metadata except
with one more additional feature that whole modules can be disabled at a
time.
Once we know the mapped size of files in Linux then we'll be able to do
the same thing there, but there's not a full mechanism wired up for that
yet.
> Implement support for additional provided volatile metadata

- Source/Tools/FEXConfig/Main.cpp
The `~/.fex-emu/Config.json` file previously written by FEXConfig breaks muvm-based setups like Fedora Asahi Remix: These setups use a muvm-internal `/usr/share/fex-emu/Config.json` to point the RootFS to `/run/fex-emu/rootfs/`, which a user-local Config.json will override however. Instead, the RootFS entry is omitted from the local Config.json if it's not set now.
This fix isn't ideal:
* It would be better if muvm could apply an overlay *after* loading the local config, not before
* FEXConfig should completely prohibit changing "distributor-provided" settings like these
* Upstream should set up FEXConfig to run in an environment where it can automatically discover the Fedora-provided RootFS. (Running in muvm is not an option currently since it fails to launch FEXConfig)
This change is …
> FEXConfig: Fix RootFS override in muvm-based setups

- Scripts/reformat.sh
This was accidentally changed back to clang-format.py in 3b322d8f375b32f08ea4c5824af4536ba7fde98a.
> Scripts: Fix use of removed helper script

- FEXCore/Scripts/json_ir_generator.py
- Source/Common/CMakeLists.txt
- Source/Tools/FEXLoader/CMakeLists.txt
- Source/Tools/LinuxEmulation/CMakeLists.txt
These used to be required because we leaked IR semantics across the API boundary. Since we no longer do, we can remove the visibility from these.
Other bits also can use hidden visibility.
> Remove visibility on functions that is no longer necessary

- unittests/ASM/Primary/Primary_63_2.asm
nasm doesn't let you encode all of these but we had already supported them in FEX.
It's a bit of a weird edge case behaviour, since it's supposed to be sign extended a 32-bit value in to a 64-bit register but with prefixes (or lack of) it can be a move with zero-extend or a 16-bit insert.
Make sure we're actually testing these edge cases.
> unittests: Adds missing movsxd edge case

- FEXCore/Source/Interface/Core/Interpreter/Fallbacks/F80Fallbacks.h
X80SoftFloat instances already initialize zeroed out in the default constructor.
> F80Fallbacks: Remove unnecessary memset

- FEXCore/Source/Interface/Core/Frontend.cpp
There is no reason for the fall-through case not be explored even if the branch is distance or to an invalid dest
> Frontend: Always explore fallthrough branches with multiblock

- FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/IR/IR.h
- unittests/InstructionCountCI/FlagM/Primary.json
- unittests/InstructionCountCI/Primary.json
The dispatcher/block linker will handle this, but if the instruction following a POPF flag doesn't otherwise trigger one of those the interrupt would be missed.
> OpDispatcher: Force a recheck of TF after POPF

- Source/Common/AsyncNet.h
No need to rely on type punning here; we can just use `alignas` instead.
> AsyncNet: Simplify declaration of ancillary buffer

- CodeEmitter/CodeEmitter/Emitter.h
- CodeEmitter/CodeEmitter/VixlUtils.inl
Gets rid of the need to cart along a clz implementation
> VixlUtils: Use std::countl_zero where applicable

- FEXCore/Source/Interface/Core/CPUBackend.cpp
Noticed when taking a quick look at the CPUBackend code. Ditto for seeing that the moves were possible
> CPUBackend: Remove unused variable in CheckCodeBufferUpdate

- FEXCore/Source/Interface/IR/IRDumper.cpp
This was missing and formatting the values like regular integers
> IRDumper: Add missing PrintArg for IndexNamedVectorConstant

- FEXCore/Scripts/config_generator.py
There were a few cases where more arguments than necessary were being passed to format calls. Not a huge deal, but it is odd to see.
> config_generator: Remove superfluous format arguments

- FEXCore/Source/Common/JitSymbols.h
- FEXCore/include/FEXCore/Utils/LogManager.h
- Source/Common/CPUInfo.h
- Source/Common/Config.cpp
- Source/Common/Config.h
- Source/Common/FDUtils.h
- Source/Common/FEXServerClient.cpp
- Source/Common/FEXServerClient.h
- Source/Common/JSONPool.h
- Source/Common/StringUtil.cpp
- Source/Common/StringUtil.h
- Source/Common/VolatileMetadata.cpp
- Source/Common/VolatileMetadata.h
- Source/Tools/FEXServer/SquashFS.cpp
Just culls a few unused dependencies from the Common utilities (and explicitly specifies some indirect includes)
> Common Utils: Remove unused/unnecessary inclusions from headers

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
ValidateCode didn't work prior to this on arm64ec, I chose to rewrite it and clean things up instead of just fixing the incorrect register usage (w2 vs TMP2)
> Frontend: Fix tailcall handling when mono hacks are enabled

- FEXCore/Source/Utils/Allocator/IntrusiveArenaAllocator.h
- FEXCore/include/FEXCore/Core/CoreState.h
- FEXCore/include/FEXCore/fextl/allocator.h
- FEXCore/include/FEXCore/fextl/functional.h
- FEXCore/include/FEXCore/fextl/memory.h
We can just use the compiler built-in in these cases. std::alignment_of mainly has utility in metaprogramming.
> General: std::alignment_of -> alignof

- FEXCore/include/FEXCore/Core/Thunks.h
- Source/Tools/LinuxEmulation/Thunks.h
Moves the IR include into one of the more specific headers, which avoids dumping the IR header into any core bits that use the interface.
Also uncovered a missing header guard.
> Core/Thunks: Remove unused IR header/forward declarations

- FEXCore/include/FEXCore/Config/Config.h
- Source/Tools/FEXConfig/Main.cpp
- Source/Tools/FEXGetConfig/Main.cpp
- Source/Tools/FEXRootFSFetcher/Main.cpp
- Source/Tools/FEXServer/Main.cpp
Removes quite a heavy unused include from the config system and specifies any indirect inclusion that were relied on because of it.
> Config: Remove unused Context.h include

- FEXCore/Source/Interface/IR/IR.h
- FEXCore/include/FEXCore/IR/IR.h
- Source/Tools/CommonTools/DummyHandlers.h
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls/Thread.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp
Pares the base IR header down to a modest size and also reveals a few indirect reliances on the allocator facilities.
> IR: Remove unnecessary forward declarations/headers

- FEXCore/Source/Utils/FileLoading.cpp
Ensures that the exposed interface is visible to the implementation (i.e. gets rid of some -Wmissing-declaration warnings).
> FileLoading: Add missing self-header

- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/Source/Utils/Allocator.cpp
- FEXCore/Source/Utils/Allocator/HostAllocator.h
- FEXCore/include/FEXCore/Utils/Allocator.h
- FEXCore/include/FEXCore/Utils/ThreadPoolAllocator.h
Reveals some more indirect inclusions.
This just about covers most of the exposed core API
> FEXCore/Allocator: Remove unused headers

- Source/Windows/WOW64/Module.cpp
DEFAULT_USER_CS isn't the default CS segment actually used on wow64
> WOW64: Fix CsSeg initialization

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
> OpcodeDispatcher: Don't assert on invalid ALU op encoding

- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- unittests/ASM/FEX_bugs/X87MMXNZCV.asm
This is not necessary, and breaks any ConvertNZCVToX87 use which relies previously saved NZCV values, as the flag-setting NZCV op after the save could trigger a flush of the saved NZCV.
Fixes a crash in the UPlay installer
> OpcodeDispatcher: Only flush MMX registers on MMX -> x87 transitions

- FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
This takes an f80 as input and returns an f32. A copy-paste error had this truncating the input float if !TMP_ABIARGS. Closes #4856
> Dispatcher: Fix FABI_F32_I16_F80_PTR argument size

- FEXCore/Source/Interface/Config/Config.json.in
- FEXCore/Source/Interface/Context/Context.h
- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/include/FEXCore/Core/Context.h
- Source/Tools/CodeSizeValidation/Main.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
- Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
- Source/Windows/ARM64EC/Module.cpp
- Source/Windows/WOW64/Module.cpp
- unittests/32Bit_ASM/CMakeLists.txt
- unittests/ASM/CMakeLists.txt
Originally added in https://github.com/FEX-Emu/FEX/pull/1752, TSO auto migration is a heuristic to disable TSO emulation until the application creates a second thread. This heuristic doesn't mesh well with code caching (see below), so I'm proposing we remove it entirely.
There are some other reasons why dropping support isn't too bad:
* The general impact of TSO emulation has been greatly reduced since 2022 (see e.g. https://github.com/FEX-Emu/FEX/pull/2760 and https://github.com/FEX-Emu/FEX/pull/3511)
* For specific applications, AppConfigs and TSO heuristics can be a good alternative (#4728, #4825)
* WoA deployments never used TSO auto migration and instead can use volatile metadata (#4378)
* Ever since #4479 was merged, we've been soft-leaking any CodeBuffer memory allocated before TSO …
> Core: Drop support for TSO auto migration

- FEXCore/Source/Interface/Core/JIT/JIT.cpp
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Avoids most cases where an infinite loop could lead to suspend interrupts never getting checked. Conditional jumps and indirect jumps are currently not treated as suspend points due to context reconstruction issues, but this is enough to get ubisoft games launching (they do a jmp +0 infloop, which uplay intercepts).
> JIT: Check for suspend interrupts at back-edges 

- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
This behaves like `UnimplementedOp`, giving a SIGILL if it actually gets hit.
> OpcodeDispatcher: Removes a log about unknown segments

- FEXCore/Source/Interface/Core/Core.cpp
- FEXCore/Source/Interface/Core/Frontend.cpp
- FEXCore/Source/Interface/Core/Frontend.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/BaseTables.h
- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
We were paying a large cost per Literal type that we can special case
for the two class of instructions that use a 64-bit literal.
If we packed this would get to a further 62 bytes but probably not worth it.
Of note, we pay this cost for every instruction we decode, so it adds up very quickly once we are hitting large enough blocks.
> Frontend: Improve DecodeInst size from 128 bytes to 80 

- Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator/GuestFramesManagement.cpp
- unittests/FEXLinuxTests/tests/signal/x87_state.64.cpp
We need to read the current x87 TOP location and rotate the values when
saving and restoring the context state on Linux. Wasn't visible in the
ASM tests since we read the FEX's CPU state directly there.
> SignalDelegator: Correctly save and restore x87 state. 

- CMakeLists.txt
Debian bullseye is a supported build environment which only provides 3.9
> Change required Python version from 3.10 to 3.9

- FEXCore/Source/Interface/Core/JIT/JITClass.h
These don't depend on any class state.
> JITClass: Mark functions as static where applicable

- FEXCore/include/FEXCore/fextl/string.h
This was unintentionally putting all the filesystem utilities into headers implicitly.
> fextl/string: Correct <filesystem> include to <functional>

- FEXCore/Source/Common/StringConv.h
This neglected to use the ::type qualifier, so this candidate was always being considered in overload resolution.
> StringConv: Fix std::enable_if usage

- CodeEmitter/CodeEmitter/SVEOps.inl
- FEXCore/Source/Common/SoftFloat.h
- FEXHeaderUtils/FEXHeaderUtils/BitUtils.h
We already have a few cases where we already use bit_cast in the emitter, so we may as well move all of our temporary helper instances over as well.
> General: Migrate to std::bit_cast

- FEXCore/Scripts/json_ir_generator.py
- FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
- FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
- FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
- FEXCore/Source/Interface/IR/IREmitter.h
- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
- FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp
Instead of having this sort of odd indirection through a struct type, we can add support for defining custom enums in the IR description. This lets us both get strong typing (and allow for weak typing, should any enum in the future need it), without needing a struct for a basic value type.
Even then, if we do need a struct for anything in the future, then we still allow strong typing for values themselves while allowing them to be used in various ways.
> IR: Convert CondClassType over to enum class

- FEXCore/Source/Interface/IR/IR.json
- FEXCore/Source/Interface/IR/IRDumper.cpp
There were a few printers that were missing a few enum values. We can just fills these in so dumped IR is a little more informative
> IRDumper: Add missing enum entries

- Source/Windows/Common/CRT/String.cpp
Included as part of the musl code we pull in. Fixes ARM64EC/WOW64 FEX.
> Windows: Avoid redeclaring strtoll as unimplemented

- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/include/FEXCore/Utils/EnumUtils.h
Handles a normal case where printing an enum type as an integral value is still desirable.
Mainly just a way to reduce boilerplate.
> EnumUtils: Add define for default passthrough formatting

- FEXCore/Source/Interface/Core/JIT/JITClass.h
- FEXCore/Source/Interface/IR/IR.h
This isn't actually used anywhere in the IR header, so we can move it to where it's actually used.
Now the IR interface header doesn't have anything related to the independent passes in it.
> IR: Move RegisterAllocationPass forward decl to JITClass

- FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
Just a small thing I noticed (alongside minor tidying changes)
> RedundantFlagCalculationElimination: Eliminate unnecessary vector copy

- FEXCore/Source/Interface/Core/CPUBackend.cpp
- FEXCore/Source/Utils/Allocator.cpp
- FEXCore/Source/Utils/PrctlUtils.h
Will allow external tools to track how much memory FEX allocates. Necessary since we can't use traditional memory usage tools to track FEX memory allocation independently of guest allocations. Plus most tools like heaptrack hook allocation symbols, which break under jemalloc.
Using this information I can see with Steam loaded with my library that FEX consumes ~825MB. Total process resident memory is 1204M, accounting for around 379MB being used by steam itself. This is /relatively/ close to my desktop running steam at around 261MB. There's a bit of variance due to what Steam chooses to do at startup.
This tracking will be the first step towards seeing where our memory usage is going.
> Allocator: Name FEX's VMA regions for allocation

- FEXCore/Source/Interface/Core/X86Tables/X86Tables.h
- FEXCore/Source/Interface/IR/IR.h
- FEXCore/include/FEXCore/Utils/EnumUtils.h
Turns out a simpler way was added to the docs at some point and I never noticed.
Before:
```
text     data      bss      dec      hex  filename
4159895  1471360  4336824  9968079   9819cf  Bin/FEX
```
After:
```
text     data      bss      dec      hex  filename
4157159  1471360  4336824  9965343   980f1f  Bin/FEX
```
> EnumUtils: Further simplify enum passthrough formatting
