External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h

Unittest to ensure this keeps working is forthcoming.

Fixes PUSH with register encoded in op

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/Primary/Primary_AA.asm
unittests/ASM/Primary/Primary_AA_REP.asm
unittests/ASM/Primary/Primary_AA_REP_down.asm
unittests/ASM/Primary/Primary_AB_dword.asm
unittests/ASM/Primary/Primary_AB_dword_REP.asm
unittests/ASM/Primary/Primary_AB_dword_REP_down.asm
unittests/ASM/Primary/Primary_AB_qword.asm
unittests/ASM/Primary/Primary_AB_qword_REP.asm
unittests/ASM/Primary/Primary_AB_qword_REP_down.asm
unittests/ASM/Primary/Primary_AB_word.asm
unittests/ASM/Primary/Primary_AB_word_REP.asm
unittests/ASM/Primary/Primary_AB_word_REP_down.asm

Also implements support for STOS without a REP prefix.

Adds unit tests for the STOS instruction family

---

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp

Fixes a bunch of unit tests.
Still about 26 tests to fix though.

Various fixes for the x86 JIT

---

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp

Fixes AArch64 LLVM intrinsic typo

---

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/Secondary/08_66_04_2.asm
unittests/ASM/Secondary/08_F2_04_2.asm
unittests/ASM/Secondary/08_F3_04_2.asm
unittests/ASM/Secondary/08_XX_04_2.asm
unittests/ASM/Secondary/08_XX_05_2.asm
unittests/ASM/Secondary/08_XX_06_2.asm
unittests/ASM/Secondary/08_XX_07_2.asm

This was just some missing coverage of the BT ops that exposed a minor bug in the x86 JIT and implementation detail was incorrect.

Unit tests and fixes for BT ops with GPR destination

---

.github/workflows/ccpp.yml

This ensures all unit tests are ran every PR and merge

Adds ctest step to the CI

---

External/FEXCore/Source/Interface/HLE/Syscalls.cpp

futex command 9 is actually WAIT_BITSET, not WAKE_BITSET
Implements futexes with timeouts as well, necessary for anything using
std::condition_variable and wait_for/wait_until

Fixes a couple bugs in the futex syscall

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
unittests/ASM/OpSize/66_51.asm
unittests/ASM/TwoByte/0F_51.asm
unittests/ASM/TwoByte/0F_52.asm

Was missing unit tests on a couple of these and saw sqrtps in testing apps

Fixes for SQRTPD, SQRTPS, RSQRTPS

---

External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/include/FEXCore/Core/CodeLoader.h
Source/Common/ArgumentLoader.cpp
Source/Common/ArgumentLoader.h
Source/Tests/ELFLoader.cpp
Source/Tests/HarnessHelpers.h
Source/Tests/LockstepRunner.cpp
Source/Tools/Debugger/Main.cpp

This is necessary for execve in the future to keep everything in sync

Plumbs ELFLoader arguments through the CodeLoader

---

External/FEXCore/Source/Interface/HLE/FileManagement.cpp
External/FEXCore/Source/Interface/HLE/FileManagement.h
External/FEXCore/Source/Interface/HLE/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/Syscalls.h

Futex needs to be looked at seriously soon to see if we can just pass it
directly

Implements more syscalls that I found while running applications

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
unittests/ASM/OpSize/66_E6.asm
unittests/ASM/REP/F3_2C.asm
unittests/ASM/REP/F3_2D.asm

Implements two more CVT instructions

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/IR/IR.json

vector pairwise add
vector unsigned shift right with narrowing
vector unsigned and signed extend with lengthening from upper bits
vector unsigned and signed multiply with lengthening from upper bits

Adds new IR ops

---

External/SonicUtils/Source/ELFLoader.cpp
External/SonicUtils/Source/ELFSymbolDatabase.cpp
External/SonicUtils/include/SonicUtils/ELFLoader.h
Source/Tests/ELFLoader.cpp
Source/Tests/HarnessHelpers.h
Source/Tests/LockstepRunner.cpp
Source/Tools/Debugger/Main.cpp

Fixes #69, makes it less annoying to run things on non x86 hosts

Adds RootFS search path in ELFLoader

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/REP/F3_5B.asm

<s>Needs a unit test still</s>

Implements CVTTPS2DQ x86 instruction

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
External/FEXCore/Source/Interface/IR/IR.json
External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.h
unittests/ASM/OpSize/66_2E.asm
unittests/ASM/OpSize/66_2F.asm

Fixes some fairly major bugs in float comparison ops that could cause undefined data getting dumped in to guest GPRs and floating point results not getting stored correctly.

Float comparison bug fixes

---

External/FEXCore/Source/Interface/HLE/Syscalls/Memory.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Memory.h
External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x64/Syscalls.h

Implements the mlock syscalls

---

External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp

The VFORK flag lets clone behaviour similarly to a fork.
The parent will be suspended until the resulting thread is exited

Fixes clone syscall when VFORK flag is used

---

External/FEXCore/Source/Interface/Core/Core.cpp

This is something that TSAN caught was happening.
Grabs the thread creation mutex when checking for idle and extends the
sleep time for WaitForIdle to something that is still below unit test
run time

Fixes a race condition in WaitForIdle

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
unittests/ASM/H0F38/0_F0.asm
unittests/ASM/H0F38/0_F1.asm

This is pretty easy to implement. Kind of flies in the face of why the
instruction implementation exists (icache and frontend issue overhead
savings) but it is easy to implement.

Implements MOVBE

---

External/FEXCore/Source/Interface/HLE/FileManagement.cpp

Was only stubbed before, easy enough to pass it through

Implements the open syscall

---

External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/FD.h
External/FEXCore/Source/Interface/HLE/Syscalls/Sched.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Sched.h
External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Thread.h
External/FEXCore/Source/Interface/HLE/Syscalls/Time.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Time.h
External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x64/Syscalls.h

Found these while running games and having upgraded from glibc 2.30 to
2.31

Implements 9 new syscalls

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
unittests/ASM/Primary/Primary_9B.asm

Since we don't yet support instruction exceptions this is nothing but a nop.

Implements fwait as a nop

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/IR/IR.json
unittests/ASM/OpSize/66_7C.asm
unittests/ASM/OpSize/66_7D.asm
unittests/ASM/REPNE/F2_7C.asm
unittests/ASM/REPNE/F2_7D.asm

haddps, hsubps, haddpd, hsubpd

Implements four new vector horizontal ALU ops 

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
unittests/ASM/Primary/Primary_E0.asm
unittests/ASM/Primary/Primary_E1.asm
unittests/ASM/Primary/Primary_E2.asm

Implements support for the three loop instructions

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
unittests/ASM/TwoByte/0F_2A.asm
unittests/ASM/TwoByte/0F_2C.asm
unittests/ASM/TwoByte/0F_2D.asm

CVTPI2PS does MMX->XMM integer to float conversion with lower 64bit insert
CVTPS2PI/CVTTPS2PI does an XMM->XMM float to integer conversion

Implements three XMM <-> MMX conversion instructions

---

External/FEXCore/Source/Interface/Core/Frontend.cpp

Optimization passes found a bug in the frontend regarding constants.
Specifically in the case of instructions that have a 32bit constant that
are sign extended to 64bit was being incorrectly set to have a size of
32bits (the size of the constant).
So an optimization pass would rematerialize constants of the expected
size, thus ~0ULL would turn in to ~0U and generate invalid code.
Now watch the destination size and set the constant to that size, which
matches what its size will be.

Fixes a bug in the frontend regarding constants

---

External/FEXCore/Source/Interface/Config/Config.cpp
External/FEXCore/Source/Interface/Context/Context.cpp
External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables.cpp
External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
External/FEXCore/Source/Interface/HLE/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/Syscalls.h
External/FEXCore/include/FEXCore/Config/Config.h
External/FEXCore/include/FEXCore/Core/Context.h
External/FEXCore/include/FEXCore/Debug/X86Tables.h
External/SonicUtils/Source/ELFLoader.cpp
External/SonicUtils/include/SonicUtils/ELFLoader.h
Source/Tests/ELFLoader.cpp
Source/Tests/HarnessHelpers.h
Source/Tests/TestHarnessRunner.cpp
Source/Tests/UnitTestGenerator.cpp

This is about 2500 lines to bring up initial support so I'm splitting it between multiple pull requests to make it more easy to digest.
This is the initial code that allows the ELF loader to load an ELF, and passes the running mode through to FEXCore.
Further implementations will be coming up after this PR is merged.

Initial 32bit support

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/HLE/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x32/FD.cpp
External/FEXCore/Source/Interface/HLE/x32/FD.h
External/FEXCore/Source/Interface/HLE/x32/Memory.cpp
External/FEXCore/Source/Interface/HLE/x32/Memory.h
External/FEXCore/Source/Interface/HLE/x32/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x32/Syscalls.h
External/FEXCore/Source/Interface/HLE/x32/Thread.cpp
External/FEXCore/Source/Interface/HLE/x32/Thread.h
External/FEXCore/include/FEXCore/Core/CoreState.h

This adds the initial 32bit syscalls for testing. No where near complete

Implements initial 32bit syscall support 

---

External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp

AArch64 redefines these four flags so they don't match between
architectures.
This is what was actually causing ls to fail, the x86 side was passing
in O_DIRECTORY which the AArch64 side was interpreting at O_DIRECT.
This made it return EINVAL

Fixes FD flags mismatch between x86 and ARM64

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

Adds a couple of assets in the other repeat instructions.
Jump targets were accidently inverted.
SCAS and LODS are the two repeat instructions we don't have unit tests
for.
Unit tests are forthcoming for this

Fixes SCAS

---

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp

Noticed these when doing x87 testing.

Minor memory allocation optimizations in the IR passes.

---

Source/Common/Config.cpp

In the case of multiple dozens of tests running, they will end up
loading and saving the config files dozens of times.
This was causing the configuration system to load in half saved files
that were causing common crashes in the posix unit tests.
Theoretically this could have happened at any time but it looks like
with the posix unit tests added, it is just more likely to happen.
Makes it so loading the configuration file is much more robust and
verbose on failure.
Makes it so saving the config file first saves to a temporary and then
moves in to the correct location. This causes the config saving to be
atomic in a sense so the unit tests won't corrupt other processes of FEX
trying to load the config file.

Fixes crashes in unit tests

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
External/FEXCore/Source/Interface/IR/IR.json
External/FEXCore/include/FEXCore/IR/IREmitter.h
unittests/ASM/OpSize/66_F6.asm
unittests/ASM/TwoByte/0F_F6.asm

Saw this when running Freedreno on x86-64

Implements psadbw for MMX and SSE2

---

External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/FD.h
External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x64/Syscalls.h

syscalls/x64: Add pselect6

---

External/FEXCore/Source/Interface/HLE/Syscalls/FS.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/FS.h
External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x64/Syscalls.h

syscalls/x64: Add fchdir

---

External/FEXCore/Source/Interface/Config/Config.cpp
External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/HLE/EmulatedFiles/EmulatedFiles.cpp
External/FEXCore/Source/Interface/HLE/EmulatedFiles/EmulatedFiles.h
External/FEXCore/Source/Interface/HLE/Syscalls/Sched.cpp
External/FEXCore/include/FEXCore/Config/Config.h
Source/Common/ArgumentLoader.cpp
Source/Common/EnvironmentLoader.cpp
Source/Tests/ELFLoader.cpp

This is just a virtual number that the guest can query through the
various means. Will affect mesa with how many helper threads it
generates at the very least

Adds new FEX config for telling the guest how many CPU cores it can have

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/OpSize/66_5B.asm

This must of have been a copy and paste error, I didn't even have this
instruction on my list of implemented instructions.
It definitely isn't converting to a GPR

 Fixes cvtps2dq instruction

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

Pretty basic for the most part, just changes default operating mode for
most everything from 64bit to 32bit.

Supports 32bit operating mode in the OpDispatcher

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp

These can only be implemented as acquire/release exclusive loops on
ARMv8.0 so they end up looking pretty disgusting.
This is more for compatibility for testing than anything. I'm not
expecting ANY ARMv8.0 device to get decent performance.
I'll be buying an ARMv8.0 device that can live in CI for ensuring these stay working.
That will be wired up once it arrives.

Implements atomic ops for ARMv8.0 devices

---

External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/FS.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Stubs.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp
External/FEXCore/Source/Interface/HLE/x64/Syscalls.h

truncate,creat,chown,fchown,lchown,setpgid,getpgid,setfsuid,setfsgid,getsid,sync,syncfs
*get/setxattr

syscalls: Implement a few easy ones

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
External/FEXCore/Source/Interface/Core/SignalDelegator.h
External/FEXCore/Source/Interface/HLE/Syscalls/Signals.cpp

Allows us to register host and guest signal delegators.
Currently only host signals are handled, guest signal delegation will
take a bit of work still.

Adds new signal delegator class

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp

Just some minor things that are really too small to fit in to a PR each.

Minor fixes

---

Dockerfile

Added basic Dockerfile configuration for use as a base image, allowing the use of FEX within Docker.

Adds Dockerfile configuration for use as a base image

---

.github/workflows/ccpp.yml
Scripts/posix_test_runner.py
unittests/POSIX/CMakeLists.txt

This ensures we can run on ARMv8.2, ARMv8.0 and X64

Adds new ARMv8.0 runner tag

---

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp

Looks like this optimisation was deleted during a refactor. 
On my 3900x with irjit -n500, this speeds up the FTL resource preload from 48.285 seconds to 24.169. A 100% speedup.
--------
The inner loop of FTLs png loader is a single block:
```asm
6f0190:       44 0f b6 04 1a          movzx  r8d,BYTE PTR [rdx+rbx*1]
6f0195:       48 83 c2 01             add    rdx,0x1
6f0199:       0f b6 3c 1e             movzx  edi,BYTE PTR [rsi+rbx*1]
6f019d:       44 0f b6 5a ff          movzx  r11d,BYTE PTR [rdx-0x1]
6f01a2:       41 89 f9                mov    r9d,edi
6f01a5:       45 89 da                mov    r10d,r11d
6f01a8:       45 29 c1                sub    r9d,r8d
6f01ab:       45 29 c2                sub    r10d,r8d
6f01ae:       45 89 cc                mov    r12d,r9d
6f01b1:       44 89 …
```

DCSE: Fix flag store elimination optimisation

---

Source/Common/ArgumentLoader.cpp
Source/Common/EnvironmentLoader.cpp
Source/Tests/ELFLoader.cpp

Not interfering with things using terminal GUIs is important.
Add an option that allows us to redirect output to a file

Adds a new option for directing where debug logs go

---

Source/Common/Config.cpp

I set -w on the config file while testing, so this log message is just
being annoying

Removes a debug log

---

CMakeLists.txt

This makes it easier to not forget to use this

Automatically enables ccache if the program is found

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h

This gives us two more volatile registers to play with

Removes usage of vixl's MacroAssembler

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp

When RA made the source address register be the same register as the
destination register then we could have overwritten the address with the
move.
Use a temporary until we get RA constraints in place.

Fixes a potential crash in ARM64's AtomicSwap

---

CMakeLists.txt
ThunkLibs/GuestLibs/CMakeLists.txt

This allows you to specify a custom x86 compiler though cmake

GuestLibs: Allow configuring compiler via cmake

---

.gitignore
Scripts/json_config_parse.py
Source/Tests/HarnessHelpers.h
Source/Tests/IRLoader.cpp
Source/Tests/IRLoader/Loader.h
unittests/ASM/CMakeLists.txt
unittests/ASM/MemoryData.asm
unittests/Example.asm
unittests/IR/Basic/MemoryData.ir
unittests/IR/CMakeLists.txt

Also... hook up memory regions.

Add support for pre-populated MemoryData to IR and ASM Tests

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

InstallToX87Table: Fix segfault in debug assert

---

External/FEXCore/Source/Interface/HLE/Syscalls/Sched.cpp

Last fix was still buggy. Should be good now...

Syscalls: Actually fix sched_getaffinity

---

.github/workflows/ccpp.yml
CMakeLists.txt
External/FEXCore/Source/Interface/IR/PassManager.cpp
External/FEXCore/Source/Interface/IR/PassManager.h
External/SonicUtils/include/SonicUtils/LogManager.h

Will slow down the CI process a bit, but it is better to catch the
assertions

Enables assertions on the buildbot

---

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp

Due to the way RCLSE is implemented, it improves the IR but misses some cases. This will run it up to 5 times. For some reason, running it twice is not good enough.

IR: Iterative RCLSE

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/IR/PassManager.cpp
External/FEXCore/Source/Interface/IR/Passes.h
External/FEXCore/Source/Interface/IR/Passes/DeadFlagStoreElimination.cpp

Mutlblock pass that eliminates flag stores that are never read.
This is a sibling to RCLSE and will likely be absorbed by it when we add MB support there.

IR: Add DeadFlagStoreElimination

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
unittests/32Bit_ASM/CMakeLists.txt
unittests/32Bit_ASM/Primary/Primary_00.asm
unittests/32Bit_ASM/Primary/Primary_00_2.asm
unittests/32Bit_ASM/Primary/Primary_00_3.asm
unittests/CMakeLists.txt

This is a very small change, but it gets us starting to test 32bit

Adds initial 32bit unit tests 

---

External/FEXCore/Source/Interface/Core/SignalDelegator.cpp

We only have 64, this is invalid!

Don't allow an application to try and set a signal past 64

---

External/FEXCore/Source/Interface/HLE/Syscalls.cpp

Not sure if anything is mapped after 0xd000'0000 in our shm, limiting this to the map size.
Needed for CS:GO and others to work, reduces heap corruption errors, so I assume we're overflowing somewhere?
malloc will keep using `brk` til `ENOMEM`. Then it switches to `mmap`.

Syscalls/BRK: Don't use more memory than mapped

---

External/FEXCore/Source/Interface/IR/IREmitter.cpp
External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
External/FEXCore/include/FEXCore/IR/IREmitter.h

* Provide a fast path for "Replace with Constant"
* Early exit optimisation for ReplaceAllUses. Stop when all uses have been found.
Depends on #365 
Ignore everything except the last two commits.

Replace improvements

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/IR/IR.json
unittests/ASM/PrimaryGroup/5_FF_00_3.asm
unittests/ASM/PrimaryGroup/5_FF_01_3.asm

Depends on #365. Only last few commits are relevant.

Remove unneeded BFEs around flag generation code.

---

External/FEXCore/Source/Interface/Context/Context.cpp
External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
External/FEXCore/Source/Interface/Core/SignalDelegator.h
External/FEXCore/include/FEXCore/Core/Context.h
External/FEXCore/include/FEXCore/Core/SignalDelegator.h

This will come to be useful for our host code execution and wine in the
future

Adds ability for the frontend to register a signal handler

---

Source/Common/ArgumentLoader.cpp
Source/Common/EnvironmentLoader.cpp
Source/CommonCore/CMakeLists.txt
Source/CommonCore/HostFactory.cpp
Source/CommonCore/VMFactory.h
Source/Tests/TestHarnessRunner.cpp

Implements x86 host runner

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/Primary/Primary_A6.asm
unittests/ASM/Primary/Primary_A6_REP.asm
unittests/ASM/Primary/Primary_A6_REP_Smaller.asm
unittests/ASM/Primary/Primary_A6_REP_down.asm
unittests/ASM/Primary/Primary_A6_down.asm
unittests/ASM/Primary/Primary_A7_dword.asm
unittests/ASM/Primary/Primary_A7_dword_down.asm
unittests/ASM/Primary/Primary_A7_qword.asm
unittests/ASM/Primary/Primary_A7_qword_down.asm
unittests/ASM/Primary/Primary_A7_word.asm
unittests/ASM/Primary/Primary_A7_word_down.asm

The order of these ops were flipped
These were confirmed by host runner

Fixes flags calculation in CMPSB 

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Common/SoftFloat-3e/extF80_to_ui64.c
External/FEXCore/Source/Common/SoftFloat-3e/s_roundToUI64.c
External/FEXCore/Source/Common/SoftFloat-3e/ui64_to_extF80.c
External/FEXCore/Source/Common/SoftFloat.h
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/IR/IR.json

Adds support for BCD x87 intructions

---

Scripts/testharness_runner.py
unittests/32Bit_ASM/CMakeLists.txt
unittests/ASM/CMakeLists.txt
unittests/ASM/Disabled_Tests_host
unittests/IR/CMakeLists.txt

Disables the thunking unit test on host because obviously it won't work
there

Adds and enables the x86 host runner when building on x86 host!

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
External/FEXCore/include/FEXCore/IR/IREmitter.h
unittests/ASM/H0F3A/0_66_0F.asm
unittests/ASM/H0F3A/0_XX_0F.asm

Fixes a couple of bugs in our palignr implementation as well.

Implements MMX register based palignr

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
External/FEXCore/Source/Interface/IR/IR.json
External/FEXCore/include/FEXCore/IR/IREmitter.h
unittests/ASM/H0F38/66_00.asm
unittests/ASM/H0F38/XX_00.asm

Both the MMX and XMM variants
Confirmed unit tests with the host runner

Implements PSHUFB

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
External/FEXCore/Source/Interface/IR/IR.json
unittests/ASM/H0F38/66_0B.asm
unittests/ASM/H0F38/XX_0B.asm

Both the MMX and XMM variants.

Implements SSSE3 PMULHRSW

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/PrimaryGroup/2_D3_07_2.asm

Need to operate on it as a 32bit value or higher

Fixes smaller than 32bit ASHR

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/PrimaryGroup/3_F6_04.asm
unittests/ASM/PrimaryGroup/3_F7_04.asm

32bit wasn't zexting correctly

Fixes unsigned multiply zext mechanics 

---

External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Source/Tests/HarnessHelpers.h
unittests/ASM/H0F38/66_00_2.asm
unittests/ASM/H0F38/XX_00_2.asm
unittests/ASM/OpSize/66_2B.asm
unittests/ASM/OpSize/66_F6.asm
unittests/ASM/REP/F3_BD_2.asm
unittests/ASM/REP/F3_BD_3.asm
unittests/ASM/REP/F3_BD_4.asm

Most of their failures come from rounding mode bugs, but it did catch some real instruction failures

Fixes from Valgrind's test suite

---

External/SonicUtils/Source/ELFSymbolDatabase.cpp

Doesn't really matter but let's put it there

Updates ELFSymbolDatabase for 32bit library paths

---

Source/Tests/HarnessHelpers.h

Matches most of the 64bit behaviour but with expected 32bit pointers

Adds support for 32bit ELFs to the code loader

---

External/FEXCore/Source/Interface/Core/Core.cpp

Unnecessary when executing in 32bit since glibc will set up the TLS

Only sets up FS on 64bit

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/IO.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Info.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Memory.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Msg.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Sched.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Socket.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Thread.h
External/FEXCore/Source/Interface/HLE/Syscalls/Time.cpp
External/FEXCore/Source/Interface/HLE/x32/FS.cpp
External/FEXCore/Source/Interface/HLE/x32/Info.cpp
External/FEXCore/Source/Interface/HLE/x32/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x32/Thread.cpp
External/FEXCore/Source/Interface/HLE/x32/Thread.h
External/FEXCore/Source/Interface/HLE/x64/FD.cpp
External/FEXCore/Source/Interface/HLE/x64/IO.cpp
External/FEXCore/Source/Interface/HLE/x64/Info.cpp
External/FEXCore/Source/Interface/HLE/x64/Ioctl.cpp
External/FEXCore/Source/Interface/HLE/x64/Memory.cpp
External/FEXCore/Source/Interface/HLE/x64/Msg.cpp
External/FEXCore/Source/Interface/HLE/x64/Sched.cpp
External/FEXCore/Source/Interface/HLE/x64/Socket.cpp
External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp
External/FEXCore/Source/Interface/HLE/x64/Thread.cpp
External/FEXCore/Source/Interface/HLE/x64/Thread.h
External/FEXCore/Source/Interface/HLE/x64/Time.cpp

Shuffles more x86-64 specific syscalls to the correct folder

---

External/SonicUtils/Source/ELFSymbolDatabase.cpp
External/SonicUtils/include/SonicUtils/ELFLoader.h
Source/Tests/HarnessHelpers.h

This requires some changes to how the ELF memory bases are calculated
and which auxp variables are passed in

Fixes 32bit ELF Loading

---

External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp
External/FEXCore/Source/Interface/HLE/x64/FD.cpp

32bit ppoll is completely wrong here.
Will be fixed in upcoming PR

Fixes 64bit ppoll

---

External/SonicUtils/CMakeLists.txt

Removes installing since it doens't make sense anymore

Switches SonicUtils over to be a static library

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp

- Added 4, 8, 16 FPR and removed 16 from GPR
- Asserts in non-supported cases (PAIR, others?)

Fill/SpillRegister: Spill based on register class

---

External/FEXCore/Source/Interface/IR/Passes/DeadCodeElimination.cpp

Looks like by accident DCE was converted to a forward loop from backward as a result of #365 
@Sonicadvance1 maybe we should merge this after #455 as a test?
@phire this looks good? I didn't see a reverse iterator introduced w/ #365 -- how hard is it to add `GetReverseBlocks()` or such?

DCE: Needs reverse iteration to be effective

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

Much faster this way, because of the block-local nature of most of our optimizations

Dynamic Shifts: use Selects instead of branches for flags

---

External/FEXCore/Source/Interface/Config/Config.cpp
External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/include/FEXCore/Config/Config.h
Source/Common/ArgumentLoader.cpp
Source/Common/EnvironmentLoader.cpp
Source/Tests/ELFLoader.cpp

This dumps the IR before and after optimizations
--dump-ir can be
"no" -> Do not dump
"stderr" -> Dump to stderr
"stdout" -> Dump to stdout
"some/path" -> Dump to "some/path/$GuestRip-pre.ir" and "some/path/$GuestRip-post.ir"

IR: Add DumpIR option, --dump-ir command line

---

External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp

This fixes bogus RA when live ranges aren't contiguous, at the cost of excessively increased register pressure.
This doesn't fix multi-block spilling, which requires fully working PHI nodes among other things. As a workaround these ranges are marked as unspillable.
Gets heavily triggered by #489, but can (and does) happen in regular code gen.

RA: Greedily extend live ranges when values are used out of defining block

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/IR/PassManager.cpp
External/FEXCore/Source/Interface/IR/Passes.h
External/FEXCore/Source/Interface/IR/Passes/DeadGPRStoreElimination.cpp

This is based on the Flag Elimination pass, and is not optimal - but does eliminate quite a few dead stores.

IR: Add DeadGPRStoreElimination

---

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp

- Handles some FPR cases that were for some reason disabled. A few are left disabled because they break stuff and need further investigation.
- Also handles some other corner cases
- VMOV zext/trunc seem to no longer be causing issues, enabled

RCLSE improvements

---

Source/Tests/ELFLoader.cpp

If a file has as shebang interpreter then switch over to that.
Fixes launching a bunch of titles in Steam where their launcher is a
bash script

Adds support for shebang redirection

---

External/FEXCore/Source/Interface/HLE/EmulatedFiles/EmulatedFiles.cpp

Some application was using this to determine CPU count as well

Captures another CPU count file

---

External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/JITCore.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h

These take different paths depending on if it was for a compile thread
or not
Doesn't yet push the code for the compile service itself.

Adds support for the CPUBackends to run in a compile thread 

---

ThunkLibs/GuestLibs/CMakeLists.txt
ThunkLibs/HostLibs/CMakeLists.txt

Generation folder wasn't getting created with make while ninja was being helpful and creating the folders for us.

Fixes thunk generation with make

---

Source/Tests/ELFLoader.cpp

If we are passed a shebang application then append the rootfs prefix for
absolute paths.
Fixes the issue where bash scripts weren't working on ARM.
Also fixes a crash that can occur if FEX wasn't passed in arguments
or if the argument passed in didn't exist.
It'll now instead exit cleanly and state that the application doesn't
exist respectively.

Shebang rootfs prefix improvements

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/GdbServer.cpp
External/FEXCore/Source/Interface/Core/GdbServer.h

Fix start paused and add a hacky segfault signal handling.

GdbServer fixes

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/include/FEXCore/Core/CodeLoader.h
External/SonicUtils/Source/ELFLoader.cpp
External/SonicUtils/Source/ELFSymbolDatabase.cpp
External/SonicUtils/include/SonicUtils/ELFLoader.h
External/SonicUtils/include/SonicUtils/ELFSymbolDatabase.h
Source/Tests/HarnessHelpers.h

This is no longer necessary now that phire fixed mapping of static elfs

Removes dead TLS setting code

---

External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp
External/FEXCore/Source/Interface/HLE/x64/FD.cpp

These end up being different for x32 so move them now

Moves the getdents implementations for x64

---

External/FEXCore/Source/Interface/HLE/Syscalls/Memory.cpp
External/FEXCore/Source/Interface/HLE/x64/Memory.cpp

These will need to be unique for 32bit

Moves some memory op implementations to x64 file

---

External/FEXCore/Source/Interface/HLE/Syscalls/Signals.cpp
External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp
External/FEXCore/Source/Interface/HLE/x64/Thread.cpp

These need specific 32bit handling

Moves 64bit sigaltstack and execve to 64bit files

---

External/FEXCore/Source/Interface/IR/PassManager.cpp
External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp

Removes unused flags from OP_FCMPs

ConstProp: FCMP Optimization

---

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp

If imms used in memops are close enough, generate them with address gen instead
of allocating a new const

ConstProp: LoadMem/StoreMem imm pooling

---

Source/Tools/CMakeLists.txt
Source/Tools/FEXConfig/CMakeLists.txt
Source/Tools/FEXConfig/Main.cpp

Adds a new UI application for setting config options

---

External/FEXCore/Source/Interface/HLE/Syscalls.h
External/FEXCore/Source/Interface/HLE/x32/Thread.cpp
External/FEXCore/Source/Interface/HLE/x64/Thread.cpp
External/FEXCore/include/FEXCore/Config/Config.h
Source/Common/ArgumentLoader.cpp
Source/Tests/CMakeLists.txt
Source/Tests/ELFLoader.cpp

All three commits are important, fixes a few things I saw when running games.

More robust FEXInterpreter checks

---

CMakeLists.txt
External/FEXCore/Source/Common/BitSet.h
External/FEXCore/Source/Interface/IR/IREmitter.cpp
External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
External/FEXCore/include/FEXCore/IR/IR.h
Source/Tests/ELFLoader.cpp

Turns out the past few PRs broke ASAN cleanliness and had a few other warnings.
Fix that.

Fixes I found when running ASAN

---

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
unittests/ASM/Primary/Primary_84_2.asm

Hotfix: Disable ConstProp/RemoveUselessMasking, add a test for it

---

Source/Tests/ELFLoader.cpp

Fixes a problem where a space between the shebang and application
argument would result in us trying to execute a null program.
Additionally it now captures all the arguments passed in the shebang
header rather than just the application and first argument.

Shebang improvements

---

CMakeLists.txt
Source/Tools/CMakeLists.txt
Source/Tools/Debugger/CMakeLists.txt

This is currently broken and going to be broken more soon

Disables visual debugger by default

---

Source/Tests/LinuxSyscalls/FileManagement.cpp
Source/Tests/LinuxSyscalls/FileManagement.h
Source/Tests/LinuxSyscalls/x32/FD.cpp
Source/Tests/LinuxSyscalls/x64/FD.cpp

Fixes Vulkan loader searching for vulkan json ICD files

Captures fsstatat in filesystem overlay

---

External/FEXCore/Source/Utils/ELFLoader.cpp

This is the same thing as the 64bit side

Makes sure to not calculate zero sized program headers on 32bit

---

External/FEXCore/Source/Common/JitSymbols.cpp
External/FEXCore/Source/Common/JitSymbols.h
External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp

Will let us see in perf how much time is spent there

Allows JITSymbols to see central dispatcher

---

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
unittests/ASM/ConstProp/ConstPooling.asm

This seems to hit some bug on RA, so blocked til @phire has that fix merged

ConstProp: Allocate constants once per block

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

Created #556 to track the missed optimization

OpDisp: Remove missed debug printf

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/include/FEXCore/IR/IREmitter.h

Some MB calculations are still wrong, See #702 and #703

OpDisp: Address most 32-bit rip size issues

---

Dockerfile
Readme.md
Source/Tests/CMakeLists.txt

We don't require this
Fixes #699

Removes all references to Boost

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp

This isn't quite optimal without RA constraints

Implements VBSL on AArch64

---

Source/Tests/LinuxSyscalls/x32/FD.cpp

If you have the COMPAT feature enabled then this just works there.
AArch64 not implemented currently since changes aren't upstream

Implements ioctl32 for x86-64

---

.github/workflows/ccpp.yml

This was an oversight of the original commit

Always upload artifact results even on failure

---

CMakeLists.txt

Adds python version check

---

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp

Fix the number of physical cpus reported

---

External/FEXCore/Source/Interface/Core/Core.cpp

This works around the issue of us stopping threads that are in stopping state, by only sending the stop signals to non-stopped threads.
Resolves the std::terminate called recursively issue in many multi threaded apps, and also allows for clean shutdown for --aotir-capture

Threading: Workaround exit_group bug

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/Secondary/08_XX_05_3_Atomic.asm
unittests/ASM/Secondary/08_XX_05_Atomic.asm
unittests/ASM/Secondary/08_XX_06_3_Atomic.asm
unittests/ASM/Secondary/08_XX_06_Atomic.asm
unittests/ASM/Secondary/08_XX_07_3_Atomic.asm
unittests/ASM/Secondary/08_XX_07_Atomic.asm
unittests/ASM/TwoByte/0F_AB_2_Atomic.asm
unittests/ASM/TwoByte/0F_AB_Atomic.asm
unittests/ASM/TwoByte/0F_B3_2_Atomic.asm
unittests/ASM/TwoByte/0F_B3_Atomic.asm
unittests/ASM/TwoByte/0F_BB_2_Atomic.asm
unittests/ASM/TwoByte/0F_BB_Atomic.asm

BTS specifically is being used for threading related tasks. Which could
be why our threading has been unstable.

Implements BTC, BTR, BTS atomic variants

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

This fixes at least one bug in pthreads, and possibly other things

OpDisp: Add atomic logic for SecondaryALUOp

---

Source/Tests/LinuxSyscalls/SignalDelegator.cpp

Verified against the kernel source
Fixes CMAKE lockups, and closes #683

Signals: SA_NOCLDSTOP only blocks CLD_CONTINUED/STOPPED/TRAPPED

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/TwoByte/0F_B0_11.asm

The comparison was using the wrong values which means this cmpxchg would fail

Fixes an edge case of 32bit cmpxchg <reg>, <reg>

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/Primary/Primary_10_3.asm
unittests/ASM/Primary/Primary_10_4.asm
unittests/ASM/Primary/Primary_18_3.asm
unittests/ASM/Primary/Primary_18_4.asm
unittests/ASM/PrimaryGroup/1_80_02_2.asm
unittests/ASM/PrimaryGroup/1_80_03_2.asm
unittests/ASM/PrimaryGroup/1_81_02_2.asm
unittests/ASM/PrimaryGroup/1_81_03_2.asm
unittests/ASM/PrimaryGroup/1_83_02_2.asm
unittests/ASM/PrimaryGroup/1_83_03_2.asm

These were fairly straightforward

Adds support for locked ADC and SBB

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/ASM/PrimaryGroup/3_F6_02_2.asm
unittests/ASM/PrimaryGroup/3_F7_02_2.asm

Adds support for locked NOT

---

Source/Tests/CMakeLists.txt

Otherwise it doesn't feel like FEXInterpreter is installing

Adds an installer message to the FEXInterpreter install

---

Source/Common/ArgumentLoader.cpp
Source/Common/CMakeLists.txt

Nicer for the user to determine what their version is

Implements a --version argument

---

Readme.md

Some of this taken from Stef's recent changes. Some taken from the wiki.
combination of the two best bits
Fixes #868

Updates readme with some more direct information

---

External/FEXCore/Source/Utils/ELFLoader.cpp

Ubuntu's x86_64 rootfs does a soft link from `/lib64/ld-linux-x86-64.so.2` to an absolute path of `/lib/x86_64-linux-gnu/ld-2.32.so`
Our frontend ELF loader logic would resolve this symlink to be just `/lib/x86_64-linux-gnu/ld-2.32.so` which would then fail.
Adds some additional logic to our frontend that if the symlink ends up being a softlink to an absolute address then it'll first resolve that symlink.
Then combines rootfs + absolute path. If that still fails then it'll fall down the regular linker path, which could still find the linker on the host side.
This is all a bit of a kludge to just work around Ubuntu doing an absolute address rather than a relative one.
Fixes #869

Adds some additional logic for finding absolute soft linked linker

---

Source/Common/ArgumentLoader.cpp
unittests/32Bit_ASM/CMakeLists.txt
unittests/ASM/CMakeLists.txt
unittests/IR/CMakeLists.txt
unittests/POSIX/CMakeLists.txt
unittests/gcc-target-tests-32/CMakeLists.txt
unittests/gcc-target-tests-64/CMakeLists.txt
unittests/gvisor-tests/CMakeLists.txt

We need these for our CI artifacts
Fixes #900

Disables silent logging on unit tests 

---

Readme.md
Source/Tools/FEXConfig/CMakeLists.txt
Source/Tools/FEXConfig/Main.cpp

Sometimes GLFW3 can just consume a full CPU core, spinning on nothing.
Fixes #906

Replaces FEXConfig usage of GLFW with SDL2 

---

External/FEXCore/Source/Utils/ELFLoader.cpp
External/FEXCore/Source/Utils/ELFSymbolDatabase.cpp
External/FEXCore/include/FEXCore/Utils/ELFLoader.h
Source/Common/Config.cpp
Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
Source/Tests/LinuxSyscalls/Syscalls.cpp
Source/Tests/LinuxSyscalls/Syscalls.h
Source/Tests/LinuxSyscalls/Syscalls/Stubs.cpp
Source/Tests/LinuxSyscalls/x32/Thread.cpp
Source/Tests/LinuxSyscalls/x64/Thread.cpp
unittests/gvisor-tests/Disabled_Tests

Fix execve again

---

Source/Tools/FEXConfig/Main.cpp

Provides a drop down dialog of RootFS folders to select.
Will be empty if the user doesn't have any folders in place.
Just allowing directory paths to be inserted
Relies on #916 being merged first
Relies on #923 being merged first
Fixes #689

Adds support for Named RootFS folders in FEXConfig

---

External/FEXCore/Scripts/config_generator.py
External/FEXCore/Source/Interface/Config/Config.json

Also makes the script check for duplicate entries to ensure it doesn't happen again.

Fixes Thunk Guest libs short arg. C&P error made it not be j

---

Source/Tools/FEXConfig/Main.cpp

Fixes some crashes and some minor feature improvements

FEXConfig improvements

---

External/FEXCore/include/FEXCore/Core/CodeLoader.h
Source/Tests/HarnessHelpers.h
Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp

In case an application checks this

Fixes wrapping cmdline arguments

---

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp

This lets Carrion get farther in game.
Seems like one of its threads hits sigsegv and it just...lets it die after checking siginfo?

Implements a minimal siginfo_t in the dispatcher's signal handler

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
External/FEXCore/Source/Interface/IR/IR.json

Useful for debugging, supports both vector and GPR

Adds support for Arm64 JIT to Print

---

unittests/POSIX/Disabled_Tests
unittests/POSIX/Known_Failures

The behaviour of these is broken but now they are documented in how they are broken
Fixes #198

Updates a couple POSIX test case failures

---

External/FEXCore/Source/Interface/Core/JIT/x86_64/AtomicOps.cpp

Fixes Factorio 1.1.30 on x86-64 hosts
Fixes #957

Fixes Zext semantics on atomic ops with x64 JIT

---

Scripts/generate_release.sh

Wasn't actually creating an annotated tag with this order

Fixes ordering problem of tag generation in release script

---

External/FEXCore/Source/Interface/Core/CPUID.cpp
External/FEXCore/Source/Interface/Core/CPUID.h

Noticed a game poking at these

Adds some more CPUID functions

---

.github/workflows/ccpp.yml
Source/Tests/ELFLoader.cpp

Relies on #950 getting merged first
Fixes #714

Enables GCC 32-bit unit tests

---

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
unittests/gvisor-tests/Known_Failures

Fixes OpenAt breaking with anonymous objects

---

External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
External/FEXCore/Source/Interface/Core/LookupCache.h

Measurably reduces startup delay

LookupCache: Add new entries to L1C

---

.github/workflows/ccpp.yml

Requires #990 and #993 to be merged first

Enables ARMv8.4 CI runner 

---

Source/Tests/LinuxSyscalls/x32/Socket.cpp

Rebased and cleaned up #933
Needs to be larger allocations than what was originally proposed by #933

Workaround fixes in sendmsg/recvmsg

---

Source/Tests/LinuxSyscalls/Syscalls.cpp

Fixes a step in the Java JRE and shapez.io

Redirect applications using execve with self

---

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
External/FEXCore/Source/Interface/Core/CPUID.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/IR/IR.json
unittests/ASM/Secondary/15_XX_7_2.asm

Implements support for CLFLUSH 

---

Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp

Fixes evdev device description at the very least

Fixes ioctl returning error

---

Source/Tools/FEXConfig/Main.cpp

Inverted this check on accident

FEXConfig: Fixes INotify watcher never coming up

---

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp

cpuinfo needs to have tabs on options rather than whitespace.
and the arguments file needs a final null argument to be correct.

Fix two EmuFD issues

---

Source/Tests/LinuxSyscalls/x64/Memory.cpp

If we are on AArch64 then MAP_32BIT doesn't exist.
Emulate it by setting the address as a hint to the kernel so it scans bottom up

Emulate MAP_32BIT in mmap

---

Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp

Until we properly wrap this we can't support it

Disable userfaultfd until supported

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
unittests/ASM/H0F3A/0_66_21.asm

Cheap Golf is using this instruction unconditionally.
With this implemented the game now runs

Implements SSE4.1 insertps

---

Source/Tools/FEXConfig/Main.cpp

Automatically fall back through older GL versions
This allows us to freely support GL 3.0, 2.1 and ES 2.0.
Should fix an issue where Pi devices don't support GL 3.0 in all configs
External imgui had to be updated to fix an issue with ES 2.0
Fixes #1036

FEXConfig: Allow lower GL versions

---

Source/Tests/LinuxSyscalls/x32/Semaphore.cpp
Source/Tests/LinuxSyscalls/x32/Types.h

There were some problems in both of these implementations.
Fixes #744
Fixes #745

Fixes semctl and msgctl

---

Source/Tests/LinuxSyscalls/x32/EPoll.cpp
Source/Tests/LinuxSyscalls/x64/EPoll.cpp

Similar to #1064, an application could potentially pass in bad values that could result in assertions/exceptions being thrown, so we can guard against that.
Despite the Linux man pages saying that applications *must* not pass `maxevents` less than or equal to zero, against all odds, this is still a handled case in the kernel, so some application out there may rely on this behavior.

{x32, x64}/EPoll: Prevent edge-case out-of-bounds access scenarios

---

Source/Tests/LinuxSyscalls/x32/FD.cpp

The read/writev family of syscalls are defined as taking in an array, so we can construct the `std::vector` in place instead of initializing and then copying.
This also fixes an edge case where an out of bounds access on the `Host_iovec` vectors could occur if these syscalls were called with an `iovcnt` of zero (`.at()` would cause an exception to be thrown). Looking into the syscalls for `readv` and `writev` in the kernel, these just return early if a size of zero is passed in.
~~Should we also be handling the scenario where a program decides to choose chaos and passes a negative `iovcnt`? In both variants of the code, this would result in assertions/exceptions from our code.~~ Handled it anyway

x32/FD: Construct vectors in place

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/IR/IRParser.cpp
External/FEXCore/include/FEXCore/IR/IR.h
Source/Tests/IRLoader/Loader.cpp

Makes a few little cleanups that don't deserve their own separate PR.

IRParser: Minor cleanup

---

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp

If a 32-bit application leaves a temporary file dangling from one of the EmulatedFiles
then glibc tries to clean up the FILE object on shutdown.
This results in a crash on 32-bit applications because our memory allocator will have already cleaned up
at that point
Use raw FDs in this instance which matches better with the syscall hooking expecting raw FDs anyway.

Fixes a crash in 32-bit applications with tmpfile

---

Source/Tests/LinuxSyscalls/FileManagement.cpp
Source/Tests/LinuxSyscalls/FileManagement.h

Just a few minor changes that reduces the overhead surrounding the maps a little bit.

FileManager: Minor changes

---

External/FEXCore/Source/Utils/Allocator.cpp
External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
External/FEXCore/Source/Utils/Allocator/HostAllocator.h

Communicates the ownership intent in the interface.

HostAllocator: Make Create64BitAllocator() return a unique_ptr 

---

Dockerfile
Readme.md
Source/Tests/LinuxSyscalls/CMakeLists.txt

We don't need libnuma, stop trying to link to it

Removes more libnuma references

---

External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp

Transparent huge pages is a feature that the linux kernel opportunistically uses.
Depending on kernel configuration this feature is either enabled always, or when you madvise the region.
To ensure we hit both cases, madvise the regions we allocate in the 64-bit VMA allocator always
Can reduce kernel bookkeeping memory usage for our abusive allocator

Enables transparent huge pages in our 64-bit VA allocator

---

Source/Tools/FEXConfig/Main.cpp

Accidentally deleted the period on this

Fixes typo on extension check for squashfs

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

While we're in the area, we can use an alias to prevent duplicated array types, and also add a static assert to ensure the arrays are always the same size. This allows us to avoid needing to bounds check several accesses in a row that we know will always be successful.

OpcodeDispatcher: Make GPR indices in SyscallOp constexpr

---

External/FEXCore/Source/Interface/Core/Core.cpp

This doesn't seem to be hooked up to anything.

Core: Remove unused DefaultFallbackCore

---

Source/Tests/LinuxSyscalls/x32/Thread.cpp

Currently our 32-bit code only gave one TLS slot and crashed
if you needed more.
First switch over to the same initial slot as the Linux kernel.
Then allow searching the slots for a free spot.
This allows us to more closely match the behaviour of the Linux kernel just in case
anything has hardcoded the TLS slots
This makes it so Saints Row: The Third stops crashing at boot, plays a few intro videos, then hangs instead.

Fixes a 32-bit processes wanting another TLS space

---

Source/Tests/LinuxSyscalls/x32/EPoll.cpp

This custom definition was missing

Fixes debug strace output

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

This is necessary for wine and some wine-like emulation layers.
With this implemented then some Saint's Row games start running.
Fixes #1100

Implements 32-bit iret instruction

---

Source/Tests/LinuxSyscalls/x32/Thread.cpp

Fairly straightforward to implement.

x32/Thread: Implement setfsuid32/setfsgid32

---

Source/Tests/LinuxSyscalls/x32/Time.cpp

Also fixes an edge case in the 32-bit implementation of utimensat

x32/Time: Implement utimes

---

Source/Tests/LinuxSyscalls/Syscalls/SHM.cpp
Source/Tests/LinuxSyscalls/Syscalls/Socket.cpp
Source/Tests/LinuxSyscalls/x32/Memory.cpp
Source/Tests/LinuxSyscalls/x32/Socket.cpp
Source/Tests/LinuxSyscalls/x64/Memory.cpp
Source/Tests/LinuxSyscalls/x64/Socket.cpp

Didn't resolve steamwebhelper performance on AArch64 sadly.

x32: Fixes shmdt, sendmsg, recvmsg syscalls

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

Given these arguments are template arguments, we can use if constexpr with these branches to guarantee their elision.

OpcodeDispatcher: Make use of if constexpr

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.h
Source/Tests/LinuxSyscalls/SignalDelegator.cpp
Source/Tests/LinuxSyscalls/SignalDelegator.h
Source/Tests/LinuxSyscalls/Syscalls.cpp

We're now tsan and asan clean again with the default configuration.

Fixes some issues I found when running under tsan and asan

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
External/FEXCore/include/FEXCore/Core/CoreState.h
External/FEXCore/include/FEXCore/Core/UContext.h
unittests/ASM/X87/FXAM_Push.asm
unittests/ASM/X87/FXAM_Push_2.asm

Wine fixes around x87 FTW and basic signal handling.
This is enough to get some 32-bit wine games running.

Wine fixes

---

Source/Tests/LinuxSyscalls/FileManagement.cpp

Similar code to readlinkat. Needs to be correct for self otherwise we
return EINVAL which is unexpected since self should always be a symlink
Fixes a bug in running bwrap

Linux: Fixes readlinkat for self

---

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp

Probably preferable for readability.

FEXCore: Use GetCursorAddress when able

---

Source/Common/RootFSSetup.cpp
Source/Common/RootFSSetup.h
Source/Tools/CMakeLists.txt
Source/Tools/FEXGetConfig/CMakeLists.txt
Source/Tools/FEXGetConfig/Main.cpp

This is a simple program to get a few configuration options that are necessary
to expose for pressure-vessel

Adds new FEXGetConfig program

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/32Bit_ASM/Primary/Primary_8C.asm
unittests/32Bit_ASM/Primary/Primary_8C_2.asm
unittests/32Bit_ASM/Secondary/15_XX_0.asm
unittests/ASM/Secondary/15_XX_0.asm

Fixes a crash that 32-bit proton 6.3 applications were hitting.
Now hangs when run under pressure-vessel for whatever reason, but works when freestanding. Very curious.

Proton 6.3 32-bit fixes

---

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp

We were checking the PC after we set the new location in the data
structure.
Didn't matter for x86-64 since it doesn't use SRA but it does matter for
ARM.
Now on signal while in JIT code it will spill correctly

Arm64: Fixes SRA spilling on signal

---

Source/Tests/FEXLoader.cpp

Comment in the file for why this can be a bug.
Noticed a game opening a file and our logs were ending up in their
files.

FEXLoader: Fixes potential bug in log output to stdout/stderr

---

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h

Arm64Emitter: Resolves some IWYU warnings

---

Source/Tests/LinuxSyscalls/Syscalls.cpp

If the binfmt_misc interpreter was installed then we were running execve
directly.
This allowed shebang programs to escape and see the host architecture
when we weren't planning on it.
Fixes `FEXBash steam` from complaining about missing packages.

Linux: Fixes accidental execve escape

---

Source/Tests/FEXBash.cpp

If not passing in any arguments then just immediately create a bash
instance. Incredibly nice little helper

FEXBash: Allow creating a bash instance easily

---

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp

Fixes lscpu and other applications that open the directory first and
then files inside of that directory.

EmulatedFiles: Fixes openat for emulated files not using FDCWD

---

Source/Tools/FEXConfig/Main.cpp

Loading a preexisting application config was impossible through the gui.
Adds a way to do so.
Also adds an advanced tab that just displays all the items.
Allows pruning of application config options to be fairly efficient

FEXConfig: Load application config and advanced tab

---

External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
External/FEXCore/include/FEXCore/Utils/BucketList.h

I'm doing this to make RegisterAllocationPass.cpp slightly smaller and easier to understand

Move BucketList into it's own file

---

External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp

The chance of hitting this is near zero, but still safer to have an assert.

RA: Add max NoteCount assert

---

Source/Tools/FEXMountDaemon/Main.cpp

Now that we deparent FEXMountDaemon we can no longer use
PR_SET_PDEATHSIG.
Instead we rely on the ref counting and checking the pipe status to see
if the original parent has left us.
Further improvements that could be done in the future is that every user
of the mount point talks to the daemon to give it a pipe to check is
still live, since the ref counting sometimes is incorrect.

FEXMountDaemon: Fixes some minor issues

---

External/FEXCore/Source/Interface/Core/ArchHelpers/MContext.h
Source/Tests/LinuxSyscalls/SignalDelegator.cpp

Due to how we emulate the guest signal handlers, we do the state setup
in the real host signal handler, then we jump out after state setup.
This was causing a situation where we were setting up the guest signal
handler state with the correct sa_mask.
Then after setting up the guest state we would leave the FEX signal
handler, restoring the signal mask to our original mask.
Instead now as we are setting up the guest state, we save our host
signal mask. Then on signal handler return we modify our host signal
mask to match what the guest wants.
Once we hit our sigreturn emulation we then restore the original signal
mask.
This looks to improve some stability problems regarding how wine uses
signals but it still doesn't fix the gvisor test sadly.

Linux: Setup signal mask correctly to block signal-in-signal situations

---

External/FEXCore/Source/Common/SoftFloat.h

This is useful for testing the ops that are emulated using different
precision.
Haven't found anything that changes behaviour but useful to keep around

Softfloat: Allow forcing use of some x87 on x86 host

---

Source/Tests/LinuxSyscalls/Syscalls/Time.cpp
Source/Tests/LinuxSyscalls/x32/Time.cpp
Source/Tests/LinuxSyscalls/x32/Types.h
Source/Tests/LinuxSyscalls/x64/Time.cpp

Linux: Fixes timex definition for 32-bit syscalls

---

Source/Tests/LinuxSyscalls/FileManagement.cpp

There was a hard upper limit to 128 json elements, this has now been
removed.
The debugging text for the thunk overlay is now disabled. It can get
very spammy but it is useful for debugging purposes.
Fixes an issue where thunks would be entirely disabled if a RootFS isn't
set.
This meant debugging in a chroot or x86_64 host was breaking rootfs

Thunks: Minor fixes to the config and loading

---

Scripts/DefinitionExtract.py

This is very useful for extracting function definitions for thunks.
Keep it in upstream to not get lost.
Sometimes it can munge a definition but it is usually fine.

Scripts: Adds a new script for extracting function definitions

---

External/FEXCore/Source/Interface/Config/Config.cpp
External/FEXCore/Source/Interface/Config/Config.json.in
Source/Tests/FEXLoader.cpp
Source/Tools/FEXConfig/Main.cpp

This can be useful for edge case environment variable setting

Adds support for setting host environment variables from config

---

External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp

This will change slightly in the future. Clean this up and document.

Core: Minor documentation and code splitting

---

ThunkLibs/Generators/ThunkHelpers.py

Allows having a library filename be different from the name.
This will fix a quirk in future thunks where the library name and
filename don't match
Also allow custom callback unpacks. A future thunk will need this

Thunks: ThunkHelpers script improvements

---

ThunkLibs/libX11/libX11_Guest.cpp
ThunkLibs/libX11/libX11_Host.cpp
ThunkLibs/libXfixes/libXfixes_Guest.cpp
ThunkLibs/libXrender/libXrender_Guest.cpp

Makes it print to stderr instead of stdout.
Also sets the mutex symbols to something that can be debugged.
Found something linking to them but not actually using them.

Thunks: Some minor X related thunk changes

---

External/FEXCore/Scripts/config_generator.py
External/FEXCore/Source/Interface/Config/Config.cpp
External/FEXCore/include/FEXCore/Config/Config.h
Source/Common/ArgumentLoader.cpp
Source/Tests/FEXLoader.cpp

Fixes #1334
Fixes the issue of `FEX_CORE=irjit` not working.

Fixes environment loader not hooked up to ArgumentLoader

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/VEX/sarx.asm
unittests/ASM/VEX/shlx.asm
unittests/ASM/VEX/shrx.asm

Gets the basic BMI2 shifts out of the way and progress on BMI2 on the road

OpcodeDispatcher: Implement BMI2 SARX/SHLX/SHRX

---

External/FEXCore/Source/Interface/Core/CPUID.cpp
External/FEXCore/Source/Interface/Core/Frontend.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
unittests/ASM/H0F38/adcx.asm
unittests/ASM/H0F38/adox.asm

Another CPU extension we can cross off the list.
Addresses #1355

OpcodeDecoder: Add support for ADX

---

Source/Tests/ELFCodeLoader2.h

With a DYN ELF in most cases the first program header will be at offset
0.
This isn't always true though, in the case of `micro` the first program
header is at a 4MB offset.
This was causing us to miscalculate the size of ELF in memory, which was
causing BRK to intersect with the ELF on allocation.
This would cause ELF loading to fail and then us to close in some cases.
Also makes sure to pass -1 as FD in mmap with anonymous to match.

ELFCodeLoader: Fixes BRK allocation on some ELF loading

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/VEX/rorx.asm

Adds handling for BMI2's RORX instruction

OpcodeDispatcher: Handle RORX

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp

OpcodeDispatcher: Resolve sign mismatches in loops

---

External/FEXCore/Source/Interface/Core/Frontend.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/VEX/mulx.asm

Now with all the other instructions out of the way, we have the fun ones left to implement (PDEP and PEXT)

OpcodeDispatcher: Implement MULX

---

Source/Tests/CMakeLists.txt
Source/Tests/ELFCodeLoader2.h
Source/Tests/FEXLoader.cpp
Source/Tests/HarnessHelpers.h
Source/Tests/IRLoader.cpp

A set of changes that were initially just going to be the first commit, but snowballed into what it is now. Mainly gets all the testing stuff off the older logger among other things

Tests: Minor cleanup

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/VEX/bzhi.asm

Implements support for BMI2's BZHI instruction

OpcodeDispatcher: Implement BZHI

---

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp

Only the interpreter requires this currently since the stack register
doesn't match.
The JITs correctly set up their stack register and matches what the API
wants.
This is guaranteed to work. signal + rt_sigreturn is a handshake with
the kernel to return the data that the kernel wants.
Only time this doesn't align is when the guest signal handler longjumps
out of the signal handler. Which leaves a dangling entry in the
SignalFrame stack on the interpreter.

Dispatcher: Removes usage of SignalFrame stack on JITs

---

ThunkLibs/Generators/ThunkHelpers.py
ThunkLibs/Generators/libxcb.py
ThunkLibs/HostLibs/CMakeLists.txt
ThunkLibs/include/common/CrossArchEvent.h
ThunkLibs/libvulkan_device/Guest.cpp
ThunkLibs/libvulkan_device/Host.cpp
ThunkLibs/libxcb/libxcb_Guest.cpp

Factored out from #1295 as these apply to the old generator too.

Various thunk library cleanups

---

Data/ThunksDB.json

We were missing installed things in /usr/local, Update the DB to include
those.
Fixes the Ender Lilies vulkan thunk hang that I was encountering

ThunksDB: Updates file to include local libs

---

Source/Tests/LinuxSyscalls/SignalDelegator.cpp

If set and oldset point to the same location. We need to be careful to
store the old mask before returning it. Otherwise we will will store the
current mask over the new mask and not change anything.

Linux: Fixes sigprocmask with new and old set being the same address

---

External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp

When compiling code and linking blocks, disable all signals then
reenable once back in the dispatcher.
This adds 15-40 microseconds on to each of these steps and some
additional branching overhead.
This is a problem where our allocator is not reentrant safe and when
receiving a signal we need to jump to a new code region and compile.
Depending on the mutexes that are currently live, we will just stall out
forever.
This is /very/ commonly picked up when attempting to run pressure-vessel

Arm64: Reduce the chance of hanging on reentrant allocations

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
External/FEXCore/Source/Interface/Core/GdbServer.cpp
External/FEXCore/Source/Interface/Core/GdbServer.h
External/FEXCore/include/FEXCore/Debug/InternalThreadState.h

Enough to get a backtrace sometimes but otherwise still pretty finicky.

GDBStub: Fixes a few hangs and crashes 

---

Source/Tests/LinuxSyscalls/Syscalls/Sched.cpp

Noticed an issue where some applications were thinking that applications
were running on a system with 512 CPU cores.
Specifically freedreno/turnip was trying to create 512 worker threads
which would cause my ARM devices to run out of memory.
Looks like sysconf behaviour has changed around this where it is
actually expecting the uint64_t alignment that the Linux kernel does.
So follow that behaviour as well and resolve the issue.

Linux: Fixes sched_getaffinity

---

External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/Config/Config.json.in
External/FEXCore/Source/Interface/Core/GdbServer.cpp
External/FEXCore/Source/Utils/NetStream.cpp
External/FEXCore/include/FEXCore/Utils/NetStream.h
Source/Common/CMakeLists.txt
Source/Common/SocketLogging.cpp
Source/Common/SocketLogging.h
Source/Tests/FEXLoader.cpp
Source/Tools/CMakeLists.txt
Source/Tools/CommonGUI/IMGui.h
Source/Tools/FEXConfig/Main.cpp
Source/Tools/FEXLogServer/CMakeLists.txt
Source/Tools/FEXLogServer/Main.cpp

Fixes #1263 
Allows us to pass all FEX logs to a socket.
Gives us a terminal UI or GUI depending on what you want to use

Adds Socket logger and tool

---

External/FEXCore/Source/Interface/Core/CPUID.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
External/FEXCore/Source/Interface/Core/Interpreter/MiscOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/X86Tables/SecondaryModRMTables.cpp
External/FEXCore/Source/Interface/IR/IR.json
unittests/32Bit_ASM/SecondaryModRM/Reg_7_1.asm
unittests/ASM/SecondaryModRM/Reg_7_1.asm

Implements RDTSCP

---

Source/Tests/LinuxSyscalls/x64/Syscalls.cpp

Syscalls on x86-64 have a gap in the range of [335, 424) where these are
defined as returning ENOSYS.
This was a decision that the Linux developers decided on so x86-64 can
realign its syscall numbers to a common infrastructure.
Turns out that Proton Experimental was using a 32-bit only syscall to
check if the feature existed and was listening for ENOSYS.
They did this unconditionally on both x86 and x86-64 and it hits this
gap section.
This was introduced in Proton Experimental with commit
563fb0fbe2a49734aede87bedccb20daefc553b0
Message: "ntdll: Use clock_gettime64 if supported."
This is technically valid since it falls within this gap section but
leaves a bad taste.
We can safely ignore this section so set it up with the
UnimplementedSyscallSafe handler and also assign it to Syscall …

Linux: Adds the safe syscall unimplemented gap for x86-64

---

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp

Still only setting the new state if RIP is affected for now.
Noticed a bug where we weren't setting our frame RIP to the new RIP on
32-bit.
Decided to walk through more of the state setting while fixing that.
This gets #1214 further but then it eventually crashes with a read to
0x11.

Dispatcher: Adds more state reconstruction to state restore

---

Source/Tests/AOT/AOTGenerator.cpp
Source/Tests/AOT/AOTGenerator.h
Source/Tests/CMakeLists.txt
Source/Tests/ELFCodeLoader2.h
Source/Tests/FEXLoader.cpp
Source/Tools/FEXConfig/Main.cpp

Only a minor fix in the ELFCodeLoader here, and FEXConfig addition of the options.
Otherwise just code movement.

More AOT code movement

---

Source/Tests/LinuxSyscalls/x64/Types.h

Wasn't quite the expected definition.
Fixes #1450

Linux: Fixes semid_ds_64 definition

---

Source/Tests/LinuxSyscalls/x32/Types.h

Linux: Fixes build on Ubuntu 20.04

---

CMakeLists.txt
External/FEXCore/Source/Interface/Core/CPUID.cpp
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp
External/FEXCore/Source/Interface/Core/Interpreter/MiscOps.cpp
External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
External/FEXCore/Source/Interface/Core/X86HelperGen.cpp
External/FEXCore/Source/Utils/Allocator.cpp
External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
External/FEXCore/Source/Utils/Threads.cpp
FEXHeaderUtils/CMakeLists.txt
FEXHeaderUtils/FEXHeaderUtils/Syscalls.h
Source/Common/SocketLogging.cpp
Source/Tests/AOT/AOTGenerator.cpp
Source/Tests/ELFCodeLoader2.h
Source/Tests/FEXLoader.cpp
Source/Tests/HarnessHelpers.h
Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
Source/Tests/LinuxSyscalls/FileManagement.cpp
Source/Tests/LinuxSyscalls/LinuxAllocator.cpp
Source/Tests/LinuxSyscalls/SignalDelegator.cpp
Source/Tests/LinuxSyscalls/Syscalls.cpp
Source/Tests/LinuxSyscalls/Syscalls/FD.cpp
Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
Source/Tests/LinuxSyscalls/x32/Ioctl/usbdev.h
Source/Tests/LinuxSyscalls/x32/Semaphore.cpp
Source/Tests/LinuxSyscalls/x64/Semaphore.cpp
Source/Tools/FEXMountDaemon/Main.cpp

Adds a header only include utility folder that can be included from
everywhere.
Contains syscall helpers for older glibc and defines for older Linux
uapi headers missing some defines.

Improves compile ability for older libraries

---

Source/Common/RootFSSetup.cpp

In the case of having a stale lock file on the system, usually due to an
unclean shutdown, have FEX retry if the socket for that lock file is
also not available.
This resolves the exact case of:
```
FEXBash xeyes &
kill -9 `pidof FEXMountDaemon`
sudo shutdown -r now
FEXBash xeyes & <--- This command would now fail
```
The first command would do:
- Check lock file and socket
- Spin up FEXMountDaemon
- Create Lock file and Socket file
- Start executing XEyes in FEXInterpreter
The second command would do:
- Kills the FEXMountDaemon process
- This leaves squashfuse running
- The lock file and socket file are now unmanaged and just files on the filesystem
The third command would do:
- unmounts the squashfuse mount
- Leaving a dangling folder as a mount point
The fourth command would do:
- …

RootFS: Be more robust against stale lock files

---

Source/Common/RootFSSetup.cpp
Source/Common/RootFSSetup.h

In most cases this will be fixed on the first retry, but give it a
chance at five.
Otherwise you have a chance to infinite loop.

RootFS: Stop trying to retry rootfs after five times

---

docs/ReleaseProcess.md

Walks through all the steps required for a monthly release.

Docs: Adds documentation about the FEX monthly release process

---

ThunkLibs/libvulkan_device/Guest.cpp
ThunkLibs/libvulkan_device/Host.cpp

To properly show vulkan related file in auto generated documents

ThunkLibs: Add meta data to libvulkan_device

---

External/FEXCore/Source/Interface/IR/IRDumper.cpp

These should print as decimal. They were ending up as hex

IR: Fixes SSA ID printing

---

.gitmodules

This allows it to be managed by all organization members
Needed to begin addressing #1414

External: Point vixl submodule towards FEX's fork

---

External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
Source/Tests/LinuxSyscalls/FileManagement.cpp
Source/Tests/LinuxSyscalls/FileManagement.h
Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp

There were various places that we can hang. Cover all of these and now pressure-vessel consistently starts.

Fix pressure vessel hangs

---

Source/Tests/LinuxSyscalls/x32/Socket.cpp

Should resolve the new building issues from #1423

Linux: Fixes for older build environments

---

Source/Tools/FEXConfig/Main.cpp

Oops. This was added late and didn't test it.

Fixes FEXConfig build

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp
unittests/ASM/H0F38/66_37.asm

I thought we already had this implemented but I guess it was missed.
Required for SSE 4.2

OpcodeDispatcher: Implements PCMPGTQ

---

External/FEXCore/include/FEXCore/Core/UContext.h

The host provided siginfo_t definition can vary depending on the build
environment.
What doesn't change however is how the data is laid out.
It's always 128bytes, The first three 32-bit words are always known.
The 64-bit host side always has an additional 32-bit pad member.
Then the remaining bytes is the sifields.

UContext: Fixes 32-bit siginfo_t copying definition

---

Source/Tests/LinuxSyscalls/x32/Types.h

Some of these are defined differently depending on environment

Linux: Make sure to use correct accessors for sigevent

---

Readme.md

Fixes an issue where the FEXRootFSFetcher wouldn't get a any user input
and just fail out.
Save it to the tmp folder and execute from there instead.
Fixes #1557

Updates Readme to fix install script

---

Source/Tests/ELFCodeLoader2.h

I was overzealous with my removal of MAP_GROWSDOWN.
We still require the primary thread to have this flag set.
Fixes Ender Lilies.

FEXLoader: Adds back required MAP_GROWSDOWN

---

.gitmodules
CMakeLists.txt

This will be used with the code serialization service soon

Adds tsl::robin_map

---

Source/Tests/LinuxSyscalls/LinuxAllocator.cpp

In the face of an application using MAP_FIXED_NOREPLACE AND the host
linux kernel doesn't understand this flag. Then we were falling down the
hint allocation path which would allocate a pointer in 64-bit space,
returning this pointer to a 32-bit userspace and breaking things.
Now when the hint fails with this flag, we know that it intersecting a
range and can early exit.
Potentially fixes wine on old unsupported kernels < 4.17.

LinuxAllocator: Fixes bug with old kernels and hint allocation

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/GdbServer.cpp
External/FEXCore/Source/Interface/Core/GdbServer.h
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/JITCore.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
External/FEXCore/include/FEXCore/Core/CodeLoader.h
External/FEXCore/include/FEXCore/Core/SignalDelegator.h
External/FEXCore/include/FEXCore/HLE/SyscallHandler.h
Source/Tests/ELFCodeLoader2.h
Source/Tests/LinuxSyscalls/Syscalls.h

Gets this more usable. Still not super nice in regards to hanging with signals getting thrown around but getting significantly closer.

GDBServer improvements

---

External/FEXCore/Source/Common/StringUtils.h
External/FEXCore/Source/Interface/Config/Config.cpp
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/GdbServer.cpp
External/FEXCore/Source/Interface/Core/GdbServer.h
External/FEXCore/Source/Interface/IR/IRParser.cpp

This builds on the previous PR, allowing gdbserver to finally query the library map and give us backtraces.
Only the last three commits are relevant.

Gdbstub improvements: The sequel

---

External/FEXCore/Source/Interface/Core/GdbServer.cpp
External/FEXCore/Source/Interface/Core/GdbServer.h

Based on the previous PR. Only the final commit is the one that matters here

GDBServer improvements: Three's a crowd

---

External/FEXCore/Readme.md
Readme.md

I brought this up in the Discord, but some of the text here is out of date and doesn't accurately reflect the current state of the project / how to use it. I've removed it and replaced it with a link to the wiki, which is more actively updated.

docs: Remove stale text

---

External/FEXCore/include/FEXCore/Core/SignalDelegator.h

Fixes Termux building.
Fixes #1642

SignalDelegator: Adds missing include

---

Source/Tests/LinuxSyscalls/x32/Memory.cpp

This went unnoticed for so long since most applications are new enough
to use mmap2 instead of mmap.
This was just completely broken.
Fixes #1630

Linux: Fixes 32-bit mmap

---

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp

mode and flags were being combined incorrectly.

EmulatedFiles: Fixes temporary file flags

---

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp

In a large number of cases we are moving pointers within a 4GB region
and some marginal pointers that are within 1MB.
This is only used in the case that MOVZ can't be used.
NOP padding still occurs after these instructions to ensure that if they
are being used with relocations it will still get padded to a full 4
instruction length.
Not all hardware fuses these and LLVM claims that Cortex beyond A72 even
doesn't, but it'll still be faster.

Arm64Emitter: Optimize constants with ADRP and ADR

---

External/FEXCore/Source/Interface/Config/Config.cpp
External/FEXCore/Source/Interface/Config/Config.json.in
External/FEXCore/include/FEXCore/Config/Config.h
Source/Tools/FEXConfig/Main.cpp

Config: Adds code cache config option

---

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp

This ended up in the wrong commit. We need to rerun the DMB that we
patched in.

Arm64: Fix LDAPUR/STLUR DMB backpatch

---

Source/Tests/HarnessHelpers.h

This will allow it to get picked up for named region handling. Thus ending up in the code caching for testing.

TestHarnessRunner: Use guest mapper for test harness files

---

Scripts/generate_release.sh

In the case of a missing month or a minor version, need to allow user
defined overrides.

Scripts: Allow user override on tagged version

---

Source/Tests/LinuxSyscalls/FileManagement.cpp

open is rarely used compared to openat and openat2, so this has been
just missed but nothing really got upset about it.
Fixes Proton Experimental while running under pressure-vessel.

Linux: Fixes `open` syscall emulated path handling

---

External/FEXCore/Source/Interface/IR/IR.json

In a few places the description key was accidentally written as Dest.

IR.json: Correct 'Dest' key to 'Desc'

---

.github/workflows/ccpp.yml
Scripts/CI_FetchRootFS.py
unittests/gvisor-tests/Disabled_Tests
unittests/gvisor-tests/Known_Failures

Have our CI system auto fetch rootfs images.

CI: Auto rootfs fetching

---

External/FEXCore/Source/Interface/Core/Interpreter/BranchOps.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
External/FEXCore/Source/Interface/IR/IR.json

Making some space for new IR ops

IR: Remove GuestCallDirect, GuestCallIndirect

---

ThunkLibs/include/common/CrossArchEvent.h
ThunkLibs/libxcb-dri2/libxcb-dri2_Host.cpp
ThunkLibs/libxcb-dri3/libxcb-dri3_Host.cpp
ThunkLibs/libxcb-glx/Host.cpp
ThunkLibs/libxcb-present/Host.cpp
ThunkLibs/libxcb-randr/Host.cpp
ThunkLibs/libxcb-shm/libxcb-shm_Host.cpp
ThunkLibs/libxcb-sync/Host.cpp
ThunkLibs/libxcb-xfixes/libxcb-xfixes_Host.cpp
ThunkLibs/libxcb/libxcb_Host.cpp

Just adding a bunch of [[maybe_unused]] in unchecked returns. Should these be converted to asserts @neobrain?

ThunkLibs: silence warnings

---

Source/Common/FEXServerClient.cpp
Source/Tools/FEXServer/ProcessPipe.cpp

Just some minor changes for things I noticed.

FEXServer: Minor changes

---

Source/Common/Config.cpp

When wine-preloader is executed it doesn't do an execve to passed in
wine program. It will instead map the executable directly in to memory
and start executing it.
This way we end up with a program executing like `wine-preloader
<absolute wine path> Game.exe`
This now handles the wine-preloader case so we can get the correct
application profile here.

Config: Fixes AppConfig for wine-preloader

---

ThunkLibs/libvulkan/Host.cpp

This was checking for the wrong debug structure and it wasn't actually
unlinking it correctly from the linked list.
Since it was talking directly to a_0 instead of the current modifying
struct.
Instead of having a stubbed debug report struct, we can just remove the
structure from the linked list. Since we are already abusing a const
cast there anyway.
Fixes Vulkan thunks on Snapdragon.

Thunks/vulkan: Disable debug report callback

---

External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp

Noticed this while running _Forsaken Remastered_ using a Debug build of FEX.
The recursive algorithm used here previously led to deeply nested function calls, which eventually exhausted the available stack space. The simple non-recursive algorithm used now avoids this problem at the expense of small overhead.
In Forsaken Remastered, the overhead was not visibly noticeable (time spent outside of validation far outweighed time in this function).

ValueDominanceValidation: Avoid stack exhaustion when aggregating predecessors

---

External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/include/FEXCore/Core/SignalDelegator.h
External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
Source/Tests/LinuxSyscalls/SignalDelegator.cpp
Source/Tests/LinuxSyscalls/SignalDelegator.h

See commit messages.
Fixes SOMA, makes unity games more stable.

Fix SOMA and sigaction definition

---

External/FEXCore/Source/Interface/Core/CPUID.cpp

Missed this in the list before since we didn't know the part ID.

CPUID: Detect Cortex-X1C

---

Source/Tools/FEXRootFSFetcher/Main.cpp

Main options here are `-y` and `-a`.
Passing both will allow the user to download the exact match image, use
it as-is, and set the config to use the rootfs by default.
Additional options `--distro-name` and `--distro-option` allows one to
select a particular distro version.
eg: `FEXRootFSFetcher -y -a --distro-name=ubuntu --distro-version=22.04`
* Will download the first Ubuntu 22.04 compressed in the json list
* Priority of erofs or squashfs depends on order in json and what the
host supports

FEXRootFSFetcher: Add some options for automation without user intervention

---

Source/Tests/HarnessHelpers.h

Last of the things that slipped through while re-adding the ldp/stp optimization.
This code isn't executed currently with the way the harnesses are set up, but at least it'll work properly as expected

HarnessHelpers: Handle SSE register offsets in CompareStates

---

Source/Tools/FEXServer/ProcessPipe.cpp

Depending on the operation we will do a vector insert or removal while
iterating over the vector.
Fixes a use after free that asan found when insert caused the vector to
resize.

FEXServer: Fix unsafe vector insert/removal

---

ThunkLibs/libGL/libGL_Guest.cpp

Multiple games will query symbols that are leaked but we don't support.
It is safe to return nullptr in these cases.
Print a warning message still just in-case someone fails hard at GL.

Thunks: Make unknown glXGetProcAddress non-fatal

---

External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp

Due to how the 64-bit allocator previously worked, it was never subjected to memory
regions larger than 64GB to be tracked. With the change in
PR #1885, this has changed to have regions that will hit sizes larger
than 170TB on some platforms.
Better yet, even with smaller regions it still had a performance issue,
it just wasn't as visible.
First problem: We used MemSet instead of MemClear for the live page
clearing. This caused pages to be claimed as "always in use".
This would cause us to always scan the entire region on allocation, find
that it didn't work and allocate a fresh region on every slab
allocation.
jemalloc saving us here since it allocates slabs from the OS fairly
aggressively.
Second problem: We used MemSet (now changed to MemClear) to "clear" the
state tracking for pages. …

64BitAllocator: Fixes a significant state tracking perf problem

---

External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
ThunkLibs/HostLibs/CMakeLists.txt
ThunkLibs/include/common/Host.h

As pointed out by @skmp in #1868.

Thunks: Minor cleanups for signature-based function pointer thunking

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp

This is a much more descriptive name.
Spawned off of discussion in #1944

Arm64/JIT: Rename CanUseSVE to HostSupportsSVE

---

Source/Tools/FEXServer/ProcessPipe.cpp

pidfd_open was added in kernel 5.3 so older kernel devices weren't able to use `FEXServer -w`. If the syscall doesn't give us an FD to the process, then use a pipe instead.
Since we are only polling for the FD to hangup this works for us.

FEXServer: Fix waiting on kernel version older than 5.3

---

Scripts/StructPackVerifier.py

The x86 runner had unattended-upgrades accidentally still enabled. It upgraded a bunch of development packages which broke CI.
Fix the struct verifier so it works with the new packages. Sadly python3-clang doesn't support all the new CursorKind types so we need to self-define some of them for now.
Once this tool gets converted over to C++ it will be a non-issue.

StructVerifier: Fixes CI failure

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
External/FEXCore/Source/Interface/IR/IR.json

This IR op duplicates what VInsElement does.

IR: Removes VInsScalarElement

---

Source/Tests/ELFCodeLoader2.h

This more closely matches behaviour of the kernel. Provides an example in source to ensure we don't break it in the future.

ELFCodeLoader: Map interpreter first

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VAbs to be able to handle 256-bit width vectors.

IR: Handle 256-bit VAbs

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFAdd to be able to handle 256-bit width vectors.

IR: Handle 256-bit VFAdd

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFAddP to be able to handle 256-bit vectors.

IR: Handle 256-bit VFAddP

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFSub to be able to handle 256-bit vectors.

IR: Handle 256-bit VFSub

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFMul to handle 256-bit vectors.

IR: Handle 256-bit VFMul

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFDiv to handle 256-bit vectors.

IR: Handle 256-bit VFDiv

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VAddP to handle 256-bit vectors.

IR: Handle 256-bit VAddP

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFMin to handle 256-bit vectors.

IR: Handle 256-bit VFMin

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFMax to handle 256-bit vectors.

IR: Handle 256-bit VFMax

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFRecp to handle 256-bit vectors.

IR: Handle 256-bit VFRecp

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFSqrt to handle 256-bit vectors.

IR: Handle 256-bit VFSqrt

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFRSqrt to handle 256-bit vectors.

IR: Handle 256-bit VFRSqrt

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VNeg to handle 256-bit vectors.

IR: Handle 256-bit VNeg

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFNeg to handle 256-bit vectors.

IR: Handle 256-bit VFNeg

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VSMin and VUMin to handle 256-bit vectors

IR: Handle 256-bit VSMin/VUMin

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VSMax and VUMax to handle 256-bit vectors

IR: Handle 256-bit VSMax/VUMax

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VBSL to handle 256-bit vectors.

IR: Handle 256-bit VBSL

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VCMPEQ and VCMPEQZ to handle 256-bit vectors

IR: Handle 256-bit VCMPEQ/VCMPEQZ

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFCMPEQ and VFCMPNEQ to handle 256-bit registers

IR: Handle 256-bit VFCMPEQ/VFCMPNEQ

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VFCMPLT, VFCMPGT, and VFCMPLE to handle 256-bit vectors

IR: Handle 256-bit VFCMPLT/VFCMPGT/VFCMPLE

---

ThunkLibs/include/common/Host.h

Lets us check if nullptr was passed in

Thunks/Host: Adds bool operator to fex_guest_function_ptr

---

Scripts/DefinitionExtract.py

Unused warning attribute wasn't getting ignored.
Also need to update output text to match new format

Scripts: Updates DefinitionExtract

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VSShrS, VUShlS, and VUShrS to handle 256-bit vectors

IR: Handle 256-bit VSShrS/VUShlS/VUShrS

---

ThunkLibs/include/common/PackedArguments.h

Thunks: Adds another packed arguments template

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VShlI, VUShlI, and VUShrI to handle 256-bit vectors

IR: Handle 256-bit VShlI/VUShlI/VUShrI 

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VRev64 to handle 256-bit vectors.

IR: Handle 256-bit VRev64

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VSMul and VUMul to handle 256-bit vectors.

IR: Handle 256-bit VSMul/VUMul

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VUABDL to handle 256-bit vectors.

IR: Handle 256-bit VUABDL

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp

It will be helpful to translate lsl Eb, Ib and ror Eb, Ib correctly

Flags: Refine _Bfe's shift

---

ThunkLibs/include/common/Guest.h

Due to how we use a modified ABI for these indirect functions, we don't have a clean way to say that the host_addr lives in a side-argument.
The previous inline asm that moved the value from r11 in to a variable worked up until you hit functions with 8 or more arguments. At that point the compiler was generating code before our inline assembly and using r11 as a temporary, thus destroying our value. Then a crash would occur and it was very hard to determine why. It would end up calling some random function (0x1 in this case) from an indirect call.
This made it /look/ like it was calling an invalid function returned from the loader but in reality it was a corrupt register loading bad data.
To work around this case, we can use an inline asm register variable and a volatile asm block that …

Thunks: Fixes indirect thunks with 8+ arguments

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VSMull and VSMull2 to handle 256-bit vectors

IR: Handle 256-bit VSMull/VSMull2

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VSQXTN and VSQXTN2 to handle 256-bit vectors.

IR: Handle 256-bit VSQXTN/VSQXTN2

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VSQXTUN and VSQXTUN2 to handle 256-bit vectors.

IR: Handle 256-bit VSQXTUN/VSQXTUN2

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VZip and VZip2 to handle 256-bit vectors

IR: Handle 256-bit VZip/VZip2

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VUnZip and VUnZip2 to handle 256-bit vectors.

IR: Handle 256-bit VUnZip/VUnZip2

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VDupElement to handle 256-bit vectors.

IR: Handle 256-bit VDupElement

---

External/FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp

Extends Vector_SToF to handle 256-bit vectors.

IR: Handle 256-bit Vector_SToF

---

External/FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp

Extends Vector_FToZS and Vector_FToS to handle 256-bit vectors

IR: Handle 256-bit Vector_FToZS/Vector_FToS 

---

External/FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp

Extends Vector_FtoF to handle 256-bit vectors.

IR: Handle 256-bit Vector_FtoF

---

External/FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp

Expands Vector_FToI to handle 256-bit vectors.

IR: Handle 256-bit Vector_FToI

---

External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp

Extends VExtractToGPR to handle 256-bit vectors.

IR: Handle 256-bit VExtractToGPR

---

External/FEXCore/Source/Interface/Core/Interpreter/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp

Extends VInsGPR to handle 256-bit vectors.
This should finish off most of the conversion ops

IR: Handle 256-bit VInsGPR

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp

Allows hardware to pack the move and following destructive operation together into one constructive operation if possible.
e.g.
```
movprfx VTMP1.D, VectorLower.D
addp VTMP1.B, Pred, VTMP1.B, VectorUpper.B
```
is allowed to be merged as if it executed constructively like:
```
addp VTMP1.B, Pred, VectorLower.B, VectorUpper.B
```
if the hardware supports it. If it doesn't, then the instructions will behave like a regular move and destructive addp operation separately.

Arm64/VectorOps: Make use of MOVPRFX where applicable

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VTBL1 to handle 256-bit vectors.

IR: Handle 256-bit VTBL1

---

Source/Tests/LinuxSyscalls/FileManagement.cpp

Previously the config options could only have ever enabled thunks rather than disable them.
Now sort the code so it can enable thunks, then following configs can redisable them.  Allowing testing with global thunks enabled and disabling problematic applications.
Also sorts the "ThunkConfigFile" config as lower priority than the application configs. I wasn't thinking about ordering that hard for these five configuration paths, but application configs should be higher priority in this case.

Thunks: Add support for disabling thunks in config

---

Source/Tests/ELFCodeLoader2.h

This is a tricky situation that wine-preloader allocates the lower 32MB of stack space through fixed address mmap with MAP_FIXED.
They can't use mmap with an address hint nor MAP_FIXED_NOREPLACE because it changes behaviour. mmap won't give you the allocation inside the stack space even if you check `/proc/self/maps` that space isn't yet allocated. The growable space of the stack blocks those allocations.
So the wine peeps might be SOL if they actually require this allocation to exist.
To replicate this, allocate the application stack at the same location using an address hint. This will give us the correct region on a 48-bit VA system, while also letting it select a different region on a 36-bit VA system.

ELFCodeLoader: Fixes Proton Experimental on 48-bit VA systems

---

ThunkLibs/libX11/libX11_Host.cpp

Fixes a crash that occurs due to `_XInitDisplayLock` due to the display lock function being initialized to our own handler.
steamwebhelper was hitting this.

Thunks/libX11: Fix recursive initialize

---

unittests/gvisor-tests/Flake_Tests

unittests/gvisor: Adds a bunch of tests to flakes

---

External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp

Extends LoadContext and StoreContext to handle 256-bit vectors.

IR: Handle 256-bit LoadContext/StoreContext

---

External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp

Extends StoreMem, StoreMemTSO, and ParanoidStoreMemTSO to handle 256-bit vectors.

IR: Handle 256-bit StoreMem/StoreMemTSO/ParanoidStoreMemTSO

---

External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
External/FEXCore/Source/Interface/IR/IR.json

Extends LoadContextIndexed and StoreContextIndexed to handle 256-bit vectors

IR: Handle 256-bit LoadContextIndexed/StoreContextIndexed

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VInsElem to handle 256-bit vectors.

IR: Handle 256-bit VInsElement

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VAddV to handle 256-bit vectors.

IR: Handle 256-bit VAddV

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp

Extends LoadRegister and StoreRegister to handle 256-bit vectors

IR: Handle 256-bit LoadRegister/StoreRegister

---

External/FEXCore/Source/Interface/Core/CPUID.cpp
External/FEXCore/Source/Interface/Core/HostFeatures.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/include/FEXCore/Core/HostFeatures.h

OpcodeDispatcher: Disable PCLMUL if not supported on host

---

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h
External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp
External/FEXCore/Source/Interface/IR/IR.json

These are unused, so we can get rid of them.

IR: Remove VLoadMemElement and VStoreMemElement

---

Source/Tests/ELFCodeLoader2.h

This is the last remaining auxv value that we were missing.
This requires a little bit of setup to match what we are doing in FEXCore's Dispatcher.
This only tracks how much space is required by the kernel to store its required state.

ELFCodeLoader: Calculate AT_MINSIGSTKSZ

---

External/FEXCore/Source/Interface/Core/Interpreter/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp

Extends VExtr to handle 256-bit vectors.

IR: Handle 256-bit VExtr

---

Source/Common/FEXServerClient.cpp
Source/Tools/FEXServer/Main.cpp
Source/Tools/FEXServer/ProcessPipe.cpp
Source/Tools/FEXServer/SquashFS.cpp

Systemd has....problems that we need to work around.

Systemd fixes

---

Source/Tests/FEXLoader.cpp

When AOT wasn't enabled it was still doing some accesses to the filesystem on shutdown.
Slightly improves shutdown time.

FEXLoader: Disables some AOT shutdown overhead when not enabled

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/VEX/vmovntdq.asm
unittests/ASM/VEX/vmovntdqa.asm
unittests/ASM/VEX/vmovntpd.asm
unittests/ASM/VEX/vmovntps.asm

Handles the trivial nontemporal moves

OpcodeDispatcher: Handle VMOVNTDQ/VMOVNTDQA/VMOVNTPD/VMOVNTPS

---

External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp

Thunk: Crash on XSetErrorHandler(NULL)

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp

This can be merged into it, considering it only has one IR op.

OpcodeDispatcher: Merge PAVGOp with VectorALUOp

---

External/FEXCore/Source/Interface/Core/ArchHelpers/MContext.h
External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
unittests/FEXLinuxTests/tests/signal/synchronous-signal-block.cpp

On Fault then ARM will return information about the fault in ESR_EL1 to
the user.
We need to decode what ESR_EL1 means in the context of the fault to get
the flags we care about.
The flags we care about specifically are PF_USER and PF_WRITE.
PF_PROT would have been interesting but I didn't see when this gets
returned to the user. ARM makes the difference if the page is unmapped
or "mapped" with PROT_NONE. x86 doesn't make the distinction here.
This should fix an issue that a user was hitting.

Dispatcher: Calculate REG_ERR correctly using ARM ESR_EL1 

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp

Keeps the implementation similarly in sync with VAddP.

Arm64/VectorOps: Simplify FADDP result merging

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp

We can just arrange the elements into a vector and XOR them all at once.

OpcodeDispatcher: Simplify SHA1MSG1 implementation

---

External/FEXCore/Source/Interface/Core/LookupCache.cpp
External/FEXCore/Source/Interface/Core/LookupCache.h

We generate a /lot/ of block links which causes our shutdown time to take a while for this map. For short running applications this shutdown time can take a statistically significant amount of time, and this has been haunting us for a while.
Using a monotonic buffer resource, we can cut the dellocation time down to effectively zero on cache clear and shutdown.
For short running applications this basically means we clear their shutdown time, for long running applications this means a cache clear is less painful.
I've measured up to 2ms , but more often this takes ~0.5ms before optimization. Now it is consistently ~0.25ms on a short running application.
Times will vary /greatly/ depending on how full it has filled this map.

LookupCache: Use a PMR map for our Blocklinks with monotonic allocator

---

ThunkLibs/HostLibs/CMakeLists.txt

Seems to be a recent-ish regression. Thanks for nothing, CMake 😩

Thunks: Fix IDE integration

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/VEX/vmaskmovdqu.asm

This one only has a 128-bit variant, so we can use the existing handling code for this

OpcodeDispatcher: Handle VMASKMOVDQU

---

External/FEXCore/Source/Interface/Context/Context.h

Apparently this has some tcache fixes and performance improvements

Externals: Update jemalloc to 5.3.0

---

Source/Tools/FEXServer/SquashFS.cpp

fix tgkill

---

External/FEXCore/Source/Interface/Core/ArchHelpers/MContext.h

Pulled from #2176.
Ensures that when we are handling signals we are actually restoring a stack state that is what we expect..
While this could randomly intersect with other stack data, it is highly unlikely and will still capture incorrect stack frames otherwise.
Keeps it out of release build to ensure we aren't sticking random data in the stack when it wouldn't have even been checked.

MContext: Insert a stack cookie with assertions enabled

---

Source/Tests/ELFCodeLoader2.h

Fixes #2095
std::random_device can fail to find a random source and throw an assert during initialization.
The constructor allows you to provide a token string to select an explicit random source, but this is c++ library specific and will still assert if the source isn't found. Also specific tokens are very much target and library specific, so it is unsafe to use.
In the libstdc++ case, the default implementation will try to open `/dev/urandom` which might not be available on all targets.
Instead of relying on this C++ object, use the `getrandom` syscall directly to generate our RNG used in the ELFCodeLoader. Resolves any sort of asserting case, blocks on RNG generation, and is guaranteed to be available since this syscall has been available since a very old kernel version.

ELFCodeLoader: Don't use std::random_device for RNG

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

These were using LoadRegister/StoreRegister directly but instead should be using the helper functions instead.
Future optimizations will need all users of these registers to use the helper. This covers all the missing cases.

OpDispatcher: Fixes a few missing GPR/XMM helper usages

---

External/FEXCore/Source/Utils/FileLoading.cpp

Optimize `FileLoad` by not using fstream.
For some reason fstream is just really bad.
Switching over to raw pread cuts the amount of time it takes to read files by a quarter of CPU time.

FileLoading: Optimize FileLoad

---

External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp

We can do a single LDP upfront when loading from the code cache, which saves an instruction and one LDP costs the same as a single LDR.
Itty bitty optimization in the hot dispatcher.

Arm64: Merge two loads in to an LDP

---

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp

In large blocks we can be generating a ton of inline constants. But in most cases these end up being 0, 1, or (1 << N).
Add these to a map and reuse if possible. Makes some IR blocks significantly smaller for later optimization passes.

ConstProp: Pool inline constants

---

Source/Common/Config.cpp

I made the assumption from some bad historical knowledge that the kernel will canonicalize relative filenames and symlinks for applications that execute through execve.
This turns out to not be true. In fact it passes pathname untouched to the interpreter. So we need to do an additional fix up on relative paths to ensure glibc doesn't break.
Fixes a major bug that breaks a bunch of games.

Config: Fix relative execve applications.

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

Knocks out another class of instructions

ARMEmitter: Handle SVE floating-point recursive reduction

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
External/FEXCore/unittests/Emitter/ALU_Tests.cpp

Crosses off most of the todos for the ALU ops

ARMEmitter: Handle RMIF, SETF8/SETF16

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

Fairly simple ones to implement

ARMEmitter: Handle integer add/subtract vectors (predicated) instruction class

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
External/FEXCore/Source/Interface/IR/IR.json
unittests/ASM/VEX/vblendvpd.asm
unittests/ASM/VEX/vblendvps.asm
unittests/ASM/VEX/vpblendvb.asm

Now the variable blends are all implemented

OpcodeDispatcher: Handle VPBLENDVB/VBLENDVPD/VBLENDVPS

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

Gets rid of another swath of TODOs that were in flight

ARMEmitter: Handle SVE2 Accumulate category

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp

Keeps all of the IR ops consistent with each other in terms of behavior in relation to op sizes. Also removes some redundant scalar checks that weren't really necessary.

Arm64/VectorOps: Use SVE only with 256-bit op sizes

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

While we're at it, we can combine them all under a single helper

ARMEmitter: Finish off SVE Predicate Misc group

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

As far as I know, nothing actually uses this path. Partially resolves the TODO of dealing with partial writes.

OpcodeDispatcher: Restrict partial XMM stores to FPRs in StoreResult_WithOpSize

---

Source/Tests/LinuxSyscalls/FileManagement.cpp

In the case that a file is getting opened to be created or writable then skip EmuFD and rootfs searching for this file.
This fixes an edge case where if FEX was run with an unpacked rootfs that was writable then pressure-vessel would break.
Fixes pressure-vessel with unpacked rootfs.

FileManagement: Skip opening emulated writable files

---

Source/Tests/LinuxSyscalls/x32/Time.cpp

Alwa's Awakening had an issue where it was spamming clock_nanosleep and getting EINVAL, consuming a CPU thread to 100%.
This is due to two things in the previous implementation 1) glibc helper does some data munging and validation of inputs 2) We were updating remain even if TIMER_ABSTIME was used
This only cropped up because this error would only occur when EINTR occured. Since the game is a mono game, the thread that would be sleeping would get interrupted and then spin forever with corrupted data.

x32: Fixes clock_nanosleep syscall

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

Now we have both LDR (predicate) and LDR (vector)

ARMEmitter: Handle LDR (vector)

---

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp
External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
External/FEXCore/Source/Interface/IR/Passes/IRValidation.h
External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
External/FEXCore/Source/Utils/Allocator.cpp
External/FEXCore/include/FEXCore/Utils/Allocator.h
External/FEXCore/include/FEXCore/fextl/deque.h
External/FEXCore/include/FEXCore/fextl/forward_list.h
External/FEXCore/include/FEXCore/fextl/list.h
External/FEXCore/include/FEXCore/fextl/map.h
External/FEXCore/include/FEXCore/fextl/set.h
External/FEXCore/include/FEXCore/fextl/string.h
External/FEXCore/include/FEXCore/fextl/unordered_map.h
External/FEXCore/include/FEXCore/fextl/unordered_set.h
External/FEXCore/include/FEXCore/fextl/vector.h

Plus two commits that are necessary that I missed in my stashed changes.

IR/Passes: Changes vector to fextl

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

Also unifies them all under one underlying main helper

ARMEmitter: Finish off SVE2 Integer - Predicated group

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

Crosses off one of the remaining groups in the emitter

ARMEmitter: Handle SVE Integer Multiply-Add - Unpredicated group

---

ThunkLibs/libxcb/libxcb_Guest.cpp

Fixes a crash in xcb thunks since more stuff on FEX side has moved over to jemalloc.
Destructors don't actually get called when a shared library is removed. It's some weirdo quirk that we can't work around. Instead refcount Display connections being created and disconnected. Creating the thread on the first display creation, and tearing down on final display teardown.
Must be merged before #2564 otherwise that PR will break thunks.

Thunks: Make xcb's callback more robust.

---

ThunkLibs/GuestLibs/CMakeLists.txt

Thunks: Enable ccache if available

---

.gitmodules
CMakeLists.txt
External/FEXCore/Source/CMakeLists.txt
External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
External/FEXCore/Source/Utils/Allocator.cpp
docs/jemalloc_usage.md

We still need to hook glibc for thunks to work with
`IsHostHeapAllocation`.
So now we link in two jemalloc allocators in different namespaces.
As usual we have multiple heap allocators that we need to be careful about.
1. jemalloc with `je_` namespace.
- This is FEX's regular heap allocator and what gets used for all the
fextl objects.
- This allocator is the one that the FEX mmap/munmap hooks hook in to
- This mmap hooking gives this allocator the full 48-bit VA even in
32-bit space.
2. jemalloc with `glibc_je_` namespace.
- This is the allocator that overrides the glibc allocator routines
- This is the allocator that native libraries (including the host side of thunks) will use.
- This is what `IsHostHeapAllocation` will check for.
3. Guest glibc allocator
- We don't touch this one. But …

Add in jemalloc glibc hooking again 

---

docs/ProgrammingConcerns.md

Explaining FEX's memory concerns.

Docs: Adds programming concerns documentation

---

External/FEXCore/Source/Interface/Core/ObjectCache/ObjectCacheService.cpp
External/FEXCore/Source/Utils/Threads.cpp
External/FEXCore/include/FEXCore/Utils/Threads.h

Not yet implemented for mingw but hides the implementation details a bit.

Threads: Adds SetThreadName helper

---

External/FEXCore/include/FEXCore/Utils/AllocatorHooks.h
External/FEXCore/include/FEXCore/fextl/allocator.h
External/FEXCore/include/FEXCore/fextl/memory.h
External/FEXCore/include/FEXCore/fextl/memory_resource.h

Allocator: Ensure uses of aligned allocations use aligned_free

---

External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/GdbServer.cpp

This needs to move to the frontend at some point.

GdbServer: Disable under mingw

---

External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

Disable Break/INT operations on mingw

---

External/FEXCore/Source/Interface/Core/ObjectCache/JobHandling.cpp
External/FEXCore/Source/Interface/IR/AOTIR.cpp

Object cache isn't ready or working anyway and AOTIR is also mostly broken anyway.

Disable AOT and object cache under mingw

---

External/FEXCore/Source/Interface/Core/ArchHelpers/MContext.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp

This needs some hefty reconstructing

Dispatcher: Disable signal handling under mingw

---

Source/Tools/FEXLoader/LinuxSyscalls/FileManagement.cpp

In the case that the symlink following would immediately fail (Due to the first query not existing or not being a symlink), then FEX would immediately return the first query. Then the resulting syscall using this result would try to run the syscall on that file, immediately error, and try again on the file outside of the rootfs. This gives us three syscalls for the price of one.
This adds an additional syscall cost to every syscall that that takes the `FollowSymlink` code path, which is quite a few.
Instead now, check to see if the filepath exists at all, and if the filepath doesn't even exist for the first fstatat, return a `NoEntry` immediately. This will cause the resulting syscall waiting for the result to skip the EmulatedFDPath check and run regular syscall.
If the filepath is …

FM: Removes double syscall issue with `GetEmulatedFDPath`

---

External/FEXCore/include/FEXCore/Utils/AllocatorHooks.h

This lets me run at least a few instructions of Win32 code under Wine.

Win32 memory allocation fixes

---

Source/Tools/FEXLoader/ELFCodeLoader.h

New versions of CEF rely on this existing. It will get this value and run strdup on it, even if it is nullptr.
Fixes a steamwebhelper process constantly crashing with the Steam Beta client.
Only missing auxv values now
- AT_PAGESZ
- AT_EXECFD (for execveat?)
- AT_PHDR
- All the random cache information values.

ELFCodeLoader: Fixes missing AT_EXECFN

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/H0F3A/pcmpistrm_equal_any.asm
unittests/ASM/H0F3A/pcmpistrm_equal_each.asm
unittests/ASM/H0F3A/pcmpistrm_equal_ordered.asm
unittests/ASM/H0F3A/pcmpistrm_ranges.asm
unittests/ASM/VEX/vpcmpistrm_equal_any.asm
unittests/ASM/VEX/vpcmpistrm_equal_each.asm
unittests/ASM/VEX/vpcmpistrm_equal_ordered.asm
unittests/ASM/VEX/vpcmpistrm_ranges.asm

Only two more string instructions left to go and they're all crossed off

OpcodeDispatcher: Handle PCMPISTRM/VPCMPISTRM

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp
External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp
unittests/ASM/H0F3A/pcmpestrm_equal_any.asm
unittests/ASM/H0F3A/pcmpestrm_equal_each.asm
unittests/ASM/H0F3A/pcmpestrm_equal_ordered.asm
unittests/ASM/H0F3A/pcmpestrm_ranges.asm
unittests/ASM/VEX/vpcmpestrm_equal_any.asm
unittests/ASM/VEX/vpcmpestrm_equal_each.asm
unittests/ASM/VEX/vpcmpestrm_equal_ordered.asm
unittests/ASM/VEX/vpcmpestrm_ranges.asm

...and with that all of the SSE4.2 string instructions are implemented now

OpcodeDispatcher: Handle PCMPESTRM/VPCMPESTRM

---

Source/Tools/FEXLoader/LinuxSyscalls/Syscalls/Thread.cpp

Noticed this while debugging Proton Experimental hanging and thought this could be related. Didn't solve that issue but this should be merged anyway.
vfork doesn't fork the host's process space in to the child process. Saving Copy-On-Write overhead problems. It also puts the parent process to sleep until the fork terminates or executes.
This is a major issue under FEX where we can't emulate vfork correctly because we need to do other work before this process terminates or executes a new process. We have been treating `vfork` as a `fork` this entire time.
This can likely cause problems for applications that actually use vfork to wait for a process to complete. So let's actually emulate that feature by using a pipe with poll to determine when that FD gets removed.
FEX can't use waitpid to …

Linux: Make vfork act more similar to how it should.

---

Scripts/InstallFEX.py

Also updates the link in the source to the new json file.

InstallFEX: Updates helper install script for Ubuntu 23.04

---

Source/Tools/FEXRootFSFetcher/Main.cpp

This basically just means that we detect ArchLinux and set a flag that it is a rolling release, skipping doing the version check for an "exact" match in that instance.

FEXRootFSFetcher: Support rolling release distros

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp

This previous implementation was particularly gnarly. Because these instructions are both weackly ordered and have implementation dependent exception and trap behaviour these can actually be fairly conveniently converted over to a load + cmlt + bsl + str instruction.
For the XMM variant this reduces code blowup from 80x to 15x!
For the MMX variant this reduces code blowup from 46x to 17x!
Both of these improvements are significant wins!
There's still some minor improvement that could be done with bsl that requires some redundant moves, but since we don't have constraint support for this we still eat two additional instructions
Before:
```asm
0x0000ffff7b800718  10ffffe0    adr x0, #-0x4 (addr 0xffff7b800714)
0x0000ffff7b80071c  f9005f80    str x0, [x28, #184]
0x0000ffff7b800720  4eb11e24 …
```

OpcodeDispatcher: Optimize MASKMOVDQU and MASKMOVQ

---

External/FEXCore/Source/Interface/Context/Context.h
External/FEXCore/Source/Interface/Core/Core.cpp
External/FEXCore/Source/Utils/Telemetry.cpp
External/FEXCore/include/FEXCore/Core/Context.h
External/FEXCore/include/FEXCore/Utils/DeferredSignalMutex.h
External/FEXCore/include/FEXCore/Utils/Telemetry.h
External/FEXCore/include/FEXCore/fextl/fmt.h
FEXHeaderUtils/FEXHeaderUtils/SymlinkChecks.h
Source/Common/CMakeLists.txt
Source/Common/Config.cpp

Mostly a quick bandage while I'm setting getting ready to setup the runners to test this for us.

FEXCore: Fixes WIN32 compiling again

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp

OpcodeDispatcher: Optimize ADD/ADC OF flag packing 

---

External/FEXCore/Source/Interface/IR/Passes/DeadStoreElimination.cpp

This pass is currently doing nothing in main.
Ever since we have enforced that LoadContext/StoreContext doesn't touch GPRs and FPRs, this has only been eliminating flags.
Remove that usage of LoadContext/StoreContext and replace with their their replacement of LoadRegister/StoreRegister for tracking GPR and FPR accesses.
Stripped from #2700 since this is safe to merge.

IR/Passes: Fixes DeadStoreElimination pass

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

32-bit and 64-bit SH{L,R}D matches behaviour of EXTR. Optimize to using this op in that case.
This converts the lsl+lsr+orr sequence in to a single extr instruction.
16-bit still goes down the old path.
Weirdly this code manages to have a bad insert for no reason? But unrelated since this happens in the old code as well.
```
%4(GPRFixed3) i64 = LoadRegister #0x0, #0x20, GPR, GPRFixed, u8:Tmp:Size
%5(GPR0) i64 = LoadRegister #0x0, #0x8, GPR, GPRFixed, u8:Tmp:Size
%6(GPRFixed0) i64 = Extr %5(GPR0) i64, %4(GPRFixed3) i64, #0x3e
```
Not sure why the SRA fails on that second LoadRegister.

OpcodeDispatcher: Optimize 32/64-bit SH{L,R}D with extr

---

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp

Noticed this when inspecting some code that was moving constant `0x80808080` in to a register. Was using two move instructions when it could have used a single bitmask move.
This now checks to see if a constant can be 32-bit encoded in a logical bitmask move and uses that.

ArmEmitter: Support 32-bit bitmask moves

---

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp

Currently we're clearing icache including the data that lives on the tail of the block. Instead only clear the code that the was emitted and not tail data.
Additionally only disasm the code rather than all the tail data as well, as it gets unwieldy if viewing.

Arm64: Only clear icache for code

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl

This lets us deduplicate the behavior rather than open-coding it everywhere and also makes it nicer to implement instructions that make use of this encoding pattern.

Arm64/Emitter: Add helper for encoding SVE shift immediates

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

The BFI cascades in this particular instruction weren't optimal. Biggest improvement is the 8-bit version, while the 16-bit version gets a minor improvement.
8-bit instruction count reduced from 38 to 29.
16-bit instruction count reduced from 34 to 28.
RCL can have a similar optimization done to it. Still some bad codegen inside of this instruction, but that comes from 8-bit and 16-bit operating sizes having uxtb/uxth when unnecessary, and some spurious moves.
```asm
Before 16-bit:
0x0000ffff80a801e0  10ffffe0    adr x0, #-0x4 (addr 0xffff80a801dc)
0x0000ffff80a801e4  f9005f80    str x0, [x28, #184]
0x0000ffff80a801e8  d3403cb4    uxth x20, w5
0x0000ffff80a801ec  d3403cf5    uxth x21, w7
0x0000ffff80a801f0  394b0396    ldrb w22, [x28, #704]
0x0000ffff80a801f4  12001294    and w20, w20, …
```

OpcodeDispatcher: Optimize 8/16-bit RCR

---

FEXHeaderUtils/FEXHeaderUtils/Filesystem.h

FHU: Avoid calling faccessat on WIN32

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl

We can collapse the entire if statement to be much simpler.

Arm64/Emitter: Simplify SVE immediate shift helper

---

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp

Picked off from #2815 .. this came up when packing flags. I see little harm in merging this regardless of what happens with #2815

ConstProp: Handle constant Bfi

---

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp

Every time I look at this I can never remember which node is the value node and which one is the store node.
Rename the opaque `Node` to `ValueNode` and have documentation comments to explain which one it is. This way I won't forget again.

RCLSE: Rename `Node` to `ValueNode`

---

External/FEXCore/unittests/CMakeLists.txt
Source/Tools/FEXLoader/CMakeLists.txt
Source/Tools/FEXLoader/WindowsDummyHandlers.cpp
Source/Tools/FEXLoader/WindowsDummyHandlers.h

Getting the CI machines setup to handle this so we can stop breaking it.

Mingw: Fixes compiling again

---

unittests/FEXLinuxTests/tests/smc/smc-mt-2.cpp

This test was written to test SMC where one thread is doing execution while the other thread is modifying.
According to the printf documentation it is supposed to "wait for code to be modified" but actually it was testing a race between a printf on one thread and the primary thread modifying the code.
Fix this test so it is actually waiting for code modification to happen rather than testing a race condition. This is likely what the original author intended.
CI is hitting this flake more frequently now because it is even faster it seems, so fixing this test is necessary to resolve these flakes.

FEXLinuxTests: Fixes race in smc-mt-2

---

Source/Tools/FEXLoader/LinuxSyscalls/x32/Socket.cpp

Steam started using this recently. So implement it. Still missing recvmmsg and sendmmsg here.

Linux: Implement accept4 inside of socketcall

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
External/FEXCore/unittests/Emitter/ALU_Tests.cpp

Knocks out a few aliases on #2836

ARMEmitter: Add sbfiz/tst/ubfiz aliases

---

Source/Tools/FEXLoader/LinuxSyscalls/x32/Socket.cpp

These are the last two missing socketcall operations. Implementing them is mostly using the other implementation just in a helper function.

Linux: Implement {recv,send}mmsg inside of socketcall

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
External/FEXCore/unittests/Emitter/ALU_Tests.cpp

Crosses off another 2 aliases for #2836

ARMEmitter: Add bfc/bfxil aliases

---

.github/workflows/mingw_build.yml

Currently only does a build, doing a CI run means figuring out why TestHarnessRunner doesn't find libraries correctly.
I want to ensure we don't break building at least while sorting out the rest of this.

Github: Adds mingw build test workflow

---

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp

Goes from 41 instructions down to 20(!) instructions.
The primary optimization here is removing a bunch of dull inserts and
instead using zip logic to get the elements where we want them.
The previous implementation was trying to retain semantics around how
the original instruction is implemented, which makes no sense at all.
Unzip the even and odd elements and just do the saturating operations
directly!
Huge shoutout to @dougallj again, showing that I was thinking about this implementation far too much like an x86 developer.
Before:
```asm
0x0000ffff8f300c50  10ffffe0    adr x0, #-0x4 (addr 0xffff8f300c4c)
0x0000ffff8f300c54  f9005f80    str x0, [x28, #184]
0x0000ffff8f300c58  3dc010c4    ldr q4, [x6, #64]
0x0000ffff8f300c5c  6e60bae5    neg v5.8h, v23.8h
0x0000ffff8f300c60  6e60b886 …
```

OpcodeDispatcher: Optimize phsubsw/phaddsw

---

External/FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/SVEOps.inl
External/FEXCore/unittests/Emitter/SVE_Tests.cpp

Also adds the relevant aliases as well

ARMEmitter: Handle SVE CPY (immediate)

---

unittests/InstructionCountCI/H0F38.json

Some of these instructions haven't been fully audited, which is why they are classified as Unknown.

InstCountCI: Adds H0F38 table

---

unittests/InstructionCountCI/x87.json

Most of these instructions aren't optimal.
Even outside of the ones that jump out of the JIT they have a issues in most cases.

InstCountCI: Adds x87 table

---

unittests/InstructionCountCI/VEX_map1.json

None of the instructions here are optimal, a couple are close.
Will be splitting each of the map tables in to their own json files since each one can get fairly large.

InstCountCI: Adds VEX map1 tables

---

Scripts/InstructionCountParser.py
unittests/InstructionCountCI/VEX_map2.json

A handful of instructions are optimal, a few random ones are close, but
a lot aren't close.

InstCountCI: Adds FEX map2 tables 

---

unittests/InstructionCountCI/VEX_map_group.json

No instructions are optimal in this table.

InstCountCI: Adds VEX map group tables

---

unittests/InstructionCountCI/PrimaryGroup.json

A lot of things fairly close to optimal but not quite there.

InstCountCI: Adds Primary group tables

---

External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
Source/Tools/CodeSizeValidation/Main.cpp
unittests/InstructionCountCI/Secondary.json
unittests/InstructionCountCI/Secondary_32Bit.json

A decent number of instructions that are optimal but still quite a lot
that aren't.

InstCountCI: Adds secondary tables 

---

unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/Secondary_REP.json
unittests/InstructionCountCI/Secondary_REPNE.json

Most of these 128-bit vector ops are looking pretty good. Scalar and edge case ops aren't always optimal though.

InstCountCI: Adds secondary prefix tables

---

unittests/InstructionCountCI/SecondaryGroup.json
unittests/InstructionCountCI/SecondaryModRM.json
unittests/InstructionCountCI/VEX_map_group.json
unittests/InstructionCountCI/x87.json

Previous numbers were from the simulator which were slightly different.

InstCountCI: Update tests from actual ARM64 device

---

FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/InstructionCountCI/H0F38.json
unittests/InstructionCountCI/VEX_map2.json

This was...surprisingly bad. I blame myself entirely.

OpcodeDispatcher: Optimize phsub 

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/InstructionCountCI/Secondary.json
unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/VEX_map1.json

This is actually fairly trivial looking at it.
MMX and SSE implementations are now optimal.

OpcodeDispatcher: Optimize pmaddwd 

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/Secondary_REPNE.json
unittests/InstructionCountCI/VEX_map1.json

This makes the SSE version optimal.
This dramatically improves the AVX version as well

OpcodeDispatcher: Optimize hsubp 

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/InstructionCountCI/DDD.json

Turns out this can be even more optimal.

OpcodeDispatcher: Optimize PFNACC 

---

unittests/InstructionCountCI/Secondary_OpSize.json

These were all optimal. Fixed now.

InstCountCI: Fix some mislabeled instructions

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
unittests/InstructionCountCI/Secondary.json
unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/VEX_map1.json

MMX and SSE versions are now optimal.

OpcodeDispatcher: Optimizes scalar movd/movq

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/InstructionCountCI/Secondary_REPNE.json

OpcodeDispatcher: Optimize movddup from register

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/ASM/OpSize/66_50.asm
unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/VEX_map1.json

I'd consider this optimal now.
Thanks to @dougallj for the optimization idea again!

OpcodeDispatcher: Optimize 128-bit movmaskpd 

---

FEXCore/Source/Interface/IR/Passes/RAValidation.cpp

RAValidation was making an assumption that GPR register class would only have up to 16 registers for either SRA or dynamic registers.
When running a 32-bit application we allow 17 GPRs to be dynamically allocated, since we can take 8 back from SRA in that case.
Just split the two classes in the RAValidation pass since they will never overlap their allocation.
Fixes validation in `32Bit_Secondary/15_XX_0.asm` locally that changed behaviour due to tinkering.

IR: Fixes RAValidation for 32-bit applications

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
FEXCore/include/FEXCore/IR/IREmitter.h

You hold no power here IR operation.

IR: Removes sext IR helper

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
FEXCore/include/FEXCore/IR/IREmitter.h

This one was fairly involved so PRing it alone.

IR: Removes implicit sized lshl

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
FEXCore/include/FEXCore/IR/IREmitter.h

This one was fairly involved so PRing it alone.

IR: Removes implicit sized lshr

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
FEXCore/include/FEXCore/IR/IREmitter.h

This one was fairly involved so PRing it alone.

IR: Removes implicit sized or

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
FEXCore/include/FEXCore/IR/IREmitter.h

A little bit of an easier one.

IR: Removes implicit sized andn

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
FEXCore/include/FEXCore/IR/IREmitter.h

This one is a bit of a mess, looking forward to coming back and cleaning this up.

IR: Removes implicit sized bfe

---

FEXCore/Source/Interface/IR/Passes/ConstProp.cpp

FEX has a problem with large blocks that uses a ton of constants spread throughout the block. Once a block gets large enough with enough constants that have large live ranges, FEX slows down to unusable speeds due to the register allocator spending more time calculating node interferences than anything else in the program.
This adds a little heuristic to ensure that constants aren't reused if the previous value is past a certain distance threshold. This threshold works well enough that XeSS's pedantic initialization code doesn't have issues now. See https://github.com/FEX-Emu/FEX/issues/2688 for more information about that.
FEX itself should work to remove bad constant usages to make this pass less necessary anyway. In most cases we are materializing duplicated 0, 1, and masks which could …

ConstProp: Adds constpool distance heuristic

---

FEXCore/Source/Interface/Core/Core.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
unittests/ASM/Primary/Primary_85.asm
unittests/ASM/Primary/Primary_A9.asm
unittests/ASM/PrimaryGroup/3_F7_00.asm
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/Primary_32Bit.json
unittests/InstructionCountCI/Secondary.json

a @dougallj brilliance. on top of #3058 and continues the work logically started in #3038

Defer second XOR for AF

---

FEXCore/Source/Interface/Core/Core.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
unittests/InstructionCountCI/H0F38.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/Primary_32Bit.json
unittests/InstructionCountCI/Secondary.json
unittests/InstructionCountCI/SecondaryGroup.json
unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/Secondary_REP.json
unittests/InstructionCountCI/VEX_map1.json
unittests/InstructionCountCI/VEX_map2.json
unittests/InstructionCountCI/x87.json

Defer PF calculation completely

---

Scripts/generate_doc_outline.sh

Otherwise all of the FEXCore docs get deleted.

Scripts: Update generate_doc_outline for moved FEXCore

---

FEXCore/Source/Interface/Config/Config.json.in
FEXCore/Source/Interface/Core/HostFeatures.cpp
FEXCore/include/FEXCore/Core/HostFeatures.h

Currently unused but at least detect the feature so that our Arm64 JIT can use it in the future.

HostFeatures: Detect FlagM/2

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/VEX_map1.json

This one is very satisfying since there are only four variants and each
one of them converts to a single instruction.
~~Needs https://github.com/FEX-Emu/FEX/pull/3088 merged first~~

OpcodeDispatcher: Optimize shufpd

---

FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp
FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/IR/IR.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/Primary_32Bit.json

Optimize out carry invert for DEC

---

FEXHeaderUtils/FEXHeaderUtils/Filesystem.h
FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
FEXHeaderUtils/FEXHeaderUtils/SymlinkChecks.h
FEXHeaderUtils/FEXHeaderUtils/Syscalls.h
FEXHeaderUtils/FEXHeaderUtils/TodoDefines.h
FEXHeaderUtils/FEXHeaderUtils/TypeDefines.h

Added with `sed -i '1 i\\/\/ SPDX-License-Identifier: MIT' *.h`

FHU: Prepend SPDX identifier

---

unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json

Noticed these were missing
Will effect #3147

InstCountCI: Adds negative immediate primary tests

---

ThunkLibs/libvulkan/libvulkan_interface.cpp

Moving some entries around I managed to delete one. Fixes Vulkan thunks.

Thunks: Oops deleted an entry point

---

.github/workflows/instcountci.yml

Otherwise features get filled out weirdly.

github: Enables Vixl simulator on x86 host for instcountci

---

FEXCore/Source/Interface/Core/CPUID.cpp

CPUID: Adds some missing cpu core names

---

FEXCore/Source/Interface/Core/ArchHelpers/CodeEmitter/ALUOps.inl
FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/IR/IR.json
FEXCore/unittests/Emitter/ALU_Tests.cpp

Safe subset pulled from the big pr

Preparatory patches for nzcv

---

unittests/FEXLinuxTests/tests/CMakeLists.txt
unittests/FEXLinuxTests/tests/signal/into.32.cpp
unittests/FEXLinuxTests/tests/signal/invalid_int.cpp
unittests/FEXLinuxTests/tests/signal/signal_flags.cpp
unittests/FEXLinuxTests/tests/signal/sigtest_siginfo.32.cpp
unittests/FEXLinuxTests/tests/signal/sigtest_siginfo.64.cpp

ATT is maddening and a unittest I'm writing was going to be a nightmare.

FEXLinuxTests: Compile tests with masm=intel

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp

Needed to avoid breaking the world w.r.t nzcv
Not the most idiomatic C++ sol'n in the world but gets the job done.

Add helper for deriving ops by opcode

---

unittests/InstructionCountCI/FlagM/HotBlocks_32Bit.json

Sonic Mania is a 32-bit game, it shouldn't be running its assembly as 64-bit.

InstCountCI: Moves Sonic Mania code to 32-bit file

---

Scripts/InstallFEX.py

Forgot to update this as our supported Ubuntu distros changed.

Scripts: Updates InstallFEX with supported Ubuntu versions

---

FEXCore/Source/Interface/Core/CPUBackend.cpp

This will result in FEX not being able to allocate executable memory. We can use shared memory in the future to work around this but for now we don't support that as a fix.

FEXCore: Warn if MDWE is set

---

FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp

If the Dst register is allocated as VectorIndices or VectorTable, using Dst as an operand to perform the tbx operation will result in an error. For example:
%131(FPR0) i128 = LoadNamedVectorIndexedConstant u8:Tmp:RegisterSize, #0x6, #0xaa0 
%132(FPR0) i128 = VTBX1 u8:Tmp:RegisterSize, %129(FPRFixed6) i32v4, %126(FPRFixed10) i16v8, %131(FPR0) i128 
Since the tbx instruction's destination register is also the original operand, this is consistent with the semantics of VTBX1. Therefore, directly using VectorSrcDst as the destination operand for the tbx instruction is safe.

JIT: Fixes broken register in VTBX1

---

FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
Source/Tools/LinuxEmulation/VDSO_Emulation.cpp

I guess this was handled by brk things before.

Fixes some new glibc allocations that cropped up

---

Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp

Previously missing files would result in a segmentation fault.

Check that path arguments to TestHarnessRunner exist

---

ThunkLibs/include/common/Host.h

Another minor fix to https://github.com/FEX-Emu/FEX/pull/3373 : `fex_apply_custom_repacking_exit` may only be called for structs. This wasn't hit in practice even in my WIP branch, but could have caused the library glue code to fail to compiling.

Library Forwarding: Don't attempt custom repacking for non-struct types

---

FEXCore/Source/Interface/Core/Frontend.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/IR/IRParser.cpp
FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
FEXCore/Source/Utils/ArchHelpers/Arm64.cpp
Source/Tools/CommonTools/HarnessHelpers.h
Source/Tools/FEXRootFSFetcher/Main.cpp

scan-build found a few dead stores that can be easily cleaned-up

Code cleanup - mainly dead store removal; NFC

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/InstructionCountCI/Atomics.json
unittests/InstructionCountCI/Primary.json

Improve XCHG operations

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp

Patch suggested by @Sonicadvance1

Clean up access to possible nullptr

---

FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/IR/IR.json
FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
unittests/InstructionCountCI/FlagM/Primary.json
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json

A few commits I had lying around on random branches, longing for merge.

Optimize TST

---

FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/IR/IR.json
FEXCore/Source/Interface/IR/PassManager.cpp
FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
unittests/InstructionCountCI/Atomics.json
unittests/InstructionCountCI/FlagM/Atomics.json
unittests/InstructionCountCI/FlagM/FlagOpts.json
unittests/InstructionCountCI/FlagM/HotBlocks_32Bit.json
unittests/InstructionCountCI/FlagM/Primary.json
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json

Finally felt good enough to type this guy up. This addresses the Sonic silly block and lays the foundation for even more juicy NZCV work. On top of #3408 , that one is smol and will land first

Add NZCV+PF/AF optimization pass

---

FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp
ThunkLibs/include/common/Host.h

This is required for host-side calls to guest functions on 32-bit guests. Since the host stack is allocated before FEX blocks memory inaccessible to the guest, the guest would otherwise fail to read the packed argument data.
New interfaces are added to Host.h for querying and changing the guest stack position. This is combined with placement new to create the `PackedArguments` as if it were a regular stack allocation.
The change renders one of the workarounds added in #3309 obsolete, fixing a big performance bottleneck for 32-bit guests:
> ~~As a transitional measure, we allocate a temporary memory page and relocate argument data to it whenever a host->guest callback is invoked. **This has a huge performance impact and makes forwarding of 32-bit libraries prohibitively slow**.~~
Ready for …

Library Forwarding: Allocate packed arguments on the guest stack if needed

---

Source/Tools/LinuxEmulation/VDSO_Emulation.cpp

Ever since #3406 this has been crashing. Struct tail padding was saving this before.

Fixes VDSO crash in 64-bit code

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp

Add and use some helpers to make less error prone, before we go adding new bugs soon.

Cleanup NZCV metadata

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
unittests/InstructionCountCI/Atomics.json
unittests/InstructionCountCI/FlagM/Atomics.json
unittests/InstructionCountCI/FlagM/FlagOpts.json
unittests/InstructionCountCI/FlagM/Primary.json
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/FlagM/Secondary.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/Secondary.json

Simplify CalculateAF

---

unittests/InstructionCountCI/Crypto/H0F3A.json
unittests/InstructionCountCI/VEX_map3.json

Removes a commit from our fork.
Adds pmull to their implementation which changes instcountci results.

Update vixl 

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
unittests/InstructionCountCI/Atomics.json
unittests/InstructionCountCI/FlagM/Atomics.json
unittests/InstructionCountCI/FlagM/HotBlocks_32Bit.json
unittests/InstructionCountCI/FlagM/Primary.json
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/FlagM/Secondary.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/Secondary.json

Just browsing instcountci for low hanging fruit

Misc little opts

---

Source/Tools/FEXLoader/FEXLoader.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.h

I remember seeing some application last year where they closed a FEX owned FD but now I don't remember what it was. This can really mess us up so add some debug tracking so we can try and find it again.
Might be something specifically around flatpack, appimage, or chrome's sandbox. I have some ideas about how to work around these problems if they crop up but need to find the problem applications again.

FEXLoader: Add some debug-only tracking for FEX owned FDs

---

FEXCore/Source/Interface/Config/Config.cpp
FEXCore/Source/Interface/Config/Config.json.in
FEXCore/Source/Utils/Config.h
FEXCore/Source/Utils/Telemetry.cpp

Telemetry: Allow redirecting directory that data is written to

---

FEXCore/Source/Interface/Config/Config.json.in
Source/Tools/FEXLoader/FEXLoader.cpp

I find myself reimplementing this nearly monthly. Actually codify it so I can stop reimplementing it.

FEXLoader: Add a way to sleep a process on startup

---

Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp

Same situation as the last stack leak memory fix, this is fairly tricky since it is dealing with stack pivoting. Fixes the memory leak around pthread stack allocations, making memory usage lower for applications that constantly spin-up and destroy threads (Like Steam).
We need to let glibc allocate a minimum sized stack (128KB and we can't control it) to work around a race condition with DTV/TLS regions. This means we need to do a stack pivot once the thread starts executing.
We also need to be careful because the `PThread` object is deleted inside of the execution thread, which was resulting in a use-after-free bug.
There are definitely some more memory leaks that I'm still fighting, and I have noticed in my abusive thread creation program that we might want to change some jemalloc …

Linux/Threads: Fixes a stack memory leak for pthreads

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/PrimaryGroup.json

commits from #3386 that can go in now

OpcodeDispatcher: clean up shifts

---

.git-blame-ignore-revs

To enable it:
`git config blame.ignoreRevsFile .git-blame-ignore-revs`

Create .git-blame-ignore-revs with whole-tree reformat sha

---

FEXCore/Source/Interface/IR/IREmitter.h
FEXCore/Source/Interface/IR/Passes/ConstProp.cpp

More readable, will probably be used in new RA

Factor out SetWriteCursorBefore

---

FEXCore/Source/Interface/Core/CPUID.cpp

From https://github.com/llvm/llvm-project/pull/91022
Easy enough

CPUID: Adds Qualcomm Oryon product name

---

FEXCore/Source/Interface/Core/Core.cpp
FEXCore/Source/Interface/IR/PassManager.cpp
FEXCore/Source/Interface/IR/PassManager.h
FEXCore/Source/Interface/IR/Passes.h
FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp

RA should not depend on whether we support AVX, that's a huge layering
violation! and fortunately, it does not.
Follow on from SRA work

RegisterAllocationPass: drop AVX flag

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h

Here BitOffset can have values higher than 32.

Fix left shift undefined behaviour

---

FEXCore/Source/Interface/IR/Passes/RAValidation.cpp

Use erase-remove idiom to remove element

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
unittests/InstructionCountCI/Atomics.json
unittests/InstructionCountCI/FlagM/Atomics.json
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/FlagM/Secondary.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/Secondary.json

small instcountci win already, and mitigates some regression from new RA

OpcodeDispatcher: reorder some moves

---

FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/IR/IR.json
unittests/InstructionCountCI/FEXOpt/MultiInst.json
unittests/InstructionCountCI/FlagM/FlagOpts.json
unittests/InstructionCountCI/FlagM/HotBlocks_32Bit.json
unittests/InstructionCountCI/FlagM/SecondaryGroup.json
unittests/InstructionCountCI/FlagM/SecondaryModRM.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/SecondaryGroup.json
unittests/InstructionCountCI/SecondaryModRM.json

Was experimenting with pairs, this is not what we want long term but gets us closer in terms of the refactoring.

Slightly improve pair coalescing + memcpy fix from RA branch

---

CodeEmitter/CodeEmitter/VixlUtils.inl
FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp

Removes warnings

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
unittests/InstructionCountCI/Atomics.json
unittests/InstructionCountCI/FlagM/Atomics.json
unittests/InstructionCountCI/FlagM/Primary.json
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/FlagM/VEX_map2.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/VEX_map2.json

fuse in PF move. on top of #3673

Optimize logical flags

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/InstructionCountCI/FlagM/Secondary.json
unittests/InstructionCountCI/Secondary.json

on top of #3680 for instcountci conflicts

optimize shld

---

.github/workflows/ccpp.yml
.github/workflows/glibc_fault.yml
.github/workflows/hostrunner.yml
.github/workflows/instcountci.yml
.github/workflows/mingw_build.yml
.github/workflows/vixl_simulator.yml

Use of HOSTFEATURES replaced use of FEX_ per host feature flag.

Use FEX_HOSTFEATURES instead of FEX_ENABLEAVX

---

Source/Tools/FEXConfig/Main.cpp

FEXConfig: Clear up TSO emulation string

---

FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp

JIT: delete silly assert

---

FEXCore/Source/Interface/Core/Core.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp

No functional changes here, just some code motion / deletion from #3703 which probably won't land *super* soon.

Clean ups from my RCLSE branch

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Crypto.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp

AVX128 is going to slam this, so make it more ergonomic.

OpcodeDispatcher: refactor zero vector loads

---

Scripts/update_instcountci.sh

This is helpful for devs working on FEXCore, I've been using this locally but it might make sense to stick it in tree.

Scripts: add update_instcountci.sh script

---

FEXCore/Source/Interface/Core/HostFeatures.cpp

The Oryon is the first CPU we know of that implemented support for the RNG extension. It also has an errata where reading the RNDRRS register never returns success. X86's RDSEED guarantees forward progress with enough retries.
When an x86 processor messed this up at one point, some Linux systems would infinite loop (presumably when something in boot was filling an entropy pool). This required a microcode change to fix that processor.
The rdseed unittest infinite loops on this platform if RNG was exposed.

HostFeatures: Work around Qualcomm Oryon RNG errata

---

FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
unittests/InstructionCountCI/AFP/SVE256/Secondary.json
unittests/InstructionCountCI/AFP/SVE256/Secondary_REP.json
unittests/InstructionCountCI/AFP/SVE256/Secondary_REPNE.json
unittests/InstructionCountCI/AFP/Secondary.json
unittests/InstructionCountCI/AFP/Secondary_REP.json
unittests/InstructionCountCI/AFP/Secondary_REPNE.json
unittests/InstructionCountCI/AFP/VEX_map1.json
unittests/InstructionCountCI/Secondary_REP.json
unittests/InstructionCountCI/Secondary_REPNE.json
unittests/InstructionCountCI/VEX_map1.json

Fixes AFP.NEP handling on scalar insertions

---

FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
unittests/ASM/X87/DD_D0_2.asm
unittests/ASM/X87_F64/DD_D0_2_F64.asm
unittests/InstructionCountCI/FlagM/x87.json
unittests/InstructionCountCI/FlagM/x87_f64.json
unittests/InstructionCountCI/x87.json
unittests/InstructionCountCI/x87_f64.json

Currently its not being set and attached test fails.

Set tag properly in X87 FST(reg)

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp

Refactors some of the base vector helpers so that AVX128 can reuse them.

Vector: Helper refactorings

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp

Also the Binary/Unary helper since this is the first use of it.

AVX128: Move moves!

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp

AVX128 will use this, it's not SSE-specific.

OpcodeDispatcher: refactor Comiss helper

---

FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/IR/IR.json

What we have here is primarily, inserts, extracts, conversions, multiplies, a subtract, and a horizontal subtract.

AVX128: More instructions

---

FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp

This was a premature optimization and currently breaks. Just remove it for now.

Arm64: Remove contiguous masked element optimization

---

FEXCore/Source/Interface/Core/CPUID.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
unittests/ASM/Disabled_Tests_Simulator
unittests/ASM/VEX/vpclmulqdq_256.asm
unittests/InstructionCountCI/VEX_map2.json

Based on top of #3747
We're getting to the point of wrapping up all the AVX specific instruction implementations here.

AVX128: More instructions Part 4

---

FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
FEXCore/Source/Interface/Core/HostFeatures.cpp
FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp

HostFeatures: Always disable AVX in 32-bit mode to protect from stack overflows

---

Source/Tools/LinuxEmulation/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp

Some applications don't measure rdtsc correctly and instead use cpuinfo to get the CPU core's base clock speed. Which for most x86 CPUs is the base clock speed which also matches their cycle counter speed.
Did this as a quick test to see if this would help `Unbound: Worlds Apart` stuttering while BinaryNinja was disassembling the binary.
Turns out the game doesn't use cpuinfo for its cycle counter speed determination, but it is good to implement this regardless.
Orin:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Cortex-A78AE
stepping        : 0
microcode       : 0x0
cpu MHz         : 4000.000
cache size      : 512 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 12
apicid          : 0 …
```

Linux: Calculate cycle counter frequency for cpuinfo

---

Source/Windows/Common/TSOHandlerConfig.h
Source/Windows/WOW64/Module.cpp

This will also be used in the arm64ec backend

Windows: Commonise TSOHandlerConfig

---

FEXCore/include/FEXCore/Utils/AllocatorHooks.h

FEX allocations can get in the way of allocations that are 4gb-limited even in 64-bit mode (i.e. those from LuaJIT), so allocate starting from the top of the AS to prevent conflicts.

AllocatorHooks: Allocate from the top down on windows

---

FEXCore/Scripts/json_ir_generator.py

Scripts: drop remnant of IR parser

---

Scripts/guest_test_runner.py
unittests/gcc-target-tests-64/Disabled_Tests
unittests/gcc-target-tests-64/Known_Failures

It's exactly the same as Known_Failures.

Remove Disabled_Tests file

---

FEXCore/Scripts/json_ir_generator.py
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/IR/IR.json
FEXCore/Source/Interface/IR/IREmitter.h

This is a followup to #3869 . Thanks for @alyssarosenzweig for most of the work here.
This is a requirement for #3547 and includes all of the used IR ops there.

X87 Stack Ops Auto-marking

---

FEXCore/Scripts/json_ir_generator.py

will be used to clean up the x87 pass

Autogenerate LoweredX87() query, misc json_ir_generator cleanup in the area

---

FEXCore/include/FEXCore/Utils/ThreadPoolAllocator.h

A disowned buffer could be unclaimed or claimed by a different thread in the time between the !IsFree check and locking the allocation mutex. Fix this and prevent such errors in the future by always checking ownership with the allocator locked before attempting to unclaim buffers.

FixedSizePooledAllocation: Fix a race when unclaiming disowned buffers

---

FEXCore/include/FEXCore/Utils/AllocatorHooks.h

These issues end up being tolerated by wine but not actual windows.

AllocatorHooks: Correct memory API usage on Windows

---

FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp

x87StackOptimizationPass: Default initialise StackMemberInfo members

---

Source/Common/Config.cpp

Saw this vector was getting initialized at runtime, sticking around, and installing an atexit handler. This is completely unnecessary, just use the OPT_BASE handler directly to walk the environment variable names.

Config: Removes a static vector initializer

---

Source/Common/Config.cpp

These two maps used for environment lookup translations were getting
globally initialized and then registers with atexit handlers.
Switch over to a constexpr array and just do linear scans. This plus
short-circuiting the environment loader so it skips all entries that
don't start with `FEX_` has the side benefit of cutting the CPU time to
1/10th the time.
This plus https://github.com/FEX-Emu/FEX/pull/3917 removes the global static initializers entirely from
this file.

Config: Converts two LUT maps over linear scan arrays

---

Source/Windows/ARM64EC/Module.cpp

Most syscalls on Windows are done by calling into their NTDLL thunks, however some DRMs parse out their numbers from NTDLL and directly call them. Support this by redirecting to their entry thunks in the FEX syscall handler.

ARM64EC: Handle direct syscall instructions

---

FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
FEXCore/include/FEXCore/Utils/SignalScopeGuards.h

The async signal issues this handles do not exist on Windows.

FEXCore: Drop deferred signal handling on Windows

---

Scripts/aarch64_fit_native.py

Apparently I messed this up in testing, is now fixed.

Scripts: Fix issue in aarch64_fit_native

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
unittests/InstructionCountCI/FlagM/Secondary.json
unittests/InstructionCountCI/FlagM/SecondaryGroup.json
unittests/InstructionCountCI/Secondary.json
unittests/InstructionCountCI/SecondaryGroup.json

Optimize BTC

---

Source/Windows/ARM64EC/Module.cpp
Source/Windows/Common/Exception.h
Source/Windows/WOW64/Module.cpp

Several fixes carried over from the ARM64EC backend

WOW64: Improve exception handling

---

Source/Tools/FEXRootFSFetcher/Main.cpp

FEXRootFSFetcher: Allow UI override through options

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.h
unittests/InstructionCountCI/AVX128/VEX_map1.json
unittests/InstructionCountCI/Secondary.json
unittests/InstructionCountCI/Secondary_OpSize.json
unittests/InstructionCountCI/VEX_map1.json
unittests/InstructionCountCI/x87_f64.json

should help perf on Billy's x13s.

Optimize AXFLAG-less systems

---

Source/Tools/LinuxEmulation/LinuxSyscalls/x32/EPoll.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/FD.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/IO.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Info.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Msg.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Sched.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Semaphore.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Signals.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x64/EPoll.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Semaphore.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Signals.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Time.cpp

Does a decent number of syscalls, but not all of them. There's only so many I can do at a time before I start becoming mindnumb.

Adds more syscall memory access checks

---

FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
FEXCore/Source/Interface/IR/IR.json

needs to be modelled explicitly or else we lose information when translating

IR: fix scalar FMA tied sources

---

.gitignore

I symlink build -> Build for YouCompleteMe.

gitignore: ignore build symlink

---

FEXCore/include/FEXCore/Core/Context.h

All uses of this have been removed.

FEXCore: Delete ThreadsState struct

---

FEXCore/Source/Interface/Core/CPUBackend.h
FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
FEXCore/docs/CustomCPUBackend.md

Some of these were bad ideas, some ideas were something we effectively grew out of.

CPUBackend: Remove unused functions

---

FEXCore/Source/Interface/Config/Config.cpp

Reduces stack usage from ~1024 bytes to ~704 bytes and stops making a bunch of string copies when they can just be pointers instead.

Config: Be a bit smarter in ReloadMetaLayer

---

Source/Tools/LinuxEmulation/VDSO_Emulation.cpp

We have been relying on the
`YesIKnowImNotSupposedToUseTheGlibcAllocator` fault avoidance for a long while now. The plan was to rewrite the symbol fetching in the future to avoid this since VDSO is kind of special anyway.
That time is now, I have had this VDSO symbol parsing code living in a different project for a few months now and it is working great.
The basic things here are that the Linux kernel provides the VDSO mapping base pointer through the auxv value `AT_SYSINFO_EHDR`. We then need a minimal ELF parser that /only/ parses the dynamic symbol header (and accompanying string header).
Then it's a simple case of walking the symbol table and recording the pointers. Confirmed this fetches all the correct symbols (As I've been using it for a while already I already knew it worked.) …

VDSOEmulation: Stop using dlopen for VDSO

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
unittests/InstructionCountCI/FlagM/Primary_32Bit.json
unittests/InstructionCountCI/Primary_32Bit.json

9% decrease in node time across the series (both with and without multiblock). bit of everything. unfortunatley, no perceivable improvement in steam startup time :crying_cat_face:

speed up the JIT

---

unittests/InstructionCountCI/AFP/SVE256/Secondary_REP.json
unittests/InstructionCountCI/AFP/Secondary_REP.json
unittests/InstructionCountCI/AFP/VEX_map1.json

This was giving false changes on RPRES enabled HW.

Disable RPRES in instcounci files

---

FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/IR/IR.json
unittests/InstructionCountCI/FlagM/HotBlocks.json
unittests/InstructionCountCI/FlagM/Secondary.json
unittests/InstructionCountCI/SSE42_Strings.json
unittests/InstructionCountCI/Secondary.json

Just some random little things from looking at Secondary.json

Optimize bsf, bsr, register cmpxchg, pcmpistri

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h

OpcodeDispatcher: Convert address size helpers to use OpSize

---

FEXCore/Source/Interface/Core/Interpreter/Fallbacks/InterpreterFallbacks.cpp
FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
FEXCore/Source/Interface/Core/JIT/ConversionOps.cpp
FEXCore/Source/Interface/Core/JIT/EncryptionOps.cpp
FEXCore/Source/Interface/Core/JIT/JITClass.h
FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
FEXCore/Source/Interface/Core/JIT/VectorOps.cpp

JIT: Remove implicit OpSize conversions

---

Source/Tools/FEXServer/ProcessPipe.cpp

FEXServer: Fix auto-shutdown regression

---

FEXCore/Source/Interface/Core/JIT/MiscOps.cpp
unittests/InstructionCountCI/Primary.json

Fixes #4196
Would rather this do nothing at all than introduce any possibility of stutters.

Revert #4118

---

FEXCore/Source/Interface/Core/CPUID.cpp

This was declared twice in the list.

CPUID: Remove duplicated ARM Neoverse-N2

---

Source/Tools/FEXConfig/main.qml

FEXConfig: Fixes instcount not being editable by keyboard

---

Source/Windows/ARM64EC/Module.cpp
Source/Windows/Common/OvercommitTracker.h
Source/Windows/WOW64/Module.cpp

Windows: Fix wine check

---

unittests/ASM/Disabled_Tests

Skip 3DNow tests with precision issues

---

Source/Windows/ARM64EC/Module.cpp

ARM64EC: Set EC_ENTRY_CPUAREA_REG at inline SMC dispatcher entry

---

Source/Tools/LinuxEmulation/LinuxSyscalls/Seccomp/SeccompEmulator.cpp

If fcntl fails then report a log message, and fix a potential overflow before widen bug.

Seccomp: Fix a couple minor things.

---

FEXCore/Source/Interface/IR/IR.json

IR: Remove some static analysis warnings

---

FEXCore/Source/Interface/Core/JIT/AtomicOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/IR/IR.json
unittests/InstructionCountCI/FlagM/Secondary.json
unittests/InstructionCountCI/Secondary.json

Hey kid, want to see a sick trick?
Finally optimal codegen for 64-bit cmpxchg.

JIT: Optimize CAS

---

unittests/ASM/X87/DB_E8.asm
unittests/ASM/X87/DB_F0.asm
unittests/ASM/X87/DF_E8.asm
unittests/ASM/X87/DF_F0.asm

Add tests for F(U)COMI(P)

---

CodeEmitter/CodeEmitter/SVEOps.inl
FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
FEXCore/Source/Interface/Core/Frontend.h
FEXCore/Source/Interface/Core/JIT/AtomicOps.cpp
FEXCore/Source/Interface/Core/JIT/JITClass.h
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/IR/IR.h
FEXCore/Source/Interface/IR/IntrusiveIRList.h
FEXCore/Source/Interface/IR/PassManager.h
FEXCore/Source/Interface/IR/Passes/IRValidation.h
FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
FEXCore/include/FEXCore/Utils/File.h
Source/Common/Config.cpp
Source/Tools/CommonTools/PortabilityInfo.h
Source/Tools/FEXConfig/Main.cpp
Source/Tools/FEXLoader/ELFCodeLoader.h
Source/Tools/FEXRootFSFetcher/Main.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/GdbServer.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/Utils/Threads.h
Source/Tools/LinuxEmulation/LinuxSyscalls/x32/Types.h
Source/Tools/LinuxEmulation/LinuxSyscalls/x64/Types.h
ThunkLibs/Generator/data_layout.cpp
ThunkLibs/Generator/main.cpp

Various: More static analysis warnings cleanup

---

Source/Tools/LinuxEmulation/LinuxSyscalls/x32/IoctlEmulation.cpp

Fixes a new warning in clang-20 about using memmove on non-trivially copyable types.

IoctlEmulation: Stop using std::pair and memmove

---

FEXCore/Source/Interface/Config/Config.json.in
FEXCore/Source/Interface/Context/Context.h
FEXCore/Source/Interface/Core/Core.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/include/FEXCore/Core/Context.h
FEXCore/include/FEXCore/Utils/IntervalList.h
Source/Tools/FEXConfig/main.qml
Source/Windows/ARM64EC/Module.cpp
Source/Windows/Common/IntervalList.h
Source/Windows/Common/InvalidationTracker.cpp
Source/Windows/Common/InvalidationTracker.h
Source/Windows/Common/OvercommitTracker.h
Source/Windows/include/winnt.h

Needs some further testing but seems to work as is.

Implement PE volatile metadata support

---

Source/Common/Config.cpp
Source/Tools/FEXConfig/Main.cpp
Source/Tools/FEXRootFSFetcher/Main.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/FileManagement.cpp

Turn invalid JSON files into fatal errors.

Improve JSON file validation and error reporting

---

Source/Tools/LinuxEmulation/VDSO_Emulation.cpp

VDSOEmulation: Safe fallback if host VDSO can't be parsed

---

FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp

RA: small cleanups

---

FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
FEXCore/Source/Interface/Core/JIT/ConversionOps.cpp
FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
FEXCore/Source/Interface/Core/JIT/VectorOps.cpp

We can make these slightly less verbose.

JIT: Simplify SVE 256 operation asserts

---

Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp

Just a few things that got picked up.

Syscalls: Minor cleanup

---

FEXCore/Source/Interface/Config/Config.cpp

- unused includes, and
- unused arguments.

Remove some warnings from Config.cpp

---

FEXCore/Source/Interface/Core/Frontend.cpp

FEXCore/Frontend: Remove logically dead code

---

unittests/32Bit_ASM/X87/D9_F6.asm
unittests/32Bit_ASM/X87/D9_F7.asm
unittests/ASM/X87/D9_F6.asm
unittests/ASM/X87/D9_F7.asm
unittests/ASM/X87_F64/D9_F6_F64.asm
unittests/ASM/X87_F64/D9_F7_F64.asm

Followup to #4475.
Tests were not really testing the interesting instructions.

Update tests for fincstp and fdecstp

---

FEXCore/Source/Utils/Allocator/64BitAllocator.cpp

This was only used for working around our old CI machines and now that our minimum kernel requirement is 5.15 this isn't required anymore.

FEXCore/Allocator: Removes old workaround for kernel 4.17

---

CodeEmitter/CodeEmitter/ASIMDOps.inl

CodeEmitter: Fixes misaligned function

---

Source/Tools/CommonTools/HarnessHelpers.h
Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
Source/Tools/LinuxEmulation/VDSO_Emulation.cpp
Source/Tools/TestHarnessRunner/TestHarnessRunner.cpp
Source/Windows/ARM64EC/Module.cpp
Source/Windows/Common/InvalidationTracker.cpp
Source/Windows/Common/InvalidationTracker.h
Source/Windows/WOW64/Module.cpp
Source/Windows/include/winternl.h

Prerequisite for NX emulation, split apart since there's nothing tying them to being merged together.

Improve tracking of executable mappings

---

CodeEmitter/CodeEmitter/Buffer.h
FEXCore/Source/Interface/Core/JIT/JIT.cpp

JIT: Align JITCodeTail to native alignment

---

Source/Tools/LinuxEmulation/LinuxSyscalls/LinuxAllocator.cpp

in 32-bit mode, shmat allocates similarly to mmap, so shmdt should unmap those pages like munmap
unfortunately untested, as I have no means of testing right now

Make shmdt reset the unmapped pages in the 32-bit allocator

---

FEXHeaderUtils/FEXHeaderUtils/RingBuffer.h

I keep rewriting this thing when I want to see some history on something. Throw it in a FHU utility so I can stop wasting my time.

FHU: Add a non-block thread local ringbuffer

---

unittests/gcc-target-tests-32/CMakeLists.txt
unittests/gcc-target-tests-32/Disabled_Tests
unittests/gcc-target-tests-32/Known_Failures
unittests/gcc-target-tests-64/CMakeLists.txt
unittests/gcc-target-tests-64/Known_Failures

Run gcc target tests with block size 1

---

FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
FEXCore/Source/Interface/Core/JIT/AtomicOps.cpp
FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
FEXCore/Source/Interface/Core/JIT/ConversionOps.cpp
FEXCore/Source/Interface/Core/JIT/EncryptionOps.cpp
FEXCore/Source/Interface/Core/JIT/JIT.cpp
FEXCore/Source/Interface/Core/JIT/JITClass.h
FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
FEXCore/Source/Interface/Core/JIT/MiscOps.cpp
FEXCore/Source/Interface/Core/JIT/MoveOps.cpp
FEXCore/Source/Interface/Core/JIT/VectorOps.cpp
FEXCore/Source/Interface/IR/IR.h

clean up for now, should let me refactor more stuff but tbd.

JIT: stop using .ID() pattern

---

FEXCore/Source/Interface/Core/JIT/ALUOps.cpp
FEXCore/Source/Interface/Core/JIT/MoveOps.cpp

oops, missed a "/g" with th sed.

JIT: use .ID() even less

---

FEXCore/include/FEXCore/Utils/SignalScopeGuards.h
Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsSMCTracking.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/SyscallsVMATracking.h

Just some minor changes and rebrands to make this feel less like NIH and help with making it easier to parse what is going on while I work towards fixing #4557

SyscallsVMATracking: Minor cleanup

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp
unittests/InstructionCountCI/AVX128/VEX_map2_flagm.json
unittests/InstructionCountCI/Atomics.json
unittests/InstructionCountCI/FlagM/Atomics.json
unittests/InstructionCountCI/FlagM/Primary.json
unittests/InstructionCountCI/FlagM/PrimaryGroup.json
unittests/InstructionCountCI/FlagM/VEX_map2.json
unittests/InstructionCountCI/FlagM/x87-HalfLife.json
unittests/InstructionCountCI/Primary.json
unittests/InstructionCountCI/PrimaryGroup.json
unittests/InstructionCountCI/VEX_map2.json

some obvious opportunities to improve here! although mostly I want this to regression test my constprop rework.

InstructionCountCI: add more cases for mov 0/~0

---

Scripts/InstallFEX.py

This was added to the PPA last month.

Scripts/InstallFEX: Add plucky

---

CodeEmitter/CodeEmitter/ASIMDOps.inl
FEXCore/Source/Interface/Core/CPUBackend.h
FEXCore/Source/Interface/Core/Core.cpp
FEXCore/Source/Interface/Core/JIT/JIT.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp
Source/Tools/CodeSizeValidation/Main.cpp
Source/Tools/FEXLoader/FEXLoader.cpp
Source/Tools/LinuxEmulation/VDSO_Emulation.cpp

NFC, just clearing out some warnings.

Some static code analysis fixes

---

Source/Windows/ARM64EC/Module.cpp

Rather than relying on wine-specific alphabetical behaviour, that has since been changed. Rely on their addresses being sorted which is more stable behaviour also present in Windows.
Supersedes #4625 
cc: @AndreRH

ARM64EC: Rely on syscall export sorting for deriving their IDs

---

FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
Source/Tools/LinuxEmulation/ArchHelpers/MContext.h
Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/SignalDelegator/GuestFramesManagement.cpp
Source/Windows/ARM64EC/Module.S
Source/Windows/ARM64EC/Module.cpp
Source/Windows/WOW64/Module.cpp

Fixes peggle deluxe (with an additional wine patch) under wow64. Also moves slightly closer to linux inline SMC support

Inline SMC fixes and support for WOW64

---

Readme.md

Support was added in 1786c2f1579ada1d99e04dc6bfce3faeed86a256

Readme.md: Mention Ubuntu 25.04 as supported

---

Source/Windows/WOW64/Module.cpp

Some compiler versions generated FP-relative operations before loading it from the stack, which would crash wine when APCs were used.

WOW64: Wrap BTCpuSimulate to ensure correct unwinding

---

FEXCore/Source/Utils/ArchHelpers/Arm64.cpp

Arm64: Remove pair usage in 128-bit loader

---

FEXCore/Source/Interface/Core/Addressing.cpp
FEXCore/Source/Interface/Core/JIT/BranchOps.cpp
FEXCore/Source/Interface/Core/JIT/JIT.cpp
FEXCore/Source/Interface/Core/JIT/JITClass.h
FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp

Local JIT translation time wins

---

Source/Tools/FEXLoader/ELFCodeLoader.h

When loading an ELF file (usually PT_EXEC), we would have BSS regions that ended up in the high pages of the address space. We would then attempt mapping BRK after whatever the highest address ending up being.
This was problematic because we used `MAP_FIXED` which means that the BRK region could cross in to 64-bit address space, overwrite VDSO, overwrite the stack, vsyscall, maybe a couple of other things.
Instead of letting that happen, reorder some of the logic so that in `LoadElfFile` will ensure the full `BRK_SIZE` is allocated (or return zero) and then we can ensure we're never overwriting other various memory regions.
This doesn't fix two fundamental issues that FEX has with brk:
* If BRK gets mapped below the ELF, that should mean it isn't mapped at all
* Linux-isms, doubt this …

ELFCodeLoader: Fixes BRK allocation with non-PT_DYN ELF files

---

FEXCore/Source/Common/StringConv.h

Same behavior, but we condense all of the integral handling into one place.

StringConv: Merge integral-handling facilities together

---

FEXCore/Source/Interface/Core/JIT/MiscOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/IR/IR.h
FEXCore/Source/Interface/IR/IR.json
FEXCore/Source/Interface/IR/IRDumper.cpp
FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp

Same thing minus an extra struct lingering around.

IR: Convert FenceType to an enum class

---

FEXCore/Source/Interface/Core/JIT/ConversionOps.cpp
FEXCore/Source/Interface/Core/JIT/MiscOps.cpp
FEXCore/Source/Interface/Core/JIT/VectorOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/IR/IR.h
FEXCore/Source/Interface/IR/IR.json
FEXCore/Source/Interface/IR/IRDumper.cpp
FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp

Same behavior, but more compact

IR: Convert rounding modes to enum class

---

FEXCore/Source/Interface/Core/Addressing.cpp
FEXCore/Source/Interface/Core/Addressing.h
FEXCore/Source/Interface/Core/JIT/MemoryOps.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/AVX_128.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87F64.cpp
FEXCore/Source/Interface/IR/IR.h
FEXCore/Source/Interface/IR/IR.json
FEXCore/Source/Interface/IR/IRDumper.cpp
FEXCore/Source/Interface/IR/IREmitter.h
FEXCore/Source/Interface/IR/Passes/x87StackOptimizationPass.cpp

Gets rid of another wrapper struct.

IR: Convert MemOffsetType to enum class

---

FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher.h
FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
FEXCore/Source/Interface/IR/IREmitter.h

OpcodeDispatcher: Move off implicit _Select

---

Source/Tools/LinuxEmulation/LinuxSyscalls/ThreadManager.cpp

SHM stats and CallRet stack was accidentally using system mmap which means it would take VA space from the guest. Ensure it uses the Allocator helpers so that doesn't happen.
Gives 32-bit guests 8-ish megabyte of VA space back.

ThreadManager: Fix mmap usage to not take guest space

---

FEXCore/include/FEXCore/HLE/SourcecodeResolver.h
Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.cpp
Source/Tools/LinuxEmulation/LinuxSyscalls/Syscalls.h

\+ a minor change to pass string_views by value.

SysCalls: Remove unimplemented prototypes
