External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h
Currently only support partially ignoring for overlay 0x66, this means
we only support no overlay at all and 0x66. Using only two bits of flag
space rather than 3.
If we find an instruction family that supports a different one then we
should break it out to three independent flags. Keeping it two until
then
Unit tests to ensure this keeps working is forthcoming
=> Implements an x86Table flag to partially ignore overlays

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Primary/Primary_A6.asm, unittests/ASM/Primary/Primary_A6_REP.asm, unittests/ASM/Primary/Primary_A6_REPNE.asm, unittests/ASM/Primary/Primary_A6_REP_Equal.asm, unittests/ASM/Primary/Primary_A6_REP_Smaller.asm, unittests/ASM/Primary/Primary_A6_REP_down.asm, unittests/ASM/Primary/Primary_A6_REP_down_Equal.asm, unittests/ASM/Primary/Primary_A6_down.asm, unittests/ASM/Primary/Primary_A7_dword.asm, unittests/ASM/Primary/Primary_A7_dword_down.asm, unittests/ASM/Primary/Primary_A7_qword.asm, unittests/ASM/Primary/Primary_A7_qword_down.asm, unittests/ASM/Primary/Primary_A7_word.asm, unittests/ASM/Primary/Primary_A7_word_down.asm
Also implements support for CMPS with no repeat prefix and the REPNE prefix.
Isn't all encompassing for the unit tests, there are still some cases we aren't testing.
=> Adds unit tests for the CMPS instruction family

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json
In some places, Neg meant logical one's complement negation.
In others it meant arithmetic two's complement negation.
As both x87 and aarch64 have neg instructions that do two's complement negations, we will standardise on that.
Additionally we will add a Not_IR op for one's complement.
=> Fix Neg IR_OP, Add Not IR_OP

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json
Fixes issue #14.
A lot of these were named in very confusing ways.
Makes them very explicit about what the operation is doing
=> Cleans up and renames the CVT ops

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
Don't do DCE inside the pass, let the DCE pass actually handle this.
This was causing later passes to crash
=> Fixes RCLSE pass generating bad IR

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, unittests/ASM/REP/F3_BC.asm
In the case that we were TZCNT was passed a zero input and the register size was <64bit then we were returning a wrong value.
Makes the x86 JIT handle the smaller sizes.
Updates the unit test so it tests that case.
=> Fixes FindTrailingZeros IR op in x86 JIT

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
This puts the x86-64 JIT on feature parity for the number of passed unit tests as the Interpreter.
=> x86-64 JIT unit test fixes

External/SonicUtils/CMakeLists.txt, External/SonicUtils/Source/VM_Noop.cpp
This is necessary to fix building on non-x86 platforms.
=> Adds noop VM source file

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
This gets the AArch64 JIT to feature parity with the x86 JIT on unit test passing
=> Get AArch64 JIT to feature parity of the x86 JIT

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp
Lets the LLVM pass the unit tests as well as the interpreter and other
JITs
=> Implements all the ops missing in the LLVM JIT

Scripts/testharness_runner.py, unittests/ASM/CMakeLists.txt, unittests/ASM/Known_Failures
This will allow us to add unit tests that have known failures like
unsupported features
Additionally if the test passes and is on the known failure list then it
still fails since its state has changed
=> Adds known failure support to unit test runner

External/FEXCore/CMakeLists.txt, External/FEXCore/Source/CMakeLists.txt
This fixes an issue with older cmake versions where it throws an error
if the install target was declared in a different cmake file
Newer cmake doesn't seem to care
=> Moves FEXCore install target to the FEXCore/Source directory

Source/Tests/TestHarnessRunner.cpp
It doesn't need 64GB of virtual memory, so knock it down to its minimum
virtual memory required
=> Make the unit test runner allocate less SHM space

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
No need to zero the register when we are going to logical shift the
upper 64bits to the lower 64bits anyway
=> Minor optimization in vsqxtun for x86

unittests/ASM/CMakeLists.txt
Rather than an integer between 0 and 8, just give each argument
configuration a short descriptor.
This makes it easier to parse the error output
=> Make unit test names more descriptive about what arguments are passed

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json
Moving from LLVM 8 to LLVM 9 caused unit tests to fail.
I didn't notice since my desktop was on LLVM 8 while the unit test runner was on LLVM 9.
We will want to keep an eye on LLVM 10 once it releases soon as well.
=> LLVM 9 fixes

External/SonicUtils/Source/ELFLoader.cpp, External/SonicUtils/include/SonicUtils/ELFLoader.h, Source/Tests/HarnessHelpers.h
Fixes #49
Makes it so we no longer have to pass in the ld location to the
ELFLoader application.
Once we switch over to the dynamic linker, the program being executed to
us is no longer a dynamic program.
But the frontend ELF loader also still needs to know that we are
executing the dynamic linker so it can append the linker to the
arguments.
=> Fixes the dynamic linker detection

External/FEXCore/Source/Interface/Core/CPUID.cpp
4000'0000h is the hypervisor CPUID information leaf, can just return all
zeroes to imply we aren't running under a hypervisor
EAX: The maximum input value for CPUID supported by the hypervisor.
- We return zero here to signify no Hypervisor
EBX, ECX, EDX: Vedor ID signature
CPUID 4000'0001h - 4000'000Fh is reserved for hypervisor, which we don't
need to expose since we return zero in EAX
=> Adds hypervisor CPUID function

External/FEXCore/Source/Interface/Core/Core.cpp
This is purely a workaround until it gets implemented correctly
=> Throws a mutex in CompileBlock until we properly handle threaded compilation.

External/FEXCore/Source/Interface/IR/Passes/DeadCodeElimination.cpp
This is useful for debugging, don't want the DCE pass to remove it
=> Makes sure DCE pass doesn't remove print IR op

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.h
These are fairly popular so not having them around is causing headaches.
We will really want these in the future to use the host register, btu
that is more time consuming than I want to dedicate to at the moment.
So the FCMP instruction must be told which flags to generate up front,
then it generates the flags in to a GPR which are then tracked and
pulled out with a specific IR op.
This can be augmented in the future to more easily RA the host flag
register
=> Implements the COMISS instructions

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
A few instructions were missing flag setting entirely or were generating
wrong flags
- ROL, ROR, SHL, SHR, ASHR, SHLD, SHRD, CMPXCHG
This fixes those instructions and removes a few outdated comments
Specifically noticed when trying to run xcalc, it was using the flag
results from SHL for something and crashed without flag setting.
Unit tests for RFLAG setting instructions is still forthcoming
=> Implements and fixes flag setting in a few instructions

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
This allows applications to push the eflags to and from the stack.
Noticed when running some GL games
=> Implements push and pop flags instruction

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
This IR op is supposed to be explicitly truncating, where the previous op chooses mode based on MXCSR
=> Use the correct float vector op for Vector_FToZS on x86

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
We were overwriting flags while reading from them.
Keep the flags in AX with LAHF/SAHF to be easy
=> Fixes FCMP in x86-64

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Primary/Primary_98_2.asm, unittests/ASM/Primary/Primary_99_2.asm
It was managing to Sext and clear the entire GPR when it was only meant to write to the lower 16bits
=> Fixes bug in CBW op

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
SystemV ABI mandates that the stack frame is aligned to 16bytes.
Once the call instruction happens then it is offset by 8bytes, so it is
on the callee's hands to realign the stack pointer to 16bytes.
We rely on the assumption that the stack is aligned to 16bytes for spill
slots and other function calls
=> Fixes stack alignment in x86_64 JIT

CMakeLists.txt, External/FEXCore/CMakeLists.txt
behaviour around enabling PIC it was only working on one platform.
This follows through with the NEW cmake behaviour required to enable
PIE.
Very specifically you have to set the cmake variable, you have to set
the new policy, AND you have to have an explicit check for pie support.
With any of those three things missing then PIE won't be enabled
=> Actually unconditionally enable PIE through cmake

Source/Tests/ELFLoader.cpp
We need to reserve that space for EXEC apps and 32bit apps. Hard throw a
warning if any of our mapping space ends up in the lower 32bits.
PIE and potentially a custom dynamic linker can enforce this.
=> Ensure the ELFLoader doesn't end up in the lower 32bit address space

External/FEXCore/Source/Interface/Core/CPUID.cpp
Node was found using it and we don't yet support it
All of the instructions directly map to AArch64 instructions aside from
AESKEYGENASSIST
=> Remove CPUID flag saying that we support AES

External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Thread.h, External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp, External/FEXCore/Source/Interface/HLE/x64/Syscalls.h
Was seen in Reicast doing it for legacy reasons. Might as well as
support it.
=> Implements personality syscall

External/FEXCore/Source/Interface/Core/BlockCache.h, External/FEXCore/Source/Interface/HLE/Syscalls/Memory.cpp
A slight modification of the original aliasing logic, that avoids aliases.
=> BlockCache: Remove MemoryBase logic, check full address for match

External/FEXCore/Source/Interface/HLE/FileManagement.cpp
Missing this was an accident, this was how it was supposed to be.
It's very helpful to map FDs to filenames when tracking mmap mappings
=> Ensure that anything opened with openat is tracked in our FD map

External/FEXCore/Source/Interface/HLE/Syscalls/Sched.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Sched.h
This was implemented with the glibc API originally which was incorrect.
The syscall API is just a simple bitmask of for the affinity of the
number of CPU cores and a size check that the resulting structure is
large enough to store the number of bits.
=> Fixes the getaffinity syscall

External/FEXCore/Source/Interface/Memory/SharedMem.cpp, Source/Tests/ELFLoader.cpp
4GB virtual memory is too small and causes things to fault.
Previously we were at `1 << 36` but it caused oom issues on devices with
smaller amounts of memory.
This time ensure the the SHM memory is allocated with MEM_NORESERVE so
devices can actually allocate the virtual memory region.
=> Fixes memory allocation

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/IR/IR.h
Changes the IR register class definition to exist in the JSON file.
Removes a couple of IR ops that were unused and weren't necessary.
Changes the CPUID IR op to the new paired op which improves perf ever so
slightly.
Changes RA class handling in the RA pass to pull directly from the new
generated helper routine until it hits a complex op
Still need RA constraints to remove extraneous moves that would crop up
Fixes #100
=> Minor IR cleanup

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/IR/IR.h
Sadly this is a fairly substantial change that can't be broken in to
something smaller.
The gist of the problem is that most of the vector ops declared their
own uint8_t RegisterSize and ElementSize variables in their structs.
This was initially done because there were assumptions elsewhere in the
source that sometimes mixed up the IROp member `Size` and `Elements` as
sometimes meaning `Size` elements and `Elements` number of elements.
Other times there was an assumption that `Size` was the full register
size and `Elements` was the number of elements inside that size.
ex: `Size`: 16, `Elements` 8 would sometimes be interpreted as i16v8 OR i128v8
These assumptions are now removed and we also save on average 16bits per
vector operation. This is a necessary evil first step for upcoming IR …
=> Move vector op RegisterSize and ElementSize values in to the header struct

External/FEXCore/Source/Interface/Core/CPUID.cpp
BMI1 would be straightforward to implement, BMI2 would take a bit more
effort because of the PDEP, PEXT, and BZHI instructions.
Bigger problem is that we don't support VEX three operand decoding in
the frontend at all.
Disable these until then
=> Removes BMI1/BMI2 CPUID bits

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
This can prove useful for applications that change some of their checks
depending what the vendor is
=> Add a compile define for choosing CPUID manufacturer id

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp
Adds some additional validation that an IR op is generating RA for ops
that set a destination.
Ensuring correct register class and that there is a physical register
assigned
Relies on #106 to be merged first!
=>  Lets the IR validation pass validate RA

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/HLE/Syscalls.h, External/FEXCore/Source/Interface/HLE/Syscalls/FD.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp, External/FEXCore/include/FEXCore/HLE/Linux/ThreadManagement.h
Fixing some bugs in threading required fixing how the futexes operate.
Instead of the terrible condition variables and atomic values just use
the kernel futex facility directly.
This required fixing some of the threading management since otherwise
there was a issue around the weird mixture of our threads using our
"Futex" class and the kernel expecting real futexes on the values.
Just switch everything over and it ends up being cleaner
Fixes random mutex failures that were happening in various applications
=> Fixes some bugs with threads and futexes

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
Currently RA is shared between threads(!).
If the RA had been previously allocated then don't allocate it again.
Fixes a race condition when multiple threads are spinning up and one is
compiling code
Relies on #112 to be merged first!
=> Ensures the JIT constructor's don't reallocate RA

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, unittests/ASM/REP/F3_2A.asm
x86's cvtsi2ss can take a 32bit or 64bit input and convert it to a 32bit
float.
This ensures the register passed in is 32bit so it uses the 32bit
instruction
=> Fixes 32bit Float_FromGPR_S IR op in x86 JIT

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp
Oops, forgot I had force enabled these when testing.
=> Disables LLVM debug messages

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
There were four independent arrays for each size of the RA.
Missed the 16bit and 8bit registers when removing a register.
This removes the redundant arrays and just uses one and transforms the
register to the right size depending on what the JIT wants
=> Fixes x86 JIT's RA for 16bit and 8bit registers

External/FEXCore/Source/Interface/Core/CPUID.cpp
Dolphin uses this in a couple of places, so until it is fully supported
leave it disabled.
=> Removes SSSE3 CPUID feature bit

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp
Turns out my Threadripper stomps these tests so the arbitrary wait time
actually slows down my unit test time.
Don't want to make it shorter since `strace -f` becomes ugly at that
point.
Instead set up a semaphore style waiting structure that waits until
there are no longer any participants in the atomic
=> Removes the dumb timer wait for idle

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp, External/FEXCore/include/FEXCore/IR/IR.h
If a backend has RA then this'll pass through the RAPass and will dump
the RA alongside the IR. Very useful for debugging.
=> Adds RA printing to the IR dumping function

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
This happened to work with clang-9 but is caught in clang-10 now.
We were constructing an iterator temp then pulling a node through it
past the destruction.
Remove the iterator construction entirely and removes the unused lambda
from the AArch64 JIT that had the same problem.
=> Fixes accessing a stack variable post destruction bug

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
If the code cache is cleared then we would have the case where the IR data would remain.
Which could result in stale IR data when aliasing.
And if the IR existed then we wouldn't grab DebugData for that code block which would cause the interpreter and x86 JIT to crash.
=> Fixes crashes when code cache is cleared

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/include/FEXCore/Core/CPUBackend.h
Need to clear the other caches in the cases the x86 cache needs to be
wiped.
Not optimal but will improve once we get multiple tiers of code cache
=> Fixes crash that occurs when the x86-64 JIT code cache gets full

External/FEXCore/Source/Interface/HLE/Syscalls/EPoll.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/EPoll.h
Accidently made it behave like epoll_create1. This caused some games to
throw asserts in terminal.
=> Fixes epoll_create syscall

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, unittests/ASM/Primary/Primary_E3.asm
This only operates on 64bit and 32bit RCX register. the 16bit encoding isn't possible in 64bit mode.
Saw this when running some game
=> Implements JRCXZ in the OpcodeDispatcher 

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Memory/MemMapper.cpp, External/FEXCore/Source/Interface/Memory/MemMapper.h, External/FEXCore/include/FEXCore/Core/CodeLoader.h, External/SonicUtils/Source/ELFLoader.cpp, External/SonicUtils/Source/ELFSymbolDatabase.cpp, External/SonicUtils/include/SonicUtils/ELFSymbolDatabase.h, Source/Tests/HarnessHelpers.h, Source/Tests/TestSingleStepHardware.cpp
If we are loading EXEC then we actually need to start loading in to the
lower 32bits of memory.
This lets the frontend code loader handle the memory base instead of
hiding it behind some core magic instead.
This lets us get EXEC programs working.
So now we support EXEC, DYN, and static applications
=> Fixes loading EXEC applications in to memory.

External/SonicUtils/Source/VM.cpp
This doesn't quite fix the build for me yet, but it makes it go further.
=> x86_64 build fix, by reordering KVM initialisation values

.github/workflows/ccpp.yml
If someone is pushing to a local branch on the repo, then don't run CI.
Only run once someone pushes a PR if local.
This makes it so we don't run CI for a branch twice over.
=> Ensure local pushes to a branch don't run through CI

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
Smaller than 8byte wasn't sexting to the full register so it was causing issues
=> Fixes ASHR on AArch64

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp
LLVM-9 doesn have the include, while LLVM-10 does
=> Fixes LLVM on AArch64

External/FEXCore/Source/Interface/HLE/Syscalls/FS.cpp
The glibc implementation and syscall implementation differ quite
significantly.
Just use the kernel interface one for now.
=> Changes getcwd to use the syscall directly.

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
This keeps the XOP instruction tables around but removes the decoding
assert.
This lets us implement the POP instruction that overlapped the XOP
prefix without having to deal with XOP at all.
I don't believe we have any real need to support XOP, but if it is a
thing later then it'll be easy to add back
=> Removes XOP frontend handling

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
We were missing the newly added GDT classifications.
Wouldn't have caused any issues in any 64bit applications, but threw an
assert in debug builds
=> Fixes RCLSE CPUState classification

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, unittests/ASM/PrimaryGroup/3_F7_06.asm, unittests/ASM/PrimaryGroup/3_F7_07.asm
These were only doing 64bit divisions.
Function calls are a bit ugly but once the new RA lands we can clean them up
=> Fixes 128bit divisions on AArch64 

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/DeadCodeElimination.cpp
There are many times in the DCE pass that I forget to add a new instruction to it for an operation that has a side effect and shouldn't be removed if usecount is zero.
This changes over so the IR op definition itself contains the sideeffect flag and the DCE pass just pulls that information from there.
This probably fixes a bunch of bugs from atomic ops getting obliterated.
=> Implements HasSideEffects IR option

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp
This is a bit of a peculiar one, we want to ensure a single threaded
application is running on the emulator's primary thread.
This mitigates the problem that an application can do a getpid versus
gettid comparison and notice a problem.
Some games rely on getpid being the actual process ID and will spin
forever if it isn't the case.
This is also necessary for wine bringup since thread creation needs a
bit more finesse there.
Fixes #186
=> Forces the primary application thread to be host primary thread

External/SonicUtils/include/SonicUtils/LogManager.h
There are cases where a WARN_ONCE macro that warns about one thing is
very nice to have.
Add the macro so we can use it later
=> Adds a WARN_ONCE macro

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/include/FEXCore/IR/IR.h, unittests/ASM/Secondary/15_XX_5.asm, unittests/ASM/Secondary/15_XX_6.asm, unittests/ASM/Secondary/15_XX_7.asm
These map directly to x86 fence instructions, which have equivalent ARM
versions as well.
=> Implements fence ops

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, Source/Tests/IRLoader/Loader.cpp
The IRHeader itself contains a flag for if a block should fallback to
the interpreter.
This is necessary for the case that an IR is loaded and the Frontend
object no longer has the data necessary to know if it should do an
interpreter fallback.
This is super useful for bisecting JIT versus Intepreter failures, and
also cases where falling back to intepreter for compatibility is a lot
more simple than wiring things through the JIT (ala x87)
This isn't currently utilized, but will be once x87 work lands
=> Adds support for interpreter fallback

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
As we run more threaded applications it is becoming apparent that this
needs to be fixed now.
This duplicates the FrontendDecoder and Passmanager per thread so they
no longer block each other while compiling.
Increases a bit of memory usage but completely worth it.
=> Makes threaded compilation not rely on a global mutex

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp
Better than relying on a hardcoded CPU target
Should fix a crash on x86 host cpus that don't support BMI1
=> Forces LLVM backend to use the native CPU architecture

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp, unittests/ASM/Primary/Primary_AC.asm, unittests/ASM/Primary/Primary_AC_REP.asm, unittests/ASM/Primary/Primary_AC_REP_down.asm, unittests/ASM/Primary/Primary_AD_REP_dword.asm, unittests/ASM/Primary/Primary_AD_REP_dword_down.asm, unittests/ASM/Primary/Primary_AD_REP_qword.asm, unittests/ASM/Primary/Primary_AD_REP_qword_down.asm, unittests/ASM/Primary/Primary_AD_REP_word.asm, unittests/ASM/Primary/Primary_AD_REP_word_down.asm, unittests/ASM/Primary/Primary_AD_dword.asm, unittests/ASM/Primary/Primary_AD_qword.asm, unittests/ASM/Primary/Primary_AD_word.asm
Theoretically the REP case can be optimized if it is known not to fault,
but that is one legitimate use case of this instruction.
This is just to ensure that we have this instruction covered, it hasn't
been encountered in a real program yet.
=> Implements LODS instruction

Source/Common/Config.cpp
Common when I'm testing and wiping the config away
=> Fixes a crash that can occur when the config exists but has nothing

External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp
A bit of a hack, but makes iteration much faster
=> x64/syscalls: Change HandleSyscall/Unimplemented Syscall to include syscall number

External/FEXCore/Source/Interface/HLE/Syscalls/Socket.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Socket.h, External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp, External/FEXCore/Source/Interface/HLE/x64/Syscalls.h
Fixes ```Bin/ELFLoader -U -c irjit -n 500 --  `which python` -m SimpleHTTPServer 8080```.
Fixes ```Bin/ELFLoader -U -c irjit -n 500 --  `which nodejs` server.js```
```
var http = require('http');
console.log("Hello from node")
//create a server object:
http.createServer(function (req, res) {
console.log("Got get request, replying");
res.write('Hello FEX-World!'); //write a response to the client
res.end(); //end the response
}).listen(8080); //the server object listens on port 8080
console.log("Server listening: localhost:8080")
```
=> x64/syscalls: Add accept, accept4

External/FEXCore/Source/CMakeLists.txt
This was a cmake job race, depending on what was trying to run in the IR
folder first, the IR folder in the binary directory may not have been
generated before our scripts tried to be run
=> Ensures IR build folder is created

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Secondary/08_XX_04_3.asm, unittests/ASM/Secondary/08_XX_05_3.asm, unittests/ASM/Secondary/08_XX_06_3.asm, unittests/ASM/Secondary/08_XX_07_3.asm
When the `BT mem` operation was accessing memory where the bit offset
wasn't a multiple of the access size, then we were dividing the offset
by bytes and accessing bits at `mem[byteOffset] &= (BitOffset)`.
BitOffset wasn't adjusted to compensate for the access size being added
to the address.
Causing a mismatch of testing the wrong bits. Unit tests didn't capture
this.
Trying to run glxgears on i965/iris showed extensive corruption because
of it though.
=> Fixes a case of the BT ops failing to test the correct bit

External/FEXCore/Scripts/json_ir_generator.py
This was forcing every op to determine it had side effects, so DCE could
never actually remove any operations.
This fixes the typo which means each op declares side effects correctly
and DCE works again
=> Fixes a typo in the HasSideEffects json generator

External/FEXCore/Source/Common/Paths.cpp, External/FEXCore/Source/Common/Paths.h, External/FEXCore/Source/Interface/Core/Core.cpp, Source/Common/Config.cpp, Source/Tests/ELFLoader.cpp
Ensures that unified memory is enabled by default. I thought this was enabled by default but it must have been missed.
Ensures the EntryCache gets stored in the correct XDG/Home folder
Ensures the Config file gets store in XDG/Home as well.
=> Config fixes

External/FEXCore/Source/Interface/Core/Frontend.cpp
64bit mode doesn't exist when we are operating in 32bit mode, so this
needs to be disabled.
This forces a fallback to a 32bit size for those ops
=> Removes 64bit size from frontend when in 32bit mode

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
These keep sneaking back in when I'm testing
=> Remove a debug log from the AArch64 JIT

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/include/FEXCore/Core/CoreState.h, unittests/ASM/Primary/Primary_8C.asm
32bit apps are setting GS register that I saw.
64Bit applications can also technically use these instructions but it
has some major limitation that causes applications to never use them
=> Supports segment register moving

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/X87Tables.cpp, unittests/ASM/X87/DF_C0.asm
There's some history for this instruction. It is not in the official
instruction documentations from AMD or Intel but it is supported on
almost every x87 supporting CPU (I think there was some Cyrix that
missed it?)
This was originally implemented by accident on the Intel 80287 CPU.
It was then periodically documented in random documentation.
The instruction behaves exactly like FFREE but then pops the stack after
the operation.
For our current implementation of FFREE, which is a NOP, we just need to
pop the stack.
This was hardware unit tested on both AMD (Threadripper 2990WX) and Intel (i7-1065G7) to behave the same between the two.
=>  Implements FFREEP Instruction

External/FEXCore/Source/Interface/HLE/x64/Syscalls.h
`FEXCore::HLE::RegisterStubs()::impl_setpgid::impl_setpgid()::{lambda(` vs `FEXCore::HLE::RegisterStubs()::$_14::operator()(`
=> Syscalls: Add a wrapping class for better backtrace

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
The break ir op is actually a block ender and it happened that in
regular code paths they were already ending the blocks correctly.
This enforces block ending in the Unimplemented op so multiblock still
generates the invalid code path correctly and it compiles.
We hit these a few times in multiblock for times in the code where it is
checking for CPU features and choosing a code path depending on CPUID
results.
Potentially these could be made in to no-ops since we'll never hit these
codepaths in practice, but it is nicer to break in case we actually do
hit one of these paths.
=> Fixes LLVM multiblock

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/include/FEXCore/Core/CoreState.h
This was misaligned by 8 bytes, which worked fine on x86, but crashed
when loaded on ARM.
Now it is correctly aligned to 128bit
=> Corrects MM register alignment in CoreState

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
Previously the ARM64 JIT didn't support cache clearing at all.
This adds support for clearing the JIT cache while keeping dispatcher
helpers around and the ASM dispatcher alive.
Requires #253 to be merged first.
=> Implements support for cache clearing in the ARM64 JIT

External/FEXCore/Source/Interface/HLE/Syscalls.h, External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp, External/FEXCore/Source/Interface/HLE/x64/Syscalls.h
This was spending ~60seconds of time compiling on my c630.
Something about fmt string formatting causing heavy compile times on
ARM.
Better to just compile it out anyway.
=> Removes syscall strace parsing if not enabled

External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp
This launches child applications under fex. With a few more syscalls this allows bash to work (chown, setgpid).
=> syscalls: implement execve

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
lock prefix needed to go before the xchg, not before the move that was
there
=> Fixes AtomicSwap IR op on x86

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/include/FEXCore/IR/IREmitter.h, unittests/ASM/OpSize/66_E0.asm, unittests/ASM/OpSize/66_E3.asm, unittests/ASM/TwoByte/0F_E0.asm, unittests/ASM/TwoByte/0F_E3.asm
This is my first opcode implementation so please review carefully
Done
- Update SecondaryTables for PAVGB (TYPE_MMX is invalid for some reason?)
- Add new IR Op, `VURAvg`
- Add and implement PAVGB/W in OpcodeDispatcher
- Add Tests PAVGB/W, MMX and XMM variants
- Implement for `VURAvg` INT/JIT x64/JIT arm64/llvm
- Check at uhradd uses an extra bit of precision
Follow up
- #261 for llvm codegen
=> Implement PAVGB/PAVGW

External/FEXCore/Source/Interface/HLE/Syscalls/Info.cpp
Run into this in CS:GO.
With this fix it progresses much further, but still doesn't get to the menu.
=> uname: Should return x86_64, not x64_64

Source/Common/ArgumentLoader.cpp, Source/Common/Config.cpp, Source/Common/Config.h, Source/Tests/ELFLoader.cpp, Source/Tests/HarnessHelpers.h
This allows us to pass environment variables that only exist for the guest and don't pollute the host environment.
This can be useful for many reasons, like glibc environment variables that we don't want to be in the host space.
ex. `./Bin/ELFLoader -E DISPLAY=:0 -E GALLIUM_HUD=fps,cpu /usr/bin/glxgears`
=> Support Environment variables passed as arguments

External/FEXCore/Source/Interface/Core/CPUID.cpp
This would be a pain to support in NEON since it requires a 128bit
resulting multiply
=> Disables CLMUL in CPUID

Dockerfile
Multi-stage building separates the building process from the actual usable environment, removing any unnecessary packages and files and only keeps what is actually needed to run the target application, significantly decreasing the final image size. In this case the image size was reduced from 1.24GBs to 490MBs. There is possibly still room for improvement though.
For now, the compiled executables are moved to `/usr/bin` (but maybe they should go to `usr/local/bin` instead?), and libSonicUtils.so to `/usr/lib` (but maybe they should go to `usr/local/lib` instead?). The rest of the Externals are statically linked. so libSonicUtils seems to be the only compiled library that needs to be kept.
=> Adds multi-stage building for Docker image

External/FEXCore/Source/Interface/HLE/FileManagement.cpp, External/FEXCore/Source/Interface/HLE/FileManagement.h
The Unigine Superposition benchmark launcher is based on qt.
Instead of the normal checking of `/proc/self/exe`, it does a `getpid()` followed by a stat to `/proc/{getpid}/exe/`
It uses this to find the qt plugin shared libraries, which are stored relative to the binary.
=> Filesystem HLE: Intercept /proc/${getpid}/exe too

External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMMemoryManager.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMMemoryManager.h
Surprised this hasn't caused issues before but was picked up on the
SolidRun Honeycomb LX2K
=> Fixes LLVM not clearing code cache on ARM platforms

External/FEXCore/Source/Interface/Core/Core.cpp
This needs to live outside of the dispatcher to do correct threading
cleanup
=> Allows ASM dispatcher to leave cleanly

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/X86HelperGen.cpp, External/FEXCore/Source/Interface/Core/X86HelperGen.h
Just generates some context level x86 code space for our guest to jump
in to.
This is only currently used for sigret but will become more important as
we come to support vdso.
=> Adds an x86 generated code helper class

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/Source/Interface/IR/IR.json
We are rebranding an x86-64 illegal instruction near VIA's old ALTINST
instruction as an instruction to handle returning from guest signals
cleanly.
If this ever collides with a new x86-64 (unlikely) then we will need to
change the instruction.
This ends up looking similar to what we will do for thunk callbacks
=> Declares new sigret x86 instruction and IR op

External/FEXCore/Source/Interface/Core/Core.cpp
Arm64 IR JIT needs the interpreter to be around first to get a pointer
to it
=> Creates the interpreter core just before the IR jit

External/FEXCore/Source/Common/SoftFloat.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LLVMJIT/LLVMCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/SignalDelegator.cpp, External/FEXCore/Source/Interface/Core/SignalDelegator.h, External/FEXCore/Source/Interface/HLE/Syscalls/Signals.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h
Relies on #294 to be merged first!
Implements ~~TSO~~ SC GPR loadstore ops with ARM's LORegion instructions.
These match x86's loadstore semantics a bit better than atomics but still have limitations.
- LORegion instructions require natural type alignment
- LORegion doesn't have a CMPXCHG8B matching instruction
- This doesn't support atomic memory ops at all.
To work around the natural alignment issue, we emit the LORegion instructions and backpatch to DMB+LoadStore+DMB.
This isn't quite optimal, but works well enough while we research if the half-barrier approach works; Which will allow us to acquire cachelines rather than ensure full cache consistency.
=> AArch64 ~~TSO~~ SC implementation

.github/workflows/ccpp.yml
We want to see the output from all of our runners.
Usually the x86 runner quickly spins through things and then we never see the ARM results if that side failed.
=> Disables fast fail in github workflow

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/HLE/Syscalls/IO.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Stubs.cpp, External/FEXCore/Source/Interface/HLE/x64/Syscalls.cpp
This syscall requires the application to have root and will fail with
-EPERM otherwise.
Implementing this as just an -EPERM return allows Crispy Doom to run
=> Implements ioperm syscall as no permissions

CMakeLists.txt
=> Throw an error in CMake if someone attempts to compile with GCC

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/X87Tables.cpp
Bunch of templated instructions that didn't need to be templated.
Removes a bunch of duplicate entries.
Saves a couple hundred kilobytes on the final file
=> Small bit of OpDispatcher table cleanup

External/FEXCore/Source/Interface/Core/SignalDelegator.cpp, External/FEXCore/Source/Interface/Core/SignalDelegator.h, External/FEXCore/Source/Interface/HLE/Syscalls/Signals.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Stubs.cpp, unittests/POSIX/Disabled_Tests, unittests/POSIX/Known_Failures
Any time a guest signal is blocked, add it to the guest signal mask.
This doesn't use a signal queue so repeat signals can end up being lost.
This is expected behaviour
This doesn't help with implementing the problem of unblocking signals
causing the masked signal to be resent
Fixes the issue of posix unit tests taking five minutes to time out.
=> Implements rt_sigpending

External/FEXCore/Source/Common/NetStream.cpp, External/FEXCore/Source/Common/NetStream.h, External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/GdbServer.cpp, External/FEXCore/Source/Interface/Core/GdbServer.h
There are a significant number of changes here that I don't really
expect much review on.
Adds a bunch of new features and allows us to support GDB, IDA, and
Binja through their remote GDB debugging facilities.
Ghidra may also work but I haven't tried.
This work isn't quite yet complete to do correct thread stepping yet. We
need to add support for stopping threads using signals since threads may
be stuck inside of a syscall.
I have a hack locally that tries pausing all threads and times out after
a few seconds which works well enough for local testing.
=> Extends gdbstub functionality

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h, unittests/IR/Basic/Sbfe.ir, unittests/IR/CMakeLists.txt, unittests/IR/Correctness/AddTruncate.ir, unittests/IR/Correctness/FPRStoreTruncate.ir, unittests/IR/Correctness/LeftShiftTruncate.ir, unittests/IR/Correctness/SubTruncate.ir
This branch started as optimisation but kind of gained a bunch of IR cleanup too.  
* `Zext` and `Sext` opcode are gone. Use `Bfe` and `Sbfe` instead.
* `Sbfe` has actually been implemented
* `Bfe` has lost it's responsibly for handling extraction FPRs.
* General IR semantics have been changed:
* IR Ops are not allowed to any bits higher than their defined size.  
For example, `%ssa5 i32 = Add Constant(0xffffffff), Constant(0x1)` will result in zero.
* Some sizes of some IR ops that don't exist on arm are now banned.  
For example 8 and 16bit `Add`/`Sub`/`Mul`. OpcodeDecoder is expected to generate a 32bit `Op` followed by a `Bfe`
* Due to this, GPR IR Ops are allowed to assume they can Zero Extend their inputs upto 64bits for free. 
* Same with FPR IR Ops, which can Zero Extend upto …
=> Misc Optimisation and IR cleanup

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
Found this while debugging mono's register allocator.
OP_NOT is only used in BTR, as NOT uses XOR.
=> Interpreter: Fix Mask calculation for OP_NOT

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
This catches a lot of common cases of small negative values, esp. from address generation
=> arm64: Add movn to LoadConstant

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
This silently breaks on CPUs without BMI1, like mine
=> JIT/x86: Don't use tzcnt

.gitmodules, External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/GdbServer.cpp, External/FEXCore/Source/Interface/Core/Interpreter/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.h, External/FEXCore/Source/Interface/Core/Interpreter/x86_64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/SignalDelegator.cpp, External/FEXCore/Source/Interface/Core/SignalDelegator.h, External/FEXCore/Source/Interface/HLE/Syscalls/Stubs.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Timer.cpp, External/FEXCore/include/FEXCore/Core/CPUBackend.h, External/FEXCore/include/FEXCore/Core/CoreState.h, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, Source/CommonCore/VMFactory.cpp, Source/Tests/ELFLoader.cpp, Source/Tests/TestHarnessRunner.cpp, unittests/POSIX/Expected_Output, unittests/POSIX/Known_Failures
This requires implementing custom ASM dispatchers for the interpreter
side of things so it works correctly.
Allows all of our CPU backends to safely support signaling.
This is a bit of a nightmare change and requires rethinking logic about
debugging in some instances.
=> Moves our entire execution model over to signal execution

Source/Tests/CMakeLists.txt
This renames ELFLoader to FEXLoader to come more in line with what an installed target should be (Otherwise what would a random ELFLoader be in /usr/bin?). Letting people know that this is FEX.
Adds a new cmake install target for installing FEXLoader.
Also adds a new cmake custom target for installing the binfmt_misc registry `sudo ninja binfmt_misc`
This just ends up executing the command 
`echo ":FEX-x86_64:M:0:\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/FEXLoader:CF" > /proc/sys/fs/binfmt_misc/register`
Which is all that is required for registering with binfmt_misc
=> Binfmt_misc support

.github/workflows/ccpp.yml
We have hit issues where the non-clean folder would end up leaving
artifacts which allowed tests to pass.
Remove the build folder on each run to clean up
=> Has the github action clean its build folder

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/include/FEXCore/Config/Config.h, Source/Common/ArgumentLoader.cpp, Source/Common/EnvironmentLoader.cpp, Source/Tests/ELFLoader.cpp
This is a knowingly wrong option for anything running in a threaded
environment
=> Adds option to disable TSO

External/FEXCore/Source/Interface/Core/Interpreter/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/x86_64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
Previously we never checked for SS_DISABLE.
We were also only ever checking for ss_sp being a valid memory range
when we should have been checking for the absense of SS_DISABLE.
Fixes #326
=> Fixes guest disabling sigaltstack.

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
If the host CPU supports RCPC instructions then it'll use those
instruction of atomics for LoadMemTSO ops.
This pushed my worst case FTL test from 16FPS to 17FPS .
There is another extension to RCPC to add short immediate offset support
which the c630 doesn't support any way. For future optimization on
hardware we can use that.
=> Adds support for RCPC load instructions

External/FEXCore/CMakeLists.txt, External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/HLE/EmulatedFiles/EmulatedFiles.cpp, External/FEXCore/include/git_version.h.in
Instead of having this file mostly just copy and pasted, it'll now be
generated.
We end up losing a lot of supported flags with this change, which is for
the best since we wouldn't have actually supported those things.
=> Has /proc/cpuinfo generated from CPUID

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
=> IR/ConstProp: Disable BFE identity as it breaks cs:go

External/FEXCore/Source/Interface/HLE/Syscalls/Sched.cpp
Just use the syscall directly rather than call through the glibc
interface.
The getpriority syscall biases the return value so it never returns a
negative, while the glibc interface returns [-20,19), so you need to do
some errno juggling for the -1 return.
Just use the syscall directly instead
Fixes some game complaining heavily when getpriority results were wrong
=> Fixes getpriority syscall

External/FEXCore/Source/Interface/Core/SignalDelegator.cpp, External/FEXCore/Source/Interface/Core/SignalDelegator.h, unittests/POSIX/Disabled_Tests, unittests/POSIX/Known_Failures
glibc raise() actually disables all signals, raises the signal that the
user wants, then reenables the previous signal mask.
On the reenabling of the previous signal mask, that is when the pending
signal fires.
This needs to be accurately handled, so check for pending signals
getting unmasked in sigprocmask
This also then needs to be further fixed to handle default signal
handling, where if a signal was sent that is default ignored (NOT set to
ignore!) then it would just exit the application before.
Now something likg SIGCHLD with the default handler (aka ignore) won't
kill the process
=> Fixes guest default signal handling and pending signals 

External/FEXCore/Source/Interface/HLE/Syscalls/Info.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Stubs.cpp
These are safe to pass through to the host, there isn't any system data
handled here.
Some game I was testing used these
=> Implements capget and capset syscalls

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/REPNE/F2_E6.asm
Without impementing MXCSR still, this matches the already implemented
CVTTPD2DQ
Rimworld hit this instruction on boot.
=> Implements missing CVTPD2DQ 

External/FEXCore/Source/Interface/HLE/Syscalls/Memory.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Stubs.cpp
These don't really do much in a coherent and UMA situation, but some
games are hitting them, so may as well as implement them
=> Implements two more memory syscalls

External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp
Since we track the PID and TID of the threads for signaling purposes, we
had the problem that if a process forked and the child then shuts down.
It was still tracking the parent thread as executing, thus it would send
it a tgkill to shut it down.
This was unintended behaviour and is now stopped
=> Ensures a process that has forked won't shutdown the other process

External/FEXCore/Source/Interface/Core/SignalDelegator.cpp, External/FEXCore/Source/Interface/Core/SignalDelegator.h, External/FEXCore/Source/Interface/HLE/Syscalls/Signals.cpp, External/FEXCore/Source/Interface/HLE/Syscalls/Stubs.cpp
This helps out Mono's garbage collector specifically. There is a minor
race that can currently occur with signal 63 but that technically should
only occur on a pause or stop condition.
Might need to change this behaviour if it becomes a problem
=> Implements sigsuspend

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/Interpreter/x86_64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86HelperGen.cpp, External/FEXCore/Source/Interface/Core/X86HelperGen.h, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/include/FEXCore/Core/CPUBackend.h, External/FEXCore/include/FEXCore/Core/Context.h, ThunkLibs/GuestLibs/CMakeLists.txt, ThunkLibs/HostLibs/CMakeLists.txt, unittests/POSIX/Disabled_Tests, unittests/POSIX/Known_Failures
This interface is for native host code to be able to call back in to JIT
to execute guest code.
This is mainly for thunks but could be used for other purposes.
This can cross a couple ABI boundaries so one must be careful when
calling in to this
=> Initial Callback support

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, unittests/ASM/PrimaryGroup/2_D1_07_2.asm
ASR should shift signed for its bit size, but then zext to full register size.
=> OP_ASR: Fix zext semantics

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/Interpreter/x86_64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/include/FEXCore/Config/Config.h, Source/Common/ArgumentLoader.cpp, Source/Common/EnvironmentLoader.cpp, Source/Tests/ELFLoader.cpp, Source/Tests/TestHarnessRunner.cpp, unittests/ASM/CMakeLists.txt, unittests/ASM/SelfModifyingCode/DifferentBlock.asm, unittests/ASM/SelfModifyingCode/SameBlock.asm
This is a brute-force solution that can catch any kind of SMC, including modifications to the next instruction
Adds two new IR ops
- ValidateCode that compares current vs original code and returns 0 on same, non zero on different
- RemoveCodeEntry that removes the code entries (via Context::RemoveCodeEntry)
Adds `--smc-full-checks` in FEXLoader and UnitTestHarness
Adds logic to validate code in `Context::CompileBlock` (Core.cpp) if enabled
Adds a unit test to check that SMC detection works, `--smc-full-checks` is passed only for that test
Notes
- ValidateCode can be implemented as a string of Constant/Cmp/Select IR ops, though codegen would be much worse
- When enabled it disables most optimizations as it emits a host-block per guest-op
=> SMC: Add --smc-full-checks, implement frontend, irint, irjit, unit test

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/IREmitter.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadCodeElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadFlagStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Interface/IR/Passes/SyscallOptimization.cpp, External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp, External/FEXCore/docs/IR.md, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/IREmitter.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h, Source/Tests/IRLoader/Loader.cpp
This moves most of the internal complexities of our IR inside just a few files:  `IR.h`, `IR.cpp`, `IREmitter.cpp`, `IREmitter.cpp` and `IntrusiveIRList.h`
There are now new iterators for Blocks and Code.
=> Refactor the IR Interface to prevent "foot-shooting"

External/FEXCore/Source/Interface/HLE/Syscalls/Thread.cpp
This can result in some terrible behaviour if something doesn't
immediately execve once it forks. Allow it instead of crashing out
though.
=> Removes error and die in multithreaded forks

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
We still aren't 100% reentrant safe in the case that the cores are
interrupted while running, but this is a step in the right direction
=> Removes a couple of unnecessary variables to improve reentrancy chances

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Primary/Primary_8D_2.asm
We were handling this in a completely broken fashion and it only broke
more with the previous zexting changes.
This fixes the EXPLICIT address size override usage.
There are still a few instructions that rely on implicit address size
override support that this doesn't handle
=> Fixes address size override prefix

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, Source/Tests/ELFLoader.cpp, Source/Tests/HarnessHelpers.h, Source/Tests/TestHarnessRunner.cpp
Noticed by Stef on 09/09/2020 as a curious code block that was failing
Forgot about it until now since we couldn't see exactly where it was
wrong
Code block was mixing x87 (Which forces a fallback to Interpreter) and
cmpxchg8b, which caused that code block to fail.
Since this op was broken with Unified Memory + Interpreter it wasn't
picked up by unit tests since those don't run in unified memory
Code block from before
```
0x00007fece80daa10:    push   rbp
0x00007fece80daa11:    mov    rbp,rsp
0x00007fece80daa14:    push   rbx
0x00007fece80daa15:    fild   QWORD PTR [rdi]
0x00007fece80daa17:    fistp  QWORD PTR [rbp-0x10]
0x00007fece80daa1a:    mov    rax,QWORD PTR [rbp-0x10]
0x00007fece80daa1e:    xchg   ax,ax
0x00007fece80daa20:    lea    rcx,[rax+rsi*1]
0x00007fece80daa24:    mov …
```
=> Fixes CASP IR op on interpreter when unified memory is enabled

Source/Tests/HarnessHelpers.h
This allows us to only check for the lower 64bits of the MM registers
when doing MMX ops for example.
Top 16bits in that case is undefined and needs to be ignored
=> Allows unit tests registers to have partial register views

Source/Tests/HarnessHelpers.h
This will become important in the future when we are actually executing
this code directly on host.
FEX itself doesn't yet care about memory permissions
=> Ensures the unit test code is marked executable

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Secondary/08_66_04.asm, unittests/ASM/Secondary/08_66_04_2.asm, unittests/ASM/Secondary/08_F2_04.asm, unittests/ASM/Secondary/08_F2_04_2.asm, unittests/ASM/Secondary/08_F3_04.asm, unittests/ASM/Secondary/08_XX_04.asm, unittests/ASM/Secondary/08_XX_04_2.asm, unittests/ASM/Secondary/08_XX_05.asm, unittests/ASM/Secondary/08_XX_05_2.asm, unittests/ASM/Secondary/08_XX_06.asm, unittests/ASM/Secondary/08_XX_06_2.asm, unittests/ASM/Secondary/08_XX_07.asm, unittests/ASM/Secondary/08_XX_07_2.asm
66 prefix /does/ change behaviour because that is the operand size
prefix.
Additionally the immediate variant will also modulo the result.
So that needs to be checked for
Confirmed with manual on upcoming host-side unit test runner
=> Fixes incorrect assuming BT tests

External/FEXCore/Source/Interface/IR/IR.cpp
In the case of an invalid SSA destination size, the IR validation pass
would catch it and then when printing the IR it would crash with a
divide by zero.
Fixes that.
=> Fixes crash when SSA value has size of zero

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, unittests/ASM/OpSize/66_F7.asm, unittests/ASM/TwoByte/0F_F7.asm
Without supporting phis this entire loop needs to be unrolled.
I just found out while reading the x86 documentation that this
instruction is explicitly a weakly ordered memory operation.
So this operation can be changed over to a couple vector conditional
loadstores soon after merging
=> Implements MASKMOVQ and MASKMOVDQU

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/IR/IR.json
Interpreter might not be quite correct here (Could end up doing truncate or host flags depending on how it compiles)
But until we have the unit tests in place it's hard to ensure atm.
=> Adds new IR ops for supporting host rounding mode conversion

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, unittests/ASM/TwoByte/0F_D7.asm
Only pulls out 8 bits of data then zero extends the result to 32bits for the GPR
=> Implements MMX PMOVMSKB 

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Primary/Primary_9C.asm, unittests/ASM/Primary/Primary_9D.asm
0x2 is the default state for hardware boot, but it isn't the state we
boot applications in.
When an application boots under Linux it is actually set to 0x202
because interrupts have been enabled.
Since we can't disable interrupts we will just always have at least
0x202 in the eflags.
This modifies the unit tests to first clear the full eflags state then
loads it so we hit "default". Once we hit the unit test runner we won't
have known the eflags state at that point, so we need to clear it
initially.
=> Ensures eflags matches real state

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, unittests/ASM/OpSize/66_5B.asm, unittests/ASM/REP/F3_2C.asm, unittests/ASM/REP/F3_2D.asm
These rely on the host flag being correct. Which will match what is set
through the regular host flag setting routines
This needs to be rebased once #416 is merged
=> Implements OpDispatcher ops for host flag conversion ops

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Instead use our helpers to determine the sizes to stay consistent
=> Removes some direct usage of widening flag

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/PrimaryGroupTables.cpp
SAL is exactly the same as SHL
TEST is exactly the same as the previous TESTs
Bit silly of encodings since compilers will never actually generate
these
No unit tests on these since getting nasm to emit it is a PITA
=> Implements the couple of duplicated ops

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, unittests/ASM/REP/F3_BD.asm
This overlaps the previous BSR instruction which is why the table had to
be changed.
We were accidently claiming support for ABM in CPUID before so that
didn't need to be changed.
We now implement both LZCNT and POPCNT so we fully support ABM now.
=> Implements ABM's LZCNT instruction

External/FEXCore/Source/Interface/Core/CPUID.cpp
Needs #432, #433, #434, #435, and #436 enabled first.
Everything is implemented to enable SSSE3 support once those are merged.
=> Enables SSSE3 in CPUID

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
We can't just flip the comparison because NaN changes behaviour here
=> Fixes float compare with negated results

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/TwoByte/0F_A4_2.asm, unittests/ASM/TwoByte/0F_AC_2.asm, unittests/ASM/TwoByte/0F_AD_2.asm
Even though it doesn't update the flags, it still needs to zext the GPR in this instance.
=> Fixes 32bit SHLD and SHRD by zero

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/TwoByte/0F_B0_2.asm
When the destination is a 32bit GPR, when the resulting compare failed
we were zexting the destination registeron accident.
Thus clearing the upper 32bits when it shouldn't have changed.
=> Fixes edge case that wasn't covered in FEX's cmpxchg 

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/PrimaryGroup/3_F6_05.asm, unittests/ASM/PrimaryGroup/3_F7_05.asm, unittests/ASM/PrimaryGroup/3_F7_05_2.asm, unittests/ASM/TwoByte/0F_AF_2.asm
Flags calculation was wrong in these and for 32bit sext result we were storing the zext result instead of the sext result.
=> Signed multiply fixes

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/32Bit_ASM/Primary/Primary_C9.asm
Was already implemented correctly, was just untested.
=> Fixes 32bit LEAVE instruction

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h
Mostly centered around fixing segment register usage in 32bit.
Every instruction that uses segment registers now uses a helper routine to ensure segment registers are used.
Also some other minor 32bit fixes that should make life easier.
=> 32bit and Segment register fixes

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
Java VM uses this to determine if the CPU is new enough to be a 486 or
newer.
Also fixes some comment text.
Java VM scans all the leafs for hypervisor entries
Instead of adding directly which was causing our CPUID map to grow to
1500 entries.
Do the correct CPUID thing and return zeroes for non-understood leafs.
Gives us the same result since we cover almost all leaves with it anyway
=> Changes CPU family reported by CPUID

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h, Source/Tests/HarnessHelpers.h, unittests/32Bit_ASM/CMakeLists.txt, unittests/32Bit_ASM/Primary/Primary_A0.asm, unittests/32Bit_ASM/Primary/Primary_A2.asm, unittests/32Bit_ASM/PrimaryGroup/5_FF_02.asm, unittests/32Bit_ASM/PrimaryGroup/5_FF_02_2.asm, unittests/32Bit_ASM/PrimaryGroup/5_FF_02_3.asm
Fixes an issue where unit test loader would load a test in to high 64bits memory space.
Fixes "RIP Literal" needing to be treated as unsigned rather than signed
Fixes MEM_OFFSET instructions having their offset modified by operand size override, when it should have been modified by address size override.
Adds some 32bit unit tests to verify these.
=> More 32bit fixes

External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
Just needed to make sure to use the right register size
=> Fixes SetRoundingMode on AArch64 JIT

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h
Based on @phire's idea, Inline constants are constants that can be used as imms in instructions.
This
- Adds OP_INLINECONSTANT to represent them in the IR
- Modifies the ConstProp pass to transform OP_CONSTANT to OP_INLINECONSTANT based on per-platform heuristics
- Modifies RA to ignore OP_INLINECONSTANT uses
- Modifies the backends to use imms
- Supported opcodes: Add, Sub, Lsl, Lsr, Asr, Ror, Rol
=> IR/JIT: Inline constants

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/PrimaryGroupTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, unittests/32Bit_ASM/Primary/Pop_Segments.asm, unittests/32Bit_ASM/Primary/Primary_60.asm, unittests/32Bit_ASM/Primary/Primary_60_2.asm, unittests/32Bit_ASM/Primary/Primary_61.asm, unittests/32Bit_ASM/Primary/Primary_61_2.asm, unittests/32Bit_ASM/Primary/Push_Segments.asm, unittests/ASM/Primary/Primary_6A_2.asm
Thanks to Stefan for finding the missing pusha/popa and push/pop segment register instructions.
From the table changes we still are missing about nine 32bit instructions, which most of them are related to BCD.
This also uncovered a bug in the 8bit push immediate op. We were treating it as always pushing a 64bit sign extended value, instead it pushes a value the size of the operating mode.
Added a new unit test to ensure that.
=> More 32bit related fixes

External/FEXCore/Source/Interface/Core/X86Tables/X87Tables.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h
All of the ops that were relying on a 64bit memory offset were being
downgraded to 32bit.
Abuses the XMM_FLAGS option a bit to indicate that it shouldn't
downgrade the 64bit size flag. Which isn't an issue since all these
operations can't encode a register since modrm_r is used for table
decoding
=> Fixes 32bit x87 usage

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/X87Tables.cpp, unittests/ASM/X87/D8_D9.asm, unittests/ASM/X87/DA_D9.asm, unittests/ASM/X87/DA_E9.asm, unittests/ASM/X87/DD_E9.asm
FCOMP was missing the pop flag in the info table
FCOMPP and FUCOMPP actually pop two values off the stack, which we hadn't supported before.
=> Fixes FCOMPP, FUCOMPP, and FCOMP

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
This changes the arm & x86 backends to only generate branches when needed.
It also sorts the blocks on the frontend to make their order optimal for this.
This assumes that if a local branch exists for the current block, OP_JUMP or OP_JUMPCOND is the last opcode of the block.
=> JIT: fallthrough branching

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
This is required for the rest of PRs. I'll split into a separate pass after we merge all the changes.
=> ConstProp: Do inline constants in a separate loop

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
- Merge CC handling in `OpDispatchBuilder::SelectCC` helper
- Use it from jCC, setCC and cmovCC
=> OpDisp: jCC, setCC & cmovCC refactor

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h
- CompareSize can be 4 or 8
- DataSize can be 4 or 8
- Support for INLINE_CONSTANTS for `Select cmp1,cmp2,1,0` that specializes to cset / setcc
=> Select: Add compare & Data sizes, cset/setcc specializations

External/SonicUtils/Source/LogManager.cpp
Default to 1024 bytes in the working string, but if something exceeds it
then try again.
Not common that we are passing through a large string but debug strings
can hit that limit
=> Fixes long messages passed through logman

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/DeadFlagStoreElimination.cpp, External/FEXCore/include/FEXCore/Config/Config.h, Source/Common/ArgumentLoader.cpp, Source/Tests/ELFLoader.cpp, Source/Tests/TestHarnessRunner.cpp
- InvalidateFlags pseudo-op is a hint for the Dead Flags Elimination pass that flags are not needed past that point
- Adds a new option, --unsafe-local-flags, that invalidates the flags on CALLs or RETs. This might break code that doesn't follow the ABI rules.
- Adds a new option, --unsafe-no-pf, that doesn't calculate PF for integer operations. This might break code that actually uses PF.
- Renames --disable-tso to --unsafe-no-tso to group the options nicely
=> Unsafe opts: --unsafe-local-flags, --unsafe-no-pf, --unsafe-no-tso

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadFlagStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h
Depends on #488
- Renames Cond to Cmp1, adds Cmp2, adds Cond as a CC (to match select), backwards compatible emit that does Cmp2 = 0, CC = NEQ
- Adds support to the backends for Cmp1/Cmp2 & Cond, with special cases for == 0, !=0 and Cmp2 being a const
- Optimization to fold Selects to CondJumps whenever possible
*rebased and re-re-re-reviewed*
=> CondJump: Add support for two operands to match Select

External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
Now that it supports large strings we can push these through here.
We really need to avoid touching stdout/stderr as an interpreter
=> Ensures pass validation goes through LogManager

External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
This will be useful with the compile service coming up to keep
IRListViews coherent across threads
=> Allow copying of an IRListView copy

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h
Allows us to save memory in the frontend decoder by starting out with a
small buffer until we hit larger code blocks.
=> Adds resizable frontend decoded buffer

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
On cache clear this would munmap pages 1.5x past the code cache.
This most certainly leads to spurious bugs
=> Fixes cache clear bug on x86_64

External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/include/FEXCore/Core/CPUBackend.h
These structures need to be shared to the threaded compiler, so set it
up for copying.
Will be necessary for the compile service
=> Adds function for copying data required for threaded compiler

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Interface/Core/CompileService.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
This is made to be completely synchronous to a thread.
This is the first step to fixing the problems with games that send signals to itself in times when it is compiling code.
Unity+Mono still requires a bit more work that is in my WIP tree but this is the necessary compile service first since other applications can benefit from this.
There are a couple of assumptions made in the compile service that will assert if broken, those can be worked around if they become an issue.
This incorporates #502, #503, #504, #505, #506, #507, #508, #509, #511, and #512 which should be merged first!
=> Implements a threaded compile service routine

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/IREmitter.h, Source/Tests/IRLoader/Loader.cpp, Source/Tests/IRLoader/Loader.h, unittests/IR/Basic/MemoryData.ir, unittests/IR/Basic/Sbfe.ir, unittests/IR/Correctness/AddTruncate.ir, unittests/IR/Correctness/FPRStoreTruncate.ir, unittests/IR/Correctness/LeftShiftTruncate.ir, unittests/IR/Correctness/SubTruncate.ir
Adds a third argument to Load/StoreMem*, `Offset`, which is by default `Invalid()`. Also adds `OffsetType` (SXTX, SXTW, UXTW, supported options vary by backend), and `OffsetScale` (1, 2, 8, 16, supported options also vary by backend).
Modifies OpDispatcher to not generate TSO opcodes if TSO is disabled.
Modifies IRLoader to support `%Invalid`, extends IRWriter and IRLoader to support `MemOffsetType`.
The ever-more-complex constprop pass does
- Fills `Offset` whenever possible, either with reg or constant
- Detects `Offset = RealOffset * scale` or `Offset = Zext/Sext(RealOffset)` and sets `OffsetType` and `OffsetScale` accordingly
- If `Offset` is a constant, and if it can be inlined, it converts it to an `InlineConstant`.
- Supports Offset Reg
- Doesn't support Offset InlineConstant
- …
=> Complex address generation for Load/StoreMem

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h
This reverts commit c12251607768afa133971f316dcb54b25522e86f.
Broke multiblock. We can come back to this to save some memory.
=> Revert "Adds resizable frontend decoded buffer"

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
This
- Adds special cases for when the flags are a result of a cmp or a test
depends on #488, #491, #499
=> OpDisp: flags bypass

External/SonicUtils/Source/ELFLoader.cpp, External/SonicUtils/Source/ELFSymbolDatabase.cpp, External/SonicUtils/include/SonicUtils/ELFSymbolDatabase.h, Source/Tests/HarnessHelpers.h
Due to a bug dealing with empty program headers used as flags, we were previously relocating static ELFs up 16KB, which can cause them to break.
Fixes #498
=> Fix mapping of static elfs.

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h
This eliminates several IR ops that lie about support on the ARM 64 backend and moves the workarounds into Opcode Dispatcher
Alternative to #528
=> Remove 8/16bit ROR and all ROL IR ops as arm doesn't support them

External/FEXCore/Source/Interface/Core/CPUID.cpp
This has the same vendor ID in the as CPUID fn0000_0000
=> Fixes manufacturer id for CPUID fn8000_0000

External/FEXCore/Source/Interface/HLE/Syscalls/SHM.cpp, External/FEXCore/Source/Interface/HLE/x64/Memory.cpp
This removes the bad attempt to keep shm regions in our 64GB shm region
This will need to be handled specially on the 32bit side through its
memory management once we have that wired up
=> Moves shmat to 64bit memory specific file

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/include/FEXCore/IR/IREmitter.h
Similar to how we did `Zext` a special case of `Bfe`, this makes `Sext` a special case of `Sbfe`
=> IR: Replace Sext with Sbfe

unittests/32Bit_ASM/Primary/Pop_Segments.asm
I have no idea why nasm assembles it, however pop cs shouldn't exist. The test currently crashes with a sigsegv, and for some reason ctest thinks it passed.
`pop cs` decodes to `movhps` and `o16 pop cs` to `pcmpgtd` both in objdump and FEX.
$ objdump -b binary -m i386 -D unittests/32Bit_ASM/Primary/Pop_Segments.asm.bin
```
0:	bc 40 00 00 e0       	mov    $0xe0000040,%esp
5:	b8 00 00 00 00       	mov    $0x0,%eax
a:	50                   	push   %eax
b:	50                   	push   %eax
c:	50                   	push   %eax
d:	50                   	push   %eax
e:	50                   	push   %eax
f:	50                   	push   %eax
10:	66 50                	push   %ax
12:	66 50                	push   %ax
14:	66 50                	push   %ax
16:	66 50                	push   %ax
18:	66 50 …
```
=> Pop_Segments: pop cs is not a valid opcode

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp
- Removes needless VINSERTs
- Updates x86 tables to use 64 bit width for *SD ops
=> frontend: Improve IR for some *SS/*SD opcodes

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
- Removes masking from reads, as writes always mask. Interpreter already worked like this.
- Moves masking to IR ops
Follow up:
- Optimize frontend codegen to not need as much masking (Use BFEs instead of shifts)
=> IR: Move BFEs to SetFlag, remove from OP_STOREFLAG

External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp
- Optimize VIns* to only use temp reg if it must
- Avoid needless movs in OP_VMOV
=> arm64: Backend Opts

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
This makes `perf top` and such much more useful in multiblock
- Adds an array in DebugData to return information per ssa block
- Registers in the form of `JIT_<guest block head>_<host block-specific-entry>`
- Had to fix some plumbing for debug data
=> JITSYMS: Per-block symbol information

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/DeadFlagStoreElimination.cpp
- Uses `uint64_t` to track dead flags as we use up to bit 64
- `OP_INVALIDATEFLAGS` now takes a param to specify which flags
- Update frontend to invalidate PF when `unsafe-no-pf` is set
=> DFSE: Fix dead clag calculation, Extend InvalidateFlags

External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h
- Moves unary ops that depend on a select before the select, if both inputs are constants.
- Assumes that unary ops without side effects on constants will be constprop'd
=> CMT: Move unary ops before selects

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
This ~ doubles the perf on REP prefixed opcodes
Depends on #558
=> OpDisp: Read DF outside REP loops as it won't change

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
RA Pass and passmanager compaction pass don't need to be independent.
This saves some memory.
In the future we should allow passes to fetch passes by name, that will
be part of the PassManager improvement in the future
=> Remove duplicated compaction pass

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/HLE/x32/FD.cpp, External/FEXCore/Source/Interface/HLE/x32/FS.cpp, External/FEXCore/Source/Interface/HLE/x32/Memory.cpp, External/FEXCore/Source/Interface/HLE/x32/Sched.cpp, External/FEXCore/Source/Interface/HLE/x32/Semaphore.cpp, External/FEXCore/Source/Interface/HLE/x32/Socket.cpp, External/FEXCore/Source/Interface/HLE/x32/Syscalls.cpp, External/FEXCore/Source/Interface/HLE/x32/Syscalls.h, External/FEXCore/Source/Interface/HLE/x32/Thread.cpp, External/FEXCore/Source/Interface/HLE/x32/Time.cpp, External/FEXCore/Source/Interface/HLE/x32/Types.h
This implements a bunch of new 32bit syscalls which almost gets FEX to
be able to run Steam.
The main missing syscalls are mremap, shmat, and ioctl for supporting
Steam execution.
=> A wackload of new 32bit syscall support

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
(There is no reason not to)
This exposed a bug on the test, and as such depends on #559
=> LSE: Also optimize away partial writes

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
This means that NANs set all flags (like x86 does), instead of setting only the unordered one. Simplifies the rest of the logic.
Also optimized the aarch64 a bit
=> IR: Change FCMP to return x86-style flags

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json
- Adds float compare operations as COND_F*
- Extends CondJump and Select to support both integer and float compare params
- Adds a frontend calculation bypass similar to cmp/test
=> FCMP: Add frontend bypass, backend float support in OP_CONDJUMP & OP_SELECT

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
This was causing issues in 32bit xeyes.
A couple of the multiply ops were still using 8bit and 16bit multiply
while the other one was already sexting or zexting the source.
=> Removes the last usage of 8bit and 16bit multiply

External/FEXCore/Source/Interface/HLE/x32/FD.cpp, External/FEXCore/Source/Interface/HLE/x32/Socket.cpp, External/FEXCore/Source/Interface/HLE/x32/Thread.cpp, External/FEXCore/Source/Interface/HLE/x32/Time.cpp, External/FEXCore/Source/Interface/HLE/x32/Types.h
fstatfs64 and statfs64 was wrong, the syscall doesn't quite match the
glibc definition
Fixes recvmsg. Specifically the aux data was failing, thus SCM_RIGHTS
wasn't getting passed correctly.
Fixes a couple of time syscalls where their arguments are optional.
=> More 32bit syscall fixes

External/FEXCore/Source/Interface/HLE/Syscalls.h, External/FEXCore/Source/Interface/HLE/x32/Thread.cpp, External/FEXCore/Source/Interface/HLE/x64/Thread.cpp, External/FEXCore/Source/Utils/ELFLoader.cpp, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/Utils/ELFLoader.h, Source/Common/ArgumentLoader.cpp, Source/Common/ArgumentLoader.h, Source/Tests/CMakeLists.txt, Source/Tests/ELFLoader.cpp
Fixes a bunch of gnarly bugs that crop up due to trying to pass arguments to execve targets.
Adds a symlink FEXInterpreter target that doesn't consume any arguments itself. Necessary since applications could pass arguments that break initialization. We can't safely determine if we are the current executing interpreter otherwise.
Make the assumption that if an application executed through the interpreter will safely call back in to FEXInterpreter once execve is hit.
execve syscall checks if we are executing as an interpreter or not then execute the target application directly, letting the kernel handle the interpreter redirection. This allows us to correctly retain the target application's capabilities.
check out `man capabilities` for all the random features we are forced to inherit from …
=> binfmt_misc interpreter and execve improvements

Source/Tests/IRLoader.cpp, Source/Tests/TestHarness.cpp, Source/Tests/TestHarnessRunner.cpp
This was accidental and can cause test failures.
Make sure to not load arguments from Main config for these
=> Removes Main config loader from test runners

External/FEXCore/Source/Interface/Core/SignalDelegator.cpp
For the ones that should be IGNORE we can safely ignore them at that
point.
For the ones that have a default behaviour of crashing, just go ahead
and crash.
This was having the fun problem space that if we received an ignore
event, we would remove the fault handler then if the guest registered a
handler it would have never been called.
SIGWINCH specifically is one that defaults to ignore and we need to care
about. If SIGWICH happened before the guest registered a handler then it
would never receive the signal.
The ones that their default behaviour is faulting are fine to uninstall
and then immediately crash, since it is a real crash at that point.
=> Makes us handle DFL smarter

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
These are several small improvements
- Add RemoveUselessMasking, implement for a few ops
- Documented different sub-passes, remove leftover continue; statements
- Special case BFE, AND in RemoveUselessMasking sub-pass
- SBFE useless masking elim, VMOV useless zexting
- Elim Bfe on ops that zext by default
- Remove some BFEs that do nothing
=> ConstProp: Masking elimination

Source/Tools/FEXConfig/Main.cpp
Fixes the formatting. Everything was using the incorrect formatting.
Changes the saved msg popup to a generic popup handler.
If a file couldn't be opened, open a popup claiming the error.
Makes it nicer to realize when trying to open main and nothing happens
when the file doesn't exit
=> Fixes for FEXConfig

Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp
The virtual function is called directly, so we were missing the strace
functionality
Strace and HandleSyscall just moved to the base implementation class instead and deduplicated.
=> Removes dead HandleSyscall function

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/include/FEXCore/IR/IREmitter.h, unittests/ASM/REP/F3_2A_2.asm
Both x86 and AArch64 support converting from one sized GPR to another
sized FPR. Expose it in our IR op.
Fixes a bug in CVTSI2SS with a 64bit source and it was treating the
input source as a 32bit value.
eg:
0x0000'0000'FFFF'FFFF was treated as converting to -1 float, which was wrong since it is a 64bit value
Major thanks to d-bub on discord for isolating this to such an easy reproduction case!
=> Adds support for proper sized GPR->FPR sized conversions

External/FEXCore/Source/Interface/Core/BlockCache.cpp, External/FEXCore/Source/Interface/Core/BlockCache.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
This adds an direct cache (1M entries) for the block lookups. Lookups in the Cache are /much/ faster than full lookups, leading to overall speedup. The cache structure is also friendly to atomic modifications.
The cache hit rate is > 98% based on my testing, though it depends on the complexity of the guest app.
This also switches to dispatching via jmp instead of call/ret, and does inline dispatch at the end of each block.
```
auto& Entry = Cache[Addr & MASK];
if (Entry.Guest == Addr) {
return Entry.Host;
} else {
HostAddr = FullLookup();
Entry.Guest = Addr;
Entry.Host = HostAddr;
return HostAddr;
}
```
```
mov(r13, ThreadState->BlockCache->GetL1Pointer());
mov(rax, rdx);
and_(rax, 1 * 1024 * 1024 - 1);
shl(rax, 1);
cmp(qword[r13 + rax*8 + 0], rdx);
jne(FullLookup);
call(qword[r13 + rax*8 …
```
=> BlockCache: Add a cache for faster lookups

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MoveOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadFPRStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadFlagStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadGPRStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.h, External/FEXCore/Source/Interface/IR/Passes/StaticRegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/IR/IR.h
Static Register Allocation keeps the guest context in fixed host registers in order to reduce load/stores and moves. 
The way this implementation works is: It replaces all eligible Load/Store Contexts to Load/Store Register, It adds an extra pass after the liveness analysis that determines whenever moves to/from the SRA host registers can be eliminated, and it adds context syncing logic. 
SRA is only implemented for the arm64 backend.
This
- Adds `OP_LOADREGISTER` and `OP_STOREREGISTER` to manipulate the statically allocated register context.
- Adds a new pass, StaticRegisterAllocation, than converts Load/Store Context to Load/Store Reg.
- Add two new allocation classes, `GPRFixedClass` and `FPRFixedClass`.
- Extends RegisterAllocation to alias-allocate `LoadRegister` and pre-write …
=> SRA: Static Register Allocation

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/include/FEXCore/Core/Context.h, Source/CommonCore/HostFactory.cpp, Source/Tests/TestHarnessRunner.cpp
This patch moves HandleSIGSEGV in HostFactory.cpp to a non-frontend host signal handler, then registers its own frontend signal handler to catch unhandled segmentation faults. 
Related issue: #561
Still needs an intentionally failing test to verify, so I'm marking this as a draft for now.
=> Have tests that throw a non-HLT SIGSEGV fail

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json
=> Dispatch: Distributed Dispatch, IR Optimizations

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/32Bit_ASM/Primary/Loops.asm, unittests/32Bit_ASM/Primary/Primary_E3.asm
JCXZ (X86 + address size prefix) was not processed correctly here, potentially leading to infinite loops.
=> Fix a few branching instructions on x86-32

External/FEXCore/Source/Interface/Context/Context.cpp
Once we fork, we no longer have any threads to track in the process.
Ensures we don't spin forever on forked process
=> Ensure idle wait ref counter is 1 on fork

Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/Thread.cpp
We need to check to see if the application wanting to be executed is in
the rootfs first. Otherwise we end up in a case where we either lose
tracking of applications in FEX, or applications fail to launch since
they don't exist in the global filesystem
=> Fixes execve with rootfs

Source/Tests/TestHarnessRunner.cpp
DumpIR was not passed through the config to CTX in the TestHarnessRunner, leading to confusion when running it independently from the tests.
=> Pass DumpIR to TestHarnessRunner

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h
When we are running in 32bit mode then it is possible to have an
instruction's modrm working as 16bit mode.
All one needs to do is prefix the instruction with an address size
override
=> Fixes 16bit ModRM rm decoding

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp, Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.h
This was being checked by an application for kernel version. Which was
seeing too new of a kernel and using things that were unsupported.
Also removes the EmulatedMap which is an unnecessary lookup.
=> Have EmulatedFiles support osrelease file

unittests/POSIX/Disabled_Tests, unittests/POSIX/Known_Failures
killpg has been causing us testing problems for a while now.
As we were running more tests it was becoming more likely to hit a test
doing killpg in the background.
All of the tests run under the same process group so it is a significant
race condition to have these running.
Until we improve CI to somehow work around how killpg works, we just
need to have these disabled.
=> Disables killpg tests and reenables a few tests

External/FEXCore/Source/Utils/LogManager.cpp, External/FEXCore/include/FEXCore/Utils/LogManager.h, Source/Tests/ELFLoader.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.h
=> Uninstalls both the signal delegator and logmanager handlers on shutdown

External/FEXCore/Source/Utils/ELFSymbolDatabase.cpp, External/FEXCore/include/FEXCore/Utils/ELFSymbolDatabase.h, Source/Tests/HarnessHelpers.h
Instead of hardcoding 64bit dynamic ELF files to 0x1'0000'0000 we
instead calculate the size of the ELF in memory. Then allocate the
ELF base up front.
LLVM ASAN steals a large amount of virtual memory space that intersected
with the original hardcoded range which caused memory allocations to
fail.
=> Fixes 64bit ELF loading when LLVM ASAN is used

External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
=> Dispatch: ExitFunction InlineConstant & unsynchronized rip

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/DDDTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h, unittests/32Bit_ASM/Primary/Primary_8D.asm
There were some edge cases that weren't quite working in the previous test.
Adds some unit tests to ensure it is working correctly.
One edge case was when 16bit addressing was used with a literal offset in the instruction encoding. The literal would have failed to decode. This was impossible to hit on Linux though.
Another one is when the 16bit address was calculated, it wasn't being properly zext.
=> More 16bit addressing mode fixes

Source/Tests/ELFLoader.cpp, Source/Tests/HarnessHelpers.h, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls.h
This will also be used soon to calculate if we can use ioctl32, which syscalls to version against, and our emulated uname version implementation.
=> Adds kernel version check to FEXLoader

External/FEXCore/Source/Interface/Core/BlockCache.cpp, External/FEXCore/Source/Interface/Core/BlockCache.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, unittests/ASM/SelfModifyingCode/Delinking.asm
Rebased on top of #637 this changes `OP_EXITFUNCTION` to link when arguments are `InlineConstants`
Linking consists of a few different parts.
`JITCore::ExitFunctionLink` takes care of looking up the guest rip from the link record, update it to link to the expected block or backpatch the code for a direct link, and return the next executed pointer. If it fails to find the block, it returns `AbsoluteLoopTopAddress`. It also adds de-linking entries to the Block Cache.
`JITCore::ExitFunctionLinker` (asm-dispatcher) is the default entrypoint that is called when an ExitFunction is not yet linked to a specific block. It recovers the record from the return address (`lr` or from `rax`), calls `JITCore::ExitFunctionLink` and jumps to the returned value.
`BlockCache::AddBlockLink` Is added, that …
=> Block linking

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IREmitter.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h, unittests/ASM/Primary/Primary_A4_REP_many.asm
When blocks aren't ordered in program order we get global variables that we can't spill. With enough unspillable vars we end up failing to compile the function.
This
- Adds an option to insert blocks right after the current block or at then end of the function
- Modifies OpDisp to insert blocks in program order
- Modifies branches for slightly better perf for fall through edge cases
- Optimizes some conditionals is OpDisp
- Adds a test with loads or REPs that requires this optimization
##
=> OpDisp: Improved Block Ordering

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, unittests/ASM/Multiblock/ReachableInvalidCode.asm
Allows multiblock to compile blocks where some paths lead to invalid / unsupported instructions.
- Moves REX handling to `Decoder::DecodeInstruction` from `HandleOpHeader`
- Makes `HandleOpHeader` and `HandleOp` return false for unhandled cases instead of asserting
- Adds `HasInvalidInstruction` to `DecodedBlocks`
- Updates `DecodeInstructionsAtEntry` to set `HasInvalidInstruction` to true for blocks with invalid instructions, or assert if the entry block as an invalid insn.
- Updates `Context::CompileCode` to not compile blocks with invalid instructions
=> Frontend, OpDisp: Don't assert on invalid instructions

CMakeLists.txt, Scripts/aarch64_fit_native.py
Some of the newer CPU cores in LLVM's source claim to be a Cortex-A73,
which means they become limited to an ARMv8.0 feature set.
This is what you get if you compile FEX with -mcpu=native
To work around this issue, manually parse /proc/cpuinfo ourselves and
pull out the CPU type to pass to clang directly.
This also fixes the issue that we were using -march on AArch64, which no
longer works on newer clang versions. We instead need to use mcpu or
mtune.
Should improve all atomic op performance outside of the JITs, where they
were turning in to loadstore exclusive pairs.
Fixes #668 on our end.
=> Works around Clang failing to identify new Kryo CPUs

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, unittests/ASM/Disabled_Tests, unittests/ASM/Secondary/09_XX_01_7.asm, unittests/ASM/Secondary/09_XX_01_8.asm, unittests/ASM/Secondary/09_XX_01_9.asm, unittests/ASM/TwoByte/0F_B0_3.asm, unittests/ASM/TwoByte/0F_B0_4.asm, unittests/ASM/TwoByte/0F_B0_5.asm, unittests/ASM/TwoByte/0F_B0_6.asm, unittests/ASM/TwoByte/0F_B0_7.asm, unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
Adds a wackload of unit tests to handle all the prickly edges that unaligned atomics can hit here.
Currently disabled because they don't pass on ARMv8.0 which uses loadstore exclusive pairs which is harder to ensure is correct.
For any cmpxchg or cmpxchg8b instruction that is unaligned we will convert it in to a larger aligned CAS operation.
In the case that the operation crosses a 16byte or 64byte cacheline boundary, it will be split in to two CAS ops that can tear.
For the 16byte variant, this is fixed with ARMv8.4 LSE2. It can't be fixed any other way.
For the 64byte variant it matches AMD behaviour, not Intel behaviour.
Might be worth routing this to telemetry data in the future to know when we need to force threads in to single threaded behaviour.
=> Handle unaligned cmpxchg and cmpxchg8b on ARMv8.1+

Source/Common/ArgumentLoader.cpp, Source/Tests/ELFLoader.cpp, Source/Tools/FEXConfig/Main.cpp
For good performance out of the box multiblock, with a default blocksize of 5000 and use IRJIT
resolves #685
=> Better Default Configuration

External/FEXCore/Source/Interface/Core/X86Tables/PrimaryGroupTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryModRMTables.cpp
Rather than just stating UND
We can't support this until we have an ARM CPU that supports TME and
more robust multiblock.
=> Add TSX names to decode tables so we know what they are

Source/Tests/LinuxSyscalls/Syscalls/Timer.cpp, unittests/gvisor-tests/Disabled_Tests
The glibc and kernel timer interfaces are sufficiently different enough
that unwrapping this through glibc is impossible.
Pass it directly through to the kernel.
Two gvisor tests that were on the fail list are now on the disabled test. Since they get farther then hang.
=> Fixes timer syscall API

External/FEXCore/Source/Interface/Core/X86HelperGen.cpp, External/FEXCore/Source/Interface/Core/X86HelperGen.h
This is visible to the guest process so for 32bit it needs to be in the
lower 32bits.
=> Forces SIGRET handler to the lower 32bits VA on 32bit processes

External/FEXCore/Source/Utils/ELFLoader.cpp, External/FEXCore/include/FEXCore/Utils/ELFLoader.h, Source/Tests/ELFLoader.cpp, Source/Tests/HarnessHelpers.h, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, unittests/gvisor-tests/Known_Failures
Base size is now only one page in size. We will then increment that BRK
size by 8MB alignments. 256MB for 32bit applications was causing some
applications on the edge to run out of virtual memory
I was hitting some 32bit applications that were being fairly mean with
BRK. They were allocating all of BRK space then running out of virtual
memory space with its mmap handler fallback after freeing BRK space.
This means we now munmap BRK pages on release for the guest, similar to
behaviour that Linux does.
Additionally I had an application that was getting very upset that BRK
wasn't actually at the end of program space. So allocate at the end of
program space like expected.
=> More improvements to BRK handling

Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x32/Semaphore.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.h
This was partially implemented before but it had some bugs still.
This fixes those bugs and also implements mremap, shmat, and shmdt.
This now works well enough for 32bit graphical applications
Fixes #692
=> Finishes 32bit memory allocator

Source/Tests/LinuxSyscalls/x32/Syscalls.cpp
It's not defined on Ubuntu 20.04
=> Syscalls: Define MREMAP_DONTUNMAP if missing

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/Interpreter/x86_64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/LookupCache.cpp, External/FEXCore/Source/Interface/Core/LookupCache.h, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp
This renames BlockCache to LookupCache, and adds a 3rd level of lookup so that inserts never fail and that the lookup cache doesn't 'forget blocks'.
If L2 is full, it'll reset and lazy re-build the lookup cache from L3.
- #721
=> BlockCache -> LookupCache, L3C

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Interface/Core/CompileService.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/IRDumper.cpp, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.h, External/FEXCore/include/FEXCore/Core/CPUBackend.h, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/RegisterAllocationData.h, Source/CommonCore/HostFactory.cpp
Sadly the two parts can't be nicely separated because of how the core/context/compile service were interacting.
Moves reg alloc mappings to `RegisterAllocationData` (RAData) from `RAPass`. This makes it possible to re-compile from IR w/o running the optimization passes again. Needed to fix some edge cases where we used stale RA data, for IRLists caching to work and for AOT in the future.
This majorly refactors how code gets compiled, and cleans up a lot of things in the way. Removes the LookupCache, IRLists, DebugData usage from the Compile Service, simplifies how caches are cleared, stores RAData so that IRLists can be correctly re-compiled and loads of other cleanups.
=> RA: Split RAData from RAPass, Optimize data packing, Cleanups

unittests/gcc-target-tests-64/Disabled_Tests, unittests/gcc-target-tests-64/Known_Failures
It's flaky on the ARMv8.0 runner
=> Disable `mcount_pic.c.gcc-target-test-64` test

unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
=> Disable more flaky gvisor tests

CMakeLists.txt, External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/LookupCache.h, External/FEXCore/Source/Interface/IR/IRParser.cpp, External/FEXCore/Source/Utils/ELFLoader.cpp, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/Core/CoreState.h, External/FEXCore/include/FEXCore/Core/UContext.h, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, External/FEXCore/include/FEXCore/Utils/ELFLoader.h, Source/Common/Config.cpp, Source/Tests/CMakeLists.txt, Source/Tests/HarnessHelpers.h, Source/Tests/LinuxSyscalls/CMakeLists.txt, unittests/32Bit_ASM/CMakeLists.txt, unittests/ASM/CMakeLists.txt
These are all the changes I needed to make while trying to get FEX built under termux on my android phone.
I've put this porting effort on hold for now, as NDK r21 doesn't implement `std::filesystem` and termux are still working on updating to r22. 
Apart from `std::filesystem` issues, I manged to get FEXCore building. The LinuxEmulation layer is going to need some more work. 
I have another PR coming which allows building and running IRLoader without LinuxEmulation (which it doesn't use).
=> Android build fixes

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
The new left-shift that replaced the multiply takes
it's size from arg[0]. If arg[0] was 64bit and the original
OP_MUL was 32bit, then the original code would truncate
upper bits, and the replacement code wouldn't.
This bug broke the SSL cert checking code in geekbench,
causing it to fail to upload results.
Fixes #647
=> Fix power of 2 OP_MUL optimisation (Fixes Geekbench result upload) 

External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
With multiblock and -n4000, at least one block in geekbench5's camera
benchmark was spilling 324 values. This meant the required stack
adjustment was 5184 bytes, which is larger than can fit into a 12bit
immediate.
Now, it's probally a bug that our RA is spilling that many values, and
we probally should be packing our spill slots closer together, but we
still shouldn't fail to run in this edge case.
So this commit adds a fallback path which uses a temp register to load
the stack adjustment.
=> arm64: Fix blocks with over 256 spill slots.

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/IRParser.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Interface/IR/Passes/StaticRegisterAllocationPass.cpp
This adds a "fallback" path for unimplemented opcodes in the JITs, and adds an interface to query the interpreter for opcode "fallbacks". The interface is semi-generic so it can be used to fallback any opcode, however only the x87 opcodes have been implemented. `ShouldInterpret` & All related logic has been removed.
This passes all tests now
- Add `JIT::PushRegs` && `JIT::PopRegs`
- Remove xmm0 from allocated regs as it is the return value
- Add xmm11 as an allocated reg, and use xmm0 as scratch reg in its place
- Add fallbacks for the abis used by x87 handlers
- Implement VBSL
- Remove `ShouldInterpret` logic
- Add fallback logic
- Remove empty F80Cmp handler
- Remove `ShouldInterpret` logic
- Make sure that F80CVTTo ops use FPR/GPR arguments as they should
- Replace VSTOREMEMELEMENT …
=> x87: Call C++ handlers instead of forcing interpreter

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MoveOps.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, unittests/gcc-target-tests-32/Known_Failures, unittests/gcc-target-tests-64/Known_Failures
Several small things got broken over the past few months
- Fix Frontend to only return false if it has invalid ops in the first block
- Fix CreateElementPair to handle edge cases
- Remove an erratic assert from RA (spill class doesn't have to match value class when spilling a GPR/GPRPair conflict)
=> Fixes for Counter Strike Global Offensive

Source/Tests/LinuxSyscalls/x32/FD.cpp
The select group of syscalls sets the fd_sets based on which fds are ready. Our marshaling logic only did guest -> host, but not host -> guest after calling the system call. This fixes that.
=> Syscalls/x86-32: Fix selects to remarshal the fd_sets

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
This is needed for Half Life 1 & 2, as well as most Source titles.
This is not an accurate model of how the instructions works
#782
=> X87: FPREM needs to set C2 to 0 to indicate finished iteration

External/FEXCore/Source/Common/SoftFloat.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/IRParser.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/include/FEXCore/Core/CoreState.h
Adds rounding mode, precision control and implements fisttp* as truncating conversions.
Fixes rendering in Counter Strike 1.6, fixes valgrind's `insn_fpu` & `insn_sse3`
- #779, #780
=> x87: Round, Truncate & Precision control

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/gcc-target-tests-32/Disabled_Tests, unittests/gcc-target-tests-32/Known_Failures, unittests/gcc-target-tests-64/Disabled_Tests, unittests/gcc-target-tests-64/Known_Failures
Fixes sar8 and sar16 sign extension in OpDisp. Fixes #774
#786
=> OpDisp: Imm SAR OpSize < 32 needs sign extension

.github/workflows/ccpp.yml
Passes the log movement stage to clean up the output.
Really it is only the first unit test stage that is failing, but each
subsequent log run will have failed to move since the previous stage
didn't run.
Makes it easier to scan over a failure as only the first unit test
failure step.
=> Pass log moves on buildbot stage failure

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
These usually don't get hit, but Geekbench4 DOES manage to hit LOCK on
BTS.
Which we just don't support right now.
=> Adds assert checks on missing LOCK support

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
glibc has a bug in the cache size lookup logic and mistakenly calculates the cache size as 0 if no information is given.
memcpy has a further bug that it assumes that the size of cache is > 144 bytes, leading to out of bound memcpys.
This adds a basic cpuid 0x2 function, and also adds a log for unhandled cpuid bits in debug bulds.
Fixes glibc2.33 that uses ssse3 memcpy that has the bug.
=> CPUID: Add cache information, function 0x2

ThunkLibs/include/common/Guest.h
```static __attribute__((naked))``` is missing from ubuntu 18.04's cross gcc for x86-64
=> Thunks: Convert guest thunk to asm, to avoid issues with older gcc versions

External/FEXCore/Source/Interface/Context/Context.h
It's really unhelpful that libstdc++ includes this by default
fixes editor-only error and gets us closer to building on android again.
=> Add missing unordered_map include

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/LookupCache.h, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/Core/Context.h, Source/Common/ArgumentLoader.cpp, Source/Tests/ELFLoader.cpp, Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x64/Memory.cpp, Source/Tests/TestHarnessRunner.cpp, Source/Tools/FEXConfig/Main.cpp, unittests/ASM/CMakeLists.txt
To get gimp working w/o --smc
This flushes the cache on `mmap` or `munmap`, and on `mprotect` w/ `PROT_EXEC` set. The idea is to catch .so load and unload, to avoid the actual need for smc tracking for non-jits.
This is a very naive implementation that uses block-lists per-page, and erases the entire page when touched.
With this, GIMP works at interactive speeds.
=> Flush IR/Code cache on mmap, mmunmap & mprot

CMakeLists.txt
=> Disabled cmake check for python development

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp, unittests/ASM/H0F38/66_2A.asm
Found this when running Steamlink under FEX on my laptop.
Turns out the Iris video driver now uses this unconditionally in a couple of locations.
Makes sense there since all the Iris targets are expected to support SSE4.1 atm.
=> Implements MOVNTDQA

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
This exposes some cache information including cacheline information.
Fills out this data structure as well just incase we hit another cacheline size bug
=> Implements CPUID 0x8000'0006 for cacheline information

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
@skmp commented about this in the L2 cacheline information PR.
Quickly implement it since it also has cacheline information.
Fairly trivial since every piece of information is just some 8bit variables.
=> Implements CPUID 0x8000'0005 for L1 cacheline information

External/FEXCore/Source/Common/StringConv.h, External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/GdbServer.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86HelperGen.cpp, External/FEXCore/Source/Interface/HLE/Thunks/Thunks.cpp, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/Config/ConfigValues.inl, Source/Common/ArgumentLoader.cpp, Source/Common/Config.cpp, Source/Core/CPU/HostCore/HostCore.cpp, Source/Tests/ELFLoader.cpp, Source/Tests/HarnessHelpers.h, Source/Tests/IRLoader.cpp, Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.h, Source/Tests/LinuxSyscalls/FileManagement.h, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/x64/Memory.cpp, Source/Tests/TestHarness.cpp, Source/Tests/TestHarnessRunner.cpp, Source/Tools/Debugger/IMGui_I.cpp
Configuration mapping was duplicated between three different tables.
Additionally default configuration values were strewn about. Making it confusing as to what the default value would end up being
Adds a new ConfigValues.inl header that defines a few things right next to each other.
Defines the enum name as usual.
Defines the JSON config option name.
Defines the Environment config option name
Defines the default value that the configuration should be
=> Deduplicates some configuration data

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp
This is currently bugged on Snapdragon 865.
Seems to only affect its prime core. Smells like errata.
=> Disables RCPC on ARM64 JIT

External/FEXCore/Source/Utils/ELFLoader.cpp, External/FEXCore/include/FEXCore/Utils/ELFLoader.h, Source/Tests/ELFLoader.cpp, Source/Tests/HarnessHelpers.h
Passes the result back up to the frontend as well which allows us to early exit correctly.
Also ensures that we return ENOEXEC on these error cases so if someone is waiting on a return value, they don't just get zero
Fixes #757
=> Extends error message about not being able to find guest interpreter

External/FEXCore/Source/CMakeLists.txt
Depends on https://github.com/Sonicadvance1/vixl/pull/1
This also fixes a bug I introduced with previous PRs where arm64 debug builds of FEX would fail to backpatch correctly.
=> Improve vixl cmakefiles

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Utils/LogManager.cpp
va_list types have an edge where after operating on it, then it is undefined behaviour to do anything other than va_end on the object.
So in order to call vsnprintf on it multiple times we must create copies with va_copy.
Easy enough to work around by doing a few more copies of the va_list
=> Fixes crash with large strings through LogManager

Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x32/Semaphore.cpp, Source/Tests/LinuxSyscalls/x32/Thread.cpp
These are straightforward to implement. Only a few dozen more syscalls missing on 32bit
=> Adds a couple new 32bit syscalls found while running Steam

External/FEXCore/include/FEXCore/Config/Config.h
This has the expected behaviour that the configuration option will be available and not default initialized.
To enforce this fact, it will assert if it tries to get a value that doesn't exist yet.
Currently unused but should be used for any configuration option that is guaranteed to have a value.
=> Adds config value option constructor without default initializer

Source/Tests/CMakeLists.txt, Source/Tests/LinuxSyscalls/CMakeLists.txt, Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/Info.cpp
While implementing /proc/version I noticed we weren't pushing the FEX version to this correctly.
We hadn't ever defined FEXCORE_VERSION so it was always just a 1.
Now we correctly set the version to our describe version and also wraps /proc/version with the same information.
Fixes #840
=> Fixes uname version and wraps /proc/version

CMakeLists.txt, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IRDumper.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
This removes a significant number of warnings from FEX.
Avoids changing code that would conflict with #831 though.
Remaining warnings end up being in externals or the `offsetof(FEXCore::Context::Context, Config.RunningMode)` warning
=> Remove most warnings from FEX

Source/Tools/FEXConfig/Main.cpp
This burns a decent amount of CPU time just idling and we don't have active screen elements to matter here
It's still responsive because it'll update as the window gets any events
=> Fixes FEXConfig trying to update full refresh

External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
Fixes steam w/ all optimization passes enabled
=> RCLSE: Invalidate around OP_SYSCALLs, Syscalls might read the context

Source/Tests/LinuxSyscalls/Syscalls/Info.cpp, Source/Tests/LinuxSyscalls/Syscalls/Stubs.cpp
We are only using this for syscalls getcap and setcap.
These are only passthrough pointers and don't need to be handled from a library.
Noticed this while writing user documentation
=> Removes libcap-dev dependency

Source/Tests/LinuxSyscalls/FileManagement.cpp, Source/Tests/LinuxSyscalls/FileManagement.h
This seems to cause the geekbench 4.4.4 crashes, still not 100% sure. It's a bug nonetheless.
Likely fixes #847 and #846
=> EmulatedFiles: Lock around FDToNameMap accesses

External/FEXCore/Source/Interface/Core/CPUID.cpp
I keep forgetting to enable this bit. Fixes #855
=> Enables Invariant TSC CPUID bit

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
ARMv8 allows you query the cycle counter register very from userspace which allows us to emulate this easily.
My IceLake device returns 1.5Ghz through this interface
My AMD Zen+ device doesn't support this but with measurements has 3Ghz TSC
My Snapdragon 865 device has a TSC frequency of 19.20Mhz
Fixes #862
=> Implements CPUID 15h

.github/workflows/ccpp.yml, CMakeLists.txt, Scripts/StructPackVerifier.py, Source/Tests/LinuxSyscalls/CMakeLists.txt, Source/Tests/LinuxSyscalls/x32/Types.h
This is a fairly complex script that walks all structs and unions in a header and following some annotations tied to the declarations will compare those struct definitions to different struct "aliases" and across architectures.
This is important for:
- Ensuring our hand defined structs for syscalls matches what the syscall wants through aliasing rules
- Ensuring thunk generated structs match across the architecture boundary
We really need to rely on a script for this, hand checking every struct is prone to failure and won't catch every case.
Additional documentation: https://wiki.fex-emu.org/index.php/Development:StructPackVerifier
=> libclang based Struct verifier written in python

unittests/32Bit_ASM/CMakeLists.txt, unittests/ASM/CMakeLists.txt
We switched the default over a while back, so we haven't been getting test coverage with multiblock off
=> Explictly as for --no-multiblock in tests

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
FNSAVE also inits the fpu. Also fixed FNINIT to clear the flags.
This fixes #780. Follow up work for missing FTW #871
=> X87: Init on X87FNSAVE, fix FNINIT

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
This adds a `HandledLock` variable to OpDispatcher, that is used in `Core.cpp` to make sure the lock prefixes have been handled.
It also adds the segment offsets missing from some memory opcodes (often ones with LOCK)
Addresses most of #845 and implements #793
=> OpDisp: Validate LOCK handling, add missing segment offsets

External/FEXCore/Source/Interface/Config/Config.cpp, Source/Common/ArgumentLoader.cpp
This takes the changes from #829 and moves it to the correct location to be picked up from any loader.
This also fixes #873.
Expands the config paths. Anything that has ~ or is relative will be converted to an absolute path.
=> Implements a couple quality of life configuration option handling

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/Thread.cpp
Massively reduces memory usage for programs that fire up large number of threads that only run for a short amount of time.  
This makes it viable to run 24 threads of geekbench without AOTIR (peeks at about 7gb of memory)
fixes #772 
fixes #760
=> Cleanup threads when they exit

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Core/CPUID.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json
Leafs come from ECX but only some CPUID functions support this.
This adds the initial infrastructure but doesn't yet add support for the CPUID functions to consume the leaf.
=> Adds support for CPUID leafs

Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/Thread.cpp, unittests/gvisor-tests/Known_Failures
Notably this allows applications to work that don't require the namespace but check up front if they are able to clone with it.
Civ 6's launcher checks this as an example
=> Returns EPERM on clone with namespace

CMakeLists.txt, Source/Tests/CMakeLists.txt, Source/Tests/FEXBash.cpp, include/Config.h.in
This is a helper program to execute a bash command through FEX.
Works around an edge case of
eg:
FEXInterpreter /bin/sh -c "echo A"
versus
FEXBash "echo A"
Argument expansion ends up being a pain point
This isn't currently used but will be very shortly
=> Adds a FEXBash helper program

CMakeLists.txt, Data/AppConfig/CMakeLists.txt, Data/AppConfig/steam.json.in
These need to be used sparingly, we don't want to proactively crush user options.
=> Implements support for installing global application profiles

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/include/FEXCore/Config/Config.h
This was a missing feature that I had skipped previously.
Before this commit, each layer would overwrite all previous environment variables if they had anything defined.
After this commit, the layers will now merge in priority order.
Meaning if a higher priority layer has the same environment variable defined, it will overwrite that specific variable
Ending up with a superset of all the layer's environment variables now.
=> Fixes environment variable configuration from multiple layers

External/FEXCore/Source/Interface/Config/Config.cpp
If the config exists as an empty string then this would crash
=> Fixes crash on empty path config string

CMakeLists.txt, ThunkLibs/GuestLibs/CMakeLists.txt, ThunkLibs/HostLibs/CMakeLists.txt
This is necessary for building FEX packages that contain some initial thunk libs.
Gives an initial foothold for a default location for the host and guest thunk folders
=> Allows installing of FEXThunks in our data directory

Dockerfile
Python3, Python3-dev and linux-headers prevent from building on arm64
=> Dockerfile add arm64 compatibility

External/FEXCore/Source/CMakeLists.txt
This now creates an object binary then static and shared libraries from that.
This stops us outputting warnings twice in FEXCore.
Also improves compilation time even with ccache enabled.
Went from 12s to 8s compilation WITH ccache.
I'm sure without ccache it is even better.
Fixes #899
=> Stop compiling FEXCore twice

External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp
There are a couple of warnings remaining but need restructuring to solve.
I believe @phire is going to fix the one warning about a virtual destructor in a upcoming PR.
Fixes #679
=> Removes remaining warnings from AArch64 JIT.

External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/DDDTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/EVEXTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/H0F38Tables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/PrimaryGroupTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryGroupTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryModRMTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/X87Tables.cpp, External/FEXCore/Source/Interface/Core/X86Tables/XOPTables.cpp, Source/Tests/FEXBash.cpp, Source/Tests/UnitTestGenerator.cpp, Source/Tools/Debugger/IMGui_I.cpp
Just learned that this is a c++17 feature and it's a nice little
cleanup.
Only one remains in our codebase which can't easily be replaced
=> Replaces FEX's usage of classic C array element count with std::size

External/FEXCore/Source/Interface/Core/Frontend.cpp
In the case of overflow then it'll just mask this result.
The rest of the logic already matches what 32-bit expects.
Fixes #703
=> Adds a 32-bit mask for multiblock RIP calculation

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp
Removes the need for an out-variable.
While we're in the same area, some minor other tidying up can be done.
Made just to get my feet wet with contributing :)
=> Context: Make use of std::optional with GetFilenameHash() 

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Fixes a case where the reason gets overwritten.
=> OpcodeDispatcher: Add missing break for UD2 in INTOp()

Scripts/changelog_generator.py, Scripts/doc_outline_generator.py, Scripts/generate_changelog.sh, Scripts/generate_doc_outline.sh, Scripts/generate_release.sh
This generates a doc outline from tags in the .c/.cpp/.cc/.h/.hpp files.
To be used at least between releases to update the doc file
To Generate, run in git root folder ```Scripts/generate_doc_outline.sh > docs/SourceOutline.md```
Tags look like
```
$info$
glossary: <name> ~ <definition> (Optional, registers or replaces a glossary entry)
glossary: IR ~ Intermidiate Representation, a of storage for our high-level opcode representation
glossary: SSA ~ Single Static Assignment, a form of representing IR in memory
glossary: Basic Block ~ A block of instructions with no control flow, terminated by control flow
glossary: Fragment ~ A Collection of basic blocks, possible an entire guest function or a fraction of it
category: <name> ~ <description> (Optional, registers or replaces a category …
```
=> Docs: lightweight doc autogen

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Common/SoftFloat-3e/extF80_roundToInt.c, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
Prevents a class of sneaky logic bugs from slipping through into the codebase.
This also resolves a case of such a bug within the Decorder's ReadData() where all 3 byte reads would be performed as if they were a 4 byte read.
=> CMakeLists: Flag unannotated implicit fallthrough as an error

External/FEXCore/Source/Interface/Config/Config.cpp
`emplace()` only performs an insertion or assignment if the key doesn't already exist within the map, which is at odds with what the comment above the line indicates should happen.
We can use `insert_or_assign()` to make the behavior work like how the comment indicates it should.
If the existing behavior is more desirable, I can just amend the comment and drop the functional changes.
=> Config: Make lookup map assignment match behavior of comment

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Config/Config.json, External/FEXCore/include/FEXCore/Config/Config.h, Source/Common/Config.cpp, Source/Common/Config.h, Source/Tools/FEXConfig/Main.cpp
If the relative or absolute folder doesn't exist then FEX will search in the data folder for a rootFS named the same thing
If the path exists then it is used.
For example if my data folder contains `$HOME/.fex-emu/RootFS/Ubuntu_main/` and I set the RootFS option to `Ubuntu_main`
Then this rootfs will be used. Allows you to easily select a rootfs in that folder without having the full file path.
Relies on #916 being merged first
Fixes #684
=> Adds support for named rootfs configurations

Source/Tests/LinuxSyscalls/Syscalls/Info.cpp, Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
FEX doesn't support seccomp in userspace and allowing these through causes chromium secure sandbox to break.
Disabling these with EINVAL allows FEX to behave as if seccomp isn't enabled in the kernel config
Necessary to get the Civ6 launcher further
=> Disables seccomp

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Interface/Core/CompileService.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/GdbServer.cpp, External/FEXCore/Source/Interface/Core/GdbServer.h, External/FEXCore/Source/Utils/Threads.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, External/FEXCore/include/FEXCore/Utils/Threads.h, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/Thread.cpp
This defaults to a pthread implementation but it can be switched over to a custom thread
handler if the frontend desires.
=> Switches FEXCore over to pthreads implementation 

External/FEXCore/Scripts/config_generator.py
The default_value doesn't have anything to do with the boolean argument being set.
Setting a boolean argument will always set true, inverted always sets false.
We don't currently have a need to support the inverted case where passing in an argument sets it to false
=> Fixes inverted boolean FEXLoader arguments

Scripts/changelog_generator.py, Scripts/generate_release.sh
Generates the current and previous tag automatically.
Checks to ensure the previous tag exists and that the current tag does not
Lets me run the script and then just check it after the fact.
Will break if we don't have a release for a month, which I'll deal with when it happens
=> Updates release script to match what I want it to be

Source/Tests/LinuxSyscalls/x64/FD.cpp
This doesn't exactly match the glibc call so do the syscall directly
Fixes a couple subtests
=> Fixes pselect6 signal arg pack argument

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/include/FEXCore/Config/Config.h, Source/Tools/FEXConfig/Main.cpp
These aren't meant to be set by the user
=> Fixes FEXConfig filling in unnamed options

Source/Tests/LinuxSyscalls/x64/Time.cpp, unittests/POSIX/Known_Failures, unittests/gvisor-tests/Known_Failures
glibc version behaves slightly differently than kernel
=> Fixes clock_nanosleep

Source/Tests/LinuxSyscalls/Syscalls/FS.cpp, unittests/gvisor-tests/Known_Failures
These were using the passthrough helper which doesn't was breaking the result value
=> Fixes truncate and creat

Source/Tests/LinuxSyscalls/Syscalls/FD.cpp
glibc function signature doesn't match kernel
=> Fixes eventfd and eventfd2

External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h, External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp
Dispatcher wasn't ever getting cleaned up.
Also ensures sharing it with the CompileService otherwise it crashes on use.
=> Fixes memory leak in CPU backends 

External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/gcc-target-tests-64/Disabled_Tests, unittests/gcc-target-tests-64/Known_Failures
This goes through the failing GCC unit tests and fixes them.
The remaining tests are ones that either don't work on host x86 systems already, requires AVX, or relies on SIGPROF.
They are now documented entirely why they fail and the rest are fixed.
Fixes #713
=> Fixes GCC tests

Source/Tests/ELFLoader.cpp
We can't rely on `getenv("HOME")` always working.
Have the AOTIR code use the helper method for getting the data directory instead.
=> Removes getenv usage for aotir

CMakeLists.txt
Useful for seeing stack scoping problems that can crop up
=> Adds use-after-scope to the ASAN options

External/FEXCore/Scripts/config_generator.py, External/FEXCore/Source/Interface/Config/Config.cpp
Introduces three new environment variables that need to live outside of the scope
of the regular argument loader path.
This will allow external applications to adjust FEX parameters in interesting ways.
FEX_APP_CONFIG: Allows you to override where Config.json lives
FEX_APP_CONFIG_LOCATION: Allows you to provide an entire folder of app profiles
FEX_APP_DATA_LOCATION: Allows you to override where the data gets stored and loaded from
Fixes #572
=> Allows overriding FEX folder locations with environment variables

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
The segment prefix only overrides one side of the string instruction.
Passing in the flags was causing the instruction to have the segment override on both sides of the copy.
So something like `movsb es:[rdi], fs:[rsi]` was being interpreted as `movsb fs:[rdi], fs:[rsi]`
Same for all the string ops which is now fixed.
We can't unit test these currently since we can't set host segment register for confirmed host behaviour.
Fixes #845
=> Fixes segment register override on string instructions. 

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/CMakeLists.txt, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/Core/CoreState.h, External/FEXCore/include/FEXCore/Debug/X86Tables.h, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/Utils/ELFLoader.h, External/FEXCore/include/FEXCore/Utils/ELFSymbolDatabase.h, External/FEXCore/include/FEXCore/Utils/LogManager.h, Source/Tests/CMakeLists.txt
Set our default visibility to hidden. There is no need to have anything default visibility.
Additionally on release builds strip unused sections and symbols.
This shaves the binary down to 2MB on x86-64 host
1.9MB on an ARMv8.2 host
Fixes #934
=> Default hidden visibility and strip symbols

External/FEXCore/Source/Interface/Config/Config.json, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, Source/Tools/FEXConfig/Main.cpp
This moves vector ops down the GPR atomic backpatch path.
Next step after this is to add SIGBUS based handlers for these rather than backpatching.
Needs more work to treat aligned versus unaligned vector loadstores differently
=>  First step in paranoid TSO mode

Source/Tests/LinuxSyscalls/FileManagement.cpp, Source/Tests/LinuxSyscalls/FileManagement.h
This is required for the AppImage loader to find the correct binary. AppImages still don't work with this fix, though.
=> Emulated Files: Don't precalculate /proc/pid path, it changes after fork

CMakeLists.txt
Clang 12 fixes the bug with big.little configurations so we
can keep using mcpu=native past this point
=> Use mcpu=native with Clang 12

Source/Tools/FEXConfig/CMakeLists.txt
Some distros include generated cmake files instead of the two cmake files from the source.
Distros that use the generated cmake files only have SDL import properties, so we are required
to use those.
=> Use cmake SDL2 target properties

External/FEXCore/Source/Interface/Config/Config.cpp
Clang 12 picks up that this was missing
=> Declare missing template specialization for GetListIfExists

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LookupCache.cpp, External/FEXCore/Source/Interface/Core/X86HelperGen.cpp, External/FEXCore/Source/Utils/Allocator.cpp, External/FEXCore/Source/Utils/ELFSymbolDatabase.cpp, External/FEXCore/include/FEXCore/Utils/Allocator.h, Source/Tests/ELFCodeLoader.h, Source/Tests/FEXLoader.cpp, Source/Tests/HarnessHelpers.h, Source/Tests/IRLoader.cpp, Source/Tests/IRLoader/Loader.h, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Memory.cpp, Source/Tests/TestHarnessRunner.cpp
This removes all usage of naked mman usage for mmap and munmap.
The only behaviour change is that the X86Dispatcher now uses its own allocator rather than allowing xbyak to allocate its own memory regions.
This is a precursor change required before we can implement our own global memory allocator.
=> Naked mman usage removal

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
There were a few missed hard-baked constants, now it should all be rip-relative
=> IR: Fix RIP relocation edge-cases

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/LongDivideRemovalPass.cpp
If the long divides don't have anything in the upper bits then they can be optimized away.
Teeworlds, SuperTuxKart, and RRootage were between 50%-55% getting removed
=> Adds Long Divide removal pass

Source/Tools/FEXConfig/CMakeLists.txt
Should fix Arch and Ubuntu 20.04 together
=> Only use SDL2 import target if it exists

CMakeLists.txt, Scripts/aarch64_fit_native.py
Parallels claims that the CPU is of implementor 0x41 and part number 0.
Easy enough to work around before real numbers get exposed
=> Work around M1 Parallels hypervisor not showing CPU type

Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp
The flags calculation is fairly intensive and we were doing it for every core.
Do it once then duplicate it per core instead
Improves generation time quite significantly. A couple of milliseconds converted to half a millisecond
Slight improvement to startup time
=> Optimizes CPUID generation a bit

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IREmitter.cpp, External/FEXCore/Source/Interface/IR/IRParser.cpp, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/IREmitter.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
Relies on #987 to be merged first
Linked list against invalid node and memory layout optimizations.
This improves the lower bound speed of optimizations passes by generating more optimal code for ARM hosts.
=> Memory layout optimizations

CMakeLists.txt
xxhash doesn't yet have a version of the library with pkg-config giving
a version.
Debian has backported a change for this but Arch hasn't.
https://github.com/Cyan4973/xxHash/issues/524
=> Removes xxhash version check

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h, Source/Tests/FEXLoader.cpp
This updates the file format and the in memory structures so we can mmap the IRData and RAData from the file, instead of having to read it. This also introduces a sorted array for binary searching the file, which can also be mmap'd.
This makes it possible to load AOTIR files very quickly, and in fairly constant time. It effectivelly can pull a few fragments from a huge (6GB+ tested) aotir file without taking 2 seconds to load.
=> AOTIR: Switch over to mmap-based loading

Source/Tests/CMakeLists.txt
AppImage files stick additional data in the ABI Version and PAD areas that it was getting blocked on.
=> Updates binfmt_misc files to support AppImage

Source/Tests/LinuxSyscalls/FileManagement.cpp, Source/Tests/LinuxSyscalls/FileManagement.h
AppImage uses this to inspect its own executable to ensure it is an AppImage file.
=> Handle more cases of an application pinging self

External/FEXCore/Source/Utils/Threads.cpp
Overriding glibc's mmap and munmap functions don't encapsulate that functions they use
for allocating stack data so it was falling down the system mmap/munmap path.
This was causing host side stacks to end up in the 32-bit VA space in 32-bit applications.
=> Fixes host thread stacks ending up in lower 32-bit VA

Source/Tests/LinuxSyscalls/FileManagement.cpp, Source/Tests/LinuxSyscalls/FileManagement.h
This fixes an issue where rootfs has symlinks to other things in the rootfs so we need to track it through.
Relies on #1009 to be merged first.
Fixes any application that relies on libblas, mpv for example.
=> Handles symlinks in rootfs in openat 

Source/Tests/LinuxSyscalls/x32/Signals.cpp, Source/Tests/LinuxSyscalls/x64/Signals.cpp, unittests/gvisor-tests/Known_Failures
Check for invalid sigsetsize
Since we are using SignalDelegator we don't use errno, so just return Result and check for Result == 0
=> Sigaction fixes

Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/FD.cpp, Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x64/FD.cpp
FD flag remapping was broken. It would remap one flag on to another and then the next check would remap it back.
Instead keep a mask of the flags to be remapped then remap them all at the end.
Also goes through the ops and fixes a few cases where it was remapping wrong flags.
=> Handle FD flag remapping correctly

Source/Tests/LinuxSyscalls/Syscalls/FD.cpp, unittests/gvisor-tests/Known_Failures
posix variant still doesn't quite match the actual syscall implementation
=> Fix fadvise64

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/include/FEXCore/Core/Context.h, Source/Tests/FEXLoader.cpp
Makes it possible to write out the aotir file format without keeping everything in memory, which makes it possible to use --aotirgenerate on arm devices directly.
- Modifies aotir file format so that the index comes last in the file
- Writes out each block as it gets generated, not all at the end
- Special cases AOTIRGenerate to not keep IR, RA or CodeData around
=> AOTIR: .aotir files are now streamed out

Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/FD.cpp, Source/Tests/LinuxSyscalls/Syscalls/FS.cpp, Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.h, Source/Tests/LinuxSyscalls/x64/Syscalls.h, unittests/gvisor-tests/Known_Failures
This was causing issues with syscalls returning errors.
Remove it and move on
=> Removes syscall forward errno preprocessor implementation

Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x64/FD.cpp
glibc implementation makes a copy of the timeout and the kernel is expected to update it
Can't use the glibc implementation because of this.
=> ppoll fixes

.gitmodules, CMakeLists.txt, External/FEXCore/Source/CMakeLists.txt
Begins the process of addressing issue #146.
This is separated off, so that others can make use of fmt immediately for other convenient purposes (general localized non-sucky string formatting), while other things are being reworked.
=> Externals: Add fmtlib as an external

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/include/FEXCore/Core/Context.h, Source/Tests/FEXLoader.cpp
Allows --aotirgenerate to use all of the host's threads for AOTGen
- Fixes concurrent stream out of aotir files. data is flushed ever 10K blocks, with minimal locking
- Changes the aot context api to be per thread, not per context
- Updates the frontend to create as many threads as the host has, and to distribute the work across all of them
=> Multi threaded AOTGen

Source/Tests/LinuxSyscalls/Syscalls/FD.cpp
Rise of the Tomb Raider launcher uses this without checking host kernel version.
Might be part of their crash handler.
=> Implements pidfd_getfd syscall

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, Source/Tests/LinuxSyscalls/CMakeLists.txt, Source/Tests/LinuxSyscalls/EmulatedFiles/EmulatedFiles.cpp, Source/Tests/LinuxSyscalls/FileManagement.cpp, Source/Tests/LinuxSyscalls/FileManagement.h, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/FD.cpp, Source/Tests/LinuxSyscalls/Syscalls/IOUring.cpp, Source/Tests/LinuxSyscalls/Syscalls/Info.cpp, Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp, Source/Tests/LinuxSyscalls/Syscalls/Stubs.cpp, Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp, Source/Tests/LinuxSyscalls/Syscalls/Thread.h, Source/Tests/LinuxSyscalls/x32/EPoll.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/EPoll.cpp, Source/Tests/LinuxSyscalls/x64/Memory.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Thread.cpp
Implements significantly more syscalls which allows us to expose a guest kernel version of up to kernel 5.12.
FEX now calculates a guest kernel version on start depending on what the host is.
Our range of kernels returned is now [5.0, 5.12] inclusive range.
We are now only missing 12 syscalls in total. Although there are definitely still edge cases in these to be resolved.
Relies on #1039 getting merged first.
=> Implements more syscalls for supporting a higher guest kernel version

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/include/FEXCore/Debug/X86Tables.h
Shortens the length of code necessary for testing the type of a decoded operand.
Also relocates the type field out of all the union types to have it in a central location.
=> DecodedOperand: Add helper functions for type testing 

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h
Now possible in a less messy way, since the type is now centralized in one location.
Makes it strongly typed and prevents any potential accidental implicit assignments to Type instead of something intended for the Data members.
=> DecodedOperand: Convert operand type into an enum class

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/LookupCache.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/HLE/Linux/ThreadManagement.h, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h, External/FEXCore/include/FEXCore/IR/RegisterAllocationData.h
A minor change that adds missing const specifiers to getters that don't modify the internal class state. Makes the API a little more explicit (and in some locations, a little more consistent) about non-modifying operations.
=> General: Add missing const specifiers where applicable

External/FEXCore/include/FEXCore/Config/Config.h
Noticed when adding amending missing const qualifiers on interfaces. We can make use of std::move here to avoid potential allocation churn a little.
While we're at it, we can implement EraseSet in terms of, well, Erase() and Set().
=> Config: Move strings where applicable 

External/FEXCore/include/FEXCore/IR/IR.h
Same behavior, but allows both operator== and operator!= to be automatically generated with a single declaration.
=> IR: Make use of defaulted operator==

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/include/FEXCore/Config/Config.h, Source/Common/Config.cpp, Source/Common/Config.h
We can make use of heterogenous lookup to avoid constructing std::string instances on lookups.
While we're in the area, we can tidy up some of the interface functions, to pass by reference where applicable.
=> Config: Avoid a few minor string copies where trivially possible

.gitmodules, Source/Tests/LinuxSyscalls/CMakeLists.txt
It's highly likely that the host system won't have these headers installed.
Carry them in an external repository to ensure they are available.
Fixes #1047
=> Adds drm headers to an external repository

External/FEXCore/Source/Interface/IR/IRParser.cpp
Same behavior, but allows the arrays to be constexpr (and use a little bit less space; 16 bytes vs 32 bytes per element*).
\* on clang, GCC, and MSVC (MSVC isn't supported, but included for completeness sake)
While in the area, I noticed some minor other locations that could have some cleanup/improvements (which I've separated into their own commits).
=> IRParser: Convert array of std::string over to array of std::string_view 

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Utils/LogManager.cpp, External/FEXCore/include/FEXCore/Utils/LogManager.h
Addresses #146 a little more by providing an interface to perform fmt-compatible logging, allowing migration over to it to begin.
No more, will people on the project be tormented by classic printf features like:
- Accidentally passing in a non-trivial type
- Goofy looking PRI macros
- Not being able to add support for custom types
- Mixing up signed/unsigned printf formatting specifiers accidentally
fmt-capable versions of the logging functions are named the same as the existing functions, just with a `Fmt` or `_FMT` suffix (depending on whether or not it's a function being used or a macro, respectively).
=> LogManager: Add fmt-capable logging functions

External/FEXCore/include/FEXCore/Core/CodeLoader.h, Source/Tests/ELFCodeLoader.h, Source/Tests/ELFCodeLoader2.h, Source/Tests/HarnessHelpers.h, Source/Tests/IRLoader.cpp
Adds two aliases to turn the signatures of MapMemory from long bois to short bois.
While we're at it, we can also give CodeLoader a virtual destructor to ensure destruction behavior is always consistent, no matter the scenario they're used in.
=> CodeLoader: Add type aliases for mapper and unmapper functions

External/FEXCore/Source/Interface/Core/GdbServer.cpp, External/FEXCore/Source/Interface/Core/GdbServer.h
Simplifies a bunch of string manipulation code.
Much nicer to grok than stream formatting in many cases.
=> GdbServer: Migrate logging/string handling to fmt where applicable

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
Makes the enumeration strongly typed, preventing implicit conversions, minimizing the potential chances of an invalid value being used by accident.
Also has the benefit of allowing the enum to be forward declared, if ever necessary.
=> InternalThreadState: Make SignalEvent an enum class

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp, External/FEXCore/Source/Interface/Core/GdbServer.cpp, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/Core/CPUBackend.h, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/Core/CoreState.h, External/FEXCore/include/FEXCore/Core/SignalDelegator.h, External/FEXCore/include/FEXCore/Core/UContext.h, External/FEXCore/include/FEXCore/Debug/X86Tables.h, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/Utils/Allocator.h, External/FEXCore/include/FEXCore/Utils/CompilerDefs.h, External/FEXCore/include/FEXCore/Utils/ELFSymbolDatabase.h, External/FEXCore/include/FEXCore/Utils/LogManager.h, Source/Tests/HarnessHelpers.h, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/x32/Ioctl/drm.h, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/FD.cpp
Puts a layer of separation around compiler specifics (and also makes them nicer to write).
=> Utils: Add CompilerDefs.h for compiler-specifics

External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
The Run() function was quite large which makes it easy to get lost reading it, so this can be broken up into constituent functions that are then called in the Run() function, making it easy to see how the pass functions at a high level.
This is purely code movement. No functional changes are made.
This change was mainly made because I was seeing if I could add some basic additions to constant propagation, but wanted to move things into their own relevant chunks so that there were fewer moving parts to worry about.
=> ConstProp: Separate out constituent chunks of const prop

External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Utils/LogManager.cpp, External/FEXCore/include/FEXCore/Utils/CompilerDefs.h, External/FEXCore/include/FEXCore/Utils/LogManager.h
We can also make use of the `<bit>` header to remove some compiler builtins, since many of them were standardized.
=> General: Place more compiler specifics into CompilerDefs.h

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/include/FEXCore/Utils/BitUtils.h, Source/Tests/HarnessHelpers.h
Places a layer of separation around the remaining compiler builtins.
=> Utils: Add header for bit-related utilities

External/FEXCore/Source/Interface/IR/IRDumper.cpp, External/FEXCore/Source/Interface/IR/IRParser.cpp
While we're in the same area, we can make the dumper lookup tables constexpr.
=> IRParser: Make use of fmt where applicable

External/FEXCore/include/FEXCore/Core/SignalDelegator.h, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.h
A few minor changes that didn't deserve their own PRs.
Primarily some cleanup, but does swap out some deprecated library functions with their relevant counterparts.
=> SignalDelegator: Minor changes

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/JITCore.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/include/FEXCore/Core/Context.h, Source/CommonCore/HostFactory.cpp, Source/CommonCore/HostFactory.h
Mainly done to communicate the intended ownership responsibilities directly within the interface itself and make it harder to unintentionally leak memory.
=> Core: return unique_ptr by default for cores

Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
`std::unexpected` was deprecated in C++11 and removed from the standard in C++17. The default unexpected_handler calls `std::terminate`, so this is identical behavior.
=> Syscalls/Thread: Replace std::unexpected with std::terminate

Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/FD.cpp, Source/Tests/LinuxSyscalls/Syscalls/IOUring.cpp, Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp, Source/Tests/LinuxSyscalls/x32/EPoll.cpp, Source/Tests/LinuxSyscalls/x64/EPoll.cpp, Source/Tests/LinuxSyscalls/x64/Memory.cpp
Shortens up the version testing code in a few places to make for quicker reading.
=> Syscalls: Add helper for version testing

Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp
These were accidentally omitted from the call.
=> Syscalls/Signals: Add missing arguments to pidfd_send_signal syscall

External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
`release()` relinquishes control of the allocated memory, but doesn't deallocate it. We need `reset()` for this.
=> RegisterAllocationPass: Prevent leaks in BucketList

External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadCodeElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadStoreElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/LongDivideRemovalPass.cpp, External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RedundantFlagCalculationElimination.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Interface/IR/Passes/StaticRegisterAllocationPass.cpp, External/FEXCore/Source/Interface/IR/Passes/SyscallOptimization.cpp, External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
Same behavior, but makes the ownership intentions explicit in the interface.
=> Passes: Return by unique_ptr where applicable

External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
`<iostream>` injects a static constructor in translation units that include it, even if its facilities aren't used. We can make use of `<sstream>` to avoid needing to execute those on startup.
While we're in the area, we can pass some logging strings as arguments to a format string instead of directly passing the output as a format string, so that the strings avoid being mangled (especially given we have things like `%ssa` in the strings which can unintentionally be interpreted as a null terminated string specifier).
=> Passes: Replace <iostream> header with narrower equivalents

External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/LookupCache.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Utils/ELFSymbolDatabase.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h, Source/Common/Config.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp
Still have a few of the offsetof on a non standard layout object warning
=> Remove most warnings in FEX again

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp
When running the cpuid application (http://www.etallen.com/cpuid.html) I noticed
that we were returning some garbage data here.
After initially implementing support for leaf functions, it still didn't resolve the issue.
So I had to fix those in the x86-64 JIT.
I then went through and solved more issues with the function results.
- We now return a more sane CPU family that is near the feature set we support
- APICID now understands how to fill out the data correctly depending on emulated core counts
- Disabled some CPU features that we don't actually support
- Found two more cache functions that we weren't populating
- Filled with generic data cache size data
- Only thing that matters is that we ensure that cacheline size is reported as 64bytes
- L1D: 32KB, L1I: 32KB, L2: 512KB, L3: 8MB …
=> CPUID: Improvements to have a more sane configuration 

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Utils/Threads.cpp, External/FEXCore/include/FEXCore/Utils/Threads.h
After FEX has forked, there aren't any other threads in the process but their stacks remain.
We need to have some book keeping in place to have the stack ranges available to clean up
after fork.
We now keep both live stacks and dead stacks in a dequeue and on fork we will walk both to
clean up all stack objects that aren't our current thread.
=> Core: After fork make sure to cleanup stacks

CMakeLists.txt, Source/Common/CMakeLists.txt, Source/Common/FileFormatCheck.cpp, Source/Common/FileFormatCheck.h, Source/Common/RootFSSetup.cpp, Source/Common/RootFSSetup.h, Source/Tests/FEXBash.cpp, Source/Tests/FEXLoader.cpp, Source/Tools/CMakeLists.txt, Source/Tools/FEXConfig/Main.cpp, Source/Tools/FEXMountDaemon/CMakeLists.txt, Source/Tools/FEXMountDaemon/Main.cpp
This adds support to FEXLoader and FEXConfig to automatically mount and manage squashfs rootfs files.
Startup time is impacted around 200-400ms per execve. Which isn't a terrible tradeoff from needing a loose filesystem sitting on the drive.
Additional stats
A loose rootfs consumes 616MB
The loose rootfs getting compressed to tar.gz is 329MB
The loose rootfs getting compressed to a squashfs with zstd is 299MB
=> Support Squashfs based rootfs files

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
This is repeated in quite a few spots throughout the opcode dispatcher, so we can place it in a utility function and use it instead.
=> Context: Move GPR size retrieval to its own function

External/FEXCore/Source/Interface/Core/Frontend.cpp
Allows clang to emit better code, since it doesn't need to push all the values onto the stack for every invocation.
<details>
<summary>Previous codegen</summary>
```asm
MapModRMToReg(unsigned char, unsigned char, bool, bool, bool, bool, unsigned char):               # @MapModRMToReg(unsigned char, unsigned char, bool, bool, bool, bool, unsigned char)
sub     rsp, 392
mov     r10b, byte ptr [rsp + 400]
movups  xmm0, xmmword ptr [rip + .L__const.MapModRMToReg(unsigned char, unsigned char, bool, bool, bool, bool, unsigned char).GPRIndexes+112]
movaps  xmmword ptr [rsp + 368], xmm0
movups  xmm0, xmmword ptr [rip + .L__const.MapModRMToReg(unsigned char, unsigned char, bool, bool, bool, bool, unsigned char).GPRIndexes+96]
movaps  xmmword ptr [rsp + 352], xmm0
movups  xmm0, xmmword ptr [rip + …
```
=> Frontend: Make lookup tables static in MapModRMToReg

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
Removes qualifiers that don't do anything to interfaces
Top-level const on functions that return by value can inhibit move semantics (thankfully we didn't have this occur anywhere that would have mattered).
=> General: Resolve -Wignored-qualifiers warnings

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Common/SoftFloat.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/include/FEXCore/Utils/BitUtils.h
Ensures that qualifiers are preserved on references and pointers to prevent undefined behavior.
=> General: Resolve -Wcast-qual warnings

Source/Tests/FEXBash.cpp
FEXBash wasn't setting up a squashfs on its end. This meant that it couldn't find any
x86-64 libraries and would fail
=> Fixes FEXBash with squashfs

unittests/POSIX/Disabled_Tests, unittests/POSIX/Known_Failures
Test sleeps for 1 second and expects to come back within 10ms of the time.
When the CPU is doing other things then it can end up missing that timeframe. Thus flake.
Just disable it
=> Disable flaky posix test

Source/Tests/LinuxSyscalls/Syscalls/FS.cpp, Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x32/Info.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/FD.cpp
This game had some unexpected crashes.
It uses the same engine as Neverwinter nights, so we should have been able to run it.
This older version of the engine managed to uncover a couple of bugs for us.
This fixes the game so it gets ingame now. There is some audio corruption periodically still, probably vector instruction related.
Fixes #894
=> Fix Star Wars Knights of the Old Republic 2

Source/Tests/ELFCodeLoader.h, Source/Tests/ELFCodeLoader2.h, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp
Instead of forcing a fixed offset for the stack. Allow it to get placed automatically.
64-bit was already doing this; Now we can also do it in 32-bit.
This is possible because the mapper that is mapping the code will always map in the 32-bit space
for a 32-bit guest.
Fixes #317
=> Fixes fixed stack offset for 32-bit applications

Source/Tests/LinuxSyscalls/x32/FS.cpp
A 32-bit game was using this syscall and now it gets farther in game
=> Implements 32-bit truncate64 syscall

Source/Tests/FEXLoader.cpp
Set these threads to minimum priority to not complete starve the system if there are other tasks running.
Fixes #1075
=> Lower priority of AOT compilation threads.

Source/Tests/LinuxSyscalls/x32/Memory.cpp
The allocator functions don't return -1 on error, instead return the actual error.
This was setup to match the syscall behaviour rather than the glibc/errno behaviour
=> Fixes a couple of 32-bit checks

Source/Tests/LinuxSyscalls/x32/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Types.h
This is a early version of the syscall that only returns the lower 32 signals.
Easy enough to support
=> Implements 32-bit sigpending

Source/Tests/LinuxSyscalls/x32/FD.cpp
Implements three basic hooks for the chown32 family of syscalls.
=> x32: Implement chown32/fchown32/lchown32

Source/Tests/LinuxSyscalls/x32/Thread.cpp
Implements two other straightforward syscalls for the 32-bit side of things.
=> x32/Thread: Implement getgroups32/setgroups32

Source/Tests/LinuxSyscalls/x32/Time.cpp
In some cases, we may be dereferencing invalid addresses that would be handled by the kernel. So we can rearrange our code a little bit to account for this and avoid potential dereferencing.
Most applications shouldn't be misbehaving, but given we're dealing with arbitrary user code, we can't assume everything will be well-behaved.
=> x32/Time: Fix a few edge cases in time related syscalls

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/Source/Interface/Core/GdbServer.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/Core/SignalDelegator.h, External/FEXCore/include/FEXCore/Core/UContext.h, Source/CommonCore/HostFactory.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.h, Source/Tests/TestHarnessRunner.cpp, unittests/POSIX/Known_Failures, unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
I saw a red herring that I thought the high cpu usage in steamwebhelper could come from signal handlers.
This turned out to not be the case, but now I've got this implemented.
Installs the few signal handlers that we need upfront but for everything that isn't a mandatory signal
we instead now wait until the guest also installs that signal handler.
This fixes #1107
=> Implements support for deferred signal handler installation 

Source/Tests/LinuxSyscalls/x32/Socket.cpp
Since the vector was being initialized with braces, this caused the arrays to only ever have one element within it instead of the size of the array.
i.e. 
```cpp
std::vector<thing> stuff{length};
```
would create a single element vector containing the value in `length`. What we want is:
```cpp
std::vector<thing> stuff(length);
```
While we're at it, we can also construct a vector in place with the necessary size.
=> x32/Socket: Amend std::vector initialization bug in sendmmsg

Source/Tests/FEXLoader.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.h, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.h, Source/Tests/TestHarnessRunner.cpp
Makes the ownership requirements explicit in the interface.
Also makes it harder to unintentionally/accidentally leak memory.
=> FEXLoader: Make use of unique_ptr for syscall handlers

Source/Tests/LinuxSyscalls/x32/EPoll.cpp
Doesn't change behaviour, just makes sure we know it is a compat_ptr
=> Wrap 32-bit epoll_ctl argument in compat_ptr

External/FEXCore/Source/Interface/Config/Config.cpp
Otherwise it will claim that the AppConfig was saved and won't actually be
=> FEXConfig: Have it create AppConfig folder on save

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/Syscalls.cpp
Don't print how many instructions are installed in the tables.
This isn't useful anymore
Not installing signal 32 and 33 are something we don't support right now. Stop complaining in that case.
Stop printing when a thread is starting up and shutting down. If you want to see this then gdb shows it well.
Don't print clone flags unless we are hitting a case where we are printing another log message.
=> Remove logs that are just noise at this point

Source/Tests/LinuxSyscalls/x32/Socket.cpp
This wasn't aligning like the other recvmsg and sendmsg variants
=> x32: Fixes sendmmsg cmsg alignment

Source/Tests/LinuxSyscalls/x32/FD.cpp
This was overwriting the cmd argument and then being checked in the switch statement
after the call.
Since it was overwritten, it wasn't falling down the correct path, returning a flock_32 instead of a flock64_32
=> x32: Fixes fcntl OP_GETLK64_32

Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
In a newer version of the kernel there was a feature to disallow cpuid.
We can emulate this by saying it is always enabled and disallow the ability to disable it.
=> syscalls: Disallow disabling CPUID from arch_prctl

Source/Tests/ELFCodeLoader2.h
gzip ships a PT_LOAD program section without a file size and only a memory size.
In the case of a zero file size PT_LOAD then return success immediately in this section loader.
This fixes Steam using gzip to package up crash logs
=> Fixes PT_LOAD with zero file size

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
Same behavior, but allows clang to elide pushing all of these values on and off the stack, particularly given these are called quite frequently throughout the opcode dispatcher.
A reduced example like so:
<details>
<summary>Code</summary>
```cpp
#include <array>
#include <cstdint>
constexpr uint32_t FLAG_SIZE_DST_OFF = 19;
constexpr uint32_t SIZE_MASK         = 0b111;
inline uint32_t GetSizeDstFlags(uint32_t Flags) { return (Flags >> FLAG_SIZE_DST_OFF) & SIZE_MASK; }
struct DecodedInst {
uint64_t PC;
uint16_t OP;
uint32_t Flags;
uint8_t ModRM;
uint8_t SIB;
uint8_t InstSize;
uint8_t LastEscapePrefix;
};
uint8_t GetDstSize(DecodedInst* Op) {
constexpr std::array<uint8_t, 8> Sizes = {
0, // Invalid DEF
1,
2,
4,
8,
16,
32,
0, // Invalid DEF
};
uint32_t DstSizeFlag = …
```
=> OpcodeDispatcher: Mark lookup tables as static in Get{Src,Dst}Size

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp
This makes it a little more straightforward to see what these return values mean without needing to look at the implementation, since a tuple's declaration is kind of opaque.
These tuples were also getting a little bit large enough to make the signature a little lengthy. Since the types are still aggregates, it's still possible to use structured bindings with them.
=> Context: Place return value from GenerateIR into a struct

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/GdbServer.cpp, External/FEXCore/include/FEXCore/Core/Context.h
Places the definition in one place so it doesn't need to be written several times.
=> Context: Add alias for exit handler

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp
Given these are called in a loop repeatedly, where we know we'll always have a set function to call, std::function adds a little bit of
overhead.
e.g. for the uint32_t case:
<details>
<summary>Previous</summary>
```asm
sub     sp, sp, #32
stp     x29, x30, [sp, #16]
add     x29, sp, #16
ldr     x8, [x0, #16]
stur    w1, [x29, #-4]
str     w2, [sp, #8]
cbz     x8, .LBB2_2
ldr     x8, [x0, #24]
sub     x1, x29, #4
add     x2, sp, #8
blr     x8
ldp     x29, x30, [sp, #16]
add     sp, sp, #32
ret
.LBB2_2:
bl      std::__throw_bad_function_call()
```
</details>
<details>
<summary>After</summary>
```asm
mov     x3, x0
mov     w0, w1
mov     w1, w2
br      x3
```
</details>
=> Arm64: Use regular function pointers with CAS handling functions

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, unittests/ASM/Disabled_Tests_ARMv8.0, unittests/ASM/Secondary/09_XX_01_10.asm, unittests/ASM/Secondary/09_XX_01_11.asm, unittests/ASM/Secondary/09_XX_01_12.asm, unittests/ASM/Secondary/09_XX_01_13.asm
There were two bugs in here.
The first bug here is with with the CMPXCHG emulation.
1) If the *Expected* value did *NOT* match what was in memory
2) *AND* The *Desired* value matched the memory value
3) The CAS would incorrectly return success for this CMPXCHG
4) Thus setting ZF incorrectly
The second bug comes from atomic memory operations (Add, CLR, EOR, SET, SWAP).
This operation is a Load + &lt;Op&gt; + CAS
1) If the memory backing between the Load and CAS changes
2) The CAS would then fail
3) On Atomic memory operations this should then retry to ensure it completes successfully
4) We were not retrying on failure in this case
5) Thus something like `LOCK INC` would have never atomically incremented correctly
6) We can't use our ASM unit tests to test this, since it needs thread …
=> ARM64: Fixes bugs in unaligned atomic signal handlers

External/FEXCore/Source/Interface/Core/CPUID.cpp
These are in place to let applications know that we do our own thermal management
TM was introduced with Pentium M, it would dispatch idle uops to counter thermals.
TM2 was later and is what allows the CPU to dynamically change its multiplier and frequency.
All in an effort to not cook themselves.
Our ARM CPUs also do all this. Claim it as well.
=> CPUID: Update TM and TM2 CPUID bits

Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
We don't need to care about what the guest stacks are doing now
=> Linux: Remove logs about parent or child stack usage

Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.h, Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp, Source/Tests/LinuxSyscalls/Syscalls/Stubs.cpp, unittests/gvisor-tests/Known_Failures
This is a base implementation of signalfd.
Signalfd allows the application to receive siginfo_t information through an FD.
The FD is either provided by the application or created by the kernel depending.
This specifically doesn't pick up *true* synchronous signals. tgkill of the number
should theoretically go through this interface.
This very specifically skips our internal required signals for now.
This means it won't pick up SIGILL, SIGBUS, or SIG63.
This is enough to capture an application that just wants to poll for SIGCHLD.
Anything more complex has the same problems of the guest handling a siginfo_t.
=> Linux: Implements a base implementation of signalfd{4,}

External/FEXCore/Source/Interface/Core/GdbServer.cpp
Previously the opened socket stream would be leaked.
=> GdbStub: Fix memory leak in GdbServerLoop()

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/32Bit_ASM/PrimaryGroup/3_F6_05.asm, unittests/ASM/PrimaryGroup/3_F6_05_2.asm, unittests/ASM/PrimaryGroup/3_F6_05_3.asm, unittests/ASM/PrimaryGroup/3_F6_05_4.asm, unittests/ASM/PrimaryGroup/3_F6_05_5.asm, unittests/ASM/TwoByte/0F_AF_2.asm
We were calculating the high bits incorrectly in a couple variants
=> OpDispatcher: Fixes imul flags calculations

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp, Source/Tests/LinuxSyscalls/Syscalls/Stubs.cpp, unittests/POSIX/Known_Failures
We already support receiving user signals in our signal handlers for this.
Just need to push through syscalls.
This fixes Dead Island Definitive Edition so it runs.
=> Linux: Implements rt_{tg,}sigqueueinfo

.gitmodules, CMakeLists.txt, External/FEXCore/Source/Interface/Core/Core.cpp
Also in the case that you don't have v0.8.0 minimum installed
Doesn't quite fix #1148 but this is necessary in some configurations.
=> Use externals xxhash if not found installed

Source/Tests/FEXLoader.cpp
In the case that there is an immediate configuration failure. Use stderr specifically for outputting.
These errors won't be output typically because silent logging is enabled by default.
In the case of executable missing or rootfs configuration failure, print directly to stderr.
Previously it looked like FEX just exited for no reason.
We had multiple users encounter this and be confused
=> FEXLoader: stderr on immediate failure

External/FEXCore/Source/Utils/Allocator.cpp, Source/Tests/CMakeLists.txt
Currently FEX is replacing glibc symbols at runtime depending on if we captured a 32-bit application or not.
This has us in a weird world where some of our allocations go through jemalloc, some go through glibc.
Instead fix FEX_jemalloc so it correctly replaces glibc symbols and do away with the FEXCore/FEX replacements.
This allows us to have glibc's allocator get replaced and solely work through FEX_jemalloc.
Then when a 32-bit application is running we only replace the VMA allocator for FEX_jemalloc.
This greatly simplifies how the allocator works.
Additionally this is the first step towards supporting static-pie with fex.
We can't yet enable it because we hit bugs inside of glibc with relocations. Some documentation is at #1114
=> Fix jemalloc malloc replace

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
This cuts start up time from 8.962ms to 3.949ms and lets us use less physical memory.
We pay a small amortized cost from the faulting to populate pages which will be fairly low
=> Switch some memory allocations over to mmap

External/FEXCore/Source/Interface/Core/CPUID.h, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/X86DebugInfo.cpp, External/FEXCore/Source/Interface/Core/X86HelperGen.cpp, External/FEXCore/Source/Interface/Core/X86Tables.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp, Source/Tests/LinuxSyscalls/Syscalls.cpp
Main thing here is the partial revert of the register allocator code.
This was causing Steam to in to the VMA region count cap of 65k.
Some other minor changes:
1) Frontend no longer accidentally allocates in 32-bit space
2) 64BitAllocator adds a backwards scan to fill VMA holes, reducing the number of holes we have
3) BRKHandler/x86HelperGen Doesn't rely on the 64bit allocator hack to allow through fixed 32-bit offsets to system mmap
4) Removes some logs that were just being annoying and don't really provide us information that matters anymore.
=> Allocator fixes

External/FEXCore/Scripts/config_generator.py
Allows users to reference the man page for the json key instead of code diving
=> Update man page to show JSON key for config options

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Config/Config.json
If the thunk config is not a path then search for the filename in $XDG_DATA_DIR/.fex-emu/ThunkConfigs/
for the file.
Just makes it easier to use rather than having full paths
=> Adds a convenience of named thunk configs

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp
MUL is handled in a different function, so this isn't needed there anymore.
This was causing a problem where if you force enabled LOCK on all capable ops it was causing a crash.
Issue #1164 is set to track getting unit tests for these.
=> Fixes flag setting for 8bit and 16bit LOCK ALU ops

External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/PhiValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/ValueDominanceValidation.cpp
Removes some logically dead variables, and narrows the construction scope for the error printing stringstream so that we only construct it when we have errors to indicate
=> Validation Passes: Remove unused variables

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/IR/IREmitter.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
Prior to the introduction of fmt, there wasn't a nice and easy way to format std::string_view, but now that we have it in place, we can modify relevant log calls to make use of it and get rid of the need to construct a string around the view, tidying up callsites a little.
While we're in the same area, we can make the rest of the modified file use fmt where appropriate.
=> General: Remove redundant string constructions in log calls related to IR op name retrieval

External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/VectorOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ConversionOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MoveOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/VectorOps.cpp
Brings over the rest of the JIT logs for consistency.
This also fixes some incorrect logging string (e.g. where the error string for AtomicSwap, would indicate an invalid size for AtomicAdd, etc)
=> Jits: Migrate logs over to fmt where applicable

External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
+16 doesn't matter anymore. This can cause stack corruption
=> Arm64: Fixes fill and spill slot offset calculation

CMakeLists.txt, Source/Tests/CMakeLists.txt, Source/Tools/FEXMountDaemon/CMakeLists.txt
This option does cmake checks to determine if your system can handle static-pie.
With upstream projects static-pie only works if you use the binutils linker.
Using lld doesn't currently work because it defines __rela_iplt_{start,end} symbols.
Our cmake file will now compile a test application and check for these symbols.
Either the symbols will not exist at all or they will exist but be a null address
Once your system passes the checks then it will allow you to enable static-pie
Fixes #1114
=> Adds cmake option ENABLE_STATIC_PIE

External/FEXCore/Source/Utils/Allocator/FlexBitSet.h
These parameters are used as indexes into the tracked memory, so sizing the index variable relative to the type being stored is kind of sketchy.
e.g. If the tracked types were uint8_t for example, we'd still want the indexing parameters to be regularly sized so that we aren't implicitly truncating values all the time when passing values to a uint8_t parameter (and while all usages are currently using uint64_t as type T, we may as well address this).
While we're at it, we can make both Get() and operator[] const member functions, since they don't directly modify any underlying data, they only read it.
=> FlexBitSet: Use non-template type parameter for index parameters

External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp
This is small enough that it can be converted over to a std::array so the heap use isn't necessary
=> 64BitAllocator: Convert std::vector table into std::array

External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
RegisterNode isn't a POD so we can't memset it.
This was overwriting some unique_ptrs which were memory leaking and causing crashes in other PRs
This pretty much entirely reverts the RAPass optimizations now.
=> Fixes bug in RAPass

CMakeLists.txt, External/FEXCore/Source/Utils/Allocator.cpp, Source/Tests/CMakeLists.txt, Source/Tests/FEXLoader.cpp
While not recommended. It is necessary to allow disabling jemalloc if you want to run asan or tsan
=> Adds an option to disable jemalloc from cmake 

Data/AppConfig/steamwebhelper.json, External/FEXCore/Source/Interface/Config/Config.json, Source/Tests/FEXLoader.cpp
For misbehaving applications before we can fully diagnose, allow
a config that hangs a process on load.
=> Adds an option to stall processes on launch

External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp
There is an assumption in the RCLSE pass that if a StoreContext + LoadContext pair of the same size
with a vector register that it is safe to remove the LoadContext.
This isn't quite safe since it can't entirely see through the IR to determine if the store op
had already zext the upper bits of the register.
This was causing 8byte loadcontext operations to "load" with garbage data in the upper
bits when it was expecting a zext.
Which granted it is likely a bug that not all vector ops zero their upper bits but that's a battle for a different day.
Additionally:
- Removes a couple dead optimizations in the GPR path that was never hit.
- Cleans up how access types are checked
- Uses ReplaceAllUsesWithRange to reinforce that this is purely a per block optimization still
Fixes #881 and also VC1 …
=> RCLSE: Fixes an assumption in RCLSE 

External/FEXCore/Source/Interface/Core/Core.cpp
On fork this thread will be gone. Make sure to delete the shared_ptr.
=> Cleanup compile service on fork

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.h, Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp
When a guest tries to use the setxid syscalls, the guest glibc has
a mechanism in place to ensure that the process wide setxid is handled.
The mechanism is fairly complex but it uses signal 33 and sends the signal to all
active threads to ensure every thread sets the correct state here.
We need to intercept this and pass the context information correctly to the guest instead.
Otherwise FEX just crashes when the glibc HOST handler tries handling the guest applications signal.
Fixes the game SOMA https://store.steampowered.com/app/282140/SOMA/
Weirdly this game uses some Autodesk SDK `FBX SDK 2012` which part of its thread initialization code tries to do a `setuid(0)`
=>  Linux: Implements support for signals 32 and 33 

Source/Common/RootFSSetup.cpp, Source/Common/RootFSSetup.h, Source/Tests/FEXLoader.cpp, Source/Tools/FEXMountDaemon/Main.cpp
Instead of watching to ensure our parent process is still alive. Mount the
squashfs once and use a combination of file leases and inotify to
ref count how many processes are using the rootfs.
This makes it so in the common case, the FEXMountDaemon only ever executes once
and runs until all FEX processes stop running.
In the rare edge case there is a race condition where multiple FEXMountDaemon
applications will start, but only one will end up mounting the squashfs.
In this case, one application wins and the one that failed to grab the lease
will wait until the other one completes.
With this change, squashfs should be reasonable to use now.
=> FEXMountDaemon: Make squashfs mounting more robust

CMakeLists.txt, External/FEXCore/Source/Common/Paths.cpp, External/FEXCore/Source/Interface/Config/Config.cpp, Source/Common/RootFSSetup.cpp, Source/Linux/Utils/ELFContainer.cpp, Source/Tests/FEXLoader.cpp, Source/Tools/FEXConfig/Main.cpp
Static-pie can only work with GNU ld instead of lld on AArch64 hosts.
This is a known problem on the llvm side: https://bugs.llvm.org/show_bug.cgi?id=49672
=> AArch64: Workaround static-pie crashing

Source/Tests/LinuxSyscalls/Syscalls/FS.cpp, Source/Tests/LinuxSyscalls/Syscalls/NotImplemented.cpp
Somehow missed this one. Easy enough and matches between architectures.
Used by bubblewrap
=> Linux: Implements pivot_root syscall

Source/Tests/CMakeLists.txt
Arch doesn't have update-binfmts. Fall back to the classic approach
without it.
Fixes #1195
=> Arm64: Reimplements support for binfmt_misc without update-binfmts

CMakeLists.txt, External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Common/Paths.cpp, External/FEXCore/Source/Common/Paths.h, External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Utils/Telemetry.cpp, External/FEXCore/include/FEXCore/Utils/Telemetry.h, Source/Tests/FEXLoader.cpp
This information is only ever going to be offline. Will be useful for multiple reasons.
1) Searching for split lock usage in applications, which can be a programming bug.
a) This isn't visible on AMD systems and on Intel is a fairly new linux feature
2) Having more information about when an application breaks.
3) Useful for some minor profiling for devs looking for statistical data
=> Implements support for offline *only* telemetry

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/IR/IRParser.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Utils/Allocator.cpp, External/FEXCore/Source/Utils/Telemetry.cpp, External/FEXCore/Source/Utils/Threads.cpp, External/FEXCore/include/FEXCore/Config/Config.h, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/Utils/Threads.h, Source/Tests/FEXLoader.cpp, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp, Source/Tests/LinuxSyscalls/Syscalls/Thread.h, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/Thread.cpp, unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
This is very tricky to handle and it has a bunch of rough edges.
One of the major problems that we can't workaround is that if we receive a
clone flag that pthreads can't support with THREAD, then we are required to fall down
the pthreads code path.
This is because threads going down the clone path will break TLS and we don't have
a way to work around it currently.
So this adds a clone path, a clone3 path, and keeps the legacy path as well.
Which makes this fairly convoluted but it gets pressure-vessel working on x86-64 host.
It's a bit tricky to setup but it does work.
Still some work necessary to get pressure-vessel working on AArch64 host, but I'm working on that.
=> Linux: Implements support for clone with namespaces 

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Primary/Primary_A4_REPNE.asm, unittests/ASM/Primary/Primary_A4_REPNE_Down.asm, unittests/ASM/Primary/Primary_A4_REPNE_many.asm, unittests/ASM/Primary/Primary_A5_REPNE.asm, unittests/ASM/Primary/Primary_A5_REPNE_Down.asm, unittests/ASM/Primary/Primary_A5_dword_REPNE.asm, unittests/ASM/Primary/Primary_A5_dword_REPNE_Down.asm, unittests/ASM/Primary/Primary_A5_qword_REPNE.asm, unittests/ASM/Primary/Primary_A5_qword_REPNE_Down.asm, unittests/ASM/Primary/Primary_A6_REPNE_Equal.asm, unittests/ASM/Primary/Primary_AA_REPNE.asm, unittests/ASM/Primary/Primary_AA_REPNE_down.asm, unittests/ASM/Primary/Primary_AB_dword_REPNE.asm, unittests/ASM/Primary/Primary_AB_dword_REPNE_down.asm, unittests/ASM/Primary/Primary_AB_qword_REPNE.asm, unittests/ASM/Primary/Primary_AB_qword_REPNE_down.asm, unittests/ASM/Primary/Primary_AB_word_REPNE.asm, unittests/ASM/Primary/Primary_AB_word_REPNE_down.asm, unittests/ASM/Primary/Primary_AC_REPNE.asm, unittests/ASM/Primary/Primary_AC_REPNE_down.asm, unittests/ASM/Primary/Primary_AD_REPNE_dword.asm, unittests/ASM/Primary/Primary_AD_REPNE_dword_down.asm, unittests/ASM/Primary/Primary_AD_REPNE_qword.asm, unittests/ASM/Primary/Primary_AD_REPNE_qword_down.asm, unittests/ASM/Primary/Primary_AD_REPNE_word.asm, unittests/ASM/Primary/Primary_AD_REPNE_word_down.asm, unittests/ASM/STOSQ2_REPNE.asm, unittests/ASM/STOSQ_REPNE.asm, unittests/ASM/STOS_REPNE.asm
MOVS, LODS, and STOS ops are only documented to support the REP prefix.
These instructions actually repeat correctly with the REPNE prefix as
well.
Behaviour is the same.
Fixes POD Gold
=>  OpcodeDispatcher: Implements undocumented repne on string ops

unittests/32Bit_ASM/Primary/Primary_CF.asm, unittests/ASM/Primary/Primary_CF.asm
Newer nasm takes the size specifier for LEA, older ones do not
=> unittests: Hotfix for older nasm

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
si_addr is set to the address that is trying to be accessed, not the RIP
that is trying to access it.
We just need to copy our host value over for this.
SIGFPE and SIGILL we still don't have a good answer for.
=> x86: Fixes siginfo_t si_addr for SIGBUS/SIGSEGV

Source/Tests/LinuxSyscalls/Syscalls/FD.cpp, Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x64/FD.cpp
A bunch of these were defined incorrectly. I tested a few of these
locally to ensure they were correct after the fact.
Shows that most 32-bit applications that we've encountered aren't
dealing with files larger than 4GB.
=> Linux: Fixes 32-bit syscalls that use 64-bit values

Source/Tools/FEXMountDaemon/Main.cpp
This allows FEXMountDaemon to remove FEXInterpreter as its parent.
Instead becoming the parent of whatever the current reaper process is.
Do it as early as possible this way FEXInterpreter won't get an
erroneous SIGCHLD.
=> FEXMountDaemon: Early fork to deparent child

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, unittests/ASM/Disabled_Tests_ARMv8.0
This implements unaligned CAS through the SIGBUS handler for ARMv8.0. It also rewrites the `OP_CAS` in the Interpreter to generate the pattern that can be detected by SIGBUS.
Fixes 0F_B0* tests for ARMv8.0.
=> Properly implement single CAS on ARMv8.0

Source/Tests/LinuxSyscalls/Syscalls/Timer.cpp, Source/Tests/LinuxSyscalls/x32/Timer.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/Time.cpp
getitimer and setitimer use an itimerval struct with 32-bit members in
it.
Handles this case and now the timers work
=> Linux: Fixes 32-bit interval timers

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/include/FEXCore/Core/UContext.h, Source/Tests/LinuxSyscalls/SignalDelegator.cpp
We were using the glibc context structure layout which doesn't match
what the kernel is doing.
Switches over to allocating fpstate independentally of the ucontext_t,
then pointing to it from uc_mcontext how we're supposed to.
glibc uses the __fpregs_mem region for other purposes.
This also fixes xmm state being stored on the 32-bit side, and also
fixes SIGALRM and SIGVTALRM siginfo overwriting structure data.
On 32-bit we can't just memcpy the siginfo_t over because the sizes
don't match. Throw a message instead.
=> Linux: Handle fpstate in the signal delegator correctly

Source/Tests/LinuxSyscalls/SignalDelegator.cpp, unittests/POSIX/Known_Failures
This flag is ignored with sigaltstack.
Fixes an early assert in:
- Splice
- No Time to Explain Remastered
- Ittledew
- Hyperdrive Massacre
- English Country Tune
=> Linux: sigaltstack ignore SS_ONSTACK

Scripts/StructPackVerifier.py, Source/Tests/LinuxSyscalls/CMakeLists.txt, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/FD.cpp, Source/Tests/LinuxSyscalls/Syscalls/Key.cpp, Source/Tests/LinuxSyscalls/Syscalls/Namespace.cpp, Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp, Source/Tests/LinuxSyscalls/Syscalls/Time.cpp, Source/Tests/LinuxSyscalls/Syscalls/Timer.cpp, Source/Tests/LinuxSyscalls/Types.h, Source/Tests/LinuxSyscalls/x32/EPoll.cpp, Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x32/Time.cpp, Source/Tests/LinuxSyscalls/x32/Timer.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/EPoll.cpp, Source/Tests/LinuxSyscalls/x64/FD.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Time.cpp, Source/Tests/LinuxSyscalls/x64/Types.h
A random smattering of 32-bit syscall fixes.
And adding of Namespace syscall handlers that I forgot to commit at some point.
=> Syscall fixes

Source/Common/RootFSSetup.cpp, Source/Tools/FEXMountDaemon/CMakeLists.txt, Source/Tools/FEXMountDaemon/Main.cpp
The FEXMountDaemon no longer uses the inotify interface for refcounting
instances of FEX.
The inotify interface fails to send close events when an application
crashes. Which is either an API oversight or intentional choice.
Now to use FEXMountDaemon the FEX process must send the daemon a pipe
fd.
The FEXMountDaemon then uses the write end of the pipe to determine if
the read end of the pipe is still open. It does this using the epoll API
and ref counting how many pipes are still active.
This is possible since epoll will tell us if pipe status has changed to
error. Signalling to the write end that the read end has closed for
whatever reason.
Now we only use the "lock" file to remove races and tell the new
instances of FEX where the rootfs is mounted
=> FEXMountDaemon: Fixes dangling mounts problem

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, unittests/ASM/Disabled_Tests_ARMv8.0
`SIGBUS` handler can now recognise the pattern generated by the JIT for `CASPair` on ARMv8.0.
Fixes the following tests:
* `Test_Secondary/09_XX_01_7.asm`
* `Test_Secondary/09_XX_01_8.asm`
* `Test_Secondary/09_XX_01_9.asm`
* `Test_Secondary/09_XX_01_11.asm`
* `Test_Secondary/09_XX_01_12.asm`
* `Test_Secondary/09_XX_01_13.asm`
NOTE: The interpreter tests for these never failed in the first place on my Cortex-A72, not sure what code clang/GCC emit for `std::atomic` that makes this the case.
=> Fix unaligned CASPair on ARMv8.0

Source/Common/RootFSSetup.cpp, Source/Common/RootFSSetup.h, Source/Tools/FEXGetConfig/Main.cpp, Source/Tools/FEXMountDaemon/Main.cpp
This solves a problem where sometimes FEX would spin up a new process
while FEXMountDaemon was in the process of shutting down. Breaking
things on both sides.
Now the race conditions are squashed that I could see.
=> FEXMountDaemon: Fixes shutdown race conditions

Source/Tests/FEXLoader.cpp
This was removed when we switched from FILE to raw fd.
This fixes an annoying issue where we would assert and not get any
output.
=> FEXLoader: Flush log output

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Config/Config.json.in, External/FEXCore/include/FEXCore/Config/Config.h, Source/Common/RootFSSetup.cpp, Source/Tests/FEXBash.cpp
In the case of running inside of a container then we need to redirect
where we look for configuration.
Currently we only care about pressure vessel so we just redirect some
options to check inside of `/run/host/`
This will resolve an issue where installed thunks wouldn't be found.
Fixes #1265
=> Config: Check for container-manager and redirect

Source/Tools/FEXConfig/Main.cpp
CTRL+A is used for selecting all in a text box.
Don't override that, it's annoying
=> FEXConfig: Change shortcut for opening application profile

Source/Tests/LinuxSyscalls/Syscalls/Info.cpp, Source/Tests/LinuxSyscalls/x32/Info.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/Info.cpp
32-bit versions of these syscalls saturate on the upper limit.
Depending on which syscall it'll saturate signed or unsigned.
With set if the 32-bit value is UINT32_MAX then it'll saturate to the
maximum 64-bit value
=> Linux: Fixes rlimit syscalls for 32-bit

Source/Tests/LinuxSyscalls/FileManagement.cpp, unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
wine walks the file structure to ensure the cwdir is safe for use. It
does this with a combination of `getcwd` and `statx`.
Once it reachs `/` then in rootfs environments it would fail to find
directories we've deleted.
Thus making it impossible to find folders like `/mnt` and `/home`
Should be safe since it just gives the application a larger world view
=> FileManager: Allow reading real root

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
Just to ensure these don't get truncated and intent
=> OpcodeDispatcher: Ensure some x87 templates get passed long constants

Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/Syscalls/Timer.cpp, Source/Tests/LinuxSyscalls/x32/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Timer.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/Time.cpp
Needed to fix rt_sigtimedwait to use the raw syscall.
Needed to have sigtimedwait and sigtimedwait_time64 parse siginfo_t
correctly.
glibc uses this to ensure it is sending the correct signal across from
their helper thread.
Needed to correctly parse sigval and sigevent for 32-bit.
Passes my unit test for timer_create
=> Linux: Implements support for timer_create

Source/Tests/LinuxSyscalls/Syscalls/Msg.cpp, Source/Tests/LinuxSyscalls/x32/Msg.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/Msg.cpp
These would have worked for 64-bit but wasn't working on 32-bit.
This now passes my unit test.
Relies on #1275 to be merged first.
Fixes #1260
Fun fact. strace when running a 32-bit application that executes mq_open, it fails to parse the mq_attr struct. Making seeing the arguments with strace pretty much entirely broken.
=> Linux: Implements support for POSIX message queues on 32-bit

External/FEXCore/Source/Interface/Core/Core.cpp
These variables are owned by other parts of the code, and AOTIR should not be freeing/deleting them.
=> AOTIR: fix use after free

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/IREmitter.cpp, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.h, External/FEXCore/Source/Interface/IR/Passes/RAValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h
This is a validation pass that attempts to prove the output from the RA pass is valid.
The current design should be able to prove that the RA result is internally consistent. That no-matter what control flow path you take thought the control flow graph, the physical registers and spill slots will always contain a single possible SSA value. 
It also checks that the SSA values in the IR actually line up with the SSA value in the physical register. 
~~It's one major blind spot is that it can't prove the spill slot contains the correct SSA.~~ Fixed by modifying FIllRegister to preserve a reference to the original SSA
=> RA validation

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
This makes debugging a bit more clear as to what is happening on crash
=> Interpreter: Changes basic loadstores to sized accesses

Scripts/StructPackVerifier.py, Source/Tests/LinuxSyscalls/x32/EPoll.cpp, Source/Tests/LinuxSyscalls/x32/Info.cpp, Source/Tests/LinuxSyscalls/x32/Msg.cpp, Source/Tests/LinuxSyscalls/x32/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Time.cpp, Source/Tests/LinuxSyscalls/x32/Timer.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/Semaphore.cpp
Fixes StructVerifier to correctly compare things annotated with `fex-match`.
Minor changes that came from it, but nothing really broken.
=> StructVerifier: Fix struct match and minor fixes

ThunkLibs/GuestLibs/CMakeLists.txt, ThunkLibs/HostLibs/CMakeLists.txt
Instead of searching inside the thunk folder for Guest and Host files
with a library name attached to it, also search for ones That are just
named `Host.cpp` and `Guest.cpp`.
Makes quickly pounding out a bunch of thunks significantly less tedious.
=> Thunks: Makes file searches a bit easier

Source/Tests/LinuxSyscalls/FileManagement.cpp, Source/Tests/LinuxSyscalls/FileManagement.h
This adds a new `ThunksDB.json` file to the config folder.
This file lets users describe thunks in a meaningful way without
duplicating it amongst multiple configuration files.
eg:
```
{
"DB": {
"GL": {
"Library" : "libGL-guest.so",
"Depends": [
"X11"
],
"Overlay": [
"/usr/lib/x86_64-linux-gnu/libGL.so",
"/usr/lib/x86_64-linux-gnu/libGL.so.1",
"/usr/lib/x86_64-linux-gnu/libGL.so.1.2.0",
"/usr/lib/x86_64-linux-gnu/libGL.so.1.7.0",
"/lib/x86_64-linux-gnu/libGL.so",
"/lib/x86_64-linux-gnu/libGL.so.1",
"/lib/x86_64-linux-gnu/libGL.so.1.2.0",
"/lib/x86_64-linux-gnu/libGL.so.1.7.0"
]
},
"X11": {
"Library": "libX11-guest.so",
"Overlay": [
"/usr/lib/x86_64-linux-gnu/libX11.so.6",
"/lib/x86_64-linux-gnu/libX11.so.6"
]
}
}
}
```
This file lets the user describe the library with an nicer name, in …
=> Thunks: Adds a new Thunks database config file

External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp
Noticed this while looking at the JIT
=> ALUOps: Fix left-over printf specifier in fmt log

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h, unittests/ASM/VEX/bextr.asm
Follows up the PR handling BMI1 ANDN (#1325), this adds handling for BMI1's BEXTR instruction
After this, all that remains is to add handling for BLSI/BLSMSK/BLSR. These are similar enough that I will likely include all of them in the following PR after this one.
=> OpcodeDispatcher: Handle BMI1 BEXTR

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/JITCore.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/include/FEXCore/Core/CPUBackend.h
Lets the compiler warn loudly when the result from any of these functions are left unused (indicating a bug).
This is primarily useful for the GetSrc/GetDst-related functions when making new IR op implementations, but the other cases are relatively useful for catching silent bugs introduced during refactors.
=> Core: Mark relevant Interpreter/JIT functions as [[nodiscard]]

External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp, External/FEXCore/Source/Interface/IR/IR.json
In a few parts of the OpcodeDecoder there's comments about making use of BIC. Given that, we can introduce the Andn IR operation that performs the same behavior as it.
I've named it `Andn`, since I feel it's more straightforward to read at a glance, but if it's preferable to name it `Bic`, I'm not opposed to changing it.
First time adding an IR op, so if anything looks wonky, just let me know and I'll fix it.
=> IR: Add handling for ANDN operations 

Source/Tests/LinuxSyscalls/x32/Time.cpp
This doesn't really change behaviour but makes sure we are consistent
=> Syscall: Fix 32-bit nanosleep always passing valid remainder

External/FEXCore/Source/Interface/Core/Interpreter/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp, External/FEXCore/include/FEXCore/IR/IREmitter.h, unittests/IR/Basic/MemoryData.ir, unittests/IR/Basic/Sbfe.ir, unittests/IR/Correctness/AddTruncate.ir, unittests/IR/Correctness/FPRStoreTruncate.ir, unittests/IR/Correctness/LeftShiftTruncate.ir, unittests/IR/Correctness/SubTruncate.ir
There's zero need for these to have an independent size field and it was
just confusing.
For stores it was always set to zero and for loads it was just
duplicated.
In addition this allows introspection of the store op without casting
the op, which can be useful in edge cases
=> IR: Fixes memory ops having a duplicate size field

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, External/FEXCore/Source/Interface/Core/Interpreter/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp, External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h
We can share this between the interpreter and the JIT. Necessary to
support the TSO-correct interpreter path.
With this change the interpreter is TSO-correct for GPRs. Just not FPRs
yet.
=> Arm64: Consolidate HandleSIGBUS

External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h, unittests/ASM/VEX/blsi.asm
PRing this separately from the other two, since this makes changes to the flag type in X86Tables to accommodate another flag
=> OpcodeDispatcher: Implement handling for BLSI

External/FEXCore/Source/Utils/Allocator.cpp, External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp, External/FEXCore/include/FEXCore/Utils/Allocator.h, Source/Tests/FEXLoader.cpp
Only a partial fix for #1330, still needs preemption disabled to work.
On x86-64 hosts the Linux kernel resides in the top bit of VA which
isn't mapped in to userspace.
This means that userspace will never receive pointers living with that
top bit set unless you're running a 57bit VA host.
This results in userspace pointers never needing to do the sign
extending pointer canonicalization. But additionally some applications
actually don't understand the pointer canonicalization.
This results in bugs like: https://github.com/golang/go/issues/49405
Now if you're running on a 57bit VA host, this will end up behaving like
FEX but it seems like no one in golang land has really messed with 57bit
VA yet.
In AArch64, when configured with a 48bit VA, the userspace gets the full
48bit VA space and on …
=> Allocator: Reserve upper 128TB of VA on 64-bit process

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h, External/FEXCore/Source/Utils/FileLoading.cpp, External/FEXCore/Source/Utils/FileLoading.h
CPUID lets the application know if it is running on a CPU with hybrid
CPU clusters.
This matches big.little fairly easily. Walk the affinity mask and
check if we are running on a big.little system and report it to the
guest.
For x86-64 host just pass through the flag.
=> CPUID: Adds support for hybrid flag

Source/Tests/LinuxSyscalls/SignalDelegator.cpp
We have been setting the host sa_flags to handle this for a while now.
So just pass the signals to the guest as expected
=> SignalDelegator: No longer do magic on SIGCHLD

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Vector loadstores were crashing. Now we emulate on load and backpatch on
store.
Store can't effectively emulate so it's better to backpatch.
=> Arm64: Fixes paranoid TSO mode

Source/Tools/FEXConfig/Main.cpp
glibc 2.34 changed the select interface to update the timeout on return
to more closely match the kernel interface.
glibc 2.33 always made a copy instead of updating.
Make sure to set the timeout on each iteration of select otherwise we
will end up having a timeout of zero. Thus burning a CPU core.
=> FEXConfig: Fixes timeout in select causing 100% CPU load

Source/Tests/LinuxSyscalls/FileManagement.h, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/NotImplemented.cpp
Ubuntu soft links a bunch of binaries in /usr/bin to softlinks that live
in /etc/alternatives/
When hitting any of these alternative softlinks execve would fail if the
host also didn't have the same softlink paths.
Allows us to correctly follow the symlinks on execve as well which fixes
launching wine directly from the wine symlink.
Alternatively you could have launched /usr/bin/wine-stable directly.
Also fixes FEX strace again.
=> Linux: Fixes execve on softlinks in rootfs

Source/Tests/LinuxSyscalls/FileManagement.cpp
Depending on how wine is launching it may do a PATH scan.
So we need to follow symlinks in a few more syscalls
=> Linux/FM: Follow more symlinks in emulation

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp, unittests/ASM/VEX/blsmsk.asm, unittests/ASM/VEX/blsr.asm
Implements the remaining two instructions to complete BMI1 support.
Now that everything is implemented we can also signify BMI1 support in our CPUID code.
=> OpcodeDispatcher: Implement BLSR/BLSMSK

Source/Tests/LinuxSyscalls/SignalDelegator.cpp
We were failing to update the emulated signal mask on return from
sigsuspend.
This was breaking Unity titles which was using sigsuspend and then
modifying the signal mask with sigprocaddr
=> Linux: SignalDelegator update signal mask on return from sigsuspend

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Allows expressing directly that we need the bit size instead of needing to repeat the operation in several places, given how common this is.
=> OpcodeDispatcher: Add helper for getting bit sizes

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp, External/FEXCore/include/FEXCore/Utils/EnumUtils.h
Makes them strongly typed so that invalid values can't implicitly be assigned to relevant variables
While we're at it, this adds helper utilities that make working with enum classes a little more convenient for avoiding boilerplate in regards to enum classes that can be used as flags. Now the relevant operations don't need to be defined long-form for every individual enum class.
=> OpcodeDecoder: Convert enums into enum classes where applicable

External/FEXCore/Source/Interface/Core/Frontend.h
This doesn't need to be constructed on a by-instance basis.
=> Frontend: Mark modrm function LUT as static

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp, External/FEXCore/include/FEXCore/Core/X86Enums.h
Previously, getting the offset of a register involved a long string of code via offsetof to get. We can wrap these behind two helper functions to make writing code that requires offsets a little more convenient
=> OpcodeDecoder: Shorten up GPR and MM base offset retrieval

External/FEXCore/Source/Interface/Core/ArchHelpers/MContext.h, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
When the context structure is adjusted in the signal handler then this
updates the state of the CPU on sigreturn.
We check to see if the RIP was adjusted and in this case we will update
the JIT in a potentially unsafe fashion.
This works well enough with signal handlers that effectively just long
jump and not much else.
Fixes wine initial prefix setup where rundl32 expects to do a try-catch
fault capture but infinite loops without this.
=> Dispatcher: Partial support for RIP adjust in signal handler

External/FEXCore/include/FEXCore/Utils/EnumUtils.h
These aren't strictly necessary for enum flags and through discussion in #1363, would lead to an awkward to use overload.
If these are ever needed, they can be discussed/added back at a later date.
=> EnumUtils: Remove shift operators from helper macro

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h
Amends the return size to handle a concern brought up by neobrain in #1362 
While we're at it, we can mark these helper functions as `[[nodiscard]]` to catch obvious bugs
=> OpcodeDispatcher: Amend return types of BitSize helpers

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterCore.cpp
Just resolves three unused variable warnings that cropped up over time
I've marked the guest_siginfo instances in the dispatcher as `[[maybe_unused]]`, since I wasn't sure if they were going to be used in the future. I can remove them entirely if they don't have any future use.
=> InterpreterCore/Dispatcher: Resolve unused variable warnings

External/FEXCore/Source/Interface/Core/Frontend.cpp, unittests/ASM/VEX/bextr.asm
These are equivalent to the REX prefix's RXB bits, except that they're in 1's complement form. These are trivial to handle and fix usages of the upper range of registers for ModRM encoded fields.
To ensure that we have coverage for existing possible usages, I've altered the BEXTR test to make use of R14 and R15.
=> Frontend: Handle VEX RXB bits

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h
C++, the language of the wrong defaults 🎉
This probably doesn't have significant impact, but it's an easy trap to avoid.
=> Dispatcher: Use std::vector as the underlying container for std::stack

Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x32/Msg.cpp, Source/Tests/LinuxSyscalls/x32/Semaphore.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.h, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x32/Time.cpp, Source/Tests/LinuxSyscalls/x32/Timer.cpp
Most of these were already marked for passthrough, just needed to be
enabled.
Some syscalls can be passed through but need to be renamed for 32-bit.
This adds another define which does that for us.
=> Linux: Passthrough 32-bit syscalls that can be

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h, External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Interface/Core/Interpreter/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/Source/Interface/IR/IRParser.cpp, External/FEXCore/Source/Interface/IR/Passes/DeadContextStoreElimination.cpp, External/FEXCore/include/FEXCore/IR/IR.h, unittests/IR/Basic/MemoryData.ir, unittests/IR/Basic/Sbfe.ir, unittests/IR/Basic/SetGPR.ir, unittests/IR/Correctness/AddTruncate.ir, unittests/IR/Correctness/FPRStoreTruncate.ir, unittests/IR/Correctness/LeftShiftTruncate.ir, unittests/IR/Correctness/SubTruncate.ir
Fixes #1217
Instead of throwing an error and closing down FEX. Instead pass the
SIGILL to the guest application.
On unhandled instruction implementation the instruction, we instead emit
a _Break IR op at that location.
A _Break IR op will ensure the context state is synchronized at the
point of of the fault and has fairly low overhead. We branch to the
dispatcher which does the SRA spilling.
Tested this with an application that attempts an AVX512 instruction,
catches the fault, and continues onward.
With #1383 in place, we also won't pass spurious ERROR_AND_DIE to the guest anymore.
=> FEXCore: Supports guest SIGILL 

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Utils/ForcedAssert.cpp, External/FEXCore/include/FEXCore/Utils/CompilerDefs.h, Source/Tests/FEXLoader.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.h
ERROR_AND_DIE was using __builtin_trap which would send our application
either a SIGILL or SIGTRAP depending on architecture.
This would then be captured by our faulting system and passed over to
the guest application.
If the guest application happened to have a signal handler installed for
these then it would pick up this fault and potentially continue
unsafely.
Now we can remove this usage of __builtin_trap and switch over to our
own handler.
Our frontend will check to see if the fault came from our handler and
uninstall the host signal handlers in this case. Which is what we want
for "ERROR_AND_DIE"
=> FEXCore: Fixes ERROR_AND_DIE

Source/Common/RootFSSetup.cpp
For some reason the full container path isn't actually setup right now.
Until this problem is resolved, keep the FEX rootfs configuration
around.
This lets applications still execute albiet still wrapped with the FEX
rootfs rather than the container's
=> RootFS: Keep rootfs around while in container

Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp
These maps are primarily used for debugging, so we don't need to construct and allocate the data until GetSyscallName() is called.
Eliminates a tiny bit of memory usage and a static constructor for release builds.
=> Syscalls: Move construction of syscall name map into GetSyscallName()

External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Interface/Core/CompileService.h, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/include/FEXCore/Core/CPUBackend.h
If a SIGBUS is received in compile service code then we weren't handling
it correctly. Instead we would fail the JIT space check and hand it off
to the guest.
=> JIT: Ensures signals in compileservice JIT space is handled

Source/Tests/LinuxSyscalls/LinuxAllocator.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x64/Memory.cpp
If MAP_32BIT was failing then we weren't checking error result
correctly.
This was causing us to crash.
Now add a helper function for checking syscall results since it is easy
to mess up.
Replaces the few cases where we were manually checking with the helper.
Fixes a Dota: Underlords crash
=> Linux: Fixes MAP_32BIT error case

External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Utils/Threads.cpp, External/FEXCore/include/FEXCore/Utils/Threads.h
The CompileService was spinning up with the incoming thread mask and
then setting the mask once running.
Instead set the mask, which the thread inherits, then set it back once
it is created.
=> FEXCore: Fixes CompileService race condition on thread creation

External/FEXCore/Source/Interface/Core/CompileService.cpp, External/FEXCore/Source/Interface/Core/CompileService.h, External/FEXCore/Source/Interface/Core/Core.cpp
Lets us simplify our GC management a little bit and also makes it so we won't potentially leak memory if an exception occurs anywhere.
=> CompileService: Store WorkItem instances as unique_ptr

External/FEXCore/include/FEXCore/Utils/BucketList.h
Minor changes to the BucketList to make it a little more flexible in terms of handling types
In particular, Append() and Erase() no longer assume a `uint32_t` type (it now uses the template type), and also allows using types that aren't direct primitive types with it.
=> BucketList: Minor API touchups

Data/AppConfig/steamwebhelper.json, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp
Fixes #1127
Finally.
I ended up taking the extremely long road on bisecting this, as I didn't validate that fcmp-eflag-bypass wasn't a culprit leading to me doing a full on bisection of steam, then proceeded to make a race condition bug in the bisection code, then went down the path of chasing that race in the guest code.
But, it's fixed. FIXED :D
Upside: We have amazing new tooling for bisections.
Will follow up with tooling PR
=> jit/arm64: COND_FGT should map to gt, not hi, as it is not FGTU

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp
We don't need to construct this every time this code is executed.
=> InterpreterOps: Mark F80CMP array as static constexpr

External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
A basic tidying up of cases where NodeIDs are passed around by repeatedly calling `ID()`. This will make it a little more convenient for turning the NodeID alias into a strong type in a followup, since it minimizes locations that need to be touched (making a review a little nicer).
=> RegisterAllocationPass: Reduce usages of NodeIDs where applicable

Source/Tests/FEXLoader.cpp
To get more information as to what intersected
=> FEXLoader: Print memory map when 32-bit intersect happens

Source/Tests/FEXLoader.cpp
Instead of early exiting, allow the application to continue running but
throw error messages anyway. Should allow some users to still run FEX
even if an application steals a page in the lower 32-bits
=> FEXLoader: Change 32-bit memory check error to warning

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterDefines.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/IR/IRDumper.cpp, External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp, External/FEXCore/Source/Interface/IR/Passes/IRValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RAValidation.cpp, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/IREmitter.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h, External/FEXCore/include/FEXCore/IR/RegisterAllocationData.h, External/FEXCore/include/FEXCore/Utils/BucketList.h
Converts the NodeID alias into a strongly-typed structure, which will allow catching attempts to pass NodeIDs into incorrect APIs at compile-time, which is a little bit better than passing around unlabeled primitive types that silently convert to one another.
=> IR: Convert NodeID into a strong type

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
Given the calls are all internal, we can store the function pointers directly and call them with the this pointer instead of indirecting through std::bind and std::function.
=> CPUID: Call handler functions directly

External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp
`try_emplace()` will return the existing entry in the map if it exists already, so we don't need to perform a `find()` and then `try_emplace()`. We can just use `try_emplace()` by itself and use the resulting inserted value (or existing one).
=> JIT: Eliminate redundant jump target map lookups

External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp
GetSSACount() returns a size_t, rather than a signed value.
=> RegisterAllocationPass: Resolve sign comparison mismatch in CalculateNodeInterference()

External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h
Some interface functions are just querying state, so we can allow them being used with const qualified data.
Also includes some other minor API-related changes
=> IR: Make some interface functions accept pointers to const 

External/FEXCore/Source/Common/JitSymbols.cpp, External/FEXCore/Source/Common/JitSymbols.h
Simplifies the format strings that get written out, making them a little nicer to visually parse
=> JitSymbols: Make use of fmt

External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, unittests/ASM/FEX_bugs/Test_CmpSelect_Merge.asm, unittests/ASM/FEX_bugs/Test_CmpSelect_Merge_Float.asm, unittests/ASM/FEX_bugs/Test_CmpSelect_Merge_Float_branch.asm, unittests/ASM/FEX_bugs/Test_CmpSelect_Merge_branch.asm
As a continuation to #1404, this was mapped to the incorrect Arm64 flags
Also adds the unit tests that were missing from #1404
=> Arm64: Fixes MapSelectCC FGT flag

External/FEXCore/Source/Utils/NetStream.cpp, External/FEXCore/include/FEXCore/Utils/NetStream.h
Given this is a private class, we can make it fully internal to reduce header dependencies on it in including code and also minimize files that need to be rebuilt if NetBuf changes.
=> NetStream: Move NetBuf definition into cpp file 

.github/workflows/ccpp.yml, .gitmodules, CMakeLists.txt, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h, External/FEXCore/include/FEXCore/Utils/InterruptableConditionVariable.h, unittests/APITests/CMakeLists.txt, unittests/APITests/InterruptableConditionVariable.cpp, unittests/CMakeLists.txt
Necessary to workaround a gdbstub hang on shutdown since regular std::mutex and std::condition_variable aren't reentrant safe.
=> Adds a new ReentrantMutex to use for FEXCore

Source/Tests/LinuxSyscalls/CMakeLists.txt
Enables warnings to keep the syscall code in sync with the warning settings used for FEXCore to ensure some bug classes don't manage to slip through
=> LinuxSyscalls: Enable warnings

Source/Tests/LinuxSyscalls/x32/Socket.cpp
Resolves some trivial sign-comparison warnings for `SendMsg` and `RecvMsg`.
This also fixes a potential case where a crash can occur due to the user sending through a message with a size of zero
=> x32/Socket: Resolve sign comparison mismatch cases

Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/Thread.cpp
Follows the previous PRs of using .data() instead of .at(0) to retrieve the buffer pointers.
=> {x32, x64}/Thread: Make use of .data() instead of .at(0)

External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ConversionOps.cpp, unittests/32Bit_ASM/FEX_bugs/InlineSyscall.asm
vixl has an assert check to ensure the register sizes are the same for
ubfm.
32-bit Inline syscalls hit this for both arguments and return value.
VCastFromGPR would have hit this but there aren't any x86 instructions
that move 8-bit and 16-bit values in to a vector register.
=> Arm64: Fixes vixl assertions around ubfm usage

External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/include/FEXCore/Core/Context.h
Several API functions act as state querying functions. These can take some parameters by const to communicate that we don't intend to modify the respective passed in instance (and also allow the API to be more flexible in how it's used)
=> Context: Take some arguments as pointer-to-const

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h, External/FEXCore/Source/Interface/Core/HostFeatures.cpp, External/FEXCore/Source/Interface/Core/HostFeatures.h, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/Interpreter/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MemoryOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryModRMTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, Source/Tests/HarnessHelpers.h, unittests/ASM/Disabled_Tests_host, unittests/ASM/SecondaryModRM/Reg_7_4.asm, unittests/ASM/SecondaryModRM/Reg_7_4_2.asm
Fixes #1081
This almost perfectly matches the `DC ZVA` instruction on AArch64.
Does some setup and checking to ensure feature bits align and then decides to expose the instruction in CPUID if things align.
=> Implements CLZero instruction

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.cpp, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/IR/AOTIR.cpp, External/FEXCore/Source/Interface/IR/AOTIR.h, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/IR/RegisterAllocationData.h, Source/Tests/FEXLoader.cpp
Specifically this tries to avoid changing much behaviour and keeping the
code the same. So most of it is a direct transplant without any
modifications. This is step one of the process so I can start logically
separating the code and making sense of it.
This mostly moves the AOT IR handling to its own independent file for
separation. Cleaning up the Core.cpp file quite heavily.
Two minor behaviour changes that got mixed up with this change.
The first one is an ASAN fix.
This is the FEX_PACKED on the RegisterAllocationData class.
I didn't want to change too heavily how this serialization works but I
wanted to resolve the ASAN error. This may change in the coming work.
Problem was the padding betwene the uint32_t and the PhysicalRegister
wasn't initialized but was being read.
Since it is all …
=> FEXCore: Reorganizes some AOT related code

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86DebugInfo.cpp
With these changes, `InstallOpcodeHandlers` only takes a fraction of the previous runtime:
* Replaces `std::vector` with arrays where possible
* Marks collections as `constexpr` to allow for better codegen
* Removes unneeded initialization code
=> Speed up initialization of X86Tables

External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, unittests/ASM/VEX/pext.asm
Handles one of the two remaining BMI2 opcodes. PDEP will follow after
=> OpcodeDispatcher: Handle PEXT

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/X86Tables/VEXTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, unittests/ASM/VEX/pdep.asm
Handles the last remaining BMI2 instruction, letting us signal full support for BMI2 within our emulated CPUID
=> OpcodeDispatcher: Handle PDEP

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h, External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/HostFeatures.cpp, External/FEXCore/Source/Interface/Core/HostFeatures.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp
Some of these were in the Emitter class and some were in the
HostFeatures.
Merge these together since in the future I'm going to be using all of
this data as a key for our AOT code cache.
=> HostFeatures: Consolidates HostFeatures flags

External/FEXCore/Source/Interface/Core/CPUID.cpp
If the CPU is unknown inside of the ARM CPU detection then the
MIDROption selected could have fallen down a path where it is set to
nullptr.
Resolve this crash by doing a nullptr check.
=> CPUID: Fixes crash on unknown CPU

Source/Tests/LinuxSyscalls/x64/Types.h
=> Linux: Fixes Ubuntu 20.04 compilation on AArch64

External/FEXCore/include/FEXCore/IR/IREmitter.h
This mask was subtracting backwards, which made anything smaller than 8
byte constants not mask correctly
=> IR: Fixes sized constant mask

External/FEXCore/Source/Interface/Core/HostFeatures.cpp, External/FEXCore/Source/Interface/Core/HostFeatures.h
On x86 this is always supported.
On ARM this is only supported if FPCR writes actually enable the things.
Also detects the AFP feature for flushing input denormals to zero.
These are all part of the x86 MXCSR.
No Cortex supports FPCR exceptions, while Apple M1 CPUs support
Exceptions but not the true "AFP" extension
Apple instead supports some additional flags in their
`SYS_APL_AFPCR_EL0` register for enabling this.
=> HostFeatures: Detect if the host CPU suports float exceptions 

Source/Tests/LinuxSyscalls/x32/Types.h
Fixes #1457
Header include order matters here. Rude.
=> Linux: Fixes build on Ubuntu 20.04 take 2

Source/Tests/LinuxSyscalls/x64/Types.h
Fixes #1457
Header is necessary for x64 types as well for struct verifier
=> Linux: Fixes build on Ubuntu 20.04 take 3

Source/Common/Config.cpp, Source/Common/Config.h, Source/Tests/FEXLoader.cpp, Source/Tools/CMakeLists.txt, Source/Tools/FEXRootFSFetcher/CMakeLists.txt, Source/Tools/FEXRootFSFetcher/Main.cpp, Source/Tools/FEXRootFSFetcher/XXFileHash.cpp, Source/Tools/FEXRootFSFetcher/XXFileHash.h
This tool supports both a zenity and tty interface.
TTY will be presented if available while Zenity will be used otherwise.
This tool pulls a rootfs list from https://rootfs.fex-emu.org/
It then allows you to select a rootfs from the list, download it, place
it in to the correct working folder, extract it if desired, and set it
as the current default RootFS.
This requires curl and potentially zenity installed to use.
Maybe also unsquashfs if the user chooses to extract the image.
This is an all in one tool to quickly get a new user up and running.
Additionally if you pass in a file path in to the tool, it will generate
an xxhash of the file and exit out. This is the hash used to ensure the
files are valid.
=> FEXRootFSFetcher: Adds a new tool to help set up a new RootFS

External/FEXCore/Source/Interface/Core/GdbServer.cpp
Fixes thread, memory-map, and OS data packet types.
These were attempting to substr when the encode function already handles
that.
Was making it so gdb was only ever receiving the first 1000 bytes of the
data and then decoding incorrectly.
=> GDBServer: Fixes long string packet encodings

External/FEXCore/Source/Interface/Config/Config.cpp
If set to an invalid Core option from the json file then sanitize it
back to JIT.
Otherwise FEX has a chance of just crashing.
=> Config: Sanitize Core option

External/FEXCore/Source/Interface/Config/Config.cpp, External/FEXCore/Source/Interface/Config/Config.json.in
We've solved the few threading problems that we had before. So now allow
FEX to query the host for the number of threads.
=> Config: Enables all host threads by default

Source/Tools/FEXRootFSFetcher/Main.cpp
So as to not confuse users who just copy and paste the hash without
thinking
=> FEXRootFSFetcher: Remove 0x prefix on hash

Source/Tests/LinuxSyscalls/CMakeLists.txt, Source/Tests/LinuxSyscalls/Syscalls/Namespace.cpp, Source/Tests/LinuxSyscalls/x32/FD.cpp, Source/Tests/LinuxSyscalls/x32/IO.cpp, Source/Tests/LinuxSyscalls/x32/Info.cpp, Source/Tests/LinuxSyscalls/x32/Sched.cpp, Source/Tests/LinuxSyscalls/x32/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Socket.cpp, Source/Tests/LinuxSyscalls/x32/Stubs.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x32/Types.h, Source/Tests/LinuxSyscalls/x64/IO.cpp
The main one that we can't implement is readdir. Falls in to the same
problem space as getdents.
With this, we have the full entry tables filled out for both 64-bit and
32-bit. With some holes in the implementation, we have almost all
coverage now.
=> Linux: Implements the remaining 32-bit syscalls

External/FEXCore/Source/Interface/Core/ArchHelpers/MContext.h, External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp, External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.h, External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/32Bit_ASM/Primary/Primary_CE.asm
This instruction is only available on 32-bit x86. On overflow flag set,
this instruction will raise a SIGSEGV with overflow exception set in
siginfo_t's si_code.
This implements the everything required to raise the signal and modify
our signal results that we are giving to the guest.
This is effectively the first step in generating signal frames with
custom data in it but only enough for INTO today.
This is enough for our unit tests doing non-faulting, and also a handwritten C test that recovers from the signal.
Fixes #929
=> FEXCore: Implements recoverable INTO instruction

Source/Common/RootFSSetup.cpp, Source/Tools/FEXMountDaemon/Main.cpp, Source/Tools/FEXRootFSFetcher/Main.cpp
Instead of using execve, use execvpe.
This glibc helper will search PATH or `confstr(_CS_PATH)`
Fixes #1475
=> Stop hardcoding /usr/bin paths

Source/Tests/LinuxSyscalls/Syscalls/Msg.cpp, Source/Tests/LinuxSyscalls/x32/Semaphore.cpp, Source/Tests/LinuxSyscalls/x32/Types.h
Implements the final ipc command, IPC_SET, and adds syscall documentation to msgctl.
Fixes #1253
=> Linux: Finish 32-bit msqid_ds usage

unittests/32Bit_ASM/CMakeLists.txt, unittests/ASM/CMakeLists.txt
The output asm folder needs to be created before the config file can be
generated. Otherwise the python script will fail.
=> unittests: Fixes a missing dependency on ASM tests

External/FEXCore/Source/CMakeLists.txt
This depends on Config. Then everything else links to this, pulling in
the dependency.
=> FEXCore: Fixes FEXCore_Base config dependency

CMakeLists.txt
By default we tune to the native CPU, using some heuristics to determine
the true native CPU since Apple doesn't expose an MIDR.
Adds an option that allows the user to pass in the CPU to tune for.
This will be useful for debugging and also for package building.
=> CMake: Adds a TUNE_CPU option

External/FEXCore/Source/Interface/Core/CPUID.cpp
When our FEX version string has less than 16 characters this would
result in size_t underflow, resulting in a crash.
This only ever occurs on a release tag so it went uncaught at first.
The PPA builder managed to uncover this problem since it only deals with
release tags.
Fixes #1483
=> FEXCore: Fixes a memcpy overflow in processor brand

CMakeLists.txt, External/FEXCore/CMakeLists.txt
This is intended to be used by a package maintainer to override the
version when the git repo or git executable isn't available.
Not expected to be used by normal users. Instead by our automated ppa
tooling.
=> CMake: Adds an OVERRIDE_VERSION option

External/FEXCore/Source/Interface/Core/CPUID.cpp
Just like the previous one, but this time when we are NOT on a release
=> CPUID: Fixes another memory overflow issue

External/FEXCore/Source/Interface/Core/Dispatcher/Dispatcher.cpp
This message can actually cause a perfectly running application to crash
due to signaling at the wrong time.
Instead constexpr disable it so if you want to see it. You can still
enable it
=> Dispatcher: Disables unsync context message

External/FEXCore/include/FEXCore/Core/UContext.h, Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Signals.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp
Due to the way this syscall handles siginfo_t, we only need to shift
data through the padding.
This is due to the syscall not allowing you to send siginfo_t with
si_code being positive. Which is what the kernel uses to interpret the
data if it is reinterpreting it.
=> Linux: Fixes pidfd_send_signal for 32-bit

External/FEXCore/Source/Interface/Core/Core.cpp, Source/Tests/LinuxSyscalls/SignalDelegator.cpp, unittests/POSIX/Known_Failures
Run() is expected to be used after a pause at this point.
Make RunUntilExit() notify using the StartRunning variable entirely.
This is because if we used Run() then the initial thread hasn't yet set
up its core or signal handlers. So it'll ignore SIG63. Then its reason
for pause is still set to Resume.
Once an application tries sending SIG63, we try restoring the context
from a paused state that does exist and crash
=> FEXCore: Don't use Run() inside RunUntilExit()

Readme.md, Scripts/InstallFEX.py
This is definitely a bit divisive but overall this is a win.
This is a user pattern that is emerging in a bunch of projects.
Allow an officially sourced script that lets you pipe a script directly
in to python/bash and setup the environment entirely.
This only supports Ubuntu {20.04, 21.04, 21.10, 22.04} which matches
exactly what we expose in the PPA.
Once this is in the repo, and our PPA is updated to the latest release
tag you can run this script like:
`curl --silent <Direct Github raw link> | python3`
Once the PPA is updated, the README and Wiki will be updated with Quick
Start guides to use this path.
The script steps
1) Checks if ARMv8, or fail
2) Checks if supported Ubuntu, or fail
3) Checks if PPA installed
3a) Install PPA if not, or fail
4) Check if packages are installed
4a) …
=> Scripts: Adds a python script that can hand hold a user through FEX install

CMakeLists.txt
I forgot about this option working for tuning arch on AArch64. This will
be used in PPA releases in the future. Will leave the previous option
since it can be used in testing.
=> CMake: Adds TUNE_ARCH option

Source/Common/SocketLogging.cpp
In the case that multiple messages appearing in a single packet then we
were repeating the first message and dropping any subsequent messages.
Fixes #1496
=> FEXLogServer: Stop duplicating and dropping messages

Source/Tests/LinuxSyscalls/FileManagement.cpp
Some syscalls support `AT_SYMLINK_NOFOLLOW` In these instances we need
to follow the symlink on a couple of syscalls.
Fixes executing wine using the basic wine path
eg:
FEXBash "wine dxcapsviewer.exe"
=> Linux: Fixes emulatedpath with symlink following

External/FEXCore/Source/Interface/Core/Interpreter/F80Ops.cpp, External/FEXCore/Source/Interface/Core/Interpreter/F80Ops.h, unittests/ASM/X87/DF_04.asm
Nothing really fantastical found here. Just that sub-precision results
weren't rounded correctly on store
Fixes #770
=> unittests: Adds a BCD unit test

Scripts/guest_test_runner.py, unittests/POSIX/CMakeLists.txt, unittests/gcc-target-tests-32/CMakeLists.txt, unittests/gcc-target-tests-64/CMakeLists.txt, unittests/gvisor-tests/CMakeLists.txt
cmake will bake in the environment variable in to the build scripts.
Instead have the guest_test_runner fetch it at runtime.
This means if you forget to set ROOTFS prior to running cmake, you can
now set it afterwards and rerun with just ctest instead of a cmake
dance.
Fixes #315
=> unittests: Fixes ROOTFS needing to be defined prior to cmake

Source/Common/SocketLogging.cpp
AssertHandler by default synchronizes but MsgHandler with Assert level
should also synchronize.
Fixes an issue where LogMan::Msg::AFmt wasn't syncing so the
FEXLogServer would never see the messages.
=> SocketLogging: Fixes MsgHandler not syncing with Assert level

External/FEXCore/Source/Interface/Core/CPUID.cpp
Needs to be a string_view for the MIDR for the StrConv helper to work in
this instance.
There is no null terminator character when reading from the file is why.
=> CPUID: Fixes ASAN problem with reading midr

Source/Tools/FEXRootFSFetcher/Main.cpp
Before doing anything that requires curl, actually check if it is
installed.
Then instruct the user to install curl before using.
Doesn't try installing curl itself since we don't have a clean way to
execute sudo from potentially GUI.
Fixes #1498
PPA installs already have a dependency on curl and will have it installed.
=> FEXRootFSFetcher: Check if curl is installed and fail before running

Source/Tests/ELFCodeLoader2.h, Source/Tests/FEXLoader.cpp
If the user passes in an absolute path then check to see if it exists in
the rootfs before executing.
Useful for launching applications directly out of the rootfs with
FEXInterpreter.
In the case that the absolute path doesn't exist in the rootfs then
fallback to the host system as usual
=> FEXLoader: Resolve the absolute path to rootfs if possible

External/FEXCore/include/FEXCore/Core/UContext.h, Source/Tests/LinuxSyscalls/Syscalls/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Signals.cpp, Source/Tests/LinuxSyscalls/x32/Thread.cpp, Source/Tests/LinuxSyscalls/x64/Signals.cpp
Just need to translate them between 32-bit and 64-bit versions.
Fixes #1254
=> Linux: Handles the remaining 32-bit siginfo_t usage 

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp, unittests/ASM/H0F38/66_17_2.asm
We were missing four flags that require setting zero.
=> OpcodeDispatcher: Fixes ptest flags calculation.

External/FEXCore/Source/Common/JitSymbols.cpp, External/FEXCore/include/FEXCore/Debug/X86Tables.h, Source/Common/SocketLogging.h, Source/Tests/IRLoader.cpp
Brings along a bunch of enhancements and ensures we always build against the latest version ([Changelog here](https://github.com/fmtlib/fmt/releases))
Also fixes up a few issues that arose due to changes in fmt to keep FEX forwards-compatible with it
=> externals: Update fmt to 8.1.1

External/FEXCore/Source/Interface/Core/JIT/Arm64/EncryptionOps.cpp
No need to do adr when loads can do a 1MB offset loadstore
=> AArch64: Single instruction optimization for AESKeyGenAssist

.github/workflows/ccpp.yml, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp
Updates vixl to the latest main branch.
Brings along a few API improvements and also access to SVE among other things.
Closes https://github.com/FEX-Emu/FEX/issues/1414
=> Externals: Update vixl

External/FEXCore/Source/Interface/Core/Interpreter/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IR.json, unittests/32Bit_ASM/Primary/Primary_E8.asm, unittests/32Bit_ASM/Primary/Primary_E8_2.asm, unittests/32Bit_ASM/Primary/Primary_E9.asm, unittests/32Bit_ASM/Primary/Primary_E9_2.asm, unittests/32Bit_ASM/TwoByte/0F_82.asm, unittests/32Bit_ASM/TwoByte/0F_82_2.asm
This cropped up mostly with multiblock and `jmp <signed displacement>`
This also happened with non multiblock `jcc <signed displacement>`
Due to how IR relocations occur, this needs to happen fairly late but
isn't a big deal.
Fixes #1517
=> JIT: Fixes signed displacement wraparound on 32-bit 

Source/Tools/FEXRootFSFetcher/Main.cpp
Makes curl do its continue feature to give the users the best chance of
downloading a rootfs. We don't need to restart the full file transfer on
failure. Helps people with slower connections.
On failure to download, asks the user if they want to retry the download
rather than just exiting with a weird error about hash failure.
Once the image is downloaded, now changes options depending on if
squashfuse or unsquashfs works.
Prevents the user from selecting a bad option and getting unexpected
behaviour. Ideally we would do a squashfs mount test as well for
platforms that don't have working FUSE, like termux. This is harder to
get right and its for an unsupported platform, so I'm not going to
invest more time with it.
Fixes #1525
Fixes #1526
Fixes #1527
=> FEXRootFSFetcher: Fixes some edge case behaviours 

External/FEXCore/Source/Common/SoftFloat.h, unittests/32Bit_ASM/Disabled_Tests, unittests/32Bit_ASM/Known_Failures, unittests/ASM/Disabled_Tests, unittests/ASM/Known_Failures
This isn't correct and breaks games.
This makes the FREM and REM1 implementation the same.
While not 100% correct, it is still better than before.
New issues will be created to handle the differences in the future.
Fixes #1374.
Also fixes most of the HL2 issues, just not the seam issue.
=> Softfloat: Stop doing special handling for FREM

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
We don't need to extract the element to compare it.
=> OpcodeDispatcher: Removes extraneous extract in VFCMP

CMakeLists.txt
Dynamically linking xxhash is causing problems with pressure-vessel.
With this in place we only have the typical C++ dependencies
```
$ ldd ./Bin/FEXLoader
linux-vdso.so.1 (0x00007fff44d9d000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4c4d884000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c4d7a0000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4c4d786000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c4d55e000)
/lib64/ld-linux-x86-64.so.2 (0x00007f4c4e0fa000)
```
=> CMake: Always use local xxhash to statically link

External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Flags.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp
This was mainly an optimization around memory usage. ALU ops tend to
bloat the IR quite heavily, but I also noticed a 2-4% uplift in
performance of some applications. So a nice side effect.
Should let us more aggressively target reducing our IR intrusive
allocator size since this is quite reduced.
In a pedantic heavy ALU op code block this reduces the number of IR ops
from 14,756 IR ops to 2,016 prior to optimization.
After optimization both had reduced down to 50 IR ops, proving the
output IR was the same.
=> FEXCore: Defer a significant number of ALU flag calculation

Source/Tests/LinuxSyscalls/x32/Types.h
Some build environments use a define to change stat64 and statfs64 to be
the same definition as stat and statfs.
Check if the define exists and if it does then remove the 64bit
constructors.
=> Linux: x32: Fixes tricky stat64 defines

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, unittests/ASM/Disabled_Tests, unittests/ASM/Disabled_Tests_host, unittests/ASM/Primary/Primary_8C_2.asm
Just noticed this while casually reading the x86 architecture manuals.
The move segment registers instructions ignore the REX.R prefix on the
segment register.
Previously this was expected to create an invalid register selection.
A little bit silly but sure, support it.
=> OpcodeDispatcher: Fixes weirdo edge case in segment moving

CMakeLists.txt, ThunkLibs/Generator/gen.cpp, ThunkLibs/GuestLibs/CMakeLists.txt, ThunkLibs/HostLibs/CMakeLists.txt, ThunkLibs/include/common/Guest.h
Previously, IDE engines couldn't parse the Host.cpp/Guest.cpp files of thunk libraries easily. This PR changes host libs to be built as part of the main project to enable parsing the former, and it adds a dummy copy of the guest libs project to enable parsing Guest.cpp.
=> Enable proper IDE integration of thunk libraries

Source/Common/RootFSSetup.cpp, Source/Common/RootFSSetup.h, Source/Tools/FEXGetConfig/Main.cpp
If the configured rootfs wasn't a squashfs then it was failing to return
the directory.
Now it works for both squashfs and directory rootfs again.
=> FEXGetConfig: Fix --current-rootfs option

External/FEXCore/Source/Utils/Threads.cpp, Source/Tests/ELFCodeLoader2.h
This is just a memory leak waiting to happen.
Only the primary thread in an application really should have this set
since the kernel cleans it up.
We only ever allocate the primary thread of the guest application then
every host thread's stack on top of that. It's up to the guest when it
is cloning to set up new stack pointers, we don't manage that.
We are already allocating the first thread's size at the soft stack
limit with RLIMIT_STACK anyway.
Fixes #1556
=> Removes MAP_GROWSDOWN usage

Source/Tests/ELFCodeLoader2.h
Fixes executing musl applications with the dynamic linker.
It was using the main executable's p_offset instead of the
interpreter's.
Wasn't a problem with glibc since it uses a different symbol to find the
base (Don't ask me why it does this).
musl dynamic linker on the other hand just uses AT_BASE directly and
since it was calculated incorrectly it was crashing.
Testing application was `ls` which had a p_offset of 0x40, so it would
try and read some values from AT_BASE, starting at an offset below where
it was mapped.
=> ELFCodeLoader: Fixes typo in AT_BASE calculation

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h
This is pulled from the code cache PR. Will be necessary for supporting
relocations.
Not currently being used but will be once we have code caching in place.
=> Arm64Emitter: Allow non-optimizing LoadConstant

unittests/32Bit_ASM/CMakeLists.txt, unittests/ASM/CMakeLists.txt, unittests/IR/CMakeLists.txt, unittests/POSIX/CMakeLists.txt
Would result in failures if you weren't expecting it.
=> unittests: Disables Interpreter tests when its disabled

External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Utils/MemberFunctionToPointer.h, External/FEXCore/include/FEXCore/Core/CoreState.h
These pointers are process or thread specific depending on which pointer
it is.
All of these pointers end up getting used inside of the JIT blocks
themselves and with code caching would result in a ton of relocations
occuring inside the code.
The pointers used within the dispatcher don't currently matter since I'm
not expecting to cache the dispatcher itself. It's only a page per
thread after all. This does move us significantly closer towards using a
single dispatcher for all threads though.
The performance impact of this change is unlikely to be felt at all,
some locations have less code generation which could improve perf
slightly. Some locations move from a 1-3 cycle constant calculation to a
4 cycle load, hard to be felt since it gets hidden by other
instructions.
x86-64 JIT will be …
=> ARMJIT: Switches over to loading pointers from state

External/FEXCore/Source/Interface/Core/Dispatcher/X86Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp, External/FEXCore/include/FEXCore/Core/CoreState.h
Just like the previous AArch64 JIT.
These pointers are process or thread specific depending on the pointer
and should be loaded from the State object.
Performance here might slightly increase.
This is required for code cache on x86
Needs https://github.com/FEX-Emu/FEX/pull/1574 merged first.
=> JITx86: Switches over to loading pointers from state

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterFallbacks.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/include/FEXCore/Core/CoreState.h
This allows x87 fallbacks to be loaded from the upcoming code cache
without relocations.
Only 40 pointers necessary to store and means x87 code won't hit
relocations heavily.
Probably improves performance slightly on the x86 host side but should
be neglible.
Needs #1574 and #1575 merged first.
=> JIT: Implements x87 fallback helpers as lookups in to state 

CMakeLists.txt, ThunkLibs/GuestLibs/CMakeLists.txt, ThunkLibs/HostLibs/CMakeLists.txt
Hosts were using the cmake install path with $DESTDIR which duplicates
paths.
GuestThunks were doing some magic that wasn't actually necessary
=> Fixes Host and guest thunks install path

FEXHeaderUtils/FEXHeaderUtils/Syscalls.h, Source/Tests/LinuxSyscalls/x32/Ioctl/asound.h, Source/Tests/LinuxSyscalls/x32/Ioctl/sockios.h, Source/Tests/LinuxSyscalls/x32/Ioctl/streams.h, Source/Tests/LinuxSyscalls/x32/Ioctl/usbdev.h, Source/Tests/LinuxSyscalls/x32/Socket.cpp
Following up the work previously done in 2079f6b3c7be81fd10546ecd978d41a8d7d6f685.
Adding more defines for older Linux uapi headers missing some defines.
Compiles properly now against l4t linux v4.9.140.
=> Improve compatibility with older uapi kernel headers

Scripts/aarch64_fit_native.py
Clang doesn't yet understand the latest ARM CPUs so just document them
and set to the closest thing.
=> Scripts: Updates CPU fitting script for latest CPUs

Scripts/aarch64_fit_native.py
According to PEP 386: https://www.python.org/dev/peps/pep-0386/
distutils is deprecated and will be removed in an upcoming python
version.
Switch over to pkg_resources for version parsing and comparison
=> Scripts: Stop using deprecated Distutils

External/FEXCore/Source/Interface/Core/CPUID.cpp, External/FEXCore/Source/Interface/Core/CPUID.h
This region is reserved for hypervisor uses. Let's follow other examples
and return a hypervisor vendor id signature as another way for software
to find if it is running under FEX-Emu.
=> CPUID: Implements leaf 4000_0000

External/FEXCore/Scripts/json_ir_generator.py, External/FEXCore/Source/Interface/Core/Interpreter/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/MoveOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/MoveOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/AtomicOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/MoveOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/X86Tables/SecondaryGroupTables.cpp, External/FEXCore/Source/Interface/IR/IR.json, unittests/ASM/Secondary/09_XX_01_14.asm, unittests/ASM/Secondary/09_XX_01_15.asm, unittests/ASM/Secondary/09_XX_01_16.asm, unittests/ASM/Secondary/09_XX_01_17.asm, unittests/ASM/Secondary/09_XX_01_18.asm, unittests/ASM/Secondary/09_XX_01_19.asm
The documentation is incorrect about this instruction. It claims that
you use 66h prefix to choose between operating at 8B or 16B.
This is incorrect, real hardware only responds to REX.W for choosing the
operating size. These other prefixes are ignored but is still accepted as
an instruction decoding.
This is based on #1603, only the final four commits are necessary here.
=> OpcodeDispatcher: Fixes CMPXCHG8B/16B with 66h/72h/73h prefix

docs/ReleaseProcess.md
FEX hardly works on Termux as-is, but we should make sure to document
how to update the packages otherwise we will quickly become outdated on
their package management.
=> Update ReleaseProcess docs for Termux

CMakeLists.txt, External/FEXCore/Source/Interface/IR/Passes/RegisterAllocationPass.cpp, External/FEXCore/Source/Utils/Allocator.cpp, External/FEXCore/Source/Utils/Allocator/64BitAllocator.cpp, External/FEXCore/Source/Utils/Allocator/IntrusiveArenaAllocator.h, FEXHeaderUtils/FEXHeaderUtils/TypeDefines.h, Source/Tests/HarnessHelpers.h, Source/Tests/LinuxSyscalls/LinuxAllocator.cpp
In the case of an AArch64 builder is using 16kb or 64kb pages like is
common on servers then it would fail to compile, even if the resulting
application would only ever run on 4k page hosts.
Resolve this by removing the build check and hardcoding 4kb pages for
each of our uses. We still require 4kb pages to run, so this mostly just
removes the weirdness where it is 16kb builder + 4k runner. Would have
broken some of our assumptions when running.
=> Change page define usages over to self-defined

CMakeLists.txt
This is necessary when cross-compiling rather than building on-device
=> Adds a cmake option for forcing a termux build

Source/Tests/LinuxSyscalls/LinuxAllocator.cpp
I accidentally committed a 32-bit range that was significantly smaller
than what it should be.
While the minimal range worked for simple cases, it didn't work for
anything complex.
Give it the full range it needs.
Fixes #1600
=> Linux: Fixes MAP_32BIT supported range

External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h
At the start of each code buffer, emit a small string for letting memory
inspection know if a code region is for the JITs.
=> JITs: Emit identification string in the code buffers

Readme.md, Source/Tests/LinuxSyscalls/FileManagement.cpp, docs/Readme_CN.md
This happend on debian buster when run realpath(i386) on arm64 host.
=> FileManager: Fix realpath failed on debian buster

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
This isn't used anywhere. Just remove these.
If we get the imgui debugger running again then we can add even more
stats to sort block costs by.
=> FEXCore: Removes unused debug data

External/FEXCore/Source/Common/SoftFloat.h, unittests/32Bit_ASM/Disabled_Tests, unittests/ASM/Disabled_Tests, unittests/ASM/X87/D9_FD_2.asm
I misread the implementation details of this instruction when
implementing.
The pseudocode says `ST(0) = ST(0) ∗ 2^rndint(ST(1))` so I understood
the instruction to use the current rounding mode of the host to extract
the integer portion of `ST(1)`.
The actual implementation is in the details of the statement `the
integer portion of the floating- point value in ST(1).`
This behaves like round towards zero/truncate, additional hardware
testing and documentation reading confirms this.
=> Softfloat: Fixes FSCALE

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/X87.cpp, unittests/32Bit_ASM/X87/DB_E3.asm
Was incorrectly setting the FCW to 037h when it was supposed to be
037Fh.
Fixes a bug in a visual novel where its CPUID state wouldn't initialize
if this was set incorrectly.
Thanks to risho on the Discord for pointing out the issue in the game!
=> OpcodeDispatcher: Fixes FNINIT

docs/CPUID.md
Currently we only implement function 4000_0000h. This will expand in the
future but this is all we have right now.
=> Documentation: Adds hypervisor CPUID information

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterClass.h, External/FEXCore/Source/Interface/IR/AOTIR.cpp, External/FEXCore/include/FEXCore/Core/CPUBackend.h
For the JIT cores we don't need to keep IR around, it's only necessary
for the Interpreter. So once the AOT IR service is done dealing with the
IR, check to see if we can delete it.
This causes teeworld's title screen memory usage to go from 730MB to
566MB. 77.5% the memory usage there.
This is effectively an infinite memory leak if the codespace wasn't ever
overwritten or invalidated. So larger memory usage programs would end up
having a larger impact.
=> FEXCore: Delete IR after it is used

External/FEXCore/Source/Interface/Core/HostFeatures.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, unittests/ASM/Disabled_Tests_x64
If the host doesn't support the instructions required for implementing
an instruction then don't even add them to the opcodedispatcher.
This means that we will never try emitting instructions that the host
doesn't support (For these instructions anyway) and successfully passes
the guest SIGILL for these particular instructions.
Fixes #1631
=> OpcodeDispatcher: Fixes SIGILL on unsupported host instructions

Scripts/aarch64_fit_native.py
Clang now supports these latest ARMv9 CPUs
=> Scripts: Updates AArch64 fit for Clang 14

External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/ALUOps.cpp, External/FEXCore/include/FEXCore/Core/CoreState.h
For 128-bit divides, we can very quickly check at runtime if we can
avoid the long divide and just do a 64-bit divide.
For unsigned just check if the top bits are all zero.
For signed just check if the top bits match bit 63 of the lower bits.
Additionally, keep the long divide handlers inside of the dispatcher.
This keeps the majority of the code bloat out of the code block itself,
significantly reducing block size for something doing these divides.
Also a fairly large icache improvement from this.
Hard performance number improvements here are hard to get since it
heavily depends on the application, also only occurs on x86-64.
Seems to have helped FTL and Dead Cells performance quite a bit though.
=> JITArm64: Get long divide out of the hot path

Source/Tests/FEXBash.cpp
This requires us to pass in --no-rc to bash since otherwise PS1 gets
overwritten by shell variables and nothing happens.
Which this is fine for the common use case of just wanting to run a
basic bash script under emulation.
=> FEXBash: Set PS1 to make it more obvious when running under FEX

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Frontend.cpp, External/FEXCore/Source/Interface/Core/Frontend.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/IR/IRParser.cpp, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/PassManager.h, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/IRCompaction.cpp, External/FEXCore/include/FEXCore/IR/IR.h, External/FEXCore/include/FEXCore/IR/IREmitter.h, External/FEXCore/include/FEXCore/IR/IntrusiveIRList.h, External/FEXCore/include/FEXCore/Utils/ThreadPoolAllocator.h, Source/Tests/IRLoader/Loader.cpp, Source/Tests/IRLoader/Loader.h
Creates a pool allocator for OpcodeDispatcher and IRCompaction that
shares memory allocations between threads in a pool and supports
reclaiming stale allocations from participating threads.
A thread will use a heuristic to keep its claimed memory allocation
around if it is allocating a lot of code. If it slows down then it will
start putting the memory allocation back in to the thread pool.
Additionally if the allocation has been "disowned" and gone to sleep
while still retaining the allocation, then another thread can inspect
these stale allocations and reclaim it from the idling thread. Saving
further memory.
This needs some more work and cleanup but this is an interesting concept
that saves a decent amount of memory even in a basic test.
Causes teeworlds' title screen to go from 754MB …
=> FEXCore: Reclaimable thread pool allocator

Source/Tests/LinuxSyscalls/LinuxAllocator.cpp
Split from #1558.
Adds missing lock to `MemAllocator32Bit::shmdt`, correctly handles errno return.
=> Linux/MemAllocator32Bit: Add missing lock to shmdt, fix error returns

Source/Tests/FEXLoader.cpp
Split from #1558.
Looks like this worked only when the directory was created, and not when it already existed.
=> FEXLoader: Fix create_directories check for aotir .path file writting

FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
Split off from #1558, allows us to return and pass around ScopedSignalMasks
- `ScopedSignalMaskWithSharedLock`, `ScopedSignalMaskWithUniqueLock`; similar to `ScopedSignalMaskWithMutex`
- Implemented move semantics so they can be passed around, similar to `std::lock_guard`, `std::shared_lock`, `std::unique_lock`
=> ScopedSignalMask: Add shared mutex support, move constructors

External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/Interpreter/BranchOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/BranchOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/LookupCache.cpp, External/FEXCore/Source/Interface/Core/LookupCache.h, External/FEXCore/Source/Interface/IR/AOTIR.cpp, External/FEXCore/Source/Interface/IR/IR.json, External/FEXCore/include/FEXCore/Core/Context.h, External/FEXCore/include/FEXCore/Core/CoreState.h, Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x64/Memory.cpp
Split off #1558, requires #1669.
Makes guest code invalidations context-wide by default, renames API from `Context::FlushCodeRange` to `Context::InvalidateGuestCodeRange`
- `LookupCache` has been updated to include a lock that is only ever contested on cross thread invalidations, and protects all writes and most reads from all structures, including `InternalThreadState::LocalIRCache` which is not part of LookupCache)
- Reads from `LookupCache` L1C are not protected by the mutex, and invalidations to L1C are done in a way that will likely tear without side effects. This needs to be validated & tested.
- Only invalidations of `LookupCache` may happen from another thread. All other operations are done from the owning thread.
- `FlushCodeRange()` has been changed to iterate over all threads …
=> Core: context-wide guest code invalidations

Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/Syscalls/Memory.cpp, Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x64/Memory.cpp
Split off #1558, requires #1670.
Centralises handling of calls to the memory manager.
- Added `FEX::HLE::SignalHandler::Track[Mmap/Munmap/...]()` (in the base class for both 32/64 handlers)
- Now all memory syscalls, both 32 and 64 bit, call `FEX::HLE::SignalHandler::Track[Mmap/Munmap/...]()` on success of these syscalls. This provides a cleaner and uniform api, and separates syscall implementations from VMA/Flushing logic.
=> Syscalls/Linux: Refactor guest mman tracking

Source/Tests/ELFCodeLoader.h, Source/Tests/FEXLoader.cpp, Source/Tests/HarnessHelpers.h, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x32/Syscalls.h, Source/Tests/LinuxSyscalls/x64/Memory.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.cpp, Source/Tests/LinuxSyscalls/x64/Syscalls.h, Source/Tests/TestHarnessRunner.cpp
Split from #1558, depends on #1671.
Introduces `FEXCore::HLE::SyscallHandler::GuestMmap` and `FEXCore::HLE::SyscallHandler::GuestMunmap` that do a guest-side mmap and munmap, as if it was done by the guest. Updated the rest of the code to use them.
Closes #1637.
- Added abstract api to `FEXCore::HLE::SyscallHandler`
- Implemented in `x64SyscallHandler` && `x32SyscallHandler`, in the corresponding Memory.cpp files.
- Modified `mmap`, and `munmap` syscall handlers to use the new handlers
- Modified `HandleBRK` to use the new handlers
- Modified the code loaders to use the new handlers
=> Syscalls/Linux: Add guest[Mmap/Munmap]

External/FEXCore/Source/Interface/Core/ObjectCache/Relocations.h
Pulled from #1548 with one of the unused relocation types removed.
Unused for now.
=> ArchHelpers: Adds relocation struct defines

External/FEXCore/Source/CMakeLists.txt, Source/Tests/LinuxSyscalls/CMakeLists.txt, ThunkLibs/GuestLibs/CMakeLists.txt, ThunkLibs/HostLibs/CMakeLists.txt
Not an expert on our build system, but I think I caught all cases we want this to be on for.
- FEXCore
- LinuxSyscalls
- Guest thunks
- Host thunks
Closes #1692.
=> CMake: C/C++ flags for defined singed overflow warping

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, External/FEXCore/Source/Interface/Core/HostFeatures.cpp, External/FEXCore/Source/Interface/Core/HostFeatures.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MemoryOps.cpp, External/FEXCore/Source/Interface/IR/PassManager.cpp, External/FEXCore/Source/Interface/IR/Passes.h, External/FEXCore/Source/Interface/IR/Passes/ConstProp.cpp
This allows us to have RCPC loadstore operations with a 9-bit signed
offset.
This gives us a small range of [-256,256) of immediate encoding range on
our TSO loadstore operations.
Updates the inline constant pass in ConstProp to support this range on
TSO IR ops if the host supports RCPC2.
Apple M1 supports this extension, didn't test with Cortex-X2/A710.
=> Arm64: Adds support for RCPC2 extension

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64Emitter.h, External/FEXCore/Source/Interface/Core/Dispatcher/Arm64Dispatcher.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/x64Relocations.cpp
The JITs currently don't use this. This is just the handling code
itself.
One line disabled in each JIT handling Guest RIP move relocations until the JIT
Object cache is enabled.
=> JIT relocation handling support

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/JIT.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/ObjectCache/JobHandling.cpp, External/FEXCore/Source/Interface/Core/ObjectCache/ObjectCacheService.cpp, External/FEXCore/Source/Interface/Core/ObjectCache/ObjectCacheService.h, External/FEXCore/include/FEXCore/Core/CPUBackend.h, External/FEXCore/include/FEXCore/Debug/InternalThreadState.h
Requires #1688 to be merged first.
First five commits commits are from that PR.
This hooks up the Code Object Cache service as a no-op implementation.
Exercising most of the external facing API to the class but all of the interfaces not yet doing any work.
=> Core: Adds Code Object Cache service 

External/FEXCore/Source/CMakeLists.txt, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/ObjectCache/CodeObjectSerializationConfig.h, External/FEXCore/Source/Interface/Core/ObjectCache/JobHandling.cpp, External/FEXCore/Source/Interface/Core/ObjectCache/NamedRegionObjectHandler.cpp, External/FEXCore/Source/Interface/Core/ObjectCache/ObjectCacheService.cpp, External/FEXCore/Source/Interface/Core/ObjectCache/ObjectCacheService.h
Requires #1690 to be merged first.
The first 11 commits are from that PR, only the final two are new.
This sets up the named region async job interface in a no-op fashion.
The async interface itself is exercised while the async thread that is supposed to do loading and storing of these objects is a minimum no-op implementation.
Next PR will be for having the async thread actually loading and storing these object files.
=> Object cache named region no-op implementation

FEXHeaderUtils/FEXHeaderUtils/ScopedSignalMask.h
Having three separate classes that essentially implement the same complex concept is cumbersome: It adds ambiguity to call-sites ("which of these should I use?") and wastes programmer time on looking for differences between the implementations. This isn't helped by us having to maintain the same docstring thrice, which hence hasn't seen as much love as the complexity of the concept deserves.
This change unifies the three separate classes we had before, allowing them to be documented more easily and clearly highlighting the difference of each specialization. For convenience at call-sites, the three names previously used are still available as specializations.
=> Clean up and document ScopedSignalMask

External/FEXCore/include/FEXCore/Utils/refcount_shared_mutex.h
This class is similar to std::shared_mutex except it is safe for the
same thread to increment or decrement the ref counter multiple times.
This can be passed to regular std locks.
This will be required with the code object cache service soon.
=> FEXCore: Adds refcount_shared_mutex class

External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp
x86 has eight instructions that are non-temporal.
Only one of which is a load-NT.
Adds a memory access type classification to our LoadSource/StoreResult
helpers.
This lets us explicitly choose Default, TSO, NonTSO, and Stream.
Stream currently just behaves like NonTSO so at some point in the future
we can add non-temporal loadstores to the IR.
Main thing is to move these NT accesses to non-TSO.
=> OpcodeDispatcher: Adds support for non-temporal loadstores

External/FEXCore/Source/Interface/Core/Core.cpp, FEXHeaderUtils/FEXHeaderUtils/TodoDefines.h
Proposal for #1696
clang-tidy already has support for detailed todo comments with the format
```
//TODO(details): comment
```
which seems to be the standardised google way to handle this.
I've defined ours as `FEX_TODO` and `FEX_TODO_ISSUE` for easier grepping.
Use like
- FEX_TODO_ISSUE(github ticket number, "comment")
- FEX_TODO("comment");
- FEX_TICKET(github ticket number)
- FEX_TICKET(github ticket number, "comment")
`#define FEX_WARN_TODO 1`  will generate warnings. That's arguably not very useful as one can just grep for `FEX_TODO`.
Thoughts?
(Closes #1696)
=> Standarized TODO markers: FEX_TODO, FEX_TODO_ISSUE

External/FEXCore/Source/Interface/Core/X86Tables/BaseTables.cpp
Run into this while debugging on `skmp/guest-rt_sigreturn`. Fixes the X86Tables entry for `leave`
=> X86Tables: Leave shouldn't end block

Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/Syscalls/Thread.cpp, Source/Tests/LinuxSyscalls/Syscalls/Thread.h
clone2 stack pointer passed in points to the highest address for the
stack.
clone3 switches this around and gives us a base pointer and a size.
glibc started using clone3 for its thread cloning which finally caught
this bug. Necessary to run any application under the Ubuntu 22.04 rootfs
since that uses a new enough glibc to encounter this.
=> Syscalls: Fixes clone3 stack pointer

Source/Tools/FEXRootFSFetcher/Main.cpp
While our CDN supports download continue, the backblaze storage backing
does not.
=> FEXRootFSFetcher: Don't continue download

Source/Tools/FEXRootFSFetcher/Main.cpp
Fixes a regression in fa87c73b9ee60a334eace2cdc3097725cbaf5b88; curl complains "curl: option -: is unknown" when trying to fetch a RootFS without this.
=> Fix dangling curl hyphen

External/FEXCore/Source/Interface/Core/OpcodeDispatcher/Vector.cpp, External/FEXCore/Source/Interface/Core/X86Tables/H0F3ATables.cpp, unittests/ASM/H0F3A/66_14_2.asm
Previously if the instruction was encoded to use rsp, rbp, rsi, or rdi
then due to how these were encoded in modrm this would hit the frontend
path for writing to the high 8 bits of a 16bit register.
This is because it's instruction specific if an 8-bit modrm instruction
chooses to use the high 8-bit region or the upper 4 registers.
See the ModRM.reg section of `ModRM.reg and .r/m Field Encodings`
specifically to see what each encoding stands for. Has four different
meanings per encoding depending on instruction.
This instruction doesn't actually write to registers at 8-bit size, it
extracts an element at 8-bit size and then zero extends it to the full
GPR.
When storing to memory it always stores to memory at the size of the
element extracted.
I grepped around the instruction tables to …
=> OpcodeDispatcher: Fixes pextrb with high registers

External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.cpp, External/FEXCore/Source/Interface/Core/Interpreter/InterpreterOps.h, External/FEXCore/Source/Interface/Core/Interpreter/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/Arm64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/Arm64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/JIT/x86_64/JITClass.h, External/FEXCore/Source/Interface/Core/JIT/x86_64/MiscOps.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.cpp, External/FEXCore/Source/Interface/IR/IR.json, unittests/ASM/Primary/Pause.asm
The pause instruction is architecturally defined to be the `REP NOP`
instruction.
This allows people to use this instruction as a backwards compatible
pause without checking for CPUID support. In fact there is no way to
check if the hardware implements this as a `REP NOP` or a `PAUSE`.
If you have new enough hardware then this just ends up being a PAUSE.
Pass this PAUSE over to our host to help out applications that are
writing spin loops with a PAUSE in it, which we were deleting
previously.
=> OpcodeDispatcher: Implements support for PAUSE 

Data/AppConfig/steamwebhelper.json, External/FEXCore/Source/Interface/Config/Config.json.in, Source/Tests/ELFCodeLoader2.h
Steam's webhelper has started enabling its sandbox which completely
breaks under FEX since we don't support seccomp.
Curiously the Chromium code is actually supposed to support a fallback
namespace only mode, which is used in glibc 2.34 environments.
The startup script for this will try to use this namespace only mode,
but Chromium developers never tested this in an environment that doesn't
support seccomp.
Due to an early check in their sandbox code, it checks for bpf support
before checking for which sandbox mode it is entering. This returns
early with a false statement which brings the entire browser instance
down with an assert.
Inject the --no-sandbox argument so we get around this and the sandbox
is disabled.
=> AppConfig: Inject --no-sandbox in to steamwebhelper

.github/workflows/ccpp.yml, Source/Tests/LinuxSyscalls/CMakeLists.txt, unittests/ASM/Disabled_Tests_ARMv8.0, unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
Runners have been updated which have caused unit tests to start failing in new interesting ways.
Work around these, will create issues to do a followup on the failures.
=> unittests: Workaround runner issues

External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/include/FEXCore/HLE/SyscallHandler.h, Source/Tests/IRLoader.cpp, Source/Tests/LinuxSyscalls/Syscalls.h, Source/Tests/LinuxSyscalls/SyscallsSMCTracking.cpp, Source/Tests/LinuxSyscalls/x32/Memory.cpp, Source/Tests/LinuxSyscalls/x32/Semaphore.cpp
- Fixes 32-bit shmat, shmdt tracking when called through ipc syscall, that path missed before.
- Adds an extra lock to guarantee that invalidations happen either before or after a block has been compiled, but never during compilation. It is still possible to compile stale code if the code gets modified while being compiled, as the mprotect locks are only applied after successful compilation.
Both of these corner cases were uncovered by the FLT PR, #1737
A shared mutex is used so that there is no contention penalty while there are no invalidations.
Locking pattern
- Around Compilation  -> lock shared
- Around Invalidation -> lock unique
=> mtrack: Fixes 32-bit shmat, shmdt tracking, guaranteed invalidation atomicity

.github/workflows/ccpp.yml, Source/Tests/LinuxSyscalls/CMakeLists.txt, Source/Tests/LinuxSyscalls/x32/Ioctl/drm.h, Source/Tests/LinuxSyscalls/x32/IoctlEmulation.cpp, Source/Tests/LinuxSyscalls/x64/Ioctl/drm.h
Multiple problems here.
System drm headers were being used instead of our provided external ones. Not sure when this broke but must have been at least half a year.
Fixed definition of a v3d ioctl, which has its own problems but as far as I currently understand, it's an ABI break.
Fixes #1740
=> Struct verifier fixes and reenable

unittests/gvisor-tests/Disabled_Tests, unittests/gvisor-tests/Known_Failures
One gvisor test didn't expect a file header to change layout.
Another one was testing behaviour that was removed from upstream Linux
Fixes #1741
=> unittests: Investigate failing CI changes

External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.cpp, External/FEXCore/Source/Interface/Core/ArchHelpers/Arm64.h, unittests/ASM/Disabled_Tests_ARMv8.0
The latest ARMv8.0 toolchain is implementing fetch_add with a bic rather
than an and. Not sure why they started doing this but support the
remaining logical operations in our unaligned atomics handler.
Fixes the Interpreter ARMv8.0 atomic ops.
Fixes https://github.com/FEX-Emu/FEX/issues/1742
=> unittests: Reenable atomic tests on ARMv8.0

External/FEXCore/Source/Interface/Config/Config.json.in, External/FEXCore/Source/Interface/Context/Context.h, External/FEXCore/Source/Interface/Core/Core.cpp, External/FEXCore/Source/Interface/Core/OpcodeDispatcher.h, External/FEXCore/include/FEXCore/Core/Context.h, Source/Tests/LinuxSyscalls/Syscalls.cpp, Source/Tests/LinuxSyscalls/SyscallsSMCTracking.cpp
Single threaded applications that don't use shared memory don't need TSO to be enabled. This is often the case with many command line applications like `bash`, `uname`, most executions of `python/3` and many others.
For those cases, we can generate non-tso code, and switch to tso mode once they might do shared memory operations.
This introduces a new configuration, `TSOAutoMigration`, that controls this optimisation and is by default enabled.
This optimisation was inspired by qemu, that also implements the same optimisation.
- Adds `TSOAutoMigration:bool=true` configuration
- Adds `void Context::MarkMemoryShared()` that does the migration and sets the `Context::IsMemoryShared` flag
- Adds `void MarkMemoryShared(FEXCore::Context::Context *CTX)` wrapper
- Adds `bool Context::IsTSOEnabled()` …
=> TSO: Add auto migration optimisation for applications that don't need TSO

External/FEXCore/Source/Interface/Core/CPUID.cpp
This was originally set to zero out of concern for any application that
is doing anti-emulation, anti-cheat, anti-VM checks.
This concern is likely unwarranted, and if any application/game starts
hitting this as a problem then we can throw an application profile at it
instead.
This makes pressure-vessel emulation checking more optimal by it not
having to do a uname dance.
=> CPUID: Enable the hypervisor bit
